### ISSUE TITLE
dagger packages' inputs not printed inside computed for loops

### ISSUE THREAD

**Issue by grouville** [dagger/dagger#1026]
### Context

Dagger packages could be summarized as a collection of definitions that receive external informations via inputs, and computes them. 

These inputs are being injected inside the Cue tree at runtime.

In order to differenciate an input from a generic key, we specify the ones requiring an external source of information with the `@dagger(input)`  annotation or the `dagger.#Input` definition.

These Cue keys (the ones marked with annotations) are being converted at runtime when the generated AST is being parsed.

### Issue

The `dagger input list` command  also parses the AST for the CLI to show the list of keys the user has to set prior interpreting a Cue configuration (via a `dagger up`).  If these inputs are not set inside the `values.yml` file, the pipeline won't become entirely concrete at runtime, and only parts of the dag will be executed.

The above parsing only happens on static values: all the computed ones are being skipped.

This is an expected behavior, but it brings a certain amount of issues/questions.

## Repro case

In order to have a common ground, you will find below the current behaviors that will serve as a postulate.

<u>Working example</u>

```cue
// file="~/dagger-repo/main.cue"
package test

import(
	"alpha.dagger.io/dagger"
	"alpha.dagger.io/js/yarn"
)

jsonValue: dagger.#Input & {dagger.#Artifact}

out: {
	"key": yarn.#Package // contains a `source` key, which is an input
}
```

> <u>Output</u>
>
> ```// Bash output:
> $  dagger input list
> Input           Value             Set by user  Description
> jsonValue       dagger.#Artifact  false        -
> out.key.source  dagger.#Artifact  false        Application source code
> ```

With the above configuration, the `out.key.source` is being outputed as a missing input key.

<u>Non-satisfying example</u>

```cue
// file="~/dagger-repo/main.cue"
package test

import(
	"alpha.dagger.io/dagger"
	"alpha.dagger.io/js/yarn"
)

jsonValue: dagger.#Input & {dagger.#Artifact}

out: {
	[string]: yarn.#Package

	for key, _ in jsonValue {
		"\(key)": yarn.#Package // Input still not specified
	}
}
```

><u>Output</u>
>
>```cue
>$ dagger input list
>Input      Value             Set by user  Description
>jsonValue  dagger.#Artifact  false        -
>```

As the `for` loops relies on `jsonValue`, which is injected at runtime. The `dagger input list` command only sees it as an empty object and thus, doesn't print the input as missing.

## What are the implications ?

This implies that any inclusion of definitions scoped inside a `for` loop on a computed value won't show the missing inputs of the given definition.

<u>Current solution</u>

Wrapping the loop inside a bigger definition/key in which we copy the hidden inputs from the `yarn.#Package`

```
package test

import(
	"alpha.dagger.io/dagger"
	"alpha.dagger.io/js/yarn"
)

jsonValue: dagger.#Input & {dagger.#Artifact}

wrapper: {
	src: dagger.#Input & {dagger.#Artifact}
	otherMissingKey: dagger.#Input & {string} //example

	out: {
		[string]: yarn.#Package

		for key, _ in jsonValue {
			"\(key)": yarn.#Package & {
				source: src
				if otherMissingKey != _|_ {
					missingKey: otherMissingKey
				}
			}
		}
	}
}
```

> <u>Output</u>
>
> ```cue
> $ dagger input list
> Input                    Value             Set by user  Description
> jsonValue                dagger.#Artifact  false        -
> wrapper.src              dagger.#Artifact  false        -
> wrapper.otherMissingKey  string            false        -
> ```

#### Open questions

> This doesn't seem scalable:
 what if, inside the `for` loop, I want to include not one but ten definitions that all have unset dagger inputs ? 

*Will I have to copy all of them as I just did above ?*
It not only doesn't seem sustainable (as this would imply to create two sources of truth), but it also would be a horrible DX.

**Comment by shykes** [comment]
This is specific to 0.1.
