### ISSUE TITLE
Git packages don't check that .git dir is present

### ISSUE THREAD

**Issue by grouville** [dagger/dagger#1034]
Most of Git packages don't check that the `.git` is present, leading to unclear error messages.
Most of the packages should test this condition or at least fail cleanly if that's the case.

Packages related to this issue:
- `#CurrentBranch`
- `#Tags`
- `#Commit`

There are two points of failure, as there are two ways to add a Git repository
* The user inputs a git dir that doesn't have a `.git` inside (generally, that's when a git repo references another git repo)
* The user uses the `git.#Repository` package without the `keepGitDir` bool set to true

**Comment by shykes** [comment]
Is this issue still relevant in 0.2?
