### ISSUE TITLE
Inline actions

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#1254]
## Problem

Dagger does not detect actions configured in an inline CUE expression. This makes a useful feature of CUE unavailable to Dagger developers, causing configurations to be more complex than necessary. This becomes more problematic as the size of a configuration grows.

## Details

Most of the time, actions are assigned to a field in the CUE configuration, for example:

To execute an action in their DAG, a developer must write the action’s configuration as a CUE value, and assign that value to a field  within the top-level `actions`. For example:

```
actions: {
  // Execute a build action
  build: docker.#Build & {
    // …
  }
  // Use the output of the build
  image: build.output
}
```

As configurations grow in size and complexity, intermediary fields can be skipped by using *inline expressions*. For example:

```
actions: {
  image: {
    docker.#Build & { … }
  }.output
}
```

In both examples, the CUE evaluator will consider `image` to have the same value. But will the build action be executed in the second example? Currently the answer is no, because Dagger does not support inlined actions: actions configured in an inline CUE expression are not detected, and therefore not executed.

## Solution

Improve the engine implementation to detect inline actions. This presents implementation challenges: the underlying `cueflow` package does the heavy lifting of action detection, and it does not support inline expressions.

One important thing to keep in mind: we don’t necessarily need to support all possible inline CUE expressions. If it makes implementation easier, even supporting the basic form `<action struct literal>.<field>`, with only one level of depth, would be a major improvement to DX. Perhaps this could be implemented in the cueflow task handler (since there would be at most one task), rather than requiring modifying cueflow itself.

**Comment by jlongtine** [comment]
This will definitely require changes to `cue/tools/flow`. I think it's very much worth exploring, because I agree that it will make writing some plans/packages quite a bit cleaner.

**Comment by shykes** [comment]
cc @verdverm do you think this can be done? 😇

**Comment by verdverm** [comment]
I agree with @jlongtine that this generally requires the nested task detection that upstream is considering

There are also many cases where you need to use intermediate fields when importing tasks (actions). This probably requires upstream changes from talking with @mpvl (there are threads on cue github)

**Comment by shykes** [comment]
> I agree with @jlongtine that this generally requires the nested task detection that upstream is considering
> 
> 
> 
> There are also many cases where you need to use intermediate fields when importing tasks (actions). This probably requires upstream changes from talking with @mpvl (there are threads on cue github)

Are you still developing an alternative cueflow implementation? Do you think we should consider doing that?

**Comment by verdverm** [comment]
@shykes No, I built on top of `cue/flow` and have the same issue. I'm not sure how easy an alternative implementation is today. In particular the dependency resolving functions make use of internal functions and info. I decided to wait for this to be handled upstream during the rewrite.

**Comment by mircubed** [comment]
@jlongtine Just checking in for an update. Let me know if you need additional support for this one

**Comment by verdverm** [comment]
This is probably the CUE issue to keep an eye on: https://github.com/cue-lang/cue/issues/1325

I suspect that many changes to cue/flow will happen as a part of this change (epic?)

**Comment by Nannapaneni** [comment]
Sorry it was an accident
