### ISSUE TITLE
support rootless mode?

### ISSUE THREAD

**Issue by edwintorok** [dagger/dagger#1287]
One of the install steps here shows how to use 'sudo' to install it: https://docs.dagger.io/1001/install/
That shouldn't be needed, lately I use containers that run in rootless mode (e.g. `podman` instead of `docker` and a wrapper that calls `podman` instead of `docker` for backwards compat, or `runc`, etc.), and a rootful docker may simply not be available in certain environments as a matter of security policy.

Therefore it'd be very useful if the `sudo` installation mode would be optional and `dagger` could run fully featured in rootless mode.
i.e. it'd be very nice if `dagger` was `rootless` first (sort of how you develop your applications cloud first, etc.)
I haven't tried yet whether this'd be possible by using the 'install from source' method, but the documentation doesn't mention `rootless` at all.
 
See https://rootlesscontaine.rs/ for various ways of running rootless containers (docker can do it too, although none of the distros I use have actually packaged the rootless mode of docker).

There is also some information here on how to use BuildKit with podman that might prove useful in integrating into dagger's docs: https://pythonspeed.com/articles/podman-buildkit/

**Comment by kajogo777** [comment]
I want to run dagger inside Kubernetes, is it possible to build and run containers without needing access to the docker socket/being privileged?

**Comment by kajogo777** [comment]
I am trying to run dagger inside a Kubernetes pod.

just to make sure I understand, it is not currently possible to run dagger without dind and access to docker sock?

**Comment by gerhard** [comment]
> it is not currently possible to run dagger without dind and access to docker sock?

Dagger v0.2 dependency is BuildKit. By default, it uses Docker to provision it, but this can be customised: https://docs.dagger.io/1223/custom-buildkit/#using-a-custom-buildkit-daemon

If you need to use Docker functionality, e.g. https://github.com/dagger/dagger/tree/main/pkg/universe.dagger.io/docker, then you will need access to Docker. Docker can run remotely, outside of K8s.

**Comment by rubin55** [comment]
@gerhard could you elaborate a bit? We're in the process of evaluating Dagger and Earthly and we're in a large-scale enterprise environment that won't allow privileged containers. Can you be more explicit, i.e, is DinD a hard requirement and so you really need to have a separate, dedicated env for it so as to alleviate/work-around the privileged container issue?

Essentially, at least in our case, we have a gitlab environment with gitlab-runner on a dedicated docker 3-node cluster (using portainer) where we have no privileged container option, which targets a kubernetes environment where we also can't run privileged containers. Does that mean using dagger (or earthly for that matter, as they also depend on BuildKit) is impossible in this scenario (and you would need to create a dedicated privileged containers-enabled environment)?

**Comment by mircubed** [comment]
Adding discord thread of additional users who need this -https://discord.com/channels/707636530424053791/1050357740528205824

**Comment by rubin55** [comment]
@mircubed how do you access that discord link? When I click it, my  discord client shows an empty page saying "No text channels".

**Comment by pmengelbert** [comment]
I'm using the rootless setup provided by docker, it hangs indefinitely on importing/exporting files from the containers

**Comment by dispensable** [comment]
Hi, can dagger support rootless mode right now ? I find the docs of this is very confusing. After trying all the settings (rootless podman + sdk / k8s buildkit + sdk /kus buildkit with privilege + sdk) seems rootless is still not possible ?

**Comment by TomChv** [comment]
@dispensable You should have a look at this part of our [doc](https://docs.dagger.io/541047/alternative-runtimes/#requirements-1), you might be able to use rootless with a custom OCI runtime like `nerdctl`
