### ISSUE TITLE
Support long-running execution

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#1337]
[Certain use cases of Dagger](#1258) require supporting long-running execution: running a DAG that will never terminate. This is different from today, where `dagger up` is expected to terminate, and might be force-terminated and return an error after a timeout period.

How do we support long-running execution without breaking support for regular, short-running execution? How do we allow both execution modes to co-exist, in a way that makes sense to the developer and the end-user?

**Comment by sipsma** [comment]
@samalba Technically `core.#Start` still requires setting a maximum timelimit on how long you will wait for the process before forcibly stopping it, but that can be set to arbitrarily high numbers and the underlying implementation has no inherent limit on how long to wait. So I'll close this, when we need to add support for a use case that requires literally indefinite waiting (i.e. https://github.com/dagger/dagger/issues/1258) then it will be trivial and won't require a dedicated issue like this.
