### ISSUE TITLE
Persist cache volumes on CI

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#1345]
Cache volumes (also known as `core.#CacheDir` in the 0.2 CUE SDK), uses the `llb.AsPersistentCacheDir()` call, the same that's used in Dockerfiles for e.g. `RUN --mount=type=cache,target=/var/cache/apt `.

The persistent cache dir is stored internally in BuildKit, which works great locally, however it's not persistent across CI runs (because we get a different BuildKit instance each time).

Ideally we should find a way to persist BuildKit's persistent cache directories into GH's cached directories.

A starting clue to figure this out is look into how people are solving the problem in Dockerfiles using `--mount=type=cache`.

/cc @samalba

**Comment by TomChv** [comment]
I'm closing this issue since Dagger cloud actually fix this issue with a persistant cache across run
