### ISSUE TITLE
Missing input verification in 0.2

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#1347]
Dagger currently checks for missing inputs by scanning `@dagger(input)`.

In Europa, `@dagger(input)` is gone. Instead there's now `#Plan.input`. Input sanity checks must be ported to Europa.

Design possibility:

- Inputs in Europa are tasks (e.g. `plan/task/inputdirectory.go`)
- Tasks have a `PreRun()` hook, which gets called at the very beginning, before the Plan is executed
- We could check concreteness in the `PreRun()` hook of inputs

/cc @samalba who implemented the original feature

**Comment by mircubed** [comment]
@samalba can we close this?

**Comment by samalba** [comment]
> @samalba can we close this?

Yep!
