### ISSUE TITLE
Add outputs to screen

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#1351]
I find the pre-europa outputs very useful, just wish you could control which outputs to show.

Europa is well positioned for this, maybe something like:

```cue
engine.#Plan & {
    actions: {
        build: push: engine.#Push & { ... }
        run: push: engine.#Push & { ... }
    }
    outputs: values: {
        "build image": actions.build.push.result
        "run image": actions.run.push.result
    }
}
```
Which would output:
```
Output		Value
build image	registry.example.net/repo:build@sha256:1b2bd4200d734dd3fb819faf21b9352f973f67c55cc8d59addeafc602835461a
run image	registry.example.net/repo:run@sha256:3eaa0b49e5ed5831cfa372cd8f62615012ec87d27401c08f28c7cb1a8bae949f

```

**Comment by NotTheEconomist** [comment]
This stood out to me immediately as a missing feature of 0.2. I'd love to see it get implemented. Judging from the comments on #1486 it looks like there's a path forward, though it may need some refinement over time (is outputting all the fields of an action actually what most people want? Consider `dagger do build push` -- do I want anything out of that other than the image ref and maybe sha1?)

**Comment by helderco** [comment]
> For outputs, we should simply print the action's fields. This can be further refined, but we can start fresh on this topic in another issue.

_Originally posted by @shykes in https://github.com/dagger/dagger/issues/1486#issuecomment-1081551488_

As I said in the description of this issue, the powerful thing for me is to be able to say exactly what I want to output because on 0.1 there was just too much I didn't care about (too much noise).

Additionally, I'm doing things like publishing multiple docker images (as in https://docs.dagger.io/1205/container-images#automation), how would I go about it showing the pushed ref either by `do versions` or `do versions 8.0`?

By referencing anything I want to ouput in a `client: console: ....`, only those that are run, would actually be outputed, just like the other `client` actions that are outputs.

**Comment by helderco** [comment]
@shykes looks like this is a priority. We need to decide on the new design. Thoughts?

**Comment by shykes** [comment]
> @shykes looks like this is a priority.

Yes agreed!

> We need to decide on the new design. Thoughts?

Here's what I propose:

1. When `dagger do` completes executing the target action, it prints the action's *output fields* to standard output, formatted as a table similar to 0.1.

2. *Output fields* are fields which a) dagger knows how to print (ie. top-level scalars as a start) and b) are not inputs (as detected by @jlongtine 's detection code)

3. Output format can be configured with an `--output-format` flag (json, yaml or text (the default))

4. Output file can be configured with a `--output` flag (although maybe redirecting stdout is enough?)

5. Stdout for `dagger do` should be reserved for printing outputs, so that they can be piped. Logs should not print to stdout, even if they're coming from the stdout of a a command executed by dagger. This should be true even in plaintext logging, and debug log level.

6. In the future we should also add a UI API, to allow Actions more control over what to show the  end user (and perhaps even what inputs to receive directly from them?). But that is a separate feature that requires more design work.

7. Remember, action developers csn already control what outputs they show. Only top-level scalar fields are printed, so those you don't want to print can be moved to a sub-field, or made a hidden field.

**Comment by helderco** [comment]
I’m a bit skeptical on the approach of using actions’ outputs.

Let’s take the simple example of [https://docs.dagger.io/1205/container-images#automation](https://docs.dagger.io/1205/container-images#automation). That plan allows you to build multiple images (`dagger do versions`) or a single one (`dagger do versions 8.0`). 

It becomes cumbersome when you have multiple levels for calling an action (depth). Action API will help control which outputs to run (otherwise we’re back to the old 0.1 behavior of printing all outputs), but it won't help on this sort of duplication and required adjustment of the structure of the plan.

```cue
dagger.#Plan & {
	actions: deploy: {
		// wrap template to add these fields in case I want to run everything
		for version, action in versions {
			"\(version)-result": action.push.result
		}

		versions: {
			"8.0": _
			"5.7": _

			[tag=string]: {
				// in case I don't reference push explicitly 
				// (i.e., dagger do deploy versions 8.0)
				result: push.result

				build: docker.#Build & {
					...
				}

				push: {
					// wrap if you need to control which outputs to print
					// (e.g., docker.#Run has quite a few outputs).
					result: _op.result

					_op: docker.#Push & {
						image: build.output
						dest:  "registry.example.com/mysql:\(tag)"
					}
				}
			}
		}
	}
}
```


I understand that the proposal is trying to mirror what’s happening with CLI inputs (which are optional), but the equivalent would be setting which fields to output from the CLI (e.g., `--result`), not being required to adapt the plan itself.

It seems much cleaner to me how it was implemented in #1486, just with a couple changes. Moving to `client` of course, and making each “value” a task so that only actions that run trigger the right outputs, while also having full control on what to print. And you'd only set it in one place, regardless of what your target is with `dagger do`.

**Comment by helderco** [comment]
Just an update. This is mostly done, but it's not simple to automatically detect inputs/outputs. I've got it mostly boiled down but now the issue is with core actions. You can't tell which fields are inputs and which are outputs.

For example, in `core.#Pull`, the field `source` is an input and `digest` is an output. Both start as inconcrete scalar strings (#2033) and end as concrete as well. I'm thinking about leveraging the computed values to decide.

**Comment by helderco** [comment]
@shykes Oh yes, I ended up resolving with the attributes at the same time as @aluzzardi, already rebased to his merged syntax 🙂 

The only blocker is the solution in https://github.com/dagger/dagger/pull/2024 if you're ok to merge.

I also just noticed that `docker.#Push` isn't detecting the `result` output while updating the documentation. I'm looking into it. Other than that it's ok to review.

**Comment by helderco** [comment]
After 4 months, this is finally closed! 😄 🎉

**Comment by shykes** [comment]
Yay!
