### ISSUE TITLE
Redact secrets from all log messages

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#1354]
Currently, dagger redacts secrets while forwarding buildkit events to the logger.

It works great to strip away secrets leaked by the CUE layer (e.g. `#Exec & { command: "echo secret: $(cat /secret)" }` shows up as `secret: ***`), however it doesn't strip away secrets leaked by Dagger itself in Go.

It's currently implemented in `Client.logSolveStatus()` (the goroutine that bridges buildkit events to the logger), which uses an internal `secureSprintf` function to strip away secrets.

An alternative would be to move this logic into a `zerolog` hook if possible: https://github.com/rs/zerolog#hooks

**Comment by shykes** [comment]
Is this still relevant in 0.3 @aluzzardi ?
