### ISSUE TITLE
Port Universe to 0.2/Europa

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#1358]
Universe packages must be ported to the Europa syntax. This is a tracking issue for the entire collection of Universe.

For each, we should:

- Determine whether it **should be ported** or not
- If it requires further discussion, create a **dedicated issue** (**do not discuss individual packages here**)
- Have an **assignee**
- And finally, an **implementation status** ❓🚧 ✅

Before we can start porting these, we must finalize reference packages #1359

| Package  | Needed by (real configs only) | Should be ported? | Dedicated Issue | Assignee | Status |
| --- | --- | --- | --- | --- | --- |
|**alpine**| changelog.com | ✅ || @talentedmrjones | ✅ |
|**argocd**| ? | :question:||||
|**aws**| ? | ✅ | https://github.com/dagger/dagger/issues/1388 | @talentedmrjones | ✅ #1622 |
|**aws/cloudformation**| ? | ? || @talentedmrjones ||
|**aws/ecr**| ? | :question:||||
|**aws/ecs**| ? | :question:||||
|**aws/eks**| ? | :question:||||
|**aws/elb**| ? | :question:||||
|**aws/rds**| ? | :question:||||
|**aws/s3**| ? | :question:||||
|**azure**| ? | :question:||||
|**azure/resourcegroup**| ? | :question:||||
|**azure/staticwebapp**| ? | :question:||||
|**azure/storage**| ? | :question:||||
|**bats**| Dagger CI | :question:||||
|**docker**| changelog.com, Dagger CI | :question:||||
|**docker/compose**| ? | :question:||||
|**gcp**| ? | :question:||||
|**gcp/cloudrun**| ? | :question:||||
|**gcp/gcr**| ? | :question:||||
|**gcp/gcs**| ? | :question:||||
|**gcp/gke**| ? | :question:||||
|**gcp/secretmanager**| ? | :question:||||
|**git**| Changelog.com, Todoapp example, Dagger CI | :question:||||
|**go**| ? | :question:||||
|**graphql**| ? | ✅ || @slumbering  ||
|**http**| ? | ✅ || @slumbering  ||
|**io**| “Dagger classic”? | ❌ Deprecated by `dagger.io/dagger` and `universe.dagger.io/docker` ||||
|**java**| ? | :question:||||
|**java/maven**| ? | :question:||||
|**js/yarn**| Todo app example | :question:||||
|**kubernetes**| ? | :question:||||
|**kubernetes/helm**| ? | :question:||||
|**kubernetes/customize**| ? | :question:||||
|**netlify**| Todo app example | :question:||||
|**os**| “Dagger classic”? | ❌ Deprecated by `dagger.io/dagger` and `universe.dagger.io/docker`. ||||
|**random**| ? | ❌ Feels like it should be a future `engine` feature instead. ||||
|**terraform**| ? | :question:||||
|**trivy**| ? | :question:||||

**Comment by hongchaodeng** [comment]
K8s issue: https://github.com/dagger/dagger/issues/1951

**Comment by nmeisenzahl** [comment]
I started working on porting the Terraform package. Any feedback is welcome. Issue #2109, WIP PR #2110

**Comment by TomChv** [comment]
@aluzzardi @shykes Is this issue still useful?

**Comment by shykes** [comment]
I personally think we should close it, since we're not actively working to port all universe packages. wdyt @aluzzardi @samalba @helderco @jpadams ?

**Comment by helderco** [comment]
I agree.

**Comment by samalba** [comment]
I agree as well, the initial plan was to port all of them, but we should instead focus on user requests.
