### ISSUE TITLE
DockerBuild logs are not contextual

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#136]
We encode the cue path in LLB operations. Because call an external frontend for DockerBuild, and therefore we are not the ones generating the LLB, the contextual information is missing.

This needs investigating, a possible solution would be to use `dockerfile2llb` directly and alter the LLB, however there are drawbacks (e.g. dockerfile.v0 does more than dockerfile2llb, we'd have to reimplement that or we lose functionality. Also, the problem would persist for alternative Dockerfile syntaxes)

**Comment by slumbering** [comment]
Is this issue still relevant even with Cloak ?

**Comment by gerhard** [comment]
I cannot visualise the contextual information that we are missing. I don't even know how to get this information. I am assuming that these changes would need to happen in `client/client.go`, but I'm not sure.

**Comment by slumbering** [comment]
test pour camille

**Comment by samalba** [comment]
Superseeded by #3587
