### ISSUE TITLE
input directories:  hard to understand error when forgetting `.contents`

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#1426]
I forgot to use `.contents` on my input directory (`source: inputs.directories.testdata` instead of `source: inputs.directories.testdata.contents`):

```
	inputs: {
		directories: {
			testdata: path: "./testdata"
		}
	}

	actions: {
		TestReact: {
			pkg: yarn.#Build & {
				source: inputs.directories.testdata
			}
	}
```

This is the error I'm getting back, which is very hard to understand:

```
4:48PM FTL system | failed to load plan: actions.TestReact.pkg.source.$dagger: field not allowed: fs
```

Any chance we can make this better?

/cc @talentedmrjones @jlongtine

**Comment by shykes** [comment]
I'm closing this, since we are no longer adding features to the CUE API - new features should be added to the GraphQL API instead.
