### ISSUE TITLE
Nested docker.#Build fails

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#1466]
When using `docker.#Build` as a *step* within another `docker.#Build`, dagger throws CUE errors.

I've narrowed it down to builds containing **multiple steps**:

```cue
_build: docker.#Build & {
	steps: [
		docker.#Build & {
			steps: [
				docker.#Pull & {
					source: "alpine"
				},
				// FIXME: the following breaks with:
				// actions.deploy._build._dag."0".output: 1 errors in empty disjunction::
				//    pkg/universe.dagger.io/docker/build.cue:26:11
				docker.#Run & {
					cmd: name: "ls"
				},
			]
		},
		docker.#Run & {
			cmd: name: "ls"
		},
	]
}
```

/cc @shykes

**Comment by Breigner01** [comment]
As discussed on discord, I have the same issue on a gcp package.
Hope this gets fixed soon.
I've basically got 3.nested `docker.#Build` which would be really convenient if it did work.
For now I'll break down my `docker.#Build` in order to have my package working.
I'm definitely looking forward to change my package once this works.

**Comment by ahmed1107** [comment]
> I'm having the same problem, which is preventing me from using Dagger, and look forward to a solution soon.

has this been sorted now?

**Comment by shykes** [comment]
> > I'm having the same problem, which is preventing me from using Dagger, and look forward to a solution soon.
> 
> has this been sorted now?

No solution yet, but we have prioritized it. Sorry.

**Comment by jlongtine** [comment]
This is due to https://github.com/cue-lang/cue/issues/754

**Comment by jlongtine** [comment]
It may also have some connection to https://github.com/cue-lang/cue/issues/1608

**Comment by NarendraPatwardhan** [comment]
Came across this issue while porting a Dockerfile. A temporary fix is to import "list"
and using steps: list.FlattenN([<original_steps],2) inside docker.#Build (The level might be higher depending on nesting).
