### ISSUE TITLE
Drop privileges in the managed buildkitd

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#151]
Right now, when no buildkit address is specified, dagger will create its own instance https://github.com/dagger/dagger/pull/149

The container is created using `--privileged` which is far from ideal. We could look into dropping `--privileged` and using more fine grained `--security-opt`s instead, see:

https://github.com/moby/buildkit/blob/master/docs/rootless.md

**Comment by gerhard** [comment]
We (+@slumbering) made the smallest possible change that starts addressing this in https://github.com/dagger/dagger/pull/2978

Is it worth continuing with that @dubo-dubon-duponey @aluzzardi?

**Comment by dubo-dubon-duponey** [comment]
hey @gerhard 

Maybe a problem with permission mapping between the buildkit container and the host?

Haven't tried that in a while...
I would try to make it work on Linux first, and without dagger - just buildctl - ignoring mac for now <- especially if you guys are going to build a standalone distribution w. lima / containerd.

**Comment by TomChv** [comment]
@dubo-dubon-duponey Any news on this issue? Do we still have this issue with dagger v0.8?
