### ISSUE TITLE
Convert our own Makefile to dagger

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#1522]
One of Dagger’s selling points is that it can unify dev and CI environments.

* Work is already underway to migrate our CI.
* Let’s talk about doing the same for our Makefile :)

**Comment by teddylear** [comment]
Hey! I'd love to help out with part of this. What's the best place to start here? I was thinking moving the CI steps that are already converted to dagger in the `ci` directory to the top level of the repo and then cleanup CI to reflect this change. Also then removing corresponding `make` commands that are in dagger. If there's something else I should start with here please let me know!

**Comment by samalba** [comment]
@teddylear It'd be great! @aluzzardi recently did some more work on it (#1984) so maybe he has some opinions on things that could help short term.

**Comment by teddylear** [comment]
@samalba Opened up draft PR with moving CI components to be in use, but needs approval because I'm a first time contributor. If there's anything else I should change with it please let me know!

**Comment by shykes** [comment]
We've made some pretty good progress on this. I personally only use `dagger`, I don't even have `make` installed on my dev machine :)

Should we close this? And if not, what steps are missing to close?

**Comment by samalba** [comment]
There is one more set of integration tests we should migrate before closing this. Last week I implemented our core-integration tests, this week I want to port the universe one. And we should be good to go to close this.
