### ISSUE TITLE
Support for the Gradle build tool

### ISSUE THREAD

**Issue by almogtavor** [dagger/dagger#1615]
I've seen that there's support for [Maven](https://docs.dagger.io/reference/java/maven), but lots of Java users (and probably the same amount if you consider Android development) use Gradle, and I think that one should be supported too.

**Comment by nightscape** [comment]
@almogtavor it should be this:
https://github.com/dagger/dagger/commit/0ba7c1fb449446ba07b3e32cc6667c75eac0e6ac

**Comment by TomChv** [comment]
Since https://github.com/dagger/dagger/issues/5287 has been fix, Dagger can support Dagger on Zenith, we should create a dagger module in the Daggerverse to emphasis on this.

I've seen a couple of gradle issue (#2650 #2972 #2215), it looks like an important module to make.
