### ISSUE TITLE
Unset image metadata

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#1624]
Ever since I started working on #1535, I wanted to be able to also unset some things.

I tried a first pass at the time that didn't work out, but decided to not delay because of it. I want to try again 🙂

For me this has come up for one reason. Sometimes I use a base image that's mostly fine, but I wish they hadn't set up a few `VOLUME`, `EXPOSE` or `ENV` instructions.

I've wondered about a `docker.#Unset`, but it's not clear to me how you would chose what to delete precisely.

What I want to explore is to allow `docker.#Set` to have _null_ values, which would efectively unset the field:

```cue
dagger.#Set & {
    // this would be a **version** of #ImageConfig that accepts nulls
    config: {
        volume: {
            "/etc/salt/pki/": null
            "/home/.console": {}
        }
        expose: {
            "4505/tcp": null
            "4506/tcp": null
            "9090/tcp": {}
        }
        env: {
            MARIADB_NAME: null
            MARIADB_USERNAME: null
            NGINX_PORT_NUMBER: "8080"
        }
        entrypoint: ["/init.sh"]
    }
}
```

`input` and `output` would still be normal `#ImageConfig`.

**Comment by TomChv** [comment]
@helderco Is it still accurate?

**Comment by helderco** [comment]
Yes, it is.

**Comment by helderco** [comment]
Closing since the 0.2 CUE API is frozen, in favor of the GraphQL API.
