### ISSUE TITLE
Kube detection in test suite is flawed

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [dagger/dagger#1643]
Currently: https://github.com/dagger/dagger/blob/main/pkg/alpha.dagger.io/helpers.bash#L77 assumes that if `~/.kube/config` exists, then there must be a running kube.

I was bitten by this (leftover file, no running kube, test suite failing in a very confusing way).

Is there a better way to verify that the cluster exist rather than this?

Maybe something as simple as:
`k=$(grep "127.0.0.1" ~/.kube/config); curl "${k#*server: }"; echo $?`

**Comment by shykes** [comment]
Is this still relevant in 0.2?

**Comment by dubo-dubon-duponey** [comment]
Probably not?

https://github.com/dagger/dagger/blob/main/docs/v0.1/learn/tests/helpers.bash
