### ISSUE TITLE
Confusing API for buildkit caching

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#1647]
By default the definition ```os.#Container``` cache the command by using **always** field.
```
	// If true, the command is never cached.
	// (false by default).
	always: true | *false
```
This naming seems pretty confusing. It has been named this way to avoid confusion with cache mounts which are different.
We went for something literal aka “always run”.

>**solomon**:  Caching systems in buildkit (run caching and cache mounts) are actually more related than it first appears. So maybe there is a way to reconcile them in our API

We should rename it more explicitly. cmdCache for instance ?

**Comment by helderco** [comment]
Not tracked, this is a conversation a bit in the air about the way commands are composed in `docker.#Run` being in need of a redesign. Nothing concrete has been drafted yet.

**Comment by helderco** [comment]
Closing since the 0.2 CUE API is frozen, in favor of the GraphQL API.
