### ISSUE TITLE
Github issue template

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#1652]
### Discussed in https://github.com/dagger/dagger/discussions/1546

I think we should add a Github issue template. Therefore, we can gather minimum information if we need to reproduce bugs for instance.

Documentation: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates.

Syntax for issue form: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

Github issue template examples:  https://github.com/stevemao/github-issue-templates

**Comment by shykes** [comment]
This is done :)
