### ISSUE TITLE
[Feature] Support local scripts and interaction

### ISSUE THREAD

**Issue by hongchaodeng** [dagger/dagger#1660]
In CUE commands, we can interact with local system to do operations like prompting for user input, file read/writes: https://cuetorials.com/patterns/scripts-and-tasks/

Example:
```javascript
     task: ask: cli.Ask({
         prompt:   "Approve it?"
         repsonse: bool
     })
```

That would be useful to orchestrate local workflow like environment promotion from dev to prod.

**Comment by helderco** [comment]
Closing since the 0.2 CUE API is frozen, in favor of the GraphQL API.
