### ISSUE TITLE
Merge official examples into universe, delete the rest

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#1694]
There is a separate repository holding examples of Dagger configurations: https://github.com/dagger/examples. This repository is consistently out of date, because it holds several examples, its ownership is unclear, and its upstream dependencies are moving fast which requires constant updates.

At this stage it's better to move the examples we care about into the main dagger repository (this one), and remove the external dagger/examples repository (after creating a secure backup of its contents). It's better to have no content than out-of-date, confusing content.

Copying @gerhard, we discussed this live today and are in agreement.

**Comment by gerhard** [comment]
Closed via https://github.com/dagger/examples/pull/60
