### ISSUE TITLE
Remove dependabot security alerts

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#1717]
The first thing I see when visiting our github repo are scary-looking security errors. We should clean those up before opening the repo; and ideally before the next release since it will bring a lot of repeat visitors.

**Comment by shykes** [comment]
Load balancing assignments :)

**Comment by aluzzardi** [comment]
Those are legit alerts that only admins can see. They are useful for security alerts on our dependencies.

The problem though is `examples` -- the todoapp comes with a TON of security alerts. Currently, there are 0 security alerts for dagger, 2 alerts for the docs website (which we should look into) and 44 alerts for `examples` (which are flooding our repo and hiding the legit alerts).

I suggest we find a way to move `examples` out of universe. Alternatively, turn off dependabot for `examples`.

Additionally, as reported by @vdemeester, when vendoring `cue.mod` into your own repo, those 44 alerts come along.

Another alternative: perhaps we should have our own example app which we properly maintain.

**Comment by shykes** [comment]
> Those are legit alerts that only admins can see. They are useful for security alerts on our dependencies.
> 
> The problem though is `examples` -- the todoapp comes with a TON of security alerts. Currently, there are 0 security alerts for dagger, 2 alerts for the docs website (which we should look into) and 44 alerts for `examples` (which are flooding our repo and hiding the legit alerts).
> 
> I suggest we find a way to move `examples` out of universe. Alternatively, turn off dependabot for `examples`.
> 
> Additionally, as reported by @vdemeester, when vendoring `cue.mod` into your own repo, those 44 alerts come along.
> 
> Another alternative: perhaps we should have our own example app which we properly maintain.

This is addressed in #2113 :) I will assign to myself, and close once the todoapp source code is no longer present.
