### ISSUE TITLE
Add fmtok8s example

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#1730]
Post 0.2.0 release

The starting point is a managed K8s
- an alternative to GKE plain would be welcome
- use the K8s cluster for running the app(s), managed services otherwise

gcr.io for container images so that github packages can be used for JAR packages

Ideally, GitHub Actions will be enough to seed everything else

One pipeline to build & publish all the artefacts for a *single* service (app)
- use the branch name for the artefact version
- https://github.com/salaboy/from-monolith-to-k8s/blob/master/tekton/resources/service-pipeline.yaml

On every merge into main, bump the version & build artefacts with the new version
Tag repository with the new version

Automatically open a pull request in the environment repository with the new version of the service (app) that changed
https://github.com/salaboy/fmtok8s-staging-env/blob/main/helmfile.yaml (a.k.a. GitOps)

Have the option to open a pull request manually with multiple services that changed

A second pipeline to sync all services with what is running the managed K8s
- https://github.com/salaboy/from-monolith-to-k8s/blob/master/tekton/resources/environment-pipeline.yaml

Running service pipeline locally, with no K8s, would be a huge advantage
Not needing to install anything in the cluster to deploy things would be welcome

cc @salaboy

**Comment by mircubed** [comment]
@gerhard is it ok to close this one?

**Comment by gerhard** [comment]
Yes, closing now.

Things have changed significantly since v0.3, and while this is a good point-in-time snapshot, I am unsure when / how I will be able to tackle this, and how many other things will be different when I will be able to dig into this.
