### ISSUE TITLE
Move universe integration test infrastructure out of upstream dagger repo

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#1766]
## Problem

Dagger Universe includes an integration test suite that requires external infrastructure to run. This infrastructure is maintained by Dagger employees, and for security and legal reasons, non-employees cannot access it. Yet, it is managed using the same open-source repository. This involves the use of sops-encrypted credentials, and automation scripts which are useless to non-employees.

## Solution

Move all content related to Dagger's proprietary test infrastructure, out of the upstream dagger repository. This has 2 benefits:

1) A cleaner upstream repository.
2) A dedicated space for the Dagger infrastructure team to focus on operating, securing and improving the test infrastructure for the benefit of upstream developers.

**Comment by aluzzardi** [comment]
Are you referring to `dagger/infra`?

**Comment by shykes** [comment]
> Are you referring to `dagger/infra`?

Not referring to any repo in particular (although I think we should converge everything into a monorepo, but that's off-topic). I just mean moving it to a downstream private repo, outside of this one.

**Comment by aluzzardi** [comment]
I meant the `infra` folder in the dagger repo (which contains some scripts to setup a Digital Ocean machine for ssh tests). I think that's the only piece of test infrastructure we maintain right now

**Comment by shykes** [comment]
> I meant the `infra` folder in the dagger repo (which contains some scripts to setup a Digital Ocean machine for ssh tests). I think that's the only piece of test infrastructure we maintain right now

Well there's also our test netlify account, and soon aws, gcp, etc.
