### ISSUE TITLE
yarn apparently leaves processes behind

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [dagger/dagger#1775]
`make integration` (and probably others) do call `yarn test`, which in turns invoke bats.

It seems that yarn leaves processes behind (bats and dagger), causing (confusing) issues for developers.

Suggestion: if there is no important reason for it, just remove the `yarn` layer of delegation and call `bats` directly instead.

cc @grouville @aluzzardi

**Comment by grouville** [comment]
Not relevant anymore
