### ISSUE TITLE
gnu parallel is not always working

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [dagger/dagger#1776]
Different versions of parallel may not be working / compatible with bats (for example on `debian:bullseye`).

Ideas to work-around it:
* sanity test parallel version and fallback to `--jobs 1` if it does not fit the bill
* make the number of parallelized jobs easy to control (environment) so that one can disable parallel on integration tests if need be

cc @grouville @aluzzardi

**Comment by grouville** [comment]
Not relevant anymore, as bats is not used in codebase
