### ISSUE TITLE
Loading plan fails when workdir is outside the project

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#1778]
## Problem

When running `dagger do -p /PATH/TO/PLAN`:

* If the workdir is *inside* the plan's project, loading succeeds
* If the workdir is *outside* the plan's project, loading fails

This is confusing because Dagger has all the information needed to load the plan without an error, but returns an error instead.

## Solution

When workdir is *outside* the plan's project, configure the cue loader to use *the project directory* as its "loader working directory", instead of the current workdir.

## Example

From the root of the dagger repo:

* This works: `cd ci && dagger -p . do --help`
* This fails: `dagger -p ./ci do --help`

**Comment by TomChv** [comment]
Related to #2454
