### ISSUE TITLE
client: filesystem: write doesn't work with string interpolation

### ISSUE THREAD

**Issue by grouville** [dagger/dagger#1781]
# Context
@Alvise88 is porting his config to Dagger Europa.
His use case is: read a file from the host and modify it using dagger.

# Issue
The first implementation doesn't seem to work because no action is being referenced. That way, `dagger do` doesn't seem to run. 
```
package main

import (
	"dagger.io/dagger"
)

dagger.#Plan & {
	client: filesystem: "test.txt": {
		read: contents:  string
		write: contents: read.contents
	}
}
```
But, it's not the subject of this issue: what we did is that we created a new action that would use the client filesystem as intermediary steps.

### However, when testing, we realized that `client: filesystem: "test.txt": write: contents` couldn't be inlined in a string:

> For all the repro cases below, you need to create a `test.txt` file with `foo` written inside

**No string interpolation - this works**
```
package main

import(
  "dagger.io/dagger"

  "universe.dagger.io/alpine"
  "universe.dagger.io/docker"
)

dagger.#Plan & {
  client: filesystem: "./test.txt": {
      read: contents: string
      write: contents: actions.hosts.export.contents // works
  }

  actions: hosts: {
    configuration: client.filesystem."/etc/hosts".read.contents

    image: docker.#Build & {
      steps: [
        alpine.#Build & {
          packages: "docker-cli": {}
          packages: "curl": {}
        },
        docker.#Run & {
          always: true
          command: {
            name: "sh"
            flags: "-c": "echo -n bar > /foo.txt"
          }
        },
      ]
    }
    export: dagger.#ReadFile & {
      input: image.output.rootfs
      path:  "foo.txt"
    }
  }
}
```

**With string interpolation - this doesn't work**
```
package main

import(
  "dagger.io/dagger"

  "universe.dagger.io/alpine"
  "universe.dagger.io/docker"
)

dagger.#Plan & {
  client: filesystem: "./test.txt": {
      read: contents: string
      write: contents: "\(actions.hosts.export.contents)" // This doesn't work
  }

  actions: hosts: {
    configuration: client.filesystem."/etc/hosts".read.contents

    image: docker.#Build & {
      steps: [
        alpine.#Build & {
          packages: "docker-cli": {}
          packages: "curl": {}
        },
        docker.#Run & {
          always: true
          command: {
            name: "sh"
            flags: "-c": "echo -n bar > /foo.txt"
          }
        },
      ]
    }
    export: dagger.#ReadFile & {
      input: image.output.rootfs
      path:  "foo.txt"
    }
  }
}
```

# Current solution
1. Enforce the `string` type of the `client: filesystem: write`:
```
      write: contents: "\(actions.hosts.export.contents)" // This doesn't work
```

becomes
```
      write: contents: "\(actions.hosts.export.contents)" // This works now
      write: contents: string
```
or 
```
      write: contents: "\(actions.hosts.export.contents)" & string // This works now
```

2. Do not inline in the client API, but directly in your actions

# Potential root causes
@helderco thought this might be related to the `dagger do` fixes that @aluzzardi and @jlongtine implemented recently.

**Comment by helderco** [comment]
There's an easy and more appropriate solution:

```diff
-write: contents: "\(actions.hosts.export.contents)"
+write: contents: (actions.hosts.export.contents)
```

As for the unexpected behavior of the interpolation, I'll defer to the #493 issue.

**Comment by helderco** [comment]
On second thought, the usage of interpolation here shouldn't fail on plan load. Intuitively it should get resolved as a string, but it isn't. We should drill down the repro into pure CUE and see if it's really about https://github.com/cue-lang/cue/issues/629 or something else.

**Comment by grouville** [comment]
Closing, as Cue API is not a priority for now
