### ISSUE TITLE
When no buildkitd is already available, dagger starting buildkitd is racy

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [dagger/dagger#1786]
With no buildkitd already started:

```
time /home/dmp/debug-ga/actions-runner/_work/dagger/dagger-0.2.0/cmd/dagger/dagger-debug do -p ./tasks/pull/pull.cue pull
```

... starts buildkitd, but doesn't wait for it to be ready, ending with:

```
1:04PM FTL unable to create client: buildkit failed to respond

real	0m12.964s
user	0m0.436s
sys	0m0.212s
```

**Comment by TomChv** [comment]
We reworked our engine provisioning and I didn't saw the issue recently, we can close it since it concerns an older version of Dagger.

Right now dagger can either provide his own runner OR use `_EXPERIMENTAL_DAGGER_RUNNER_HOST` as explained there: https://docs.dagger.io/541047/alternative-runtimes
