### ISSUE TITLE
Actions with no core buildkit actions don't trigger filesystem write

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#1789]
## Problem

Some actions don't need to call buildkit. For example a simple string transformation using only CUE builtins. These actions can be called with `dagger do`, but any client filesystem writes that depend on them will *not* be triggered.

## Example

```
import (
  "strings"
  "dagger.io/dagger"
)

dagger.#Plan & {
  client: filesystem: write: "./output": contents: actions.upper.output
  actions: upper: {
    input: "hello, world"
    output: strings.ToUpper(input)
  }
}
```

```
$ dagger do upper
$ cat output
cat: can't open 'output': No such file or directory
```

## Workaround

 A pure cue action can wrap its output in dagger.#Nop, which will trigger client filesystem writes. Requires merging #1790.

**Comment by jlongtine** [comment]
@shykes Do you think we should keep this around?

**Comment by shykes** [comment]
Yes I think so, although not a high priority, it's good to keep track of known limitations of the cue sdk.

**Comment by jlongtine** [comment]
Sounds good, @shykes! 👍🏻

**Comment by TomChv** [comment]
I'm closing this issue since it's related to old cue dagger, we are not working on this version anymore.
