### ISSUE TITLE
[Feature] Missing `dagger input list` style feature in Europa

### ISSUE THREAD

**Issue by hongchaodeng** [dagger/dagger#1806]
In v0.1 , you can list all the fields that needs to input with type and description:

```
$ dagger input list
Name      Type         Description
token     string       Token to access Github
```

But in v0.2, you can not list the inputs in client:

```
	client: {
		filesystem: {
			".": read: {...}
			build: write: contents: actions.build.contents.output
		}
		env: {
			APP_NAME:      string
			NETLIFY_TEAM:  string
			NETLIFY_TOKEN: dagger.#Secret
		}
	}
```

Here, the path to read and write, envs, are all inputs to the plan. How can I show their type and description? It would be great if dagger could provide an API to interact with.

**Comment by shykes** [comment]
I believe this is solved, you can pass inputs as command-line flags, and list available inputs with `dagger do --help`.
