### ISSUE TITLE
[Docs] - Display a warning version banner

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#1830]
While I was using the search engine, I've been redirected to a page in the 0.1 documentation. This is very confusing.
Maybe we could display a banner :

> This is documentation for Dagger 0.1, which is no longer actively maintained.
> For up-to-date documentation, see the [latest version](https://docs.dagger.io/) (0.2).

what do you think @gerhard ?

**Comment by digitalsanctum** [comment]
There's also links to deprecated (and archived) repos from the docs. For example, https://docs.dagger.io/1007/kubernetes/

**Comment by dolanor** [comment]
What is the next step to make this reality? It still confuses users.

Do we need to embed metadata in the markdown? Modify theme from docusaurus?

**Comment by slumbering** [comment]
PR open #2066

**Comment by shykes** [comment]
This is done right? Ok to close?
