### ISSUE TITLE
Bring back `dagger doc`

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#1872]
## Problem

Dagger 0.1 had a command called `dagger doc`, which was similar to `go doc`. Given the names of a CUE package and definition, it would print information about their API.

Unfortunately, this feature was not compatible with Dagger 0.2, because it relied on concepts such as `@dagger(input)` and `@dagger(output)` which no longer exist. This is also why we currently don't have an API reference in our docs: the generator has not been ported to 0.2.

As a result, there is no easy way to look up available packages and their APIs while developing a Dagger 0.2 plan.

## Solution

Bring back `dagger doc` in a simpler form. Instead of scanning the CUE code and generating documentation, just print the CUE code as is. The output can be refined later - but at least developers get the equivalent of looking up the source file on github, which is what they need to do anyway. It's a strictly better developer experience, achievable in the short term.

**Comment by dolanor** [comment]
For the future, I think if we could embed [glow](https://github.com/charmbracelet/glow) as the documentation pager/reader, it would be amazing.
That would require to generate some markdown format from the CUE API.

**Comment by jpadams** [comment]
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/3187222/169950214-f3344f51-b6ab-44a4-89eb-fb694794dc46.png">
