### ISSUE TITLE
Should we require two dagger packages to be imported?

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#1903]
I think that requiring two packages to be imported instead of a single one (which we had before #1866) doesn't sit right:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/3342/160501645-56bb9eaa-c96a-47ee-a113-90ebbc5d3d88.png">

Could we simplify this so that only a single package would need to be imported?

---
Follow-up to https://github.com/dagger/dagger/pull/1866 cc @helderco @shykes

**Comment by shykes** [comment]
I think we're in good shape with the new docs page added this week. In particular:

* [Core Actions Reference](https://docs.dagger.io/1222/core-actions-reference/)
* [Dagger Actions](https://docs.dagger.io/1221/action/)
