### ISSUE TITLE
[Feature] Dagger Go API

### ISSUE THREAD

**Issue by hongchaodeng** [dagger/dagger#1911]
We can only use dagger using the binary for now. Is there any way we can call dagger via Go API?

**Comment by evalsocket** [comment]
@shykes We have a use case for this, We have one account service that is responsible for tenant deployment, Currently the process is manual and it involves CI/CD provider.  One other alternative solution is cross plane but we don't like the CRD way to do things, We want to use terraform/opta.

My assumption is that with buildkit you can run these dagger plan from anywhere an triggering them from a service(GO) is possible,  But i am not sure how hard is it. 
What are the cons of doing it ?, Dagger command can be converted into a service that will get the message and start the deployment on buildkit(remote)

**Comment by shykes** [comment]
> @shykes We have a use case for this, We have one account service that is responsible for tenant deployment, Currently the process is manual and it involves CI/CD provider. One other alternative solution is cross plane but we don't like the CRD way to do things, We want to use terraform/opta.
> 
> My assumption is that with buildkit you can run these dagger plan from anywhere an triggering them from a service(GO) is possible, But i am not sure how hard is it. What are the cons of doing it ?, Dagger command can be converted into a service that will get the message and start the deployment on buildkit(remote)

If I understand your use case correctly, you can probably achieve the desired result by invoking the `dagger` binary remotely over ssh.

**Comment by d3rp3tt3** [comment]
@shykes @mircubed, the Go SDK was delivered. https://docs.dagger.io/sdk/go. Do you think this request should be closed/resolved?

**Comment by shykes** [comment]
> @shykes @mircubed, the Go SDK was delivered. https://docs.dagger.io/sdk/go. Do you think this request should be closed/resolved?

Yes 😁 Thanks for catching. Closing now.
