### ISSUE TITLE
Docs: missing intro for "getting started"

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#1912]
## Problem

When I follow "getting started" from the [website](https://dagger.io), I dive straight into the first part of a multi-part, hands-on tutorial. Hands-on is good, but the transition is abrupt, especially for a first-time visitor who only learned about Dagger 30 seconds ago. The fact that the title does not use the words "getting started" amplifies this. Personally, I briefly thought I had followed the wrong link.

## Solution

When I follow a "getting started" link, I should land on a page called "getting started", with a brief overview of what awaits me next. What will I achieve, how long will it take, and what is the overall structure? This clearly frames my experience, and I am ready to dive in.

**Comment by slumbering** [comment]
Ideas:

A simple Welcome message with a short intro of Dagger ? A nice illustration ?

Welcome to the documentation for Dagger. Dagger is a tool to run your CI/CD pipelines locally, then easily integrate them with any CI environment.
I want to play with Dagger now! Ok then, let's test and run a CI/CD pipeline locally :)
////// Link to CI/CD in your local dev ///////

If you’d like to familiarize yourself with Dagger core concepts, we recommend reading up on Dagger core concepts:
////// Link to Dagger core concept ///////

Display the actual Getting started sections cards (CI/CD in your local dev, integrating with your CI..., Dagger vs ....)

**Comment by mircubed** [comment]
@jpadams is going to do a tutorial with me this Friday on how to update docs, so I should be able to take on this issue to add the intro content. 

I also want to improve the section to look like this example: 
[Pulumi example](https://www.pulumi.com/resources/getting-started-with-automation-api/)

I can add the content first and then we can add the video later when it is done. A user also mentioned making the guide match the older getting started guide by starting with empty directory in #2223.

**Comment by mircubed** [comment]
Going to work on a new getting started video as part of this improvement #2472

**Comment by jpadams** [comment]
> We are addressing this with the fix in this PR - #2690

With a more thorough re-imagining coming through work with the team.
