### ISSUE TITLE
website: global horizontal scroll appears if code blocks overflow

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#1935]
Checking at https://docs.dagger.io/1215/what-is-cue/ seems like when code blocks overflow, a global horizontal scrollbar [1] also appears which leaves an empty white space at the left of the screen [2]

After some minimal testing after removing the lines that overflow in code blocks (which make then a bit smaller), the global scroll goes away.

[1]
![image](https://user-images.githubusercontent.com/1578458/160736063-920ea089-82bb-4a5c-8136-bf7696d3c0e9.png)

[2]

![image](https://user-images.githubusercontent.com/1578458/160736106-f3c4485e-344b-4514-9b4f-ae46aff3ed74.png)

This happens both in Brave and Firefox browsers in linux.  

Take into account that OSx might not show the scrollbar immediately since OSx only displays it when you actually use it and it hides it afterwards

**Comment by slumbering** [comment]
PR #1969
