### ISSUE TITLE
docs: use the Europa Rising blog post content for the docs.dagger.io new index page

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#1936]
Starting with **CI/CD in your local dev** is too abrupt, and there is a lot of great content on that blog post page that we should promote more 😉

cc @shykes

**Comment by shykes** [comment]
Good idea 👍

**Comment by gerhard** [comment]
Duplicate of https://github.com/dagger/dagger/issues/1912, closing in favour of that one.
