### ISSUE TITLE
🐞 Homepage says yaml does not support docs

### ISSUE THREAD

**Issue by josegonzalez** [dagger/dagger#1945]
### What is the issue?

The [homepage](https://dagger.io/) has this text:

```
Wire actions together using CUE, a powerful configuration language developed at Google. CUE has all the features you wish YAML had: comments, string interpolation, templating, static type checking, a complete package system, and more. And best of all, it can natively import and export YAML and JSON, for maximum compatibility with your existing tooling.
```

YAML definitely supports comments.

### Log output

N/A

### Steps to reproduce

Read the homepage, notice the comment reference.

### Dagger version

all

### OS version

N/a

**Comment by gerhard** [comment]
cc @slumbering

**Comment by slumbering** [comment]
Thanks @josegonzalez for your contribution :). This has been fixed
