### ISSUE TITLE
Improvements to Windows installation instructions

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#1946]
From [this comment on Hacker News](https://news.ycombinator.com/item?id=30858740):

> [gregmac](https://news.ycombinator.com/user?id=gregmac) [4 minutes ago](https://news.ycombinator.com/item?id=30858740) | [next](https://news.ycombinator.com/item?id=30857012#30858085) [[–]]()
> 
> Your Windows instructions/process needs work.
> > curl https://dl.dagger.io/dagger/install.ps1 -OutFile install.ps1
> This uses the `curl` alias, which is really `Invoke-WebRequest`. It also makes the incorrect assumption I haven't fixed this dumb Microsoft mistake to be an alias to actual curl.exe.
> > [Windows] We try to move the dagger binary under C:\Windows\System32
> Ack, please don't do this! This is similar to installing something under /usr/sbin/. Malware is the only modern thing that would attempt to deploy to that folder.
> > but in case we miss the necessary permissions, we'll save everything under <your home folder>/dagger > C:\<your home folder>\dagger.exe
> I'm glad you have a non-admin fallback, but also: yuck. I don't want this polluting my home folder (more importantly: I don't want 100's of other things like this also polluting my home folder).
> The "Windows way" is to install system-wide to %ProgramFiles%\dagger\ (eg c:\Program files\dagger\dagger.exe), or to install to %LocalAppData%\dagger\ (eg: c:\Users\shykes\AppData\Local\dagger\dagger.exe). The latter is kind of the closest equivalent to $HOME/.dagger on linux. Add whatever folder to the user's PATH environment variable to make it easy to run.
> Honestly, providing just the .zip is better: then Windows users can muck up their own system however they like. Alternatively, package it with something like Scoop [2] which is a fairly popular dev tool, and provides a fairly easy way to get a sane install with updates, versioning and path stuff all handled.
> [1] https://docs.dagger.io/
> [2] https://scoop.sh/

**Comment by gerhard** [comment]
cc @samalba @grouville

**Comment by FilipDeVos** [comment]
You can use long form
`Invoke-WebRequest -UseBasicParsing -url https://releases.dagger.io/dagger/install.ps1 | Invoke-Expression`

With the aliases that exist in powershell you can compress the command down to the following
`iwr -useb https://releases.dagger.io/dagger/install.ps1 | iex`

Since you have TLS 1.0 enabled this should work ok on powershell 3 all the way up to powershell 7.x on pretty much any supported OS. The -UseBasicParsing is needed for machines that don't have internet explorer installed.

**Comment by vardrop** [comment]
RE: [Scoop App-Manifest](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests)
https://gist.github.com/vardrop/a25e0c8e2dc055f86a3ff4dd7a7de309

```shell
scoop install https://gist.github.com/vardrop/a25e0c8e2dc055f86a3ff4dd7a7de309/raw/0b7f1e29454d7d2cbe1ae9d6c807ddfcdacb7feb/dagger.json
```
or

```shell
scoop install https://raw.githubusercontent.com/ScoopInstaller/Main/3e60437a91fbc47fed7dcdd3502de44f9ab66838/bucket/dagger.json
```
Awaiting approval, see also:
ScoopInstaller/Main/pull/3461
ScoopInstaller/Main#3460
