### ISSUE TITLE
✨ Linux installation, proposal for a small improvement

### ISSUE THREAD

**Issue by carmelo0x99** [dagger/dagger#1950]
### What are you trying to do?

Install dagger by following the Linux flow as specified on https://docs.dagger.io:
```
/usr/local $ curl -L https://dl.dagger.io/dagger/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7649  100  7649    0     0   111k      0 --:--:-- --:--:-- --:--:--  109k
sh debug downloading files into /tmp/tmp.r6tBDVdRC5
sh debug http_download https://dagger-io.s3.amazonaws.com/dagger/releases/0.2.4/dagger_v0.2.4_linux_amd64.tar.gz
sh debug http_download https://dagger-io.s3.amazonaws.com/dagger/releases/0.2.4/checksums.txt
install: cannot create regular file './bin/dagger': Permission denied <<< 😢
```
**NOTE**: same result if I run the command above through `sudo`

### Why is this important to you?

- The recommended way leads to an error
- It is safer + saner to download the script (`install.sh`), examine it, then run it

### How are you currently working around this?

1. download the installer script: `curl -LO https://dl.dagger.io/dagger/install.sh`
2. edit it:
```diff install.sh.ori install.sh
294c294,295
<     bin_dir="./bin"
---
> #    bin_dir="./bin"
>     bin_dir="/usr/local/bin"
```
3. after a thorough (!) examination, run it as follows:
```
$ sudo sh ./install.sh
./install.sh debug downloading files into /tmp/tmp.VcGzdCCwUk
./install.sh debug http_download https://dagger-io.s3.amazonaws.com/dagger/releases/0.2.4/dagger_v0.2.4_linux_amd64.tar.gz
./install.sh debug http_download https://dagger-io.s3.amazonaws.com/dagger/releases/0.2.4/checksums.txt
./install.sh info installed /usr/local/bin/dagger <<< 🥳
```

**Comment by carmelo0x99** [comment]
Hi Marcos,
and many thanks for responding to my message. Indeed, I've kind of mixed two separate topics, my bad.
Let me address them one by one.

1. the need for `sudo`
- **doesn't work**: the couple of commands on the documentation page, `sudo` seems necessary anyway (unless one runs the entire installation as `root`)
- **works**: `cd /usr/local` + `curl -L https://dl.dagger.io/dagger/install.sh | sudo sh`
- **even better**:
  - `cd /usr/local`
  - `curl -LO https://dl.dagger.io/dagger/install.sh`
  - educate users to examine the script
  - run the script as `sudo sh ./install.sh`

2. absolute location vs. relative location: I believe it's a best practice to have absolute locations, such as `/usr/local/bin`, instead of relative ones, such as `./bin`. Doing so would also avoid the need to `cd` to directory first.

Thanks!

**Comment by clly** [comment]
I was looking for a way to customize the `bin_dir` which I believe would solve this issue as well. The `install.sh` script is using the `install` command to move the binary into the location. 

To run it from anywhere and install into `/usr/local/bin` you would use `curl -L https://dl.dagger.io/dagger/install.sh | sudo BIN_DIR=/usr/local/bin sh`

I can create a PR with the functionality and have the change locally because I wanted to do it anyway.

Thoughts?

**Comment by samalba** [comment]
> I can create a PR with the functionality and have the change locally because I wanted to do it anyway.
> 
> Thoughts?

Your suggestion makes sense, we'll welcome a PR (feel free to cc me on it)!
