### ISSUE TITLE
✨ Replace Jaeger with generic OTLP Export

### ISSUE THREAD

**Issue by austinlparker** [dagger/dagger#1952]
### What are you trying to do?

Rather than exporting to Jaeger directly, why not output OTLP over gRPC/HTTP in order to support trace data export in a more 'pure' format that can go to the OTel Collector or directly to a tracing system that supports OTLP ingest?

### How are you currently working around this?

I did a local rip/replace of the Jaeger exporter with `"go.opentelemetry.io/otel/exporters/otlp/otlptrace"` and it seems to work fine going to a local collector. Obviously, someone could also use a Jaeger receiver on the collector and transform the trace data that way, but I just thought it'd be neat to skip that step. I'm not sure if there's a reason that Jaeger is being used in the first place other than convenience?

**Comment by austinlparker** [comment]
It looks like everything works in terms of the trace itself, maybe there's stuff in buildkit that's looking for Jaeger to export to, I admit I didn't do a _ton_ of research on how all of these parts work together
<img width="1290" alt="Screen Shot 2022-03-30 at 9 56 44 PM" src="https://user-images.githubusercontent.com/4140740/160960910-c7dc7a78-a0dd-4228-8b1a-b2a46dd22aff.png">
.

**Comment by jlongtine** [comment]
I like this idea. I suspect the original reason for setting this up this way was simply to keep it straightforward so we could just run buildkitd and jaeger as shown here: https://github.com/dagger/dagger/blob/main/tracing.compose.yaml

Seems like we could pretty easily change the code to OTLP export, change the compose file to include an OTel collector that forwarded to Jaeger (or another trace system).

**Comment by austinlparker** [comment]
If you'd like, I can change up the compose file and submit a PR? Probably next week.

**Comment by jlongtine** [comment]
@austinlparker That'd be great! I'll keep an eye out for your PR (and feel free to @ me!).

**Comment by jedevc** [comment]
Hiya, closing this issue out since this is an old one - a lot of our architecture has changed in the meantime, we're now focused on language SDKs instead of CUE :tada:

However, we've recently added support for more complex OTEL support, there's a lot more information in https://github.com/dagger/dagger/pull/6835 about exactly how that works - so I think that should possibly actually resolve the original idea in this issue?

If I've misunderstood, no worries we can re-open! :tada:
