### ISSUE TITLE
🐞 Code blocks in the docs look aliased/distorted on some displays

### ISSUE THREAD

**Issue by alireza-ahmadi** [dagger/dagger#1956]
### What is the issue?

The documentation code blocks use the `Courier New` font, which is relatively old. There aren't any major problems on my retina display, but codes **look aliased on my external non-retina display**. To help you understand better, I took a few screenshots:

#### On non-retina display
![non-retina-w:o-anti-aliasing](https://user-images.githubusercontent.com/1054228/161002404-da13783b-0978-4322-a679-a4b00369d57d.png)

#### On non-retina display + manually editing CSS to enable subpixel-anti-aliasing for code blocks 🎨 
![non-retina-w-anti-aliasing](https://user-images.githubusercontent.com/1054228/161002832-d5595719-d1f8-4259-b63e-451ba038d320.png)

#### On retina display
<img width="730" alt="retina-w:o-anti-aliasing" src="https://user-images.githubusercontent.com/1054228/161003565-1ae29001-d1f8-48c6-b08d-f8978bf9e43e.png">

#### On retina display + manually editing CSS to enable subpixel-anti-aliasing for code blocks 🎨 
<img width="730" alt="retina-w-anti-aliasing" src="https://user-images.githubusercontent.com/1054228/161003695-db113ea5-f912-48f3-ae83-48431430194f.png">

## How can we fix this problem?
If we want to go with the easy and fast route, we can add `-webkit-font-smoothing: subpixel-antialiased` to the CSS of code blocks. This will render the code blocks as shown in the screenshots above (the ones marked with 🎨 ). However, forcing anti-aliasing on older fonts can sometimes [make users uncomfortable](https://www.reddit.com/r/vscode/comments/bs7ju3/how_to_disable_antialiasingcleartype_on_windows/) (AFAIK, the CSS property above only affects macOS/iOS users and this thread is by a Windows user but, I've seen similar complaints from mac users as well).

A better solution is to use a modern font. For example, this is how [Cascadia Code](https://github.com/microsoft/cascadia-code) renders on non-retina display:

![non-retina-modern-font](https://user-images.githubusercontent.com/1054228/161005281-0ad9811d-277e-499e-b3b3-316ed76ba1fd.png)

I didn't submit a PR right away because I wasn't sure whether you wanted to change the font or not. Let me know if I can help in any way.

### Steps to reproduce

1. Go to the [docs website](https://docs.dagger.io/)

### Dagger version

v0.2.4

### OS version

macOS 12.3

**Comment by slumbering** [comment]
Hi @alireza-ahmadi. Many thanks for your report. I've opened a PR #2127 . Let me know if the font has a better rendering.

Have a great day :)

**Comment by alireza-ahmadi** [comment]
@slumbering Thanks for the update. Code blocks are now way more readable.
