### ISSUE TITLE
docs:add comparison between dagger and other ci/cd tools

### ISSUE THREAD

**Issue by pigletfly** [dagger/dagger#1960]
### Why is this important to you?

users want to know the difference between dagger and other ci/cd tools.The below are some tools that I care about:

- tekton
- jenkins
- Drone
- argocd

if someone cares about other tools, please add it in this issue.

**Comment by grouville** [comment]
Thanks @pigletfly, could you please elaborate with the ci/cd tools that would would love to see a comparison with ?

**Comment by pigletfly** [comment]
> Thanks @pigletfly, could you please elaborate with the ci/cd tools that you would love to see a comparison with ?

added

**Comment by shykes** [comment]
Hi, we have a documentation that explains this: https://docs.dagger.io/1002/vs/#dagger-vs-ci-github-actions-gitlab-circleci-jenkins-etc

Unfortunately it is not yet ported to the 0.2 documentation...

**Comment by pigletfly** [comment]
related https://github.com/dagger/dagger/pull/1986
