### ISSUE TITLE
🐞 `go.#Build` is broken by default with go 1.18

### ISSUE THREAD

**Issue by vdemeester** [dagger/dagger#1965]
### What is the issue?

Doing a standard `go.#Build` fails with the following logs: 

This is because of `go` defaulting this flag to `true` and dagger not necessarily send the `.git` in the context (for relatively good reason).

### Log output

4:04PM INF actions.tknlocal.container._exec | #5 0.325 go: missing Git command. See https://golang.org/s/gogetcmd
4:04PM INF actions.tknlocal.container._exec | #5 0.325 error obtaining VCS status: exec: "git": executable file not found in $PATH
4:04PM INF actions.tknlocal.container._exec | #5 0.325  Use -buildvcs=false to disable VCS stamping.

### Steps to reproduce

Create the following plan

```
package foo

import (
	"dagger.io/dagger"
	"universe.dagger.io/go"
)

dagger.#Plan & {
    client: {
        filesystem: {
            "./.": read: contents: dagger.#FS
        }
    }

    actions: {
        build: go.#Build & {
            source: client.filesystem."./.".read.contents
        }
    }
}
```

### Dagger version

dagger devel () linux/amd64 (20220331 build)

### OS version

NixOS unstable

**Comment by dolanor** [comment]
This is something I think we should support as one reason to migrate to Go 1.18 was also for the versioning support (#1859).
I guess we should default to true and pass along the `.git` folder, or let people deactivate it with a flag.

**Comment by helderco** [comment]
> I guess we should default to true and pass along the `.git` folder, or let people deactivate it with a flag.

We're not excluding `.git` 🙂

**Comment by vdemeester** [comment]
A workaround here would be 
```
        _goimage: go.#Image & {
            packages: { git: {} }
        }
        build: go.#Build & {
            source: client.filesystem."./".read.contents
            package: "./cmd/my-binary"
            container: go.#Container & {
                input: _goimage.output
            }
        }
```

So basically, having `git` in the default `go.#Image` would fix the issue.
