### ISSUE TITLE
✨ META: dagger dev DX

### ISSUE THREAD

**Issue by 4x0v7** [dagger/dagger#1992]
### What are you trying to do?

Get up and running as fast as possible with minimal friction

Expect
```sh
git clone https://github.com/dagger/dagger
make mdlint
....
file lint success!
```

Actual
```sh
git clone https://github.com/dagger/dagger
make mdlint
bash: line 1: markdownlint: command not found
make: *** [Makefile:87: mdlint] Error 127
```

### Why is this important to you?

Doing things automatically for a developer lets them get to their innerLoop faster.
Optimise for the LCD (lowest common denominator)

Having to:
lookup markdownlint
find a docker image
write a "docker run" command
so the Make target runs
or
search with a package manager
find the right package and version for my OS and install that package

Takes time. Not a huge amount of time, but it's time that could be spent iterating on the codebase

Why not:
Gather list of reqs
if they are not found on $PATH, try and:
test if docker is installed
Pull a docker image and apk add <tool> or apt-get install <tool> (configurable with Dagger itself)
Use stdin/stdout redirection to run the original command "through" the container
Cache it so it's near instant next run
Offer suggestions to install tool locally (brew install <tool>) and optionally, do that for the user too

Result:
```sh
git clone https://github.com/dagger/dagger
make mdlint
... tool not found locally, checking docker cache
... using tool with container: alpine:3.15
file lint success!
INFO: this tool was not found locally on $PATH, so was run in a Docker container for convenience
INFO: this tool is available to install on your system using: brew install markdownlint-cli
```

Installing dependencies for every conceivable developer machine is probably not that feasible. While a lot of people use docker, we can ever assume it's there. But if it is, use it (or try to).
In the worst case, if docker isn't installed, or can't be used for any reason, you're back to where you started, finding and installing a dependency for your OS

### How are you currently working around this?

```sh
docker run --rm -v ${PWD}:/doclint -w /doclint registry.gitlab.com/pipeline-components/markdownlint:latest mdl ./docs README.md
```

**Comment by gerhard** [comment]
This is a great suggestion! Do you know what would be even more amazing? To run this in Dagger 😀

We started this initiative here, but did not get to this in time for launch. Would you like to help us out @4x0v7 😉

This is how you can make that happen:
1. Learn in 2 minutes [how to contribute to Dagger ](https://github.com/dagger/.github/blob/main/CONTRIBUTING.md)
2. CC @samalba when you open your Dagger PR (he has the most context on this)
3. Enjoy everyone's appreciation for your first Dagger PR 👏🏻

**Comment by aluzzardi** [comment]
👋 

I've actually been working on this on and off for the past few days: https://github.com/dagger/dagger/pull/1984

All linting (Go, Markdown, CUE, Shell) will be done by dagger, and `make mdlint` can go away (or just do a `dagger do lint markdown` instead)

**Comment by 4x0v7** [comment]
Hey @aluzzardi that's aweseome! What better way to learn how Dagger works (and by extension CUE), than helping to abstract away the build system 🗡️ 🐋 🙂 
I'll travel to #1984 and see how I can help it become #2022 💯

**Comment by shykes** [comment]
I have been using `dagger do lint markdown` for the last 2 days, and I can confirm it is awesome :) Never going back to `make`.
