### ISSUE TITLE
🐞 docker: entrypoint not merged when using command args

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#1994]
### What is the issue?

When attempting to use an image containing an entry point:

```
	_image: docker.#Pull & {
		source: "tmknom/markdownlint:0.31.1"
	}

	container: docker.#Run & {
		input: _image.output
		mounts: "source": {
			dest:     "/src"
			contents: source
		}
		workdir: "/src"
		command: {
			args: ["./docs"]
		}
	}
```

I get `actions.lint.markdown.container._exec.args.1: cannot convert non-concrete value string`

Removing `command` works (I get the help message because no arguments were provided):

```
#5 1.189 Usage: markdownlint [options] <files|directories|globs>
```

### Dagger version

main

### OS version

macOS

**Comment by aluzzardi** [comment]
This works properly:

```
		command: {
			name: "markdownlint"
			args: ["./docs"]
		}
```

**Comment by helderco** [comment]
The entry point is in another field, not inside `command`, which is the same as `CMD`. So if you want to use the entry point there, then `command: name: “./docs”`.

**Comment by helderco** [comment]
I had a PR for making `name` optional, but it was closed. Then you could just have those `args` without `name`.

- https://github.com/dagger/dagger/pull/1749

**Comment by aluzzardi** [comment]
Thanks @helderco!

So what I'd like to achieve is `docker run markdownlint docs/foo.md`

This is the current definition:

```
#Lint: {
	// Source code
	source: dagger.#FS

	// shellcheck version
	version: *"0.31.1" | string

	// Files to lint
	files: [...string]

	_image: docker.#Pull & {
		source: "tmknom/markdownlint:\(version)"
	}

	container: docker.#Run & {
		input: _image.output
		mounts: "source": {
			dest:     "/src"
			contents: source
		}
		workdir: "/src"
		command: {
			// FIXME: this should not be required
			name: "markdownlint"
			args: files
		}
	}
}
```

> The entry point is in another field (entrypoint), not inside command, which is the same as CMD. So if you want to use the entry point there, then command: name: “./docs”.

The problem with that is that I would need to split it by hand:

```
command: name: files[0]
command: args: files[1:]
```

Or something

**Comment by helderco** [comment]
Yes, the solution for that would have been https://github.com/dagger/dagger/pull/1749. It was closed in favor of a `command` redesign.

**Comment by helderco** [comment]
You can also use the entrypoint from the image config in the command name to avoid hard coding, until another solution comes along.

**Comment by TomChv** [comment]
I'm closing this issue because it is outdated, our current dagger version correctly merge entrypoint with arguments.
