### ISSUE TITLE
✨ disable colors when log format is plain and dagger is not attached to console (or provide a switch to disable colors in logs)

### ISSUE THREAD

**Issue by godfryd** [dagger/dagger#2001]
### What are you trying to do?

I try to get logs with no colors so it is easy to read dagger logs collected by some CI system.

### Why is this important to you?

It is hard to read when ANSI color codes are displayed in a log when coloring is not available.

### How are you currently working around this?

no workaround, getting json is not an option as it is totally not human readable

**Comment by teddylear** [comment]
Hey! If it's alright I can try to take a look at this.

**Comment by teddylear** [comment]
Actually this is a lot more than I originally thought. If someone else wants to take a look into this, please feel free.

**Comment by slumbering** [comment]
Close this one. Logs has been revamped.
