### ISSUE TITLE
🐞 website renders wrong on mac m1 safari

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2014]
### What is the issue?

https://twitter.com/alexellisuk/status/1510880710294396928

### Steps to reproduce

Visit https://dagger.io on safari on a mac m1.

### Dagger version

should not be required 

### OS version

should not be required

**Comment by gerhard** [comment]
This is what I see on my end:

<img width="1728" alt="Screenshot 2022-04-04 at 11 37 59" src="https://user-images.githubusercontent.com/3342/161527237-33eec018-0ddd-4d8a-b95e-3bf98fa43ecf.png">

- Apple M1 arm64
- macOS v12.3
- Safari v15.4

**Comment by shykes** [comment]
@alexellis are you still experiencing the issue?

**Comment by alexellis** [comment]
I can check later on. Did you deploy a fix?

**Comment by shykes** [comment]
Thanks! I think we were not able to reproduce (cc @slumbering who may have more details & questions).

**Comment by alexellis** [comment]
<img width="1347" alt="Screenshot 2022-04-14 at 07 43 01" src="https://user-images.githubusercontent.com/6358735/163328728-77714472-f2cb-47ab-927a-9c69cf6f5a6b.png">

No change.

**Comment by slumbering** [comment]
Hi @alexellis.

Almost all of our team members are actually using Mac M1 with safari. It's very strange...
Would it be possible for you to do as @gerhard did above please ?

neofetch + safari version + your screen resolution ? 

Thanks again :)

**Comment by slumbering** [comment]
Hi @alexellis ! Ok I have been able to reproduce your bug but with an old Safari (13.1). Is it the one you're using ?

**Comment by slumbering** [comment]
Hi  @alexellis ! The problem has been fixed. Thanks
