### ISSUE TITLE
✨ As a Dagger user, I want to be able to use private keys from the SSH agent to clone private dependencies in order to avoid configuring a username and password or explicit private key

### ISSUE THREAD

**Issue by DWSR** [dagger/dagger#2034]
### What are you trying to do?

As a Dagger user, I want to be able to use private keys from the SSH agent to clone private dependencies in order to avoid configuring a username and password or explicit private key

### Why is this important to you?

This is important in order to publish and maintain privately accessible Dagger modules	

### How are you currently working around this?

Manually cloning repository contents

**Comment by helderco** [comment]
Closing. More context in parent issue: https://github.com/dagger/dagger/issues/2163.
