### ISSUE TITLE
✨ `dagger project info`

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2038]
### What are you trying to do?

Type a simple command that gives me basic information about my Dagger project

* Its location on the filesystem
* Location and status of available plans (do they load ok?)

**Comment by teddylear** [comment]
@shykes If possible I would love to take a look at this!

**Comment by teddylear** [comment]
@shykes Added PR for the first part of this to add a location of dagger project on the filesystem based of cue mod parent path. Please let me know if there are any issues or better testing I should do. 

 As for the second part of this feature, do you want the list of available cue files with `dagger.#Plan` that have [`loadPlan` from `do.go`](https://github.com/dagger/dagger/blob/f3ac279f73907b61f0f00d8e84cb7e8cb92c6e35/cmd/dagger/cmd/do.go#L89) not not error? Is there existing functionality to search for all cue files in a repo, or are they all in the same directory that I could attempt to just loop through and load? Any and all feedback would be helpful here!
