### ISSUE TITLE
✨ Pin down to the CUE node that caused failure

### ISSUE THREAD

**Issue by hongchaodeng** [dagger/dagger#2056]
### What are you trying to do?

Once a CUE action fails, we can't know which CUE node fail specifically.

For example, if I run the following CUE code:

```cue
up: bash.#Run & {
	script: contents: #"""
		some_problem_here
		"""#
}
```

I could tell the `up` command fail from the logs from `dagger do up --log-format plain`.

But dagger as the engine should know that `up` node failed, and can get the stdout/stderr from `bash.#Run`. It would be great if dagger can expose these three things to users: 1. which node failed; 2. failed node's stdout; 3. failed node's stderr.

**Comment by marcosnils** [comment]
I can start taking a look at this one.

**Comment by aluzzardi** [comment]
Added to this epic: https://github.com/dagger/dagger/issues/613

**Comment by marcosnils** [comment]
hey @hongchaodeng! I was testing your example and I see that dagger actually outputs what you're expecting correctly. 

Given the current plan file:
```
-- test.cue --
package main

import (
	"dagger.io/dagger"
	"universe.dagger.io/bash"
	"universe.dagger.io/alpine"
)

dagger.#Plan & {
	actions: {
		// Pull and build alpine container with bash
		_image: alpine.#Build & {
			packages: {
				bash: _
			}
		}

		// Hello World Dagger
		hello: bash.#Run & {
			input: _image.output
			script: contents: """
				some_problem_here
				"""
		}
	}
}
```

This is the output that I'm getting when running `dagger do hello`
```
 dagger do hello 
[✔] actions.hello.script                                                                               0.0s
[✔] actions                                                                                            0.1s
[✗] actions.hello                                                                                      0.1s
#5 0.095 something here                                                                                    
#5 0.095 /bash/scripts/run.sh: line 2: some_problem_here: command not found                                
11:25AM FTL failed to execute plan: task failed: actions.hello._exec: process "bash --norc -e -o pipefail /bash/scripts/run.sh" did not complete successfully: exit code: 127
```

As you can see from the output, by defualt I can see what node failed, and the stdout and stderr from the `#Run` action. Is there anything you think we could do to improve the output here?

**Comment by hongchaodeng** [comment]
Can I get it via a key: `dagger query actions.hello.stdout`

**Comment by marcosnils** [comment]
> Can I get it via a key: `dagger query actions.hello.stdout`

starting dagger 0.2 (Europa) `dagger query` is not a thing anymore

**Comment by hongchaodeng** [comment]
I know. That's what I am missing as described in this issue -- pinning down to the specific node for errors:

> It would be great if dagger can expose these three things to users: 1. which node failed; 2. failed node's stdout; 3. failed node's stderr.

**Comment by mircubed** [comment]
reassign to @dolanor to confirm if we should close or not.

**Comment by aluzzardi** [comment]
@marcosnils I think this might have fixed by the changes you made a while ago (logger error messages), right? If that's the case we can close this

**Comment by dolanor** [comment]
I'm closing this. It seems @marcosnils fixed part of it, and from my last message, it seems all the info are available in the last lines of the log.

If you feel there is still something missing @hongchaodeng , don't hesitate to reopen.
