### ISSUE TITLE
`dagger do`: load local directory in command-line flag

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2063]
## Overview

As an end-user, if an action has an incomplete field of type `dagger.#FS`, I want to be able to set it from the command-line, for example:

```
actions: build: {
  source: dagger.#FS
  ...
}
```

```
dagger do build --source ./src
```

**Comment by jlongtine** [comment]
@mircubed Haven't thought about this in a while, so no update currently. I'm not sure how this is related to error messages, but I'm happy to have @dolanor take it over, if he's got interest + bandwidth.

**Comment by mircubed** [comment]
Sorry meant to say "user pain" vs error messages due to DX tag.
