### ISSUE TITLE
Dagger 0.1 docs do not make it clear that they are outdated

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2068]
### What is the issue?

There should be a banner at the top of every Dagger 0.1 documentation page saying "This page is for Dagger 0.1 and is now outdated, for up-to-date documentation, see <link>".

**Comment by marcosnils** [comment]
Should be fixed by https://github.com/dagger/dagger/pull/2066

**Comment by slumbering** [comment]
Duplicate #1830
