### ISSUE TITLE
🐞 "FTL" is confusing in error messages

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2079]
### What is the issue?

Error messages start with the word "FTL", for example:

```
5:15AM FTL failed to execute plan: task failed: actions.lint.markdown._exec: process "/home/nonroot/entrypoint.sh markdownlint ./docs README.md" did not complete successfully: exit code: 1
```

Several people have asked me "what does FTL mean"? The answer is "fatal error". But clearly that is not at all obvious.

### Log output

-

### Steps to reproduce

Run `dagger do` of an action that fails. Look at output.

### Dagger version

dagger devel (fb3eafb6) linux/amd64

### OS version

Linux ip-172-31-39-148 4.19.0-16-cloud-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 Linux

**Comment by marcosnils** [comment]
FTL is something we're handling for the plain logger. Would renaming to FATAL should be enough?

**Comment by dolanor** [comment]
In another issue, I think @shykes talked about putting ERR or error. The fact that it is a panic, fatal or error is a granularity that is not interesting for end users.

**Comment by shykes** [comment]
> In another issue, I think @shykes talked about putting ERR or error. The fact that it is a panic, fatal or error is a granularity that is not interesting for end users.

I don't remember saying that specifically, but I do agree it would be slightly better. Generally it would be nice for users to get a "regular" terminal UX, instead of feeling like they are tailing log files. In other words, yes it's better if they're tailing readable log files, but even better if they're not tailing log files at all.
