### ISSUE TITLE
how to execute in a private AWS VPC

### ISSUE THREAD

**Issue by mikestaub** [dagger/dagger#2089]
### What is the issue?

Part of our CI pipeline is executing code in a private AWS VPC, how can this be done?

**Comment by gregwebs** [comment]
@mikestaub did you have any particular issues that came up? To reach the internet you will need a NAT gateway or an IPV6 egress-only gateway.

**Comment by d3rp3tt3** [comment]
@mikestaub , I am closing this since I think you have the answer. Please comment here if you're blocked. Thank you!
