### ISSUE TITLE
✨ Explicit `dagger project update` usage

### ISSUE THREAD

**Issue by TomChv** [dagger/dagger#2091]
### What are you trying to do?

There is a lost of users who can't run `hello world` example or any other example in the docs because they forgot to tip `dagger project update`.

It is not explicitly explained in the doc and there is no tip in the CLI.

What would be awesome is that you have a small message after `dagger project init` to remember you to tip `dagger project update` to install dagger dependencies.

Example
```shell
$ dagger project init
Project initialised! To install dagger universe, run : dagger project update
```

### Why is this important to you?

It's a common mistake that break on-boarding flow.
As a user, it should be easier to do a simple plan or copy/paste something from the doc and run it.

### How are you currently working around this?

Explain directly to users what to do

**Comment by TomChv** [comment]
I know it's a really small change but since it's about UX, I'm pinging you @shykes

**Comment by helderco** [comment]
Yes, and `update` could also output a success message or something. You wonder if it did anything.

**Comment by TomChv** [comment]
Agreed!
