### ISSUE TITLE
🐞 all PreRunner execute in prepare stage

### ISSUE THREAD

**Issue by sword-jin** [dagger/dagger#2093]
### What is the issue?

speaking this is not a bug strictly, maybe can change a `kind/enhancement` tag

### Log output

no need

### Steps to reproduce

In official example `todoapp`, run `dapper do build`, The following two runners will be called:

- client.filesystem."./".read
- actions.deploy.container.script._load

the first `PreRun` is excepted, but second in `deploy` stage, maybe can optimization by some logical judgments.

### Dagger version

dagger devel (def93a29) linux/arm64

### OS version

macOS

**Comment by jedevc** [comment]
This issue looks specific to 0.1 of dagger, which used cue - we've now switched away from this approach, see https://docs.dagger.io/quickstart/562821/hello :tada:

Feel free to shout if you're interested or need a hand migrating to the new architecture!
