### ISSUE TITLE
✨ Add CUE syntax highlighting support to highlight.js which is used by Discord

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2107]
### What are you trying to do?

Add CUE syntax highlighting support to highlight.js which is used by Discord in code blocks.

### Why is this important to you?

Highlighted code is more readable and pleasant to look at for many users.

### How are you currently working around this?

Today, I often hijack the typescript to render CUE code with some syntax highlighting, but there should be proper support for CUE.

e.g.

```
```typescript
      params: {
            imageBuild: {
                ref:  "<dockerhubusername>/alptest"
                tag?: string
            }
            imagePush: imageBuild & {
                auth: {
                    username: "<dockerhubusername>"
                    secret:   _registrySecret.output
                    //secret: client.env.REGISTRY_SECRET
                }
            }
        }
```
```

**Comment by jpadams** [comment]
related in cue project:
https://github.com/cue-lang/cue/issues/1332
https://github.com/cue-lang/cue/issues/142

related in dagger project:
https://github.com/dagger/dagger/issues/825

**Comment by jpadams** [comment]
https://prismjs.com/

**Comment by maert** [comment]
Since typescript looks pretty good, I thought to use that as a basis for the cuelang syntax: https://github.com/highlightjs/highlight.js/blob/main/src/languages/typescript.js

**Comment by jpadams** [comment]
https://discord.com/channels/707636530424053791/962838575504826368

**Comment by jpadams** [comment]
https://github.com/shikijs/shiki/blob/main/packages/shiki/languages/cue.tmLanguage.json

**Comment by aluzzardi** [comment]
If it helps, a while ago I hacked together a Prism.js syntax file (used by our docs site): https://github.com/dagger/dagger/blob/main/website/src/theme/prism.cue.js

I just stitched together some bits from the Swift and Go syntax definitions
