### ISSUE TITLE
Incorrect link to core actions

### ISSUE THREAD

**Issue by ivorscott** [dagger/dagger#2111]
### What is the issue?

1. The Dagger [core action reference page](https://docs.dagger.io/1222/core-actions-reference) has an incorrect link to the core actions page.

Incorrect link shown: https://docs.dagger.io/core-concepts/1221-action
Should be: https://docs.dagger.io/1221/action 

2. The [Dagger actions page](https://docs.dagger.io/1221/action) has an incorrect link to the plan structure page.

Incorrect link shown: https://docs.dagger.io/1221/action/1202-plan
Should be: https://docs.dagger.io/1202/plan

**Comment by slumbering** [comment]
Hi @ivorscott :)! Thank you very much to report this issue.

Would you be keen to fix it by opening a PR ? Otherwise I'll do it, not a problem. Let me know

Have a great day
