### ISSUE TITLE
🐞 Windows with rancher-desktop docker failing with: cannot find package "dagger.io/dagger"

### ISSUE THREAD

**Issue by 4x0v7** [dagger/dagger#2112]
### What is the issue?

I've been trying to figure out what's going on here..
I'm on Windows 10, and can't seem to get dagger to work
```
dagger do build
4:24AM FTL failed to load plan: import failed: cannot find package "dagger.io/dagger":
    C:\Users\agw\git\dagger-src\ci.cue:4:2
: running `dagger project update` may resolve this
```
I've run through a few things already, `project init`ing `project update`ing
Destroying and recreating the docker host; I'm using Rancher Desktop v1.2.1 so blowing away `ext4.vhdx` and deleting the wsl distros with `wsl --unregister rancher-desktop; wsl --unregister rancher-desktop-data` should get a clean docker slate.

I'm using `scoop.sh` to install dagger, if that's something that might make a difference

I though I'd see what happens in CI, so I used Cirrus CI to try running a Windows Container with dagger.
That fails too as it's trying to pull a windows image of buildkit, which as far as I can tell, isn't a thing

[Logs from Cirrus CI](https://cirrus-ci.com/task/5847094165504000?logs=install_scoop_base_scoop_then_dagger_then_dagger_do#L64)

Relevant section:
```
{
    "level": "error",
    "version": "v0.10.0",
    "error": "exit status 1",
    "output": "v0.10.0: Pulling from moby/buildkit no matching manifest for windows/amd64 10.0.17763 in the manifest list entries",
    "time": "2022-04-10T16:08:41Z",
    "time": "2022-04-10T16:08:41Z",
    "caller": "/home/runner/work/dagger/dagger/util/buildkitd/buildkitd.go:179",
    "message": "failed to pull buildkit image"
}
```

I'm a little stumped.. I'm going to try on Windows 11 to see if it's any different

Docker info:
```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.4.1)
  scan: Docker Scan (Docker Inc., v0.16.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: 52b36a2dd837e8462de8e01458bf02cf9eea47dd
 init version:
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Rancher Desktop WSL Distribution
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.763GiB
 Name: X36
 ID: AAWL:C6IF:OWVY:INXS:4X45:P7ER:7RO6:4FY2:U2IU:67YT:3HJC:JLB5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: 4x0v7
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```
```
docker ps
CONTAINER ID   IMAGE                   COMMAND       CREATED         STATUS         PORTS     NAMES
9119bf3e94f4   moby/buildkit:v0.10.0   "buildkitd"   5 minutes ago   Up 5 minutes             dagger-buildkitd
```

### Log output

```
dagger do build
4:24AM FTL failed to load plan: import failed: cannot find package "dagger.io/dagger":
    C:\Users\user\git\dagger-src\ci.cue:4:2
: running `dagger project update` may resolve this
```

### Steps to reproduce

```
gh repo clone dagger/dagger dagger-src
cd dagger-src
dagger project init
dagger project update
dagger do build
```

### Dagger version

dagger 0.2.5 (7d2f279c) windows/amd64

### OS version

Windows 10 Version 21H2 (November 2021 Update) OS Build 19044.1586

**Comment by 4x0v7** [comment]
Also to note, LCOW (Linux Containers on Windows) is [deprecated](https://docs.microsoft.com/en-us/troubleshoot/windows-server/containers/support-for-windows-containers-docker-on-premises-scenarios)
Cirrus are using [windows-2019-core-for-containers](https://github.com/cirruslabs/vm-images/blob/master/googlecompute/windows_images.json#L8) running on [Mirantis Container Runtime](https://cirrus-ci.com/task/5847094165504000?logs=echo_docker_debug_info#L9)

**Comment by 4x0v7** [comment]
I can reproduce this on Windows 11 21H2 OS Build 22000.953

```sh
dagger do build
5:26AM FTL failed to load plan: import failed: cannot find package "dagger.io/dagger":
    C:\Users\user\git\dagger-src\ci.cue:4:2
: running `dagger project update` may resolve this
PS C:\Users\user\git\dagger-src> docker ps
CONTAINER ID   IMAGE                   COMMAND       CREATED         STATUS         PORTS     NAMES
3acfa76d37c5   moby/buildkit:v0.10.0   "buildkitd"   5 minutes ago   Up 5 minutes             dagger-buildkitd
PS C:\Users\user\git\dagger-src> docker logs 3acfa76d37c5
time="2022-04-10T17:21:04Z" level=info msg="auto snapshotter: using overlayfs"
time="2022-04-10T17:21:04Z" level=warning msg="using host network as the default"
time="2022-04-10T17:21:04Z" level=info msg="found worker \"u19ssqj7p9l0k4zvipk4ctir0\", labels=map[org.mobyproject.buildkit.worker.executor:oci org.mobyproject.buildkit.worker.hostname:X47 org.mobyproject.buildkit.worker.network:host org.mobyproject.buildkit.worker.oci.process-mode:sandbox org.mobyproject.buildkit.worker.snapshotter:overlayfs], platforms=[linux/amd64 linux/amd64/v2 linux/amd64/v3 linux/amd64/v4 linux/386]"
time="2022-04-10T17:21:04Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
time="2022-04-10T17:21:04Z" level=info msg="found 1 workers, default=\"u19ssqj7p9l0k4zvipk4ctir0\""
time="2022-04-10T17:21:04Z" level=warning msg="currently, only the default worker can be used."
time="2022-04-10T17:21:04Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
```

**Comment by jpadams** [comment]
Hi, @4x0v7! 👋 Your repro suggests (to me) that you are running dagger do build within your clone of the dagger/dagger github repo in order to use the build action inside of the plan in ci.cue, correct?

Is that your goal? To run build a dagger binary? I believe we are using GitHub Actions as the CI runner for that with additional env vars and other things in place to drive the process.

Or do you want to run dagger do on another cue file you have?

**Comment by 4x0v7** [comment]
@jpadams Yes that's correct. Should I expect it to work? It works great on my linux installs, which is what leads me to think this is a Windows issue, and what lead me to trying to repro on a CI system.
Seems @cdhunt has been running up against the same error too in some scenarios.

It's not just `dagger do build` either, _any_ `dagger do` command fails with the same message.
My real goal was just to run `dagger do lint markdown` as per #1992

**Comment by 4x0v7** [comment]
Closing this after discord discussion with @cdhunt 
It's actually just a dupe of https://github.com/dagger/dagger/issues/1820
