### ISSUE TITLE
✨ why not support other http verb

### ISSUE THREAD

**Issue by sword-jin** [dagger/dagger#2121]
### What are you trying to do?

In the pipeline end, i need post some data to our internal api to report dagger result.

**Comment by helderco** [comment]
Thank you for your feedback. 

In the meantime, you can create a custom action to use curl (or something else) to do that.

**Comment by rrylee** [comment]
> Thank you for your feedback. 
> 
> 
> 
> In the meantime, you can create a custom action to use curl (or something else) to do that.

thank you

I know dagger don't support it now. I just want to know what the official team is for. 😊

**Comment by slumbering** [comment]
👋 @rrylee 

supporting http verb is definitely in our pipe ;).
