### ISSUE TITLE
VSCode extension

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2132]
### VSCode extension

> I'd like a proper integration with the Language Server Protocol and a nice VSCode extension that comes with it. It's important for CUE and libraries added by Dagger. I spend too much time reading through the library code base to know what I can use, ideally VSCode could auto-complete everything nicely.

_Originally posted by @samalba in https://github.com/dagger/dagger/discussions/2052#discussioncomment-2512196_

**Comment by gerhard** [comment]
FWIW https://twitter.com/solidnerd/status/1519214764756455425

**Comment by marcosnils** [comment]
> FWIW https://twitter.com/solidnerd/status/1519214764756455425

It's a nice intermediate solution until we can get a fully fledged LSP solution :rocket:
