### ISSUE TITLE
Core action to check that a file exists

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2135]
## Problem

Sometimes I want to check if a file exists. There is not core action to do this: `core.#ReadFile` will simply fail if the file doesn't exist, causing my entire execution to stop.

## Solution

Two possible options:

* Add `core.#Stat` to return information about a path: whether it exists, whether it's a file or regular directory, permissions, etc.
* Extend `core.#ReadFile` to support a default value `contents: string | *null`. If the file doesn't exist, then the default value is set.

## Use case

For reference, my use case is to improve todoapp example such that 1) if local directory has a `package.json`, use it as app source code, 2) otherwise fetch the todoapp example from upstream repo.

**Comment by jlongtine** [comment]
It should be pretty straightforward to add `core.#Stat` using this: https://github.com/dagger/dagger/blob/15176acc9dfcd9294867d427193696bd5572303b/solver/fs.go#L30

**Comment by jpadams** [comment]
+1 to this. We could use this today.

cc @Siafu

**Comment by shykes** [comment]
Adding to cuelite backlog for triage @mircubed @helderco
