### ISSUE TITLE
✨ Dagger 0.2 Lua Package

### ISSUE THREAD

**Issue by teddylear** [dagger/dagger#2137]
### What are you trying to do?

Have reusable dagger commands for lua for linting/formatting checks using `stylua` and `luacheck`

### Why is this important to you?

Makes creating CIs for lua projects easier to lua/neovim community

### How are you currently working around this?

None

**Comment by d3rp3tt3** [comment]
@teddylear added this as part of this PR: https://github.com/dagger/dagger/pull/2138
