### ISSUE TITLE
Improve Console UI

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#2139]
## Console UI

The console experience (e.g. status of `dagger do`) is not great. Oftentimes, we have to resort to `--log-format plain --log-level debug` because the default suppresses important information. In no particular order:

- [x] #2444
- [ ] #2147
- [x] #449
- [ ] #2283
- [x] #2491
- [x] #2492
- [ ] It's not clear what's going on, the list of actions is confusing. Currently the CUE path of all "actions" is displayed. I think there are ways to make it better: perhaps group actions by top-level action? Maybe group by action defined in the current package (e.g. don't show sub-actions of imported packages)

_Originally posted by @aluzzardi in https://github.com/dagger/dagger/discussions/2052#discussioncomment-2512329_

**Comment by shykes** [comment]
The “some errors are suppressed” issue is major. I am affected all the time, and have seen several users affected as well. It makes almost all debugging sessions worse. Standalone issue: https://github.com/dagger/dagger/issues/2147

**Comment by helderco** [comment]
> I am affected all the time

Yeah, me too 🙂

**Comment by RonanQuigley** [comment]
Just to add to this, there does not seem to be a way to "bubble up" logs from when commands are executed inside of a docker container. This is really important for diagnosing why a plan is going wrong. 

```
package simple

import (
    "dagger.io/dagger"
    "universe.dagger.io/alpine"
    "universe.dagger.io/docker"
)

dagger.#Plan & {

    actions: {
        image: alpine.#Build & {
            packages: {}
        }
        run_simple: docker.#Run & {
            input: image.output
	        command: {
				name: "sh"
				flags: "-c": "echo date" // the date will not show up in your logs!
			}
        }
    }
}
```

**Comment by shykes** [comment]
Can we create individual issues for each part of this?

**Comment by sipsma** [comment]
https://github.com/dagger/dagger/issues/2283 should maybe be part of this epic, though it's more obscure than the existing issues here

**Comment by shykes** [comment]
Is someone working on this at the moment?

**Comment by dolanor** [comment]
Yes I am, working on the TTY rendering after investigating some time to maybe use some other logger/TUI interface.
It seems more about some logic that is wrong.
I wanted to add some test to have an idea of what was going on, but I would have to have some advanced mock because in the end, it's all syscall checking if the FD is a TTY.
So now, I'm debugging step-by-step to figure out where we are missing some grouping/terminal size computation, or things of this sort.

**Comment by dolanor** [comment]
Right now, the TTY output seems to only display a live log of one task. (maybe my test case doesn't trigger a way to display 2 tasks at a time).
Is that something we want? do we want to display as many parallel tasks live log at the same time?

/cc @aluzzardi

**Comment by shykes** [comment]
I added #2491 to the list.

**Comment by shykes** [comment]
Added #2492 as well

**Comment by shykes** [comment]
> Right now, the TTY output seems to only display a live log of one task. (maybe my test case doesn't trigger a way to display 2 tasks at a time). Is that something we want? do we want to display as many parallel tasks live log at the same time?
> 
> /cc @aluzzardi

I think we should consider not showing any live logs *by default*.

**Comment by aluzzardi** [comment]
> Right now, the TTY output seems to only display a live log of one task. (maybe my test case doesn't trigger a way to display 2 tasks at a time).
Is that something we want? do we want to display as many parallel tasks live log at the same time?

It's displaying the live logs of all tasks that are currently active. Number of lines per task is dynamically computed based on # of running tasks / term height.

**Comment by shykes** [comment]
I'm closing this, since it's not actively being worked on now. There are other issues related to improving various aspects of the console UI, logs etc.
