### ISSUE TITLE
`dagger test`: first class testing in Dagger

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#2141]
### Dagger TDD/BDD as first class concept

---

We can create a Dagger definition and a plan to test that new definition using bash/bats, like dagger team does in universe package.    
I would like Dagger introduce tdd/bdd using cue syntax

```yaml
dagger.#Spec & { // Like Dagger plan
  "removeSNames": dagger.#Describe & {
    "should remove all S names": dagger.#It & {
       // verify definition
     }
  
    "should not remove other names": dagger.#It & {
        // verify definition
     }

     "should mind the case": dagger.#It & {
       // verify definition
     }
  } 
}
```

For the command line:
`dagger test removeSNames`

_Originally posted by @Alvise88 in https://github.com/dagger/dagger/discussions/2052#discussioncomment-2513355_

**Comment by shykes** [comment]
I'm closing this, because it's CUE-specific and we're not adding new features to the CUE API. Additionally, in Dagger 0.3 we are taking a new direction with SDKs and a GraphQL API.
