### ISSUE TITLE
Jetbrains / Intellij plugin

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#2143]
### Jetbrains / Intellij plugin
(similarly to VSCode extension above)

There is an existing plugin here that provides cue support: https://github.com/monogon-dev/intellij-cue but unfortunately does not seem to be updated. Could be used as a base though?

References:
* https://plugins.jetbrains.com/plugin/16126-cue (which is https://github.com/monogon-dev/intellij-cue)
* discussion on intellij tracker: https://youtrack.jetbrains.com/issue/IDEA-242301
* discussion on the cue tracker: https://github.com/cue-lang/cue/issues/250

Also worth noting: it is apparently possible to load a VSCode extension (https://github.com/cue-sh/vscode-cue) in Intellij using TextMate Bundle (pretty sure there are some caveats but).

_Originally posted by @dubo-dubon-duponey in https://github.com/dagger/dagger/discussions/2052#discussioncomment-2512524_

**Comment by shykes** [comment]
Since we have #2132 as high priority, I think this is a logical follow-up.
