### ISSUE TITLE
✨ doc code block embed full files with scoping (like Go present slides)

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#2150]
### What are you trying to do?

I know the person who created this PR: https://github.com/facebook/docusaurus/pull/3558
I just asked him how hard it would be to implement a scoped embedding like the [Go present tools use](https://pkg.go.dev/golang.org/x/tools/present#hdr-Command_Invocations)

### Why is this important to you?

Then we could dump our `.cue.fragment` files, and only use the full file that we could run tests on, but that we could scope with markups to just present the part we want to highlight.
There is already highlighting that exists, but sometimes, you don't want to show the whole file if it's too big.

### How are you currently working around this?

Verifying the `.fragment` still represent the actual cue files that are tested (I believe)

**Comment by dolanor** [comment]
It is already nice to only show part of the file based on lines, but it can be problematic if we change the source without updating the extracted lines. We could then show the wrong lines in the documentation, and we have no way to test that automatically.
And unless we verify it manually, it might break the docs website.

In Go present, you can add specific comment in the source code that can act as markups
```go
func DocumentedFunction() {
// uninteresting init var
str := "test"

// interesting part start OMIT
strings.Split(str, ",")
// interesting part end OMIT
}
```
The OMIT will remove this comment from the embedded source code, and the name of the comment will allow you to scope the embedding to just the `strings.Split()` line. It is done as:
```
.code test.go /start OMIT/,/end OMIT/
```
2 regexp separated by `,` to specify the beginning and the end.

**Comment by TomChv** [comment]
We actually support this feature in our documentation, this issue can be closed
