### ISSUE TITLE
Guide: using the docker package

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2153]
### What is the issue?

The `universe.dagger.io/docker` package is so widespread, it deserves its own guide for explaining how to use it, showing common patterns, etc.

**Comment by Vrashabh-Sontakke** [comment]
> ### What is the issue?
> The `universe.dagger.io/docker` package is so widespread, it deserves its own guide for explaining how to use it, showing common patterns, etc.

Hi, I am a newbie learning DevOps. I've been using Docker for a month now and I can tell I'm pretty good at using it. 
I'm really eager to contribute, please mentor me to begin writing the documentation.

**Comment by samalba** [comment]
@grouville Would you be ok to take this one?

**Comment by grouville** [comment]
> @grouville Would you be ok to take this one?

With pleasure 😇

**Comment by helderco** [comment]
Sorry @samalba, I wasn't able to finish this before my vacation last week, but I have a WIP.
