### ISSUE TITLE
How can we use our own repo for packages?

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#2175]
### What is the issue?

@vandlol is wondering how can he use his own repository to store & use dagger packages. This sounds like a great FAQ to me.

**Comment by helderco** [comment]
This should be answered in the guide about package management. @grouville is working on it.

**Comment by gerhard** [comment]
By the way, I think that this question is also related: https://github.com/dagger/dagger/pull/2159#issuecomment-1098163412
