### ISSUE TITLE
Document how to create an action in any language

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2178]
### What is the issue?

From [feedback on twitter](https://twitter.com/pokgak73/status/1514294555465564162?s=21&t=VC1rno1RSrwRpqaa1q6FCw):

> Oh and apparently you can write Dagger actions in "Python, Go, TypeScript, Ruby, Java, and shell scripts".
>
> @dagger_io how do I do this? I cannot find any docs on your site on how to write Dagger actions in those language. My first impression was you MUST use Go for it.

**Comment by usrme** [comment]
Though certainly nothing to consider this complete, there's a small example on the homepage next to the "Create actions with any programming language" section:

![Screenshot 2022-04-14 at 18-46-54 dagger io](https://user-images.githubusercontent.com/5902545/163426357-2162267e-92b1-4bea-9e3c-c3279cf4a09f.png)

Adding that as an actual example to the documentation would be a great starting point to clue people in.

**Comment by samalba** [comment]
Agreed, and I would also include an example about keeping the scripts external to the CUE code.
