### ISSUE TITLE
✨ Better Error Message for Shadowed Variable

### ISSUE THREAD

**Issue by ivorscott** [dagger/dagger#2180]
### What are you trying to do?

I created a custom package, imported it and tried the following but received an error.

```go
package main

import (
    "dagger.io/dagger"
    "github.com/ivorscott/helloworld/pkg/hello" // my custom package
)

dagger.#Plan & {
    // Say hello by writing to a file
    actions: {
        hello: hello.#AddHello & {. // <--- WON'T WORK - VARIABLE IS SHADOWED BY PACKAGE NAME
            dir: client.filesystem.".".read.contents
        }
    }
    client: filesystem: ".": {
        read: contents: dagger.#FS
        write: contents: actions.hello.result
    }
}
```
The error was caused by a shadowed variable but I couldn't understand this from the error message. 

### Why is this important to you?

The error message didn't help me resolve the issue. Here's the message:

<img width="1063" alt="Screen Shot 2022-04-13 at 20 02 29" src="https://user-images.githubusercontent.com/1488558/163242467-4e9b2a85-009a-4f02-93af-0b643fc4efcd.png">

I would expect an error message that explained the existence of a shadowed variable.

## Solutions: 

1. Change the action name.

```
    actions: {
        hi: hello.#AddHello & {
            dir: client.filesystem.".".read.contents
        }
    }
```
2. Use quotes.
 
```
    actions: {
        "hello": hello.#AddHello & {
            dir: client.filesystem.".".read.contents
        }
    }
```

**Comment by aluzzardi** [comment]
@jlongtine @helderco Is this something we could report upstream?

I just tried this: `source: source`

- `v.ReferencePath()` says it's not a reference
- `v.Err()` says there is no error

Doesn't seem there's a way for us to detect this on our end.

**Comment by berryp** [comment]
This is gonna come up a LOT. It's just not something we're used to worrying about in most other environments and I get stung by this every time I pick up something new to do in Dagger.

**Comment by TomChv** [comment]
I'm closing this issue since we're no longer working on the Cue SDK, please check our documentation to quickstart with our new version: https://docs.dagger.io/
