### ISSUE TITLE
🐞 Can't access Minikube with docker.#Run

### ISSUE THREAD

**Issue by lyzhang1999** [dagger/dagger#2194]
### What is the issue?

I tried to use Minikube as Kubernetes cluster, and mount kubeconfig in docker.#Run, but It can't access Minikube Kubernetes api server.

I tried to use KiND, It worked. so I want to know if we have any solution for access Minikube with docker.#Run or bash.#Run.

### Log output

4:26PM INF actions.test.run._exec | #3 3.141 The connection to the server 127.0.0.1:51686 was refused - did you specify the right host or port?
4:26PM INF actions.test.run._exec | #3 3.595 The connection to the server 127.0.0.1:51686 was refused - did you specify the right host or port?
4:26PM INF actions.test.run._exec | #3 4.007 The connection to the server 127.0.0.1:51686 was refused - did you specify the right host or port?
4:26PM INF actions.test.run._exec | #3 4.404 Error: Kubernetes cluster unreachable: Get "https://127.0.0.1:51686/version": dial tcp 127.0.0.1:51686: connect: connection re

### Steps to reproduce

Docker version: 4.4.2 (73305)
Dagger version: dagger devel (e2c2213a) darwin/arm64
buildkit: automatic set by dagger
Minikube version: v1.25.2(latest)

```
minikube start
# get kubeconfig without certificate file
kubectl config view --flatten --minify
```
mount kubeconfig file to dagger acton, and run.

### Dagger version

dagger devel (e2c2213a) darwin/arm64

### OS version

macOS12.2.1 M1

**Comment by TomChv** [comment]
Same for me, I have to use [`kind`](https://kind.sigs.k8s.io) to use a Dagger with a local Kubernetes cluster

**Comment by renuy** [comment]
tried with minikube start --embed-certs=true , that also fails.

**Comment by helderco** [comment]
Even though this was for v0.2, this looks like container-to-host networking, which is tracked here:
- https://github.com/dagger/dagger/issues/4080
