### ISSUE TITLE
`dagger.io/dagger` tests should follow same dir structure as `universe.dagger.io`

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2201]
From discord:
Q. I'm not seeing any tests (.cue, .bats)  in `dagger.io/dagger` or `dagger.io/dagger/core` like we have in `universe.dagger.io packages`. I often look to those for example usage. Was looking just now to answer a question from user about `core.#Export`

A.`dagger.io/dagger` and `dagger.io/dagger/core` etc tests are currently in the `[dagger/dagger/tests](https://github.com/dagger/dagger/tree/main/tests)` folder. 

From @aluzzardi:
Improvement: We should probably follow the same structure in both ... core predates universe, we improved the organization of tests but never backported old tests

**Comment by mircubed** [comment]
I am going to close this for now, but we can reopen when we focus on universe
