### ISSUE TITLE
Update examples to latest dagger version (automate this?)

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2205]
### What is the issue?

https://docs.dagger.io/1200/local-dev

0.2.4 listed in examples, would be ideal if this was latest release (0.2.6 when this was written).

Could this be automated easily/reliably?

**Comment by jpadams** [comment]
I've seen this done often via PR. Need to check if in automation.

@samalba @marcosnils ?

**Comment by samalba** [comment]
@gerhard has a draft PR for this: https://github.com/dagger/dagger/pull/2369

I agree this is needed.
