### ISSUE TITLE
✨ Add Github Codespaces configuration

### ISSUE THREAD

**Issue by berryp** [dagger/dagger#2216]
### What are you trying to do?

I'm using Github Codespaces to write contributions for the Dagger repo, but the default Codespaces environment is general purpose and so isn't tailored for this specific repo. It would be useful to have a fixed Codespaces configuration for this repo for repeatable dev environments on any branch.

### Why is this important to you?

I can easily work on this repo without having to make sure I have my dev environment set up correctly. Additionally every branch I work on will always have a version of Dagger compiled from that branch's head.

### How are you currently working around this?

I have to create new config files for each new branch and make sure I don't commit them if making a pull request.

**Comment by michealbenedict** [comment]
love this contribution -- thanks!
