### ISSUE TITLE
✨ Adopting Dagger shouldn't make it harder for a user/project independently to use CUE. And vice versa.

### ISSUE THREAD

**Issue by jpluscplusm** [dagger/dagger#2219]
### What are you trying to do?

I'm building a system.

Because CUE is awesome, I want this system to use CUE.

Because Dagger is awesome, I want the people building this system to use Dagger to build it.

Because I am awesome, I want both my users and developers to have a great DevX. This means I'd like characteristics like:

- the ability to sit in the root of the project and use the project with commands like `./bin/foo` and `cue def .:my-cool-project`
- the ability to sit in the root of the project and use the Dagger-Do'd commands like `dagger do wibble`

... and it'd be nice to have

- a file-system view that exposes the fact that Dagger's used (e.g. `dagger.cue` is present)

# My suggestion

These are merely *light* suggestions to help with the core problem, as stated throughout this Issue. The core problem is "the problem", and can of course be solved any which way :-)

Change the `dagger` CLI's param -> "which package should I be looking at?" logic so it aligns its invocation with the `cue` CLI:

- if a `.:foo` positional (not `-p`, flag-based) param is detected, use it like the `cue` CLI does, as stating the CUE package
- Make `-p` (or perhaps introduce some other param) use the same CUE package syntax as the `cue` CLI (to align users' muscle memory with `cue`):

```shell
$ head -1 *.cue
==> dagger.cue <==
package asdface

==> foo.cue <==
package wibble
$ cue vet .:asdface
some instances are incomplete; use the -c flag to show errors or suppress this message
$ dagger do .:asdface
FTL failed to load plan: found packages "asdface" (dagger.cue) and wibble (foo.cue)
$ dagger do -p .:asdface
FTL system | failed to load plan: stat /home/user/project/.:asdface: no such file or directory
$ dagger do -p dagger.cue
[ .. success .. ]
```

- Instead; perhaps make the `-p` param pick up a file, discover the package, and then use standard CUE "look at ALL the files" package discovery logic to expand out the definition of the plan. (Right now, each `-p` looks at the contents of a single file, and whilst it `-p`s can be repeated to expand the scope that the Dagger CLI examines, that's at odds with the CUE norms. 

### Why is this important to you?

Dagger and CUE go hand in hand. As more projects choose to use either, the "wow, that's awesome!" / network effect will increase the adoption of the other.

I think it's important that Dagger anticipate this, and doesn't simply stake a claim to the CUE contents of a project's top-level directory - whilst still allowing for nice DevX characteristics.

### How are you currently working around this?

Right now, being nice to developers and users simultaneously, running Dagger and CUE (or `cue`-wrapping commands), is fiddly.

If there are multiple CUE packages in the root (or current directory), Dagger complains `failed to load plan: found packages "blah" (dagger.cue) and "wibble" (foo.cue)`.

If I place the Dagger files in a sub-directory (e.g. `ci`), then my developers either have to: 

- invoke `dagger do -p ./ci` each time
- use `direnv`/etc to set the (undocumented?) `DAGGER_PLAN=./ci` when entering /this/ directory << this is what I do right now

If I place my *non*-Dagger .cue files in a sub-directory, then my developers don't have the simple `cue def .:wibble` DevX, but instead need to inject `cue def ./dir:wibble` into their muscle memory. Differently from other, CUE-using projects, just because Dagger is /also/ using CUE.

Or I could `Makefile`/etc shim around these different, per-project nuances ... and avoiding this is (IMHO!) at the very /core/ of why I hope projects adopt Dagger!

Also, Dagger and its `dagger project` subcommand feel like they're in control of my top-level `cue.mod` contents, which they might modify at any point. If this /isn't/ the case, it'd be nice to have this stated!

**Comment by TomChv** [comment]
@helderco @aluzzardi In case you didn't saw this one :D
