### ISSUE TITLE
Missing a guide to get started from scratch

### ISSUE THREAD

**Issue by lat0z** [dagger/dagger#2223]
### What is the issue?

From the repository I was trying to create a new project by following https://github.com/dagger/dagger/blob/v0.2.6/docs/learn/1003-get-started.md, thanks to @jpadams  for pointing to the updated articles, however, the current articles does not cover the instructions to create a project from an empty directory as the deprecated article did. 

One option here would be add a "your first project" or something to the Getting Started or Guides section, with the same intention from the older learn/1003-get-started article, but with the content updated.

Other option would be take advantage of the current "Migrate from Dagger 0.1" article and explain  what is no longer there and how it was replaced, the downside of this approach is that someone new to dagger would ignore that article because they might be looking for a getting started article rather than a migration one.

If it is considered relevant I can update the deprecated article to cover the new options available, just looking for a different point of view around this idea.

**Comment by mircubed** [comment]
Yes, this is covered in #2690, so I will close this. @lat0z let us know if you still feel that there is content missing. We are actively working on improving onboarding, so all feedback is always welcome.
