### ISSUE TITLE
✨ Structured data input from client machine's config file

### ISSUE THREAD

**Issue by hongchaodeng** [dagger/dagger#2225]
### What are you trying to do?

Back in the 0.1 days, you can input the entire config file into data as structured data:

```shell
dagger input yaml parameters -f app.yaml
```

Here is the full example: https://github.com/hongchaodeng/ai-demo/blob/main/app.yaml

It will automatically converts to a CUE struct which can then be used in latter actions.

But now all you can do is to input ENV style string input. This is very cumberson.

### Why is this important to you?

Since Dagger is missing this feature, we have to build a wrapper to convert the config to a CUE struct and add it to the Dagger plan file.

### How are you currently working around this?

Since Dagger is missing this feature, we have to build a wrapper to convert the config to a CUE struct and add it to the Dagger plan file.

**Comment by helderco** [comment]
## Declaratively

You can do that declaratively already.

```cue
dagger.#Plan & {
	client: {
		filesystem: "./app.yaml": read: contents: string
	}

	actions: {
		_params: #Parameters & yaml.Unmarshal(client.filesystem."./app.yaml".read.contents)

		test: #Echo & {
			input: _params.metadata.name
		}
	}
}
```

<details><summary><h3>Full plan</h3></summary>

```cue
package main

import (
	"encoding/yaml"
	"dagger.io/dagger"
	"universe.dagger.io/alpine"
	"universe.dagger.io/docker"
)

dagger.#Plan & {
	client: {
		filesystem: "./app.yaml": read: contents: string
	}

	actions: {
		_params: #Parameters & yaml.Unmarshal(client.filesystem."./app.yaml".read.contents)

		test: #Echo & {
			input: _params.metadata.name
		}
	}
}


#Parameters: {
	metadata: {
		name: string
		namespace: string | *"default"
		stack: string
		...
	}
	...
}

#Echo: {
	input: string

	_image: alpine.#Build

	_run: docker.#Run & {
		"input": _image.output
		env: INPUT: input
		command: {
			name: "sh"
			flags: "-c": "echo $INPUT > /out"
		}
		export: files: "/out": _
	}

	echo: _run.export.files."/out"
}
```

</details>

Output:

```console
➜  dagger do test                        
[✔] actions.test
[✔] client.filesystem."./app.yaml".read
Field  Value
echo   "ai-demo"
```

_Notice I'm using outputs from #1351, which is a WIP._ 

## Custom file

Do you need to provide random file name/paths into the CLI command?

```cue
dagger.#Plan & {
	client: {
		env: PARAMS_FILE: string | *"app.yaml"
		commands: params: {
			name: "cat"
			args: [env.PARAMS_FILE]
		}
	}

	actions: {
		_params: #Parameters & yaml.Unmarshal(client.commands.params.stdout)

		test: #Echo & {
			input: _params.metadata.name
		}
	}
}
```

Output: 

```console
➜  dagger do test
[✔] actions.test
[✔] client.env
[✔] client.commands.params
Field  Value
echo   "ai-demo"
```

That uses the default, but you can use another file:

```console
➜  PARAMS_FILE=values.yaml dagger do test
[✔] actions.test
[✔] client.env
[✔] client.commands.params
Field  Value
echo   "ai-demo-2"
```

**Comment by jpadams** [comment]
@hongchaodeng could you explain why the approach from @helderco above does not meet your needs?
