### ISSUE TITLE
🐞 website not rendering well on iphone 8

### ISSUE THREAD

**Issue by danenania** [dagger/dagger#2230]
### What is the issue?

Looks like this for me on mobile safari:

![3855B78E-CF39-43A6-9828-D00D65157B52](https://user-images.githubusercontent.com/545350/164055755-8e3e3ea8-bc97-4684-a041-7f27d9bacc5d.png)

### Dagger version

na

### OS version

ios 14.2

**Comment by slumbering** [comment]
Hi @danenania ! Thanks for your message. This issue has been fixed.
