### ISSUE TITLE
✨ Hashi vault universe package

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2237]
### What are you trying to do?

Hashicorp Vault is a wildly popular secrets store.

Ex:

`vault read -format json <vault app role>`

https://learn.hashicorp.com/tutorials/cloud/vault-auth-method?in=vault/cloud#enable-approle-auth-method

**Comment by dezren39** [comment]
Came here looking for vault integration. Can one make their own 'secret' provider? I'd guess so, but I'm just beginning.

**Comment by gerhard** [comment]
FYI: https://docs.dagger.io/723462/use-secrets/#use-secrets-from-an-external-secret-manager

Can this be closed now? cc @dolanor @vikram-dagger

**Comment by dolanor** [comment]
Yes it can be
