### ISSUE TITLE
🐞 `dagger do` causes seg fault when running in directory with no actions

### ISSUE THREAD

**Issue by kjuulh** [dagger/dagger#2245]
### What is the issue?

When running `dagger do` on a directory with no actions it will crash the CLI with a seg vault.

### Log output

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xfa7903]

goroutine 1 [running]:
go.dagger.io/dagger/plan.(*Action).FindByPath(0x12347c9, {{0xc0004e62c0, 0x1, 0x0}})
        /home/kjuulh/git/github/kjuulh/dagger/plan/action.go:34 +0xa3
go.dagger.io/dagger/cmd/dagger/cmd.glob..func2(0x1d3e940, {0x1d89c10, 0x0, 0x0})
        /home/kjuulh/git/github/kjuulh/dagger/cmd/dagger/cmd/do.go:70 +0x3bf
github.com/spf13/cobra.(*Command).execute(0x1d3e940, {0x1d89c10, 0x0, 0x0})
        /home/kjuulh/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x1d3ee40)
        /home/kjuulh/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/kjuulh/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/kjuulh/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
go.dagger.io/dagger/cmd/dagger/cmd.Execute()
        /home/kjuulh/git/github/kjuulh/dagger/cmd/dagger/cmd/root.go:89 +0x414
main.main()
        /home/kjuulh/git/github/kjuulh/dagger/cmd/dagger/main.go:8 +0x17
       

### Steps to reproduce

$ pwd
.../dagger/pkg/universe.dagger.io/go/

$ dagger do

### Dagger version

632b89e

### OS version

Manjaro Linux, Kernel: 5.15.28-1-MANJARO

**Comment by grouville** [comment]
cc @jlongtine

**Comment by ab-passos** [comment]
Hi, 

I have the following minimal example from the todoapp:

`package todoapp

import (
	"dagger.io/dagger"
	"dagger.io/dagger/core"
)

dagger.#Plan & {
	_nodeModulesMount: "/src/node_modules": {
		dest:     "/src/node_modules"
		type:     "cache"
		contents: core.#CacheDir & {
			id: "todoapp-modules-cache"
		}

	}
	client: {
		env: {
			APP_NAME:      string
			NETLIFY_TEAM:  string
			NETLIFY_TOKEN: dagger.#Secret
		}
	}
}`

When I do dagger do, I get the following output:
Usage: 
  dagger do  [flags]

Options


Available Actions:


Flags:
      --cache-from stringArray   External cache sources (eg. user/app:cache, type=local,src=path/to/dir)
      --cache-to stringArray     Cache export destinations (eg. user/app:cache, type=local,dest=path/to/dir)
  -h, --help                     help for do
      --no-cache                 Disable caching
  -p, --plan string              Path to plan (defaults to current directory) (default ".")
      --platform string          Set target build platform (requires experimental)
  -w, --with stringArray
Global Flags:
      --experimental        Enable experimental features
      --log-format string   Log format (auto, plain, tty, json) (default "auto")
  -l, --log-level string    Log level (default "info")

Can you provide an example that I can use to reproduce it? 

Thanks

**Comment by aluzzardi** [comment]
Fixed in #2258!
