### ISSUE TITLE
🐞 Error (`grpc: received message larger than max`) when exporting files larger than 16 MB

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#2248]
### What is the issue?

When exporting a file using [the instructions in our docs](https://docs.dagger.io/1226/handling-outputs/#writing-outputs-to-the-filesystem), if the file is larger than 16 MB than you get an error.

As pointed out by @marcosnils, this appears to be a limit hardcoded by [the Buildkit client here](https://github.com/moby/buildkit/blob/master/client/client.go#L41-L44).

In general, while we could make that limit configurable, it's still problematic in that this approach to exporting a file to a local dir requires loading the entire file into memory as a single byte slice and then writing it to the filesystem. A better approach is to stream the file bytes continuously from the server to the client to the filesystem. I believe (but need to double check) that this is what Buildkit's local exporter does, so I'm wondering if we can switch to using that to implement these use cases. 

### Log output

```
FTL failed to execute plan: task failed: actions.test.export._files."/hello.txt"._read: ReadFile /hello.txt: ResourceExhausted: grpc: received message larger than max (16777221 vs. 16777216)
```

### Steps to reproduce

Run this:
```
package main

import (
	"dagger.io/dagger"

	"universe.dagger.io/alpine"
	"universe.dagger.io/bash"
)

dagger.#Plan & {
    client: filesystem: "output.txt": write: contents: actions.test.export.files["/hello.txt"]

    actions: {
        _image: alpine.#Build & {
            packages: bash: {}
        }
        test: bash.#Run & {
            input: _image.output
            script: contents: "dd if=/dev/zero bs=1M count=16 > /hello.txt"
            export: files: "/hello.txt": string
        }
    }
}
```

### Dagger version

dagger devel (632b89ea) linux/arm64 (built from our main branch)

### OS version

Linux buildkit_dev 5.16.0-6-arm64 #1 SMP Debian 5.16.18-1 (2022-03-29) aarch64 GNU/Linux

**Comment by jlongtine** [comment]
@sipsma @marcosnils 

This uses local export:

```cue
package main

import (
	"dagger.io/dagger"

	"universe.dagger.io/alpine"
	"universe.dagger.io/bash"
	"universe.dagger.io/docker"
)

dagger.#Plan & {
	client: filesystem: "export": write: contents: actions.copy.output.rootfs

	actions: {
		_image: alpine.#Build & {
			packages: bash: {}
		}
		test: bash.#Run & {
			input: _image.output
			script: contents: "dd if=/dev/zero bs=1M count=16 > /hello.txt"
		}
		copy: docker.#Copy & {
			input: rootfs: dagger.#Scratch
			contents: test.export.rootfs
			include: ["hello.txt"]
		}
	}
}
```

**Comment by marcosnils** [comment]
Awesome, thx Joel! I'll open up a follow-up issue to clarify that in the handling-outputs (https://docs.dagger.io/1226/handling-outputs/) guide.

**Comment by sipsma** [comment]
Thanks @jlongtine good to know that's possible already. Agree @marcosnils that documenting this is the right immediate fix.

In general, I am wondering if it even makes sense have that `export` field in `bash.#Run`. It seems very confusing that there are multiple ways to export a file that have subtle but important differences like the one here. It also seems like something that every variation on `bash.#Run` would need to handle, which is not ideal.

I would need to think about different ways of approaching it more though. For the shorter term, I think we should also make this error more clear (it's basically incomprehensible right now). I'll leave this issue open for tracking that.

**Comment by AP-Hunt** [comment]
I tried @jlongtine's solution with Dagger 0.2.7 on Mac (thanks!). I expected `dagger do test` to write the file, but it didn't. 
```
$ dagger do -p test.cue test
[✔] actions                 0.0s
[✔] actions.test.script     0.0s
[✔] actions.test                                     
```

I had to do `dagger do copy` which, to me, seemed like it was leaking an implementation detail. The below modification worked in the way I would've expected:

```cue
package main

import (
	"dagger.io/dagger"

	"universe.dagger.io/alpine"
	"universe.dagger.io/bash"
	"universe.dagger.io/docker"
)

dagger.#Plan & {
	client: filesystem: "export": write: contents: actions.test.output.rootfs

	actions: {
		_image: alpine.#Build & {
			packages: bash: {}
		}
		test: bash.#Run & {
			input: _image.output
			script: contents: "dd if=/dev/zero bs=1M count=16 > /hello.txt"

			_copy: docker.#Copy & {
				input: rootfs: dagger.#Scratch
				contents: test.export.rootfs
				include: ["hello.txt"]
			}
		}
	}
}
```

```
$ dagger do -p test.cue test
[✔] actions                                    0.0s
[✔] actions.test.script                        0.0s
[✔] actions.test                               0.0s
[✔] client.filesystem.export.write
```

**Comment by marcosnils** [comment]
> I had to do `dagger do copy` which, to me, seemed like it was leaking an implementation detail. The below modification worked in the way I would've expected:

Yep, @jlongtine's suggestion was a mostly a quick example. :raised_hands:

**Comment by 4x0v7** [comment]
For posterity, I had to reference the nested `_copy` action in @AP-Hunt's example above to have dagger export just the single file.
So
> `client: filesystem: "export": write: contents: actions.test.output.rootfs`
becomes
> `client: filesystem: "export": write: contents: actions.test._copy.output.rootfs`

**Comment by sipsma** [comment]
This issue was in the context of cue. I had forgotten about it and made a new issue for the new engine here: https://github.com/dagger/dagger/issues/5002

Going to close this issue in favor of that one since most of the discussion on workarounds here are no longer relevent
