### ISSUE TITLE
Deprecation policy for CUE packages

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#2251]
We need a deprecation policy for changes to CUE packages.

The idea is to avoid breaking configs as much as possible, so if there's something that can be done (like renaming fields, e.g., https://github.com/dagger/dagger/blob/main/pkg/dagger.io/dagger/compat.cue) to ease the transition then we should do it.

I'm thinking about adding attributes to fields (e.g., `@deprecated()`) so we can spit out warnings when loading the plan. I know attributes are frowned upon, but I think it's an ok use here. This would notify users of a change and give them time to adjust.

We could then take the opportunity of a minor version bump (i.e., 0.2.x -> 0.3.x) to remove deprecations and to change other things that aren't easy to add a compatibilty layer.

For actual breaking changes, don't forget adding a `!:` prefix on the commit message and adding a `BREAKING CHANGE:` footer in the commit body ([conventional commits](https://www.conventionalcommits.org)), with migration notes. 

The idea is that you should be able to look at a release's notes, see that it has breaking changes and follow on what to do.

**Comment by dolanor** [comment]
I don't know about attributes (yet), but I believe it seems a sensible thing to do.

As our CUE package might evolve a bit as we're pre-1.0, it would be nice to have some `dagger fix` system, like `go tool fix` that they used [before the v1 promise](https://go.dev/blog/introducing-gofix) and what CUE seems to have as well. It's a more involved task I believe, though.

**Comment by jpadams** [comment]
@helderco I didn't see this issue before, but I also have a need for a deprecation marker for promoting Universe packages and stopping the PRs to deprecated packages.

We've already deprecated the old `universe.dagger.io/x` packages by using a comment at the top of the file like `Deprecated: in favor of ...`

I want to put a check in CI to stop PRs to deprecated packages, etc: https://github.com/dagger/dagger/issues/2634

**Comment by helderco** [comment]
I think this should be prioritized to help with changing configs, especially with the initiatives possibly bringing lots of changes. It would be easier to have a consensus on https://github.com/dagger/dagger/pull/2210, for example, if we could actually warn users if they're using something that deprecated.

**Comment by TomChv** [comment]
This is related to the CUE SDK, we are no longer working on it.

We also have an issue #4855 that track our deprecation policy with a warning log message for now.
