### ISSUE TITLE
🐞 files deleted when running bash action

### ISSUE THREAD

**Issue by tomasmota** [dagger/dagger#2253]
### What is the issue?

When a bash action fails, there is a chance dagger will wipe a bunch of files, including git related files, It usually renders the git repo unusable, requiring a clean clone.

The set of deleted files is not always the same and not always are files deleted. In the following screenshot I ran the action 3 times, but only the third time the files were deleted:

![image](https://user-images.githubusercontent.com/25929015/164412194-c74cf3a4-c6a2-4a72-ad7b-bd93f5773f98.png)

### Steps to reproduce

```
git clone git@github.com:tomas-mota/dagger-testing.git
cd dagger-testing
dagger do run (might need to run this more than once)
```

### Dagger version

dagger 0.2.5 (7d2f279c) linux/amd64

### OS version

Ubuntu 20.04 on wsl

**Comment by TomChv** [comment]
@tomas-mota Hi 👋 

Is this issue still active? Could you find a way to solve it?

**Comment by jedevc** [comment]
It looks like this is from quite an old version of dagger - we've changed so much since then, so it's likely that this issue isn't relevant any more, so I'm going to close it.

If it's still relevant, we can re-open easily! :tada:
