### ISSUE TITLE
✨ Support Windows install through Chocolatey

### ISSUE THREAD

**Issue by 1nv1n** [dagger/dagger#2259]
### What are you trying to do?

Hello, for setting up Dagger on Windows, I was wondering whether there is any interest in making Dagger available as a Chocolatey package.

The process to create & publish a package seems fairly straightforward:
https://docs.chocolatey.org/en-us/create/create-packages

And the actual install script (package) could look something like:

```
$packageName = 'dagger'
$fileType = 'ps1'
$url = 'https://dl.dagger.io/dagger/install.ps1'

Install-ChocolateyPackage $packageName $fileType $url
```

The end-user can install it by running:
`choco install dagger`

The `install.ps1` script would need to be updated to accept a version number as an argument so we are able to get specific releases through Chocolatey. And we could use the same script for the `choco upgrade dagger` command by omitting the version number argument to pull in the latest version.

### Why is this important to you?

- Simpler to get & keep up-to-date (`choco install` & `choco upgrade`).
- Can be used in a Chocolatey Script Builder (https://docs.chocolatey.org/en-us/community-repository/script-builder) to queue up multiple package installs (eg: run one script to get/install Jenkins, then Dagger, etc.)
- Any/all Chocolatey benefits would apply to this package as well.

### How are you currently working around this?

By using the provided PowerShell install command.

**Comment by jpadams** [comment]
Thanks for the suggestion, @1nv1n! Have you built a choco package before?

@ferventcoder 👋 as a big Chocolatey fan myself, I'll be looking into how we can add Dagger :)
https://docs.chocolatey.org/en-us/create/create-packages

**Comment by 1nv1n** [comment]
I have not! But it seems easy, given we already have the install-script for Dagger. I'll be looking into this as well.

**Comment by piraces** [comment]
Hi! I have not seen this issue but some days ago when I found that dagger was not in Chocolatey, I worked on provide it as I manage other packages for Chocolatey Community.

It is available in this URL: https://community.chocolatey.org/packages/dagger
Simply to install with choco as executing: `choco install dagger`

The repo where I have all the scripting for the Chocolatey packages I mantain is here: https://github.com/piraces/chocolatey-packages

Nevertheless, if the dagger owners/community wants to own the package and publish vía this main repo or other in the organization, please let me know to proceed to transfer it.

I have also noticed that for [Scoop](https://scoop.sh/) (another Windows package manager) [has it too](https://scoop.sh/#/apps?q=dagger) (thanks to @vardrop ).

PS: I have also thought about adding in the installation documentation for Dagger in Windows these two possibilities... I can work on that documentation if you are ok with it.

**Comment by jpadams** [comment]
@piraces thanks so much for driving choco and docs!
@vardrop thanks for wrangling scoop!

I'll close this issue now. Yes, would be good to figure out if we should integrate the release process into the `dagger` repo. cc @samalba
