### ISSUE TITLE
Explain input/output concept

### ISSUE THREAD

**Issue by TomChv** [dagger/dagger#2269]
### What is the issue?

Many users have difficulties to understand input and output concept and that lead them to issues they do not really understand.

We should write a page in `core concept` category to explain how you can link action together through input and output.
We should also explain when use `docker.#Build` and when not.

And also explain how create dependency between actions that not necessary has `input` field : link `docker.#Push` and `docker.#Pull` for instance.

**Comment by marcosnils** [comment]
> Many users have difficulties to understand input and output concept and that lead them to issues they do not really understand.

Do you have a link to a thread in discord or an example about use-cases users were trying to achieve and they were finding confusing? That could help to put a guide relatively easy

**Comment by TomChv** [comment]
Sure : https://discord.com/channels/707636530424053791/966990447065071648 is a good example

**Comment by mircubed** [comment]
Closing this issue to consolidate since #2162 is similar.
