### ISSUE TITLE
Provide an example for "You can extend your script by wrapping it, as-is, into a DAG. This allows you to start using Dagger right away, and worry about rewrites later."

### ISSUE THREAD

**Issue by DazWilkin** [dagger/dagger#2272]
### What is the issue?

The statement "[You can extend your script by wrapping it, as-is, into a DAG. This allows you to start using Dagger right away, and worry about rewrites later.](https://docs.dagger.io/1220/vs)" is interesting but there's nothing to back it up. I'm skeptical that wrapping a complex bash script as-is into a DAG would offer benefit but I'd value an example being included in you docs.

As a startup founder building a reasonably complex cloud-native app that's composed mostly of containers and am intrigued by CUE, I'm also intrigued by Dagger.

For what I think are good reasons, my deployment process comprises bash scripts and -- rather reluctantly -- multiple GitHub Actions.I'm intrigued by Dapper because I like the portability promise and I would value more explicit dependencies between tasks in my deployment process.

However, I'm reluctant to (re)do a bunch of work in an aspect of my "thing" that's important but not core to my goal in launching it without clear guidance in how to achieve this with Dapper and proof that there are benefits to this.

**Comment by jpadams** [comment]
@DazWilkin Thanks for this issue!

Is there a public example similar to your deployment process that would be a good starting point?

Also, ping me in Discord if you'd like to work on your use case.

**Comment by DazWilkin** [comment]
Thanks @jpadams for the prompt response!

The deployment repo's private but I'd be willing to add you or others to it if that would help.

My "thing" runs predominantly on Google Cloud Platform where it spans Firestore (DB), Cloud Run (serverless containers), Kubernetes and platform resource config, but there are additional platforms (GitHub, Stripe) involved too.

It may be too complex as a starting point. However there are patterns:

+ modular (functions) but it's bash
+ environment used for (global) config
+ minimal parameters and error handling
+ minimal dependency tracking

I would want Dapper to help with some|all of the above:

1. Convert bash functions into Dapper components
1. Leverage Dapper components (?) to add typing, dependencies|dependents and better error-handling

I think much of this could be demonstrated minimally with 2 Dapper components:

1. One dependent on the success of the other;
1. Return values and other state from the first, piped into the second;
1. Bonus: error-handling
1. Bonus: validation of params e.g. URL

I think this would cover a big chunk of my need.

I chose bash rather than Terraform or Go because:

+ Bash is quicker to hack arbitrary CLIs and `curl`
+ 1st party CLIs are almost always current with the platform whereas 3rd party stuff lags
+ I was concerned (rightly) that Terraform would lack some of the platforms|components that I need
+ Go gives me everything but then I'm supporting and updating Go code for my app and its deployment.

That was a longer answer than I expected but I feel it represents my situation and hope it's helpful.

**Comment by jpadams** [comment]
> components that wrap bash function(ality):
>
> One dependent on the success of the other;
> Return values and other state from the first, piped into the second;
> Bonus: error-handling
> Bonus: validation of params e.g. URL
> I think this would cover a big chunk of my need.

@DazWilkin I agree that would be a valuable pattern to highlight. Wrapping bash.
Would love to work with you on that.

**Comment by DazWilkin** [comment]
Does anything exist?

The documentation is ambiguous but suggests that it does.

**Comment by jpadams** [comment]
@DazWilkin I think combining the practices of keeping scripts in their own files and using `core.#Source` to access a directory in a repo full of scripts, is a great way to illustrate this.

If you have a an example that we could use for this, it could make a great guide.

https://docs.dagger.io/1226/coding-style#dont-inline-scripts
https://docs.dagger.io/1240/core-source

**Comment by TomChv** [comment]
@DazWilkin Hey 👋 

Any update on this topic?

**Comment by jpadams** [comment]
@kpenfound interesting prompt

**Comment by shykes** [comment]
Closing this given the low priority, and the fact that docs and website have been completely rewritten since then. I don't believe the original claim exists in the current version.
