### ISSUE TITLE
Add env var defaults to docs

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2280]
### What is the issue?

Add example with this change: https://github.com/dagger/dagger/pull/2122#event-6411429502

here: https://docs.dagger.io/1203/client#environment-variables

**Comment by helderco** [comment]
There’s an example already, what am I missing?

**Comment by jpadams** [comment]
Whoops missed it! Thanks @helderco 

```
// load as a string, using a default if not defined
BASE_IMAGE: string | *"registry.example.com/image"
```
