### ISSUE TITLE
🐞 docker.#Run mount with sub variable fails

### ISSUE THREAD

**Issue by kjuulh** [dagger/dagger#2295]
### What is the issue?

There is a problem with vars in docker mount.

The idea is that a split of variables in docker mount causes `dagger do build` to failed

```
$ cd doesnt-work
$ dagger do build
```

### Log output

```
2:11PM FTL failed to execute plan: task failed: actions.build.container._exec: invalid secret at path "actions.build.container._exec.mounts.\"ssh Known Hosts\".contents": secret is not set
```

### Steps to reproduce

```
$ cd doesnt-work
$ dagger do build
```

see: https://github.com/kjuulh/dagger/pull/1 for code

the diff

The difference is basically

```
			"ssh key": {
				contents: ssh.Key
				dest:     _sshPath
			}
			"ssh Known Hosts": {
				contents: ssh.KnownHosts
				dest:     _sshKnownHostsPath
			}
			...
			vs
			...
			"ssh key": {
				contents: sshKey
				dest:     _sshPath
			}
			"ssh Known Hosts": {
				contents: sshKnownHosts
				dest:     _sshKnownHostsPath
			}
```

diff -U3   doesntwork/doesnt-work.cue works/works.cue
```diff
--- doesntwork/doesnt-work.cue	2022-04-25 14:06:22.000000000 +0200
+++ works/works.cue	2022-04-25 14:01:52.000000000 +0200
@@ -19,7 +19,8 @@
 	ssh: #SSH

 	#GoContainer & {
-  ssh: ssh
+		sshKey:        ssh.Key
+		sshKnownHosts: ssh.KnownHosts
 		command: {
 			name: "go"
 			args: [package]
@@ -66,7 +67,8 @@
 				GOARCH: arch
 			}
 		}
-		ssh:        ssh
+		sshKey:        ssh.Key
+		sshKnownHosts: ssh.KnownHosts
 		command: {
 			name: "go"
 			args: [package]
@@ -93,7 +95,8 @@
 	// Source code
 	source: dagger.#FS

-	ssh:        #SSH
+	sshKey:        dagger.#Secret
+	sshKnownHosts: dagger.#Secret

 	// Use go image
 	_image: #GoImage
@@ -125,11 +128,11 @@
 				dest: _buildCachePath
 			}
 			"ssh key": {
-				contents: ssh.Key
+				contents: sshKey
 				dest:     _sshPath
 			}
 			"ssh Known Hosts": {
-				contents: ssh.KnownHosts
+				contents: sshKnownHosts
 				dest:     _sshKnownHostsPath
 			}
 		}
```

### Dagger version

1c36f8e

### OS version

macOS 12.3.1

**Comment by aluzzardi** [comment]
@kjuulh Can you try again against `main`? We just added a few improvements around error messages

**Comment by kjuulh** [comment]
@aluzzardi 

I've tried against main, it is giving a different error now. Which is correlated with the recent changes, `... key is not set`, I am still struggling with what is really going wrong. I will have more time to investigate tomorrow, and will get back to you hopefully then.

**Comment by helderco** [comment]
Hey, just looking from afar I see `ssh: ssh` which gives you shadowing issues. You need to do `"ssh": ssh` instead.

**Comment by helderco** [comment]
@kjuulh Do you still have this issue?

**Comment by kjuulh** [comment]
@helderco Sorry about that, it turned out to be the shadowing issue. So adding a quotes around ssh worked.

**Comment by helderco** [comment]
👍
