### ISSUE TITLE
🐞 Fix `dagger do` flag validation

### ISSUE THREAD

**Issue by jlongtine** [dagger/dagger#2297]
### What is the issue?

https://github.com/dagger/dagger/pull/2261 broke flag validation for `dagger do` (while fixing another issue created by changing cobra flag parsing). We should work to enforce flag validation again. 

### Dagger version

dagger 0.2.7

### OS version

macOS 12.3

**Comment by marcosnils** [comment]
We should also create tests for flag parsing so we guarantee not to break this functionality moving forward.
