### ISSUE TITLE
Nested core actions are silently ignored

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#2303]
Core actions cannot be nested under other core actions because of CUE flow limitations.

As an example:

```
actions: foo: core.#WriteFile & {
  _xxx: core.#ReadFile & {
  }
  contents: _xxx.contents
}
```

In this case, `actions.foo._xxx` is **nested** under `actions.foo` and is silently ignored. The result will be a confusing non-concrete error `contents: _xxx.contents` (since `_xxx.contents` will never be filled by the runtime).

We should scan for nested tasks and fail with a clean error.

Example (dirty code):

```diff
@@ -122,3 +123,46 @@ func isPlanConcrete(p *compiler.Value, v *compiler.Value) error {
        // Ignore all other types.
        return nil
 }
+
+func checkNestedTasks(v *compiler.Value) ([]*compiler.Value, error) {
+       if !v.Kind().IsAnyOf(cue.StructKind) {
+               return nil, nil
+       }
+
+       t, _ := task.Lookup(v)
+       isTask := t != nil
+
+       subTasks := []*compiler.Value{}
+       fields, err := v.Fields(cue.All())
+       if err != nil {
+               return nil, err
+       }
+
+       var groupErr cueerrors.Error
+       for _, field := range fields {
+               sub, err := checkNestedTasks(field.Value)
+               if err != nil {
+                       groupErr = cueerrors.Append(groupErr, cueerrors.Promote(err, "nested task"))
+               }
+               subTasks = append(subTasks, sub...)
+       }
+
+       if isTask {
+               if len(subTasks) > 0 {
+                       for _, sub := range subTasks {
+                               err := cueerrors.Newf(sub.Pos(), "task defined in %s", sub.Path().String())
+                               if groupErr == nil {
+                                       groupErr = err
+                               } else {
+                                       groupErr = cueerrors.Append(groupErr, err)
+                               }
+                       }
+                       groupErr = cueerrors.Append(groupErr, cueerrors.Newf(v.Pos(), "task defined in %s", v.Path().String()))
+
+               }
+
+               subTasks = append(subTasks, v)
+       }
+
+       return subTasks, groupErr
+}
```

**Comment by dolanor** [comment]
Is it something that can be improved upstream as well? Or is it a design decision from cueflow?

**Comment by aluzzardi** [comment]
> Is it something that can be improved upstream as well? Or is it a design decision from cueflow?

@jlongtine has more context on this one. I think there are side effects on having nested tasks and therefore CUE is deciding to ignore them altogether.

**Comment by jlongtine** [comment]
@dolanor and I had a good (if brief) chat about this. I think our best bet (for now, until we spend the time to improve `cue/flow` tasks more) is to catch this error whenever we can (should work for most cases, except for dynamic tasks), and print something nice for the user so they know we won't be running that task for them.

**Comment by helderco** [comment]
There's current usage patterns around this that we need to replace.

A nested core action can be used to force a dependency on another core action. Execution is ignored as expected, but the other core action is recognized as a dependency and therefore runs first.

You can see examples in https://github.com/dagger/dagger/blob/0b91998c66b8c6c0021c9459aa40aca11b88e5dc/tests/tasks/exec/start_stop_exec.cue#L45

We can use a field to force dependency and it'll have the same effect of forcing the dependency:

```diff
sig: core.#SendSignal & {
	input:  start
	signal: core.SIGHUP
-	_dep:   sleep
+	_dep:   sleep.exit
}
```

`client: filesystem` is also using this pattern to force a read before a write to the same path:

https://github.com/dagger/dagger/blob/0b91998c66b8c6c0021c9459aa40aca11b88e5dc/pkg/dagger.io/dagger/plan.cue#L22

```diff
if (read.path & write.path) != _|_ {
-	_after: read
+	_after: read.contents
}
```

These workarounds are hidden, but the `core.#Stop` and `core.#SendSignal` tasks actually depend on it. Both depend on `input: core.#Start`:

https://github.com/dagger/dagger/blob/0b91998c66b8c6c0021c9459aa40aca11b88e5dc/pkg/dagger.io/dagger/core/exec.cue#L85
https://github.com/dagger/dagger/blob/0b91998c66b8c6c0021c9459aa40aca11b88e5dc/pkg/dagger.io/dagger/core/exec.cue#L138

So this is a breaking change for these actions.

**Comment by TomChv** [comment]
This issue is outdated, we are not longer working on the CUE SDK
