### ISSUE TITLE
✨ Add  convenient "last" field to docker.#Build action

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#2311]
### What are you trying to do?

Speaking with @helderco he came up with the idea of having a convenience way to reference the last action output from a `docker.#Build` steps since it's not uncommon to see `docker.#Build` actions are followed up by a `#Subidr` or `#Readfile` to validate or export contents out of it. 

This also goes in line with some of the comments in #1993 and with other convenience features proposed like #2290 

Example: 

Replace this:

```cue
dagger.#Plan & {
	client: {
		filesystem: {
			"./launcher/": {
				read: {
					contents: dagger.#FS
				}
				write: {
					contents: actions.output
				}
			}
		}
	}

	actions: {
		build: docker.#Build & {
			steps: [
				alpine.#Build & {
					packages: {
						bash: {}
						yarn: {}
					}
				},
				docker.#Copy & {
					contents: client.filesystem."./launcher/".read.contents
					dest:     "/src"
				},
				bash.#Run & {
					workdir: "/src"
					script: contents: "yarn install"
				},
			]
		}

		_output: core.#Subdir & {
			input: build.output.rootfs
			path:  "/src"
		}
		output: _output.output
	}
}
```

With something like this:

```cue
dagger.#Plan & {
	client: {
		filesystem: {
			"./launcher/": {
				read: {
					contents: dagger.#FS
				}
				write: {
					contents: actions.build.last.export.directories."/test"
				}
			}
		}
	}

	actions: {

		build: docker.#Build & {
			steps: [
				alpine.#Build & {
					packages: {
						bash: {}
						yarn: {}
					}
				},
				docker.#Copy & {
					contents: client.filesystem."./launcher/".read.contents
					dest:     "/src"
				},
				bash.#Run & {
					workdir: "/src"
					script: contents: "yarn install"
                                        export: directories: "/src": _
				},
			]
		}
	}
}
```

Thoughts? 

cc @shykes @aluzzardi 

### Why is this important to you?

Avoid the mental overhead of creating unnecessary actions for things that should "naturally" work.

### How are you currently working around this?

Provided in the example.

**Comment by shykes** [comment]
Wouldn't it be much simpler to add a `docker.#Subdir` build step?

```
dagger.#Plan & {
        client: {
                filesystem: {
                        "./launcher/": {
                                read: {
                                        contents: dagger.#FS
                                }
                                write: {
                                        contents: actions.output
                                }
                        }
                }
        }

        actions: {
                build: docker.#Build & {
                        steps: [
                                alpine.#Build & {
                                        packages: {
                                                bash: {}
                                                yarn: {}
                                        }
                                },
                                docker.#Copy & {
                                        contents: client.filesystem."./launcher/".read.contents
                                        dest:     "/src"
                                },
                                bash.#Run & {
                                        workdir: "/src"
                                        script: contents: "yarn install"
                                },
                                docker.#Subdir & {
                                        path: "/src"
                                },
                        ]
                }
        }
}
```

**Comment by TomChv** [comment]
> Wouldn't it be much simpler to add a docker.#Subdir build step?

Subdir would not works for file and what if you have multiple `exports`?

>  just implement a custom build step?

I totally agree with you but since it's a really common usage, it could become a standard?

Maybe add it as an experimental definition : `x/dagger.io/output` for now and see if it's adopted by the community?

**Comment by marcosnils** [comment]
> Subdir would not works for file and what if you have multiple `exports`?

This

> just implement a custom build step

This violates the purpose of this proposal. The idea here is not creating additional steps / actions since you have anything you need there, we just don't have a way to access it. Creating a custom build step is not very different from adding another action to just get what you need.

**Comment by shykes** [comment]
Let's regroup here. What's the use case exactly?

**Comment by shykes** [comment]
Ok, that's very helpful, thanks. Honestly this seems to me that `docker.#Build` is the wrong tool for the job, and you would be better off running `yarn install` in a standalone action, where you can then reference it the normal way without having to deal with an array. The only reason `docker.#Build` has an array is to offer a convenient shortcut when you don't need to reference the individual steps because you only care about the final docker image. There's no point in hacking around the limitations of the array - if it's not convenient then just don't use it.

Switching to "hack mode" for a second, in response to this:

> `actions.<action>.steps[2].export` [...] that didn't work given how `steps` gets resolved

Have you tried `actions.<action>.dag["2"]` ? That might do the trick for a quick and dirty solution to your problem.

**Comment by marcosnils** [comment]
> The only reason `docker.#Build` has an array is to offer a convenient shortcut when you don't need to reference the individual steps because you only care about the final docker image.

Makes sense. If I asked myself the question: is my output a Docker image? initially, I would have used `docker.#Build`. On that context, I guess we don't really need to do anything here. 

Regarding the hack solution, it doesn't seem to work since the CUE evaluator complains about `actions.<action>.dag` being an undefined field.
