### ISSUE TITLE
Update settings in GitHub to make rebase default update

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2316]
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/3187222/165381815-3606e488-9df6-4117-a718-fbb7ef80d045.png">

seems aligned with
https://docs.dagger.io/1227/contributing/#3-update-your-pull-request-with-latest-changes

cc @aluzzardi @helderco @gerhard

**Comment by TomChv** [comment]
@jpadams This has been done or not?

**Comment by gerhard** [comment]
I have not see this option in the settings or in the docs. AFAIK, this will default to what the user used last. Did I miss something @jpadams?

**Comment by thaJeztah** [comment]
One note (in case relevant) is that using this option will mutate the commit, and in doing so discard signing if the contributor signed their commit.

**Comment by jpadams** [comment]
@thaJeztah very interesting. We're going to close this for now since GitHub doesn't seem to support this, though I mistakenly though it did.

**Comment by thaJeztah** [comment]
👍 thought I'd mention it, as it's easy to overlook that it happens (I think the rebased commit will be re-signed by GitHub instead); not all projects may care about signed-commits, but in some cases it could be relevant (to keep the original author's signing - if present).

**Comment by gerhard** [comment]
That is a great point @thaJeztah, we care about that a big deal. Glad we could resolve this one 💪
