### ISSUE TITLE
CUE Upstream Issues and Enhancements

### ISSUE THREAD

**Issue by jlongtine** [dagger/dagger#2318]
We've encountered a few issues with upstream CUE, and have some enhancements we'd like to help contribute, as well. This issue is intended to catalog, discuss, and suggest potential solutions for each of these. 

## Issues

- https://github.com/dagger/dagger/issues/2182
- https://github.com/cue-lang/cue/issues/1647
- https://github.com/dagger/dagger/issues/1867
  - https://github.com/dagger/dagger/pull/2024
  - https://github.com/dagger/dagger/pull/2371
- https://github.com/dagger/dagger/issues/1466
  - https://github.com/cue-lang/cue/issues/754
- https://github.com/dagger/dagger/issues/2326

## Enhancements
- https://github.com/dagger/dagger/issues/825
- https://github.com/dagger/dagger/issues/940
  - https://github.com/dagger/dagger/discussions/2124
- https://github.com/dagger/dagger/issues/2163
- https://github.com/dagger/dagger/issues/1254
- Allow more direct control of CUE tasks in `cue/flow`

# Discussion

The broad strokes of this issue are that there are a few areas where CUE is currently evaluating things in an incorrect way, or there is some subtlety in the evaluation that worked before, but no longer works. 

Also, there are some pathologic cases in the evaluator that cause runtimes and memory use to balloon.

My hope is that future releases (and probably betas) of CUE help solve some of these problems. Marcel is improving the comprehension code right now (May 4, 2022), and that should include changes that make other changes in the rest of the codebase much more straightforward, including the potential for structure sharing, which will likely help with some of those pathologic cases. 

### Upgrading CUE - https://github.com/dagger/dagger/issues/2182

The changes on `cue/master` have caused some issues with comprehensions that break `docker.#Build`. 

Specifically, the comprehensions over `files` and `directories` (and related comprehensions over `_files` and `_directories`): https://github.com/dagger/dagger/blob/a0a5f18a813d9573a5683b2c0a64a051b9b0425c/pkg/universe.dagger.io/docker/run.cue#L122-L152

The cyclic quality of these comprehensions causes this error:

```
   actions.test.four.script._write.contents: invalid interpolation: cycle error:
       ./plan/do/do_not_run_unspecified_tasks.cue:41:23
       ./cue.mod/pkg/universe.dagger.io/docker/run.cue:124:20
```

We need to sort these out with upstream. Hopefully this will be resolved by the comprehension work being done in upstream CUE. 

### cue eval takes an abnormous \[sic\] amount of time when it shouldn't  - https://github.com/cue-lang/cue/issues/1647

Some community members (including @Breigner01) are having issues with CUE performance. An example is attached. I suspect this has to do with the disjunctive embed [here](https://github.com/Breigner01/Dagger-ServerlessCloudAgnostic/blob/feat/global-package-first-version/global/function/function.cue#L25-L46). 

### Structural cycle when dagger do --with and dagger.#DecodeSecret are conjointly used - https://github.com/dagger/dagger/issues/1867

There are issues with filling values into the `#Plan`. This needs further investigation.

### Nested docker.#Build fails  - https://github.com/dagger/dagger/issues/1466

We're getting structural cycles when using nested `docker.#Build` instances. I recently found this issue in [cue](https://github.com/cue-lang/cue): https://github.com/cue-lang/cue/issues/754

I believe work is being done on this error, as well: https://github.com/cue-lang/cue/issues/754#issuecomment-1117472128

### panic: not properly initialized state - https://github.com/dagger/dagger/issues/2326

Issues with undefined fields + disjunctions. `incomplete cause disjunction`. It seems like the `undefined field` error is getting swallowed by the `incomplete cause disjunction` error. I would have expected it to at least wrap the `undefined field` error. 

### Language Server for Dagger - https://github.com/dagger/dagger/issues/825

This would be obviously useful for Dagger as well as the CUE community generally. 

Some concerns I have are:
- Performance. Correctly parsing and evaluating CUE in realtime in order to provide feedback to CUE devs is a harder problem than the current evaluation scheme. 
- Different ways to set up CUE instances. Think `./...` vs `.:dagger` vs `plan.cue`. I'm not sure how the LSP will know which mode we're hoping to use for our configs.

### Support explicit dependency - https://github.com/dagger/dagger/issues/940

This likely requires a general enhancement to `cue/flow` to make it easier to depend on sets of tasks under a given key. 

### Improve Package Management - https://github.com/dagger/dagger/issues/2163

`cue mod` is something that Dagger needs (as an improvement over `dagger project`), and something the CUE community needs as well. It will help with managing, importing, and depending on various CUE schemas. 

### Inline actions - https://github.com/dagger/dagger/issues/1254

This should make some plans much cleaner/easier to write. But requires enhancement to `cue/flow` as well. 

### Allow more direct control of CUE tasks in `cue/flow`

- [ ] Create an issue to describe the need for this and some potential implementations. 
  - [ ] Add link to `cue/flow` API changes I made + example code that leverages it. 

Our current system for choosing which tasks to run... leaves a lot to be desired. It would be much easier if we were able to let `cue/flow` find all tasks, but choose which ones we actually want to run. This potentially introduces situations where we could induce race conditions, but I believe it's worth the risk. Also, we're wanting to simply select a particular path in the DAG, from inputs through our selected action(s) through to outputs, so we should be able to do that without introducing races. 

I've experimented with extending the `cue/flow` Task APIs to allow a task to be put into a `UserWaiting` state. This allows me to basically pause Tasks that I don't want to run, _and_ (crucially) allow me to change my mind if task dependencies change, etc.

**Comment by helderco** [comment]
I reported https://github.com/dagger/dagger/issues/1867 upstream with:
- https://github.com/cue-lang/cue/issues/1671
