### ISSUE TITLE
`dagger plan` command

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#2335]
I think a command to introspect the plan would be very useful (e.g. similar to `terraform plan`).

This would:
- Load and validate the plan
- Print the DAG and its dependencies

This would help:

- Navigating the plan: `dagger do --help` kinda does that, but it's one dimensional
- Figure out action dependencies
- Potentially output different formats (e.g. `dot` file use with graphviz)

cc @dagger/maintainers thoughts?

**Comment by jlongtine** [comment]
I like this idea. A bit concerned about dynamic fields (once we figure out how to do that nicely with `cue/flow`), because I don't see how we could do this well in that case.

**Comment by jpluscplusm** [comment]
As useful as `dagger plan` would be, I think a lot of the benefit could be won for (I /think/!) somewhat less effort: adding a `--all` or `--recursive` flag to `dagger do --help`, that walks the tree and pretty-prints all the runnable actions+doc-comments that are present in the Plan.

I.e. exactly as `dagger do [action] --help` does right now, but /not/ stopping at the level of the DAG that the user indicated.

**Comment by samalba** [comment]
I agree with need something like this to introspect the DAG without running it. As an alternative, it could be a simple `dagger do [action] --dry-run` instead of a new command. The plan will need an optional action name since technically, each action is a distinct DAG.

**Comment by shykes** [comment]
Could this be part of #2331 ?
