### ISSUE TITLE
Make more clear that `universe.dagger.io/x` is experimental

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2339]
### What is the issue?

Not everyone will know that `universe.dagger.io/x` (in golang `x` way) means experimental pre-universe packages that are contributed by the community and not yet fully supported by Dagger as a universe package.

**Comment by jpadams** [comment]
best to have a status of integration: perhaps CNCF model: incubating, ...., graduated

**Comment by jpluscplusm** [comment]
I reckon it'd be very very worth making their "not yet deemed ready for prime-time" status **really** clear, by breaking `/x/*` into a differently-named hierarchy. e.g. BUT NOT REALLY `lolthesemightbreakyourmachine.dagger.io`.

Folks *are* going to get bitten by their inclusion under the `universe` hierarchy, and no amount of caveats in READMEs is going to mitigate this. People **do not read documentation**! Something *absolutely unavoidable* that makes it super clear that they're in flux, with unstable interfaces, needs to be thrown in users' faces. IMHO YMMV ;-)

**Comment by jpadams** [comment]
This is superseded by the new alpha, beta, stable flow for universe: https://github.com/dagger/dagger/discussions/2616
