### ISSUE TITLE
Tutorial. How to turn a "makefile" into flat dagger plan and then refactor for reuse

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2341]
### What is the issue?

Tutorial. How to turn a "makefile" into flat dagger plan and then refactor for reuse.

Show progression of simple translation, then go to progressively better structures for reuse/testability/etc.

Talk about tradeoffs involved in more abstraction. How to avoid pitfalls. Talk about user personas and how to create actions and plans that serve their needs: ops, devops, devs, app owners, etc.

Show thought process. Show how to do the re-factors.

Example: start with todoapp "Makefile" (actually yarn file) -> show dagger todapp 1.0 -> show refactoring process and why better
Talk about downsides of original approach and advantages of dagger approach.

Better to show a project other than dagger/dagger.

cc @shykes @jpluscplusm

**Comment by samalba** [comment]
@grouville Assigning this one to you if you don't mind. I would ask guidance from @jpadams when you're ready to work on this, as it's pretty big in comparison to other docs issues.

**Comment by shykes** [comment]
Let's talk about this one before investing too much time, it might go down in priority depending on how we refine positioning (the whole "replace your Makefile / replace your CI workflow" approach doesn't seem to be performing very well compared to "replace one action first").

**Comment by grouville** [comment]
> workflow

Ok, I'll standby it then

**Comment by samalba** [comment]
I'll remove the prio for now.
