### ISSUE TITLE
Better explain how to use `core.#Source`

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2342]
### What is the issue?

confusion today around `core.#Source` and `client: filesystem` for some users.

Can augment existing content and perhaps create blog.

https://docs.dagger.io/1222/core-actions-reference/#core-actions-related-to-filesystem-trees

https://github.com/dagger/dagger/blob/main/pkg/dagger.io/dagger/core/fs.cue#L7-L18

https://docs.dagger.io/1226/coding-style/#dont-inline-scripts

https://github.com/dagger/dagger/issues/1492#issuecomment-1024592441

**Comment by samalba** [comment]
comment from @shykes from issue #2467:
> core.#Source is an important feature of the Dagger API, and it is not documented anywhere.
> 
> As requested by @Siafu: "it would be great if you could explain when to use core.#Source versus client.filesystem.
