### ISSUE TITLE
:sparkles:  Automatically update dagger versions in docs after a new release

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#2351]
### What are you trying to do?

We currently have a script that updates our `dagger version` in our docs instructions but it's not part of our release process. We should ideally try to make our docs depend on hardcoded versions as least as possible and, if not possible, make the release process update docs automatically.

### Why is this important to you?

Currently we're having weekly releases and some docs get outdated and cause issues for new users since some instructions are still referencing older versions of dagger.

### How are you currently working around this?

running a script manually each time a release is made.

cc @aluzzardi 

## Related

https://github.com/dagger/dagger/issues/2327
https://github.com/dagger/dagger/issues/2317

**Comment by aluzzardi** [comment]
> We should ideally try to make our docs depend on hardcoded versions as least as possible and, if not possible, make the release process update docs automatically.

I would go one step further and stop hardcoding versions altogether, I don't think they're doing any good.

The only useful one is **maybe** `git checkout v0.2.8` to get the right examples -- perhaps we could replace that with `git checkout $(dagger version --short)` or something

**Comment by helderco** [comment]
> perhaps we could replace that with `git checkout $(dagger version --short)` or something

Love that!

**Comment by marcosnils** [comment]
> I agree with this. But i'm not sure if we can avoid that for the API reference. Maybe we could handle this through `docusaurus` by having variable in the `docusaurus.config.js` so we have the change it only in a single place.

Speaking about this with @gerhard and @slumbering we just found a better way to do it. We'll have an update by today.
