### ISSUE TITLE
🐞can't run an action because of missing input in another action

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2362]
## Problem

* Good: `dagger do` now checks for missing values before running an action, which saves me time by catching errors early.
* Bad: `dagger do` checks for missing values *in all actions*, even those I am not currently trying to run. This wastes my time, by forcing me to complete values that I don't care about.

Additional notes:

* Actions can leave incomplete values intentionally. Thanks to the missing value check, this becomes the equivalent of a mandatory command-line parameter. For example `dagger do deploy` may fail with "please specify a site ID", which can be solved with `dagger do deploy --site MY_ID". However this pattern only works if the checking is limited to *only the actions that will be run*.

## Solution

When checking for missing values, exclude actions that won't be run.

### What I did

1. Setup a new project to reproduce

```
cd $(mktemp -d)
dagger project init
```

2. Add repro config

```
cat > repro.cue <<-EOF
package main

import (
        "dagger.io/dagger"
        "dagger.io/dagger/core"
)

dagger.#Plan & {
        actions: {
                build: core.#Nop & {
                        input: dagger.#Scratch
                }
                deploy: {
                        site: string
                        command: core.#Nop & {
                                input: dagger.#Scratch
                        }
                }
        }
}
EOF
```

3. Install deps

```
dagger project update
```

4. Run build action

```
dagger do build
```

### What I expected to see

Expected output for step 4:

```
$ dagger do build
[✔] actions.build                                                                                                                                 0.0s
```

### What I see instead

Actual output of step 4:

```
$ dagger do build
failed to load plan: "actions.deploy.site" is not set:
    ./repro.cue:13:3
    ./repro.cue:14:4


Usage: 
  dagger do [flags]


Flags:
      --cache-from stringArray   External cache sources (eg. user/app:cache, type=local,src=path/to/dir)
      --cache-to stringArray     Cache export destinations (eg. user/app:cache, type=local,dest=path/to/dir)
  -h, --help                     help for do
      --no-cache                 Disable caching
  -p, --plan string              Path to plan (defaults to current directory) (default ".")
      --platform string          Set target build platform (requires experimental)
  -w, --with stringArray
Global Flags:
      --experimental        Enable experimental features
      --log-format string   Log format (auto, plain, tty, json) (default "auto")
  -l, --log-level string    Log level (default "info")
```

**Comment by aluzzardi** [comment]
Added some context here: https://github.com/dagger/dagger/pull/2372#issuecomment-1113867006

In summary, this is **very** hard to do.

The whole validation system was a major headache to pull off. It runs off many assumptions. One of those is it must walk the entire tree, top-down.

The "chunks of CUE" that are going to be pulled in to execute a single action are an unknown quantity.

I'm not just talking about "task dependencies", I also mean the bits of CUE that are needed to evaluate an action and might not be part of an action themselves.
