### ISSUE TITLE
🐞 GHA Throttling causes CI to fail

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#2365]
### What is the issue?

We appear to be hitting some sort of limit/throttling with GHA as many PRs are getting timeouts while trying to export cache, especially when they are running in parallel with one another. This needs to be fully confirmed as the only error message we get [is `maximum timeout reached` from this line](https://github.com/sipsma/buildkit/blob/2683fbb986737fa744e7a9b00773347dd3d80e83/vendor/github.com/tonistiigi/go-actions-cache/retry.go#L42), which is not especially descriptive, but given that it happens when there's lots of PRs concurrently exporting to GHA and we just updated our CI to export to GHA more, this seems a decently likely explanation.

This is extremely painful because it causes CI in PRs to fail and the only consistent way to get them to pass is to ensure that only one PR run executes at a time. Lots of manual clicking and waiting.

There's a few options, none of which are mutually exclusive:
1. Get a limit increase on GHA
2. Make the failure to export cache non-fatal to CI runs, just a best-effort thing
3. Export less cache data to GHA

In general, `1` doesn't seem great unless we get a better handle on the issue, know what scale of limit increase we need and are committed to using GHA for at least a while. Otherwise I think we might just be playing whack-a-mole here.

`2` is a good option, but it's unfortunately harder than it should be right now for a few reasons:
1. Buildkit doesn't have built-in support for this yet: https://github.com/moby/buildkit/issues/2578
2. The approach of first doing a solve w/out any cache export options and then repeating the exact same solve with cache exports almost works, but not in the case where we set `always: true` (i.e. `llb.IgnoreCache`). You could perhaps have the second solve override every setting of `IgnoreCache` to be false, but that's a pretty huge hack.

That leaves `3`, which while unfortunate might be the right immediate step IMO. I think we could continue to import/export cache from our main branch, but then in PRs only import cache from the main branch and disable import/export of PR-specific cache. That leaves us with some benefits but less chance of hitting fatal errors that block PRs.
* Note: Buildkit does try to make cache import errors be non-fatal (as opposed to export), but [as noted here](https://github.com/dagger/dagger/issues/324#issuecomment-1112554327) this doesn't cover every case right now.

### Dagger version

n/a

### OS version

n/a

**Comment by sipsma** [comment]
[Related issue in Buildkit](https://github.com/moby/buildkit/issues/2804), some confirmation from Github team that throttles are possible at relatively small scales. Doesn't guarantee that's exactly what's happening to us too, but adds to the evidence.

**Comment by sipsma** [comment]
Figured out one major cause here that is also slowing our CI down an enormous amount.

Even though we export to GHA using per-test scopes, there are often multiple invocations of `dagger do` within a single test, each of which will use the same export target and thus overwrite each other's cache manifests.

This meant that we would pay the price to export cache (quite expensive for large blobs), eat up our bandwidth limit uploading that cache (causing more throttles) and then never actually reuse the cache because the manifest got overwritten.

[For one example, the `./container.cue` test in the `go` universe package](https://github.com/dagger/dagger/blob/main/pkg/universe.dagger.io/go/test/test.bats#L9) would take ~8 seconds to execute w/out cache hits, but then spend ~30 seconds exporting cache. If you run the test on its own in GHA so that the cache manifest doesn't get overwritten, it will only take 3 seconds to run. So in this single test case we were wasting ~37 seconds most runs. There are many other test cases in the same boat.

<img width="2383" alt="Screen Shot 2022-05-05 at 1 09 04 PM" src="https://user-images.githubusercontent.com/30126853/167018063-aecaf4ad-5166-4351-a934-913352c52708.png">

In terms of the fix, in the immediate-term we can just split multiple invocations of `dagger do` in the tests into multiple bats test cases so they each get a separate name. In general though, we need a way for users to easily manage this, as discussed [here](https://github.com/dagger/dagger/issues/2140). The proposal there to have cache be configured as part of a `Plan` might be a good option as you could more programmatically namespace the cache targets.

Also, another lesson from this is that it was very difficult to find out any of this; our current observability into cache performance is next to nothing. I hacked together in my fork a bunch of stuff for collecting Jaeger traces in GHA that can be exported and orchestrating tests that let you more easily compare multiple test runs with different cache settings. I will prioritize productionizing this so we can more quickly diagnose these types of issues in the future.

**Comment by sipsma** [comment]
Just a note since I didn't explicitly mention it previously, with the new traces I setup in the integration tests I confirmed that these slowdowns are due to GHA cache returning 429 errors when importing/exporting cache, which causes Buildkit to exponentially backoff and the tests to timeout.

**Comment by marcosnils** [comment]
> In terms of the fix, in the immediate-term we can just split multiple invocations of `dagger do` in the tests into multiple bats test cases so they each get a separate name.

how about if instead of setting the dagger cache at the global level like we do here (https://github.com/dagger/dagger/commit/ccf5e66ef42f4d993c166816a01666c6ccb456ff#diff-a497976d6ef820a2a28e4dd1a6f3cdce8fba2bc36647b4e168beee966d98bd57L57-L67) we do it for each `dagger do` that bats runs here https://github.com/dagger/dagger/blob/main/tests/helpers.bash?

That should fix the cache overwriting issue since we can use different cache names per test, correct?

**Comment by sipsma** [comment]
Closing this as we don't use GHA cache in our CI anymore.
