### ISSUE TITLE
Proposal: LLB Network support

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#237]
#### Goal

In order for dagger to communicate with `localhost`, it must support the `llb.Network()` operation.

This is necessary when deploying to minikube/KinD.

#### Network support in CueLLB:

```
llb.#Exec {
  network: *"sandbox" | "host" | "none"`
}
```

This gets directly translated to the LLB equivalent (e.g. `llb.Network(llb.NetModeHost)`)

#### Entitlements support in Dagger

The previous LLB snippet will **not** work, unless the build session has been started with the right entitlement.

I propose a simple solution: support the same entitlement flag as buildctl for `dagger up` and `dagger compute`, as follows:

```
$ dagger up --allow network.host
```

The parser is available here: https://github.com/moby/buildkit/blob/4e69662758446c7dc0e6de2bc1f7973d03bacbed/cmd/buildctl/build/allow.go

We might do something more complex in the future (e.g. set per deployment entitlements), but having that on `compute`/`up` does the trick for now.

#### UX Enhancement: Prompt for entitlements

With entitlements, the Cue configuration will fail late in the game as soon as some LLB attempts to do a `llb.Network`.

To enhance the UX, I propose we do something similar to how we handle `#Local` today: scan the configuration, detect if there are any `network: "host"` and abort with a clean message if the entitlement has not been set.

```
$ dagger up
FTL myApp.kubernetes.cuePath requires host mode networking. To enable it use --allow "network.host"
$ dagger up --allow network.host
INF computing ...
```

#### Start the builtin buildkitd with the right permissions

For entitlements to work, they must be enabled in buildkitd directly.

I propose we do this by default in the `buildkitd` instance dagger creates by default. Operators can decide to lock this down by creating their own `buildkitd` instance and using a custom `BUILDKIT_HOST` can running dagger.

**Comment by lyzhang1999** [comment]
so far, do we have any possible solution for access minikube and kind?

**Comment by marcosnils** [comment]
> so far, do we have any possible solution for access minikube and kind?

Yes, check out https://discord.com/channels/707636530424053791/709803368318632038/966786084111540314

It's  a "hack" but it should work until we find out the best UX here.
