### ISSUE TITLE
Secrets from cloud secret manager

### ISSUE THREAD

**Issue by mrgleeco** [dagger/dagger#2377]
### What are you trying to do?

Ideally dagger can support secrets found in a secret manager, eg. [GCP secret manager](https://cloud.google.com/secret-manager/docs) or [AWS](https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html)

Perhaps this exists(?) and i am just seeking docs...

**Comment by TomChv** [comment]
It actually does, we already have a type named `dagger.#Secret` that can store secret.

See [dagger secrets docs](https://docs.dagger.io/1204/secrets/#what-are-secrets) for more information.

**Comment by samalba** [comment]
Duplicate of #2377

**Comment by marcindulak** [comment]
This issue is 2377. Which is the duplicate?

**Comment by samalba** [comment]
> This issue is 2377. Which is the duplicate?

🤦 sorry my bad...

I meant Duplicate of #4339

**Comment by samalba** [comment]
Duplicate of #4339
