### ISSUE TITLE
docs: Provide more information about what dagger.#Secret actually does

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#2383]
### What is the issue?

The dagger 0.2 docs have a section about handling secrets here: https://docs.dagger.io/1204/secrets. However, this page doesn't mention anything what using `dagger.#Secret` actually enables and what properties this entails. 

Is my data encrypted?
How are secrets secure?
How can I guarantee that only specific actions can access secrets?

I think it'd be a good idea to provide a bit more in-depth detail about what secrets are and how Dagger handles them internally. Finally, I've seen some users asking questions about how to integrate with X provider like Vault, Secrets Manager, etc. A starting point in the docs mentioning this I believe it'd be very useful also.

cc @jpadams

**Comment by shykes** [comment]
Agreed. There is content in the Europa release post that could be used as a starting point: https://dagger.io/blog/dagger-0-2 . See “ Secure by default: the Secrets API”.

**Comment by marcosnils** [comment]
> See “ Secure by default: the Secrets API”.

This. 

It's a bit misleading that  the end of the article has a link to "learn more about secrets" and it redirects to our current docs (https://docs.dagger.io/1204/secrets/) which bring us back to the reason of this issue. :pray:

**Comment by shykes** [comment]
This was requested by a user on Discord yesterday.

![6E869FCE-643F-4AE6-9316-FF07B9609084](https://user-images.githubusercontent.com/29565/168904980-0e581a74-829a-4c18-b7d9-7a7f7b061bbd.jpeg)

**Comment by jpadams** [comment]
<img width="971" alt="image" src="https://user-images.githubusercontent.com/3187222/169729277-22623b9d-7c12-44e8-a6cd-cc7795056252.png">

Need to ensure that we cover secrets as inputs via environment variables, files, and cli flags (unsupported, I believe: https://github.com/dagger/dagger/issues/1719#issuecomment-1065516501).
