### ISSUE TITLE
core.#Copy exclude functionality not working

### ISSUE THREAD

**Issue by akselleirv** [dagger/dagger#2401]
### What is the issue?

I'm trying to delete a sub-directory by using `core.#Copy`, but it fails when marking the sub-directory as excluded.

### Log output

```
9:14AM FTL failed to execute plan: task failed: actions.syncK8sRepo.copy: failed to copy file info: failed to chown /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/48/fs/test-dir/another-dir: lchown /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/48/fs/test-dir/another-dir: no such file or directory
```

### Steps to reproduce

Filesystem used for example:
```
└── test-dir
    ├── another-dir
    │   └── another-file.txt
    └── some-file.txt
```

```
package pipeline

import (
    "dagger.io/dagger"
    "dagger.io/dagger/core"
)

dagger.#Plan & {
    client: filesystem: {
        "./copied": write: contents: actions.syncK8sRepo.copy.output
        "./": read: contents:        dagger.#FS
    }
    actions: syncK8sRepo: copy: core.#Copy & {
        input:    dagger.#Scratch
        contents: client.filesystem."./".read.contents
        exclude: ["./test-dir/another-dir"]
    }
}
```

### Dagger version

dagger 0.2.9 (4fc38dac) darwin/arm64

### OS version

macOS 12.3.1

**Comment by dolanor** [comment]
I reproduced it on linux/amd64.
It seems core.#Copy is trying to chown the excluded dirs. Is it because it has some knowledge of the lower level FS, before the files gets excluded?
@sipsma Do you know if it is more related to buildkit than to dagger?

**Comment by helderco** [comment]
You can try a glob pattern:
```cue
exclude: ["./test-dir/another-dir/*"]
```
But this won't exclude the directory, only it's contents. There's a workaround if you need, where you can run a command in your host to rm that dir.

**Comment by helderco** [comment]
> @sipsma Do you know if it is more related to buildkit than to dagger?

We're passing through to buildkit, we may need to enable an option.

**Comment by helderco** [comment]
It's supported here: https://github.com/moby/buildkit/blob/a7fa387fe3524303c70eeddb22e50dd351f319f7/client/client_test.go#L1400

**Comment by jlongtine** [comment]
I changed: https://github.com/dagger/dagger/blob/8cfb840d21d6d6ba3e36d5cbe2c03354eb0a0945/plan/task/copy.go#L63-L69

to 
```go
	opts := &llb.CopyInfo{
		CopyDirContentsOnly: false,
		CreateDestPath:      true,
		AllowWildcard:       true,
		IncludePatterns:     filters.Include,
		ExcludePatterns:     filters.Exclude,
	}
```

And this case works. @aluzzardi + @sipsma, do you know what the intent of `CopyDirContentsOnly: true` vs `CopyDirContentsOnly: false` is?

**Comment by helderco** [comment]
I tried that but didn't work. Maybe I didn't hook the right build in the repro 🙂

**Comment by sipsma** [comment]
I am looking into this, but one quick note before I forget, there's two features we could easily add that would make this use case much more sane:
1. Support for `core.#Rm`
   * `Rm` is a builtin FileOp subtype in Buildkit, so very little effort required
3. Support for getting a mount after an `Exec`. This would have allowed the workaround of mounting the fs at somewhere like `/mnt` and then using the `rm -rf` or similar command to remove the files. In this use case might be overkill but in general is nice to have if you want a command that more selectively deletes files.
   * Also something that's in Buildkit (`GetMount`) that we just haven't exposed yet.

Gonna try reproducing this quick but will create issues for those after if they don't exist already.

**Comment by sipsma** [comment]
I think this is just a bug in Buildkit, I can reproduce it with LLB directly.

There's a code path where even though the directory is never created and didn't exist, `overwriteTargetMetadata` is set true, which results in `copyFileInfo` staying its default value of true, which finally results in the code incorrectly trying to update the owner of the non-existent dir: 
https://github.com/tonistiigi/fsutil/blob/3c5c7e8489942350b821cf16683d7d2dc4368023/copy/copy.go#L348-L349

Gonna open a PR with a fix in the fsutil repo to confirm.

Unfortunately, this mean that we need to wait for another Buildkit release to have a fix. I think @helderco's suggestion to use a `client` command to remove the dir might be all that's possible at the exact moment. Adding support for `core.#Rm` is also pretty easy and would probably be faster to get out in the next dagger release than it is to wait for a Buildkit release with the fix.

**Comment by sipsma** [comment]
Open a PR with a fix to the 3rd party fsutil repo here: https://github.com/tonistiigi/fsutil/pull/132

Open issues for the features we should have to support use cases like this here:
* https://github.com/dagger/dagger/issues/2408
* https://github.com/dagger/dagger/issues/2409

**Comment by akselleirv** [comment]
Adding support for delete would solve my use-case as my use of copy is simply a workaround for the lack for `core.#Rm`

**Comment by TomChv** [comment]
Issue closed since we implemented this feature in our old Dagger API and it's currently possible through shell script and `exclude` fields when we mount a directory..
