### ISSUE TITLE
✨ Make `core.#Exec.hosts` editable in `docker.#Run`

### ISSUE THREAD

**Issue by teneko** [dagger/dagger#2407]
### What are you trying to do?

I want to set the hosts in a `docker.#Run`, but it is unfortunately not exposed because `_exec` is not mutable from the outside and therefore `core.#Exec.hosts` not editable.

Either delegate hosts from docker.#Run to _exec or make _exec publish and therefore accessible from outside. I personally prefer the second one to comply with CUE and make everything extendible.

### Why is this important to you?

Realize commands like `docker run --add-host=host.docker.internal:host-gateway`.

### How are you currently working around this?

Copying the hole docker.#Run definition and implemented one of the solutions described above.

**Comment by TomChv** [comment]
Great suggestion!

Feel free to open a PR that includes this change :rocket:

**Comment by TomChv** [comment]
Related to CUE, we are not longer working on this version so I'm closing this issue.
