### ISSUE TITLE
✨ Support for removing files (`core.#Rm`)

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#2408]
### What are you trying to do?

Remove files, similar to how I can make files and dirs with `core` tasks. `Rm` is a supported FileOp type in Buildkit, so not much effort needed in Dagger.

### Why is this important to you?

Users needed it here, had to resort to workaround (that turned out to have a buildkit bug anyways): https://github.com/dagger/dagger/issues/2401

**Comment by TomChv** [comment]
If you don't mind, I would like to take care of that one.

[Here's a link to `llb.Rm`](https://github.com/moby/buildkit/blob/master/client/llb/fileop.go#L82). I think we can also [enable wildcard](https://github.com/moby/buildkit/blob/9b45d4513b8d6f46a7e9cb5b7d7b4fa367065862/client/llb/fileop.go#L376), that could be useful.

Here's the current definition I have in mind:

```cue
// dagger/core/fs.cue
#Rm: {
  // Container filesystem
  input: dagger.#FS

  // Path to delete (handle wildcard)
  // (e.g., /file.txt or /*.txt)
  path: string

  // Modified filesystem
  output: dagger.#FS @dagger(generated)
}
```

WDYT? @sipsma @shykes?

**Comment by sipsma** [comment]
Thanks @TomChv that looks good. The only thing I'd add are fields equivalent to the options available in Builkdkit: https://github.com/moby/buildkit/blob/b6924b0f5f01c8cdea34238e1d35278ea6eb9680/client/llb/fileop.go#L360-L361

The "allowWildcards" field is necessary to handle the extreme corner case where someone creates a file or dir that actually has the char `*` in its name. It's more debatable whether we in Dagger should default to allowing them or not, but either way the toggle should exist IMO.

"AllowNotFound" would be good too, I guess it's the equivalent of the `-f` option in `rm` sortof.

**Comment by TomChv** [comment]
Thank you! I take care of that tomorrow

**Comment by TomChv** [comment]
I did some test with `AllowNotFound` and it looks like it doesn't works.

That sound logic since [`removeAll`](https://github.com/moby/buildkit/blob/master/solver/llbsolver/file/backend.go#L159) do not return an error if path do not exist

> RemoveAll removes path and any children it contains. It removes everything it can but returns the first error it encounters. If the path does not exist, RemoveAll returns nil (no error). If there is an error, it will be of type *PathError.

Indeed, it's not a blocker for now but I'm not sure we can make `AllowNotFound` working for now.
