### ISSUE TITLE
✨ Support for getting a `Mount` after execution of an `Exec`

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#2409]
### What are you trying to do?

In Buildkit, you are able to mount a filesystem in an `ExecOp`, make changes to it in the exec and then get the new updated contents after the Exec (at which point it can be used as any other LLB state). E.g.
```go
// mnt will have the contents of busybox plus /foo
mnt := llb.Image("alpine").Run(
   llb.Shlex("touch /mnt/foo"),
   llb.AddMount("/mnt", llb.Image("busybox")),
).GetMount("/mnt")
```

The same should be true of Dagger's `core.Exec`. `FS` mounts should be retrievable after the Exec.

### Why is this important to you?

Use cases include
* modifying filesystems with commands, e.g. if you have a directory that you want to remove files matching a certain specific pattern, you could mount it on a rootfs and then use the `find` command from that rootfs to delete them. 
* the target for something like `DESTDIR=/mnt make install`, which allows you to collect artifacts together into an isolated filesystem and then use that fs however you want (i.e. as an input to `Merge`)

### How are you currently working around this?

Sometimes merge+diff can be use instead, but there are tradeoffs with that approach currently. Just being able to get a mount after an Exec is sometimes the simpler approach.

**Comment by jaen** [comment]
FWIW this is what I have tried to do when figuring out how to emulate shell globs in copy by rsync-ing between `#FS`es, naively assuming mounts will just be mutable directories as usual – but it didn't work. Could be useful to implement it.

**Comment by sipsma** [comment]
We support this in 0.3 now: https://github.com/dagger/dagger/blob/d49784610d9fae36f047e5b23ee739dbf0cab1e6/core/schema/container.graphqls#L42-L43
