### ISSUE TITLE
Expose packages' Definition interfaces in a more standardised way

### ISSUE THREAD

**Issue by jpluscplusm** [dagger/dagger#2415]
### What is the issue?

When using a non-core (e.g. universe) package, it takes some digging to discover which Definitions a specific package embeds and uses. It's already clear, in a standardised location, which Definitions a particular package *uses*, as the Is-A syntax puts this front and centre (`foo: #bar & { ... }`).

Given that the IsA-vs-embedded distinction isn't important to the consumer (as both define which fields the user *must* and *may* provide concrete definitions for, and also "use" as outputs, if required) it would be fantastic if packages made the embedded definitions that define their external interface more discoverable and more obvious.

One easy way to make it more obvious would be to place a block at the top of each Definition that explicitly lists the Definitions that are embedded. For example, https://github.com/dagger/dagger/blob/main/pkg/universe.dagger.io/bash/bash.cue#L12 currently calls out the embedding as a comment. As well as this comment, changing and adding to the CUE definition, taking it from its current:

```
#Run: {
	// The script to execute
	script: {
		// A directory containing one or more bash scripts
		directory: dagger.#FS
...
```

to, instead, reflect https://github.com/dagger/dagger/blob/main/pkg/universe.dagger.io/bash/bash.cue#L44 

```
#Run: {
	// Definitions embedded by this definition
	docker.#Run
	// The script to execute
	script: {
		// A directory containing one or more bash scripts
		directory: dagger.#FS
...
```

... then it will be clearer for the consumer which *other* definitions they need to look at.

So it's clear that this isn't an Issue being filed against the bash.#Run Definition, also consider the AWS package. It requires hunting from line 10 all the way through to line 111 (https://github.com/dagger/dagger/blob/main/pkg/universe.dagger.io/aws/cli/cli.cue#L111) before the embedding is discovered. 

Placing this naked embedding right at the top of each Definition and establishing it as the norm would produce a nice network effect that other in- **and out-** of universe packages could adopt. Which, given that the primary reference documentation for Dagger currently just points at the CUE definitions (https://docs.dagger.io/1222/core-actions-reference), might well be of significant value to a wider set of consumers. 

Adding the embedded Definitions only as a comment might get out of sync with the code. Adding them as CUE constraints would act as a guard against this desync. I believe that adding a naked embedding statement produces semantically identical CUE, so I'm filing this as a documentation issue. Please do re-tag/re-name as appropriate!

**Comment by TomChv** [comment]
I totally agree with your comments!

WDYT @helderco @shykes @jpadams ?

**Comment by helderco** [comment]
I understand your point of view, but I like to put the new fields next to the definitions they apply to. Maybe seeing it in action I could warm up to it 🙂
