### ISSUE TITLE
Guide for mounting docker socket use cases, with AWS `sam` cli example.

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2421]
### What is the issue?

This are great docs for interacting with a docker socket on the client
- https://docs.dagger.io/1203/client/#using-a-local-socket
- https://docs.dagger.io/1216/docker-cli-load/

but users might not know to look for these when they're getting an error like from `sam build`:

```
Error: Building image for LambdaFunction requires Docker. is Docker running?
```

We should explain a bit more when/why you might use this approach generally.
Not sure if there are other examples like this, a cli tool that itself calls `docker build`.

**Comment by munichbughunter** [comment]
Here is an example... 

https://docs.dagger.io/1248/aws-sam
