### ISSUE TITLE
`cue fmt -s` aka `--simplify` in CI linter is confusing for users making PRs

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2434]
`cue fmt -s` aka `--simplify` in linter is confusing for users making PRs with valid CUE code that doesn't pass.

https://github.com/dagger/dagger/pull/2433#issuecomment-1124550442

If this is important to us, it should be be documented somewhere like https://docs.dagger.io/1226/coding-style and users need better feedback/error messages in GitHub.

cc @samalba

**Comment by samalba** [comment]
I think this is important to us to enforce some consistency. I'll update the coding style.
