### ISSUE TITLE
Proposal: provide core.#ClientGlobalEnv to get env in any package

### ISSUE THREAD

**Issue by morlay** [dagger/dagger#2437]
### What are you trying to do?

Provide `core.#ClientGlobalEnv` to get env var which defined in `client.env`.

### Why is this important to you?

Now we have to define all env var in `client.env`

```cue
#GoBuild: {
    docker.#Run & {
        env: _
    }
}

dagger.#Plan & {
    client: {
        platform: _

        env: {
            GOPROXY:   string | *""
            GOPRIVATE: string | *""
            GOSUMDB:   string | *""
        }
    }
    actions: {
        _envForGoProxy: {
             GOPROXY:   client.GOPROXY
             GOPRIVATE: client.GOPRIVATE
             GOSUMDB:   client.GOSUMDB
        }
    
        build: {
            // once the build jobs incrase, (it always happened in micro services project)
            a:  #GoBuild & {
                env:  { 
                   // putting this for each one will be painful
                   _envForGoProxy
                }
            }
        }
    }
}
```

if we could get the unnecessary env var in the pre-defined task. it will make plan to simple.

```cue
#GoBuild: {
    _env: core.#ClientGlobalEnv & {
        GOPROXY?:   string // could return value
        GOPRIVATE?: string // could return value
        GOSUMDB?:   string // nothing return
    }

    docker.#Run & {
        env: _env
    }
}

dagger.#Plan & {
    client: {
         GOPROXY?:   string @global()  // or @scope("global") ?
         GOPRIVATE?: string @global()
    }
    actions: {
        build:  a:  #GoBuild & {}
        build:  b:  #GoBuild & {}
        build:  c:  #GoBuild & {}
    }
}
```

**Comment by helderco** [comment]
This is the same issue that I replied in:
- https://github.com/dagger/dagger/issues/2200#issuecomment-1100082395

> We decided against this for security reasons, in the sense that we don't want users to load files from their computer automatically from actions they're reusing from others, without being aware. You have to go through your plan's client to do that. It's by design.
>
> [...] We focus on reusable actions, not reusable plans [...]
>
> We made the decision that anything that communicates with the host machine, must come from the `client` top level field in the `dagger.#Plan`.

So this is for security reasons. It may look harmless with some environment variables but these can be secrets so there's real sensitive information that could be exposed like this, hidden in a third-party package.

In the plan, you have a top level field that makes it clear what's being read from the host machine. So you must explicitly allow what you want and set the inputs in the actions you're using.

**Comment by morlay** [comment]
For the security reason.

How about create `core.#ClientEnv` to limit usage?
only can get env key which defined in client.env

```
#GoBuild: {
    _env: core.#ClientEnv & {
        GOPROXY?:   string // could return value
        GOPRIVATE?: string // could return value
        GOSUMDB?:   string // nothing return
    }

    docker.#Run & {
        env: _env
    }
}

dagger.#Plan & {
    client: {
         GOPROXY?:   string
         GOPRIVATE?: string
    }
    actions: {
        build:  a:  #GoBuild & {}
    }
}

```

**Comment by helderco** [comment]
It's an interesting idea at first glance, but even though it's more verbose, it's also more clear where you're hooking stuff from client into which actions.

If you look only at the plan, not knowing how the actions are built, necessarily, it would seem you're exposing variables and not using them.

But the biggest downside, I think is, how would you control which variables you want exposed to which actions? If you need your SSH private key only in action `a`, action `#B` would be able to read it.

**Comment by morlay** [comment]
@helderco 

Could split to `client.unsafeEnv` 😂 
or using cue value tag `@unsafe()` to mark sharable

**Comment by helderco** [comment]
Hey, we're planning on redesigning Client API (#2470). We should take this into consideration then.
