### ISSUE TITLE
Error passing cache

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2439]
Filed on behalf of `Luis T#1639` on Discord:

> Hello, I have a question regarding the use of the core.#Cache, what I am trying to do is to create an action that accepts cache as field and pass that field to docker.#Run actions, but can't get it to work, I get an error of empty disjunction.
> If instead I create the cache inside the action it works, any recommendation is well appreciated 🙏 
> ```
> package vscode
> import (
>     "dagger.io/dagger"
>     "dagger.io/dagger/core"
>     "universe.dagger.io/docker"
>     "universe.dagger.io/docker/cli"
> )
> #Add: {
>     url: string
>     file: string
>     sufix: string 
>     cache: core.#Mount
> 
>     toil: docker.#Build & {
>         steps: [
>             docker.#Pull & {
>                 source: "index.docker.io/alpine:latest"
>             },
>             docker.#Run & {
>                 env: "url": url
>                 env: "file": file
>                 env: "sufix": sufix
>                 workdir: "/cache"
>                 mounts: cache: {
>                     dest: "/cache"
>                     contents: cache
>                 },
>                 command: {
>                     name: "sh",
>                     flags: "-c":"""
>                         wget $url -o $file.$sufix
>                     """
>                 }
>             }
>         ]
>     }
>     output: toil.output
> }
> dagger.#Plan & {
>     client: {
>         filesystem: {
>             "./": read: contents: dagger.#FS
>         }
>         network: {
>             "unix:///var/run/docker.sock": {
>                 connect: {
>                     dagger.#Socket
>                 }
>             }
>         }
>         env: {
>             "IMAGE_TAG": string | *"demo"
>         }
>     }
>     actions: {
>         _cache: core.#CacheDir & {
>           id: "internalCache"
>         }
>         add: #Add & {
>             url: "https:~"
>             file: "terraform"
>             sufix: "zip"
>             cache: _cache
>         }
>     }   
> }
> ```

**Comment by lat0z** [comment]
I am getting this error 
```
failed to load plan: actions.add.cache: 1 errors in empty disjunction:
actions.add.cache: field not allowed: dest:
    ./cue.mod/pkg/dagger.io/dagger/core/exec.cue:93:2
    ./cue.mod/pkg/dagger.io/dagger/core/exec.cue:95:2
    ./cue.mod/pkg/dagger.io/dagger/core/exec.cue:119:12
    ./partial.cue:26:12
```
If you want me to send the original plan I can share it, I have just removed few actions at the time I sent it to discord

**Comment by helderco** [comment]
Hi @lat0z, just looking at your plan quickly I spotted a shadowing issue. Try this:

```diff
#Add: {
    cache: core.#Mount
    ...
-                mounts: cache: {
+                mounts: "cache": {
                    dest: "/cache"
                    contents: cache
                },
}
```

**Comment by lat0z** [comment]
@helderco Thanks!, that is what I was missing to fix it
