### ISSUE TITLE
TTY rendering is buggy (e.g. flashing/broken lines)

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#2444]
To fix this, I tried to add test to understand and consolidate our codebase around this.
It's more tricky as I can't just use a mock. The mock file type would get tested by containerd via syscall to check if it's a correct TTY.
So for now, I'm debugging it directly to understand what's the logic flaw.

**Comment by mircubed** [comment]
@dolanor were you able to sync with Sam about this one to see how he might want this to move forward? If I remember correctly, this one relates to pre-europa right?

**Comment by dolanor** [comment]
@mircubed, maybe, I'm not sure.

I finally made a breakthrough, it needs some rearchitecture to separate size/format from styling as we're currently doing both and counting size once styling escape codes or markups are in the text, which totally screw the count and get garbled once we have to trim a too long message.

My strategy is to use some struct that will store the content (string) with its correct length (the grapheme, not just the rune nor the byte) as well as the styling that should be applied to it.
On a first pass, I'll deal with the sizing + padding
On the second pass, I'll deal with adding the style markup/escape code, before sending that to the console.

**Comment by dolanor** [comment]
This was for the previous engine, so it is obsolete now.
