### ISSUE TITLE
How about introducing bitbucket✨

### ISSUE THREAD

**Issue by Youngshark3** [dagger/dagger#2451]
### What are you trying to do?

I would like to introduce bitbucket on your feature to help manage tasks. 

### Why is this important to you?

I find bitbucket so cool especially when it comes to pipelines handling. 

### How are you currently working around this?

am working with a team to improve and come up with a  good plugin to collaborate and integrate the two tools for efficient deployment.

**Comment by TomChv** [comment]
@Youngshark3 Hey 👋 

Have you made some progress? Your use case looks interesting!

/cc @jpadams

**Comment by helderco** [comment]
Duplicate of https://github.com/dagger/dagger/issues/5444
