### ISSUE TITLE
Update the get started video for Dagger 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#2472]
It would be great to change the getting started page to match this look and feel: [example ](https://www.pulumi.com/resources/getting-started-with-automation-api/)

We need to update our getting started video from this page:[old video](https://docs.dagger.io/1003/get-started/)

**Comment by mircubed** [comment]
@jpadams who would be best to record this new video? I would do it, but I am not technical enough atm. Was this the video that you were talking about creating already?

**Comment by jpadams** [comment]
> @jpadams who would be best to record this new video? I would do it, but I am not technical enough atm. Was this the video that you were talking about creating already?

Yes! We can def work on together if you'd like to get more hands on.

**Comment by mircubed** [comment]
yup, would love to! I can edit pretty well in Imovie too, so I can help a lot with post edit stuff.

**Comment by mircubed** [comment]
@jpadams let me know if I can help with this at all. Otherwise, I'll just wait for the video and then we can incorporate it into changes needed for #1912
