### ISSUE TITLE
Standalone install page

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2490]
## Problem

The [Dagger documentation](https://docs.dagger.io) don't have a standalone install page. There are installation instructions, but they are embedded/hidden inside the Getting Started tutorial.

Having a standalone install page, and ideally a easy-to-find location on the main website like "dagger.io/install" are tablestakes.

## Solution

Create a standalone install page.

**Comment by samalba** [comment]
Duplicate of #2129?

**Comment by shykes** [comment]
Indeed :) Thanks
