### ISSUE TITLE
Don't show log-formatted messages on a tty

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2492]
## Problem

`dagger` prints most of its output via a standardized logger. This logger is great for producing machine-readable outputs, or sysadmin-friendly log files. But it makes the tool less pleasant to use compared to other command-line client tools. Prefixing every line with a cryptic loglevel code and timestamp, eg. `1:47AM FTL <the part you care about>` makes the UX worse.

## Solution

Print regular outputs to the user like other regular command-line clients; without sacrificing the ability to produce great machine-readable and sysadmin-friendlt logs when needed.

**Comment by dolanor** [comment]
Would option/flag be a good enough solution for this?

**Comment by shykes** [comment]
I don't think so, no.

**Comment by dolanor** [comment]
I replied here https://github.com/dagger/dagger/issues/2146#issuecomment-1143298030

> So we should check if this execution is run inside a terminal or not, and if yes, we remove the log prefix (with level + timestamp)?
Do we do that in all log formats (plain + tty)?
