### ISSUE TITLE
Fix `dagger.mod` and `dagger.sum` formats

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#2502]
## Problem

The `dagger.mod` and `dagger.sum` files are being written with a simple `fmt.Sprintf()`. `dagger.mod` isn't storing pseudo-versions for branches and in the case of `dagger.sum` it's also missing the version component.

## Solution

I think there's stuff we can reuse from `golang.org/x/mod` to parse and write these files. Also, make sure to generate pseudo versions for branches.

**Comment by TomChv** [comment]
I'm closing this outdated issue, we are no longer using `dagger.mod` and `dagger.sum`
