### ISSUE TITLE
Do not require vendoring packages in git (i.e., use a global cache)

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#2503]
## Problem

CUE only looks for packages in `cue.mod/{pkg,gen,usr}` (merging these directories). This has required us to commit packages to git.

## Solution

We do have our own `dagger.mod` and `dagger.sum` files, like Go. We can make them good enough to be depended on to reinstall packages in new git clones like in CI (verifying checksums). This makes committing `cue.mod/pkg` less necessary.

But I want to propose using a global cache here.

### Global cache

We can take a hint from [cuemod](https://github.com/octohelm/cuemod), which downloads modules into a global cache (GOMODCACHE in that case), and then symlinking them into `cue.mod/pkg`. @morlay took inspiration from [pnpm](https://pnpm.io) (homebrew does this as well), although it uses hard links instead of symlinks (there's a whole discussion on why that's better).

We could do the same. Use the global cache to avoid re-downloading repos and also for verifying the checksums. At which point, link packages into `cue.mod/pkg` so that CUE can read them. CI can also be configured to cache this directory.

### Ask upstream to add setting

It would be much better if upstream supported looking for packages in a `$CUEMODCACHE` environment variable, besides `cue.mod/pkg`, even if they don't use/manage it themselves yet. It would avoid the need to symlink and I think it's a very easy change on their part. Planned even.

UPDATE: not an easy change to ask because of lack of version concept.

**Comment by morlay** [comment]
Cue not  resolve sub vendor (`cue.mod/pkg`) like go vendor did.
Once import path resolved, all sub module will use the first one

```shell
cue.mod
├── module.cue
└── pkg
    └── x.io
        ├── a
        │   ├── a.cue
        │   └── cue.mod  // cue will never resolve this folder
        │       ├── module.cue
        │       └── pkg
        │           └── x.io
        │               └── b 
        │                   └── b.cue
        └── b
            └── b.cue

```
If cue support sue vendor resolve, 
we could create store like pnpm did, to support multi versions (just for semver conflicts)
https://github.com/morlay/cue-mod-multiple-versions
