### ISSUE TITLE
Support "tidy"'ing

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#2508]
## Problem

To keep a project up to date on dependencies, there's a bit of manual work involved.

## Solution

Add a new `dagger project tidy` command that does the following:

1. Scan project imports
2. Add missing requirements to `dagger.mod`
3. Remove unused requirements from `dagger.mod`
4. Do a `dagger project update` (installs requirements, verifies/updates checksums)
5. Remove files that aren't being used (from global cache or  `cue.mod/pkg` if not)

**Comment by mlkmhd** [comment]
this project was a good package manager for ‍‍`.cue` files:
https://github.com/octohelm/cuemod

is it possible to merge it to dagger source?

**Comment by helderco** [comment]
> is it possible to merge it to dagger source?

Not right now, I replied in https://github.com/dagger/dagger/pull/2292#issuecomment-1159254500.

**Comment by helderco** [comment]
Closing. More context in parent issue: https://github.com/dagger/dagger/issues/2163.
