### ISSUE TITLE
✨ rename _op to _pull

### ISSUE THREAD

**Issue by tekumara** [dagger/dagger#2536]
### What are you trying to do?

Given an action like:
```
		_alpine: alpine.#Build & {
			packages: bash: _
		}
```

The output is
```
6:59PM INF actions._alpine._dag."0"._op | computing
6:59PM INF client.env | computing
6:59PM INF client.env | completed duration=0s
6:59PM INF actions._pull | computing
6:59PM INF actions._pull | completed duration=0s
6:59PM INF actions._alpine._dag."0"._op | completed duration=3.7s
6:59PM INF actions._alpine._dag."1"._exec | computing
6:59PM INF actions._alpine._dag."1"._exec | completed duration=0s
```

It's not self-evident that the line
```
6:59PM INF actions._alpine._dag."0"._op | completed duration=3.7s
```

[refers to an image pull](https://github.com/dagger/dagger/blob/070491b/pkg/universe.dagger.io/docker/pull.cue#L23).

### Why is this important to you?

Improves the logging UX for users new to dagger.

### How are you currently working around this?

Diving into [pull.cue](https://github.com/dagger/dagger/blob/070491b/pkg/universe.dagger.io/docker/pull.cue#L23) to figure out what `_op` is 🙂

**Comment by TomChv** [comment]
Nice catch, I think it's a good idea to rename it.

Do you want to take care of it?
