### ISSUE TITLE
✨ Run from any directory

### ISSUE THREAD

**Issue by rawkode** [dagger/dagger#2539]
### What are you trying to do?

I have a monorepo and I'd like to be able to run `dagger do` from any of the subprojects within the monorepo.

Much like `git commit` traces up the directory tree to find `.git`, I'd like `dagger do` to do the same for `cue.mod`.

### Why is this important to you?

To save me having to run `cd ../../../ && dagger do` or `dagger do -p ../../../`

### How are you currently working around this?

As above

**Comment by shykes** [comment]
Just want to say, I run into the same issue in the dagger repo itself (using dagger to develop dagger) and it's really annoying.

**Comment by rawkode** [comment]
I’m currently exploring an alternative approach to, by having another CUE file in each “project” within the monorepo that defines its own #Plan and dependencies. 

I think this might work well, but also will be a lot of repetition as my main CUE entry point at the top level will need the same details. 

I don’t think I can reuse / merge the #Plans because CUE doesn’t really have a good way to work with associative lists. Unless you’ve got some ideas?

**Comment by jpadams** [comment]
Here's one hack with a file called `dagger.cue` with your plan in it. You could also look for `cue.mod`.

`~/dagger-find-up`
```bash
#!/bin/bash

while [[ $PWD != / ]] ; do
    if [[ ! -e "dagger.cue" ]]
    then
      cd ..
    else
      echo "From dagger.cue in directory $PWD:"
      dagger "$@"
      kill -INT $$
    fi
done
kill -INT $$
```

`alias dag='~/dagger-find-up'`

`dag do hello --log-format plain`

**Comment by morgante** [comment]
@jpadams Thanks for sharing the hack, this is somewhat similar to an alternative I had tried. Unfortunately, it requires cue.mod to be in a parent directory—for my use case, I want to essentially share a Dagger plan across many projects. So the directory structure would be something like this:

```
~/.tooling/dagger/dagger.cue
~/.tooling/dagger/cue.mod
~/code/app1
~/code/app2
```

I'd like to be able to run the actions from the .tooling directory on app1 and app2, but haven't found a way to make that work.

**Comment by rawkode** [comment]
Got this working with multiple plans

https://github.com/rawkode-academy/rawkode-academy/blob/main/build.cue

**Comment by TomChv** [comment]
I'm closing this issue, we have an option `-w` to execute dagger from another directory now
