### ISSUE TITLE
End to end Dagger Real-World Example 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#2552]
### What is the issue?

Many users have asked for a best practices example that shows how Dagger is used in "real life".

**Comment by jpadams** [comment]
Examples like this one (in progress) from @remakingEden should help a lot with this need :)
https://github.com/dagger/dagger/pull/2382

**Comment by crjm** [comment]
Should we close this as #2382 is merged?

**Comment by marcindulak** [comment]
I think the need for more complex examples, and generally for runnable examples, will come up again. Often SaaS vendors decide to only maintain non-runnable examples, arguing that having reliable testing of the cloud is hard and requires too much engineering effort. I imagine dagger.io would maintain the complex examples in separate ci-tested repositories. This would help to maintain the code quality. For example https://github.com/dagger/dagger/tree/d45b946f024c63bcb89d22bd843a011f18d64b69/docs/use-cases would be runnable.

**Comment by mircubed** [comment]
closing since we have many guides coming up that take care of this
