### ISSUE TITLE
How to run single actions within a cue plan 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#2554]
### What is the issue?

A user has a cue plan with multiple actions, but they want to understand how to run a single actions with the same cue plan. We should clarify how to do this today and provide a real-world example.

**Comment by helderco** [comment]
We need to know what's missing from the [Dagger Actions guide](https://docs.dagger.io/1221/action#discovery). You have the _Discovery_ and _Execution_ sections that should explain that. Did the user read it? Was it confusing, or something missing that would have helped? Should we add another action to that example to make it clearer that you can single out a single action amongst multiple ones?

The [Todo App](https://docs.dagger.io/1200/local-dev/) has a more complete real-world example, multiple actions included. I think there's more around but the core concept explanation should be the intro to that.

**Comment by jpadams** [comment]
I think we want to show:

```
dagger.#Plan & {
    actions: {
        build: {...}
        deploy: {
            local: {...}
            cloud: {...}
        }
    }
}
```

`dagger do build`
`dagger do deploy` does `deploy local` and `deploy cloud`
`dagger do deploy local` and `dagger do deploy cloud` single actions only
