### ISSUE TITLE
dagger-cue project init help - document command 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#2555]
We don't have clear docs on how to use `dagger-cue project init help`. A user wanted to create a new cue file, but didn't see how to do this with `dagger-cue project init`. @marcosnils explained that they could use `dagger-cue project init help` command to do this. 

We should make this more clear in the docs, so it is easier for our users to find.

**Comment by mircubed** [comment]
@marcosnils is this still needed or can I close it?

**Comment by marcosnils** [comment]
@mircubed let's assign this to the CLI milestone since it needs a broader review in the context of the UX we're planning to ship in the CLI.

**Comment by shykes** [comment]
This is really a `dagger-cue` issue, I edited to make that more clear. Specific to CUE SDK, unrelated to upcoming dagger CLI launch. Cleaner this way.

**Comment by TomChv** [comment]
We are no longer working on the cue SDK so I'm closing this issue.
