### ISSUE TITLE
✨ docker.#UpdateEnv or docker.#Path

### ISSUE THREAD

**Issue by NarendraPatwardhan** [dagger/dagger#2572]
### What are you trying to do?

I am trying to update the PATH variable based on its previous value inside docker.#Build. docker.#Set is insufficient for it. A mechanism to update env values or PATH specifically should be abstracted away as an action for ease in translation.

### Why is this important to you?

Various pieces of software demand the PATH variable be updated for global discovery.
ENV PATH=${PATH}:<NewFragment> is a common occurrence in most Dockerfiles, but it is extremely convoluted to do using Dagger in its current form.

**Comment by helderco** [comment]
This is how I do it:

```cue
docker.#Set & {
    input: image.output
    config: env: PATH: "/foobar:\(input.config.env.PATH)"
}
```
We don't resolve variables like `$VAR`, but you can interpolate the value in CUE.

If this doesn't work for you, can you please show how you're using it? I may require a small tweak based on your use case.

**Comment by helderco** [comment]
Here's a full example:

```cue
package main

import (
	"dagger.io/dagger"
	"universe.dagger.io/docker"
)

#TestSet: {
	_build: docker.#Build & {
		steps: [
			docker.#Pull & {
				source: "ubuntu"
			},
			docker.#Set & {
				input: _
				config: env: PATH: "/foobar:\(input.config.env.PATH)"
			},
			docker.#Run & {
				always: true
				command: {
					name: "sh"
					flags: "-c": "echo $PATH"
				}
			},
		]
	}
	result: _build.output.config.env.PATH
}

dagger.#Plan & {
	actions: test: #TestSet
}
```
```console
➜  dagger do test
[✔] actions.test
Field   Value                                                                                                                                                                                            
result  "/foobar:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

You can see the output of `docker.#Run` with `--log-format plain`:
```console
6:29PM INF actions.test._build._dag."2"._exec | #3 0.098 /foobar:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by NarendraPatwardhan** [comment]
Thanks! This solved my problem. I didn't have a input: _ field in #Set
