### ISSUE TITLE
show how to use `powershell` package on `arm` machines in test or docs

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2580]
Today, the `universe.dagger.io/powershell` package's tests employ

`mcr.microsoft.com/powershell` which is only for x86/amd

The Microsoft team has released an image tag for arm32 that works on arm32 and arm64 linux including MacOS: `mcr.microsoft.com/powershell:arm32v7-ubuntu-bionic`
https://github.com/PowerShell/PowerShell-Docker/issues/520#issuecomment-1121468388

**Comment by TomChv** [comment]
@jpadams Any update on this issue?

**Comment by jpadams** [comment]
The microsoft team is still working on the powershell and arm64 issues.

If you use the new Dagger language SDKs then this has effectively been solved:
https://github.com/dagger/dagger/blob/main/docs/current/sdk/go/snippets/multiplatform-support/non-linux-support/main.go
https://github.com/dagger/dagger/blob/ecf8a51897bfdfd0d8207e90e97ce0d769f3c710/core/integration/platform_test.go#L243-L249
