### ISSUE TITLE
Make actions more visible 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#2585]
### What is the issue?

Note from Discord:  it'd be really helpful to have the list of available actions surfaced a bit more prominently on the site! I had to dig down to https://docs.dagger.io/1202/plan/ before anything linked me to the universe repo

https://discordapp.com/channels/707636530424053791/708371226174685314/983530001355902978

**Comment by crjm** [comment]
Maybe we can find content to make an Actions CTA in the overview page of the docs redesign?
