### ISSUE TITLE
✨ resolve dependencies 

### ISSUE THREAD

**Issue by mlkmhd** [dagger/dagger#2589]
### What are you trying to do?

I created a `main.cue` and imported the `github.com/mlkmhd/dagger-maven` project in it, but it does not resolve my dependency when I run `dagger project update` command:

main.cue:

    package main

    import (
        "dagger.io/dagger"
        "dagger.io/dagger/core"
        "github.com/mlkmhd/dagger-maven"
    )
    
    dagger.#Plan & {
    ...

I run this command:
`$ dagger project update`

but it does not resolve imported dependency and my tree is like this:
`$ tree -L 3`

    .
    ├── cue.mod
    │   ├── module.cue
    │   ├── pkg
    │   │   ├── dagger.io
    │   │   └── universe.dagger.io
    │   └── usr
    └── main.cue

Am I doing something wrong?

**Comment by TomChv** [comment]
You must first install it using `dagger project update github.com/mlkmhd/dagger-maven`

[Look at this guide for more information](https://docs.dagger.io/1239/making-reusable-package#push-package-on-repository)

**Comment by helderco** [comment]
Closing since [CUE is no longer supported](https://dagger.io/blog/ending-cue-support).
