### ISSUE TITLE
Use wget instead of curl in Gitlab CI example

### ISSUE THREAD

**Issue by rolule** [dagger/dagger#2599]
### What is the issue?

Hello,
I looked at the Gitlab example [here](https://docs.dagger.io/1201/ci-environment) (which works btw) and wondered why curl is installed for fetching the dagger install.sh instead of just using wget, which is natively available in Linux systems. I am no expert in this matter, but this seems like unnecessary overhead for me. 

If using wget, this line could be removed:
`- apk add --no-cache curl`

and the curl line could be replaced with `wget -O - https://dl.dagger.io/dagger/install.sh | sh`

Looking forward for your feedback :)

**Comment by jpadams** [comment]
Thanks @rolule!  Simpler is better!
