### ISSUE TITLE
Guides for working with cloud registries with Actions to follow

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2608]
### What is the issue?

Users aren't sure how to use registries other than Docker Hub with `core.#Pull/#Push` and `docker.#Pull/#Push`. Docker Hub which might be rate-limiting/throttling them, or they might have an org requirement to use their registry. Common ones will be AWS ECR, Azure ACR, Google GCR, GitHub Container Registry.

Can start with using command on client to get creds.

```cue
package main

import (
    "dagger.io/dagger"
    "universe.dagger.io/docker"

)

dagger.#Plan & {
    _awsRegion: "us-east-1"

    client: {
        commands: {
            "ECR Login": {
                name: "aws"
                args: ["ecr", "get-login-password", "--region", _awsRegion]
                stdout: dagger.#Secret
            }
        }
    }
    actions: {
        pull: docker.#Pull & {
            source: "XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/lambda/terraform-lambda:test-ecr"
            auth: {
                username: "AWS"
                secret:   client.commands."ECR Login".stdout
            }
        }
        run: docker.#Run & {
            input: pull.output
            command: {
                name: "ls"
                args: ["-al", "/"]
            }
            always: true
        }
    }
}
```

**Comment by jpadams** [comment]
Good to also touch on the anonymous Docker Hub rate limit issues and workaround.

**Comment by grouville** [comment]
@jpadams, shall  I do for all these registries `AWS ECR, Azure ACR, Google GCR, GitHub Container Registry` ?

**Comment by jpadams** [comment]
> @jpadams, shall I do for all these registries `AWS ECR, Azure ACR, Google GCR, GitHub Container Registry` ?

Yes, and Docker Hub should already be there, right? Short examples should be good.
The actual code snippets might be better under as very small, complete working simple examples under https://github.com/dagger/examples linked from an overview in docs.

What do you think?

**Comment by grouville** [comment]
Shall I create a new subdirectory next to templates ? How do you see the implementation of these examples ?

**Comment by mircubed** [comment]
@grouville do you think we can close this one?
