### ISSUE TITLE
Guide for showing easiest way to develop a Universe package right in a fork of `dagger/dagger`

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2609]
### What is the issue?

Since it's complicated to get package management right and we'd love folks to share their creations with the whole Dagger community via Universe, it's easiest if they develop their packages right in a Universe context versus in a disconnected repo. 

To that end we'd recommend creating a fork of `dagger/dagger`, creating a branch for their new package, then putting it under `universe.dagger.io/x/<email>/<package>` and taking advantage of the `cue.mod` already governing the `universe.dagger.io` module namespace. Their testing/develop will go easier and their finished product will be easy to contribute.

Motivation:
The current guides we have give a lot of info, but can be difficult to follow in practice.

**Comment by mircubed** [comment]
@jpadams with upcoming changes, should we close this issue?

**Comment by jpadams** [comment]
closing unless demand brings it back.
