### ISSUE TITLE
🖐️ Pull from git with self-sigined certificate

### ISSUE THREAD

**Issue by ebcFlagman** [dagger/dagger#2623]
### What is the issue?

I tried to pull from a remote git repository which runs with a self signed certificate. Is there a option to add a trusted certificate?

### Log output

#1 0.058 Initialized empty Git repository in /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/3/fs/
#1 0.144 fatal: unable to access 'https://gitlab/group/project.git/': SSL certificate…
4:25PM FTL failed to execute plan: task failed: actions.source: failed to load cache key: failed to fetch remote https://gitlab/group/project.git: exit status 128

### Steps to reproduce

```
package main

import (
	"dagger.io/dagger"

	"dagger.io/dagger/core"
)

dagger.#Plan & {
  client: env: GITLAB_TOKEN: dagger.#Secret
  actions: {
    source: core.#GitPull & {
      remote: "https://gitlab/group/project.git"
      ref: "master"
      auth: {
	username: "gitlab"
	password: client.env.GITLAB_TOKEN
      }
    }
  }
}
```

### Dagger version

0.2.18

### OS version

Windows 10

**Comment by grouville** [comment]
Hi, did you try https://docs.dagger.io/1224/self-signed-certificates/ ?

**Comment by samalba** [comment]
Closing this, the cue sdk isn't supported anymore
