### ISSUE TITLE
Need guide on FS mounts

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2627]
### What is the issue?

Help users understand why some actions sometimes fail due to missing files or confusions about filesystem and mounts locations.
See comment form @marcosnils at 
https://github.com/dagger/dagger/issues/2197#issue-1204811074
> why some actions sometimes fail due to missing files or confusions about filesystem and mounts locations.

During many help sessions there is confusion about
- what "transient" or "ephemeral" filesystem mounts mean.
- confused between docker bind mounts and dagger/buildkit mounts.
- when to docker.#Copy vs mount.
- why mounted FS cannot be exported.
- confused about mounts vs core.#Source vs client key.
- how a mount can overshadow/clobber FS on a container

related to and could be combined with #2605

**Comment by helderco** [comment]
Is that the right comment? Can you give examples of confusion?

**Comment by jpadams** [comment]
Additional user feedback:
> I  was hoping someone could explain me the basics on writing to the client filesystem. I've been strugling to grasp how these work in combination with an export: directories: entry on the a docker.#Run. It keeps throwing "failed to execute plan: task failed: actions.build.run.container.export._directories."/vendor"._subdir._copy: failed to compute cache key: failed to calculate checksum of ref ke2pkl6om5pfaf6d01vwsfvzw::xw35kbmyth
g6pgqs1uk8ttbe3: "/vendor": not found" even though vendor in the _exec clearly exists.
