### ISSUE TITLE
Starter template Dagger plans

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2630]
starter template code, guide on how to use

#### Templates needed

- [ ] node.js
- [ ] docker image build & publish
- [ ] dotnet
- [ ] maven
- [ ] python-app
- [ ] c & cpp
- [ ] golang
- [ ] gradle
- [ ] laravel or other PHP (composer?)

**Comment by mircubed** [comment]
@jpadams I think we can close this one now since we made issues for each template now.

**Comment by pipinet** [comment]
- gradle multi-module
- test with testcontainers
- test with other services
