### ISSUE TITLE
Improve parsing for git URLs when adding third party CUE modules

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#2631]
### What are you trying to do?

The current design for fetching repos is very limiting. We're parsing a URL into repo and path, but current design assumes 2 parts for the repo and rest for the path.

For example, the URL `gitlab.com/dagger/dagger/stdlib/test/test` gets parsed into:
 - **Repository:** `github.com/dagger/dagger`
 - **Path:** `/stdlib/test/test`

I think it's more flexible to require a `.git` separator in the URL to get the path after it, otherwise making the full URL the repository.

Examples:

| URL | Repository | Path |
| -- | -- | -- |
| `gitlab.com/dagger/dagger/stdlib/test/test` | `gitlab.com/dagger/dagger/stdlib/test/test` | |
| `gitlab.com/dagger/dagger/stdlib/test/test.git` | `gitlab.com/dagger/dagger/stdlib/test/test` | |
| `gitlab.com/dagger/dagger/stdlib/test.git/test` | `gitlab.com/dagger/dagger/stdlib/test` | `/test` |

### Why is this important to you?

GitLab is well adopted and you can create arbitrary depth on the repo path because of sub-groups.

There's an issue already for general improvements on this but we need to expedite this specific fix because there's users blocked by the current design.

- #2511

### How are you currently working around this?

There's no workaround apart from managing this manually, skipping writing to `dagger.mod` and `dagger.sum`. It's possible to use a git submodule instead, inside `cue.mod/pkg`.

**Comment by TomChv** [comment]
I'm closing this issue since we are no longer working on CUE modules
