### ISSUE TITLE
Find home for packages in `universe/x` not yet moved

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2636]
https://github.com/dagger/dagger/pull/2579#issue-1260905491

**Comment by jpadams** [comment]
https://github.com/dagger/dagger/tree/main/pkg/universe.dagger.io/x/tom.chauveau.pro%40icloud.com/kubernetes

**Comment by TomChv** [comment]
I'm closing this issue since it's outdated, we no longer have a universe, it's now called daggerverse and available on https://daggerverse.dev
