### ISSUE TITLE
Create a guide for the community on how to create a template 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#2642]
We want to create some starter templates. We will make an issue for each of the templates that we are requesting. 

This issue specifically covers the need for a guide that the community can use to build the templates quickly. The output of this issue should be a guide that the community can follow to ensure that all of the starter templates have the same consistency. 

Once completed, we will attach this guide to each of the starter template issues as a reference. 

Some examples: 
https://github.com/actions/setup-node

**Comment by jpadams** [comment]
Principles:
- Use multi-arch images
- keep it simple but useful
- pithy comments with links

**Comment by jpadams** [comment]
Going to use a single repo for this which will have instructions on how to contribute.
