### ISSUE TITLE
Node.js Starter Template v1

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#2643]
We'd love to have a Node.js starter template. 

Recommended approach and best practices for creating a starter template - (coming soon with #2642 )

**Comment by jpadams** [comment]
Question:
`npm` or `yarn` or both? Probably both...

https://www.linkedin.com/pulse/yarn-3-vs-npm-8-dev-teams-2022-alex-alksne/?trk=articles_directory
https://www.section.io/engineering-education/npm-vs-yarn-which-one-to-choose/
https://ruanmartinelli.com/posts/npm-7-workspaces-1

Inspirations:
- https://circleci.com/docs/2.0/language-javascript#build-and-test-the-app
- https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
  - https://github.com/actions/starter-workflows/pull/191/files
- https://gitlab.com/gitlab-examples/nodejs/-/blob/master/.gitlab-ci.yml

**Comment by jpadams** [comment]
https://stackoverflow.com/questions/57534295/npm-err-tracker-idealtree-already-exists-while-creating-the-docker-image-for

**Comment by jpadams** [comment]
https://github.com/jpadams/nodetestnpm

https://github.com/jpadams/nodetestyarn

**Comment by jpadams** [comment]
motivation: what, why
steps
gif/video
conclusion
what next?

**Comment by jpadams** [comment]
https://github.com/dagger/examples
