### ISSUE TITLE
laravel or other PHP (composer?) Starter Template 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#2651]
We'd love to have a laravel (or other PHP) starter template.

Recommended approach and best practices for creating a starter template - (coming soon with https://github.com/dagger/dagger/issues/2642 )

**Comment by jpadams** [comment]
#2620 related

**Comment by crjm** [comment]
I think it would be great to have templates for Composer, Laravel and Symfony.

**Comment by mircubed** [comment]
Closing until we work on extensions again
