### ISSUE TITLE
Hard to put a secret into a file

### ISSUE THREAD

**Issue by karak1974** [dagger/dagger#2655]
### What are you trying to do?

I'm trying to put a secret into a file, but it's very hard because there's no function what makes it easier.

**Comment by jpadams** [comment]
@karak1974 Can you explain more of what you want to do?
- Where does the secret come from? How generated?
- Why do you want to store it in a file?
- Where would the file be? On client (e.g. laptop, ci server) or file in a container in Dagger?
- Is the file ephemeral (use and throw away) or will it be persisted (e.g. on your laptop, encrypted in a git repo)?
- Would you store the secret decrypted or encrypted somehow?
- Could you store the secret in a more ephemeral place like an environment variable?

Here are secrets docs: https://docs.dagger.io/1204/secrets/

**Comment by mircubed** [comment]
related to #4366

**Comment by mircubed** [comment]
This is related to 0.3 and with CUE. We will close this one since it is unrelated to the new version
