### ISSUE TITLE
improve error message for "dagger project update" 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#2671]
The documentation for the `dagger project update` will be improved in #2543. 

This issue is for tracking the improvement of the error message that you get when using tags in `dagger project update`.

**Comment by helderco** [comment]
Sorry for the mixup, I decided it's simpler to do a quick fix in the error message as well, I'll create a new issue about the underlying behavior which needs fixing.

**Comment by helderco** [comment]
New issue:
- https://github.com/dagger/dagger/issues/2672
