### ISSUE TITLE
🐞 `docker/cli.#Load` is unnecessarily slow

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#2695]
### What is the issue?

Several users have reported that loading an image into docker takes a very long time. While part of this is inherent (exporting a tarball and loading it into docker can take up a fair bit of memory+cpu), our implementation relies on a lot of extra copying:
1. It uses `core.#Export` to export the tarball to a tmp dir on the local filesystem
2. Then that gets reloaded back into buildkit with a local import
3. That local import gets copied (to deal with some cache invalidation issues involving local imports)
4. The tarball is mounted into a container w/ the docker CLI, where it gets read and transferred to the docker daemon

One initial idea for a more efficient approach would be to re-implement `cli.#Load` to use a core task that starts the docker cli load command as a subprocess and pipes the buildkit tarball export directly into it. Basically, [on these lines](https://github.com/sipsma/dagger/blob/ac469c02576cc6c6d732a1aea7eec1427cacca05/plan/task/export.go#L94-L94), set the `io.WriteCloser` to the stdin of the load subprocess.

**Comment by marcosnils** [comment]
:wave: question.

Does `buildx` currently follow the same approach? It exports the buildkit output and then it uses the engine `Load` API to import it?

Just wondering.

**Comment by sipsma** [comment]
> Does buildx currently follow the same approach? It exports the buildkit output and then it uses the engine Load API to import it?

This gets a bit more involved as it depends on which driver `buildx` is using:
1. If the default `docker` driver is in use, then all of this is avoided because you aren't using "vanilla" buildkit; it's actually a hybrid buildkit baked into dockerd where the storage backend is adapted to docker's graphdriver (rather than the containerd snapshotter backend used by regular buildkit). While that does avoid the issue here, there are a lot of tradeoffs to using that dockerd-buildkit implementation that make it less appealing.
2. If one of the other `buildx` drivers are in use, then you are using regular buildkit (same as what dagger does). In this case, exporting to docker is implemented how I suggest we improve things (pipe directly from the export to `docker load`). It does not do what we do today where the tarball ends up being copied 3 times before being loaded.

**Comment by marcosnils** [comment]
> 2\. f one of the other `buildx` drivers are in use, then you are using regular buildkit (same as what dagger does). In this case, exporting to docker is implemented how I suggest we improve things (pipe directly from the export to `docker load`). It does not do what we do today where the tarball ends up being copied 3 times before being loaded.

gotcha.. makes sense.. Seems like this process of exporting <> importing images into the engine to make `docker run` happy could potentially be annoying for big images. I'm wondering if there's anything Docker could to do to make `docker run` more friendly to OCI standard images so we don't have to load them into the engine each time.

**Comment by mircubed** [comment]
@sipsma when you return from vacation, can you review this priority with @samalba and see if there is a workaround that we can promote to our users in the meantime while we work on a better fix?

**Comment by aluzzardi** [comment]
> One initial idea for a more efficient approach would be to re-implement cli.#Load to use a core task that starts the docker cli load command as a subprocess and pipes the buildkit tarball export directly into it. Basically, [on these lines](https://github.com/sipsma/dagger/blob/ac469c02576cc6c6d732a1aea7eec1427cacca05/plan/task/export.go#L94-L94), set the io.WriteCloser to the stdin of the load subprocess.

That would work great. The only downside (and the reason it's this way in the first place) is `cli.#Load` is built upon the CLI package and supports whatever `cli.#Run` supports -- loading to a remote engine, ssh auth through `dagger.#Secret`, ..

Having a native `#Load` would imply running docker on the client machine, without container:

- `#Load` will need the machine running `dagger` to have the `docker` CLI
- Authentication sandboxing is bypassed (e.g. it will use whatever auth the client has, including the host ssh agent)
- It will not share the same interface of other `cli` actions (e.g. take a socket as input)

I see a few paths going forward:

1) Find fixes for all of the above, somehow
2) Embrace the fact `cli.#Load` is very different from other actions (in terms of API but also sandboxing behavior, etc)
3) Keep `cli.#Load` as is, provide a "fast" `core.#DockerLoad` (or similar) on the side, specialized for fast loading images on the local daemon

No matter the option, one remaining challenge to which I don't have an answer is sandboxing (e.g. "client API"). Having an operation directly affect the host goes against the client principle. Perhaps this could somehow be integrated into client? I don't know how /cc @helderco

**Comment by sipsma** [comment]
I'll also add that the real fix here should be on the BuildKit-side, all of these other ideas are just hacks to workaround missing features in BuildKit. They would be pretty large changes though; the ability to mount the result of an export directly in an ExecOp would be perfect, but even just the ability to call export from the Gateway API could help a lot.

**Comment by sipsma** [comment]
I don't think we are currently going to invest effort in optimizing this, so closing for now.
