### ISSUE TITLE
🐞 image history by core.#Copy always `fileop target`

### ISSUE THREAD

**Issue by morlay** [dagger/dagger#2711]
### What is the issue?

This is upstream issue, buildkit ignore `llb.customname` for fileop.

With the fix https://github.com/moby/buildkit/pull/2932
The customname show as expected.

<img width="471" alt="image" src="https://user-images.githubusercontent.com/1667873/175767533-d94d616e-2386-4c4d-8776-a53d65e0c4c1.png">

### Dagger version

-

### OS version

-

**Comment by helderco** [comment]
Closing since [CUE is no longer supported](https://dagger.io/blog/ending-cue-support).
