### ISSUE TITLE
Guide: Optimal settings for working on Dagger projects (version control, editors, etc)

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2714]
- Version Control:
  - tab size: 4
    - GitHub: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/managing-your-tab-size-rendering-preference
  - GitLab: ??
  
etc

**Comment by verdverm** [comment]
For editors, you will want to get the CUE plugin, which exist for most major IDEs (I'm using nvim). Dagger plans are written in CUE and there is a `cue fmt` tool, tl;dr tabs for spacing, width is up to you as it is for everyone.

https://docs.dagger.io/1226/coding-style

Version control, probably whatever you already use and/or are comfortable with.

Build systems the same, https://docs.dagger.io/1201/ci-environment

**Comment by mircubed** [comment]
@dolanor review to see if you'd like to take this
