### ISSUE TITLE
🐞 Cannot `go install dagger@latest`

### ISSUE THREAD

**Issue by verdverm** [dagger/dagger#2728]
### What is the issue?

```
$ go install github.com/dagger/dagger@latest
go: downloading github.com/dagger/dagger v0.2.21
go: github.com/dagger/dagger@latest (in github.com/dagger/dagger@v0.2.21):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

Go 1.18

### Dagger version

n/a

### OS version

Debian 10 on ChromeOS | amd64

**Comment by tuong-at-wes** [comment]
Since the `main.go` file is under `cmd/dagger`,  you'll need to do `go install github.com/dagger/dagger/cmd/dagger@latest` to install I believe. Or we'll have to copy `cmd/dagger/main.go` to the root folder.

**Comment by tuongaz** [comment]
You'll need to run `go install github.com/dagger/dagger/cmd/dagger@latest` instead because the `main.go` file is in the `cmd/dagger` folder. Or we have to copy the `main.go` file from `cmd/dagger` to the root of the repos.

**Comment by TomChv** [comment]
@tuongaz Thanks for your answer, I'm closing this issue since it's solved by your comment
