### ISSUE TITLE
npm package?

### ISSUE THREAD

**Issue by troncoso** [dagger/dagger#2730]
### What is the issue?

I've looked all over the place, but any searching regarding "dagger.io" and "npm" shows absolutely nothing. Is there really not an npm package? I see there's a yarn one in the "dagger universe".

**Comment by jpadams** [comment]
@troncoso thanks for this issue! We're creating some quickstart templates for node.js including for `npm` and `yarn`. The templates will have an example Dagger project that will show how to run `dagger do build` or similar to get your node project to build, test, etc. Inside, the Dagger plan would run `npm install`, `npm xxx`, etc.

Would it be valuable to have an example like that?

Would you like to see an npm package with certain features?

**Comment by troncoso** [comment]
@jpadams I figured it out for myself. I don't know if there was an easier way, but I just copied the yarn package and changed everything to be "npm". Also for the packages installed by in alpine I changed them from "yarn" to "nodejs-current" (for node 18) and "npm".

**Comment by jpadams** [comment]
@troncoso here's another simpler approach you could try as well:

```cue
package main

import (
	"dagger.io/dagger"
	"dagger.io/dagger/core"
	"universe.dagger.io/bash"
	"universe.dagger.io/docker"
)

dagger.#Plan & {
	actions: {
		build: {
			checkoutCode: core.#Source & {
				path: "."
			}
			pull: docker.#Pull & {
				source: "node:lts"
			}
			copy: docker.#Copy & {
				input:    pull.output
				contents: checkoutCode.output
			}
			install: bash.#Run & {
				input: copy.output
				script: contents: """
					npm install
					npm run build
					npm run test
					"""
			}
		}
	}
}
```

**Comment by jpadams** [comment]
@troncoso Hoping you can make a PR for this from what you have working above 🙏 for `npm`.

**Comment by slumbering** [comment]
@troncoso what about creating a new field in your npm package to be able to specify node version in your plan ? that would be awesome 🚀

**Comment by troncoso** [comment]
I created a PR for this: https://github.com/dagger/dagger/pull/2908. After learning a bit more about the yarn package, I found that if you really wanted a different version, you can actually just build your own image and pass it to the npm commands.
