### ISSUE TITLE
✨ Let core.#Source use a file list for includes/excludes

### ISSUE THREAD

**Issue by troncoso** [dagger/dagger#2732]
### What are you trying to do?

When I use `core.#Source` for a node project, I only want to include files that are actually tracked in git. Conveniently, we already have files that tell git what to ignore ie. `.gitignore`. It would be nice if we had 2 things:

1. Recursive exclude - Currently, excluding "node_modules" only excludes the top level folder, but not any in subfolders
2. The ability to reference a file with a list of files to exclude. In this case, `.gitignore`.

I apologize if this *is* possible in some way. The documentation for built-in actions is pretty much non-existent. This is the closest I could find: https://docs.dagger.io/1222/core-actions-reference. But that doesn't detail anything about what each actions' parameters are or how to use them

### Why is this important to you?

Combining those 2 things, I could easily ignore all "node_modules", "dist", ".git", etc. folders throughout a monorepo. This is a step towards the goal of the local pipeline running the same way it would in CI environment.

### How are you currently working around this?

I have to manually exclude every single file I don't want:

```cue
getSource: core.#Source & {
    path: "."
    exclude: [
        "node_modules",
        "client/node_modules",
        "shared/node_modules",
        "server/node_modules",
        "client/dist",
        "shared/dist",
        "server/dist",
        "cue.mod"
    ]
}
```

**Comment by troncoso** [comment]
I do have a question about this as it is being considered. Am I approaching this the wrong way? In the [yarn](https://github.com/dagger/dagger/blob/main/pkg/universe.dagger.io/yarn/test/test.cue) example, it pulls the source code from github:

```cue
todoreact: {
		pull: git.#Pull & {
			remote: "https://github.com/mdn/todo-react"
			ref:    "4c1ad2bc5d50f96265693be50997c306081b0964"
		}
```

and uses those files. That makes sense for a test, but it didn't make sense to me for production use. When running this in github actions, for example, the code has already been checked out. I guess you could just remove the `actions/checkout@v3` action.

So I guess my question is: When running dagger locally to test the pipeline, should we be running it with our local code, or always check out a fresh copy like in the yarn example?

**Comment by TomChv** [comment]
> So I guess my question is: When running dagger locally to test the pipeline, should we be running it with our local code, or always check out a fresh copy like in the yarn example?

You can do both, you could have a step that pull your repository and another step that use your current directory.

For instance

```cue
#CI: {
   
   source: dagger.#FS
   // Define your CI here so you can reuse it from multiple sources and avoid duplication
}

actions: {
  local: {
    source: // Retrieve data from filesystem with core.#Source

    #CI & {
       "source:" source.output
    }
  }

  remote: {
    pull: git.#Pull & {...}
   
    #CI & {
       source: pull.output
    }
  }
}
```

**Comment by TomChv** [comment]
> Recursive exclude - Currently, excluding "node_modules" only excludes the top level folder, but not any in subfolders

`**/node_modules` do not works?

> The ability to reference a file with a list of files to exclude. In this case, .gitignore.

That's a good idea, WDYT @helderco ?

**Comment by helderco** [comment]
> > Recursive exclude - Currently, excluding "node_modules" only excludes the top level folder, but not any in subfolders

> `**/node_modules` do not works?

Yes, this should be the solution.

> > The ability to reference a file with a list of files to exclude. In this case, .gitignore.

> That's a good idea, WDYT @helderco ?

I've suggested this when I started working on `client: filesystem`, to make it easier but the feedback I got from Solomon was _"Not a fan of .dockerignore, IMO it's much better to have it in the plan. Make the CUE config the source of truth for as much as possible."_

You can reuse the exclude/include either as lists in CUE, or the `core.#Source` itself if it's something that's common. Wrap it in an abstraction.

**Comment by troncoso** [comment]
> > > Recursive exclude - Currently, excluding "node_modules" only excludes the top level folder, but not any in subfolders

> > **/node_modules do not works?

> Yes, this should be the solution.

Thanks for this. That does ease the situation a tad.

> I've suggested this when I started working on client: filesystem, to make it easier but the feedback I got from Solomon was "Not a fan of .dockerignore, IMO it's much better to have it in the plan. Make the CUE config the source of truth for as much as possible."

Considering the prevalence of .*ignore usage ie. .gitignore, .npmignore, .eslintignore, .dockerignore, etc. I don't see why this would be a bad feature to add for the people who would like that convenience. It's fine if Solomon doesn't want to use them that way, but why force everyone to have duplicate file lists?

> Make the CUE config the source of truth for as much as possible."

Not only does this not make sense, but you quite literally cannot make the CUE config the source of truth for this situation. I can't have git ignore files based on what's in the CUE config. So it will be 2 of the exact same list that have to be maintained. What's worse is that in a monorepo (a very common repo setup these days) you'll have several .gitignore files in various levels of the file hierarchy. So now I have to make sure my CUE config matches all of those different files.

Of course I could write scripts to keep these in sync. But that seems a little ridiculous based on how common the pattern I'm requesting is.

**Comment by helderco** [comment]
@troncoso Yes, I agree with you. So what do you suggest?

```cue
getSource: core.#Source & {
    path: "."
    patterns: ".gitignore"
}
```
If also adding `include`/`exclude` I'd assume they would supersede the patterns file, correct?

**Comment by troncoso** [comment]
Hey @helderco, I agree that `include`/`exclude` should take priority, yes.

**Comment by TomChv** [comment]
Our `exclude` option in `WithMountedDirectory` and `Host.Directory` supports wildcard.
I'm closing this issue.
