### ISSUE TITLE
Explore and document how to write Universe package unit tests

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2733]
Since your test in test/image.cue has package codecov at the top, and you're in the codecov package directory tree, you don't need to import the universe.dagger.io/alpha/codecov package and don't need to use codecov.#Image just #Image. Like this:

```
package codecov

import (
	"dagger.io/dagger"
)

dagger.#Plan & {
	actions: test: #Image & {}
}
````

Comment from user:
> How does it handle ambiguous package names in different paths? My gut tells me staying explicit is generally better.

This makes sense because for example, several packages may have an `#Image` action/definition and these could conflict in a slightly more complex test.

**Comment by mircubed** [comment]
@jpadams should we close this issue?
