### ISSUE TITLE
Detailed docs for core Actions

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2734]
### What is the issue?

> I apologize if this is possible in some way. The documentation for built-in actions is pretty much non-existent. This is the closest I could find: https://docs.dagger.io/1222/core-actions-reference. But that doesn't detail anything about what each actions' parameters are or how to use them

related: #2732

**Comment by shykes** [comment]
With the switch to Dagger Engine 0.3 and a GraphQL API, the current set of core actions is destined to be replaced by the GraphQL API. The current CUE API is still supported, but it doesn't make sense to invest resources to expand its documentation given the above.
