### ISSUE TITLE
[Docs] DocSearch User Events

### ISSUE THREAD

**Issue by crjm** [dagger/dagger#2735]
Registering anonymous user events in the docs would be great as it would bring us a great source of information for the decision-making process when designing the docs.
Right now, we are using the [latest version of DocSearch](https://docsearch.algolia.com/docs/DocSearch-v3), so we would rely on [Algolia's User Events](https://www.algolia.com/doc/guides/sending-events/getting-started/).

**Comment by slumbering** [comment]
@crjm Algolia metrics are just traking searchs from docs. You are talking about tracking user paths right ?

**Comment by crjm** [comment]
Exactly.
I have to research a bit more, but Algolia [offers an endpoint](https://www.algolia.com/doc/rest-api/insights/) to send user events to with [Google Tag Manager](https://www.algolia.com/doc/guides/sending-events/implementing/connectors/google-tag-manager/).
I'm guessing this implies adding some sort of user consent mechanism to be GDPR compliant.

**Comment by crjm** [comment]
This is not necessary as it overlaps what Posthog does.
