### ISSUE TITLE
core.#CacheDir doesn't seem to work as a cache

### ISSUE THREAD

**Issue by rucciva** [dagger/dagger#2782]
### Dagger Cloud run URL

https://dagger.cloud/runs/ab98d285-7037-48db-8491-0f157049e291

### What happened? What did you expect to happen?

The core.#CacheDir seem to not store the modification done from the container. It can be reproduced by running `dagger  do test` multiple times and observe the "./export/ls" which should be appended from result of each execution but instead the content is replaced each time the dagger do is executed (Unless i'm mistaking the way core.#CacheDir works, since i'm pretty new to dagger.)

**Comment by TomChv** [comment]
Hi, thanks for your report! 

I think it's normal because you are setting the field `always: true` in your `docker.#Run`, that means you will drop the cache on each run.
You should remove this field and see if it's solves your issue or not ;)

**Comment by rucciva** [comment]
You were right. i was under the impression that the `always:true` does not affect  `core.#CacheDir`. But this lead to another question.
So what i'm trying to do is to run a source code scanning every time the dagger do is invoked. The scanner needs to download a database for the scan and i would like that database cached for subsequent run. So if `core.#CacheDir` was affected by `always:true`, how should i configure dagger to allow this scenario?

**Comment by yann-soubeyrand** [comment]
Hello,

We have a similar use case: running `pulumi preview` each time we do a `dagger do preview` without throwing away the build cache nor the plugins cache. I came up with a workaround for the moment (see the `_hack` action and the mount of its output in the `preview` action), I don’t know if there’s a better solution:
```
package ci

import (
	"dagger.io/dagger"
	"dagger.io/dagger/core"
	"universe.dagger.io/bash"
	"universe.dagger.io/docker"
)

dagger.#Plan & {
	client: {
		env: {
			AWS_ACCESS_KEY_ID:     dagger.#Secret
			AWS_SECRET_ACCESS_KEY: dagger.#Secret
		}
	}

	actions: {
		_sources: core.#Source & {
			path: "."
		}

		_cache: core.#CacheDir & {
			id: "cache"
		}

		_mounts: {
			sources: {
				type:     "fs"
				dest:     "/src"
				contents: _sources.output
			}

			cache: {
				type:     "cache"
				dest:     "/cache"
				contents: _cache
			}
		}

		build: docker.#Build & {
			steps: [
				docker.#Pull & {
					source: "docker.io/pulumi/pulumi:3.37.2"
				},

				docker.#Set & {
					config: {
						workdir: "/src"

						env: {
							GOMODCACHE:  "/cache/go/mod"
							GOCACHE:     "/cache/go/build"
							PULUMI_HOME: "/cache/pulumi"
						}
					}
				},

				bash.#Run & {
					script: {
						contents: """
							go build
							pulumi plugin install
							"""
					}

					mounts: _mounts
				},
			]
		}

		_hack: docker.#Run & {
			input: build.output

			entrypoint: [
				"true",
			]

			always: true
		}

		preview: docker.#Run & {
			input: build.output

			command: {
				name: "preview"

				args: [
					"--stack",
					"test",
				]
			}

			env: {
				AWS_ACCESS_KEY_ID:     client.env.AWS_ACCESS_KEY_ID
				AWS_SECRET_ACCESS_KEY: client.env.AWS_SECRET_ACCESS_KEY
			}

			mounts: _mounts & {
				always: {
					type:     "fs"
					dest:     "/hack"
					contents: _hack.output.rootfs
				}
			}
		}
	}
}
```

**Comment by husseinraoouf** [comment]
@yann-soubeyrand thank you for posting your solution it helped me alot

I think setting `always: true` shouldn't discard `core.#CacheDir` mounted

**Comment by TomChv** [comment]
Our cache is now stable and work with the latest API. 
Users can also subscribe to dagger cloud to get distributed cache in their CI.
I'm closing this issue
