### ISSUE TITLE
✨ create documentation endpoint at the import URL

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#2785]
### What are you trying to do?

When people see the CUE code, [some (myself and some other daggernaut as well)](https://discord.com/channels/707636530424053791/709803368318632038/995115047816806410) try to actually access that URL.
Except for now, there is no service running at that address.

### Why is this important to you?

It would be great if we could host some documentation server at that URL, so people could actually explore what there is in this package. It would improve self exploration of the packages documentation.

As a first step, we could just redirect to the github repo, in the correct directory (since anyway, we don't manage URL that are not part of `dagger.io` yet)

### How are you currently working around this?

When I didn't know Dagger at all, I didn't even know where to look. I didn't know the existence of the https://github.com/dagger/dagger/pkg directory, and that it was there that the system was looking. It is not intuitive.

Once you know, you go to github, and look in that directory, but that is bad UX.
Without even taking into account the actual code that is used for this plan that should be in your `cue.mod` directory.

LSP will improve this explorability, but this should also be taken into account, URL that points to nowhere are never useful.

**Comment by mircubed** [comment]
@dolanor should we create a smaller issue to just tackle re-directs for the links below as a quick fix and then tackle this larger fix after? 

![Screen Shot 2022-07-11 at 8 18 12 AM](https://user-images.githubusercontent.com/101831275/178611619-fa163782-103c-4ef6-ac05-94ccd6c1f91c.png)

**Comment by jpadams** [comment]
https://docs.netlify.com/routing/redirects/

**Comment by crjm** [comment]
@marcosnils has been updated for redirection through AWS

**Comment by crjm** [comment]
Followed internally [here](https://github.com/dagger/dagger.io/issues/661)
