### ISSUE TITLE
Doco when it's good/needed to use Raw Strings: `docker.#Dockerfile`, `bash.#Run`, Coding Style, etc

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2813]
### What is the issue?

We advise users to generally avoid raw strings here: https://docs.dagger.io/1226/coding-style/#avoid-raw-strings

but they are needed when doing shell style line continuation such as

```
dockerfile: contents: """
    FROM ubuntu:18.04 as PHP
    ENV DEBIAN_FRONTEND noninteractive

    RUN apt-get update && apt-get install -y \
    nano \
    ....
```
where the above throws an error
`ERROR system | failed to load plan: unknown escape sequence:`

the error is corrected by using `#""" ... """#`

Was encountered by user adapting our example here https://docs.dagger.io/1205/container-images/ by adding their own Dockerfile code.

They noticed the issue not as an error message from `dagger do` but from VS Code giving them a red mark on the right.

**Comment by helderco** [comment]
The rule says to _avoid unless you need it_. At the time I didn't have any good examples where it's needed, but left a comment:

https://github.com/dagger/dagger/blob/6a2368cf838d33cb1083ee01e29ac89b4846a0c3/docs/guidelines/1226-coding-style.md?plain=1#L229

If more examples are known, they should be added, but I don't think we need to be exhaustive. The user just needs to be aware that's not usually needed.... until it is.
