### ISSUE TITLE
Give ability to pick and choose what you need from Dagger project update ✨ 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#2836]
### What are you trying to do?

I want to do Dagger Project update without pulling all the code. Right now, Dagger project update requires you to do a full update instead of giving you the ability to pick precisely what you need. 

(feedback from Dagger user interview)

### Why is this important to you?

There is a lot of code that is needed, so it would be great if the user could choose what they actually need. 

### How are you currently working around this?

Just doing Dagger Project update and dealing with all the code that comes with it. No workaround in place since it isn't a crucial blocker.

**Comment by helderco** [comment]
I believe this is a duplicate from:
- https://github.com/dagger/dagger/issues/2496

Please reopen if not 🙂
