### ISSUE TITLE
✨ Project Update to Main Branch

### ISSUE THREAD

**Issue by rawkode** [dagger/dagger#2839]
### What are you trying to do?

Currently, we need to wait for the Dagger team to cut a release before we have `dagger project update` and get the latest actions from universe.

It would be nice if we could `dagger project update --main` to fetch the latest version from the main branch.

### Why is this important to you?

So I can consume new actions from GitHub Actions without awful hacks

### How are you currently working around this?

Currently not, but could add a step to GHA to pull the repo

**Comment by samalba** [comment]
Closing this given that `dagger project` has been deprecated with 0.3
