### ISSUE TITLE
docs: Followup simple CircleCI example with caching

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2842]
#2841 

https://testdriven.io/blog/faster-ci-builds-with-docker-cache/
https://pythonspeed.com/articles/circleci-docker/

**Comment by shykes** [comment]
@jpadams should we close this, or recycle as a SDK-agnostic issue to improve CircleCI integration docs?

**Comment by jpadams** [comment]
I'll close this. We have enough CircleCI integration for now in the docs for each SDK around CI integration.
