### ISSUE TITLE
docs: "It all starts with a plan" -> "A Dagger Plan orchestrates the Actions"

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2849]
idea to change Plan doc title to explain role of the Plan in relation to Actions versus making the Plan the "starting point" or "central focus".

"It all starts with a plan" -> "A Dagger Plan orchestrates the Actions"

**Comment by crjm** [comment]
I think this is great because the current title is a bit vague IMO.
I would try to convey the same idea with less words, something like "Orchestrate Actions with a Plan".
