### ISSUE TITLE
✨ use a lighter version of todoapp

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#2851]
### What are you trying to do?

cloning the `dagger/todoapp` repo is very long and heavy. The size of the history of this fork is not so interesting to us.
Should we do some shallow clone and start from here?
How much would we push patches to upstream for this specific case, anyway?

### Why is this important to you?

People on low bandwidth (bad network infrastructure in some areas, slow mobile connection, etc), having to wait multiple minutes for a clone of a todoapp is too much and can make people go away.
It's 35MB of history, for 844KB of effective data.

### How are you currently working around this?

I don't.
I guess we could download the zip from the repo

**Comment by shykes** [comment]
Makes sense to me. An extra benefit will be to finally be able to open issues on dagger/todoapp. Go for it @dolanor :)

**Comment by dolanor** [comment]
Here is the repo with only the main branch, down to 1.3MB once cloned.
https://github.com/dolanor/todoapp
I guess I should give rights to someone being able to move it into GH dagger org. Since it's a new history, I can't just create a PR to it, and without deleting the other branches, it would still take too much space.
Who's able and up for the task?

**Comment by dolanor** [comment]
Invited @aluzzardi and @shykes as collaborators.
I don't know who else has rights to create public repos on dagger org on GH.
Also, I don't know if that's enough, as I'm the owner, GH might not let overtake my repo and be able to transfer ownership.

**Comment by dolanor** [comment]
Fixed a few months back
