### ISSUE TITLE
explain how to use the packages, so users don't need to go to the source code

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#2855]
### What is the issue?

The user wrote a blog post on Dagger and where they ran into issues. In this case, they mentioned they needed to go to the source code to understand how to use the package. Maybe we can add more documentation around this to make it easier for the users? 

[Blog post (feedback in the "Introducing the points that I thought were not good with Dagger" section) ](https://dev-classmethod-jp.translate.goog/articles/dagger_cicd_get_started/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp)

Snippets from blog post: 
For example, [here](https://translate.google.com/website?sl=ja&tl=en&hl=en&client=webapp&u=https://github.com/dagger/dagger/tree/main/pkg/universe.dagger.io) is the official package defined.

Even if you look at the official documentation of each, there is almost no description on how to use it, so you need to read the source of each package.

You need to see this package for input / output and type information of each package.

For example, I was dockern't sure about the output of the package, so I read [the source](https://translate.google.com/website?sl=ja&tl=en&hl=en&client=webapp&u=https://github.com/dagger/dagger/blob/6a2368cf838d33cb1083ee01e29ac89b4846a0c3/pkg/universe.dagger.io/docker/run.cue%23L120) around here and figured out how to get the output I wanted.

**Comment by troncoso** [comment]
I would love to see more traction on this. Most of my time developing Dagger plans is spent mulling through the package source code and tests. It is a really poor developer experience. I really like the promise of this technology so I'm willing to put up with it. But there is no way I could suggest Dagger to my team or to other devs in this state.

**Comment by brittandeyoung** [comment]
I have been contributing to the Terraform related actions inside `universe.dagger.io`. Is there an established pattern for documenting these packages?

**Comment by jpadams** [comment]
Important to be able to expose embedded or wrapped fields as well whether in LSP or in docs.
https://discord.com/channels/707636530424053791/1009427748902686810/1009454201442664520
@grouville

**Comment by mircubed** [comment]
@jpadams can I close this one for now?
