### ISSUE TITLE
Explain how to handle dependent modules

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#2856]
### What is the issue?

The user wrote a blog post on Dagger and where they ran into issues. In this case, the user wasn't confident about how to handle dependent modules because we didn't have docs that were able to explain it. 

[Blog post (feedback in the "Introducing the points that I thought were not good with Dagger" section)](https://dev-classmethod-jp.translate.goog/articles/dagger_cicd_get_started/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp)

blurb from blog: 
In Dagger, dagger project initthe dependent modules are cue.modoutput to the directory by the command.

I was wondering node_modulesif these would .gitignorebe excluded from git management in Node.js and get the dependent modules on each host machine running Dagger.

However , in the example for Github Actions setting of Dagger official ( [Integrating with your CI environment | Dagger](https://translate.google.com/website?sl=ja&tl=en&hl=en&client=webapp&u=https://docs.dagger.io/1201/ci-environment) ), the packages obtained by executing in advance in the local environment are committed and placed in git management as follows. , Suggestes to run on each host machine to update dependent modules.yamldagger project initdagger project update

You need to run dagger project initlocally before and commit the cue.mod directory to the repository with its contents

cue.modContains hundreds of files, so I felt a little uncomfortable managing this area with Git for each project.

npmdenoI think I'm confused because I only knew the idea of ​​package

From now on, the mechanism around here may be improved.

**Comment by jpadams** [comment]
related to #2163
