### ISSUE TITLE
✨ AKS authentication

### ISSUE THREAD

**Issue by bluebrown** [dagger/dagger#2860]
### What are you trying to do?

It would be nice to have first class support to get a kubeconfig file for AKS and authenticate with something like service principal credentials.

### Why is this important to you?

We are deploying into AKS, and without authentication mechanism its not possible.

### How are you currently working around this?

I have custom scripts/images/actions that handle the auth part for me, so  that I can use the resulting kubeconfig in actions that connect to the kubernetes API of the AKS cluster.

**Comment by bluebrown** [comment]
I would like to add my authentication code to universe/alpha. But there are some open questions. 

I am not sure whether it's better to only add the script so that the images that can do the authentication and connect the AKS api are build during pipeline run, or if it should be a pre-build image. Currently, I am using pre-build images which I have pushed to one of our private registries.  

If pre-build images should be used, I think they should end up in the dagger namespace on dockerhub so that they can be audited.  This would come with extra overhead of mantaining those with the latest packages and so on.

On the other hand, letting the user build the image during the pipeline run is less overhead for the dagger maintainers, but it will make the pipeline slower, at least until the image is cached.

**Comment by jpadams** [comment]
Suggested structure for a PR. Agree we should stick to code/scripts/Dockerfile vs built images.

Thinking common Azure auth and AKS-specific auth (that will use some common Azure auth) in tree like this under `alpha`.

```
.
└── azure
    ├── aks
    │   └── auth
    └── auth
    ```

**Comment by bluebrown** [comment]
I created a basic implementation. There is still the open question how to bootstrap secrets such as the AD token or kubeconfig without caching the non-secret file which is eventually exported as secret.
