### ISSUE TITLE
How to force an action dependency?

### ISSUE THREAD

**Issue by troncoso** [dagger/dagger#2902]
### What is the issue?

I'm trying to wrap my head around inputs, outputs, and dependencies. From my understanding, one action is dependent on another if it uses the output of that action. But let's say I have this:

```cue
actions: {
    source: core.#Source & {
        path: "."
    }
    pull: docker.#Pull & {
        source: "node:current"
    }
    copy: docker.#Copy & {
        input: pull.output
        contents: source.output
    }
    install: bash.#Run & {
        input: copy.output
        script: contents: """
            npm ci
            """
    }
    build: bash.#Run & {
        input: copy.output
        script: contents: """
            npm run build
            """
    }
    deploy: bash.#Run & {
        input: copy.output
        script: contents: """
            npm run deploy
            """
    }
}
```

Obviously, I want to run `install` before `build` and `build` before `deploy`. But how do I make these actions dependent on the previous action if there isn't an output?

I tried something like this:

```cue
install: bash.#Run & {
    input: copy.output
    script: contents: """
        npm ci
        """
    output: copy.output // <--
}
build: bash.#Run & {
    input: install.output // <--
    script: contents: """
        npm run build
        """
}

but that causes errors.

**Comment by helderco** [comment]
Your approach is correct, `install` should have `input: copy.output` and `build` should have `input: install.output`.

If you're having errors it must be something else, so you need to look into the error message more closely. If you need help with that I suggest you fill a [support request issue](https://github.com/dagger/dagger/issues/new?assignees=&labels=help+wanted&template=help_wanted.yaml&title=🖐%EF%B8%8F+%3Ctitle%3E).

**Comment by jpadams** [comment]
Right, just do like @helderco mentions above.

What's not obvious is that since each `bash.#Run` contains a `docker.#Run`
https://github.com/dagger/dagger/blob/main/pkg/universe.dagger.io/bash/bash.cue#L73
 which itself has an `output` field with a `docker.#Image`,
 https://github.com/dagger/dagger/blob/main/pkg/universe.dagger.io/docker/run.cue#L173-L176
 you get that `output` field already in every `bash.#Run`.

**Comment by troncoso** [comment]
Thanks @jpadams! I was missing this part of the equation:

> What's not obvious is that since each bash.#Run contains a docker.#Run
https://github.com/dagger/dagger/blob/main/pkg/universe.dagger.io/bash/bash.cue#L73
which itself has an output field with a docker.#Image,
