### ISSUE TITLE
🐞 `client` API should have certain keys pre-filled and available to Dagger plan 

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2918]
### What is the issue?

It's often necessary to use information about the `client` (laptop, CI runner, etc) in order to decide which portions of a CUE tree should be included in a plan via `if` statement guards, etc. Today, there is no guarantee that essential fields like `client.platform` for `os` and `arch` or `client.env.XXX` will be available, but they should be.

That means that plans that handle multiple operating systems or which have portions conditional on environment variables are difficult or impossible to write naturally without resorting to hardcoding, or passing `--with` CUE blocks.

There is a classic feature of automation tools like Puppet, Chef, Ansible, Salt where system "facts"/inventory/state are collected before the automation run and are available to the run. That could be a pre step of the `dagger do` as well.

> Facter, Puppet’s inventory tool, gathers facts about an agent node such as its hostname, IP address, and operating system. The agent sends these facts to the primary server in the form of a special Puppet code file called a manifest. This is the information the primary server uses to compile a catalog — a JSON document describing the desired state of a specific agent node. 

![image](https://user-images.githubusercontent.com/3187222/183681570-66aa9ea4-7cfe-4d2d-9fb8-28dbd4f8dd46.png)

from https://puppet.com/docs/puppet/6/puppet_overview.html#platform_components

### Log output

```
failed to load plan: non-concrete value string in operand to !=:
```

### Steps to reproduce

For example, this doesn't work today because `client.platform.os` is not concrete.

```
non-concrete value string in operand to !=:
```

```cue
package main

import (
    "dagger.io/dagger"
    "universe.dagger.io/alpine"
    "universe.dagger.io/docker/cli"
)

dagger.#Plan & {
    _addr: "unix:///var/run/docker.sock" | "npipe:////./pipe/docker_engine"
    //_addr: "unix:///var/run/docker.sock" // | "npipe:////./pipe/docker_engine"

    if client.platform.os != "windows" {
        _addr: "unix:///var/run/docker.sock"
    }
    if client.platform.os == "windows" {
        _addr: "npipe:////./pipe/docker_engine"
    }
    client: network: (_addr): connect: dagger.#Socket

    actions: {
        _build: alpine.#Build
        load:   cli.#Load & {
            image: _build.output
            host:  client.network[_addr].connect
            tag:   "cdhunt/alpine"
        }
    }
}
```
even though this does work:
```
package main

import (
    "dagger.io/dagger"
    "universe.dagger.io/alpine"
    "universe.dagger.io/docker/cli"
)

dagger.#Plan & {
    //_addr: "unix:///var/run/docker.sock" | "npipe:////./pipe/docker_engine"
    _addr: "unix:///var/run/docker.sock" // | "npipe:////./pipe/docker_engine"

    //if client.platform.os != "windows" {
    // _addr: "unix:///var/run/docker.sock"
    //}
    //if client.platform.os == "windows" {
    // _addr: "npipe:////./pipe/docker_engine"
    //}
    client: network: (_addr): connect: dagger.#Socket

    actions: {
        _build: alpine.#Build
        load:   cli.#Load & {
            image: _build.output
            host:  client.network[_addr].connect
            tag:   "cdhunt/alpine"
        }
    }
}
```

### Dagger version

0.2.28

### OS version

macOS 12.5

**Comment by helderco** [comment]
Yes, this has been discussed somewhat, especially because of `env` in:

- https://github.com/dagger/dagger/pull/2385#issuecomment-1115491512

`env` and `platform` are actually cheap to collect. Are there others you think would be useful to add?

**Comment by cdhunt** [comment]
Could you populate `platform` with the platform spec docker CLI defailt address? That could just be a concrete string based on `os`.
