### ISSUE TITLE
🐞 Universe Tests Timeout

### ISSUE THREAD

**Issue by brittandeyoung** [dagger/dagger#2943]
### What is the issue?

I am noticing that occasionally the Github CI checks for Universe are reaching some sort of timeout limit that is causing these tests to fail. A re run will usually clear up the issue. It would be good to resolve these so that new users are not confused about failing tests.

Here is an example action run with the timeout failure:
https://github.com/dagger/dagger/actions/runs/2861943183

I have been attempting to find where this timeout is taken place. If I do I will update this issue with more details. 

### Log output

4:36PM INFO  actions.test.integration.universe._dag."10"._exec | #27 554.9 # 4:28PM DEBUG system | 
4:36PM INFO  actions.test.integration.universe._dag."10"._exec | #27 554.9 # 4:28PM DEBUG system | #14 exporting cache
4:36PM INFO  actions.test.integration.universe._dag."10"._exec | #27 554.9 # 4:28PM DEBUG system | #14 sha256:2700d4ef94dee473593c5c614b55b2dedcca7893909811a8f2b48291a1f581e4
4:36PM INFO  actions.test.integration.universe._dag."10"._exec | #27 554.9 # 4:28PM DEBUG system | #14 preparing build cache for export
4:36PM INFO  actions.test.integration.universe._dag."10"._exec | #27 554.9 # 4:29PM DEBUG system | #14 preparing build cache for export 40.6s done
4:36PM INFO  actions.test.integration.universe._dag."10"._exec | #27 554.9 # 4:34PM DEBUG system | #14 ERROR: maximum timeout reached
4:36PM INFO  actions.test.integration.universe._dag."10"._exec | #27 554.9 # 4:34PM DEBUG system | ------
4:36PM INFO  actions.test.integration.universe._dag."10"._exec | #27 554.9 # 4:34PM DEBUG system | > exporting cache:
4:36PM INFO  actions.test.integration.universe._dag."10"._exec | #27 554.9 # 4:34PM DEBUG system | ------
4:36PM INFO  actions.test.integration.universe._dag."10"._exec | #27 554.9 # 4:34PM FATAL system | failed to execute plan: maximum timeout reached

### Steps to reproduce

Open up a Pull request with changes under `pkg/universe.dagger.io/`

### Dagger version

CI builds a fresh verion

### OS version

ubuntu-latest

**Comment by marcosnils** [comment]
thx for reporting! we're aware, we are investigating.

**Comment by slumbering** [comment]
Close this one. Our current runners have been upgraded.
