### ISSUE TITLE
✨ feat: tooling to check broken links across dagger websites

### ISSUE THREAD

**Issue by grouville** [dagger/dagger#2946]
Internal broken links are not being sufficiently monitered by Docusaurus: every week, we find at least one broken link.

The current best way to check them is to manually follow this command: https://github.com/dagger/dagger/blame/main/docs/README.md#L39.

However, it is not enough:
1. some internal redirections are not being caught when building the docs (relative path inclusion). It is however the recommended behavior from our docs (and theirs): https://docs.dagger.io/1227/contributing/#use-relative-file-paths-for-links
  > Last example from yesterday https://github.com/dagger/dagger/pull/2940/files
2. Our tests don't cover the testing of broken links across our websites (especially our cloud one, for example)

_Example:_
I don't trust docusaurus anymore. So, prior each merge, I run `Integrity` on the netlify preview to do a first pass, but it shall be automated

cc @crjm

**Comment by crjm** [comment]
As we discussed yesterday, this is really important.
Just to check, we should test the following sources in CI:
* Website
* Docs
* Dagger Cloud
* Every README across all repositories

**Comment by munichbughunter** [comment]
What kind of solution do you use for testing? I have some ideas on that.

**Comment by crjm** [comment]
Hey @munichbughunter! Thanks for asking.
Right now, we are only relying on Docusaurus thrown errors for broken links inside the docs. We are aware this is not a good approach, se we are looking at options to add a test in CI where all links across all services (READMEs included) are checked when a doc is changed.
It would be great to hear some suggestions!

**Comment by crjm** [comment]
Yes, this seems to be stale + don't have the time to look into it now. 
We can reopen if a case related to this arises, but I think it hasn't been a problem for a while.
WDYT @grouville?
