### ISSUE TITLE
✨ Update `_#DefaultVersion` for `universe.bagger.io` to use `latest`

### ISSUE THREAD

**Issue by brittandeyoung** [dagger/dagger#2951]
### What are you trying to do?

I would like to get thoughts on making the default version for all `universe.dagger.io` packages to be `latest`. In the current behavior, a developer will be hard coded directly to the `_#DefaultVersion` specified in the package unless they pass in a different version.

If we were to do this, we would need to make sure that each package does have the ability to pass in a custom version as an input.

### Why is this important to you?

This may be a great way to keep the Actions up to date with the latest version. This is also the default behavior when pulling a docker image without specifying a tag. Otherwise developers will have to specify latest or a newer version of the specified default if they need functionality that is in a newer version than the default currently defined in the package. Having this as `latest` would prevent developers from needing to specify version if they are okay with using the latest version and okay with getting auto updates. Then hard coding to a specific version would be more of a conscience effort.

### How are you currently working around this?

Currently to use a version other than the default, developers need to pass in the `version` input (if the package currently supports it).

**Comment by brittandeyoung** [comment]
I am more than willing to work on this once I get something from the dagger team indicating that they either agree/disagree with this.

**Comment by TomChv** [comment]
I'm closing this issue, we are no longer working on the CUE sdk.
Please check our doc to start with the new version: https://docs.dagger.io/
