### ISSUE TITLE
Docs: confusing linear flow in "How it Works"

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2958]
## Problem

When I go to the new ["How it works" docs page](https://docs.dagger.io/f44rm/how-it-works), I expect that clicking "next" at the bottom of the page will take me linearly through each part of the "How it works". Instead it sends me to an entirely different section. I found that surprising and inconvenient

## Solution

Change the "next" link at the top of "How it works" section so that it allows a linear navigation through the section's contents.

**Comment by crjm** [comment]
This is an issue that should be solved case-by-case, as it depends on the metadata of each doc file.
The default behavior is to link to the next doc in the sidebar (in this case, the default value is the tutorial). I'll change it to [Actions](https://docs.dagger.io/1221/action), as [Dagger vs](https://docs.dagger.io/1220/vs) is going to be removed from this section in the near future.
