### ISSUE TITLE
✨Jetbrains Idea Plugin

### ISSUE THREAD

**Issue by pipinet** [dagger/dagger#2970]

**Comment by slumbering** [comment]
Regarding JetBrains plugins you can use :
- https://plugins.jetbrains.com/plugin/10209-lsp-support (LSP support)
- https://github.com/dagger/cuelsp (Language Server implementation for [CUE](https://cuelang.org/), with built-in support for [Dagger](https://dagger.io/).)

The next JetBrains generation will use natively LSP.
See https://www.jetbrains.com/fleet/
