### ISSUE TITLE
✨ Improve documentation UX by adding 2 docusaurus  plugins   

### ISSUE THREAD

**Issue by jossemarGT** [dagger/dagger#2981]
### What are you trying to do?

**Disclaimer**: Since these proposals require code changes I did not file them as a "documentation" issue.

#### Background

Weeks ago, I decided to learn more about dagger and began exploring its documentation. Everything was fine until I got a little bit of difficulty when I tried to read the diagram under the [Transfer of #FS via docker.#Copy](https://docs.dagger.io/1247/dagger-fs/#transfer-of-fs-via-dockercopy) section due to its size, which is wider than the page layout.

After reaching the dev team on Discord  (#dev > #docs diagram) and discussing this matter a bit, we found an opportunity to adopt "diagrams as code" as well.

#### Proposals

We could improve the documentation user/dev experience by including the following Docusaurus changes:

- Wrap [medium-zoom](https://github.com/francoischalifour/medium-zoom) as a local plugin, allowing the users to zoom on the diagrams when these are wider than the page layout.
- Support "diagrams as code" with `mermaid.js` by either wrapping [mdx-mermaid](https://github.com/sjwall/mdx-mermaid) or [holding until upstream natively support them](https://github.com/facebook/docusaurus/issues/1258). 

Worth noting that each of the proposals can be implemented independently. Also, from past experiences, I do not recommend using mermaid for anything else than the diagrams it supports out of the box; in other words, only the flow charts under "Use cases" may find such change beneficial.

### Why is this important to you?

- The "zoom" capability could improve the user experience when reading diagrams that are wider than the page layout.
- The mermaid support _may_ be of benefit on the documentation flow charts maintenance, however I don't hold strong opinions about it :wink: 

### How are you currently working around this?

For the diagrams wider than the page layout. I left click the image and select the "Open image in new tab" option on my web browser. 

For the "diagrams as code", I could ask for the sources in Discord but it requires time from the maintainers to lookup for them.

**Comment by jossemarGT** [comment]
Before I forget (again), I am willing to contribute on the implementation of those proposals but I wanted to check with the maintainers first if those ring any bell.

**Comment by slumbering** [comment]
Hey @jossemarGT 👋 ! Thanks for your message. You're totally right about the zoom capability. This is something that we need to seriously consider. I'm going to create an issue for that.
Regarding mermaid support, we are already working on it for our futur documentation ;). The current one should be updated soon I guess, @jpadams ?

**Comment by jossemarGT** [comment]
Thanks @slumbering, let me address your comments on the following manner:

> Regarding mermaid support, we are already working on it for our futur documentation ;)

Noted, I'll hold on to that front to not duplicate efforts.

> I would choose the following one : https://github.com/flexanalytics/plugin-image-zoom. It's specific to Docusaurus, so its implementation should be straight forward

I can see that a local wrapper would mean another "little thing" to maintain, so I'll stick to the plugin as you suggested. I can create a PR for it right away since I already tested the change locally, where we can discuss other implementation details.

**Sidenote**: I'd like to share why I started suggesting a local wrapper. On my local tests, I learned that the plugin only adds a couple of timeouts on its initialization, then delegates everything else to the [medium-zoom](https://github.com/francoischalifour/medium-zoom) library, which is outdated by two patch versions. Then I realized I could create a PR for that plugin to bump their dependencies separately.

**Comment by slumbering** [comment]
> Thanks @slumbering, let me address your comments on the following manner:
> 
> > Regarding mermaid support, we are already working on it for our futur documentation ;)
> 
> Noted, I'll hold on to that front to not duplicate efforts.
> 
> > I would choose the following one : https://github.com/flexanalytics/plugin-image-zoom. It's specific to Docusaurus, so its implementation should be straight forward
> 
> I can see that a local wrapper would mean another "little thing" to maintain, so I'll stick to the plugin as you suggested. I can create a PR for it right away since I already tested the change locally, where we can discuss other implementation details.
> 
> **Sidenote**: I'd like to share why I started suggesting a local wrapper. On my local tests, I learned that the plugin only adds a couple of timeouts on its initialization, then delegates everything else to the [medium-zoom](https://github.com/francoischalifour/medium-zoom) library.

Contributions are more than welcome :). Many thanks @jossemarGT

**Comment by jpadams** [comment]
@vikram-dagger should we close this or look into this? Might already be solved.

**Comment by vikram-dagger** [comment]
- Mermaid support is now available in Docusaurus by default and we are using it in various places. 
 - The zoom plugin is also included in the current docs site. 
 I'll go ahead and close this @jpadams .
