### ISSUE TITLE
🖐️ How to config yarn registry mirror site url globally?

### ISSUE THREAD

**Issue by lifubang** [dagger/dagger#2984]
### Dagger Cloud run URL

Can't visit Dagger Cloud

### What happened? What did you expect to happen?

When I try the nodejs yarn example, I got some errors because we should use the mirror site for yarn registry in our area.
But I don't know how to config it globally.
Besides yarn, the other package management tools also need to config the mirror site url, such as `pip`, `npm`, `maven`, `go` etc. Could you give some example files for there configuration? Thanks.

root@acmcoder:/opt/examples/templates/nodejs/yarn/universe# dagger do build
[✔] actions.build.test.container                                                                          5.0s
[+] actions.build.build.install.container                                                               252.8s
[✔] actions.build.build.install.container.script                                                          0.0s
[✔] actions.build.install.container.script                                                                0.0s
[+] actions.build.install.container                                                                     252.8s
#9 0.114 + yarn install
#9 0.114 + tee /logs
#9 0.573 yarn install v1.22.17
#9 0.615 info No lockfile found.
#9 0.626 [1/4] Resolving packages...
#9 130.8 info There appears to be trouble with your network connection. Retrying...
[✔] actions.build.build.container.script                                                                  0.0s
[+] actions.build.test.install.container                                                                252.8s
[✔] actions.build.test.container.script                                                                   0.0s
[✔] actions.build.build.container                                                                         4.7s
[✔] actions.build.test.install.container.script                                                           0.0s
[✔] actions.build.checkoutCode                                                                            0.1s

**Comment by dolanor** [comment]
@slumbering How do we setup some private yarn/npm registry?
@helderco How do we setup some private pip registry?

For Go, I would say you can just set the correct env variables GOPROXY and GOSUMDB, and also GOPRIVATE.
