### ISSUE TITLE
🐞 Tutorial project could not `do build` on m1 pro Mac

### ISSUE THREAD

**Issue by PowerfooI** [dagger/dagger#2989]
### What is the issue?

Following the [tutorial](https://docs.dagger.io/1200/local-dev), I clone the project and run `dagger project update` successfully. However I got `FATAL` error, when I run `dagger do build`.

dagger version: dagger 0.2.32 (624e5bb94) darwin/arm64
OS version: macOS 12.5.1
Docker Desktop version: 4.1.1 (Apple Chip)

On WSL Ubuntu 20.04, I could not reproduce the issue.

### Log output

$ dagger do build           
[✗] actions.build.container                                                                                                                                                                              4.1s
#6 0.065 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/aarch64/APKINDEX.tar.gz                                                                                                                      
#6 0.065 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/main: could not connect to server (check repositories file)                                                                           
#6 0.065 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/aarch64/APKINDEX.tar.gz                                                                                                                 
#6 0.065 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/community: could not connect to server (check repositories file)                                                                      
#6 0.065 ERROR: unable to select packages:                                                                                                                                                                   
#6 0.066   bash (no such package):                                                                                                                                                                           
#6 0.066     required by: world[bash]                                                                                                                                                                        
[✔] actions.build.install.container.script                                                                                                                                                               0.0s
[✔] actions.build.container.script                                                                                                                                                                       0.0s
[✗] actions.build.install.container                                                                                                                                                                      4.1s
[✔] actions.source                                                                                                                                                                                       2.0s
2:12PM FATAL failed to execute plan: task failed: actions.build.install.container._image._dag."1"._exec: process "apk -U --no-cache add bash" did not complete successfully: exit code: 1

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/26134111/187845106-22d4843b-be57-4816-bdbf-9138cec67307.png">

### Steps to reproduce

Follow the steps in tutorial
```bash
git clone https://github.com/dagger/todoapp
cd todoapp
dagger project update
dagger do build
```

### Dagger version

dagger 0.2.32 (624e5bb94) darwin/arm64

### OS version

macOS 12.5.1

**Comment by slumbering** [comment]
Hi @PowerfooI !

It works in my side with the exact same config as you.
Could you try to stop your dagger buildkit, remove your volume and try `dagger do build` again please ? Let me know if this fix your issue. Thanks

**Comment by slumbering** [comment]
I close this issue since it has been resolved.
