### ISSUE TITLE
docker.#Copy fail when exclude is used

### ISSUE THREAD

**Issue by guitcastro** [dagger/dagger#2990]
### What is the issue?

I have the following docker.#Copy: 

```
docker.#Copy & {
  contents: app
  dest:     "/app"
  exclude: [
    ".gradle/",
    ".idea/"
  ]
}
```

### Log output

`failed to execute plan: task failed: actions.build._build._dag."1"._copy: failed to copy file info: failed to chown /var/lib/buildkit/runc-overlayfs/cachemounts/buildkit3698781898/app/.gradle/7.4.2/checksums: lchown /var/lib/buildkit/runc-overlayfs/cachemounts/buildkit3698781898/app/.gradle/7.4.2/checksums: no such file or directory`

### Steps to reproduce

Create a plan with docker.#Copy and use exclude in a directory (Host).  

### Dagger version

dagger 0.2.32 (624e5bb94) darwin/arm64

### OS version

MAC OS 12.4

**Comment by TomChv** [comment]
I attest that there is an issue with Dagger, I created a simple ready to run repro case to demonstrate it.

#### Steps

- Download and unzip repro case
- `dagger project init && dagger project update` to load dependencies
- `dagger do build`: see the issue

[Click to download dagger-2990-repro.zip](https://github.com/dagger/dagger/files/9485597/dagger-2990-repro.zip)

I still meet this error when I'm trying to use Dagger from main. It's definitely broken.

**Comment by guitcastro** [comment]
FYI: When using absolute, it works.

**Comment by helderco** [comment]
Closing since [CUE is no longer supported](https://dagger.io/blog/ending-cue-support).
