### ISSUE TITLE
🐞 `--cache-to` to private registry authentication errors

### ISSUE THREAD

**Issue by fbdtemme** [dagger/dagger#3006]
### What is the issue?

I want to export the build cache to a private gitlab container registry.
Looking into the buildkit documentation they seem to use the default `~/.docker/config.json` files generated after running `docker login` to authenticate.

I tried creating a customized buildkit container that had the docker credential files mounted at `/root/.docker/config.json`

Using cache export using buildctl inside this container works fine.
```
buildctl build --frontend=dockerfile.v0 --local dockerfile=. --local context=. --opt source=test.dockerfile --export-cache type=registry,ref=registry.gitlab.com/<my-registry>
```

But not using dagger when pointing to that buildkit-container with `export BUILDKIT_HOST="docker-container://my-dagger-buildkitd"`

### Log output

```
5:55PM DEBUG system | 
5:55PM DEBUG system | #8 exporting cache
5:55PM DEBUG system | #8 sha256:2700d4ef94dee473593c5c614b55b2dedcca7893909811a8f2b48291a1f581e4
5:55PM DEBUG system | #8 preparing build cache for export
5:55PM DEBUG system | #8 preparing build cache for export 0.1s done
5:55PM DEBUG system | #8 writing layer sha256:31b3f1ad4ce1f369084d0f959813c51df0ca17d9877d5ee88c2db6ff88341430
5:55PM DEBUG system | #8 writing layer sha256:31b3f1ad4ce1f369084d0f959813c51df0ca17d9877d5ee88c2db6ff88341430 0.2s done
5:55PM DEBUG system | #8 ERROR: error writing layer blob: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
5:55PM DEBUG system | ------
5:55PM DEBUG system | > exporting cache:
5:55PM DEBUG system | ------
5:55PM FATAL system | failed to execute plan: error writing layer blob: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
```

### Steps to reproduce

Try to upload the build cache to a private registry. eg.

```
dagger --cache-to type=registry,ref=registry.gitlab.com/username/project/cache do testJob
```

### Dagger version

dagger 0.2.27 (954664e6d) linux/amd64

### OS version

Linux fedora 5.19.6-200.fc36.x86_64

**Comment by grouville** [comment]
Hi,
I created the PR #3002, to enable that for github private registries (using `DOCKERHUB_AUTH_USER` and `DOCKERHUB_AUTH_PASSWORD` env vars). I would use this branch, and change the ```if target == "docker.io" && username == "" && secret == "" {``` to match the target here `registry.gitlab.com`

**Comment by fbdtemme** [comment]
I managed to get it working :tada:

 I used the workaround that was suggested in the documentation of the PR you linked.
So basically a small dependency that uses docker.#Push with a scratch image to this private registry.
After that authentication to the registry when using `--export-to` works for all actions that have a dependency on this helper task.

Thanks for the help and the quick response.

**Comment by fbdtemme** [comment]
Turns out this workaround is not enough. `--export-to` works fine since it is executed at the end, but for `--export-from` it works unreliably because of a race. I followed your advice and recompiled from your branch with modifications and this works flawlessly.
