### ISSUE TITLE
🐞 Conflicting values are ignored

### ISSUE THREAD

**Issue by jozuenoon** [dagger/dagger#3008]
### What is the issue?

I was trying to modify packages installed inside universe `go.#Image` and override `go.#Container` image. By accident, I picked the local variable `_img` which conflicts with the internals of `go.#Container`. From what I tested in CUE Playground https://cuelang.org/play/?id=VTfqP3w-QJ3#cue@export@cue this should produce the error something like `conflicting values x and y`, which would probably be a bit more helpful. I assume that the presented playground problem is exactly the same issue, however, maybe someone with more experience can take a look :)

### Log output

```bash
$ dagger do test
[✗] actions.test                                                                                                                                                     
[✗] actions                                                                                                                                                                                      
8:56PM FATAL failed to execute plan: task failed: actions.test._img._dag."3"._exec: invalid FS at path "actions.test._img._dag.\"3\"._exec.input": FS is not set
```
### Steps to reproduce

Run the following plan `dagger do test`:
```cue
package main

import (
	"dagger.io/dagger"
	"dagger.io/dagger/core"
	"universe.dagger.io/go"
)

#Test: {
	packages: [...string] | *["./..."]

 	tags: *"" | string

	_img: go.#Image & {
		version: "1.19"
		packages: {
			"libxml2-dev": {}
			"libxslt-dev": {}
		}
	}

	go.#Container & {
		image: _img.output
		command: {
			name: "go"
			args: _
			flags: {
				test: true
			}
		}
	}
}

dagger.#Plan & {
	actions: {
		_source: core.#Source & {
				path: "."
			}
		test: {
			#Test & {
				source:  _source.output
			}
		}
	}
}
```

### Dagger version

dagger 0.2.34 (46adf1fbd) linux/amd64

### OS version

Linux 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by helderco** [comment]
Closing since [CUE is no longer supported](https://dagger.io/blog/ending-cue-support).
