### ISSUE TITLE
Too much whitespace around some mermaid diagrams in intro

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#3020]
Can CSS or a mermaid plugin config change make this better?

Look at the cloak introduction page. Notice the whitespace around the diagrams. Why so much? Almost seems to increase as more diagrams rendered down the page.

@slumbering @crjm

**Comment by slumbering** [comment]
@crjm did you get any chance to work on this one ?

**Comment by crjm** [comment]
@slumbering not really, researched a bit more but reached a dead end.

**Comment by crjm** [comment]
Is this solved? @jpadams 
I don't see too much white-space around the diagrams anymore.

**Comment by jpadams** [comment]
If it looks good to you 👍
