### ISSUE TITLE
Add CI checks that nodejs sdk `dist` build is up to date

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3021]
Due to the fact that this repo is private and we haven't published to npm yet, we actually have to commit the built `dist/` dir here: https://github.com/dagger/cloak/tree/main/sdk/nodejs/dagger/dist

Otherwise external repos like todoapp that have a dependency on us ([i.e. here](https://github.com/dagger/todoapp/blob/f23002614d5404ef06507ea307de3ff51146f57b/package.json#L17-L17)) won't be able to import any code.

The problem is that it's really easy to forget to re-run `yarn build` and update that `dist/` repo. If we forget to do that, js clients depending on us will be running with out-of-date code.

I suspect that if we publish an npm package in the future this won't be an issue anymore (but not sure at all). But in the meantime, it seems like it would be worth testing this in CI somehow. Simplest idea would be to have a step that runs `yarn build` and fails if anything changes in `dist`. Very open to other suggestions though cc @slumbering @crjm

**Comment by slumbering** [comment]
Cloak has been recently merged. We are now able to publish an NPM package. cc @sipsma @aluzzardi

**Comment by slumbering** [comment]
Close this one. `dist` dir is not commited anymore and we cut a release the SDK is automatically build and publish to npmjs.
