### ISSUE TITLE
Use cloak generate like npm init

### ISSUE THREAD

**Issue by munichbughunter** [dagger/dagger#3030]
npm init can be used to set up a new or existing npm package.

The init will ask you a bunch of questions, and then write a package.json for you. 
Cloak can work the same way. The generate command can ask you some questions and generates everything for you.

**Comment by jedevc** [comment]
This can now be done using dagger functions :tada: For more information, see our docs about the [dagger init](https://docs.dagger.io/reference/979596/cli/#dagger-init) command :tada:
