### ISSUE TITLE
Switch to viper over cobra in CLI

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3032]
That will get us env var support for specifying flags out of the box: https://github.com/dagger/cloak/blob/2894044664e76873c14b70e2197b35fb045548b6/engine/engine.go#L88

**Comment by ringods** [comment]
> Switch to viper **over** cobra

You mean: drop cobra? 

Both together make an ever more powerful pair:

> Viper has the ability to bind to flags. Specifically, Viper supports Pflags as used in the [Cobra](https://github.com/spf13/cobra) library. ([Source](https://github.com/spf13/viper#working-with-flags))

> Viper is designed to be a [companion](http://en.wikipedia.org/wiki/Viper_(G.I._Joe)) to [Cobra](https://github.com/spf13/cobra). ([Source](https://github.com/spf13/viper#why-is-it-called-viper))

**Comment by sipsma** [comment]
Ancient issue, not really relevant anymore in new modules implementation
