### ISSUE TITLE
Flush engine logs on SIGTERM 

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3033]
Right now when the engine shutsdown it's easy for some remaining logs to get dropped. Hence this silly sleep hack in the nodejs engine wrapper: https://github.com/dagger/cloak/blob/2894044664e76873c14b70e2197b35fb045548b6/sdk/nodejs/dagger/engine.ts#L66-L69

Should be able to flush them when SIGTERM is received before shutdown.

**Comment by dolanor** [comment]
@aluzzardi do you mean this shouldn't be a problem, or we need to dig more and make sure the context is passed accordingly?

**Comment by jpadams** [comment]
Related to "clean shutdown" or "graceful shutdown".

Today if the engine is stopped, for example with `docker stop`, a nonzero exit code is produced.

**Comment by sipsma** [comment]
I believe this specific issue has been addressed and is mostly outdated due to time
