### ISSUE TITLE
Rework `ts` SDK to be `nodejs` SDK, possibly yarn/npm agnostic

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3036]
Our `ts` sdk isn't actually specific to typescript AFAICT. I think its main assumptions are that you are using a node module and that you are using yarn.

It might make more sense for it to be a nodejs SDK, with configuration fields for whether yarn, npm, or whatever is used (or possibly autodetection based on lockfile if robust enough).

A slight variation would be to have separate `yarn` and `npm` sdks. They might share some common code, but that's fine if this ends up being a cleaner route.

**Comment by slumbering** [comment]
Close this one because the SDK has been renamed to nodejs.
