### ISSUE TITLE
Support for Services

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3037]
Services:
* Run asynchronously (can be started and stopped)
* Aren't cached in their execution
* Can expose sockets (and similar concepts like TTYs).

One classic use case is an e2e test that needs to run against a live database. Also may include use cases like hot-reloading web dev servers, interactive containers hooked up to a user's terminal, etc.

This is a pretty broad issue, should be broken down into subtasks.

**Comment by Gambler13** [comment]
Would love to see this feature in near future. In Gitlab you can easily use the `services` keyword to start a new container asynchronous on the same network. I tried a workaround with the `docker.#Run` action, but unfortunately the service container is running forever.

**Comment by shykes** [comment]
Related: #4080 which I believe is a requirement for this issue (no point in running services if you can't connect to them).

**Comment by shykes** [comment]
Perhaps the parts of #4080 that depend on services (c2c and h2c) should be spun out and moved here? That way, #4080 would be limited in scope to c2h networking, and could be closed potentially very soon.

WDYT @sipsma @vito ?

**Comment by sheldonhull** [comment]
I know one part of using dagger for me is the ability to spin up services that keep running and allow more integration type tests to run. While I would try to use a dockertest package or such in Go, there's some stuff that just makes sense to be stateful to test and iterate on, such as `ng serve` for Angular, or maybe even `hugo serve` type commands where I want to run and leave it running with refresh.

I'm following this issue and if there's a better one for services let me know. Excited to see where this goes :-)

**Comment by mircubed** [comment]
Closing this since #4505 was merged. Please create a new task for any additional work that needs to be done.
