### ISSUE TITLE
Support chaining from Go client SDK

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3038]
The autogenerated clients in go are just barely okay, but suffer from a number of problems:
1. Chaining can't be used from them, you can only generate them from pre-declared operations
2. The fields on the outputs are extremely hard to navigate. Even if the query only selects one field, you have to navigate a whole tree of objects leading to that field.

@aluzzardi started experimenting briefly a while back w/ a client that operated sort of like a "query builder", which let you chain and also made obtaining output fields more natural. It's worth seeing if we could integrate this with codegen to solve all these problems at once and significantly improve the Go DX.

This will almost certainly require us creating our own codegen tools; it's highly unlikely genqlient could be convinced to do this. One possibility is [the language-agnostic graphql-codegen tool here with pluggable support for language backends](https://www.the-guild.dev/graphql/codegen/#live-demo). But this requires more investigation.

Additionally, we will likely hit the same problem in other languages (though it is most urgent in Go), so it would be great if the solution here could end up being re-usable in other language SDKs.

**Comment by helderco** [comment]
> Additionally, we will likely hit the same problem in other languages (though it is most urgent in Go), so it would be great if the solution here could end up being re-usable in other language SDKs.

Yep, thinking about the same in Python and TS.

**Comment by helderco** [comment]
This is already implemented.

Typescript and Python are also following the same convention:
- https://github.com/dagger/dagger/pull/3459
- https://github.com/dagger/dagger/pull/3460

But there's feedback on when to execute the query:
- https://github.com/dagger/dagger/issues/3555
