### ISSUE TITLE
Allow specifying path to directory holding `dagger.json`

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3040]
Right now you have to point to the actual `cloak.yaml` file when using the `-p` flag or adding a dependency in a yaml file, which is kind of annoying and creates more opportunities for typos like `.yml` vs `.yaml`.

You should instead be able to point to a directory, in which case it's assumed you mean the file `cloak.yaml` in that directory. You should still be able to provide a full path to the actual file too (in case you want to use a name besides `cloak.yaml`).

**Comment by dolanor** [comment]
It seems `cloak.yaml` will disappear.
I'll close this.

Reopen if I'm wrong @sipsma , @aluzzardi

**Comment by sipsma** [comment]
Addressed in modules implementation
