### ISSUE TITLE
Core API: support redirecting exec output streams

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3042]
It should be possible to redirect stdout and/or stderr to a file during `exec`.

```graphql
type ExecInput {
  redirectStdout: String
  redirectStderr: String
}
```

**Comment by vito** [comment]
This is implemented:

https://github.com/dagger/dagger/blob/fdbf190307776b4cfb8acaa39cc82956d104e310/core/integration/container_test.go#L310
