### ISSUE TITLE
Core API: support passing stdin to exec

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3043]
It's possible to retrieve stdout and stderr from an exec, but not to inject stdin. This would be very useful.

```graphql
type Exec {
  # This exists:
  stdout: String
  stderr: String
}

type ExecInput {
  # This doesn't exist, but it should :)
  stdin: String
}
```

**Comment by vito** [comment]
Implemented:

https://github.com/dagger/dagger/blob/fdbf190307776b4cfb8acaa39cc82956d104e310/core/integration/container_test.go#L279
