### ISSUE TITLE
`core` `git` should have `keepGitDir` option and perhaps `depth`. Should it be `true` by default?

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#3050]
I've found it confusing that when I see demos of doing a git pull of the `dagger/dagger` repo and a `dockerbuild` that the `docker version` command run afterwards doesn't show a short git hash in the version number like it does when I `git clone` and build `dagger` locally on my machine.

For example:

```
dagger devel (708210f74) darwin/arm64
```

```
dagger devel (708210f74) linux/arm64
```

```graphql
{
    core {
        git(remote: "https://github.com/dagger/dagger") {
            dockerbuild(dockerfile: "Dockerfile") {
                exec(input:{args:["dagger", "version"]}) {
                    stdout
                }
            }
        }
    }
}

{
  "data": {
    "core": {
      "git": {
        "dockerbuild": {
          "exec": {
            "stdout": "dagger devel () linux/arm64\n"
          }
        }
      }
    }
  }
}
```
I expected a `git clone` type functionality. Not sure if other folks are expecting something else. If the size of the `.git` directory is a concern, we could use something like `git clone --depth=1`.

It seems that perhaps the default BuildKit behavior is to not preserve the `.git` directory (not sure), but I see that this is an option in BuildKit LLB land (depending on things like dockerfile frontends and such I think), and so we should have that option in `cloak` to keep the `.git` directory and likely limit the clone depth and other bells and whistles.

https://github.com/dagger/dagger/blob/main/plan/task/gitpull.go#L40-L43
https://github.com/dagger/dagger/blob/main/version/version.go#L16-L30
https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#example-keep-git-dir

**Comment by sipsma** [comment]
We have support for including the git dir now. We don't have an option for git depth though

**Comment by vito** [comment]
I'm leaning towards keeping the `.git` dir by default at this point. It seems like we've needed it more than half the time we've used the Git API.

**Comment by helderco** [comment]
Closing since this is done. If reopening because of making `keepGitDir` default to `true`, please update issue or create new one.
