### ISSUE TITLE
Migrate existing Dagger plans with Cloak for kralicky

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3051]
In the last community call, @kralicky mentioned the need for a solution for his existing makefiles. 

" The first thing that comes to mind is an improvement on existing makefile, so some way to place legacy makefiles with more powerful Cloak. Most projects will have some sort of makefile with homebrew with make targets and shell scripts, so there is no official go equivalent for the makefile. " - @kralicky 

We can use this issue to track the overall migration for @kralicky's specific Dagger plans.

**Comment by mircubed** [comment]
@kralicky, @jlongtine is working on something that might be helpful for your migration, so it would be best to connect with him. @jpadams and @kpenfound can help as well!

**Comment by kralicky** [comment]
Sounds good. I had begun looking at how I could transition to cloak but I feel like i could use some help 😁

**Comment by mircubed** [comment]
@kralicky, I will close this issue for now, but feel free to reach out to @kpenfound @jpadams or any of us on Discord if you need anything!

**Comment by kralicky** [comment]
Thanks, I'll reach out to you soon.
