### ISSUE TITLE
Bash SDK

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3065]
We should have an SDK that supports at least authoring workflows (and possibly extensions too) w/ bash scripts.

It would be great if it turned out that this just meant using the same `cloak` CLI that you use already (possibly with some tweaks), but that's not a hard requirement necessarily.

**Comment by marcosnils** [comment]
we briefly spoke about it with @aluzzardi and @sipsma during the offsite. An idea that I'm particularly excited about exploring is:

```shell
#!/bin/cloak shell    # this will start the engine in shell mode and inject the Schema to shell functions.

declare -A img_params=(
 [ref]="alpine"
)

img = core.Image img_params

build = core.Exec $img.id
```

I'm also aware that it'd probably take some time to get there as we need to figure out code generation particularly in the context of chaining which might not be trivial. I think in the meantime we could be shipping a quick without having to take a final decision regarding code generation.

This example (https://discord.com/channels/707636530424053791/1003718839739105300/1023672021277741136) could translate as something like: 

```shell
#!/bin/cloak shell #Initializes cloak and injects some generic helper functions

# query is a helper function injected by the `cloak shell` output

CONTENT= query --args '.core.git.yarn.id' <<EOF      ## Notice the response json selector already embedded in the bash SDK (could be part of cloak's binary)
query Build {
  core {
    git(remote: "https://github.com/dagger/todoapp", ref: "cloak") {
      yarn(runArgs: "build") {
        id
      }
    }
  }
}
EOF
)

URL= query--secret "token=$TOKEN" --args '.netlify.deploy.deployURL' <<EOF
query Deploy($token: SecretID!) {
  netlify {
    deploy(
      contents: $CONTENTS,
      token: $token,
      siteName: "jeremy-foo",
      subdir: "build",
    ) {
      deployURL
    }
  }
}
EOF
)
echo $URL
```

cc @shykes @aluzzardi @jpadams @sipsma

**Comment by sipsma** [comment]
Yeah I totally agree with everything here. This also solves the problem of how to use multiple commands from shell that all exist within the same session (right now each CLI call is a different session, as opposed to `engine.Start` where everything happens in the same one).

I have some vague sense that also supporting `#!/usr/bin/cloak python` and similar for other languages could be interesting, but no concrete ideas on actual use case yet, just feels potentially useful :-)

**Comment by shykes** [comment]
There are some interesting ideas here, but given our constraints of time and engineering cycles, we need to start with something less ambitious.

The most urgent problem to solve is how to use dagger inside a shell script - ideally for *any kind of shell* since not everyone uses Bash, and not everyone will be able to adopt our choice of wrapper shell either.

I propose we start with simply making the `dagger` CLI [easy to script in the traditional sense](#3213).
