### ISSUE TITLE
Use image config to configure action ExecOps

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3066]
Right now any env vars (like `PATH`) or other configuration provided as part of an image config w/ the `FS` for a package don't get set when invoking the action, resulting in hacks like this: https://github.com/dagger/cloak/blob/e60aede62917e4e2711cca499d019c857f0b14ed/examples/netlify/ts/index.ts#L17-L17

**Comment by vito** [comment]
fixed by #3137
