### ISSUE TITLE
Try moving to federation model

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3117]
https://github.com/wundergraph/graphql-go-tools is a Go implementation of an apollo federation router. Federation is an existing framework that enables multiple graphql servers to be stitched together behind one unified gateway, which takes care of routing each resolver request to the correct backend "subgraph".

This is one potential route to solving the problem of how to resolve chainable `core` types like `Filesystem` when returned by non-`core` user packages. Early prototype here: https://github.com/dagger/cloak/tree/core-gqlgen

**Comment by helderco** [comment]
@sipsma Can you help give context on the reason why we gave up on Federation? Code-first schemas leveraging a library would become so much easier to implement, so it's a trade off. Was it because of caching concerns?

**Comment by helderco** [comment]
I can see context in https://github.com/dagger/dagger/issues/3116#issuecomment-1249772673:

> We actually ended up deciding to pursue option 3 above today after discussion. Will close this for now

Which states:

> 3. Switch from implementing actions as their own graphql servers (subgraphs) to a model where they accept input for a single resolver and call that resolver directly.
>    * This fixes all the caching problems in every case except for the default args one (`#3` above), both when resolver across different packages and within a single package.
>    * Major downside is that we use less "off-the-shelf" components in this model. This model is fairly simple, but will require more custom code in each language's SDK because it is specialized to our use case.

This is precisely the reason for my question:

> Major downside is that we use less "off-the-shelf" components in this model. [...] **will require more custom code** in each language's SDK [...].

Understand the reasons 👍

**Comment by sipsma** [comment]
@helderco Sorry you had to find the context on your own, I'm just catching up on this ping now. But yeah, the fact that we couldn't get caching to work the way we needed was the biggest reason. I think the caching issue may have just been a symptom of the larger problem that federation is pretty opinionated, which is a risk for us since our use case is so different than most other graphql use cases.
