### ISSUE TITLE
Port CUE SDK to Dagger Engine 0.3

### ISSUE THREAD

**Issue by jlongtine** [dagger/dagger#3121]
This issue is a collaboration point and place to discuss the porting of `dagger` 0.2 CUE-based plans to run in `cloak`/`dagger` v0.3.

This issue currently is _only_ tracking the work to allow `dagger@0.2` `dagger.#Plan`s to be run using cloak. A future `cloak` CUE SDK has been discussed, but not specced out yet. As such, the running of other `cloak` extensions within CUE is not tracked by this issue.

It will contain a list of various pieces that need to be ported to `cloak`, including a list of what has/hasn't been implemented in `cloak` and any current compatibility issues.

It currently includes some analysis of differences between Europa and the original `core` API. This will be updated to reflect the latest API design: <https://github.com/dagger/dagger/tree/cloak/core/schema>

### Some open questions

1. Are we aiming for 100% compatibility with 0.2 `dagger.#Plan` by launch?

### Other concerns/things to think about

1. Logging system changes
2. Module system
3. Secrets management is not in a good spot currently (creating new Secrets securely isn't currently possible in v0.3+).

## Major blockers

- https://github.com/dagger/dagger/issues/3173

### `dagger.io/dagger/plan.cue`

`#Plan`

| Europa  | Dagger v0.3 status | `dagger-cue` status | Notes |
| ------------- | ------------- | ------------- | ------------- |
| [`client.filesystem.read`](https://github.com/dagger/dagger/issues/3214) | ✅✅✅✅ | ✅✅✅✅  |  |
| [`client.filesystem.write`](https://github.com/dagger/dagger/issues/3214) | ✅✅✅✅ | ✅✅✅✅  |  |
| [`client.network`](https://github.com/dagger/dagger/issues/3465) | ✅✅✅❌ | ❌❌❌❌ | This should be unblocked by recent releases. Unsure about `npipe` support. |
| [`client.env`](https://github.com/dagger/dagger/issues/3215) | ✅✅✅✅ | ✅✅✅✅  |  |
| [`client.commands`](https://github.com/dagger/dagger/issues/3481) | ✅✅✅✅ | ✅✅✅✅  | Missing secrets creation API |

### `dagger.io/dagger/types.cue`

`dagger.#FS`
`dagger.#Secret`
`dagger.#Socket`

## `dagger.io/dagger/core` to port to `cloak`

| Europa  | Dagger v0.3 status | `dagger-cue` status | Notes |
| ------------- | ------------- | ------------- | ------------- |
| [`#Exec`](https://github.com/dagger/dagger/issues/3208) | ✅✅✅🚧 | ✅✅🚧🚧  | Currently missing `socket` mounts, `always: true`, and `hosts` config |
| [`#Source`](https://github.com/dagger/dagger/issues/3229) | ✅✅✅✅ | ✅✅✅✅ | |
| [`#Mkdir`](https://github.com/dagger/dagger/issues/3230) | ✅✅🚧❓ |  ✅✅🚧🚧 | Missing `permissions` and `parents: false` |
| [`#ReadFile`](https://github.com/dagger/dagger/issues/3231) | ✅✅✅✅  | ✅✅✅✅ | |
| [`#WriteFile`](https://github.com/dagger/dagger/issues/3209) | ✅✅✅🚧  |  ✅✅✅🚧 | Missing `permissions` |
| [`#Copy`](https://github.com/dagger/dagger/issues/3232) | ✅✅✅✅ | ✅✅✅✅ | Doesn't have `include` + `exclude` filtering |
| [`#Rm`](https://github.com/dagger/dagger/issues/3233) | ✅✅🚧🚧 | ✅✅❌❌ | Still missing some functionality around wildcards |
| [`#Merge`](https://github.com/dagger/dagger/issues/3234) | ❌❌❌❌ | ❌❌❌❌ |
| [`#Diff`](https://github.com/dagger/dagger/issues/3235) | ✅✅✅✅ | ✅✅✅✅ |
| [`#Subdir`](https://github.com/dagger/dagger/issues/3236) | ✅✅✅✅ | ❓❓❓❓ | This just uses `#Copy` under the covers, so probably don't need a v0.3 equivalent |
| [`#GitPull`](https://github.com/dagger/dagger/issues/3237) | ✅✅🚧🚧 | ✅✅🚧🚧 | Missing `keepGitDir`, and `auth`|
| [`#HTTPFetch`](https://github.com/dagger/dagger/issues/3238) | ✅🚧🚧🚧 | ✅🚧🚧🚧 | Missing `checksum`, `permissions`, `uid`, and `gid` |
| [`#Push`](https://github.com/dagger/dagger/issues/3239) | ✅🚧🚧🚧  | ✅🚧🚧🚧 | Missing `ImageConfig`, `auth`, and `digest` |
| [`#Pull`](https://github.com/dagger/dagger/issues/3240) | ✅🚧🚧🚧  | ✅🚧🚧🚧 | Missing `auth`, and `digest`, partial implementation of `ImageConfig` |
| [`#Dockerfile`](https://github.com/dagger/dagger/issues/3210) | ✅🚧❌❌ | ✅❌❌❌ | Partial implementation |
| [`#Export`](https://github.com/dagger/dagger/issues/3241) | ✅✅❌❌ | ✅🚧❌❌ | Probably need to implement this myself... |
| [`#DecodeSecret`](https://github.com/dagger/dagger/issues/3242) | ✅✅✅✅ | ✅✅✅✅ | Needs the ability to create new secrets |
| [`#NewSecret`](https://github.com/dagger/dagger/issues/3243) | ✅✅✅✅ | ✅✅✅✅ | Needs the ability to create new secrets |
| [`#TrimSecret`](https://github.com/dagger/dagger/issues/3244) | ✅✅✅✅ | ✅✅✅✅ | Needs the ability to create new secrets |
| [`#Start`](https://github.com/dagger/dagger/issues/3245) | ❌❌❌❌ | ❌❌❌❌ | Services aren't in dagger v0.3 yet |
| [`#Stop`](https://github.com/dagger/dagger/issues/3246) | ❌❌❌❌ | ❌❌❌❌ |  Services aren't in dagger v0.3 yet |
| [`#SendSignal`](https://github.com/dagger/dagger/issues/3247) | ❌❌❌❌ | ❌❌❌❌ |  Services aren't in dagger v0.3 yet |

**Comment by mircubed** [comment]
@vikram-dagger I am adding the docs label as a reminder since the table will most likely turn into a doc that the users can review. There is no action needed from you side since Joel is still working on this.

**Comment by mircubed** [comment]
@jlongtine Can we make a more detailed issue around which parts of this user story can be done by the 0.3.0alpha1 release?

After discussing with @samalba @shykes , we need the following for alpha, so I am just trying to determine which issues of this overall story need to be completed to achieve the goal below: 

" we need a cue story, especially for the preview. We don’t need the full compat, just something that bridges cue 0.2 to 0.3, otherwise it’ll confuse a lot of people. I expect a docs page somewhere that gives a simple cue example that works in 0.3."

**Comment by Alvise88** [comment]
I prefer to have a Cue SDK and understand how to translate an europa plan rather than having to use a disposable layer

**Comment by jpadams** [comment]
@aluzzardi  is socket support planned?

**Comment by shykes** [comment]
@jlongtine I took the liberty of editing this issue's title to match the newly defined terminology :)

**Comment by jlongtine** [comment]
> @jlongtine I took the liberty of editing this issue's title to match the newly defined terminology :)

Awesome!

**Comment by shykes** [comment]
The project to port the CUE SDK to 0.3 is **officially canceled**.

We really tried... But in the end there were too many technical obstacles, and not enough community interest. Thank you @jlongtine for your valiant effort, and to @morlay for carrying the torch with [Project Wagon](https://github.com/octohelm/wagon).
