### ISSUE TITLE
✨ Allow Actions to fail

### ISSUE THREAD

**Issue by schlapzz** [dagger/dagger#3141]
### What are you trying to do?

I would like to have to allow an (sub-)action to fail without failing the whole execution.
For example sometimes you have optional linter steps in your pipeline which are allowed to fail.
It would be nice if we have the option that an action throws a warning instead of an error.
Like we have in GitLab CI with the `allowFailure` keyword.

### How are you currently working around this?

IMO there is at the moment no workaround for this.
https://github.com/dagger/dagger/blob/main/pkg/dagger.io/dagger/core/exec.cue#L43

**Comment by helderco** [comment]
Closing since [CUE is no longer supported](https://dagger.io/blog/ending-cue-support).

For newer SDKs, this is documented in [Continue using container after command execution fails](https://docs.dagger.io/cookbook#continue-using-container-after-command-execution-fails).
