### ISSUE TITLE
📖 Conditional action execution

### ISSUE THREAD

**Issue by marcindulak** [dagger/dagger#3149]
### What are you trying to do?

My use case is a conditional execution of an action depending on a branch name, or other arbitrary condition.
There is this example in [azure devops pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#run-for-the-main-branch-if-succeeding)

```
and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/staging'))
```

Conditions like this are used to perform some operations only on selected branches. I use a general "operations" term since azure devops has several layers of those: pipelines, stages, jobs, steps, tasks, ..... The reason for using conditions could be for example running integration tests only after releasing staging environments (from a staging branch), or create a disposable environment in a cloud for a branch named with a specific prefix.

I'm not clear about whether dagger is designed for it, or even whether it already supports it.

### Why is this important to you?

For most CI systems, yaml based, it is difficult to setup complex conditions and even more difficult to test those conditions, since changes require submitting the pipeline onto a non-local agent. The conditional logic of the pipelines is mixed with the actual application build/deployment, making debugging slow and requiring coming up with ingenious changes to fully cover the pipeline branching. Some changes that trigger only from e.g. main branch can only be tested after the code is commited to main. Locally I could fake the branch I'm on.

Ideally I would like to define the pipeline conditional logic in dagger, including the dependencies between actions https://github.com/dagger/dagger/discussions/2124, and then test the logic https://github.com/dagger/dagger/issues/2141.

### How are you currently working around this?

No workarounds yet. Maybe migrating back to jenkins or buildbot?

![pipeline-slacking](https://user-images.githubusercontent.com/3178318/192314843-ac33146a-2477-46fe-b06f-b948c19c52d3.png)

Image credits: [Marius](https://www.augmentedmind.de/2022/06/26/speed-up-gitlab-ci-pipelines/) after https://xkcd.com/303/

**Comment by schlapzz** [comment]
You can easily implement conditional actions based on branch names.
```cue
test: "test"

#Def: {
   branch: string
   
   if branch == "main" {
     do: "main actions"
   }
   
   if branch != "main"{
    do: "non main actions"
   }
}

concrete: #Def & {
  branch: "main"
}
```

For example in GitLab you can use the environment variable `CI_COMMIT_BRANCH` to pass the current Branch name to dagger. Pretty sure something similar exists for Azure pipelines.

Maybe there are other/better ways like cue disjunction to achive something similar. Or you simply create multiple actions and handle the execution of your action within your CI Pipeline.

**Comment by marcindulak** [comment]
Thanks! I don't have yet a clarify how to map the entire flow into the cue code, but will mark this issue as "documentation".

Would you say that the "if" conditional above is the preferred aproach?
I was not able to find references to "if" in https://github.com/dagger/examples, https://github.com/dagger/dagger/issues/2552 or https://docs.dagger.io/category/use-cases, but I see some in https://github.com/dagger/dagger/blob/main/pkg/dagger.io/.
Is the lack of "if" in the examples only a way to shield beginners from it, or something discouraged?

**Comment by schlapzz** [comment]
Indeed the documentation is IMO lacking yet some of the crucial parts. But let us keep in mind that dagger is still in an early phase and it is still improving with every new release.

About the if conditions, regarding to the documentation it is not the preffered approach:
https://docs.dagger.io/1226/coding-style/#favor-disjunctions-over-if-conditions

I also try to model the example above with disjunction

```cue
test: "test"

#Def: {
   branch: string
   {
     branch: "main"
     do: "do main actions"
   } | {
     branch: "feature"
     do: "do feature test"
   }
   
}

concrete: #Def & {
  branch: "main"
}
```

But in this example you have to specify the branch to `main` or ``feature`
I don't have an idea how to model a default case with disjunction...

**Comment by shykes** [comment]
Both `if` and disjunction are valid methods and should work fine in Dagger. Cue has some edge cases and gotchas with disjunctions, which exist in dagger as well.

Here is the disjunction example above with a default. Note the `*`

```
test: "test"

#Def: {
   branch: string
   *{
     branch: "main"
     do: "do main actions"
   } | {
     branch: "feature"
     do: "do feature test"
   }
}

concrete: #Def
```

**Comment by shykes** [comment]
You may also find useful information in this style guide: https://docs.dagger.io/1226/coding-style
