### ISSUE TITLE
🐞 Unexpected execution of commands with explicit dependencies

### ISSUE THREAD

**Issue by marcindulak** [dagger/dagger#3157]
### What is the issue?

For subactions that use commands with explicit dependencies, it appears that all commands that use explicit dependencies are executed, instead of executing only up to and including the requested command. Discussed at [discord](https://discord.com/channels/707636530424053791/708371226174685314/1023706551405522955).

The original goal of this example was to have explicit dependencies between subactions, which execute shell commands.
The `sleep1` and `sleep2` subactions are to be executed in order, and `sleep2` skipped if `sleep1` fails.
This is achieved by addiing `env` block to the dependent commands. See https://github.com/dagger/dagger/issues/940 for more about explicit dependencies.

### Log output

`client.commands.sleep2` is not expected in the output below.

```sh
dagger do hello sleep1
[✔] client.commands.sleep1                                     1.0s
[✔] client.commands.sleep2                                     1.0s
[✔] actions.hello.sleep1                                       1.0s
Field   Value
stdout  ""
stderr  ""
```

### Steps to reproduce

Execute the following example with `dagger do hello sleep1`.
```sh
cat << EOF > dagger.cue
package hello

import (
    "dagger.io/dagger"
)

dagger.#Plan & {
    client: commands: {
        sleep1: {
            name: "sleep"
            args: ["1s"]
        }
        sleep2: {
            name: "sleep"
            args: ["1s"]
            env: {
                "EXIT": client.commands.sleep1.stderr
            }
        }
    }
    actions: {
        hello: {
            sleep1: { client.commands.sleep1 }
            sleep2: { client.commands.sleep2 }
        }
    }
}
EOF
```

Actual output
```sh
dagger do hello sleep1
[✔] client.commands.sleep1                                     1.0s
[✔] client.commands.sleep2                                     1.0s
[✔] actions.hello.sleep1                                       1.0s
Field   Value
stdout  ""
stderr  ""
```

Expected output (obtained when If the `env` block is removed).
```sh
dagger do hello sleep1
[✔] client.commands.sleep1                                     1.0s
[✔] actions.hello.sleep1                                       1.0s
Field   Value
stdout  ""
stderr  ""
```

### Dagger version

dagger 0.2.34 (46adf1fbd) linux/amd64

### OS version

Ubuntu 20.04.4 LTS

**Comment by helderco** [comment]
Closing since [CUE is no longer supported](https://dagger.io/blog/ending-cue-support).
