### ISSUE TITLE
Create get started guide

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#3159]

**Comment by marcindulak** [comment]
Would getting started be made runnable and automatically tested? See comment in https://github.com/dagger/dagger/issues/2552#issuecomment-1259973039

**Comment by mircubed** [comment]
@vikram-dagger how many days would you need to write this with the updated API? @aluzzardi needs to know, so we can backtrack the API timeline for you

**Comment by mircubed** [comment]
@aluzzardi @sipsma @vito talked with Vikram, and he would need about 2-3 days to create the guide after you feel more confident about the API changes
