### ISSUE TITLE
Add `jq` support to `dagger`/`cloak` binary

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#3165]
To support`bash`use, the binary should include `jq` support in a way similar to the GitHub `gh` cli: https://cli.github.com/manual/gh_help_formatting

example:

today, need `jq` binary on dev or ci machine and have to do `echo` and pipe:
```
BUILD=$(cloak -p ./cloak.yaml do<<EOF
query Build {
  core {
    git(remote: "https://github.com/dagger/todoapp", ref: "cloak") {
      yarn(runArgs: "build") {
        id
      }
    }
  }
}
EOF
)
CONTENTS=$(echo -n $BUILD | jq -r '.core.git.yarn.id')
```

with `jq` support like `gh` cli:
```
CONTENTS=$(cloak -p ./cloak.yaml do --jq '.core.git.yarn.id'<<EOF
query Build {
  core {
    git(remote: "https://github.com/dagger/todoapp", ref: "cloak") {
      yarn(runArgs: "build") {
        id
      }
    }
  }
}
EOF
)
```

**Comment by marcosnils** [comment]
related #3065

**Comment by marcindulak** [comment]
Another reason for not relying on jq presence https://github.com/stedolan/jq/issues/2305

**Comment by dolanor** [comment]
It seems cli/cli uses github.com/itchyny/gojq
https://github.com/cli/cli/blob/trunk/go.mod#L56

in https://github.com/stedolan/jq/issues/2305 we can see he also propose himself as being part of maintainers. He seems to have quite an extensive knowledge of jq. So I guess using his package is pretty good.

**Comment by dolanor** [comment]
This just popped up in my github feed: https://github.com/noahgorstein/jqp.
I wonder if it's worth integrating. It's more an after the fact playground. But if it improves ergonomy, that could be nice.

**Comment by jpadams** [comment]
not pressing

**Comment by marcosnils** [comment]
should we close this unless we make an intentional decision of **not** supporting this?
