### ISSUE TITLE
🐞 ENTRYPOINT/CMD data lost during Dagger image build

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#3170]
### What is the issue?

The default entrypoint/cmd of a base image is lost when that image is used in a Dagger image build process.

### Steps to reproduce

Running standard PHP image:
```
$ docker run  php:8.1-apache
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
[Sat Sep 17 06:11:06.065706 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/8.1.9 configured -- resuming normal operations
[Sat Sep 17 06:11:06.065751 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

Building new image based on above image, making no changes, pushing it to registry and running it:

```
query {
  core {
    image(ref: "php:8.1-apache") {
      pushImage(ref:"xxx/testrepo:latest")
    }
  }
}

$ docker run  xxx/testrepo
docker: Error response from daemon: No command specified.
See 'docker run --help'.
```

### Dagger version

cloak devel (97205d987) linux/amd64

### OS version

Linux  5.15.0-47-generic #51-Ubuntu SMP

**Comment by kpenfound** [comment]
I think what you're looking for is `Container.from/publish` instead of `Image/push`, though I don't know how much of any is available right now https://github.com/dagger/dagger/blob/cloak/core/schema/container.graphqls
it would look roughly like:
```gql
query {
  core {
    container {
      from(address: "php:8.1-apache") {
        publish(address: "xxx/testrepo:latest")
      }
    }
  }
}
```

**Comment by mircubed** [comment]
@sipsma @aluzzardi can you review, prioritize, and assign to the best person? This is blocking @vikram-dagger for docs. 

Thanks!

**Comment by sipsma** [comment]
I'll take a look at this quickly, I think it's pretty straightforward, should just build off of what @vito did the other day but now add cmd/entrypoint and image push support too.

**Comment by sipsma** [comment]
@vikram-dagger Just merged a fix into `cloak` that should fix this; I included a test case for the exact image you were using. Let me know if you run into any other issues like this though.
