### ISSUE TITLE
finish the services API

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#3173]
The services API is incomplete.

Mainly:

- Convert to New Core API
- Restructure to be multi-process (just like buildkit)
- Support non-interactive mode (e.g. for launching a db etc, we don't want tty streaming etc)
- cloak attach is hardcoded to localhost
- Tests

We should either address this or remove the services API for release.

See #3123 for more details

**Comment by samalba** [comment]
Duplicate of #3037
