### ISSUE TITLE
implement `Secret` core API

### ISSUE THREAD

**Issue by vito** [dagger/dagger#3178]
We need to implement the new `Secret` type in order to finish implementing `Directory` and `File`:

https://github.com/dagger/dagger/blob/03ea15e68fcc46f2c51bc829fd0d24e97d88c576/core/schema/secret.graphqls#L2-L14

See [`core/file.go`](https://github.com/dagger/dagger/blob/03ea15e68fcc46f2c51bc829fd0d24e97d88c576/core/file.go) for reference.

Once `Secret` exists, use it to implement `file { secret }`:

https://github.com/dagger/dagger/blob/03ea15e68fcc46f2c51bc829fd0d24e97d88c576/core/file.go#L151-L155

Disclaimer: I'm writing this issue without having used Secrets in Dagger before. I think `SecretID` is just a simple string rather than a JSON->base64'd value.

**Comment by dolanor** [comment]
Pulling out as it is harder with still unanswered design.
Working on the [HTTP impl](https://github.com/dagger/dagger/issues/3181) instead.
