### ISSUE TITLE
finish implementing `Directory` core API

### ISSUE THREAD

**Issue by vito** [dagger/dagger#3179]
I implemented the first parts of this API in https://github.com/dagger/dagger/pull/3168 but left a few parts unimplemented:

https://github.com/dagger/dagger/blob/03ea15e68fcc46f2c51bc829fd0d24e97d88c576/core/directory.go#L209-L228

* `secret` ~~will need #3178 first.~~ can be removed from the schema per comments below
* `withoutFile` _might_ be a simple application of `llb.Rm` but I've never used that before.
* `withoutDirectory` might be the same assuming `llb.Rm` is just placing a tombstone over a path and doesn't need to be done recursively.
* `diff` is probably just `llb.Diff` of two directory states but I'm a little suspicious this might be more complicated with sub-directory paths. 🤔

**Comment by vito** [comment]
@shykes Can we get rid of `directory { secret(path: "foo") }` since we already have this?:

```graphql
directory {
  file(path: "foo") {
    secret {
      id
    }
  }
}
```

The former is definitely more succinct, but thought I'd flag in case it's a relic of a prior iteration. :slightly_smiling_face:

**Comment by shykes** [comment]
> @shykes Can we get rid of `directory { secret(path: "foo") }` since we already have this?:
> 
> 
> 
> ```graphql
> 
> directory {
> 
>   file(path: "foo") {
> 
>     secret {
> 
>       id
> 
>     }
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> The former is definitely more succinct, but thought I'd flag in case it's a relic of a prior iteration. :slightly_smiling_face: 

Good catch, yeah makes sense to get rid of it. Can't remember if we had already decided that but it makes sense to me now.
