### ISSUE TITLE
Container: support configuring and respecting `CMD`

### ISSUE THREAD

**Issue by vito** [dagger/dagger#3184]
If we want users to be able to fully configure an image just as they would with a `Dockerfile`, I think we'll need to support `CMD` as well. Right now the spec only supports `ENTRYPOINT`.

I think this would mean the following changes to the spec (strawman proposal):

```graphql
extend type Container {
  "Configures a default command for the container to run."
  withCmd(args: [String!]!): Container! # or withArgs?

  "This container after executing the specified command inside it"
  exec(args: [String!], opts: ExecOpts): Container! # note that args is optional now
}
```

When running a container that has a specified `CMD` (either from its image or from `withCmd` above), `exec.args` would override them. But if not present it would default to the `CMD`.

**Comment by shykes** [comment]
Good catch. I see two good options:

1. We take the opportunity to get quietly remove `CMD` from our API, on the grounds that it's a shameful relic of the past, and redundant with `entrypoint`. Those who still want to add it to their image can always rely on a Dockerfile.
2. We use a field name so clear and accurate that the confusion is gone. Personally my favorite is:

  ```graphql
  "Configures default arguments for future commands"
  withDefaultArgs(args: [String!]): Container!
  ```

**Comment by vito** [comment]
> We take the opportunity to get quietly remove `CMD` from our API, on the grounds that it's a shameful relic of the past, and redundant with `entrypoint`. Those who still want to add it to their image can always rely on a Dockerfile.

I didn't know we saw it as a relic! Since they work in combination and both affect UX in different ways I never really saw it that way. I'm OK with omitting it but I wonder if others will think it's an oversight. The [Docker docs](https://docs.docker.com/engine/reference/builder/#cmd) and [OCI spec](https://github.com/opencontainers/image-spec/blob/main/config.md#properties) don't mark it as deprecated/discouraged or anything.

If we decide not to support configuring it, do you think we should respect a `CMD` if it's in the image config and just not provide a way to set it, or ignore it entirely?

If we decide to support it, +1 to your `withDefaultArgs` - much clearer.

**Comment by shykes** [comment]
> > We take the opportunity to get quietly remove `CMD` from our API, on the grounds that it's a shameful relic of the past, and redundant with `entrypoint`. Those who still want to add it to their image can always rely on a Dockerfile.
> 
> I didn't know we saw it as a relic! Since they work in combination and both affect UX in different ways I never really saw it that way. I'm OK with omitting it but I wonder if others will think it's an oversight. The [Docker docs](https://docs.docker.com/engine/reference/builder/#cmd) and [OCI spec](https://github.com/opencontainers/image-spec/blob/main/config.md#properties) don't mark it as deprecated/discouraged or anything.

Yeah the “shameful relic” is a highly subjective opinion based on my personal experience designing it 😅

> If we decide not to support configuring it, do you think we should respect a `CMD` if it's in the image config and just not provide a way to set it, or ignore it entirely?

Good question, it would be weird to go out of our way to ignore it. But also weird to support it without any way to see or change it…

> If we decide to support it, +1 to your `withDefaultArgs` - much clearer.

Based on the above I think it makes more sense to support it.

**Comment by dolanor** [comment]
Based on this discussion, the consensus would be:
```graphql
extend type Container {
  "Configures default arguments for future commands"
  withDefaultArgs(args: [String!]): Container!

  "This container after executing the specified command inside it"
  exec(args: [String!], opts: ExecOpts): Container!
}
```
If so, I'll work on this.

**Comment by vito** [comment]
@dolanor Yep, that looks good. :+1:

**Comment by shykes** [comment]
works for me

**Comment by vito** [comment]
Same, but I think that implies we should also add `withoutEntrypoint`, `withoutWorkdir`, `withoutUser`.

**Comment by dolanor** [comment]
I believe so. I don't love it, but it's better than unclear behavior.

**Comment by dolanor** [comment]
Follow up in: https://github.com/dagger/dagger/issues/3284
