### ISSUE TITLE
Proposed Universe (think integrations hub/marketplace/catalog) plan

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#3206]
## Meta
What to call this thing we're building?
- Dagger Universe xxxx | Dagger Universe Integrations xxxx
- xxxx = [**catalog** | registry | directory | marketplace | hub | planetarium | ???]

I like "catalog" best so far.

Integrations could be: Extensions, (complete runnable examples), Extension builder tools (like repo templates, SDKs, etc)

We're use this as a tracking issue and break out work item issues. We'll note those issue numbers below where appropriate.

## Preview Goals, Assumptions, Requirements: <a href="#preview" id="preview">#</a>
- [ ] Browse extensions in a website
- [ ] Easily use discovered extensions in projects thanks to basic prompts/snippets
- [ ] Submit community extensions for listing in Universe catalog
- [ ] Public backlog of needed, coming soon extensions.
- [ ] Link to extensions page/site from docs, main website, Dagger Cloud, etc
- [ ] Links back to docs page: "build an extension", "how to submit an extension", etc
- [ ] Links to Dagger Cloud, etc
- [ ] We should start with a simple separate Universe site leveraging tools and prior art from our docs site and website. `universe.dagger.io` or `dagger.io/universe`
- [ ] Categories will start small and static, can expand and get dynamic later: 
    * [ ] start with by "Dagger" and by "Community"
- [ ] Listings can be opened/expanded to get more detailed info, will have CTA buttons/links, example code
- [ ] Need a source of truth for all extensions in catalog: comment from @vikram-dagger : https://github.com/dagger/dagger/pull/3171#issuecomment-1262755218

### Source of truth: <a href="#source-of-truth" id="source-of-truth">#</a>
JSON or YAML file or files in git is attractive:
  * [example from Netlify](https://list-v2--netlify-plugins.netlify.app/plugins.json)
  * [example from Backstage](https://backstage.io/docs/plugins/add-to-marketplace)
  * Lightweight plain text
  * Easy integration with web tools for rendering
  * Submitting an extension is simply a PR to the file or directory of files
  * Ample tooling to lint JSON/YAML file or run other validation/quality checks 

#### structured data (e.g. JSON, YAML) format: <a href="#data-format" id="data-format">#</a>
- Tags for extension attributes
- Link to publisher’s git repo
- Version/git ref
- Example gql file path?**
- Possibly an icon:
  + such as https://feathericons.com/ for Community
  + company logo for partners

#### Rendered structured data in catalog website:  <a href="#snippet" id="snippet">#</a>
- Snippet to use in dagger.gql (uses version)
<img width="300" alt="image" src="https://user-images.githubusercontent.com/3187222/193378034-6313c572-e1e8-4475-af8f-73c6f189c3ac.png">

- **A gql file with sample usage in publisher’s git repo that gets rendered
<img width="400" alt="image" src="https://user-images.githubusercontent.com/3187222/193378301-8b54ac53-492a-4aeb-b713-5ee7eb5f7d22.png">

       
#### Universe program: <a href="#universe-program-guides" id="universe-program-guides">#</a>
- Basic extension contrib guide
- Basic extension tech build guide
https://github.com/netlify/plugins/blob/main/docs/CONTRIBUTING.md#add-a-plugin

## GA Goals:
- [ ] Better search, sort of extensions
- [ ] Linkage to Dagger Cloud playground
- [ ] Possibly Partner extensions category
- [ ] Build dagger.gql file by selecting a "basket"/set of extensions?
- [ ] Use set of extensions in Dagger Cloud playground session
- [ ] Buttons for launch in playground
- [ ] GitHub actions checks for contributor PRs
- [ ] Snippet has “lock” info (full git sha of recommended version)
<img width="300" alt="image" src="https://user-images.githubusercontent.com/3187222/193378127-b396a604-b8bc-44a0-93ea-5961b805ad9d.png" /> (related #3198)
- [ ] Templated extension repo with more features and/or cli command to generate template skeleton repo
- [ ] Good extension contrib guide
- [ ] Good extension tech build guide
- [ ] Connecting Cloud + Universe via third part authentication (Github, Google...)

**Comment by jpadams** [comment]
Excellent discussion from Docusaurus Showcase: https://github.com/facebook/docusaurus/issues/6882

Netlify plugin contrib guidelines: https://github.com/netlify/plugins/blob/main/README.md

**Comment by vikram-dagger** [comment]
No problem from my end to have this in a separate site. Docs can link to it instead of duplicating the info, either just a single link called `Extensions` pointing to the universe root, or a separate stub link pointing to each each extension detail page in universe.

**Comment by kpenfound** [comment]
>Warns against a single file for all showcase entries

I'm also wondering if a single file will be difficult to manage with conflicts

Another good thing to have from the start would be a "Don't see what you're looking for?" at the bottom of the cards that links to a github discussion for extension requests

**Comment by slumbering** [comment]
@jpadams Regarding GA Goals I've added the authentication topic. Connecting Cloud + Universe.

**Comment by shykes** [comment]
@sipsma @vito @aluzzardi thoughts? How does this affect core?

**Comment by Camille-Elairin** [comment]
@jpadams @mircubed @shykes @slumbering @kpenfound 
Here is the preview for the Universe's UI for "Preview launch", feel free to add comments here :)
https://www.figma.com/proto/mG8LytdXWFV2OcYDY8I5gC/Marketplace?node-id=17%3A757&scaling=min-zoom&page-id=0%3A1

**Comment by samalba** [comment]
I remove the priority here given the extensions are on hold. Leaving you assigned @jpadams since you started to spec it out, we can resume this work whenever we re-design the extensions.

**Comment by jpadams** [comment]
daggerverse.dev exists!
