### ISSUE TITLE
Don't pollute host stdout/stderr

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3218]
## Problem

In cloak (0.3) the Dagger engine is embedded in a host program (script or tool), which instruments it to run pipelines.

Currently the dagger engine prints all its output to the standard output of the engine, which is inherited from the host program. The result is that dagger "takes over" the standard output of its host, which is not desirable.

## Solution

When a program is run that embeds the dagger engine, the output of the dagger engine should not pollute the host program's standard output and error streams. Instead, all useful outputs from running a pipeline should be available to the host program by making API calls.

**Comment by jlongtine** [comment]
Perhaps we could make this a configurable part of the client? So `engine.Start` would let you print all of the logs or suppress them or have your own callback for them?

**Comment by jpadams** [comment]
related #3403
