### ISSUE TITLE
Automated tests on macos

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3225]
There's a lot of tricky details to get right when starting dagger on macos: need to create buildkit running on a VM somewhere (w/ docker desktop by default for now), need to ensure LLB is using the right platform, etc. 

It's very easy to miss issues when you don't have a macos machine readily available to test on.

While it's not trivial, we should find a way to run our CI on macos. GHA does have mac os runners, so that's an obvious possible option.

**Comment by gerhard** [comment]
+1 for `macos-latest` GitHub Actions runners. cc @grouville 

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by sipsma** [comment]
As mentioned here: https://github.com/dagger/dagger/pull/3749

There's a lot more very important testing we need to do on macos now (around provisioning done by SDKs+engine-session binaries), and it's currently totally manual, which is not great. So we should be sure to cover that when we set this up.
