### ISSUE TITLE
Replace `ContainerAddress` with a regular string

### ISSUE THREAD

**Issue by vito** [dagger/dagger#3257]
per https://github.com/dagger/dagger/pull/3219#discussion_r987337784

We generally use scalars for opaque values that pass through the client without ever being modified or constructed directly. `ContainerAddress` on the other hand is a user-provided string, and having to cast it to this special type is a little weird.

Also, we currently use regular strings for paths (e.g. `withNewFile(path: String!)`), so it seems a little inconsistent to opt for a scalar type for image addresses but not paths.

**Comment by shykes** [comment]
No opinion on this.

**Comment by helderco** [comment]
This is why I did this:

<img width="620" alt="Screen Shot 2022-10-19 at 21 19 22" src="https://user-images.githubusercontent.com/174525/196806825-26f4e7db-4f26-402f-849d-ca78db2f8a44.png">

So 👍 to this.
