### ISSUE TITLE
Update project schema to use new API

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3259]
Expanding this comment out to its own issue: https://github.com/dagger/dagger/issues/3016#issuecomment-1261344900

Project loading + building has it's own schema: https://github.com/dagger/dagger/blob/9bbbf8459b8dec91be8e0cdb60f6a2f0770314eb/core/project.schema.go#L37-L94

It is only used internally (not meant to be used by users directly yet) but it nonetheless needs to be integrated with the new API (i.e. `Directory`/`Container`/etc.). At minimum, this is needed so we can delete the old `Filesystem` code, but it will also be good to rethink the design at this time too.

**Comment by sipsma** [comment]
This may actually just be a matter of removing this from the "public" schema and only supporting this internally, with dagger.gql contents provided as a header. We may still model this as an API if convenient but it should not be exposed directly to users.

**Comment by sipsma** [comment]
Also, note to self, be sure to try not to break the existing mechanism for all this if feasible and if cloud work relies on any of it.

**Comment by vito** [comment]
Update: the project schema has been updated, slightly, via the above PR - but it still uses LLB directly and returns a `*core.Directory`. It should instead return a `*core.Container`, so this issue is still valid. Some context here: https://github.com/dagger/dagger/pull/3304#discussion_r992864815

**Comment by sipsma** [comment]
I think updating the schema to not use Filesystem is good enough for this issue. Any future changes to the internal code can be tracked separately. Closing
