### ISSUE TITLE
Container: add `withDirectory` and `withFile`

### ISSUE THREAD

**Issue by vito** [dagger/dagger#3264]
```graphql
type Container {
  withDirectory(path: String!, directory: DirectoryID!): Container!
  withFile(path: String!, file: FileID!): Container!
}
```

Use case: copying the contents of a directory/file into a container's rootfs, rather than mounting it.

Some discussion in https://github.com/dagger/dagger/pull/3219#issuecomment-1267809318

**Comment by vito** [comment]
Now that `Container.withFS` exists I don't think we need this, because you can just take the existing FS and replace it with a copied one:

```go
func TestContainerDirectoryCopy(t *testing.T) {
	c, ctx := connect(t)

	dirID, err := c.Core().Directory().
		WithNewFile("hello.txt", api.DirectoryWithNewFileOpts{
			Contents: "hi there",
		}).
		ID(ctx)
	require.NoError(t, err)

	ctr := c.Core().Container().From("alpine:3.16.2")

	cpID, err := ctr.FS().WithCopiedDirectory(dirID, "/content").ID(ctx)
	require.NoError(t, err)

	rootfs := t.TempDir()

	ctr = ctr.WithFS(cpID)
	ok, err := ctr.FS().Export(ctx, rootfs)
	require.NoError(t, err)
	require.True(t, ok)

	content, err := os.ReadFile(filepath.Join(rootfs, "content", "hello.txt"))
	require.NoError(t, err)
	require.Equal(t, "hi there", string(content))

	content, err = os.ReadFile(filepath.Join(rootfs, "etc", "alpine-release"))
	require.NoError(t, err)
	require.Equal(t, "3.16.2\n", string(content))
}
```

Erring on the side of closing this since we've used similar justification to turn down other duplicative APIs, e.g. here: https://github.com/dagger/dagger/issues/3179#issuecomment-1269179918

**Comment by vito** [comment]
Reopening as it's way more convenient to just have this directly in the API, since it'll propagate to all codegen'd SDKs.

**Comment by sipsma** [comment]
Done here https://github.com/dagger/dagger/pull/3827
