### ISSUE TITLE
Security issue on containerd

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#3274]
Found out there is a new dependency site linked from pkg.go.dev: https://deps.dev/go/go.dagger.io%2Fdagger/v0.2.35.
We can see: https://deps.dev/advisory/ghsa/GHSA-5ffw-gxpp-mxpf
I guess we need to update our dependency on containerd.

**Comment by dolanor** [comment]
Upgrading containerd brings this issue: https://deps.dev/advisory/osv/GO-2022-0969
But it can be fixed by upgrading golang.org/x/net as well.
So it seems feasible.
I'm gonna try that tomorrow.

**Comment by gerhard** [comment]
Sounds good to me! Let's try it and see what happens.

**Comment by dolanor** [comment]
Stuck for now because of some caching quirks + GHA.
Let's see if it's just a flaky situation.
