### ISSUE TITLE
Final CLI syntax for 0.3

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3278]
## Overview

In 0.3 (codename cloak) the CLI syntax will need to change, since the underlying engine is quite different.

The exact syntax has not been defined - the current syntax is an accident of implementation.

## What to do

[ ] Initial proposal
[ ] Get feedback, discuss
[ ] Consensus
[ ] Implementation

**Comment by mircubed** [comment]
@shykes can I close this since you created #3347 ?
