### ISSUE TITLE
Add tests for nodejs engine SDK

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3290]
There's no automated tests for starting the engine from the nodejs SDK. Instead, there should be tests.

**Comment by gerhard** [comment]
Yes, something basic would have really helped. If the engine starts, runs & exits successfully within a certain time interval (e.g. 1 minute?), that would be a good enough first test.

**Comment by sipsma** [comment]
Merged that barebones test case here: https://github.com/dagger/dagger/pull/3292

cc @slumbering let me know if there's any really dumb about the test I added. I just slapped together what I could quickly but I'm guessing there's actual test frameworks and stuff that are usually used. If there's any simple improvements we can make to ease the addition of more tests in the future that would be good to know (no need to implement immediately though)

**Comment by slumbering** [comment]
> Merged that barebones test case here: #3292
> 
> cc @slumbering let me know if there's any really dumb about the test I added. I just slapped together what I could quickly but I'm guessing there's actual test frameworks and stuff that are usually used. If there's any simple improvements we can make to ease the addition of more tests in the future that would be good to know (no need to implement immediately though)

No dumb about your tests IMO ;). However we should definitely use a unit test framework like mocha. Moreover, the `timeout` command you're using is not compatible with MacOs. I'll open a PR for that.

**Comment by sipsma** [comment]
We should of course add more tests as we change things going forward, but between my original PR and JF's improvement (https://github.com/dagger/dagger/pull/3329) I feel okay closing this issue as we at least have any coverage at all now.

**Comment by slumbering** [comment]
I've created a new issue for the next step: #3353
