### ISSUE TITLE
Extension OS dependencies

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#3306]
Some libraries (no matter the language) may need OS packages as dependencies.

The way buildpacks (CNB) solve this is to have a big base image packed with dependencies that **may** be needed. It's better for reusability. It also has the ability for you to provide your own base image if you need to. 

Have we thought about this? If a Python extension needs gettext for example, do we provide a config to add packages to the runtime?[^1] Or do we simply allow to replace the runtime image with a custom one?

In the future we should publish in an OCI registry our base images for the SDK runtimes. A user can use that as a base and add on stuff that’s needed. Or replace it entirely with Debian instead of Alpine for example. 

It has to be done in a way that doesn’t break the runtime protocol, but this pattern already exists elsewhere (buildpacks, buildkit frontends…).

That's my prefered solution. It's more flexible. Are there other options or ideas around this?

[^1]: There's the different package managers and OSes to consider. Even the name of the packages change between these.

**Comment by helderco** [comment]
We should have guidelines for making extensions and we can add one for preferring a common base image. Otherwise, if authors change it just for preference sake we lose layer reusability increasing disk size and network traffic.

But if you're making extensions for your own company, it's good to have this flexibility.

**Comment by sipsma** [comment]
Totally agree that the base image can't be fixed, in addition to what you mentioned we will also run into company compliance issues eventually.

Besides just customization of the base image, runtimes are most likely going to need to other configuration settings. E.g. some of the ideas mentioned here: https://github.com/dagger/dagger/issues/3036#issue-1376410749

So I think there's probably a path to supporting base image customization through that. Made an issue for it: https://github.com/dagger/dagger/issues/3352

**Comment by sipsma** [comment]
Also, while I'm not opposed to publishing our own OCI images and such, I do like how we currently avoid that by using LLB in the engine. It would be nice if we could maintain that model in the long run. Random idea: maybe users could customize the base image by providing graphql queries (either raw or maybe even lang-specific) in their configuration (optionally).

Lots to figure out there, not a fleshed out idea, just something to keep in mind, doesn't need to be figured out now.

**Comment by helderco** [comment]
Things are very different now. I'm going to close and we'll revisit later. The Python SDK already provides an escape hatch to use a different base image from the default one, by a setting in `pyproject.toml`. However, the other SDKs don't have this feature, so this needs a decision on a convention.

If we move to Wolfi, we can also support an array of packages, also defined in `pyproject.toml`, to install there.
