### ISSUE TITLE
🐞 insane memory usage

### ISSUE THREAD

**Issue by tiramiseb** [dagger/dagger#3307]
### What is the issue?

I am working on a project with a large amount of tasks to execute in order to deliver what needs to be delivered.
In short, I have subdirectories which correspond to different pieces of software (backend, frontend, etc etc), and I build linux packages out of them, in order to deliver a suite of packages.
Therefore, I have a "#Package" definition in each subdirectories. In another directory, I import all these directories and use their "#Package" definitions for a job that builds a packages repository by merging all these outputs.
In one call, dagger must build images, compile software (go, yarn, etc), then generate the packages, and then finally deliver the repository files.

I am currently using Earthly and it works correctly, without using too much memory. I am trying to switch to Dagger, mainly because how fast it starts jobs.

Unfortunately, Dagger eats memory far more than any other software I have seen before: approximately 2 minutes after starting it, it consumes more than 20 GB, and it gets killed by the kernel.

### Steps to reproduce

Have a huge plan, and run it.

### Dagger version

dagger 0.2.35 (00cde7521) linux/amd64

### OS version

Ubuntu 21.10

**Comment by tiramiseb** [comment]
I have tried compiling the latest commit in main ([ea275a3](https://github.com/dagger/dagger/commit/ea275a3bafbc5b5c611e0b81bf2dd8a8add72f6b)), it acts the same way.

**Comment by grouville** [comment]
> main

Hi @tiramiseb,
We are aware of this issue. It is related to [Cue](https://github.com/cue-lang/cue/issues/1795). The new release of Dagger will enable you to code your pipeline in Go, Typescript / Python, and won't have these issues. It is in alpha version for the moment, and you can find more infos on the `cloak` branch. It is very early and the API design is not fully stable yet

**Comment by tiramiseb** [comment]
Unfortunately, removing all `docker.#Build` didn't change anything.
I'll take a look at the `cloak` branch

**Comment by gerhard** [comment]
FTR https://github.com/dagger/dagger/pull/2942#issuecomment-1219143178

**Comment by mircubed** [comment]
Closing due to end of support for CUE SDK - https://dagger.io/blog/ending-cue-support
