### ISSUE TITLE
Python: Consider not using alpine for runtime image

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#3309]
Part of #3326

I generally don’t like to use Alpine images for running Python unless it’s for quick prototyping or something trivial because quite often you find some issues.

## Problems

Standard PyPI wheels don’t usually work on Alpine which means the package manager has to compile binaries if needed, making the **build time slower and the image bigger**. 

Also, in practice, the `musl` C library has some differences with `glibc` which can cause problems. This has happened to me in the beginning before I switched.

So even though the Alpine image is quite small, you can easily get a much bigger image than just using a slimmed version of Debian (e.g., `python:3.10-slim-bullseye`).

## However

This could all be better now with [PEP 656](https://peps.python.org/pep-0656/) (pip and PyPI supporting wheels for the `musl` C library) and the [`cibuildwheel`](https://cibuildwheel.readthedocs.io/en/stable/) build tool. And connected to #3306, we can allow a user to replace the image for something more suitable.

## Context

- [Using Alpine can make Python Docker builds 50× slower](https://pythonspeed.com/articles/alpine-docker-python/)
- [The best Docker base image for your Python application (Sep 2022)](https://pythonspeed.com/articles/base-image-python-docker-images/)

**Comment by sipsma** [comment]
Sounds good, I don't think alpine was chosen more than arbitrarily, slim debian image sounds good 👍

**Comment by gerhard** [comment]
My suggestion is https://github.com/chainguard-images/python. Double-check that it's based on glibc. FWIW:

[![Image](https://user-images.githubusercontent.com/3342/199778330-c4c5fc17-dbfe-473a-9426-b5314280031c.png)](https://changelog.com/shipit/76)
