### ISSUE TITLE
Wrap error messages with links/pointers to help

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3316]
Once Go SDK is merged I will send out a PR that wraps all errors returned by it with a link pointing somewhere for help.

Original idea was to just wrap engine.Start errors with this, but we are planning on refactoring that to not be a callback soon so not worth it.

**Comment by mircubed** [comment]
@shykes @samalba are we ok with pointing the users to our discord channel and telling them to use the help channel for support?

**Comment by sipsma** [comment]
Sent out a PR: https://github.com/dagger/dagger/pull/3342

Just need to decide what message to include there

**Comment by samalba** [comment]
> @shykes @samalba are we ok with pointing the users to our discord channel and telling them to use the help channel for support?

Given that the binary will be harder to change than a web page, I would make the link short and easy to remember (eg. `https://dagger.io/help` with a short message). On this page I would simply give both options (github issues and discord), and we can change it later without having to re-release.

**Comment by shykes** [comment]
> > @shykes @samalba are we ok with pointing the users to our discord channel and telling them to use the help channel for support?
> 
> Given that the binary will be harder to change than a web page, I would make the link short and easy to remember (eg. `https://dagger.io/help` with a short message). On this page I would simply give both options (github issues and discord), and we can change it later without having to re-release.

I agree. The URL should also include an element that is specific to the cloak Go SDK, as opposed to eg. Dagger Europa, NodeJS SDK etc.

For example `https://dagger.io/help/go` . That's probably specific enough?

**Comment by samalba** [comment]
> For example `https://dagger.io/help/go` . That's probably specific enough?

Semantic bike shedding if I may, I'd use an anchor instead (`/help#go`) - because the content is likely to be the same for all SDKs initially and vary over time.

**Comment by shykes** [comment]
works for me 👍

**Comment by mircubed** [comment]
Noted - created an issue to create URL #3350

**Comment by mircubed** [comment]
@aluzzardi can this move to you instead since Erik is OOO? He has a PR open, but it needs some updates.

**Comment by sipsma** [comment]
Done here: https://github.com/dagger/dagger/pull/3342
