### ISSUE TITLE
[EPIC] Create documentation for 0.3.0-alpha.N 

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#3322]
### What is the issue?

This is the parent issue for all issues related to documentation for 0.3.0-alpha.N 

- [x] #3318 
- [ ] #3048 
- [ ] #3156 
- [ ] #3159 
  - [ ] #3052 
- [ ] #3321 
- [ ] #3256 
- [ ] #3177

**Comment by mircubed** [comment]
@shykes based on the [new launch plan](https://github.com/orgs/dagger/discussions/969), should we remove #3256 and #3052 from this release requirement? 

And add an excellent Getting started with Dagger Go SDK doc instead?

**Comment by mircubed** [comment]
@vikram-dagger we are working an update list today to review with you during our sync tomorrow. After that, we can update the description of this list.

**Comment by gerhard** [comment]
FWIW, one thing that I realised today, as I was talking to @aluzzardi, is that we will need to import all docs from the `main` branch into the `cloak` branch **before** the merge. Once we merge `cloak` into `main`, everything in `main` will be wiped. I have added a reminder for me to check this before the merge in https://github.com/dagger/dagger/issues/3283, but I think that we should track the PR/issue for that in this epic @vikram-dagger.

**Comment by shykes** [comment]
> FWIW, one thing that I realised today, as I was talking to @aluzzardi, is that we will need to import all docs from the `main` branch into the `cloak` branch **before** the merge. Once we merge `cloak` into `main`, everything in `main` will be wiped. I have added a reminder for me to check this before the merge in #3283, but I think that we should track the PR/issue for that in this epic @vikram-dagger.

Good catch. no matter what, make sure #3283 is the source of truth on what needs to happen for release. Either directly or indirectly by referencing othe issues. Let 3238 be our rock 😁

**Comment by mircubed** [comment]
Closing this since we updated the plan. Please refer to #3360 now
