### ISSUE TITLE
Support configuring additional options for secrets

### ISSUE THREAD

**Issue by vito** [dagger/dagger#3323]
Buildkit's full `SecretInfo` struct is as follows:

```go
type SecretInfo struct {
	ID       string
	Target   string
	Mode     int
	UID      int
	GID      int
	Optional bool
	IsEnv    bool
}
```

We already support `ID`, `Target`, and `IsEnv` but maybe folks will have a use for `Mode`, `UID`, `GUID`, and/or `Optional`.

**Comment by dolanor** [comment]
I decided not to work on this one until https://github.com/dagger/dagger/pull/4932 is cleared.

**Comment by TomChv** [comment]
@vito If I wanna take care of this issue, I need to update option in https://github.com/dagger/dagger/blob/30e48293b2a287aca3957482ebb71150fb975df4/core/schema/container.go#L586 right?

Is there any other location when this would be necessary?
