### ISSUE TITLE
Code-first schemas: support for converting comments into schema docs

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3335]
Didn't implement this in Go yet, should be pretty trivial though: https://pkg.go.dev/go/ast#Comment

Not sure if it works with strawberry @helderco (no need to support it immediately if not, this is just a tracking issue so we don't forget about it).

TS supports grabbing comments too: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker

**Comment by helderco** [comment]
Yes it's supported. Not necessarily via comments, but you can set descriptions.

**Comment by sipsma** [comment]
Addressed in modules implementation
