### ISSUE TITLE
Create help URL for error messages 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3350]
In #3316, @sipsma is working on wrapping error messages with a basic message that includes a link to a help URL.

We need to have the following:
- short link and easy to remember and using an anchor like help/#go
- On this page, we just need a short message and links to ability to create github issues and discord help channel. We can change it later without having to re-release.

**Comment by slumbering** [comment]
PR opened: https://github.com/dagger/dagger.io/pull/980

**Comment by mircubed** [comment]
closing since PR is merged, thanks!
