### ISSUE TITLE
Go Getting Started Guide 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3363]
related to #3360 

We need a getting started guide that focuses on the Go SDK. @kpenfound can help support with any Go questions 

It should have a section for installation, but should point back to the install page created in #3362

**Comment by kpenfound** [comment]
Getting-started code example here: https://github.com/kpenfound/dagger-demos/tree/main/go/getting-started

**Comment by mircubed** [comment]
After reviewing the current guide, we need to have a shorter getting started guide that showcases the "why dagger" question.. @kpenfound is working on this. 

    - idea #1 - Show how we build and test front and backend….showing that you need two toolchains typically, but only one with Dagger
    - idea #2 - Go repo that builds binary with several versions of Go to a directory on your local work dir

**Comment by mircubed** [comment]
reopening since @kpenfound is working on the updates for this

**Comment by kpenfound** [comment]
Merged now 😄 https://github.com/dagger/dagger/pull/3450
