### ISSUE TITLE
Refactor engine Start to not normalize workdir+configpath

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3375]
Right now engine.Start implicitly sets workdir+configpath to defaults if they are not set. This creates complications for callers of it who sometimes don't want to load one or the other or both.

Instead engine Start should just use the values as set. If workdir is not set, don't load it; if configpath is not set, don't load it.

This allows higher levels to determine the right value.

Slight complication comes from the fact that all our SDKs probably *do* want some consistent behavior in determining defaults. We can reimplement in each of them or we can change it so that when they shell out to the engine they go through a layer that implements the defaults (e.g. maybe the command discussed [here](https://github.com/dagger/dagger/issues/3347#issue-1406924910)).

Another complication is that we can't currently determine the difference between explicitly set `""` and implicitly unset `""`, so may just need to make the args to engine a `*string` instead

**Comment by helderco** [comment]
Python already sets those only if configured (≠ `None`). Seems like there's a decision to be made on consistency, so I'm going to remove Python scope for now. If it's decided that the current behavior needs to change then please add it back.

**Comment by TomChv** [comment]
Fixed for nodeJS in #4465

**Comment by sipsma** [comment]
Ancient issue, no longer relevant
