### ISSUE TITLE
Installing Go SDK is not intuitive

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3391]
## Problem

To install the Dagger Go SDK, one has to run the following commands:

```console
go get go.dagger.io/dagger@<version if needed>
go mod edit -replace=github.com/docker/docker=github.com/docker/docker@v20.10.3-0.20220414164044-61404de7df1a+incompatible
go mod tidy
```

This is 1) verbose, and 2) unusual for Go developers. Therefore it will result in a bad DX. We should boil this down to just `go get`.

## Solution

The solution unfortunately is complex, because it is caused by a conflict between the Moby/Docker and Go projects, respectively. There are four ways we can solve this:

1) Convince Go to revert their decision to break the established tagging convention for go projects. Estimate: impossible.
2) Convince Docker to change their tagging convention to match Go's new tagging mandate. Estimate: unlikely.
3) Convince Go and Docker to find a middle ground. Estimate: unlikely.
4) Solve the problem downstream with a private fork + custom tooling. Estimate: annoying but doable.

Related: https://github.com/dagger/dagger/issues/3367#issuecomment-1278324885
Related: https://github.com/dagger/dagger/issues/3368

**Comment by vito** [comment]
> Convince Docker to change their tagging convention to match Go's new tagging mandate. Estimate: unlikely.

Update from today's community call: it sounds like they're doing this after all by switching to regular semver!

However we'd still need to wait for a new release of `moby/buildkit` to be tagged. Maybe that won't be too much trouble.

We can't easily bump to an untagged `moby/buildkit` either; I tried this and ended up needing to add a `replace` line to stop the Go CLI from "bumping" (really rewinding) the dependency, which brings us back to square one. Context: https://github.com/dagger/dagger/pull/3560#discussion_r1007075789

The long-term fix, to me, is to bite the bullet and switch to an external engine so the SDK doesn't depend on any of this at all.

**Comment by vito** [comment]
Yep - closing, thanks for checking in!
