### ISSUE TITLE
API: contents field can be ambiguous

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#3397]
Both `File` and `Directory` have a `contents` field.

This can be confusing, for instance:

```go
c.Directory().WithNewFile("/foo.txt").Contents(ctx)
```

`WithNewFile()` returns a `Directory` so here we're listing the directory rather than grabbing the contents of `/foo.txt`.

With the builder pattern, it's not obvious to the naked eye which object is being returned.

I suggest renaming `directory.contents` to files perhaps? e.g.

```go
c.Directory().WithNewFile("/foo.txt").Files(ctx) // <-- list files
c.Directory().WithNewFile("/foo.txt").File("/foo.txt").Contents() // <-- get a file's contents
```

/cc @shykes @vito @sipsma

**Comment by vito** [comment]
I like it! Bikeshed/strawman: maybe "entries" instead since it will also return directories? Just using the term from https://man7.org/linux/man-pages/man3/readdir.3.html. Don't love it though.

**Comment by aluzzardi** [comment]
Oh, entries is even better!

**Comment by shykes** [comment]
I waive my bikeshedding privileges on this one 😛works for me.
