### ISSUE TITLE
Merge docs and website folders from cloak branch into main

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#3400]
The `cloak` branch included a separate set of content and docs website configuration. When `cloak` was merged into `main`, those docs/configuration were preserved by moving them to the `docs-0.3` and `website-0.3` directories (#3371). These docs/configuration should be merged into the existing `docs` and `website` directories and the above temporary directories should be deleted.

**Comment by jedevc** [comment]
The temporary directories added in https://github.com/dagger/dagger/pull/3371 look to have been removed at some point - so we can close this one out.
