### ISSUE TITLE
Replace dockerfile with golang guide

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#3420]
We talked about a transitional approach earlier today. One where someone who uses a `Dockerfile` and `docker build` could move to first building their `Dockerfile` with the Go SDK and then replace the lines of the `Dockerfile` with calls to the Go SDK. The idea is to give people a path and confidence is what is being built.

cc @kpenfound @mircubed @shykes

**Comment by aluzzardi** [comment]
/cc @vito 

docker build support in new API is not yet available

**Comment by kpenfound** [comment]
Is there an issue to track that @aluzzardi ?

**Comment by mircubed** [comment]
@kpenfound I think this? https://github.com/dagger/dagger/pull/3438

**Comment by jpadams** [comment]
https://github.com/dagger/dagger/pull/3438 merged

**Comment by samalba** [comment]
I'll get this one, good practice for testing the SDK (if someone is already on it, let me know).

**Comment by jpadams** [comment]
Still needed @vikram-dagger or @samalba?  Or can close?

**Comment by vikram-dagger** [comment]
I'm not sure why it's not linked but we have https://github.com/dagger/dagger/pull/4173 open and awaiting review for this requirement. @kpenfound has approved it already, I was waiting to see if any other feedback came in before merging but we can go ahead and merge if it looks good.

**Comment by samalba** [comment]
Fixed by #4173
