### ISSUE TITLE
rename `dagger` CUE cli release/packaging considerations

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#3447]
We'll rename the current `dagger` 0.2 cli to make it more clear that it's for the CUE version of `dagger`. This will require some release changes and docs updates. This issue will track the work.

discussion for name change decision: https://github.com/dagger/dagger/discussions/3432#discussioncomment-3919281
- [x] Goreleaser
- [x] `install.sh`
- [x] homebrew bottle
- [x] Homebrew tap
- [ ] GitHub action: https://github.com/dagger/dagger-for-github

from @gerhard:
As far as I can tell, the changes will be mostly in Goreleaser, specifically https://github.com/dagger/dagger/blob/main/.goreleaser.yml

`install.sh` is fairly quick to figure out once we have the Goreleaser changes.

For Homebrew bottle, I think that we should introduce a new formula with the new name. I'm thinking deprecate the existing formula as `dagger@0.2` - similar to `go@1.18`

For Homebrew tap, we introduce a new formula & deprecate the existing formula as `dagger@0.2`

Not sure about the GitHub Action - I would like to get @crazy-max 's opinion on that.

**Comment by jpadams** [comment]
@shykes @samalba @aluzzardi @gerhard if I understand correctly, the idea is to bring everything that is currently on the `v0.2.x` branch and bring it back to `main` but with the `dagger` cli name changes etc. So we won't have a long-lived `v0.2.x`, correct?

**Comment by shykes** [comment]
Yes that's right. Eventually the v0.2.x branch can go away, although we don't need to rush that part for go sdk launch

**Comment by jpadams** [comment]
Got it! Oh I see that here: https://github.com/dagger/dagger/issues/3445

**Comment by shykes** [comment]
I added this issue to the overall list in https://github.com/dagger/dagger/issues/3445

**Comment by shykes** [comment]
Also: VSCode plugin...

**Comment by shykes** [comment]
For the following:

* VSCode
* Github Actions

Is there any chance we may want to expand the existing project to be useful beyond CUE?

**Comment by mircubed** [comment]
@gerhard now that we have this list and name confirmation, is the assumption that you will own this issue?

**Comment by jpadams** [comment]
GHA effort covered elsewhere
