### ISSUE TITLE
Directory: add `include` and `exclude` to `withDirectory`

### ISSUE THREAD

**Issue by jlongtine** [dagger/dagger#3466]
This is necessary for a full implementation of `dagger-classic` `core.#Copy` - https://github.com/dagger/dagger/issues/3232

I'd suggest this API: 

```graphqls
type Directory {
  withDirectory(path: String!, directory: DirectoryID!, include: [String!], exclude: [String!]): Directory!
}
```

**Comment by vito** [comment]
Done via https://github.com/dagger/dagger/pull/3583
