### ISSUE TITLE
Organize the dagger/examples repo by SDK

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3470]
Organize the dagger/examples repo by SDK: transpose the contents of the `v0.2.x` branch of dagger/examples into `main`, under an sdk-specific subdirectory

**Comment by mircubed** [comment]
@kpenfound @jpadams I know you were already doing clean-up on the examples repo, so does it make sense to assign this to one of you?

**Comment by kpenfound** [comment]
@mircubed yup either of us!

**Comment by mircubed** [comment]
Great, thank you @kpenfound! Do you think it is worth adding context about this repo in the docs FAQ?

**Comment by kpenfound** [comment]
Oh I think I mixed up some threads here 😆 My understanding was that we would move to sdk specific examples living alongside their sdk, as in `sdk/go/examples/`, which now may be `dagger-go-sdk/examples/`

**Comment by mircubed** [comment]
I think we can close this now right @kpenfound ? Should we document it anywhere in the Readme?

**Comment by kpenfound** [comment]
Yeah I think the last remaining task is to mention dagger/examples in the dagger/dagger README

**Comment by mircubed** [comment]
@kpenfound can you submit a PR to the readme and then close this issue? You can add Solomon as the PR reviewer for the Readme update
