### ISSUE TITLE
Transpose the content of the `v0.2.x` branch into a new fork `dagger/dagger-cue`

### ISSUE THREAD

**Issue by samalba** [dagger/dagger#3471]
Here is what we came up with for promoting the `dagger@v0.2.x` branch as the cue-sdk under `main`:

- [x] create a branch `cue-sdk` based on `v0.2.x`
- [x] create `./sdk/cue/README.md` in the `dagger/dagger@main` repo with a link to the `dagger/dagger@cue-sdk` branch
- [x] ensure the release process still works (rename the published binary from `dagger` to `dagger-cue`)

cc @aluzzardi who has the context

**Comment by gerhard** [comment]
My understanding was that all SDKs will be kept in the `dagger/dagger` repo, under `sdk/`. I thought that we were all for the monorepo approach. What changed?

**Comment by gerhard** [comment]
Closed by https://github.com/dagger/dagger/pull/3486.
