### ISSUE TITLE
0.2 docs into a new "Dagger CUE SDK" site

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#3474]
### Need solutions for the following

**CLI install scripts:**
cc @gerhard

Linux shell:
guessing we're leaving env vars alone but will script go from _current_ to _new_?
```
current: curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.2.19 sh
new?: curl -L https://dl.dagger.io/dagger-cue/install.sh | DAGGER_VERSION=0.2.19 sh
```
Powershell:
will we move from _current_ to _new_?
```
current: $script = Invoke-WebRequest -UseBasicParsing -Uri https://dl.dagger.io/dagger/install.ps1
new?: $script = Invoke-WebRequest -UseBasicParsing -Uri https://dl.dagger.io/dagger-cue/install.ps1
```
and update this:
```
Without passing in the `-InstallPath`, We'll save everything under `<your home folder>\dagger-cue`

C:\<your home folder>\dagger\dagger-cue.exe
```

**Will these paths continue to work in CUE files?:**
cc @aluzzardi 
```
import (
    "dagger.io/dagger"
    "universe.dagger.io/alpha/aws/sam"
)
```

**GitHub action:**
https://github.com/dagger/dagger-for-github
https://github.com/dagger/dagger-for-github/issues/75
We'll probably want to list a new action in the GitHub Marketplace called `dagger-cue-for-github` and then deprecate `dagger-for-github` and point to new one, but leave it in place to not break folks using it. cc @crazy-max 
```
uses: dagger/dagger-for-github@v3
...
cmds: |
            project update
            do deploy
```

**Version script used in some docs pages:**
```
<DaggerVersionLatestReleased>
{daggerVersionLatestRelease =>
<>Now check all the available packages in <a href={`https://github.com/dagger/dagger/tree/${daggerVersionLatestRelease}/pkg/universe.dagger.io`}>universe.dagger.io</a>.</>
}
</DaggerVersionLatestReleased>
```
**Homebrew for Mac/Darwin:**
assuming will be `brew install dagger-cue`

**Windows**:
related: https://github.com/dagger/dagger/issues/3484

```
https://community.chocolatey.org/packages/dagger-cue
choco install dagger-cue
```
 &
```
https://scoop.sh/#/apps?q=dagger-cue
scoop bucket add main # If you don't have the main bucket added yet
scoop install dagger-cue
```

**CLI Env Vars:**
Guessing we won't change ENV VARs like `DAGGER_PLAN`, `DAGGER_CACHE_FROM`
 cc @gerhard 

<hr/>

Can cherry pick from here:
https://github.com/dagger/dagger/pull/3431/commits/19f4e9335fa784864f8ec66df10bacd1c5cc3265

Tracking work here:
I made a fresh clone of `dagger/dagger`, switched to @vikram-dagger 's multi-site PR and added a `docs/v0.3/sdk/cue` directory.

I moved the contents of 0.2 docs in there: from `sdk`: `cp -R  ~/src/dagger-fork/docs/v0.2/* cue/.`

I then started moving \`dagger\` to \`dagger-cue\`:

```
sed -i.bak -e 's/\`dagger\`/\`dagger-cue\`/g' **/*.md*
<commit>
sed -i.bak -e 's/dagger do/dagger-cue do/g' **/*.md*
rm **/*.bak.bak
<commit>
sed -i.bak -e 's/dagger project init/dagger-cue project init/g' **/*.md*
rm **/*.bak.bak
<commit>
sed -i.bak -e 's/dagger project update/dagger-cue project update/g' **/*.md*
rm **/*.bak.bak
<commit>
etc
```

**Comment by jpadams** [comment]
Need solve for:
`curl -L https://dl.dagger.io/dagger/install.sh | sh`

**Comment by jpadams** [comment]
should update version of Dagger-Classic in `1222-core-actions-reference.md` to latest

**Comment by jpadams** [comment]
maybe move `CUE API` -> `CUE SDK` where it appears in a few places like in
`docs/v0.3/sdk/cue/core-concepts/1213-dagger-cue.md`

**Comment by jpadams** [comment]
should look to see if still links back to `0.1 docs` and remove

**Comment by jpadams** [comment]
@vikram I pushed edits to your 3440-sdk-aware-docs branch that's part of PR 3464. I didn't put them in the right place (docs/v0.3/sdk/cue), I'm sure. Looks like they'll end up under websites/docs-sdk-cue/docs ?? Likely need to sync with you on that and on common and sidebars.js.

**Comment by jpadams** [comment]
I've use `Dagger-Classic` is any place where a decision needs to be made between `the Dagger Engine` or `Dagger Engine`. There should be hardly any (or none) that need to be turned into `dagger-cue`.

**Comment by jpadams** [comment]
Removing Buildkit customization docs for now to leave room for future "Dagger Engine operator manual".

**Comment by jpadams** [comment]
TODO: remove  https://devel.docs.dagger.io/1243/dagger-cloud from sidebar in new CUE SDK site

**Comment by jpadams** [comment]
Need to watch out for inter-docs links like: https://docs.dagger.io/1227/contributing/ linked to in use-cases/1248-aws-sam.md

**Comment by gerhard** [comment]
There are a lot of relevant changes for this in https://github.com/dagger/dagger/issues/3474

There is a follow-up PR coming up shortly which bumps the version from `0.1.0` to `0.2.232` as discussed in this [(private) Discord thread](https://discord.com/channels/707636530424053791/1034332524425527356/1034408871063715870).

Doing a quick pass:

```diff
# New:
+ curl -L https://dl.dagger.io/dagger-cue/install.sh | sh

# VERSION instead of DAGGER_VERSION is also new:
+ curl -L https://dl.dagger.io/dagger-cue/install.sh | VERSION=0.2.232 sh

# Powershell URL is also new:
+ new?: $script = Invoke-WebRequest -UseBasicParsing -Uri https://dl.dagger.io/dagger-cue/install.ps1
# Yes, it behaves as you have assumed
```

- Yes, paths should continue working in CUE files AFAIK
- Keep GitHub Action as is until we have `dagger-cue v0.3.x` (there is also the new `dagger v0.3.x` CLI to consider that we don't know everything about just yet https://github.com/dagger/dagger/issues/3347)
- I missed the docs version script, the gotcha is the `sdk/cue/v<version>` tag
- Homebrew **bottle** will need (deprecating) versioning (I'm thinking `dagger@0.2`) but this is a bigger topic https://github.com/dagger/dagger/issues/3484#issuecomment-1290333787
- Same for Scoop / Chocolatey 👆
- `brew install dagger/tap/dagger-cue` works as expected → https://github.com/dagger/dagger/issues/3474
- Yes, `dagger-cue` env vars continue working as before, `DAGGER_PLAN`, etc.

**Comment by jpadams** [comment]
For future, we should also consider arch linux.
