### ISSUE TITLE
Inform chocolatey and scoop of new `dagger-cue` cli

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#3484]
`dagger-cue` is the new Dagger binary for running Dagger CUE plans. It is at version `0.2.232` at the time of this writing. @piraces has created a `dagger-cue` Choco package. Thanks so much!
https://community.chocolatey.org/packages/dagger-cue/

<hr/>

Up until now,`dagger` packages for Choco and Scoop have been maintained by @piraces and @vardrop respectively. Thank you both! The last version is `0.2.36`. No updates are expected and the `dagger` cli may be deprecated/repurposed in the future.

 `dagger` Choco repo here: https://github.com/piraces/chocolatey-packages/tree/main/automatic/dagger
https://community.chocolatey.org/packages/dagger

`dagger` ScoopInstaller repo here: https://github.com/ScoopInstaller/Main/blob/master/bucket/dagger.json
https://scoop.sh/#/apps?q=dagger&s=0&d=1&o=true

**Comment by vardrop** [comment]
This only affects the name of the package or installer not the contents of GitHub releases, right?

**Comment by jpadams** [comment]
> This only affects the name of the package or installer not the contents of GitHub releases, right?

@vardrop I believe that's correct.

**Comment by piraces** [comment]
Hello! So if I understand it right, the package its going to to be named `dagger-cue` instead of `dagger`? And the repo name its going to be changed?

If so, I can make the changes quickly in the repo once the new release it's ready with the new name.

Nevertheless, I think since the package changes its name it will be passed through moderation for a longer time (actually its trusted by Chocolatey moderators and each version of dagger goes upstream very quick)... I will contact the Chocolatey community to gain knowledge about how to make this changes.

**Comment by gerhard** [comment]
I would hold off making this change.

The current plan is to:
- transition `dagger` CLI v0.2.x into maintenance
- introduce `dagger-cue` v0.3.x - somewhat similar to `dagger` v0.2.x
- introduce the new `dagger` CLI v0.3.x (we still need to figure a bunch of things out https://github.com/dagger/dagger/issues/3347)

`dagger` CLI `v0.2.x` will continue working as is. We don't intend to publish any new versions, but we can if we need to.

The maintenance transition needs to happen across a bunch of package manages, including HomeBrew (the most popular one), Chocolatey, Scoop & possibly others that I don't know about just yet - FWIW https://cs.github.com/?scopeName=All+repos&scope=&q=go.dagger.io

`dagger-cue` in its current form (`v0.2.x`) is temporary. As soon as @jlongtine is finished with his implementation on top of the `v0.3.x` Dagger Engine, we will know more.

`dagger` CLI `v0.3.x` is a completely new beast, and my opinion is that we shouldn't be introducing any changes to the existing `v0.2.x` CLI, especially in package managers such as Scoop / Chocolatey / Homebrew, until we are clear on what is happening with `v0.3.x`. If we start making changes before everyone on our side is clear with the next 10 steps, the risk which I see is confusing everyone else. If reading the above was confusing, then consider it a preview for how everyone else will feel when other changes will start flowing **if** we act on this Scoop / Chocolatey change in the next few weeks.

Leaving this with you @shykes @samalba @aluzzardi. Back in 1 week 🏝

**Comment by shykes** [comment]
Correct, do not rename downstream `dagger` packages. If there is a `dagger-cue` package it should be a brand new one.

**Comment by piraces** [comment]
Thank you all for the information! I will try to create a `dagger-cue` package 👍

**Comment by grouville** [comment]
> Thank you all for the information! I will try to create a `dagger-cue` package 👍

Hi @piraces,
Can I help on any way ?

**Comment by piraces** [comment]
Thank you @grouville for your willingness to help!
For now, I will investigate the current `install.ps1` script from dagger and check how to approach it with chocolatey.

I will let you know if I need help 👍

**Comment by piraces** [comment]
Hi @jpadams ! I just published the `dagger-cue` package to chocolatey: https://community.chocolatey.org/packages/dagger-cue/
I based the automatic script to update versions in chocolatey in your `install.ps1` script.

Note that Chocolatey has a large queue for moderation of newer packages, but it will become listed in some days.

If I understood well, then there will be not another release of the `dagger` (classic) package? All the new releases will be of `dagger-cue`?

Thanks for all! 👍

**Comment by jpadams** [comment]
Sent email to arch linux maintainer to inform about changes as well.
https://archlinux.org/packages/community/x86_64/dagger/
