### ISSUE TITLE
Copy edit Go SDK get started

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#3502]

**Comment by vikram-dagger** [comment]
Copy edit the get started guide

**Comment by vikram-dagger** [comment]
Additional feedback from Discord https://discord.com/channels/707636530424053791/1034373947040477204/1034373947040477204

Go SDK - Getting started
- If the Step 1 first step is a duplication of "Installation" section, is it useful to keep it? Or it may be better to just include Installation in the getting started?
- Coding style is not consistent, sometime there are space between comments, sometime not
- "In this step, create the main function that the tool will run": "First, let's create the main function that the CI will run"
I do not like the naming "the tool will...". I think using a more specialised word like "Go CI" is more accurate and help to keep a context.
- "just creates a dagger client with dagger.Connect()": you could add a link to the dagger.Connect() method on GoPkg 😉
- Substep numbers in Steps are always 1, Why?
- Sometime you use first letter in Uppercase in list, sometime lowercase, be consistent
- There are comments in code snippets + explanation below in a list. I think there shall be only 1 source of explanation, either as comments or explanations but not both. Because if I read the comment in snippet, I will think I have understand everything and not read the full explanation, and then lose a lot of important information IMO. (It's just psychological though)
- "In the output of this command, you will see Dagger cloning the git repo and running go build on it.": Show it? Is there anything to do in case that doesn't work?
- "Save the file once done": I'm not sure it's useful to write it. It adds content to read that is not really essential and cut the lecture.
- "The output of the tree command will show you the built artifact on your machine at build/greetings-api.": Show it 🙂
- "Many applications need to be distributed to users on a variety of systems" I would love to see a quick simple schema of this, that would produce a "woah" effect and help new people with less experience to understand what's happening.
- I see a lot of repetitions like "Another common operation that might happen in a CI environment is targeting multiple Go versions. In this step the tool will be updated to build the git repo with multiple Go versions.". I think this can be reduce in one concise sentence.
- I really like this tutorial, but I think make more concise sentence will help the lecture. There are lot of text to read, some are very useful but some are just repetitions. I think more graphical things and less text could have the same effect.
- Step 5 and Step 6 looks independents and unrelated, it looks more like "bonus" step or "to go further".

**Comment by vikram-dagger** [comment]
General comment that this PR restructures the get started guide, so some of the references below may not be valid any longer.
 
> Go SDK - Getting started
> 
>     * If the Step 1 first step is a duplication of "Installation" section, is it useful to keep it? Or it may be better to just include Installation in the getting started?

I believe it is useful to keep the installation steps within the get started guide, to save the user the additional clicks of going to a different page, following a separate set of instructions and returning to the guide.

>     * Coding style is not consistent, sometime there are space between comments, sometime not

Corrected in PR.

>     * "In this step, create the main function that the tool will run": "First, let's create the main function that the CI will run"
>       I do not like the naming "the tool will...". I think using a more specialised word like "Go CI" is more accurate and help to keep a context.

Corrected in PR, using "Go CI tool" wherever it makes sense to do so.

>     * "just creates a dagger client with dagger.Connect()": you could add a link to the dagger.Connect() method on GoPkg wink

I've opened a separate discussion for this in https://github.com/dagger/dagger/issues/3580

>     * Substep numbers in Steps are always 1, Why?

Corrected in PR, list numbering should now be correct but please lmk if you still see this issue.

>     * Sometime you use first letter in Uppercase in list, sometime lowercase, be consistent

Corrected in PR
 
>     * There are comments in code snippets + explanation below in a list. I think there shall be only 1 source of explanation, either as comments or explanations but not both. Because if I read the comment in snippet, I will think I have understand everything and not read the full explanation, and then lose a lot of important information IMO. (It's just psychological though)

My subjective opinion but I think it is useful to have both. Some readers prefer to read code comments, others prefer the text explanation. We should meet readers where they are rather than force them to a specific approach.
 
>     * "In the output of this command, you will see Dagger cloning the git repo and running go build on it.": Show it? Is there anything to do in case that doesn't work?

I will ask @kpenfound to comment on this.
 
>     * "Save the file once done": I'm not sure it's useful to write it. It adds content to read that is not really essential and cut the lecture.

Corrected in PR (removed)
 
>     * "The output of the tree command will show you the built artifact on your machine at build/greetings-api.": Show it slightly_smiling_face

Corrected in PR, output added

>     * "Many applications need to be distributed to users on a variety of systems" I would love to see a quick simple schema of this, that would produce a "woah" effect and help new people with less experience to understand what's happening.

I am not sure what you mean by "schema" here. Can you please add more information?
 
>     * I see a lot of repetitions like "Another common operation that might happen in a CI environment is targeting multiple Go versions. In this step the tool will be updated to build the git repo with multiple Go versions.". I think this can be reduce in one concise sentence.

Corrected in PR.

>     * I really like this tutorial, but I think make more concise sentence will help the lecture. There are lot of text to read, some are very useful but some are just repetitions. I think more graphical things and less text could have the same effect.

Corrected in PR, tried to reduce sentence verbosity where feasible.
 
>     * Step 5 and Step 6 looks independents and unrelated, it looks more like "bonus" step or "to go further".

These steps have been restructured so perhaps the connection is clearer now. Happy to get more feedback on this one.

**Comment by TomChv** [comment]
> > Go SDK - Getting started
> > ```
> > * If the Step 1 first step is a duplication of "Installation" section, is it useful to keep it? Or it may be better to just include Installation in the getting started?
> > ```
> 
> I believe it is useful to keep the installation steps within the get started guide, to save the user the additional clicks of going to a different page, following a separate set of instructions and returning to the guide.

I was thinking about removing the `Installation` page since instructions already exist in `Getting Started` and then you can just add a quick link to jump to the instruction page in the Overview.


> > ```
> > * "Many applications need to be distributed to users on a variety of systems" I would love to see a quick simple schema of this, that would produce a "woah" effect and help new people with less experience to understand what's happening.
> > ```
> 
> I am not sure what you mean by "schema" here. Can you please add more information?

I was thinking about a more illustrated explanation of what do you mean by distributing a system to a variety of systems.
Here's an example schema that I draw quickly.

![dagger-multi-platform-schema-example](https://user-images.githubusercontent.com/61683879/198407001-f3a270a9-88c5-48ad-9690-d4a95ab6ca30.png)

> > ```
> > * Step 5 and Step 6 looks independents and unrelated, it looks more like "bonus" step or "to go further".
> > ```
> 
> These steps have been restructured so perhaps the connection is clearer now. Happy to get more feedback on this one.

I love your example! That's powerful!

**Comment by vikram-dagger** [comment]
> I was thinking about removing the `Installation` page since instructions already exist in `Getting Started` and then you can just add a quick link to jump to the instruction page in the Overview.

We would like to maintain a separate installation page for Go users who are already familiar with the SDK (maybe from previous use) and just need a quick snapshot of how to install it and move on with their project. Such users might not appreciate having to read through the introductory content of the get started guide just to locate the installation steps. 

Also, to some extent, this is driven by convention: most SDKs (not just Go) usually have a separate installation page and consequently, developers would expect to find this in our docs.
 
> > > ```
> > > * "Many applications need to be distributed to users on a variety of systems" I would love to see a quick simple schema of this, that would produce a "woah" effect and help new people with less experience to understand what's happening.
> > > ```
> 
> I was thinking about a more illustrated explanation of what do you mean by distributing a system to a variety of systems. Here's an example schema that I draw quickly.
> 
> ![dagger-multi-platform-schema-example](https://user-images.githubusercontent.com/61683879/198407001-f3a270a9-88c5-48ad-9690-d4a95ab6ca30.png)

Thanks, this clarifies your comment and IMO is a good idea. Ping @kpenfound to get his opinion on adding a similar diagram to this guide.
 
> > > ```
> > > * Step 5 and Step 6 looks independents and unrelated, it looks more like "bonus" step or "to go further".
> > > ```
>
> I love your example! That's powerful!

Thanks, and thanks also for the feedback and the collaboration on improving this guide!
