### ISSUE TITLE
Edit CUE SDK get started guide

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#3503]

**Comment by vikram-dagger** [comment]
Update the CUE SDK as follows:
- single page
- step 1..n structure
- other changes for consistency with Go SDK guide structure

**Comment by shykes** [comment]
Works for me @vikram-dagger I say let's see if in a PR, and we can fine tune. In general 1) less is better, 2) simpler is better, 3) we can always add stuff back in later.
