### ISSUE TITLE
Document docs deployment process

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#3542]
Document how the docs are deployed both to docs.dagger.io and devel.docs.dagger.io, so that everyone in the team is aware of the process.

**Comment by mircubed** [comment]
One thing that I want to understand from this internal documentation - how do we ensure that something is pushed to production after it is merged? Merging doesn't mean that it is live, so idk how we track which is live or not.

**Comment by mircubed** [comment]
@vikram-dagger did you need anything to help move this forward, or can I remove the "stuck" status?
