### ISSUE TITLE
✨ Restore Dagger-cue's like pretty / animated pipeline process as a pluggable output

### ISSUE THREAD

**Issue by talios** [dagger/dagger#3553]
### What are you trying to do?

One of the nice things I found with the earlier 0.2 cue based dagger, was the clean "pretty printed" progress display of ones pipeline - esp when running in a terimal.

![image](https://user-images.githubusercontent.com/19093/197964122-537a98dd-eadd-4f8a-9299-ace39224776b.png)

When experimenting with the new Dagger Go SDK - the debug process output is nice for debugging, and would be preferred when running from a CI build, or when wishing to debug a pipeline locally:

```
#6 [build 1/6] FROM docker.io/library/golang:1.18.2-alpine@sha256:4795c5d21f01e0777707ada02408debe77fe31848be97cf9fa8a1462da78d949
#6 resolve docker.io/library/golang:1.18.2-alpine@sha256:4795c5d21f01e0777707ada02408debe77fe31848be97cf9fa8a1462da78d949 0.0s done
#6 DONE 0.0s
```

Since the current `dagger.WithLogOutput(os.Stdout)` logger is raw output, I presume some additional form a dagger listener ( most likely powered by a GraphQL subscription ) would be used?

### Why is this important to you?

Cosmetics help sell adoption. Whilst dagger is primarily a programmable pipeline, not everyone who will run the pipeline interactively may want, or need to know the full structure /internal implementation the pipeline.

I can see this in the examples of multi-arch/multi-os/multi-go-version matrix builds - a complex pipeline may have a lot of under-the-covers logging that can distract a developer who only cares about why their build failed - and not why the pipeline failed.

**Comment by jedevc** [comment]
Our TUI output has changed a *lot* since this version of dagger.

We support `--progress=plain` to enable the older style of output that might be more useful for debugging, as well as new verbosity flags - `-v`/`-vv`/`-vvv`.

I'm going to close this issue, since the TUI from this issue is now no longer supported, and been replaced with a more span-focused approach :tada:
