### ISSUE TITLE
404s on source files, in `pkg.go.dev`

### ISSUE THREAD

**Issue by grouville** [dagger/dagger#3556]
Source files shown at https://pkg.go.dev/dagger.io/dagger#section-sourcefiles lead to 404s.

example:
- [error.go](https://github.com/dagger/dagger/tree/main/sdk/go/blob/v0.3.1/error.go)

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/31691250/198033312-46d85387-7895-4b5d-a93b-c82f5439fb99.png">

I tried to understand/reverse with @helderco, but did not manage to find how/where to fix (seems related to releases):
- The Repository link in picture above
[github.com/dagger/dagger/tree/main/sdk/go](https://github.com/dagger/dagger/tree/main/sdk/go) links to a main branch
- the `error.go` URL links to [github.com/dagger/dagger/tree/main/sdk/go/blob/v0.3.1/error.go](https://github.com/dagger/dagger/tree/main/sdk/go/blob/v0.3.1/error.go)

We see that the `error url` == `repository url` +  `blob/v0.3.1/error.go`, however, this file is not present in `v.0.3.1` on [dagger/dagger repo](https://github.com/dagger/dagger/blob/v0.3.1/sdk/go/error.go)

It does exist on [main though](https://github.com/dagger/dagger/blob/main/sdk/go/error.go), and in [go-dagger-skd](https://github.com/dagger/dagger-go-sdk/blob/v0.3.1/error.go) on `v.0.3.1`

cc @aluzzardi @vito @sipsma

**Comment by dolanor** [comment]
You can access it here: https://github.com/dagger/dagger/blob/sdk/go/v0.3.1/sdk/go/error.go
I guess the pkg.go.dev doesn't correctly write the full path if the `go.mod` is not on top of the repo. It just adds the relative path from the `go.mod` instead of adding the relative path from the repo root.
We should report it upstream.

**Comment by dolanor** [comment]
It didn't seem this issue was reported earlier, so I did: https://github.com/golang/go/issues/56666

**Comment by grouville** [comment]
@aluzzardi, in order to make this advance. Our current `go-source` and `go-import` are composed of such:
```
     <meta
      name="go-import"
      content="dagger.io/dagger git https://github.com/dagger/dagger-go-sdk"
    />
    <meta
      name="go-source"
      content="dagger.io/dagger     https://github.com/dagger/dagger/tree/main/sdk/go https://github.com/dagger/dagger-go-sdk/tree/main{/dir} https://github.com/dagger/dagger-go-sdk/blob/main{/dir}/{file}#L{line}"
    />
```

I don't recall the reason why we are referencing the `dagger-go-sdk` on the `go-import` (cf. [comment](https://github.com/golang/go/issues/56666#issuecomment-1320383541))
