### ISSUE TITLE
Unclear Go Chaining API

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3563]
### What is the issue?

[Discord Reference for context](https://discord.com/channels/707636530424053791/1034734239675068458)

Request: 

> Been diving a little more into the golang sdk now that it's stabilized somewhat, and I've found the chaining syntax a bit... unintuitive.
> 
> Initially, it's just not very clear what actually executes the GQL, but ultimately I've figured out - just find whatever takes a context. This strategy has worked a fair amount, but see below, this was was quite confusing.
> 
> Trying a simple docker build, the below compiles and runs with no errors. The only issue, it's not actually running anything.

> I'm thinking I might have a lack of conceptual understanding for the underlying types. It might be cool to have docs answering questions like 
> * When would I want to use/pass dagger.Directory vs dagger.DirectoryID
> * What does each of these represent when it comes to GQL? Prior versions would print the GQL, but I'm not sure how to access that right now.
> * What do these types represent when it comes to the underlying buildkit execution?

**Comment by mircubed** [comment]
@marcosnils @crjm maybe this context could be incorporated into the API playground experience too?

**Comment by crjm** [comment]
@mircubed  It would be great, but right now the doc is generated from the schema programmatically. We could try to add context in our own implementation of the Playground when we stop leveraging on the GraphiQL component we are using right now.
I think adding comments in the schema would be an easy way to add context though, but don't know how feasible it is. @aluzzardi

**Comment by mircubed** [comment]
@crjm @marcosnils do you think we can add this context to the docs now as an FYI in the GraphQL docs?

**Comment by crjm** [comment]
I think this is related to best practices and how-to guides, is it something we should delegate to the core team @marcosnils? I don't have the knowledge to answer these questions yet.

**Comment by shykes** [comment]
Reading the original discord thread, the root cause is a confusing DX in the early versions of the Go SDK, specifically with chaining. I added quotes from the original request above to make this more apparent.

The Go SDK has since greatly improved in this area, in particular you don't need to access `DirectoryID` yourself anymore, chaining is done directly. So I would consider this issue solved.
