### ISSUE TITLE
✨ Build Args for Dockerfiles

### ISSUE THREAD

**Issue by stobias123** [dagger/dagger#3574]
### What are you trying to do?

Just trying to do a docker build within my dagger pipeline, can't see a way to pass in build args with `container.Build()`. 

I would think I could just pass in a struct of args to build. something like 

```
container.build( dagger.buildArgs{
  {"foo": "bar"},{"biz":"bang"}
} )
```

### Why is this important to you?

We have lots of multi-stage docker builds. Long term I can see a migration path to more efficient builds directly via dagger commands, but the immediate migration path would need to leverage existing builds.

### How are you currently working around this?

I'm not 😅

**Comment by jlongtine** [comment]
I know this is possible (we did it with v0.2/CUE), so should be very doable again. @sipsma, @vito, and @aluzzardi should have a better sense of when we can do it, though.

**Comment by Alvise88** [comment]
This feature can be used as a workaround to [forward ssh agent issue](https://github.com/dagger/dagger/issues/3581), example:


```
ARG SSH_KEY

# Adding ssh private key used to download private repos only and only if present
# If SSH KEY is not present, this dockerfile tries to use --mount=type=ssh
RUN if [ -n ${SSH_KEY+x} ]; then (mkdir -p /root/.ssh \
 && echo "    IdentityFile ~/.ssh/id_rsa" >> /etc/ssh/ssh_config \
 && echo "$SSH_KEY" > /root/.ssh/id_rsa \
 && chmod 400 /root/.ssh/id_rsa); fi
```

I think the structure ContainerBuildOpts can be modified in 

```go
type ContainerBuildOpts struct {
	Dockerfile string
	BuildArgs  map[string]string
}
```

following cue sdk contract.

**Comment by aluzzardi** [comment]
Bumpimg this as it came up another time recently.

@mircubed What label could we use to track user requests?

**Comment by shykes** [comment]
Note: @stobias123 really needs this. From discord today.

> Hey yall - I know there's open issues for this, but I just want to bump it.
> I'm making a push to use dagger in the new year at my company, build args will be critical during migration

**Comment by shykes** [comment]
FYI @stobias123 , @jlongtine is on it :) See #4207
