### ISSUE TITLE
Add links to pkg.do.dev docs in Go get started guide

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#3580]
### What is the issue?

We received the following feedback in this Discord thread  https://discord.com/channels/707636530424053791/1034373947040477204/1034373947040477204 for our Go getting started guide at https://docs.dagger.io/sdk/go/959738/get-started

 "just creates a dagger client with dagger.Connect()": you could add a link to the dagger.Connect() method on GoPkg

**Comment by vikram-dagger** [comment]
This is a good idea but I'm concerned we then need to maintain and update those links every time we release a new version of our Go SDK to pkg.go.dev. However I'm not sure about
- the frequency at which we will release
- whether a release will impact specific links to sections of the auto-generated API docs on pkg.go.dev

WDYT @sipsma @vito @kpenfound?

**Comment by AlvaroRaul7** [comment]
Hi, I can work on this!

**Comment by vito** [comment]
@vikram-dagger 

Links are pretty stable since they don't need to go to a specific version, e.g. https://pkg.go.dev/dagger.io/dagger#Connect

> whether a release will impact specific links to sections of the auto-generated API docs on pkg.go.dev

It might for backwards-incompatible changes, but we'd be updating the docs for that anyway, so I think this is OK.
