### ISSUE TITLE
✨  forward `ssh-agent` to build and run core operations

### ISSUE THREAD

**Issue by grouville** [dagger/dagger#3581]
### What are you trying to do?

A user was trying to build, inside Dagger, a Dockerfile containing an advanced buildkit feature: `mount=type=ssh` (relying on `llb.MountSSHSock`)

This `mount` option tells the Docker frontend to forward the ssh connection of the `ssh-agent` to the build step and execute some ssh commands with the forwarded ssh connection. We do not support it for the build and run operations (for now).

It is really useful, as it works locally, and with password protected ssh keys: 
1. You load it locally: `ssh-add yourkey`
2. You execute it
3. It forwards the ssh to BuildKit

We are already relying on this feature for git: https://github.com/dagger/dagger/blob/4f29d2d35d7b48efee9aadd009d62acf7bf840c7/core/core.schema.go#L86-L88

### Why is this important to you?

A user requested it: https://discord.com/channels/707636530424053791/1034907314869780510/1034907314869780510.

It seems natural to be able to support this feature on our `Container().Build()`. I think it lies inside our `core.build` implementation.

However, the user was trying to build using the `pants` build tool, inside a `docker.#Run` (dagger v0.2)

<img width="940" alt="image" src="https://user-images.githubusercontent.com/31691250/198414732-9912983a-ff72-4ef9-a7e6-e70c8202a2d5.png">

### How are you currently working around this?

The user managed to workaround it in Dagger v0.2 by forwarding the SSH_AUTH_SOCK.

However, I don't think it is possible in 0.3

**Comment by grouville** [comment]
Even though it seems to be an easy fix, it might add some `core.API` questions, if it gets optional: what does the option to forward the agent looks like in the core API

**Comment by marcosnils** [comment]
> , if it gets optional: what does the option to forward the agent looks like in the core API

`withMountedSSH` maybe?

**Comment by Alvise88** [comment]
This is quite useful for Dockerfile:

```dockerfile
RUN --mount=type=ssh go mod download
```

**Comment by sipsma** [comment]
Unix socket mounting should enable this now: https://github.com/dagger/dagger/pull/4025
