### ISSUE TITLE
Support `export` on `File`

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3599]
In terms of the implementation: Buildkit doesn't have builtin support exactly, but you can create the end effect by exporting an LLB state that contains just the file you are exporting. You'll need to use an LLB copy to isolate the file and to rename it to whatever the user wants it to be, but should work I think.

This should let us add `export` to the `File` object.

**Comment by marcosnils** [comment]
> In terms of the implementation: Buildkit doesn't have builtin support exactly, but you can create the end effect by exporting an LLB state that contains just the file you are exporting. You'll need to use an LLB copy to isolate the file and to rename it to whatever the user wants it to be, but should work I think.
> 
> This should let us add `export` to the `File` object.

does LLB copy requires the directory to exist beforehand? otherwise we'll have to some llb Mkdir magic to hide that and then clean up everything after we're done exporting since the user might still want to do something else with the container after exporting and we shouldn't leave the temporary stuff around.

**Comment by vito** [comment]
Done via #3348 

@marcosnils Not sure if this answers your question, but the [implementation](https://github.com/dagger/dagger/pull/3348/files#diff-697e59d3ff7c2e6c3c5cf6e9f101e51a1bb0df6a8843097641c0866c11d35690R129-R141) ended up being pretty straightforward, didn't have to make any dirs or anything.

**Comment by marcosnils** [comment]
> @marcosnils Not sure if this answers your question, but the [implementation](https://github.com/dagger/dagger/pull/3348/files#diff-697e59d3ff7c2e6c3c5cf6e9f101e51a1bb0df6a8843097641c0866c11d35690R129-R141) ended up being pretty straightforward, didn't have to make any dirs or anything.

it does. thx :pray:
