### ISSUE TITLE
Guide: building a Go program

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3615]
There should be a guide explaining how to build a Go program with Dagger. Note: this is different from building a docker container.

Benefits of having this guide:

* Seeing it in the list, clarifies to the user that this is something you can do
* Reading its content, helps you actually getting it done

**Comment by vikram-dagger** [comment]
@shykes @mircubed I believe this topic is already covered in:
- https://docs.dagger.io/sdk/go/959738/get-started/#step-4-create-a-single-build-pipeline
- https://docs.dagger.io/544174/multistage-build

Please let me know if OK to close?

**Comment by mircubed** [comment]
ok, to close!

**Comment by shykes** [comment]
Generally @vikram-dagger I defer to you on those kinds of decisions :)
