### ISSUE TITLE
Update user docs with multiplatform support

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3616]
At minimum: Update the getting started guide for go to show exporting a multiplatform image (in addition to current example of local filesystem export)

It would also be nice to show running binaries for different platforms via emulation (i.e. you want to test binaries you built for different platforms). We could either put this in the getting started guide too or we could have a separate guide that explores multiplatform support in greater detail on its own.

**Comment by mircubed** [comment]
dependent on #3119

**Comment by sipsma** [comment]
We merged docs for multiplatform support
