### ISSUE TITLE
Change buildkit container name to just "container" 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3620]
Before renaming, we need to confirm how we will explain it, which is tracked in #3595 

We need to replace that with dagger-standard terminology. This also applies to the container name (currently dagger-buildkitd, should be changed too. 

You can see where the user sees the name confusion here - https://www.youtube.com/watch?v=w-3K8in9jb4

**Comment by mircubed** [comment]
Change to from "buildkit container" to just "container"

**Comment by sipsma** [comment]
It's now called `dagger-engine-<engine image sha>`. Closing this as even though we didn't rename to `container` we did rename it to something that doesn't reference buildkitd anymore
