### ISSUE TITLE
Improve install and copy/paste from the getting started guide 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3621]
### What is the issue?

Feedback from this video: https://youtu.be/w-3K8in9jb4?t=904

@marcosnils feedback - 

Because he's not following the the docs by the line as he's an advanced Go developer, here he gets an error about `dagger `not being available as the dependency got removed when he did `go mod tidy` without having any code. Even though it's highlighted here (https://devel.docs.dagger.io/sdk/go/371491/install/), you can tell that he didn't read the message and went directly to the copy/paste snippet flow. I actually have two suggestions on how we could improve this:

1) Remove the `install `page (https://devel.docs.dagger.io/sdk/go/371491/install/) and merge it  with the `get started one`
2) In the `get started` page, have two very friendly copy/paste flows. One for adding dagger to an existing project, and another to start a project from scratch (current example). I feel we'll have several other users falling into the same confusion he did with the current doc structure.
3) Show how to replace a Dockerfile with Dagger

**Comment by mircubed** [comment]
@shykes @samalba  do you agree with the removing on the install page and merging with the Get started doc? I want to make sure that we have founder's approval before we make a change like that. cc @vikram-dagger

**Comment by kpenfound** [comment]
I think number 3 is https://github.com/dagger/dagger/issues/3426

**Comment by shykes** [comment]
> @shykes @samalba do you agree with the removing on the install page and merging with the Get started doc? I want to make sure that we have founder's approval before we make a change like that. cc @vikram-dagger

No.

**Comment by mircubed** [comment]
Ok since #1 is a "No" and #3 is covered in #3426 then I am going to close this issue and make one specifically to track #2

**Comment by mircubed** [comment]
moved #2 to #3628
