### ISSUE TITLE
Guide: lazy execution property

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3622]
### What is the issue?

feedback from Marcos regarding https://youtu.be/w-3K8in9jb4?t=904: 

We should add some docs about the lazy execution property once we finalize the API here: https://github.com/dagger/dagger/issues/3555. Seems like that often confuses users.

**Comment by mircubed** [comment]
related to #3617

**Comment by mircubed** [comment]
@jpadams will take a pass at this to get something started

**Comment by mircubed** [comment]
@aluzzardi to add quick summary of things to include

**Comment by mircubed** [comment]
related to #3623

**Comment by vikram-dagger** [comment]
This is explained in the API concepts guide https://docs.dagger.io/api/975146/concepts#lazy-evaluation
