### ISSUE TITLE
✨ Allow to invalidate cache for a complete pipeline or a step via the SDK

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#3626]
### What are you trying to do?

Force the pipeline to re-run some steps that would be cached otherwise.

### Why is this important to you?

Because dagger/buildkit has an opinionated way of caching that sometimes I want to override for specific tasks.

### How are you currently working around this?

Removing the buildkit container and volume which is not idea..

**Comment by sipsma** [comment]
Dupe of https://github.com/dagger/dagger/issues/3073
