### ISSUE TITLE
Transfer Go code in docs into separate files

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#3633]
Move code snippets inlined in markdown into their own files (e.g. docs/current/sdk/go/snippets) and import them back from markdown

**Comment by dolanor** [comment]
If possible, if we could make them testable, that would be great.
That would require to follow the Go example conventions, but also, to display only a subset of this snippets, to avoid showing all those Go example conventions.

ref: https://go.dev/blog/examples

**Comment by vikram-dagger** [comment]
This is currently being done so I believe this issue can be closed now.
