### ISSUE TITLE
Dump queries to a graphql document

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3635]
## Problem

When running pipelines from the Go SDK (and soon the Python and NodeJS SDKs), one can sometimes be unsure of what exactly is happening under the hood. This could be caused by inexperience (perhaps I am still learning Dagger), or debugging ("is the problem in my code? or at another layer?").

This problem is compounded when I need help from someone else. The only medium available for getting help is sharing my code, but that makes it difficult to reproduce. The person helping me may not have the environment necessary to build my code; they may not be familiar with my SDK of choice; my code may have unrelated business logic mixed in, or I may not be able to share it at all.

## Solution

I can instruct the Dagger Engine to export all GraphQL operations to a file, as they are sent. This file is a standard GraphQL document, which all GraphQL tools can natively load and use.

To trigger a graphql query export, the end user must set the environment variable `DAGGER_EXPORT_QUERIES=1`. This will write to the filename `dagger-export.gql` (insert bikeshedding here).

The resulting document can be used in several ways:

1. Read the document  to understand or verify what my code does
2. Copy-paste the document into the [API playground](https://play.dagger.cloud) and run it without modification3. 
3. Run any of the queries directly from the Dagger CLI, using its standard support for graphql documents4. 

## See also

#3561

**Comment by TomChv** [comment]
I definitely feel the need for this feature! Few weeks ago I struggle trying to write a Go Extension, something was wrong but I couldn't find what until  I replicate my query written using the Go extension in the GraphQL playground.

This was before changes on the Go SDK, may this error would have not happened with the recent DX but it's still an interesting debug feature IMO.

**Comment by shykes** [comment]
This is solved by new TUI + Dagger CLoud
