### ISSUE TITLE
Python SDK Documentation 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3639]
### What is the issue?

We will need the following for the Python launch. 

- New section in docs 
- Get Started Guide 
- API reference guide 
- Installation 

@helderco can help support as needed since he is Python SDK release lead.

**Comment by mircubed** [comment]
@kpenfound, @vikram-dagger is going to have this issue as his P1, so please let Vikram know if you are working on anything related to a getting started guide so y'all don't do double the work

**Comment by helderco** [comment]
On the **installation** instructions:

There's many ways to install python, multiple package managers and ways to manage virtual environments. Pythonistas should know this. We can say "on this guide we'll use x and y", but should be obvious that one can use whatever one's comfortable with. I leave to Vikram to add that note anyway.

Notes: 

- Need python 3.10
- Use poetry
  - Popular
  - Manages environment (simpler instructions)

Pseudo, high-level overview of steps needed for the guide:
1. brew install python[^1]
2. pip install pipx && pipx install poetry[^2]
3. mkdir, cd && poetry init
4. poetry add dagger.io (if not chosen during init above)
5. poetry shell
6. (insert first example)
7. python example.py
8. iterate on last two points

[^1]: Just link to python's guide on installing python, no need to give commands.
[^2]: Same as above, just refer to poetry's guide to install it.
