### ISSUE TITLE
NodeJS Documentation 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3640]
### What is the issue?

We will need the following for the NodeJS launch.
- New section in docs
- Get Started Guide
- API reference guide
- Installation
- FAQ

@slumbering  can help support as needed since he is NodeJS SDK release lead.

**Comment by mircubed** [comment]
@slumbering , Vikram will need guidance on best practices for the NodeJS API references

**Comment by mircubed** [comment]
@slumbering , @vikram-dagger will need this content by Thursday morning (your time), so he has time to create the guide on Friday. That way, @kpenfound can create the demo that is needed for the blog post promo since it is dependent on the getting started guide.

**Comment by mircubed** [comment]
@vikram-dagger as soon as the Python docs are out, this will be the next P1. France and US have holidays on Friday, so we'll need to ensure you get what you need tomorrow.

**Comment by slumbering** [comment]
We did sync with Vikram, but I didn't send him any content so far. 
I'll try to send something today.
