### ISSUE TITLE
✨ Dockerfile build args.

### ISSUE THREAD

**Issue by stobias123** [dagger/dagger#3655]
### What are you trying to do?

Use build args.

### Why is this important to you?

easier transition towards dagger. dockerfiles are a good middleground between native dagger and our exiting dockerfile setup.

### How are you currently working around this?

I dont :(

**Comment by marcosnils** [comment]
@stobias123 is this the same as? https://github.com/dagger/dagger/issues/3574. Seems like a dupe to me.

**Comment by stobias123** [comment]
yeah not sure what happened here, happy to close out!
