### ISSUE TITLE
✨ Include .git in the Go SDK client Git

### ISSUE THREAD

**Issue by jaredpatrick37** [dagger/dagger#3657]
### What are you trying to do?

I am implementing a conventional commit task and I require the .git directory to be present in my cloned repo so that I can generat a new semantic release,

### Why is this important to you?

Having access to the git metadata is useful for any tasks that need more information than just the source files.

### How are you currently working around this?

The current workaround is to handle the `git clone` in a container via exec.

**Comment by jpadams** [comment]
@aluzzardi @vito @sipsma 
https://discord.com/channels/707636530424053791/1037710136346685460/1037710136346685460

**Comment by samalba** [comment]
Requested here as well: https://discord.com/channels/707636530424053791/1042334329625399296/1042334329625399296

**Comment by aluzzardi** [comment]
This was already implemented in #3660 by OP (@jaredpatrick37). However, we haven't released a Go SDK version yet.
