### ISSUE TITLE
API: lookup git commit

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3664]
## Problem

The Dagger API supports pulling a remote git repository 1) by branch (`git { branch }`) and 2) by tag (`git { tag }`), but not by commit.

Initially reported [on discord](https://discord.com/channels/707636530424053791/1037789606134939758)

## Solution

Add a new field to the API `git { commit }`

Under the hood it's all refs, but it's better to have a dedicated field for each, to be closer to the actual intent of the developer, and adapt the wording.

**Comment by marcosnils** [comment]
I had to use the `git` API recently and got surprised that I **needed** to specify either a branch or a tag. When doing `git clone` usually the server returns the default branch the HEAD points to, so I was hoping that I didn't need to specify it. Not sure if that's required in the buildkit API. cc @sipsma ?

**Comment by shykes** [comment]
It’s not required. I don’t mind adding `ref` too.

**Comment by marcosnils** [comment]
> Yes it is required @marcosnils .

Was just checking the code. Doesn't seem like it? https://github.com/moby/buildkit/blob/master/client/llb/source.go#L240-L242

**Comment by shykes** [comment]
> > Yes it is required @marcosnils .
> 
> Was just checking the code. Doesn't seem like it? https://github.com/moby/buildkit/blob/master/client/llb/source.go#L240-L242. IIUC `ref` can be empty in buildkit. I'd assume that automatically picks the `git` default branch

Wow, you’re right! Here’s the underlying implementation: https://github.com/moby/buildkit/blame/master/source/git/gitsource.go#L715

I had no idea. I guess I should have read the docs! (just kidding there are no docs).

So yes it appears we can have a default branch: now to decide the API for it :)

**Comment by shykes** [comment]
> I had to use the `git` API recently and got surprised that I **needed** to specify either a branch or a tag. When doing `git clone` usually the server returns the default branch the HEAD points to, so I was hoping that I didn't need to specify it in Dagger. Not sure if that's required in the buildkit API. cc @sipsma ?

I moved this discussion to a new issue: https://github.com/dagger/dagger/issues/3670
