### ISSUE TITLE
Create visible changelogs per SDK 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3667]
We need a changelog, but we need to determine the how and where first. Once we have this, we can work on creating it. 

Does the changelog cover each SDK or Dagger overall? 
We have confirmed that we want it to be per SDK 

Where does it live and how is it updated? 
TBD 

@vikram proposal - section is under each SDK category in docs. The format could follow this:  https://gist.github.com/juampynr/4c18214a8eb554084e21d6e288a18a2c or https://keepachangelog.com/en/1.0.0/

@gerhard proposal - We should use GoReleaser for this, same as we used to do for the dagger CLI.
Until we get that going, this is decent: gh release create sdk/go/v0.4.0 --generate-notes --notes-start-tag sdk/go/v0.3.1 --draft
https://github.com/dagger/dagger/releases/tag/untagged-1a1d88e2402de602d145 - we will need to clean some of these, but it's a good starting point

Who creates the summary?  
Engineering at each release

**Comment by mircubed** [comment]
@gerhard @vikram-dagger I will let you take the lead on concluding where these will live and how they will stay updated.

**Comment by gerhard** [comment]
@aluzzardi should we generate the release notes for the Go SDK `v0.4.0` in this repo? e.g. https://github.com/dagger/dagger/releases/tag/untagged-1a1d88e2402de602d145

```
gh release create sdk/go/v0.4.0 --generate-notes --notes-start-tag sdk/go/v0.3.1 --draft
```

**Comment by aluzzardi** [comment]
@gerhard Definitely

I don't know though how to filter commits for sdk/go -- otherwise it'll include commits for engine (not **too** bad) and Python/Node (really bad)

**Comment by samalba** [comment]
Assigning to you @gerhard (removing @vikram-dagger). Moving this to P2, but feel free to bump the priority if it's likely to happen in short-term.

**Comment by samalba** [comment]
Given we now generate release per SDK and they have a generated changelog, I think we could close this issue?

**Comment by mircubed** [comment]
Yes, we can close this since this is already done today.
