### ISSUE TITLE
API: use default branch when pulling a git repository

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3670]
## Problem

As reported by @marcosnils :

> I had to use the git API recently and got surprised that I needed to specify either a branch or a tag. When doing git clone usually the server returns the default branch the HEAD points to, so I was hoping that I didn't need to specify it in Dagger. Not sure if that's required in the buildkit API?

After further research, buildkit does in fact support this:

> https://github.com/moby/buildkit/blob/master/client/llb/source.go#L240-L242. IIUC ref can be empty in buildkit. I'd assume that automatically picks the git default branch
> Here’s the underlying implementation: https://github.com/moby/buildkit/blame/master/source/git/gitsource.go#L715

## Solution

Allow pulling from a remote git repo without specifying a branch.

API design: TBD

**Comment by shykes** [comment]
@marcosnils do you know if this is still an issue?

**Comment by jedevc** [comment]
Yup, this is still an issue - it's just not possible from an API perspective.

Calling `dag.Git` gets you a `GitRepository` - but then you need to call `Branch()`/`Commit()`/`Ref()` etc, to get a `GitRef` - which is what you can call `Tree` on.

Some API ideas to resolve this:
- We add a `Head()` method with no args to `GitRepository`, which just returns a `GitRef` with the default branch
- Or we could merge `GitRepository` and `GitRef` together? Then you don't need that extra step at all (maybe we could even rename the methods to `WithBranch`/etc).

**Comment by shykes** [comment]
We could add a `GitRepository.defaultBranch()` function, that returns the default branch as defined by the remote?

**Comment by jedevc** [comment]
Slightly related, found while searching: https://github.com/dagger/dagger/issues/3670
