### ISSUE TITLE
docs: URL previews are broken

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#3688]
Somehow URL previews of the docs show the internal code rather than the rendered content

<img width="671" alt="Screen Shot 2022-11-04 at 12 00 12 PM" src="https://user-images.githubusercontent.com/179503/200054536-99fdec4a-b355-4607-b4e2-52306b6d1105.png">

/cc @vikram-dagger @slumbering @crjm

**Comment by vikram-dagger** [comment]
Already tracking this in https://github.com/dagger/dagger/issues/3681 :)

**Comment by aluzzardi** [comment]
Whoops!
