### ISSUE TITLE
Support sync

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#3689]
## Context

To move faster, sync support was put on pause.

It’s a bit of a pain to support both sync and async. NodeJS comes with an event loop built-in but in Python it’s optional. It’s easy to just spin an event loop in a sync environment to run async dagger, but not the inverse. 

If we start with only sync support then you can’t run tasks concurrently and you can’t use dagger in an async environment otherwise it’ll block your event loop.

## Todo

- [x] Figure out execution on leaves (i.e., how to make API client support both DRYly?)
- [x] #3686
- [ ] Documentation?
  - Async has more capabilities
  - Default to async in all examples
  - Have one section on sync with note and differences

**Comment by helderco** [comment]
@vikram-dagger re: documentation on this, there's an example in https://github.com/helderco/dagger-examples/blob/main/say_sync.py. As you can see you just remove the `async` and `await` keywords, and also the event loop (i.e., `anyio.run`).

We can have a section in the docs alluding to this or not add it and see if people ask for it.

**Comment by vikram-dagger** [comment]
The get started guide examples currently use async. Is that OK, or do we want to change to use sync in all those examples?

**Comment by helderco** [comment]
No, I'd rather use `async` by default as much as possible. It's more powerful in async since you can do concurrency for example, you can use them in both sync and async environments and it's simple enough compared to sync. Just need the event loop and the async/await keywords.

The sync support is only there because we don't know if some people will be off put if it's not there. For those people we can either leave a short section saying we support it and how to convert from an async example, or we can just not include it and see what people say. If they ask for it we could add it later.

In the examples repo there's a sync example anyway. That could be enough. Wdyt?
