### ISSUE TITLE
Connect to engine via unix socket

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#3694]
It's useful for testing and allows the future extension runtime to not require [socat](https://github.com/dagger/dagger/issues/3370).

Depends on:
- https://github.com/dagger/dagger/issues/3693

**Comment by aluzzardi** [comment]
@helderco Alternatively, we can make sure SDKs never have to use unix sockets, TCP only.

**Comment by helderco** [comment]
This is not for the current milestone and I believe it's easy work so I can give more feedback at the time. I like the simplicity of the socket.

**Comment by helderco** [comment]
Implemented in https://github.com/dagger/dagger/pull/3983/commits/8a222804da5ddf3e7ec4c80b9e639deb3b25bf9a.

**Comment by helderco** [comment]
Closing based on #3983. Easy enough to add later if it comes to it.
