### ISSUE TITLE
Rename exec to something less confusing

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3709]
## Problem

Developers learning Dagger get occasionally confused by the programming model. Most commonly the confusion revolves around the exact behavior of `Container.Exec`: when is a command actually executed, and why?

One reason of the confusion about Exec is its name: unlike almost every other step that lazily adds a node to the dag, it does not have the `With` prefix:

* `WithDirectory`: lazily add a directory
* `WithFile`: lazily add a file
* `WithEnvVariable`: lazily add an environment variable 
* `WithUser`: lazily set user
* **`Exec`: lazily execute a command** 🤔

This “breaks the pattern” and although there are several aspects of the DX that contribute to the overall confusion on the programming model, this is definitely one of them.

## Solution

Rename `Exec` to `WithExec`. This is not a perfect name (which is why we didn’t choose it in the first place), but the current lack of consistency is worse.

### Other possible names

Some other possible names:

* `WithExec` (current proposal).
* `AfterExec` (original name in API draft. Was changed to Exec for simplicity). IMO the difference between “with” and “after” makes sense, it’s semantically more elegant and expressive. But also too subtle, and per @aluzzardi ”I got confused because I thought there was a callback involved”.
* `Command` (proposed by @aluzzardi). I think this looks too much like `Directory` or `EnvVariable` ie: a different pattern of operations that return a different type, are often (always?) non-lazy. So IMO it would be confusing in a different way.
* `WithCommand` (proposed by @dolanor & @marcosnils). Evokes familiar `CMD` in Dockerfile
* `WithRun`. Evokes familiar `RUN` in Dockerfile

May the bikeshedding begin :)

**Comment by dolanor** [comment]
How about: `WithCommand`?

Keep the consistency, and sounds more passive than `Exec`, and less weird than `WithExec`.

**Comment by marcosnils** [comment]
> How about: `WithCommand`?

+1 here since `Exec` actually translates to Dockerfile's CMD instruction. So `WithCommand` might be simpler for users to understand.

**Comment by shykes** [comment]
> > How about: `WithCommand`?
> 
> +1 here since `Exec` actually translates to Dockerfile's `CMD` instruction. So `WithCommand` might be simpler for users to understand.

I really like the idea of leveraging familiarity with Dockerfile. However the problem is that `Exec` is not exactly equivalent to `CMD`: it’s a combination of `CMD` and `RUN`. So calling it `WithCommand` might create its own confusion.

**Comment by vito** [comment]
I think I see why you might want to differentiate `Exec` from the other `With`s. The mental model would be that all the "With"s modify the upcoming layer, and "Exec" is what actually adds a layer. If everything starts with `With` the whole thing becomes a drumroll with no "bang!"

So from that perspective `AfterExec` makes sense - just by virtue of being different - but it's unfortunate that it sounds callback related.

Here are some more ideas going on that theory:

* `HavingRun` - sounds a bit posh :sweat_smile: 
* `Commit` - as in `docker commit`, might be weird to lean on dated parts of Docker, but feels kinda neat anyway, and I like that it conveys returning a 'modified/added-to thing' as opposed to a side effect
* `CommitExec`
* `ExecCommit`
* `CommitRun`

---

I agree that `WithCommand` is probably too easy to confuse with `WithDefaultArgs`. 

I'd also be happy with either `WithExec` or `WithRun`.

**Comment by marcosnils** [comment]
> I agree that `WithCommand` is probably too easy to confuse with `WithDefaultArgs`.

yeah.. that makes sense. Dockerfiles don't have an analogous to `WithDefaultArgs`

> However the problem is that `Exec` is not exactly equivalent to `CMD`: it’s a combination of `CMD` and `RUN`. So calling it `WithCommand` might create its own confusion.

True


> I'd also be happy with either `WithExec` or `WithRun`.

Agree. I think I personally prefer `exec` since it's closer to the libc function family. Run resembles more to the Dockerfile instruction, but for some reason `WithRun` doesn't sound appealing to me :shrug: .

**Comment by dolanor** [comment]
For me, `commit` or `exec` still sounds like something happens at that stage, which is not true.
I didn't know about the confusion possible with the `CMD` + `RUN`, so I understand how `WithCommand` is not great.

I don't really have great suggestions:
- `WithProcess`
- `WithPlannedExec`
- `SetupExec`

A more gangsta suggestion
- `LazyE` for lazy exec'
![lazy-e](https://user-images.githubusercontent.com/928722/200658499-a70ec53a-fe33-494f-9d6f-1fbc03d66438.jpeg)

**Comment by aluzzardi** [comment]
> I think I see why you might want to differentiate Exec from the other Withs. The mental model would be that all the "With"s modify the upcoming layer, and "Exec" is what actually adds a layer. If everything starts with With the whole thing becomes a drumroll with no "bang!"

On the other hand, maybe the "bang!" is `Stdout()`, `ExitCode()`, `Publish()` -- things that actually do trigger a request. Maybe this actually would help clarifying what's sync and async -- "bang!"s are sync.

Regarding the layer model -- having `container.WithNewFile` etc (#3673) already "decouples" `With*` and layers.

> > I agree that `WithCommand` is probably too easy to confuse with `WithDefaultArgs`.
> 
> yeah.. that makes sense. Dockerfiles don't have an analogous to `WithDefaultArgs`

Well, they kinda do. It's `CMD` for default args and `RUN` for exec.

I'm good with `WithExec` -- but equally good with `WithRun` to be closer to Dockerfile's.

```go
ctr.WithDefaultArgs([]{"ls"}).WithExec([]string{})

// vs

ctr.WithDefaultArgs([]{"ls"}).WithRun([]string{})
```

Any preference anyone?

### Alternative

As I typed this, I realize there's a big bang alternative. It doesn't fix the confusion between lazy/non-lazy -- quite the contrary, it makes it worse. But hey, just throwing it here.

What if we embrace language first while making the GraphQL API odd?

> * `WithDirectory`: lazily add a directory
> * `WithFile`: lazily add a file
> * `WithEnvVariable`: lazily add an environment variable
> * `WithUser`: lazily set user
> * **`Exec`: lazily execute a command**

- `CopyDirectory`
- `CopyFile`
- `SetEnvVariable`
- `SetUser`
- `Exec`

Now, no one knows from the function name if it's lazy or not. We'd have to make it clear by another method (because it returns an `error` in Go, uses `await` for py/ts, etc).

But at least, `Exec` doesn't look out of place :P And it's pretty "natural" as code.

```go
out, err := c.Container().
  From("alpine").
  CreateNewFile("foo.txt", "hello world").
  SetEnvVariable("FILE", "foo.txt").
  Exec([]string{"cat", "$FILE").
  Stdout(ctx)
```

**Comment by shykes** [comment]
> > yeah.. that makes sense. Dockerfiles don't have an analogous to `WithDefaultArgs`
> 
> Well, they kinda do. It's `CMD` for default args and `RUN` for exec.

Yes, but I was saying something different. The problem is that `Exec` is not exactly equivalent to `CMD`: it’s a combination of `CMD` and `RUN`.

> I'm good with `WithExec` -- but equally good with `WithRun` to be closer to Dockerfile's.

This would be a Dockerfile “faux ami” because of the detail above 😁

**Comment by marcosnils** [comment]
I guess we can close this since we've shipped `withExec` already? cc @aluzzardi @mircubed

**Comment by aluzzardi** [comment]
Yes, shipped!
