### ISSUE TITLE
Testing NodeJS before launch 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3711]
We should test NodeJS SDK E2E before launching.

E2E experience to test:
Look at @slumbering 's guidance in his comment below. See #3642 for example 

Docs to follow while testing:
@slumbering  FIXME

External Users -
Please let us know in the general channel in Discord if you would like to help test the latest version and give feedback this week. I will add you to a private chat to give feedback. Please make issues for anything that you run into (big or small) and label it sdk/nodejs

Maintainers to test -
Please check the box below when you've completed your test.
maintainers who will test 
- [ ] @TomChv 
- [ ] @grouville 
- [ ] @kpenfound

**Comment by slumbering** [comment]
## 1. Run the engine

**Important:** The NodeJS isn't provisioning at the moment. This will be tackle soon. Here is the PR for more info: 
- https://github.com/dagger/dagger/issues/3653


Clone the [dagger/dagger](https://github.com/dagger/dagger) repo and run cloak: 
```shell
$ git clone https://github.com/dagger/dagger
$ cd dagger
$ go run ./cmd/cloak dev
```

## 2. Run client-simple example
FIXME

**Comment by mircubed** [comment]
@TomChv @kpenfound @grouville please test NodeJS experience above and let us know your thoughts. Thanks!

**Comment by slumbering** [comment]
Close this one as done
