### ISSUE TITLE
NodeJS SDK: return the value instead of an object

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#3715]
The actual query builder is always returning an object like the following example:
```js
const source = await client.host().workdir().id()

// Return
// {id: "myID...."}
```

Because the GraphQL api will always return a single field (shorturl.at/HJMNP), there is no need to return an object but the value only instead.

**Comment by benjaminstrasser** [comment]
@slumbering 
Is somebody already working on this?

**Comment by slumbering** [comment]
@benjaminstrasser nice timing ;). I've worked on it today. I can add you as a reviewer if you want ?
