### ISSUE TITLE
[DISCUSSION] - Define CLI experience.

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#3717]
In preparation for the GraphQL API announcement we need to provide Dagger users a way to execute GraphQL queries from a file. Currently, this is being allowed through the `cloak` command which is a binary that's not intended to be used by users. Below are some of the questions that initially I'm thinking need some answers:

- Shall we extract the `cloak do` to something public that requires its own SDLC?
- Is the current `cloak do` UX enough for this initial release? I'd assume so.
- Do we need to combine this as part of the Bash SDK release and don't release a GraphQL CLI until that's ready?  

cc @shykes @vito @sipsma @aluzzardi

**Comment by shykes** [comment]
@marcosnils see #3347. I will clean it up based on the first round of discussion.

**Comment by marcosnils** [comment]
Moving discussion to #3347
