### ISSUE TITLE
NodeJS SDK : Publish NodeJS SDK to npm

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#3719]
Publishes the NodeJS SDK to the registry so that it can be installed by name.
ex: `npm publish @dagger.io/nodejs-sdk`

https://www.npmjs.com is the npm Registry that has a public collection of packages of open-source code for Node.js.

In order to publish, follow the developer guide: https://docs.npmjs.com/cli/v9/using-npm/developers#the-packagejson-file

Need to discuss everything related to the CI with github action (Test, build and publish to NPM). cc @gerhard 

Tasks:
- [x] add a README.md
- [x] LICENSE

Npm automatically handles node_modules ignore. Do not add node_modules to .npmignore.

**Comment by slumbering** [comment]
cc @aluzzardi @sipsma

**Comment by gerhard** [comment]
Started looking into this with @slumbering. A few notes from our sync conversation:

We are missing a `README.md` & `LICENSE`
- These are currently in the PR queue: https://github.com/dagger/dagger/pull/3459
- Our first priority is to get this one merged (we plan on doing this today)

As soon as this is in, we will shift focus to implementing `mage sdk:nodejs:publish` & the [`publish-sdk-python.yml`](https://github.com/dagger/dagger/blob/sdk/python/v0.1.0-alpha.1/.github/workflows/publish-sdk-python.yml) workflow equivalent. We will test it by publishing an alpha pre-release via `npm publish --dry-run`, same as we did with the Python SDK: https://pypi.org/project/dagger-io/0.1.0a1/

Before we can publish, we need a `dagger` org / account, similar to PyPI: https://pypi.org/user/dagger/. Can you help @aluzzardi?

We are thinking of publishing the NodeJS SDK as https://www.npmjs.com/package/dagger-io, similar to what we did in PyPI: https://pypi.org/project/dagger-io/ . What do you think @shykes @mircubed? FWIW, https://www.npmjs.com/package/dagger is taken - last publish was **9 years ago**.

## AFAIKs

AFAIK 1: @slumbering is currently focusing on the Getting started part of the docs, especially making sure that everything is in place. @vikram-dagger will be helping shortly.

AFAIK 2: @dolanor is focusing on codegen in https://github.com/dagger/dagger/pull/3606. This is a blocker for the final `0.1.0` release.

AFAIK 3: @sipsma @TomChv will be helping with provisioning. This is a blocker for the final `0.1.0` release.

## Mental checklist offload

- [ ] `README.md` & `LICENSE` - @slumbering 
- [ ] `mage sdk:nodejs:publish` & `publish-sdk-nodejs.yml` - @gerhard @slumbering 
- [ ] GitHub release changelog - @gerhard 
- [ ] codegen - @dolanor 
- [ ] https://www.npmjs.com/org/dagger.io - @aluzzardi 
- [ ] provisioning - @sipsma @TomChv 
- [ ] https://docs.dagger.io/sdk/nodejs - @vikram-dagger 

---

FWIW, the above is not comprehensive. It's just enough to help us move in the right direction. It definitely helps me see what I need to focus on in the next few days. I trust @mircubed to have the comprehensive view.

**Comment by aluzzardi** [comment]
> Before we can publish, we need a dagger org / account, similar to PyPI: https://pypi.org/user/dagger/. Can you help @aluzzardi?

- `@dagger.io` org
- `@dagger.io/dagger` package
- `RELEASE_NPM_TOKEN` GHA secret is in place (similar to `RELEASE_PYPI_TOKEN`)

**Comment by slumbering** [comment]
> 



> > Before we can publish, we need a dagger org / account, similar to PyPI: https://pypi.org/user/dagger/. Can you help @aluzzardi?
> 
> We have the `@dagger.io` org
> 
> > We are thinking of publishing the NodeJS SDK as https://www.npmjs.com/package/dagger-io, similar to what we did in PyPI: https://pypi.org/project/dagger-io/ . What do you think @shykes @mircubed? FWIW, https://www.npmjs.com/package/dagger is taken - last publish was 9 years ago.
> 
> I believe the trend is to use an organization rather than root packages: `@dagger.io/dagger`
> 
> > mage sdk:nodejs:publish & publish-sdk-nodejs.yml - @gerhard @slumbering
> 
> Also missing test, lint and the whole CI pipeline. Started a skeleton here: #3783

Yes totally. but should we name it `@dagger.io/nodejs-sdk` instead of `@dagger.io/dagger` ?
