### ISSUE TITLE
Update `engine:dev` to be more of a bootstrap

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3739]
From conversation in discord:
1. We can use stable dagger to build dev dagger, but we should be sure that this "bootstrap" step only uses a stable sdk + engine. It thus might need to have its own `go.mod` (maybe can use the [`tools.go` convention](https://play-with-go.dev/tools-as-dependencies_go119_en/) here?) so we can ensure its only using stable versions.
2. Our CI steps will typically do something like:
   1. Build+start dev dagger (bootstrapping it with stable dagger)
   1. Export DAGGER_HOST=docker-container://test-dagger-engine
   1. Run the rest of our CI steps
3. But developers locally can retain the flexibility of doing the above or instead using stable dagger to run ci steps (i.e. I broke my local dev engine but want to lint my python code still)
4. The above means that the bootstrap stage where we build dagger w/ dagger can only rely on stable released features. The rest of the steps can use dev features though. I think that's probably fine? Worst case scenario it's always possible to add more stages to your bootstrap process...

Additionally, it would make sense to find a way of modelling this as a sort of "wrapper" where you can run a command that bootstraps dev dagger and then invokes the rest of the commandline you provide in the context of that dev dagger (i.e. `DAGGER_HOST=...`.

A kind of silly approach to this could be `mage devdagger sdk:python:test`, where the `devdagger` target invokes mage as a subprocess. But there's probably better ways of doing it too.

cc @aluzzardi @shykes @vito

**Comment by vito** [comment]
Picking this up since I need it for #3671 now that it adds new SDK/engine interaction (session initialization).
