### ISSUE TITLE
configure dependabot for Python SDK

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#3754]
Need to add a section for `sdk/python`:

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

I think `poetry` is supported but not `hatch`

**Comment by helderco** [comment]
Duplicate of #3727

**Comment by helderco** [comment]
No longer using hatch. I switched to poetry.

**Comment by aluzzardi** [comment]
whoops!

**Comment by ofek** [comment]
It's supported now https://github.blog/changelog/2022-10-24-dependabot-updates-support-for-the-python-pep-621-standard/

> No longer using hatch. I switched to poetry.

Out of curiosity, why?

**Comment by helderco** [comment]
> Out of curiosity, why?

More context here:
- https://github.com/dagger/dagger/issues/3702

A big reason was dependabot, glad that's not an issue anymore. Still, poetry is generally better supported because it's been around longer. Even in VS Code it can detect a poetry venv but not hatch.

But what pushed over the edge was that I was wasting time figuring out how to have a different project name from package name. Do you know?

**Comment by ofek** [comment]
> how to have a different project name from package name

- Name controlled by https://hatch.pypa.io/latest/config/metadata/#name
- What is shipped controlled by https://hatch.pypa.io/latest/config/build/#file-selection like:
   ```toml
   [tool.hatch.build.targets.wheel]
   packages = ["src/foo"]
   ```

**Comment by helderco** [comment]
Yeah, I was confused by the `wheel` target. What about sdist?

**Comment by ofek** [comment]
First section on https://hatch.pypa.io/latest/config/build/

```toml
[tool.hatch.build.targets.sdist]
```

https://hatch.pypa.io/latest/plugins/builder/sdist/

**Comment by ofek** [comment]
> you have to duplicate that for each

Right which is desirable because they include different things

> sdist doesn't seem to have the `packages` option?

Also first section on https://hatch.pypa.io/latest/config/build/

> For each build target you may override any of the defaults set in the top-level `tool.hatch.build` table.

But for sdist you'd want https://hatch.pypa.io/latest/config/build/#patterns

**Comment by ofek** [comment]
Did you have time yet to try?

**Comment by helderco** [comment]
> Did you have time yet to try?

You mean hatch? No, there's no reason to change back to hatch now.

If you don't agree you can list your pros & cons in https://github.com/dagger/dagger/issues/3702 so it stays in scope 🙂
