### ISSUE TITLE
[Docs] Examples Implementation

### ISSUE THREAD

**Issue by crjm** [dagger/dagger#3781]
Based on a discussion we had, we should document the main thoughts and possibilities for rendering examples for each SDK and API in a programmatic, integrated and maintainable manner across Dagger documentation.
The main implementation idea is to leverage on Docusaurus plugins and [`swizzling`](https://docusaurus.io/docs/swizzling).
Because of time restraints, this should be revisited in the future.
cc @vikram-dagger @marcosnils

**Comment by mircubed** [comment]
Along with that, adding the feedback from Vikram that this should also "Provide a "code library" with minimum 10-15 examples of common operations, in each supported SDK language and for the CLI"

**Comment by marcosnils** [comment]
Closing in favor of #4291
