### ISSUE TITLE
review issue templates

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#3794]
We should revisit our issue templates since some of them still request the user to run old commands like `dagger version`. i.e: https://github.com/dagger/dagger/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.yaml&title=%F0%9F%90%9E+%3Ctitle%3E

cc @gerhard

**Comment by marcindulak** [comment]
It asks also about OS version, but it could provide cli commands to get it
```
sw_vers  # MacOS
cat /etc/*release | grep PRETTY  # Linux
ver  # Windows, not sure it's supported still https://en.wikipedia.org/wiki/Ver_(command)
```
![Screenshot from 2022-11-26 12-17-31](https://user-images.githubusercontent.com/3178318/204086161-2a5eaae4-e059-4efe-9123-6a57e6d55d7c.png)

**Comment by marcindulak** [comment]
The <title> field could also be removed - it's easy to forget to remove it since it looks like a kind of tag.

![Screenshot from 2022-11-26 12-18-42](https://user-images.githubusercontent.com/3178318/204086101-ef12f44b-6fa8-43e2-a076-4305c0073cd5.png)

**Comment by marcindulak** [comment]
dagger.io indicates "DEVELOP YOUR CI/CD PIPELINES AS CODE AND RUN THEM ANYWHERE" and it would be beneficial if issue reports were also runnable anywhere. Dagger would facilitate the environment setup where reports would be asked to run before submission. The old dagger 0.2 behaved that way: there was just the dagger binary and the cue files it executed.
