### ISSUE TITLE
NodeJS SDK: query builder args as strings

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#3810]
## Update

we went for required as top level params and optionals as an object with fields as optionals:

```typescript
withExec(args: string[], stdin?: string, redirectStdout?: string, redirectStderr?: string, experimentalPrivilegedNesting?: boolean): Container {
//…
}
```

```typescript
withExec(args: string[], opts?: ContainerWithExecOpts): Container {
//…
}
export type ContainerWithExecOpts = {
  stdin?: string
  redirectStdout?: string
  redirectStderr?: string
  experimentalPrivilegedNesting?: boolean
}
```

## Original

To be more consistent with Go and Python SDKs, we should pass strings as arguments instead of object with the NodeJS query builder.

```typescript
// BEFORE
const node = await client.container().from({ address: `node:${nodeVersion}` })
```

```typescript
// AFTER
const node = await client.container().from(`node:${nodeVersion}`)
```

**Comment by helderco** [comment]
Since TS doesn't have named parameters, the same can be done as in Go for the optionals. I.e., make required parameters positional, and put optionals in an `opts` argument typed in an `interface`.

```typescript
const node = await client.container().from(`node:${nodeVersion}`).exec({args: ["node", "--version"]})
```

**Comment by slumbering** [comment]
We are actually rolling back to object as it fills more natural and we also avoid positional arguments.

**Comment by helderco** [comment]
Between all positional or all in an object, I suggested the middle ground of positional required arguments, and an object for optionals (`opts`). What's wrong with that? Seems the better DX.

**Comment by slumbering** [comment]
TBD with @dolanor
