### ISSUE TITLE
Make `Workdir` less confusing/overloaded: `Host.Workdir` & `Container.Workdir`

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#3828]
## Problem
Some Dagger devs get confused by the overloaded use of "Workdir" in `Host.Workdir` and `Container.Workdir`.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/3187222/201836793-a817a309-ccb7-4497-90fa-af65fc9d0809.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/3187222/201983459-febc6b88-4679-400c-83fa-4a3d8bc09fb8.png">

## Possible Solutions
1) Change `Container.Workdir`

Common elements:
- Leave `Host.Workdir` as is (though we might promote `Host.Directory(".")` more)

a) Use `Container.WithWorkdir`:
- Rename `Container.Workdir` to `Container.WithWorkdir` (even though its a config thing and not a new layer).
- Already the inclination in the Node SDK: https://github.com/dagger/dagger/blob/main/sdk/nodejs/api/client.ts#L610-L613

<hr/>

2) Change `Host.Workdir`

Common elements:
- Keep `Container.Workdir` as it's aligned with the concept of `Dockerfile` `WORKDIR`.
- Leave `Host.Workdir` (for compatibility) for now.

a) Use `Host.Directory(".")`:
- Promote use of `Host.Directory(".")` in docs (already works, ty @shykes )
Relatively safe. Though it can escape out of the current working directory, you must use an absolute path to do so:
```
input:1: host.directory path ".." escapes workdir; use an absolute path instead
```

b) New element that works like `Host.Workdir` but is called something else:
- `Host.Source` (Dagger CUE `core.#Source` style)
- `Host.ProjectDir` or `Host.ProjectDirectory`
- `Host.CWD`
- `Host.PWD`
- `Host.RootDir`
- `Host.BuildContext` or `Host.BuildContextRoot` or `Host.Context` (Docker-ish https://docs.docker.com/engine/reference/commandline/build)
- etc

**Comment by jlongtine** [comment]
A couple of things to note:

`func (r *Container) WithWorkdir(path string) *Container` [already exists](https://github.com/dagger/dagger-go-sdk/blob/main/api.gen.go#L503), `func (r *Container) Workdir(ctx context.Context) (string, error)` is for retrieving the currently set `Workdir`.

I can understand that having both `Container.WithWorkdir` and `Host.Workdir` might be confusing. I like the idea of just dropping `Host.Workdir`. 


We could suggest: `cwd, _ := os.Getwd(); currentDir := c.Host().Directory(cwd)` for Go (and similar for other languages)?

**Comment by shykes** [comment]
I agree, let's do it:

1. Add deprecation warning
2. Remove `Host().Workdir()` from all examples in all docs /cc @vikram-dagger
