### ISSUE TITLE
NodeJS SDK: automatic sdk engine version

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#3837]
![Capture d’écran 2022-11-15 à 11 40 32](https://user-images.githubusercontent.com/1186424/201899367-dadba053-1ed5-4a87-b0c0-5252bf5c0fa7.png)

Not a blocker on merge but just FYI we'll want to integrate this with the automatic sdk engine version bumper: https://github.com/dagger/dagger/pull/3809/files

_Originally posted by @sipsma in https://github.com/dagger/dagger/pull/3820#discussion_r1022238179_

**Comment by gerhard** [comment]
Closed via https://github.com/dagger/dagger/pull/3841
