### ISSUE TITLE
Automate tests of provisioning

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3852]
Right now we can't test provisioning via dagger-in-dagger so the testing is just manual: https://github.com/dagger/dagger/blob/main/RELEASING.md#go-sdk

We should automate this by either:
1. Supporting mounting a docker.sock into containers: https://github.com/dagger/dagger/issues/3850
2. Running the tests outside dagger-in-dagger

`1.` is my strong preference since it saves us from having to setup a bunch of dependencies for running the sdk tests directly on the host.

---

When we do this we should
1. Update RELEASING.md to remove manual test steps
2. Unskip the test mentioned here: https://github.com/dagger/dagger/pull/3851#discussion_r1023164201
3. Also make sure to run the tests with emulation so that we verify it works on the different arches we support (https://github.com/dagger/dagger/pull/3858)

**Comment by aluzzardi** [comment]
Since 1) has been requested by multiple users, I think we should just go for it

**Comment by slumbering** [comment]
Correct me if I'm wrong but this has been implemented, right ?
I mean at least for Node.js SDK : https://github.com/dagger/dagger/blob/main/sdk/nodejs/test/connect.spec.ts#L52
cc @sipsma. Feel free to reopen it

**Comment by helderco** [comment]
I think so, in:
- https://github.com/dagger/dagger/pull/4208
