### ISSUE TITLE
Add checksum verification of engine-session binary

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3856]
We should verify the checksums of cached engine-session bins. This will help us better handle bugs like [this](https://github.com/dagger/dagger/pull/3855) where the cached bin can get corrupted (in that case, any empty file).

**Comment by slumbering** [comment]
Is it part just check the downloaded checksum ? https://github.com/dagger/dagger/blob/main/sdk/nodejs/provisioning/bin.ts#L69

**Comment by sipsma** [comment]
@slumbering yep this got implemented as part of the recent updates https://github.com/dagger/dagger/pull/4194
