### ISSUE TITLE
🐞 When using docker.#Run with export.files, exporting binary files with client.filesystem breaks them

### ISSUE THREAD

**Issue by Puddinghat** [dagger/dagger#3878]
### What is the issue?

I was trying to create plan files via Terraform plan via docker.#Run in dagger and export the resulting planfile. Using that planfile I had planned to insert it back into docker via docker.#Copy and apply it via terraform apply. However, when using client.filesystem in dagger.#Plan, it inexplicably breaks the planfile. 
It gets corrupted and can't be used in terraform anymore, showing the following error:

> Terraform couldn't read the given file as a state or plan file.
> The errors while attempting to read the file as each format are
> shown below.
> 
> State read error: Error reading tf.plan as a statefile: 2 problems:
> 
> - Unsupported state file format: The state file could not be parsed as JSON: syntax error at byte offset 1.
> - Unsupported state file format: The state file does not have a "version" attribute, which is required to identify the format version.
> 
> Plan read error: zip: not a valid zip file

However, when exporting the entire directory, it works without a problem. It also works when just using the output of the plan-step in the apply-run. Just when using explicitly files in combination with plan, it breaks.

### Log output

[✔] actions.terraformPrepare.write                                                                                                                                                 0.0s
[✔] client.network."unix:///var/run/docker.sock"                                                                                                                                   0.0s
[✔] actions.terraformPlan.state                                                                                                                                                    0.0s
[✔] actions.terraformPrepare.image                                                                                                                                                 0.1s
[✔] actions.terraformPrepare.copy                                                                                                                                                  0.0s
[✔] actions.terraformPrepare.tfInit                                                                                                                                                0.0s
[✔] actions.terraformPlan.copy                                                                                                                                                     0.0s
[✔] actions.terraformPlan.plan                                                                                                                                                     0.3s
[✔] actions.terraformPlan.plan.export                                                                                                                                              0.0s
[✔] client.filesystem.plan.write                                                                                                                                                   0.0s

### Steps to reproduce

I have created a branch on a public git-branch here:
https://github.com/Puddinghat/cuetest/tree/dagger-bug

The broken plan is called "terraformPlan". You need to create a folder called "build" and precreate an empty file "terraform.tfstate".

### Dagger version

dagger v0.2.36 (ea275a3ba) darwin/arm64

### OS version

MacOS 13.0.1

**Comment by samalba** [comment]
Closing, the cue sdk is no more supported.
