### ISSUE TITLE
announcement channel on Discord with release notifications 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3883]
Community Request - Could we get a releases channel for just release github/general release notification? 

Advice - 
>I did change log driven releases for my team lately (using changie) and it’s really helped as only release notifications get piped through. An announcement channel would be great as long as it’s not dev level commits but release/tag driven

[Discord context](https://discord.com/channels/707636530424053791/708371226174685314/1042496617938436156)

**Comment by mircubed** [comment]
@gerhard tagging you since I think this might be something that you'd need to include in the release process?

**Comment by gerhard** [comment]
That is a great idea!

I don't have privileges to create channels in Discord, but @aluzzardi can help.

Will follow-up on this part of today's release.

**Comment by mircubed** [comment]
Now, we have the announcement channel for the community, so I will use that as the place to add the change logs when the team notifies me of the new release.
