### ISSUE TITLE
API: Creating a new file is annoying

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#3884]
Because of the optional contents, creating a new file looks something like this:

```go
	newDir := c.Directory().WithNewDirectory("/foo").WithNewFile("some-file", dagger.DirectoryWithNewFileOpts{
		Contents: "some-content",
	})
```

By making contents required it would look like this:

```go
	newDir := c.Directory().WithNewDirectory("/foo").WithNewFile("some-file", "some-content")
```

Creating an empty file would still be possible, although a bit quirky:

```go
	newDir := c.Directory().WithNewDirectory("/foo").WithNewFile("some-file", "")
```

From my own dogfooding experience, creating an empty file is extremely rare (never done it) whereas every time I reached for `WithNewFile` it was to inject some contents.

/cc @shykes @vito

**Comment by shykes** [comment]
I say ship it 😁

**Comment by dolanor** [comment]
Have you ever had the need to actually pass some `io.Writer` to it? Or it was always small enough that some `[]byte` or `string` was enough?

**Comment by aluzzardi** [comment]
> I say ship it 😁

👍 

> > Have you ever had the need to actually pass some `io.Writer` to it? Or it was always small enough that some `[]byte` or `string` was enough?
> 
> Given that it's going to have to be a string once the API is called, it probably doesn't matter.

Correct. `WithNewFile` is limited to small files because it ends up as a single gRPC call to buildkit (not a streaming thing). If it's above a few kilobytes it becomes a problem.

**Comment by helderco** [comment]
How about adding a file to a container?

**Comment by jlongtine** [comment]
> Correct. `WithNewFile` is limited to small files because it ends up as a single gRPC call to buildkit (not a streaming thing). If it's above a few kilobytes it becomes a problem.

Given this, should we actually put a limit on it? 

Perhaps we could print an warning from the SDK, or at least put a warning in the SDK docs? I can confidently say that we'll have a user that tries a large file and gets some really fun errors as a result. 😄
