### ISSUE TITLE
✨ implement dagger.#Set in cloak

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#3886]
### What are you trying to do?

Allow to set OCI image config through cloak. Some other users in Discord are requesting this also.

https://discord.com/channels/707636530424053791/1042489428788138025
https://discord.com/channels/707636530424053791/1042489428788138025/1042660776831365190

### Why is this important to you?

Because it's currently available in the CUE SDK

### How are you currently working around this?

N/A

**Comment by marcosnils** [comment]
Update: seems like only `EXPOSE` is missing.

ref: https://discord.com/channels/707636530424053791/1090037052923453470

**Comment by helderco** [comment]
Update: `EXPOSE` is supported since services.

**Comment by helderco** [comment]
## Supported image metadata
| OCI                                                                                                                                  | Dockerfile                                                                 | Dagger                                                                           |
| ------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| [User](https://github.com/opencontainers/image-spec/blob/0b40f0f367c396cc5a7d6a2e8c8842271d3d3844/specs-go/v1/config.go#L26)         | [USER](https://docs.docker.com/engine/reference/builder/#user)             | [WithUser](https://pkg.go.dev/dagger.io/dagger#Container.WithUser)                                                                         |
| [ExposedPorts](https://github.com/opencontainers/image-spec/blob/0b40f0f367c396cc5a7d6a2e8c8842271d3d3844/specs-go/v1/config.go#L29) | [EXPOSE](https://docs.docker.com/engine/reference/builder/#expose)         | [WithExposedPort](https://pkg.go.dev/dagger.io/dagger#Container.WithExposedPort) | 
| [Env](https://github.com/opencontainers/image-spec/blob/0b40f0f367c396cc5a7d6a2e8c8842271d3d3844/specs-go/v1/config.go#L32)          | [ENV](https://docs.docker.com/engine/reference/builder/#env)               | [WithEnvVariable](https://pkg.go.dev/dagger.io/dagger#Container.WithEnvVariable) |
| [Entrypoint](https://github.com/opencontainers/image-spec/blob/0b40f0f367c396cc5a7d6a2e8c8842271d3d3844/specs-go/v1/config.go#L35)   | [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#entrypoint) | [WithEntrypoint](https://pkg.go.dev/dagger.io/dagger#Container.WithEntrypoint)   |
| [Cmd](https://github.com/opencontainers/image-spec/blob/0b40f0f367c396cc5a7d6a2e8c8842271d3d3844/specs-go/v1/config.go#L38)          | [CMD](https://docs.docker.com/engine/reference/builder/#cmd)               | [WithDefaultArgs](https://pkg.go.dev/dagger.io/dagger#Container.WithDefaultArgs) |
| [Volumes](https://github.com/opencontainers/image-spec/blob/0b40f0f367c396cc5a7d6a2e8c8842271d3d3844/specs-go/v1/config.go#L41)      | [VOLUME](https://docs.docker.com/engine/reference/builder/#volume)         |                                                                                  |
| [WorkingDir](https://github.com/opencontainers/image-spec/blob/0b40f0f367c396cc5a7d6a2e8c8842271d3d3844/specs-go/v1/config.go#L44)   | [WORKDIR](https://docs.docker.com/engine/reference/builder/#workdir)       | [WithWorkdir](https://pkg.go.dev/dagger.io/dagger#Container.WithWorkdir)                                                                      |
| [Labels](https://github.com/opencontainers/image-spec/blob/0b40f0f367c396cc5a7d6a2e8c8842271d3d3844/specs-go/v1/config.go#L47)       | [LABEL](https://docs.docker.com/engine/reference/builder/#label)           | [WithLabel](https://pkg.go.dev/dagger.io/dagger#Container.WithLabel)                                                                        |
| [StopSignal](https://github.com/opencontainers/image-spec/blob/0b40f0f367c396cc5a7d6a2e8c8842271d3d3844/specs-go/v1/config.go#L50)   | [STOPSIGNAL](https://docs.docker.com/engine/reference/builder/#stopsignal) |                                                                                  |

Dagger right now supports only the OCI spec, but it did support the [extended definitions](https://github.com/moby/buildkit/blob/57a029f7653a878e9b551d50bb1ad79110ab68aa/exporter/containerimage/image/docker_image.go#L35-L41) from Dockerfiles in [CUE](https://github.com/dagger/dagger/blob/4771b27142e707be75f8d84ac62e076087ed2c16/plan/task/image.go#L11C1-L71):
- [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck)
- [ONBUILD](https://docs.docker.com/engine/reference/builder/#onbuild)
- [SHELL](https://docs.docker.com/engine/reference/builder/#shell)
- StopTimeout

Let’s open individual issues if someone needs support for more.
