### ISSUE TITLE
✨ Ability to add LABELs to Docker images published via SDK

### ISSUE THREAD

**Issue by nipuna-perera** [dagger/dagger#3887]
### What are you trying to do?

Generate and publish a docker image which has LABELs. 

Related discussion : https://discord.com/channels/707636530424053791/1042501877906022481

### Why is this important to you?

We have corporate policies that mandate certain labels on all docker images

### How are you currently working around this?

The workaround is to manually create a dockerfile with the LABELs added. But this is inconvenient and bypasses the features provided by the API and SDK

For broader set of OCI configs: #3886

**Comment by marcosnils** [comment]
ref https://github.com/dagger/dagger/issues/3886

**Comment by aluzzardi** [comment]
#4245 for API proposal
