### ISSUE TITLE
Node.js SDK : Error handling

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#3899]
Currently, if an error occur, it's printed out but the exit code is still 0.
We should trigger a more appropriate `process.exit(1)`.

**Comment by mircubed** [comment]
discord context, so we can follow up with user once completed - https://discord.com/channels/707636530424053791/1040027260155088956/1042802626649141298

**Comment by benjaminstrasser** [comment]
Maybe borrow the pattern from [hardhat](https://hardhat.org/hardhat-runner/docs/guides/deploying) to achieve exit codes and add this pattern to the examples and guides.
This way the SDK just throws "better errors" and the user can do with them what they want.
Dagger just provides a sensible example of how to deal with errors per default.

> ```
> async function main() {
>    ...
>}
>
>main().catch((error) => {
>    console.error(error);
>    process.exitCode = 1;
>});
>```

**Comment by benjaminstrasser** [comment]
Another option is

```
connect(async (client: Client) => {
    ....
}).catch((error) => {
   console.error(error);
   process.exitCode = 1;
});
```

**Comment by marcindulak** [comment]
@benjaminstrasser - how the example below should be modified to "exit 1"?

Execute the modified [get-started/step3/build.ts](https://github.com/dagger/dagger/blob/79faf032be522d03ea215874df2cb2c147881c79/docs/current/sdk/nodejs/snippets/get-started/step3/build.ts) example containing an injected error command `node none`. Run `node --loader ts-node/esm ./build.ts`
   ```javascript
   import Client, { connect } from "@dagger.io/dagger"

   // initialize Dagger client
   connect(async (client: Client) => {
     // get Node image
     // get Node version
     const node = await client.container().from("node:16").exec(["node", "none"])

     // execute
     const version = await node.stdout().contents()

     // print output
     console.log("Hello from Dagger and Node " + version.contents)
   }).catch((error) => {
      console.error(error);
      process.exitCode = 1;
   })
   ```

To reproduce:

1. Use the following `Dockerfile`
   ```Dockerfile
   FROM node:18.12.1-alpine3.16

   # Install docker-cli
   RUN apk update \
       && apk add shadow docker-cli \
       && rm -rf /var/cache/apk/*

   # Allow node to execute docker commands without sudo
   RUN addgroup -S docker && adduser node docker

   # Configure sudo
   RUN apk update \
       && apk add sudo \
       && rm -rf /var/cache/apk/*
   RUN echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel
   RUN adduser node wheel && sudo -lU node

   USER node

   WORKDIR /app

   CMD ["sleep", "infinity"]
   ```
2. Execute
   ```sh
   docker rm -f dagger
   docker build -t dagger:latest .
   docker run -d --rm --name dagger -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/app dagger:latest sleep infinity
   docker exec -it dagger sh -c "sudo groupmod -g \$(stat -c '%g' /var/run/docker.sock) docker"
   docker exec -it dagger sh -c "npm install ts-node"
   docker exec -it dagger sh -c "npm install @types/node"
   docker exec -it dagger sh -c "npm pkg set type=module"
   docker exec -it dagger sh -c "echo '{\"compilerOptions\":{\"moduleResolution\":\"Node\",\"module\":\"ESNext\",\"target\":\"ES2020\"}}' > tsconfig.json"
   docker exec -it dagger sh -c "npm install @dagger.io/dagger@0.1.0"
   docker exec -it dagger sh -c "node --loader ts-node/esm ./build.ts"
   ```

Output:
```
(node:86) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{
  "response": {
    "data": {
      "container": {
        "from": {
          "exec": {
            "stdout": null
          }
        }
      }
    },
    "errors": [
      {
        "message": "process \"/_shim docker-entrypoint.sh node none\" did not complete successfully: exit code: 1",
        "locations": [
          {
            "line": 2,
            "column": 82
          }
        ],
        "path": [
          "container",
          "from",
          "exec",
          "stdout",
          "contents"
        ]
      }
    ],
    "status": 200,
    "headers": {}
  },
  "request": {
    "query": "\n            {container{from(address:\"node:16\"){exec(args:[\"node\",\"none\"]){stdout{contents}}}}}\n          "
  }
}
Hello from Dagger and Node undefined
```
```
echo $?
0
```

**Comment by benjaminstrasser** [comment]
@marcindulak 
I don't think you can currently use my approach since no Errors are thrown by dagger.
Introducing sensible error handling is part of the discussion. Once sensible errors are thrown catching them as per my example will work.

Her you can see how errors coming from the graphql backend just get logged and ignored.

``` client.gen.ts
  protected async _compute() : Promise<Record<string, any>> {
    try {
      // run the query and return the result.
      const query = queryBuilder(this._queryTree)
      const computeQuery: Awaited<Promise<Record<string, any>>> =  await this.client.request(gql`${query}`)

      return queryFlatten(computeQuery)
    } catch (error) {
      console.error(JSON.stringify(error, undefined, 2))
      return {}
    }
  }
```

What you can do for now is simply to check if a value is undefined every time a call is made. In your example  this would be something like

```ts
import Client, { connect } from "@dagger.io/dagger"

// initialize Dagger client
connect(async (client: Client) => {
  // get Node image
  // get Node version
  const node = await client.container().from("node:16").exec(["node", "none"])

  // execute
  const version = (await node.stdout().contents()).contents
  if (!version){
    throw Error("Custom Error")
  }

  // print output
  console.log("Hello from Dagger and Node " + version)
}).catch((error) => {
  console.error(error);
  process.exitCode = 1;
})
```

Another less general apraoch is to check the exit code og the last executed comand

```ts
  if ((await node.exitCode()).exitCode != 0){
```

**Comment by marcindulak** [comment]
There is also a question what is the exposed contents when an error occurs: graphl's `did not complete successfully: exit code: X` is not enough when debugging failures.

At least these issues are relevant for the discussion: https://github.com/dagger/dagger/issues/3496#issuecomment-1295245671 and https://github.com/dagger/dagger/issues/3182

**Comment by slumbering** [comment]
> Maybe borrow the pattern from [hardhat](https://hardhat.org/hardhat-runner/docs/guides/deploying) to achieve exit codes and add this pattern to the examples and guides. This way the SDK just throws "better errors" and the user can do with them what they want. Dagger just provides a sensible example of how to deal with errors per default.
> 
> > ```
> > async function main() {
> >    ...
> > }
> > 
> > main().catch((error) => {
> >    console.error(error);
> >    process.exitCode = 1;
> > });
> > ```
> 
> If this is the way we want to proceed just @ me and I'll open a PR. Am obviously open to input/suggestions.

@benjaminstrasser totally keen to let you open a PR if you want 🙏 .

**Comment by benjaminstrasser** [comment]
Opened draft here #3947
