### ISSUE TITLE
Download shim from our own image

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3900]
## Problem

Currently dagger automatically downloads a `golang` image, to produce the  "shim" necessary to execute commands in containers. This causes several problems:

* Users messages about downloading a golang image in their logs, which is confusing especially if you're not a Go developer. This has been brought up by users already
* It creates a dependency on third-party infrastructure which we have less control over. Downtime, rate limiting etc

## Solution

Host the shim in an image packaged and distributed by Dagger, on our own registry.

**Comment by shykes** [comment]
FYI @aluzzardi @sipsma @samalba

**Comment by sipsma** [comment]
Have an issue here: https://github.com/dagger/dagger/issues/3733

If possible I'd prefer to solve this by giving ourselves the ability to just have the shim binary included in the engine image and then mount it into execs. That's unfortunately not super straightforward, but I think there's some possibilities worth exploring (will list in subsequent comment).

That approach would:
1. save us from managing another image. 
2. make it easier for users to customize the engine image in the future or to mirror it on their own registries (i.e. an internal company one)
3. be more performant (pull everything at once)

However, if it's too complicated for now, I think we can fallback to pulling it from a separate image.

**Comment by shykes** [comment]
Thanks @sipsma, I'll close this one as duplicate. To be clear I don't have an opinion on using engine image vs having a new image. As long as all the bits are downloaded from our registry, and the log output is not confusing to users, I'm happy :)
