### ISSUE TITLE
Make a clear distinction between 0.2 docs and new docs 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3904]
### What is the issue?

Users are landing on the old docs for some reason, so we need to clarify that they should go to the new docs instead when they land in the old docs. 

I think they are landing there because google is showing quick links to the old docs. 

![Screen Shot 2022-11-17 at 12 01 58 PM](https://user-images.githubusercontent.com/101831275/202547707-f8548c8d-fd63-4849-89a9-455ebd983ec6.png)

We should add a warning on the old docs and then try to fix the google search issue - 
![Screen Shot 2022-11-17 at 12 03 59 PM](https://user-images.githubusercontent.com/101831275/202548414-b19e469c-d2d9-41cf-b9cc-349b0af468b6.png)

**Comment by mircubed** [comment]
I'll take a look at the google rendering issue. I think we were able to fix this problem at Bitnami, so I just need to remember how we did it.

**Comment by vikram-dagger** [comment]
> I'll take a look at the google rendering issue. I think we were able to fix this problem at Bitnami, so I just need to remember how we did it.

One solution might be to add redirects to let Google know the new URLs (if we have equivalents in the current docs). Or use their search console tool, which has an option to remove outdated content from search results: https://support.google.com/webmasters/answer/7041154?hl=en

**Comment by vikram-dagger** [comment]
Notice added to old docs in #3915 and #3988
