### ISSUE TITLE
language agnostic guides 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3909]
### What is the issue?

Problem: 

>If they want emulation to work yes. It's the same state as docker build{x} users for now. It's mentioned in the requirements here: https://docs.dagger.io/sdk/go/406009/multiplatform-support
But as @Jeremy Adams pointed out in the zoom meeting earlier that's not good because it's a requirement that applies to all of our SDKs, not just Go. So we need a language agnostic section or something. 

We need to find a solution for guides that are related to all SDKs instead of just a singular SDK. When we created the SDK docs, we were thinking of the concept of a user staying in a single SDK section. We can technically keep that same concept, but just link to the language-agnostic guides from those sections in some way.

**Comment by shykes** [comment]
In the case of multi-platform, there seems to be a natural split in two parts:

1. An operator's guide: how to configure multi-platform support in your engine (language-agnostic)
  * Setup emulation with binfmt
  * But also later: clustering with machines of different architectures
  * And also later: using Dagger Cloud to do some of these things

2. A developer's guide: how to develop multi-platform pipelines
  * SDK-specific
  * Requires an engine configured with multi-platform support: see this operator's guide to learn more

**Comment by marcosnils** [comment]
Closing in favor of #4291
