### ISSUE TITLE
Mage dagger tests should check that latest engine is being used

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#3932]
I've noticed that some tests (https://github.com/dagger/dagger/blob/main/internal/mage/sdk/python.go#L29-L80) are accidentally not currently using the `WithDevEngine`  util helpers which causes the SDK to pick the latest defined in the `engine.gen.go`. 

We should add something that prevents accidentally using an outdated to test since this will result in potential issues that are not easy to track.

**Comment by marcosnils** [comment]
IIRC @sipsma told me that he was working in something for this. Eric, do we still need to validate this somehow?

**Comment by sipsma** [comment]
Oh yeah this isn't relevant anymore. We now use a stable (previously released) version of dagger to execute tests. Inside the test container the docker sock is mounted and the tests can either bootstrap dagger as normal or be provided a dev engine (setup in ./hack/make)
