### ISSUE TITLE
✨ Create container from a locally built docker image

### ISSUE THREAD

**Issue by marcindulak** [dagger/dagger#3933]
### What are you trying to do?

Use a docker image built locally for creating containers with dagger.

To reproduce the error, take the example from 
https://github.com/dagger/dagger/blob/79faf032be522d03ea215874df2cb2c147881c79/docs/current/sdk/nodejs/snippets/get-started/step3/build.ts, and modify it to use a locally built image `mynode:latest` instead of `node:16`:

```
import Client, { connect } from "@dagger.io/dagger"
connect(async (client: Client) => {
  const node = await client.container().from("mynode:latest").exec(["node", "-v"])
  const version = await node.stdout().contents()
  console.log("Hello from Dagger and Node " + version.contents)
})
```

1. Build the `mynode:latest` image:
   ```sh
   docker build -t mynode:latest -f Dockerfile .
   ```
   using this `Dockerfile`
   ```
   FROM node:18.12.1-alpine3.16

   CMD ["sleep", "infinity"]
   ```
2. Test the image
   ```sh
   docker run -it --rm --name mynode mynode:latest node --version
   v18.12.1
   ```
3. Install dagger 
   ```sh
   npm install ts-node
   npm pkg set type=module
   npm install @dagger.io/dagger@0.1.0
   echo '{"compilerOptions":{"moduleResolution":"Node","module":"ESNext"}}' > tsconfig.json
   ```
4. Try to use the image with dagger:
   ```sh
   node --loader ts-node/esm build.ts
   (node:1581) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
   (Use `node --trace-warnings ...` to show where the warning was created)
   {
     "response": {
       "data": null,
       "errors": [
         {
           "message": "pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed",
           "locations": [
             {
               "line": 2,
               "column": 24
             }
           ],
           "path": [
             "container",
             "from"
           ]
         }
       ],
       "status": 200,
       "headers": {}
     },
     "request": {
       "query": "\n            {container{from(address:\"mynode:latest\"){exec(args:[\"node\",\"-v\"]){stdout{contents}}}}}\n          "
     }
   }
   Hello from Dagger and Node undefined
   ```

Expected output:
```sh
Hello from Dagger and Node v18.12.1
```

### Why is this important to you?

The image may be built by another approach (or another instance of dagger) and dagger is then used to only consume the image.
Avoiding remote or local registries for pushing and pulling the image makes dagger easier to use and saves resources.

### How are you currently working around this?

Unknown

**Comment by vito** [comment]
It feels kind of weird to support this since it means you've got implicit dependencies outside of the DAG.

@marcindulak is there a reason you can't build the image with Dagger instead?

```js
import Client, { connect } from "@dagger.io/dagger"
connect(async (client: Client) => {
  const dir = client.host().directory("/path/to/image-context")
  const node = await client.container().build(dir).exec(["node", "-v"])
  const version = await node.stdout().contents()
  console.log("Hello from Dagger and Node " + version.contents)
})
```

@dolanor 

> is this feature available in buildkit? (import an OCI tarball as a base for running a build) From a quick check, it doesn't seem so.

Unfortunately this isn't possible, much as I've tried. There's a new "OCILayout" source but I haven't found an easy way to use it for this. My past attempt is [here](https://github.com/vito/bass/commit/d617dac480dce6a5798e7212dbff96171a908612) - iirc it just barfed with a cryptic error.

**Comment by sipsma** [comment]
@vito
> Unfortunately this isn't possible, much as I've tried

I've seen a lot of commits being merged into buildkit pretty recently cleaning up things around that feature, so it'll be worth a try again once v0.11 is out I think.

Agree though that the best way to do this is to build the dockerfile in dagger. If that's impossible for some reason, let us know and we'll see if we can fix it. But the fallback option would be to mount the docker.sock into the container.

**Comment by marcindulak** [comment]
I have a setup that uses docker-compose and make to build the image locally, then the shell scripts come and exec commands in a container created from that image. I would like to keep the original image build part, and use dagger to only replace the shell scripts, so I don't need to convert the build part to dagger.

Can you provide more details about:

> But the fallback option would be to mount the docker.sock into the container.

**Comment by sipsma** [comment]
@marcindulak Cool that makes perfect sense, no need to buy in all at once if it doesn't make sense for your use case :-)

This `index.mjs` works for me when using the latest node SDK (0.3.):
```js
import { connect } from "@dagger.io/dagger";

connect(
  async (client) => {
    const output = await client
      .container()
      .from("docker:cli")
      .withUnixSocket(
        "/var/run/docker.sock",
        client.host().unixSocket("/var/run/docker.sock")
      )
      .withExec(["docker", "ps"])
      .stdout();
    console.log(output);
  },
  { LogOutput: process.stdout }
);
```

Basically, you mount the host's docker socket into the exec and then can use the docker cli as you normally would.

**Comment by slumbering** [comment]
Close this one cc @marcindulak. If you still facing issue please reopen.

**Comment by marcindulak** [comment]
For reference, here is a newer issue asking for the same https://github.com/dagger/dagger/issues/5245
