### ISSUE TITLE
mac os installation example not working

### ISSUE THREAD

**Issue by morriswinkler** [dagger/dagger#3935]
### What is the issue?

current mac os installation instruction is not working

https://github.com/dagger/dagger/blob/main/docs/current/partials/_install-sdk-cue.md

```
brew install dagger-cue
```

looking at #3474 the issue states
```
assuming will be brew install dagger-cue
```

then looking at #3486 I can see that the package was tested with:
```
brew install gerhard/tap/dagger-cue
```

Long story short: `brew install dagger-cue` doesn't work while `brew install gerhard/tap/dagger-cue` works.

I suppose either the brew tab needs still to become a homebrew  formula or  the docs need to be updated.

**Comment by morriswinkler** [comment]
The package also doesn't work

```
▊ dagger-cue project init
Project initialized! To install dagger packages, run `dagger project update`

▊ dagger-cue project update
11:44AM INFO  system | installing all packages...
11:44AM INFO  system | installed/updated package dagger.io@0.1.1
11:44AM INFO  system | installed/updated package universe.dagger.io@0.1.1

▊ dagger-cue do deps
11:45AM ERROR system | failed to load plan: package "dagger.io" (version 0.1.1) is incompatible with this version of dagger (requires 0.2.11 or newer). Run `dagger project update` to resolve this
package "dagger.io" (version 0.1.1) is incompatible with this version of dagger (requires 0.2.11 or newer). Run `dagger project update` to resolve this
```

**Comment by morriswinkler** [comment]
So for everyone having that issue, the only thing that worked for me was:

```
git clone -b v0.2.36 --depth=1 https://github.com/dagger/dagger
cd dagger
CGO_ENABLED=0 go build -o ~/go/bin/dagger ./cmd/dagger/
```

You need to update the version to the latest release  see: https://github.com/dagger/dagger/releases

**Comment by morriswinkler** [comment]
Final feedback after getting it work:

I think dagger is a great idea, having local tests reflect remote CI test is a real solution to a real problem. 

I wonder if I feel brave enough to use it professionally, but I guess as long as you stick to a version you could be fine.

The second thing I wonder is how good will that work in a real CI environment where a lot of things are dependent on stuff that is only available inside the CI . I guess it  comes down to setting up the Environment correct and rely as little as possible on stuff that is only available inside your CI. 

But yes nice work, I wish the team the best, hopefully this will fly.

**Comment by grouville** [comment]
Closing as this issue as the docs now reference the proper formula: https://docs.dagger.io/cli/465058/install

<img width="1696" alt="image" src="https://github.com/dagger/dagger/assets/31691250/31f78be6-21aa-49b2-955a-a764d81c093b">
