### ISSUE TITLE
Remote buildkit -without docker

### ISSUE THREAD

**Issue by RealHarshThakur** [dagger/dagger#3939]
### What are you trying to do?

* I'm trying to achieve a workflow where dev machines could spin up dagger engine as the state can shared on buildkit. 
* I would like to avoid using Docker to spin up Buildkit. 
* I'm okay with the responsibility of directly having to maintain buildkit - although it would be nice if Dagger could have links to Buildkit docs for operational concerns like scaling, caching, etc. 

<img width="805" alt="Screenshot 2022-11-21 at 1 58 10 PM" src="https://user-images.githubusercontent.com/38140305/203001899-9f452376-9121-46f9-9b3c-50c4f8df483d.png">

### Why is this important to you?

I think Docker should remain an optional dependency for Dagger. 

Note: this was supported in v0.3.x but recent changes(from v0.4.0 I think?) seem to have stopped picking `BUILDKIT_HOST` . 

### How are you currently working around this?

I think this could be a viable solution : https://github.com/dagger/dagger/pull/3938

**Comment by sipsma** [comment]
@RealHarshThakur Thanks for reaching out and filing this issue!

We are thinking about the best way to approach our support for this in the short term and will update you when we have a decision soon.

Two questions right away though:
1. I saw in the other PR that you wanted to use `tcp://` to connect to the remote buildkit. Do you need to also configure TLS certs to connect to it? Or do you just want to use plain tcp?
2. We have diverged a bit from the default `moby/buildkit` image and now have a few customizations that require our own image. Will that work for you provided we give you a stable image repo + tags to pull from?
   * Or is there any requirement on your side that you *must* use `moby/buildkit` for whatever reason?

**Comment by RealHarshThakur** [comment]
> Do you need to also configure TLS certs to connect to it? Or do you just want to use plain tcp?

Plain tcp works.

>  is there any requirement on your side that you must use moby/buildkit for whatever reason?
No, happy to run and operate the fork. 

> Will that work for you provided we give you a stable image repo + tags to pull from? 
Yep.

**Comment by sipsma** [comment]
>  Engine image is not necessary.

@morlay The engine image will be necessary for running any execs (on go sdk version v0.4.1 and above). We bundle a binary in the image that we use as a shim for redirecting stdio (among other things). It won't work with vanilla `moby/buildkit` anymore. We expect that divergence to grow over time too as we add more custom features, so it's not just temporary.

We're working on figuring out the path to supporting provisioning outside of docker [here](https://github.com/dagger/dagger/issues/4105) currently (but may need to break that out into separate issues depending on the direction it goes).

**Comment by morlay** [comment]
@sipsma Got it.

Could I use `ghcr.io/dagger/engine` with mounting `/etc/buildkit/buildkitd.toml`?
Just for exposing tcp address,  registry mirrors settings, and gc settings.

If it could, I really hope https://github.com/dagger/dagger/pull/3938 could be landed ASAP. 
it is the only block for me to migrate from `dagger-cue`.

Graph of @RealHarshThakur is my use case too.

Shared `buildkit` (`dagger/engine`) will be speed up the CI with controllered caches.

**Comment by RealHarshThakur** [comment]
@morlay  I think that PR won't go through as there are different plans but I'm confident Dagger team will make it easy support our use-case. I'm on v0.3.x until it's officially sorted out

**Comment by morlay** [comment]
@RealHarshThakur 

Now we could use `_EXPERIMENTAL_DAGGER_RUNNER_HOST=tcp://<engine_service_host>:1234` to connect remote dagger engine 

Just run the engine with custom `buildkitd.toml` and mount to  `/etc/dagger/engine.toml`

```toml
[grpc]
address =  ["tcp://0.0.0.0:1234"]
```

```cuelang
// pod container
containers: engine: {
	image: {
		name:      _ | *"ghcr.io/dagger/engine"
		tag:       _ | *"\(version)"
	}
	securityContext: privileged: true
	ports: tcp: 1234
	readinessProbe: {
		exec: command: ["buildctl", "--addr=tcp://0.0.0.0:\(ports.tcp)", "debug", "workers"]
		timeoutSeconds:   1
		periodSeconds:    10
		successThreshold: 1
		failureThreshold: 3
	}
}
```

**Comment by RealHarshThakur** [comment]
Nice! I haven't migrated over yet to the newer version but thanks for pointing out. Out of curiosity, how are you hosting the engine? Personally, I've this setup on [Kubernetes deployment](https://github.com/moby/buildkit/blob/master/examples/kubernetes/pod.rootless.yaml)  behind a LB in round-robin mode. 

From what you showed above, it looks as simple as changing the image. From the initial setup, I found that each Buildkit pod can only handle one request at a time i.e if a second build request arrives, the second build will fail. We're working on setting up HPA which triggers scaling based on CPU usage but I wonder if there's a more reliable metric. I assume the challenges will lie with Dagger engine too.

**Comment by morlay** [comment]
> how are you hosting the engine?

Just k8s deployments and simple service

> I found that each Buildkit pod can only handle one request at a time i.e if a second build request arrives, the second build will fail.

I have seen this issue. Maybe becasue of my buildkit configuration.
```toml
[worker.oci]
   max-parallelism = 8
```
https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md


Btw Each buildkit instance has a lockfile at `root` , so I need to set my deployment when mount HostPath / PVC 
```cue
spec: replicas: 1
spec: strategy: type: "Recreate"
```

**Comment by RealHarshThakur** [comment]
I've been using self-hosted dagger engine for some time now- closing this. Thanks team :)
