### ISSUE TITLE
✨ Release Dagger on Anaconda / Conda-Forge

### ISSUE THREAD

**Issue by Zeitsperre** [dagger/dagger#3942]
### What are you trying to do?

I would like to be able to have dagger available as a pre-compiled Python binary in my Anaconda Python environments. A package entry for dagger on Conda-forge would be ideal.

For more information: https://conda-forge.org/#add_recipe

### Why is this important to you?

Conda-forge is an integral tool for data science and reproducibility. Many complex C-based dependencies that R and Python rely on are easily accessible and installable via Anaconda/Conda-Forge, and as such using it greatly simplifies environment configurations. Dependency solving is much more refined, and it is much simpler to recreate complex environments across platforms and operating systems using Anaconda.

Dagger would be a great candidate for Conda-forge.

### How are you currently working around this?

Pip-based dependencies can be set within an environment configuration, but there are impacts to the dependency solver speed and to reproducibility. Mixing pip and Conda-forge packages is not an ideal solution, especially when creating images or configurations to be used across different platforms.

**Comment by helderco** [comment]
Thanks for making the issue! I had this on the back of my mind but I'll make it a priority.

**Comment by helderco** [comment]
I've sent a PR for the recipe but it's failing because of an outdated dependency. The dependency in question (strawberry) should be optional so I'm going to fix that, but it'll only be released in the next version which should be in a week or so.

- https://github.com/conda-forge/staged-recipes/pull/21245
- https://github.com/dagger/dagger/issues/3966
- https://anaconda.org/conda-forge/strawberry-graphql

In the meantime, you can try to expedite the update of strawberry in _conda-forge_.

**Comment by helderco** [comment]
Now stuck on poetry update_
- https://github.com/conda-forge/poetry-feedstock/pull/74#issuecomment-1323663645

**Comment by helderco** [comment]
New version of poetry has been published, will make another attempt.

**Comment by helderco** [comment]
\cc @grouville for help

**Comment by helderco** [comment]
This is currently pending review from the folks at conda forge. All checks are passing.

**Comment by helderco** [comment]
Recipe has been merged 🚀

**Comment by helderco** [comment]
FYI: https://anaconda.org/conda-forge/dagger-io
