### ISSUE TITLE
🐞 Can't run mage on macos

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#3950]
### What is the issue?

Running mage tasks locally in macos fails because, I suppose, the `test-dagger-engine` container has a binary for my host (`dagger-engine-session-darwin-arm64`) but not for running inside a container (linux in dagger-in-dagger).

Examples:
```shell
$ ./hack/make sdk:python:test
$ ./hack/make sdk:go:lint
```

### Log output

```
#0 0.056 container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/usr/bin/dagger-engine-session-linux-arm64" to rootfs at "/.dagger_engine_session" caused: stat /usr/bin/dagger-engine-session-linux-arm64: no such file or directory
```

\cc @sipsma

**Comment by sipsma** [comment]
Thanks for reporting @helderco ! Fix here https://github.com/dagger/dagger/pull/3954

I ran tests on macos after those changes manually but only direct on the host (to do the provisioning), so didn't notice this 😞 The automated macos tests should help us catch this sort of thing in the near future hopefully.
