### ISSUE TITLE
Node.js SDK document how to use `connect`'s `config` options, including `LogOutput`

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#3952]
```
connect(async (client: Client) => {

  const source = await client.host().workdir().id()
  ...

}, {LogOutput: process.stdout})
```

**Comment by slumbering** [comment]
I need to create a section in docs to explain how to improve debugging. 
Also need to add JSDocs on reference: https://docs.dagger.io/current/sdk/nodejs/reference/interfaces/connect.ConnectOpts
