### ISSUE TITLE
Use consistent default for `XDG_CACHE_HOME` across all SDKs

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3963]
On macos, the Go SDK ends up defaulting `XDG_CACHE_HOME` if not set to be `~/Library/Caches` whereas in other SDKs it defaults to be `~/.cache/` on macos. On Linux it's a consistent value right now (always defaults to `~/.cache/~`).

This isn't especially harmful but does result in an extra binary living on the local filesystem if you use both Go and non-Go SDKs on macos, whereas all the SDKs should just be sharing the same one.

It's worth checking if `~/Library/Caches` is the "more correct" default on macos (we ended up with it because we use a 3rd party `xdg` library in Go). If it is, we can switch other SDKs to use it too. (Update: `~/Library/Caches` is in fact the default for Mac OS)

If it's not a meaningful difference, then we should just switch all the SDKs to use `~/.cache` as a default consistently.

### Next steps

- [x] #4178
- [x] #4179
- [x] #4361

**Comment by helderco** [comment]
Most python projects just use `~/.cache` as default, but [xdgappdirs](https://pypi.org/project/xdgappdirs/) implements platform specific dirs. Not worth to add the dependency, but we can just port over the bit we need.

**Comment by helderco** [comment]
This one is actually up to date: [platformdirs](https://pypi.org/project/platformdirs/).

**Comment by helderco** [comment]
We're all using third-party libraries for this now:

- **Go**: https://github.com/adrg/xdg
- **NodeJS**: https://github.com/sindresorhus/env-paths
- **Python**: https://github.com/platformdirs/platformdirs

For most cases we should have the same result, but there may be some differences, for example from supported platforms or using [Known Folder](https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid)(s) in Windows before falling back to env vars.

Another big difference is that the Go library uses the `XDG_` environment variables for all platforms and only falls back to the platform dependent dirs. Usually [xdg](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) is only used in linux or unix based platforms. Some library may include macOS for example, but hardly Windows.

- https://github.com/platformdirs/platformdirs/issues/4

In Python I've compensated for this behavior in the SDK:

- https://github.com/dagger/dagger/pull/4281

However, I'm not sure if NodeJS is doing the same. I've not tried it myself but the code seems to delegate it all to the chosen library and it doesn't seem to use `XDG_CACHE_HOME` in non-linux platforms.

- https://github.com/dagger/dagger/pull/4256

With that said, to close this issue we still need to agree on how much consistency is enough. I suggest we ignore differences in supported platforms like java, plan 9 or android. Go's added support for [Known Folder](https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid)(s) is a 🤷 for me. Doesn't seem worth it to implement in the other SDKs but if that's picked on for most windows users than we're back to having different dirs per SDK for a lot of users but I know nothing about this feature.

Lastly we're left with `XDG_CACHE_HOME` and the fallback behavior. @dolanor can you confirm if NodeJS is only using it in linux?

**Comment by dolanor** [comment]
Yes, it only uses XDG related variables on linux. Not on MacOS.
But it seems the behaviour is the same for the Go lib as well?
It seems we're all good once you have yours merged, no?

**Comment by helderco** [comment]
> But it seems the behaviour is the same for the Go lib as well?

Well, it appears to me the Go library uses the XDG vars for every platform and only uses the platform specific dirs as a fallback. Am I wrong?

**Comment by helderco** [comment]
Going to take a bit of time checking differences and see if this can be closed or if some change is still required.

**Comment by helderco** [comment]
@grouville will help checking consistency.

**Comment by grouville** [comment]
## Windows

### [Go library](https://github.com/adrg/xdg)

Tested using this script:

```go
package main

import (
	"log"

	"github.com/adrg/xdg"
)

func main() {
	log.Println("Cache directory:", xdg.CacheHome)
}
```

`LOCALAPPDATA` or `%LOCALAPPDATA%`. Seems to be a protected environment variable present on most of Computers. It is safe to assume that most (+99%) of Microsoft users will have it set. I didn't manage to unset it manually, it needs super privileges, and people without it know what they do.

In below tests, the value of `LOCALAPPDATA` is:
```powershell
 $env:LOCALAPPDATA
C:\Users\dagger\AppData\Local
```

#### With `XDG_CACHE_HOME` unset, and with `LOCALAPPDATA` set

Library fallbacks to value of `LOCALAPPDATA`

```powershell
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\go> [Environment]::SetEnvironmentVariable('XDG_CACHE_HOME', $null, 'User')
# Reload shell
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\go> $env:XDG_CACHE_HOME
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\go> .\toto.exe
2023/01/10 16:57:18 Cache directory: C:\Users\dagger\AppData\Local\cache
```

#### With `XDG_CACHE_HOME` set and `LOCALAPPDATA` set

Library follows the value of `XDG_CACHE_HOME`
```powershell
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\go> $env:XDG_CACHE_HOME
C:\toto\
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\go> .\toto.exe
2023/01/10 16:51:33 Cache directory: C:\toto\
```

### [NodeJS library](https://github.com/sindresorhus/env-paths)

The NodeJS library does not take into account the value of `XDG_CACHE_HOME` at all, but also uses the `LOCALAPPDATA` on Windows.

Here is the script I worked with:
```nodejs
cat test.js
import envPaths from 'env-paths';

const paths = envPaths('dagger');

console.log(paths.cache);
```

This library automatically appends `-nodejs` to the cache subfolder:
```shell
$ node test.js
/Users/home/Library/Caches/-nodejs # in this example, envpath ==> envPaths('');
```

#### With `XDG_CACHE_HOME` unset, and with `LOCALAPPDATA` set

```powershell
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\node> [Environment]::SetEnvironmentVariable('XDG_CACHE_HOME', $null, 'User')
# Reload shell
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\node> $env:XDG_CACHE_HOME
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\node> node .\test.js
C:\Users\dagger\AppData\Local\dagger-nodejs\Cache
```

#### With `XDG_CACHE_HOME` set and `LOCALAPPDATA` set

```powershell
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\node> $env:XDG_CACHE_HOME = 'C:\toto\'
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\node> $env:XDG_CACHE_HOME
C:\toto\
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\node> node .\test.js
C:\Users\dagger\AppData\Local\dagger-nodejs\Cache
```

### [Python library](https://github.com/sindresorhus/env-paths)

Given this script:
```python
from platformdirs import *

appname = "dagger"
appauthor = "dagger"
print(user_cache_dir(appname, appauthor))
```

#### With `XDG_CACHE_HOME` unset, and with `LOCALAPPDATA` set

```powershell
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\python> $env:XDG_CACHE_HOME
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\python> python .\script.py
C:\Users\dagger\AppData\Local\dagger\dagger\Cache
```

#### With `XDG_CACHE_HOME` set and `LOCALAPPDATA` set

```powershell
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\python> $env:XDG_CACHE_HOME = 'C:\toto\'
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\python> $env:XDG_CACHE_HOME
C:\toto\
PS Microsoft.PowerShell.Core\FileSystem::\\tsclient\tmp-shared-rdp\xdg\python> python .\script.py
C:\Users\dagger\AppData\Local\dagger\dagger\Cache
```

`XDG_CACHE_HOME` env var is not taken into account either. I know that @helderco took that into account in his logic

## Summary

All three libraries have a different cache path, on Windows:
1. Both Python and NodeJS do not take the `XDG_CACHE_HOME` env var into account
2. All libraries take the `LOCALAPPDATA` env variable into account
- The Go library retrieves the value of the `localappdata`. The logic inside needs to be implemented
- The Node library takes the `localappdata` and appends inside a subdir name `appname`+`-nodejs` at the end
- The python library creates subdirs (`author`/`appname`) inside the `localappdata`

**Comment by helderco** [comment]
@grouville just some quick remarks:

- There's no need to test `%LOCALAPPDATA%` unset if that's a rare use-case. Even though the Go library handles it by looking into Known Folder, we can ignore that.
- The library path suffixes are only as important as the SDKs are using them.
- There's two parts we need to test:
  1. Fallback behavior of the libraries;
  2. How the SDKs are leveraging that; 

## 1. Libraries

Two questions we needed an answer here, which seem to be **yes** per your testing:
1. Does the Go library use `XDG_CACHE_HOME` in all platforms if defined? ✅
2. Do all libraries return the same thing on windows? ✅

## 2. SDKs

This is how the SDKs are actually calling the libraries, forget `author/appname`:

### Go

https://github.com/dagger/dagger/blob/9e60c70500c3f46e111fcee1ab7297a336abff4b/sdk/go/internal/engineconn/cli.go#L56

### NodeJS

https://github.com/dagger/dagger/blob/9e60c70500c3f46e111fcee1ab7297a336abff4b/sdk/nodejs/provisioning/bin.ts#L35

### Python

https://github.com/dagger/dagger/blob/9e60c70500c3f46e111fcee1ab7297a336abff4b/sdk/python/src/dagger/engine/download.py#L143-L145

> **Note**
> In Python, the suffix `"dagger"` is added to `XDG_CACHE_HOME` if set, not just the platform fallback. This makes it behave the same as in Go.

## Summary

So it looks to me there's **just one remaining issue** to close this: NodeJS needs to mirror Python in taking `XDG_CACHE_HOME` into consideration before the fallback.

Do you concur? If so, we need to create an issue for it.

**Comment by grouville** [comment]
> Do you concur? If so, we need to create an issue for it.

Thank you for such a great summary 😍 ! I totally concur. Here is it 🙏 https://github.com/dagger/dagger/issues/4361

**Comment by dolanor** [comment]
At first, I was for using the OS specific default dir all the time. And I thought the Go project did that as well.
But it's true XDG was there to harmonize it between all OSes. And I understand why the Go package does it that way now.
I agree we should check for XDG vars first, then use the system default.

**Comment by slumbering** [comment]
@helderco :

> In Python, the suffix "dagger" is added to XDG_CACHE_HOME if set, not just the platform fallback. This makes it behave the same as in Go.

It looks like the suffix "dagger" is added even if XDG_CACHE_HOME is not set, right ?
```python
 env = os.environ.get("XDG_CACHE_HOME", "").strip() 
 path = Path(env).expanduser() if env else platformdirs.user_cache_path() 
 cache_dir = path / "dagger" 
```

**Comment by grouville** [comment]
> CLI in a `dagger` subdir in the cache

I believe it is already automatically done in Node, when relying on the library: https://github.com/dagger/dagger/blob/9e60c70500c3f46e111fcee1ab7297a336abff4b/sdk/nodejs/provisioning/bin.ts#L35.

Given this node file:
```node
import envPaths from 'env-paths';

const paths = envPaths("dagger", { suffix: "" });

console.log(paths.cache);
```
We can see that:
```shell
$ node node test.js
/Users/home/Library/Caches/dagger
```

**Comment by helderco** [comment]
> I believe it is already automatically done in Node, when relying on the library

Yes, but not if `XDG_CACHE_HOME` is set on macOS or Windows. That's why you need to take that into consideration.

**Comment by slumbering** [comment]
@grouville : PR is ready to be reviewed #4363

**Comment by grouville** [comment]
@helderco, closing as https://github.com/dagger/dagger/issues/4361 got merged 😇
