### ISSUE TITLE
Remote Cache import/export API Proposal

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3965]
There was an earlier extremely provisional implementation of this to give a quick solution for a user who wanted it on a short term basis: https://github.com/dagger/dagger/pull/3543

There was then some discussion in that PR on how to best approach this in the long term, using this issue to continue that discussion and get consensus.

## API vs. Client Config

To start, there are different options in terms of whether we make cache import/export be part of the actual API or whether we make it more of a client config.

### Client Config
This could take the form of something like:
1. `DAGGER_CACHE_EXPORT` and `DAGGER_CACHE_IMPORT` env vars that get interpreted by each SDK and applied to the build
2. Arguments to `dagger.Connect` for setting cache imports and exports

The implementation would need to do something like set this configuration in headers that get read by the router and applied to the build.

Similar to the previous v0.2 implementation, this would need to be implemented by including every LLB vertex that occurs across the client instance in the cache exports, so fine grain control and buildkit's min/max cache settings won't be usable.

**Pros:**
1. If you want the same cache settings to apply to every vertex in a number of builds you only need to set an env var or apply a setting when you create your client

**Cons:**
1. Requires re-implementing support in each SDK rather than just picking it up as part of codegen
2. Have to come up with a schema for configuring this that is different than our graphql schema 
   * Also need it to be flexible enough to handle more import export backends and configuration in the future
1. Can't reuse our secret support for providing credentials to the cache backends (i.e. gha tokens, s3 api creds, etc.)
1. Can't choose what gets exported or choose between min/max exports
   * Selecting what gets exported is important because exporting cache adds overhead, so it's often not beneficial to just export everything.
   * See for example the problems that our CI started having after we enabled GHA caching for our whole CI builds in v0.2: https://github.com/dagger/dagger/issues/2365
   * If we support import export of cache mounts in the future (an often requested feature), getting fine grain control over this will be even more important as those cache mounts have **huge** tradeoffs in terms of whether they are efficient to remotely export vs just redownloading their contents on a cache miss.
1. No clear route to adding cache management apis (i.e. query how much storage is being used, pruning it, etc.) if we wanted to in the future

### API
This approach would put cache import/export config in the actual API. This could take many forms (and one proposal exists below) but the idea is that:
1. The cache config for different export/import targets (and the options within each target) are all defined in our graphql schema
1. You can pick and choose what to actually export as part of the API (i.e. which `Container`s or `Directory`s)
  * Additionally, if we want, we could also optionally support "global" settings that apply to the whole build too (e.g. `withCacheImports(...) Query!` type APIs), so we retain flexibility
  * This would also enable min/max settings that buildkit supports

**Pros:**
1. SDKs don't have to do any extra work on top of their existing codegen
2. Re-uses existing mechanisms for defining schemas
3. Can re-use secret support for providing credentials
4. Flexible enough to support "global" settings for cache import/exports but also easily able to support fine grain control when users need optimization (which they often do when it comes to remote caching)
5. Gives routes to supporting APIs for querying remote cache state like storage usage + pruning

**Cons:**
1. Requires explicit usage of an API by users rather than just having them set an env var and then picking that up from there.

## API Proposal (provisional)
My opinion is that we should go the API route rather than client config, so including a proposal for that API here.

**There's many many possibilities here and I'm very open to bikeshedding or completely different approaches.**

This proposal makes use of some graphql features we've previously not used like interfaces+enums, so there will be a little bit of overhead to update our codegen clients to support this. I think that's just work we'll want to do anyways and thus worth it, but I am also okay with different approaches to this API if we don't think that's a good tradeoff.

To be honest, I'm not totally convinced by this entirely, but gotta start somewhere and there are a few appealing aspects of it mentioned below. Will wait to get others thoughts before making more adjustments.

```graphql
extend type Query {
  # namespace for remoteCache backends. Optional, can skip this at cost of polluting top level namespace
  remoteCache: RemoteCache!
}

# The supported cache backends (options are mostly derived from docs here https://github.com/moby/buildkit#cache)
type RemoteCache {
  githubActions(scope: String, url: String, token: Secret!): RemoteCacheBackend!

  s3(
    bucket: String!
    region: String!
    accessKeyId: Secret!
    secretAccessKey: Secret!
    sessionToken: Secret
    blobsPrefix: String = "blobs/"
    manifestsPrefix: String = "manifests/"
    manifestName: String = "dagger"
    endpointUrl: String
    usePathStyle: Boolean
  ): RemoteCacheBackend!

  registry(ref: String!): RemoteCacheBackend!

  # TODO: others like azure + local
}

# common interface across all remote cache backends (registry, gha, s3, etc.)
interface RemoteCacheBackend {
  # use the imports of this backend as cache sources for the rest of the query
  useImports: Query!

  # push the provided containers, directories, and files with the given min/max mode to this cache backend
  pushExports(
    containers: [ContainerID!]
    directories: [DirectoryID!]
    files: [FileID!]
    mode: CacheExportMode = MIN
  ): Boolean!

  # if we want, we can also configure global cache exports for the build too with something like this
  # useExports(mode: CacheExportMode = MIN): Query!

  # Someday could add APIs for managing cache like
  # usageBytes: Integer!
  # prune(since: DateTime!): Boolean!
}

enum CacheExportMode {
  MIN
  MAX
}
```

### Example usage
```go
c, _ := dagger.Connect()

ghaCache := c.RemoteCache().GithubActions(
  c.Host().EnvVariable("GHA_TOKEN").Secret(), 
  dagger.GithubActionsOptions{
    Scope: "my-cool-scope",
  })
)

// wrap the rest of the operations with cache imports
c = ghaCache.UseImports()

// do something that's worth caching remotely, it will use the previously configured cache imports
ctr := c.Container().From("alpine").Exec([]string{"some", "expensive", "operation"})
output, _ := ctr.Stdout(ctx)

// export the cache too now
_, err := ghaCache.PushExports(containers: []*dagger.Container{ctr}, dagger.PushExportOpts{
  Mode: dagger.CacheExportModeMax,
})
```

Overall I like the fact that it becomes really easy to blanket whole sets of queries with cache imports but then pick and choose what you want to export (while still making it easy to combine a lot of exports into one by having the interface accept multiple containers, directories and files). I think that reflects the reality of what you currently need to do to use buildkit remote caching effectively.

I also like that the remote backends have their unique options in the schema while still combining them behind a common interface after the unique configuration is applied. This seems like it should support the addition of more backends in the future while also not exploding the API in size more than necessary.

---

cc @aluzzardi @vito @shykes

**Comment by cpdeethree** [comment]
Anything I can do to help move this proposal along? Trying to bring dagger to a wider audience in my org but not having the speed gains from leveraging a remote cache via sdk is kind of holding that back

**Comment by shykes** [comment]
> Anything I can do to help move this proposal along? Trying to bring dagger to a wider audience in my org but not having the speed gains from leveraging a remote cache via sdk is kind of holding that back

@cpdeethree sorry about that. This feature is held up in a design discussion on the best way to expose it. I will try to soeedyit along. While discussing we found a potentially better way to persist cache (import/export has fundamental limitations regardless of how it’s exposed). We actually have a prototype of this alternative solution that we could demo to you, if that interesting. Ok if I contact you privately to discuss your use case and how we can help?

**Comment by cpdeethree** [comment]
Sure! I will ping you on discord.

**Comment by shykes** [comment]
@sipsma resuming this discussion... My feeling is that we should *not* expose this in the API, but rather configure it at the engine config level (*not* at the client config level!). This is because IMO configuring cache is an operator concern, not a client concern.

**Comment by sipsma** [comment]
> That doesn't mean those APIs are wrong... just that they should be private to the engine. Either compiled in the engine binary, or perhaps loaded dynamically as a new kind of "caching backend".

@shykes I agree, my thinking on this has evolved since I originally wrote it. Part of the reasoning behind the proposal was that it let pipeline developers pick and choose when it was beneficial to use remote caches and when it wasn't based on their knowledge of the pipeline. But I think we (as Dagger devs) should try to make a system that enables automatic decisions on caching in combination w/ engine operator configuration. Just a much better DX.

It's certainly a hard problem but I think it's worth a shot. If we give good guidance and users set up fast cache backends then the need for finer grain optimization will shrink somewhat. That'll give us room to start simple and introduce more advanced features over time. The idea of being able to specify a `Service` that serves an API for deciding what to cache and where, similar-ish to the whole secret provider idea, is pretty intriguing in the long run.

---

I'm not sure if this is precisely what you were imagining or not, but the general idea of there being [an API for engine operators separate from the core api came up here too](https://github.com/dagger/dagger/issues/4220) and probably could be used in all sorts of different ways (e.g. configuring bootstrap services).

A cache config API for the engine can easily fit into that. It would be nice since it would keep this out of pipeline code but still allow us to reuse types from the core API as desired (e.g. secrets for configuring cache backends).

I think I will start there in terms of prototyping the implementation of this (since the need for it is imminent) but let me know if you were imagining something different or if I'm not being clear.

**Comment by TomChv** [comment]
@gerhard This issue does not seem stuck, but just waiting for an actual implementation, should we move it to `ready for work`?

**Comment by shykes** [comment]
Things have changed significantly since this issue was opened... The main change is that we have lost confidence in the synchronous cache import/export model for building scalable distributed caching. It sounds great in theory, but in practice there are too many caveats.

We still have to find the right balance between 1) not sending users down a path they will regret, and 2) still allowing an "escape hatch" for buildkit power users who understand the downsides, and still want to access the low-level buildkit feature.

I would also like to get the opinion of @sipsma and @aluzzardi on what I said above. Do you agree with me that bk import/export doesn't meet the bar for us to make it a first-class feature in Dagger? Or do you think that is excessive, and there is room for it in a production setting?

**Comment by sipsma** [comment]
> Do you agree with me that bk import/export doesn't meet the bar for us to make it a first-class feature in Dagger? Or do you think that is excessive, and there is room for it in a production setting?

I think that is right. Just in terms of documentation and time spent troubleshooting w/ users, it would get to be a huge burden; not only for us at Dagger but also for users. The subtleties, limitations and various performance problems once you get beyond the simplest use cases are so much that it's hard to justify outside of the "escape" hatch approach for power-users who know what they are doing already.

**Comment by shykes** [comment]
Closing for clarity. Let's open a new one specifically for the buildkit escape hatch.
