### ISSUE TITLE
Go SDK install partial not being used in live docs

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#3979]
@vikram I noticed that the feature of
> Go SDK no longer requires go mod replace to install

though implemented here: https://github.com/dagger/dagger/pull/3962/files#diff-06f64a45e1c277b0b72114e68d6c0936525c046b63a5d969b53e4a60a6e553adL9
and working in docs on my laptop via yarn start:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/3187222/203645280-9efdc1f6-ed79-4299-a967-bbe2a3453030.png">
 

are not working in live docs here: 
- https://docs.dagger.io/sdk/go/959738/get-started#step-3-add-the-dagger-go-sdk-to-the-module
- https://docs.dagger.io/sdk/go/371491/install

cc @aluzzardi @gerhard @slumbering

**Comment by MDr164** [comment]
It shows up correctly for me on the live docs as well. Maybe it was a caching issue of the old page being shown?

**Comment by slumbering** [comment]
@MDr164 
The fix has been actually published this morning ;). 
Close this issue
