### ISSUE TITLE
Passing build args when building from Dockerfile

### ISSUE THREAD

**Issue by tristan625** [dagger/dagger#3982]
### What are you trying to do?

i want to utilise a pre-existing Dockerfile for building an image in dagger but want to pass build args so that i can have a multiarch image.

### Why is this important to you?

Mainly It helps in creating multi-arch images which is a big

### How are you currently working around this?

building using docker cli

**Comment by marcosnils** [comment]
closing
 to prevent dupes. 

https://github.com/dagger/dagger/issues/3574
https://github.com/dagger/dagger/issues/3655

**Comment by shykes** [comment]
Bumped by "stobias123" on discord:

> Hey yall - I know there's open issues for this, but I just want to bump it. 
> I'm making a push to use dagger in the new year at my company, build args will be critical during migration
