### ISSUE TITLE
🐞 [Node SDK] `withExec` removes whitespace of arguments

### ISSUE THREAD

**Issue by phroggyy** [dagger/dagger#3990]
### What is the issue?

When calling `withExec` and passing a single argument that contains whitespace, all whitespace is stripped.

For example, `.withExec(['echo', 'foo bar'])` will print `foobar`.

The expected output is `foo bar`.

### Log output

N/A

### Steps to reproduce

1. Run the following

```ts
import Client, { connect } from "@dagger.io/dagger";

connect(async (client: Client) => {
    await client.container().from('alpine:latest')
        .withExec(['echo', 'foo bar'])
}, { LogOutput: process.stdout })
```

2. observe that the output is `foobar` rather than the expected output

### Dagger version

dagger v0.2.36 (ea275a3ba) darwin/arm64

### OS version

macOS 12.1

**Comment by dolanor** [comment]
Hi, thanks for reporting!
I'm gonna investigate this and see what's causing this.
