### ISSUE TITLE
🐞 NodeJS SDK get-started/step3 not working with @dagger.io/dagger@0.1.1

### ISSUE THREAD

**Issue by marcindulak** [dagger/dagger#3993]
### What is the issue?

The example https://github.com/dagger/dagger/blob/9466c09f5d7872ae294ea8cf3227edf3b5bbe7f5/docs/current/sdk/nodejs/snippets/get-started/step3/build.ts#L13 is not working with `@dagger.io/dagger@0.1.1`.

I believe the current usage should be
```
console.log("Hello from Dagger and Node " + version.stdout)
```

Ths problem is illustrating the comment from https://github.com/dagger/dagger/issues/3918#issuecomment-1320839613 `code sample in a separate snippets file (so it gets tested and can be reused)`.

### Log output

```
node --loader ts-node/esm build.ts
(node:664) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Hello from Dagger and Node undefined
```

### Steps to reproduce

Follow https://docs.dagger.io/sdk/nodejs/783645/get-started, using the first `build.ts` example
```sh
import Client, { connect } from "@dagger.io/dagger"

// initialize Dagger client
connect(async (client: Client) => {
  // get Node image
  // get Node version
  const node = await client.container().from("node:16").withExec(["node", "-v"])

  // execute
  const version = await node.stdout()

  // print output
  console.log("Hello from Dagger and Node " + version.contents)
})
```

```sh
npx create-react-app my-app --template typescript
cd my-app/
npm install ts-node
npm pkg set type=module
npm install @dagger.io/dagger@0.1.1 --save-dev
node --loader ts-node/esm ./build.ts
```

### Dagger version

dagger.io@dagger@0.1.1

### OS version

Alpine Linux v3.16

**Comment by marcindulak** [comment]
The github action https://github.com/dagger/dagger/actions/runs/3553457291/jobs/5968980250 which handles the issues backlog failed with
```
Projects cannot have more than 1200 items. To add more, please archive or delete existing items.
```

**Comment by dolanor** [comment]
> The github action https://github.com/dagger/dagger/actions/runs/3553457291/jobs/5968980250 which handles the issues backlog failed with
> 
> ```
> Projects cannot have more than 1200 items. To add more, please archive or delete existing items.
> ```

Created a new issue about this: https://github.com/dagger/dagger/issues/4107. Thanks for reporting!

**Comment by dolanor** [comment]
I'll close this issue as it has been fixed by https://www.npmjs.com/package/@dagger.io/dagger/v/0.2.1

I agree this is a problem linked to running docs snippets and I think it's important. We're gonna work on this!

**Comment by slumbering** [comment]
@marcindulak: The 0.1.1 is deprecated. We're returning primitives instead of objects now.

More to read here: https://github.com/dagger/dagger/pull/3956

Also docs have been updated to reflect those changes:  https://github.com/dagger/dagger/blob/main/docs/current/sdk/nodejs/snippets/get-started/step3/build.ts
