### ISSUE TITLE
🐞 The Amazon CloudFront distribution is configured to block access from Ukraine

### ISSUE THREAD

**Issue by Searge** [dagger/dagger#3994]
### What is the issue?

Hello!
I wanted to try Dagger CUE, but it turned out that Ukrainians are not allowed access.

![Prohibited content for invaded countries](https://i.imgur.com/dHqNFIt.png)

Excuse me, what does this mean?
Do you support a terrorist country in this shameful war?

### Steps to reproduce

Just download script from Ukraine.

### Dagger version

https://dl.dagger.io/dagger-cue/install.sh

### OS version

Fedora

**Comment by shykes** [comment]
Hi @Searge, sorry about that, we will investigate and look for a fix ASAP. US businesses are required by law to block access from Russian-occupied Crimea, but not from the rest of Ukraine of course. Some platforms are having difficulties making the distinction, in this case AWS. We have experienced a similar problem with another provider, and found a solution. I am confident that we can fix it in this case too. We will investigate and report back.

Thank you for the report and sorry again.

**Comment by Searge** [comment]
Hello, @shykes 

Sorry for the perhaps excessive emotionality of the message. It just hurts a little, you know.

Now everything is clear, thank you :-)

**Comment by andrii-zakurenyi** [comment]
Hi! Experiencing the same issue. Living in Kyiv, Ukraine.

![image](https://user-images.githubusercontent.com/85106843/216589991-3a13926b-d93d-429b-a7e5-0224d6b72656.png)

Error message:

```
failed to download checksums from https://dl.dagger.io/dagger/releases/0.3.10/checksums.txt: 403 Forbidden
Please visit https://dagger.io/help#go for troubleshooting guidance.exit status 1
```

If I open that URL in a browser I get:

![image](https://user-images.githubusercontent.com/85106843/216587031-4f10911e-6a24-4f91-b29d-5489a8c77d09.png)

Request ID: `yFhPXnuQ-m9LQSGt0tvXkbjv_H0ouH57S2uJ3T6jvsS7iU-0MSsbgA==`

:(

Help please.

**Comment by shykes** [comment]
Hi @andrii-zakurenyi , sorry about this. This looks like a new version of the issue. We will investigate and report back.

**Comment by shykes** [comment]
@andrii-zakurenyi I believe we have fixed it, could you check please?

@Searge I am very sorry for not fixing this sooner. I hope you are able to try again and use Dagger correctly.

Thank you both for your patience.

**Comment by jlongtine** [comment]
@andrii-zakurenyi If this isn't fixed, let me know, and I'll re-open this issue.

**Comment by Searge** [comment]
Hello, guys :-)

Yes, I can download that file, thnx!

![image](https://user-images.githubusercontent.com/2125311/216810264-8d8b1922-ffef-41d1-be48-fd5467eb0f06.png)
