### ISSUE TITLE
🐞 Go SDK: unable to get the actual error from container.WithExec()

### ISSUE THREAD

**Issue by jritsema** [dagger/dagger#3997]
### What is the issue?

Hello.  I'm new to Dagger and I'm running Terraform using the Go SDK and am unable to get the actual error from the `terraform init` command running inside the container.  How can I see the underlying error?  What am I doing wrong?

```
did not complete successfully: exit code: 1
```

### Log output

```
input:1: container.from.withMountedDirectory.withWorkdir.withExec.withExec.stdout process "/bin/terraform init -backend-config='bucket=123456789012' -backend-config='key=terraform.tfstate'" did not complete successfully: exit code: 1

Please visit https://dagger.io/help#go for troubleshooting guidance.
```

### Steps to reproduce

```go
tf := client.Container().From("hashicorp/terraform:1.3.4")
tf = tf.WithMountedDirectory("/src", src).WithWorkdir("/src")

tf = tf.WithExec([]string{"init",
  fmt.Sprintf(`-backend-config='bucket=%s'`, bucket),
  fmt.Sprintf(`-backend-config='key=%s.tfstate'`, environmentName),
})
if out, err := tf.Stdout(ctx); err == nil {
  fmt.Println(out)
} else {
  return err
}
```

### Dagger version

dagger.io/dagger v0.4.1; go version go1.19 darwin/arm64

### OS version

macos 12.6.1

**Comment by marcmodin** [comment]
I have also run into this. Did you find out how to get the output required?

**Comment by jritsema** [comment]
No. I gave up on Dagger (for now).

**Comment by aluzzardi** [comment]
I believe this has been fixed /cc @sipsma

**Comment by sipsma** [comment]
Yes, this will be fixed in the upcoming release (should be next Monday at the latest). After that you can upgrade your go sdk version and the stdout+stderr will be included in the error object whenever an Exec fails (exits non-zero) @jritsema @marcmodin 

Gonna close this issue as it is resolved in our main branch, but please let me know if you have any further questions.

**Comment by jritsema** [comment]
Confirmed this is working now!  Thanks for addressing so quickly.  I'm excited about Dagger.
