### ISSUE TITLE
🐞 [Node SDK] build and publish break

### ISSUE THREAD

**Issue by phroggyy** [dagger/dagger#3998]
### What is the issue?

When using the `.build()` or `.publish()` methods on a `Container`, execution fails with an `ECONNREFUSED`, indicating that the engine API is not responding.

I expect `build` and `publish` to work.

### Log output

```
{
  "message": "request to http://127.0.0.1:62356/query failed, reason: connect ECONNREFUSED 127.0.0.1:62356",
  "type": "system",
  "errno": "ECONNREFUSED",
  "code": "ECONNREFUSED"
}
```

### Steps to reproduce

Run the following:

```ts
import Client, { connect } from "@dagger.io/dagger"

const workDir = '/workspace'

connect(async (client: Client) => {
    const container = client.container().from('nginx:latest')
        // .export('./build.tar.gz')
        // .publish('phroggyy/nginx:latest')
        
    const out = await container.stdout()
    console.log('returning output', out.stdout)
}, { LogOutput: process.stdout })
```

1. Run it as is, it will work.
2. Uncomment either the `.export()` or `.publish()` line, and remove the last two lines (as `.stdout()` doesn't work on the output of `export` and `publish`).
3. Run it again, get `ECONNREFUSED.

### Dagger version

dagger 0.2.36

### OS version

macOS 12.1

**Comment by phroggyy** [comment]
Bug between chair and keyboard. Might be useful to catch this somewhere in the SDK and provide a more useful error message, like "you probably need to `await` your call".

**Comment by helderco** [comment]
Ok, can you create a new issue for that? And close this one if there's no issue with `export` and `publish`?
