### ISSUE TITLE
✨ [Node SDK] helpful error messages when await is missing

### ISSUE THREAD

**Issue by phroggyy** [dagger/dagger#4000]
### What are you trying to do?

Relates to #3998.

When calling `.build` or `.publish` without `await`ing the result, you get an `ECONNREFUSED` error. The graphql client (or some other component) should be able to catch this and write a nicer error to the user, like "Failed to connect to Dagger engine, you might need to add await to your call".

### Why is this important to you?

It's easy to forget the `.await` call, especially as some calls (e.g all `with*` calls that just configure the container) do not return a promise.

### How are you currently working around this?

Asking in the discord until someone points out (or I realise) that I failed to RTFM 😄

**Comment by slumbering** [comment]
hey @phroggyy 👋 
You're totally right. We are currently working on this PR: https://github.com/dagger/dagger/pull/3947 that is handling by @benjaminstrasser. You can have a look at it :)
It should be shipped very soon

**Comment by benjaminstrasser** [comment]
@phroggyy 
I am currently trying to fully understand what causes an error on your side to make sure #3947 is giving sensible feedback. Could you provide an example, which throws this error?

**Comment by slumbering** [comment]
Hey @phroggyy ! If you're using TS, you should have something like this that let you know that `await` is unnecessary.

<img width="729" alt="Capture d’écran 2022-12-13 à 15 33 43" src="https://user-images.githubusercontent.com/1186424/207361278-bb8c4229-a799-4246-86f8-20e4cca84501.png">

Could you provide an example where you get an error when not using an await please 🙏  ? Many thanks

**Comment by slumbering** [comment]
Close this one. If you feel that we're missing something @phroggyy please reopen this issue
