### ISSUE TITLE
CLI release test

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#4002]
Issue to track progress on the CLI release.

- [x] `curl -L https://dl.dagger.io/dagger/install.sh DAGGER_VERSION=? | sh`
- [x] `brew install dagger/tap/dagger` - for [our tap formula](https://github.com/dagger/homebrew-tap)
  - Move the existing `dagger.rb` to `dagger@0.2.rb`
- [x] `brew install dagger` - for [bottled formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dagger.rb)
  - Move the existing `dagger.rb` to `dagger@0.2.rb`

**Comment by gerhard** [comment]
We first want to try this out with a pre-release, e.g. `v0.3.6-alpha.1`
