### ISSUE TITLE
Github repository website shows wrong "latest" release

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#4014]
## Problem

When navigating to https://github.com/dagger/dagger, there is a "releases" widget that shows the latest release. That widget currently indicates that *v0.2.36* is the latest release, which is incorrect (the latest dagger engine release is in fact 0.3.5).

The reason for this is that github defines "release" narrowly as "the act of using the Github release feature". However the Dagger Engine since 0.3.0 has been released by setting a git tag. Per Github's narrow proprietary definition, nothing is wrong. However, something clearly *is* wrong: people visiting our github repository page are misled into thinking 0.2.36 is our latest available version of the software, which it is not.

## Solution

Unclear.

Perhaps the imminent CLI 0.3.x release will coincide with an engine release, and use the proprietary github release feature? If so, perhaps the problem will resolve itself shortly?

**Comment by gerhard** [comment]
No longer an issue, works as expected:

<img width="1428" alt="Screenshot 2023-05-07 at 10 52 26" src="https://user-images.githubusercontent.com/3342/236670463-8a14eef8-17d1-426a-93e9-2d64bbea26d3.png">
