### ISSUE TITLE
Update NodeJS getting started following all the breaking changes in v0.3.0

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#4018]
### What is the issue?

Since now we split required args and optional args, we need to update the code in the documentation. Other breaking changes might have to update the documentation as well.

## Tasks
- [ ] update `host.workdir()` part with new API

**Comment by dolanor** [comment]
cc @vikram-dagger : we talked about this today. You can close this issue when it's up to date with v0.3.0 (got released a few minutes ago)

**Comment by vikram-dagger** [comment]
It seems like the get started snippets are already up to date @dolanor. Was there a specific issue you found which requires changes?

**Comment by dolanor** [comment]
No, as I said, I created before we talked together and you released an update. It now should be good.
