### ISSUE TITLE
make Go codegen coherent with the nodejs one

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#4032]
based on https://github.com/dagger/dagger/pull/3606#issuecomment-1319309884, we need to refactor the Go codegen to make it more coherent with the NodeJS one.

cc @aluzzardi

**Comment by slumbering** [comment]
@aluzzardi is still a priority ? Thanks

**Comment by TomChv** [comment]
I'm closing this issue since we're pretty stable on the codegen and do not plan to change it.

We already made severals progress on making the codegen more reusable.
