### ISSUE TITLE
Node.js SDK - Ref docs needs to be improved

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#4036]
Our current ref docs need to be reviewed. Some outputs are not displayed in the good place.
For instance Type aliases `FileID` is displayed here :https://docs.dagger.io/current/sdk/nodejs/reference/modules/api_client_gen
A better place to display it could here:
https://docs.dagger.io/current/sdk/nodejs/reference/classes/api_client_gen.default/#file

The `Client` class is also renamed to `default` which doesn't make sens.
https://docs.dagger.io/current/sdk/nodejs/reference/classes/api_client_gen.default

**Comment by dolanor** [comment]
From #4147 
> ## NodeJS reference name for the default client should be more explicit
> Right now, the name of it is: default.
> When I was doing some demo, I couldn't find the API for the client, because it was not shown, except under default which was not clear at all.
> 
> maybe defaultClient at least?

**Comment by TomChv** [comment]
Our reference TS doc is way better than before: https://docs.dagger.io/reference/typescript/modules/api_client_gen
I think we can close this issue since it's a pretty old one and we can reopen a new one if we catch anything new.
