### ISSUE TITLE
Update SDKs to use dagger session token

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#4040]
`dagger run` now uses a session token in http basic auth to safeguard the localhost listener. The SDKs should be updated similarly.

There's a choice between:
1. Having the SDKs generate the session token and tell the engine session bin
2. Having the engine session bin generate the token and tell the SDK

My preference is currently 2 because:
1. It more closely matches what we do in the `dagger run` case in that the CLI does the token creation
   * We don't need the CLI to support both the case where it generates the token and sets the env var AND the inverse case
2. Getting the token can be implemented the same way as how we currently get the port: by reading it over the stdout pipe of the subprocess
3. Avoids each SDK needing to securely generate the token and securely pass it to the subprocess

**Comment by helderco** [comment]
@sipsma This has been implemented in https://github.com/dagger/dagger/pull/4145, right?

**Comment by sipsma** [comment]
@helderco yes, thanks for the ping! closing
