### ISSUE TITLE
NodeJS: Inconsistent object modification behavior

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#4079]
Some functions are returning a new state whereas others are modifying the object in-place.

- `exitCode()` modifies in-place:
https://github.com/dagger/dagger/blob/f378cabc6254b69fc1f4765d3c83e57e12057841/sdk/nodejs/api/client.gen.ts#L255-L260
- `withExec()` returns a copy:
  https://github.com/dagger/dagger/blob/f378cabc6254b69fc1f4765d3c83e57e12057841/sdk/nodejs/api/client.gen.ts#L575-L579

We should make that consistent across the board, and should always return a copy to be consistent with the other SDKs.

Furthermore, I **think** the following major problem happens:

```typescript
const ctr = ...
const foo = ctr.exitCode() // <-- { exitCode }
const bar = ctr.stdout() // <-- { exitCode { stdout } } *** invalid query ***
```

**Comment by slumbering** [comment]
Thanks @aluzzardi. 
related PR #4081
