### ISSUE TITLE
Container From removes existing env vars

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#4085]
Example: https://play.dagger.cloud/playground/JBT8x7KCicC
```graphql
{
  container {
    withEnvVariable(name:"FOO", value:"BAR") {
      from(address:"alpine:latest") {
        withExec(args:["env"]) {
          stdout
        }
      }
    }
  }
}
```
That will not show `FOO` in the output.

---

I suppose the correct behavior is not totally obvious, but I'd argue that we should not remove existing env vars because:
1. It can be nice for certain use cases. I was trying to set some env vars that would be shared across all our sdk base containers but I couldn't set them in a common base container because each SDK calls `From`.
2. Other APIs like `WithMountedFile` change the container state but don't get removed by calling `From`, so we should be consistent one way or the other at least

**Comment by vito** [comment]
Though it seems also worth mentioning that the current name (`from`) definitely feels more like a replacement to me.

If we were to normalize on `WIthX` for additive changes I suppose we could rename it to, or add, something like `WithImageConfig`?

**Comment by sipsma** [comment]
> Maybe the mental model here is that from should be analogous to withXXX for every XXX set by the image config ([ref](https://github.com/opencontainers/image-spec/blob/main/config.md))?

Agreed that should be the behavior, I think it creates the most consistency.

> If we were to normalize on WIthX for additive changes I suppose we could rename it to, or add, something like WithImageConfig?

Also agree that hindsight being 20/20 `From*` sticks out and breaks the pattern of the rest of the APIs. `WithImage` would make more sense to me. That's a separate issue from this one though.

**Comment by dolanor** [comment]
Concerning #4455, should we already apply that without adding `withImage` first?

Would there be a need for a dedicated `from` function? Or the first `withImage` called would serve as a `from`?
Hence, would we deprecate `from`?
