### ISSUE TITLE
✨ Rust SDK

### ISSUE THREAD

**Issue by milewski** [dagger/dagger#4088]
Hi is there any plan for a Rust SDK?

**Comment by grouville** [comment]
Hi,
I also wanted one. However, it's not our priority atm, as we are still adding features to the core engine. If you want to do it though, we're here to help you along the way 😇

**Comment by mircubed** [comment]
@kjuulh is working on one here :) https://github.com/kjuulh/dagger-rs

Reference: 
They mentioned it on Discord [here](https://discord.com/channels/707636530424053791/708371226174685314/1068975704441626694). 

They will be presenting an update during the Feb 23rd community call @milewski

**Comment by helderco** [comment]
Done in:
- https://github.com/dagger/dagger/pull/5148
