### ISSUE TITLE
Automated changelog generation and/or semantic versionning bump

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#4090]
context: https://discord.com/channels/707636530424053791/1048264718369951854

I think we could use some tooling to help us for generating better changelog, and maybe even automate some version bumping.

I see we could maybe use: https://pkg.go.dev/golang.org/x/exp@v0.0.0-20221204150635-6dcec336b2bb/apidiff#section-readme for tracking the engine and the Go SDK. I don't know for other languages.

cc @gerhard @aluzzardi @sipsma @vito

**Comment by jedevc** [comment]
We now use `changie` for doing this - see https://github.com/dagger/dagger/blob/main/RELEASING.md for more information on our release process.
