### ISSUE TITLE
most GraphQL field params documentation are empty

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#4092]
### What is the issue?

Sometimes, their names are explicit enough, sometimes, they are not

eg.: https://pkg.go.dev/dagger.io/dagger#ContainerOpts
What is a platform? What's its format? Going to https://pkg.go.dev/dagger.io/dagger#Platform doesn't give more information. Especially that the platform supported are limited to `linux/` for now

We should fill out more of these documentation to make the generated SDK reference documentation more useful to our users.

cc: @aluzzardi @shykes @vikram-dagger

**Comment by dolanor** [comment]
So I wanted to point @vikram-dagger on the source files to update for having documentation, but I struggle to understand what can be modified to add those information.

On the [GraphQL spec](https://spec.graphql.org/October2021/#sec-Comments), comments are prefixed by `#`, though, in our own graphqls code, we use `"` or `"""` blocks for multiline comments.
I don't know where it comes from, or how it works.
I guess we could add some directives (like a `@param(desc: String!)` to put next to each field), or in the multiline comments in the form of `@param Xxx represents yyy`.

I tried to see where we generate the schema, but I don't see past our deps `dagger/graphql` and it's a little bit too involved for me.

So, my question is: how could we document those params directly in the `.graphqls`?

cc: @aluzzardi

**Comment by dolanor** [comment]
Actually, I see how we did it in on of the few cases we had documentation for params: https://github.com/dagger/dagger/blob/main/core/schema/container.graphqls#L134-L150
```graphqls
  "This container after executing the specified command inside it"
  withExec(
    "Command to run instead of the container's default command"
    args: [String!]!
    "Content to write to the command's standard input before closing"
    stdin: String
    "Redirect the command's standard output to a file in the container"
    redirectStdout: String
    "Redirect the command's standard error to a file in the container"
    redirectStderr: String
    """
    Provide dagger access to the executed command
    Do not use this option unless you trust the command being executed
    The command being executed WILL BE GRANTED FULL ACCESS TO YOUR HOST FILESYSTEM
    """
    experimentalPrivilegedNesting: Boolean
  ): Container!
```

We simply explode the params 1 per line and prefix by a `"` comment on the line above.

@aluzzardi : my question still holds: why are we different from the GraphQL spec and how is it not documented as an alternative in the GraphQL spec?

**Comment by TomChv** [comment]
However, if we add documentation on a required parameter that is not part of a struct, this piece of documentation does not appear on Go and Node SDK.

I was improving the doc to fix https://github.com/dagger/dagger/issues/4089#issuecomment-1340980931 and bunch of stuff but I figure out this bug.
We need to fix this issue to strongly improve the documentation.


### Repro case

Update `container.graphqls`:`line 189`
```diff
-  "Publish this container as a new image, returning a fully qualified ref"
-  publish(address: String!, platformVariants: [ContainerID!]): String!
+  "Publish this container as a new image, returning a fully qualified ref."
+  publish(
+    "Address to publish the image to. Formatted as <host/user/repo:tag> (E.g. docker.io/dagger/dagger:main)."
+    address: String!,
+    "Identifiers of related containers for a multi-platform image."
+    platformVariants: [ContainerID!]
+  ): String!
```

Generate doc

```shell
./hack/make sdk:all:generate
```

See outputs in Python, `address` is explained

```python
    async def publish(
        self, address: str, platform_variants: "list[Container] | None" = None
    ) -> str:
        """Publish this container as a new image, returning a fully qualified
        ref.

        Parameters
        ----------
        address:
            Address to publish the image to. Formatted as <host/user/repo:tag>
             (E.g. docker.io/dagger/dagger:main).
        platform_variants:
            Identifiers of related containers for a multi-platform image.
```

But not in Go or Typescript.

```diff
--- a/sdk/nodejs/api/client.gen.ts
+++ b/sdk/nodejs/api/client.gen.ts
@@ -87,6 +87,9 @@ export type ContainerExportOpts = {
 }
 
 export type ContainerPublishOpts = {
+  /**
+   * Identifiers of related containers for a multi-platform image.
+   */
   platformVariants?: ContainerID[] | Container[]
 }
 
@@ -504,7 +507,7 @@ export class Container extends BaseClient {
   }
 
   /**
-   * Publish this container as a new image, returning a fully qualified ref
+   * Publish this container as a new image, returning a fully qualified ref.
    */
   async publish(address: string, opts?: ContainerPublishOpts): Promise<string> {
     const response: Awaited<string> = await queryBuilder(
```

```diff
--- a/sdk/go/api.gen.go
+++ b/sdk/go/api.gen.go
@@ -305,10 +305,11 @@ func (r *Container) Platform(ctx context.Context) (Platform, error) {
 
 // ContainerPublishOpts contains options for Container.Publish
 type ContainerPublishOpts struct {
+       // Identifiers of related containers for a multi-platform image.
        PlatformVariants []*Container
 }
 
-// Publish this container as a new image, returning a fully qualified ref
+// Publish this container as a new image, returning a fully qualified ref.
 func (r *Container) Publish(ctx context.Context, address string, opts ...ContainerPublishOpts) (string, error) {
        q := r.q.Select("publish")
        q = q.Arg("address", address)
```

**Comment by dolanor** [comment]
Good catch @TomChv . I'm gonna investigate.
I'll create an issue out of your post.

**Comment by slumbering** [comment]
Follow-up in #4129
