### ISSUE TITLE
Ability to run the same command again

### ISSUE THREAD

**Issue by vito** [dagger/dagger#4118]
I worded the title this way because I don't think we want to go full "skip cache." If I run a command that uses a cache mount, and I want to run it again, that defeats the point of the cache mount. (With Buildkit, using `llb.IgnoreCache` does both.)

**Comment by sipsma** [comment]
I have an issue for figuring out the various ways of disabling cache here: https://github.com/dagger/dagger/issues/3073

Let me know if you agree it's a dupe @vito

**Comment by vito** [comment]
Oh cool, yeah I'll close this!
