### ISSUE TITLE
some func param documentation is missing in Go and TS

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#4129]
> If we add documentation on a required parameter that is not part of a struct, this piece of documentation does not appear on Go and Node SDK.
> 
> I was improving the doc to fix https://github.com/dagger/dagger/issues/4089#issuecomment-1340980931 and bunch of stuff but I figure out this bug.
> We need to fix this issue to strongly improve the documentation.
> 
> ### Repro case
> 
> Update `container.graphqls`:`line 189`
> ```diff
> -  "Publish this container as a new image, returning a fully qualified ref"
> -  publish(address: String!, platformVariants: [ContainerID!]): String!
> +  "Publish this container as a new image, returning a fully qualified ref."
> +  publish(
> +    "Address to publish the image to. Formatted as <host/user/repo:tag> (E.g. docker.io/dagger/dagger:main)."
> +    address: String!,
> +    "Identifiers of related containers for a multi-platform image."
> +    platformVariants: [ContainerID!]
> +  ): String!
> ```
> 
> Generate doc
> 
> ```shell
> ./hack/make sdk:all:generate
> ```
> 
> See outputs in Python, `address` is explained
> 
> ```python
>     async def publish(
>         self, address: str, platform_variants: "list[Container] | None" = None
>     ) -> str:
>         """Publish this container as a new image, returning a fully qualified
>         ref.
> 
>         Parameters
>         ----------
>         address:
>             Address to publish the image to. Formatted as <host/user/repo:tag>
>              (E.g. docker.io/dagger/dagger:main).
>         platform_variants:
>             Identifiers of related containers for a multi-platform image.
> ```
> 
> But not in Go or Typescript.
> 
> ```diff
> --- a/sdk/nodejs/api/client.gen.ts
> +++ b/sdk/nodejs/api/client.gen.ts
> @@ -87,6 +87,9 @@ export type ContainerExportOpts = {
>  }
>  
>  export type ContainerPublishOpts = {
> +  /**
> +   * Identifiers of related containers for a multi-platform image.
> +   */
>    platformVariants?: ContainerID[] | Container[]
>  }
>  
> @@ -504,7 +507,7 @@ export class Container extends BaseClient {
>    }
>  
>    /**
> -   * Publish this container as a new image, returning a fully qualified ref
> +   * Publish this container as a new image, returning a fully qualified ref.
>     */
>    async publish(address: string, opts?: ContainerPublishOpts): Promise<string> {
>      const response: Awaited<string> = await queryBuilder(
> ```
> 
> ```diff
> --- a/sdk/go/api.gen.go
> +++ b/sdk/go/api.gen.go
> @@ -305,10 +305,11 @@ func (r *Container) Platform(ctx context.Context) (Platform, error) {
>  
>  // ContainerPublishOpts contains options for Container.Publish
>  type ContainerPublishOpts struct {
> +       // Identifiers of related containers for a multi-platform image.
>         PlatformVariants []*Container
>  }
>  
> -// Publish this container as a new image, returning a fully qualified ref
> +// Publish this container as a new image, returning a fully qualified ref.
>  func (r *Container) Publish(ctx context.Context, address string, opts ...ContainerPublishOpts) (string, error) {
>         q := r.q.Select("publish")
>         q = q.Arg("address", address)
> ```
> 
> _Originally posted by @TomChv in https://github.com/dagger/dagger/issues/4092#issuecomment-1341963453_

- [x] #4132
- [ ] #4133

**Comment by aluzzardi** [comment]
+1 on fixing both

@dolanor Can you take care of it?

**Comment by dolanor** [comment]
I was going to work on it this week, but it seems @TomChv has already done a pass with #4240 :+1:
I'm gonna add my suggestions if I find some.

**Comment by slumbering** [comment]
Should we close this issue @dolanor ?

**Comment by TomChv** [comment]
I think we can close it!
