### ISSUE TITLE
NodeJS reference name for the default client should be more explicit

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#4147]
### What is the issue?

Right now, the name of it is: `default`.
When I was doing some demo, I couldn't find the API for the client, because it was not shown, except under `default` which was not clear at all.

maybe `defaultClient` at least?

cc @slumbering

**Comment by slumbering** [comment]
The problem is coming from the way typedoc generate the docs. I didn't figure it out yet.
This issue is related to #4036 
Could you please close it and add your comment above on #4036
Thanks :)

**Comment by dolanor** [comment]
Done. Duplicate with #4036
