### ISSUE TITLE
Split EngineSessionPortParseError in different errors

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#4149]
Sorry I haven't been able to pitch in during the error handling PR. I come after the fact.

I've read the documentation of https://docs.dagger.io/current/sdk/nodejs/reference/classes/common_errors.EngineSessionPortParseError and it seems to me that either the name of the error is confusing, or its behavior is.

If it's a parse error, then it should be thrown at parsing time. It should not be thrown if it times out.

I guess (with my limited JS/TS knowledge) that it's thrown by a function that could fail different ways. Is it possible to throw 3 errors instead on our side?
- EngineSessionPortParseError
- EngineSessionConnectionTimeoutError
- EngineSessionEOFError
?

cc: @slumbering @benjaminstrasser

**Comment by benjaminstrasser** [comment]
As I was just quickly naming errors on what I thought was going on this is much appreciated. I'll open a PR right away.

**Comment by benjaminstrasser** [comment]
tagging #4156

**Comment by slumbering** [comment]
Close this one as completed #4156
