### ISSUE TITLE
Cannot get size of file > 2.14GB (max int32)

### ISSUE THREAD

**Issue by vito** [dagger/dagger#4152]
### What is the issue?

If I try to get the `size` of a file that's larger than max int32 (2147483647 bytes or ~2.14GB), I get an error.

The [GraphQL spec](https://graphql.org/learn/schema/#scalar-types) has this to say:

> `Int`: A signed 32‐bit integer.

So we might need a different representation here.

### Log output

```
Cannot return null for non-nullable field File.size.
```

### Steps to reproduce

https://play.dagger.cloud/playground/sNxo3mQis2M

```graphql
query {
  container {
    from(address: "alpine") {
      withExec(args: ["dd", "if=/dev/zero", "of=./foo", "bs=1000", "count=2147484"]) {
        file(path:"foo"){
          size
        }
      }
    }
  }
}
```

### Dagger version

24c0ac804d5c9c3ecdd2c6c565ee9799653c3313 (`master`, but all versions)

### OS version

Linux

**Comment by sipsma** [comment]
Great catch, on a less urgent note we'll also run into problems representing dates w/ unix time after 2038 :-)

My immediate thought is to create a custom scalar that replaces the 32 bit Int w/ a 64 bit one. We'll be able to parse it ourselves and thus choose which maximum we want. I *think* it's even possible for us to override the default "Int" scalar rather than having to switch to something like `Int64` and update our schemas everywhere, but not sure of the full implications of doing this.

Worth seeing what other graphql users do to deal with this out in the world.

**Comment by vito** [comment]
> Great catch, on a less urgent note we'll also run into problems representing dates w/ unix time after 2038 :-)

Yup, just ran into this while trying to implement `Directory { stat }`. :sweat_smile: (Except it was for the `mode` field, since we're not in 2038 yet.)

> My immediate thought is to create a custom scalar that replaces the 32 bit Int w/ a 64 bit one. We'll be able to parse it ourselves and thus choose which maximum we want. I _think_ it's even possible for us to override the default "Int" scalar rather than having to switch to something like `Int64` and update our schemas everywhere, but not sure of the full implications of doing this.

Given we need to support JavaScript and its wacky numbers, seems like we'd need to limit ourselves to `9007199254740991`:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

I wonder if we should represent times as RFC3339 timestamps instead. Especially if someone wants nanosecond precision. :scream:

**Comment by jlongtine** [comment]
I was curious about custom scalars for mode/permissions for #3167, too, which is a `uint32`: [`type FileMode uint32`](https://pkg.go.dev/io/fs#FileMode).

Not quite sure what that might mean for client code generation, though.

**Comment by jlongtine** [comment]
@sipsma @vito Found this code for creating custom scalars, by the by: https://github.com/graphql-go/graphql/blob/v0.8.0/examples/custom-scalar-type/main.go

**Comment by grouville** [comment]
Update:
- https://github.com/dagger/dagger/pull/5227 seems to prove that this works.

Now, once https://github.com/dagger/graphql/pull/2 is reviewed, I will be able to bump #5227 to reference the new commit hash of the master branch

**Comment by grouville** [comment]
@JammUtkarsh, as stated by Erik above: 
> Great catch, on a less urgent note we'll also run into problems representing dates w/ unix time after 2038 :-)

You could take reference on all PRs referenced on this issue to try fixing the Unix Time issue
