### ISSUE TITLE
Lack of documentation on setting up a new typescript project (tsconfig.json, etc)

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#4180]
### What is the issue?

Following https://discord.com/channels/707636530424053791/1045683363496869950/1047108076823642132
We have a getting started that base itself on a react app template. As such, it has some TypeScript project files, like the [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#handbook-content).
We need to create some documentation for people who wants to use TypeScript but always bootstrapped them with tools and never had to edit a `tsconfig.json` file. (I must say the documentation on this file on the official typescript is not shown at first at all…)

**Comment by slumbering** [comment]
cc @vikram-dagger WDYT ?

**Comment by TomChv** [comment]
Related to #4311

**Comment by TomChv** [comment]
@vikram-dagger Is this issue stil accurate? A lot of improvement happened on this aspect and we now have doc for ESM, Typescript and CommonJS

**Comment by TomChv** [comment]
I think we can close this issue, our new doc pretty much explain all the init directory
- https://docs.dagger.io/developer-guide/typescript/370239/module-structure
- https://docs.dagger.io/developer-guide/typescript/629502/ide-integration
- https://docs.dagger.io/developer-guide/typescript/506316/first-module
