### ISSUE TITLE
Python: force keyword arguments for optional parameters

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#4182]
## Overview

Even though you can easily reach for a named parameter in Python, I think we should make it required for optional parameters.

This is to **avoid** someone actually using positional params even though it's obvious that named is better here.

## Example

```python
# ❌ don't allow this
ctr.with_exec(["wat"], None, None, "/out/stderrr")

# ✅ force this instead
ctr.with_exec(["wat"], redirect_stderr="/out/stderr")
```

## Motivation

- Clearer when reading code
- Order of params can change if a new one is added

**Comment by helderco** [comment]
I'm second guessing this decision because there's some simple use cases of fields with a single optional argument, or two. Not worth forcing in these cases. Also not worth triggering this based on num of params. It's actually rarer that there's many like in `with_exec`, so I'll let this simmer for a few days.

**Comment by helderco** [comment]
I'm reopening because I've seen more cases of `ctr.with_exec(["wat"], None, None, "/out/stderrr")` or `.directory("/path", None, ["src"])`.

**Comment by gerhard** [comment]
💙 `wat`
