### ISSUE TITLE
Rename `id` argument name in fields that don’t return its type

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#4192]
Some top-level fields return an object if you have their ID:

```graphql
type Query {
    container(id: ContainerID, platform: Platform): Container!
    directory(id: DirectoryID): Directory!
    file(id: FileID!): File
    secret(id: SecretID!): Secret!    
    socket(id: SocketID): Socket!
}
```

There’s one exception to this “rule”. I think it makes sense for us to rename this parameter to make it more consistent:

```diff
type Container {
  "Initializes this container from this DirectoryID."
- withRootfs(id: DirectoryID!): Container!
+ withRootfs(directory: DirectoryID!): Container!
}
```

### Notes
- `directory` is consistent with `withDirectory(path: String!, directory: DirectoryID!)`. `withRootfs` is similar just with `path` set to `/`;
- `Container.withFS` doesn’t matter as it’s deprecated and is going to be removed;
- Downside is the breaking change but for codegen clients, `withRootfs`‘s `id` being a required argument, the name is hidden from usage so it shouldn’t actually break most users;
- This was surfaced in https://github.com/dagger/dagger/issues/4191.

**Comment by dolanor** [comment]
I also found that some optional methods parameters are named `id` when passing the object makes more sense. We should rename them as well.

example:
```diff
export type ClientContainerOpts = {
-  id?: ContainerID | Container
+  id?: Container
   platform?: Platform
}
```

**Comment by helderco** [comment]
@dolanor I'm pretty sure all those optional `id`s are meant to keep their `ID`. Have something been added in the meantime?

Your `ClientContainerOpts` example comes from here:

```graphql
extend type Query {
  """
  Load a container from ID.
  Null ID returns an empty container (scratch).
  Optional platform argument initializes new containers to execute and publish as that platform. Platform defaults to that of the builder's host.
  """
  container(id: ContainerID, platform: Platform): Container!
}
```

So we do mean to pass an ID here, to get the corresponding `Container` object.

**Comment by gerhard** [comment]
We intend to implement this breaking change for:
- https://github.com/dagger/dagger/discussions/5374
