### ISSUE TITLE
Docs: use graphql document in shell scripting example

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#4198]
## Problem

In the guide "[Run pipelines from the command line](https://docs.dagger.io/cli/389936/run-pipelines-cli)", graphql queries are inlined in the shell script. This is less convenient than if they used the available feature of writing queries to a separate graphql file, and referencing them by name.

## Solution

Change the docs to use graphql documents in their examples.

**Comment by rmodpur** [comment]
@shykes I would like to start contributing to dagger, can i pick this up if no one is working on it ?

**Comment by shykes** [comment]
Closing, this as it is deprecated by `dagger call`.

**Comment by shykes** [comment]
PS. I am very sorry @rmodpur that we never got to your PR. We got overwhelmed by the volume of contributions, trying to be better about it now.
