### ISSUE TITLE
nodesdk/docs : Error Codes

### ISSUE THREAD

**Issue by benjaminstrasser** [dagger/dagger#4226]
LGTM 🚀 

Next step will be to add error codes to doc refs.

_Originally posted by @slumbering in https://github.com/dagger/dagger/pull/4156#pullrequestreview-1224147004_

**Comment by benjaminstrasser** [comment]
Docs currently look like this.
It's simply all the error codes and a linkage to the detailed error page.

![image](https://user-images.githubusercontent.com/55442329/208631644-09f6bb10-a675-4760-8472-432a1242093d.png)

**Comment by slumbering** [comment]
> Docs currently look like this. It's simply all the error codes and a linkage to the detailed error page.
> 
> ![image](https://user-images.githubusercontent.com/55442329/208631644-09f6bb10-a675-4760-8472-432a1242093d.png)

Oh you're right ! Thanks ! close this one then.
