### ISSUE TITLE
✨npm prereleases

### ISSUE THREAD

**Issue by benjaminstrasser** [dagger/dagger#4233]
### What are you trying to do?

Release prerelease versions of the node SDK.

IMO there are 3 possibilities of doing this.

- Release a new prerelease version for every commit to main (${version}-dev-${GITHUB_SHA})
- Release a new prerelease version every day via cronjob(Seems to be the most common and the one I have used)
- Some other logic like publishing manually

### Why is this important to you?

Creating pre-releases is quite common

- [React](https://www.npmjs.com/package/react?activeTab=versions)
- [Typescript](https://www.npmjs.com/package/typescript?activeTab=versions)
-  ...

It is potentially useful because
- allow users to test and provide feedback on new features and changes before they are released
- allow maintainers to more easily use and test new features and changes, without having to build and reference locally

### How are you currently working around this?

Building and referencing via [local paths](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#local-paths)

**Comment by slumbering** [comment]
That's an excellent idea ! I really like it
To give you some context @benjaminstrasser, we're aiming to release each SDKs once every week.

Getting prerelease would require some tweaking in our workflow only for the Node.js SDK.
This is something that I can talk about with @gerhard

**Comment by benjaminstrasser** [comment]
> That's an excellent idea ! I really like it To give you some context @benjaminstrasser, we're aiming to release each SDKs once every week.
> 
> Getting prerelease would require some tweaking in our workflow only for the Node.js SDK. This is something that I can talk about with @gerhard

Thank you!
I already peeked at the GitHub workflows and I don't think it is too complicated.
Once there is a clearer direction on the requirements and a go from your side I can get to work or help out If wanted/needed.

**Comment by slumbering** [comment]
> > That's an excellent idea ! I really like it To give you some context @benjaminstrasser, we're aiming to release each SDKs once every week.
> > Getting prerelease would require some tweaking in our workflow only for the Node.js SDK. This is something that I can talk about with @gerhard
> 
> Thank you! I already peeked at the GitHub workflows and I don't think it is too complicated. Once there is a clearer direction on the requirements and a go from your side I can get to work or help out If wanted/needed.

You're right it shouldn't be too hard to implement but I just want to make sure that it's ok to not be 100% consistant in our workflow (prerelease only for Node.js and not Go nor Python ?..) cc @gerhard

**Comment by benjaminstrasser** [comment]
> You're right it shouldn't be too hard to implement but I just want to make sure that it's ok to not be 100% consistant in our workflow (prerelease only for Node.js and not Go nor Python ?..) cc @gerhard

You are 100% right. No need to rush anything 😄 
I haven't looked into it too deeply, but it looks like for python(pip, numpy,...) and go(rest, http,...) prereleases/rcs/betas seem somewhat common as well. Probably something to look into as well next to npm and reach some overarching consensus on how prereleases should be handled for all SDKs.

**Comment by gerhard** [comment]
If we did this, we would need do it across all SDKs, and also the Engine & CLI. If we did this as pre-releases across everything, that would be a big piece of work if we did it using the current artefacts as they are.

Instead, we want to leverage Zenith to generate these pre-releases locally. We already have a starting point here: https://github.com/shykes/daggerverse/tree/main/dagger . That sounds something worth investing in. WDYT @benjaminstrasser?

cc @shykes @jpadams

**Comment by benjaminstrasser** [comment]
@gerhard 
sounds interesting. What is the current progress on this?

**Comment by TomChv** [comment]
@gerhard Do we plan to work on this feature at the scale of dagger or should we only keep it to typescript?

In this case, I can work on it next week

**Comment by TomChv** [comment]
We can now close this issue because the TypeScript SDK became a local dependency, meaning that when you update dagger, you will update the your local environment on your next `dagger develop`.

**Comment by TomChv** [comment]
It's possible to also use the SDK before the release using the [new install `DAGGER_COMMIT` variable](https://github.com/dagger/dagger/pull/8012):

```shell
curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin DAGGER_COMMIT=head sh
```

So you can update your runtime with a no-release dagger binary, which it's kind of like an rc based on our current release process.
