### ISSUE TITLE
🐞 Add support to share multiple operations in the playground

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#4235]
### What is the issue?

I can't share something that contains multiple queries

### Steps to reproduce

1 - Go to `play.dagger.cloud` and try to share this: 

```
query foo {
  host {
    directory(path:".") {
      id
    }
  }
}

query bar {
  host {
    directory(path:".") {
      id
    }
  }
}
```

2 - You'll get a share URL but when accessing it, you'll get this response: 

```
{
 "data": null,
 "errors": [
  {
   "message": "Must provide operation name if query contains multiple operations.",
   "locations": []
  }
 ]
}
```

### SDK version

N/A

### OS version

N/A

**Comment by marcosnils** [comment]
cc @crjm

**Comment by gerhard** [comment]
Do we still want this @marcosnils? If yes, I propose that we move it to Linear @mircubed.

**Comment by mircubed** [comment]
Closing since moved to linear
