### ISSUE TITLE
Learn Dagger Tutorial 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#4239]
Suggestion from @marcosnils : 

>"Learn Dagger" tutorial with the option to log-in using Github a-la nextjs learn (https://nextjs.org/learn/foundations/about-nextjs). The good thing about doing this is that if the user decides to log-in using Github, we might design the flow in a way that by using the SSO credentials we could create a repository and setup the GHA flow automatically ourselves. In that flow, the "dagger" setup will be super smooth

**Comment by marcosnils** [comment]
closing in favor of #4291
