### ISSUE TITLE
Auth Parameters for pulling an image

### ISSUE THREAD

**Issue by jlongtine** [dagger/dagger#4242]
We should allow users to provide a `username` and `secret` for pulling an image. 

Something like this: 
```graphql
container {
  from(address: "alpine", auth: {username: "joel", secret: "mypassword") {
  }
}
```

**Comment by TomChv** [comment]
I'm down to work on this issue! I'll assign it to myself :)

**Comment by jlongtine** [comment]
@TomChv Something I realized I didn't mention in the description... We should probably make the API require a Secret, rather than a String. 



```
input Auth {
  name: String!
  secret: Secret!
}

container {
  from(address: String!, auth: Auth) {
  }
}
```

**Comment by TomChv** [comment]
I currently did that, should I update `SecretID` to `Secret`? @jlongtine 
 
```graphql
  "Initializes this container from the base image published at the given address."
  from(
    """
    Image's address from its registry.
    Formatted as [host]/[user]/[repo]:[tag] (e.g. docker.io/dagger/dagger:main).
    """
    address: String!,

    """
    Authentication information to pull image from private registry.
    """
    auth: ContainerAuth,
  ): Container!

input ContainerAuth {
  username: String!
  secret: SecretID!
}
```

**Comment by jlongtine** [comment]
@TomChv I think you're good with `SecretID`! 

I just checked how the rest of the API is working with them: 

https://github.com/dagger/dagger/blob/main/core/schema/container.graphqls#L104
