### ISSUE TITLE
Auth Parameters for pulling git repo

### ISSUE THREAD

**Issue by jlongtine** [dagger/dagger#4243]
We should allow users to provide a username and secret for pulling a git repo.

```graphql
{
  git(url: "https://github.com/dagger/dagger", auth: {username: "jlongtine", secret: "my key or pat or whatever"})
}
```

**Comment by marcosnils** [comment]
We should be able to support buildkit's `AuthTokenSecret` and `AuthHeaderSecret` https://github.com/moby/buildkit/blob/75fcbfeda6661f190ec1edfc923dc4e0491d0032/client/llb/source.go#L345-L350. @jedevc  WDYT?

I'd assume we could add those fields to the GitRef struct (https://github.com/marcosnils/dagger/blob/e5feaea7f1d6eb01d834e83b180fc3daed3463ea/core/git.go#L16) as *dagger.Secret?

**Comment by jedevc** [comment]
@marcosnils I think we could de-dupe this against https://github.com/dagger/dagger/issues/5930?

> I'd assume we could add those fields to the GitRef struct ([marcosnils/dagger@e5feaea/core/git.go#L16](https://github.com/marcosnils/dagger/blob/e5feaea7f1d6eb01d834e83b180fc3daed3463ea/core/git.go#L16)) as *dagger.Secret?

I think that's probably the right approach, yup :tada:

**Comment by helderco** [comment]
Fixed in https://github.com/dagger/dagger/pull/6992
