### ISSUE TITLE
Implement target for Dockerfile build

### ISSUE THREAD

**Issue by jlongtine** [dagger/dagger#4244]
This allows a user to build a particular target in the Dockerfile

```graphql
type Directory {
  dockerBuild(dockerfile: String, platform: Platform, target: String): Container!
}
```

**Comment by grouville** [comment]
Bumping, as some active users are requesting it: https://discord.com/channels/707636530424053791/708371226174685314/1061942068164964382

**Comment by jlongtine** [comment]
@grouville This should also be pretty straightforward. We can add a `target` key to the `FrontendOpt` for the Buildkit call, very similar to `buildarg:`.
