### ISSUE TITLE
Implement labels for Dockerfile build

### ISSUE THREAD

**Issue by jlongtine** [dagger/dagger#4245]
This allows a user to add labels the Dockerfile build

```graphql
input Label {
  key: String!
  value: String!
}

type Directory {
  dockerBuild(dockerfile: String, platform: Platform, labels: [Label!]): Container!
}
```

**Comment by aluzzardi** [comment]
Could we have a generic `withLabel(key: String!, value: String!)` and make sure labels stick around?

e.g.

```go
dir.DockerBuild(...).WithLabel("foo", "bar").WithLabel("bar", "baz").Export(...)
```

/cc @vito

**Comment by aluzzardi** [comment]
> Should labels map 1:1 to [OCI image annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md) or would we add the org.opencontainers.image prefix?

Thoughts on this one, @nipuna-perera? You mentioned in #3887 that you "have corporate policies that mandate certain labels on all docker images". 

I'm assuming you'd like to have full control of the label name rather than dagger auto-prefixing them with `org.opencontainers.image`, but I might be wrong

**Comment by nipuna-perera** [comment]
> > Should labels map 1:1 to [OCI image annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md) or would we add the org.opencontainers.image prefix?
> 
> Thoughts on this one, @nipuna-perera? You mentioned in #3887 that you "have corporate policies that mandate certain labels on all docker images". 
> 
> I'm assuming you'd like to have full control of the label name rather than dagger auto-prefixing them with `org.opencontainers.image`, but I might be wrong

Yes! I would like the ability to have full control of the labels. Honestly I am not sure what auto-prefix would achieve. Is there a rule/best-practice?

**Comment by jlongtine** [comment]
`WithLabel` sounds good to me!

**Comment by vito** [comment]
> Yes! I would like the ability to have full control of the labels. Honestly I am not sure what auto-prefix would achieve. Is there a rule/best-practice?

@nipuna-perera Just a (wrong) guess based on the annotations spec docs which talk about prefixes quite a bit. :slightly_smiling_face: Happy to see folks expect to work with explicit labels.

**Comment by grouville** [comment]
@aluzzardi, @jlongtine showed me how to append the `labels` to the `build` endpoint. In buildkit, this could be done with https://github.com/moby/buildkit/blob/e86ba9479d2c4170a0b191a977be51052c3692de/frontend/dockerfile/builder/build.go#L442

However, it seems here, that you want the ability to append the labels with `WithLabel`. Which means that you want to "update" the config of a container. Do you have any hints on where to start looking for that, in Buildkit codebase ?
