### ISSUE TITLE
✨ Provide a host { file(path) } operation

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#4271]
### What are you trying to do?

I'm trying to fetch use a file in my host machine and mount that into a container. It'd be nice to do something like

```
{
  host {
    file(path:"some/file.txt") {
      id
    }
  }
}
```

However, `file` is not currently a field of the `host` query.

### Why is this important to you?

So I don't have to make multiple calls.

### How are you currently working around this?

I have to use a `directory` call to get what I need. i.e: 

```
{
  host {
    directory(path: "some/folder") {
      file(path: "somefile.txt") {
        id
      }
    }
  }
}
```

**Comment by helderco** [comment]
Added `kind/user-request` from https://github.com/dagger/dagger/issues/4745.

**Comment by mircubed** [comment]
closing this, and will track user issue instead from #4745
