### ISSUE TITLE
Docs: Enhance code readability

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#4299]
### What is the issue?

In the docs website, the black background on `monospace` text is too noisy. I think it looks better in gray, as seen in:
- https://github.com/dagger/dagger/pull/4275

\cc @slumbering @vik

**Comment by slumbering** [comment]
> ### What is the issue?
> In the docs website, the black background on `monospace` text is too noisy. I think it looks better in gray, as seen in:
> 
> * [Node.js SDK - Improve ref docs readability #4275](https://github.com/dagger/dagger/pull/4275)
> 
> \cc @slumbering @vik

Thanks Helder. #4275 has also update title size and spacing. We've planned to do the same for the whole website.

**Comment by helderco** [comment]
#4275 is just for the reference docs. This issue is to extend that to the rest of the docs website.

**Comment by slumbering** [comment]
I'm gonna tackle this one today

**Comment by slumbering** [comment]
Done: #4351
