### ISSUE TITLE
✨ support RUN --mount=type=cache

### ISSUE THREAD

**Issue by robertu94** [dagger/dagger#4301]
### What are you trying to do?

I want to test if my app's code works on several Linux distributions using the system dependencies (I.e. dnf/apt). For these, I don’t have a lock file per se, and If I did I wouldn’t want one — I want the cache to invalidate as soon as apt or dnf says there is a newer version. In docker I would use something like mount-type=cache=locked https://docs.docker.com/engine/reference/builder/#run---mounttypecache

More info and context [on discord](https://discordapp.com/channels/707636530424053791/1060048433894936606/1060065296662151208)

### Why is this important to you?

My application is a moderate to small c++ code with a bunch of dependencies (200MB-8GB depending on configuration).  Depending on which ones and how many downloading or building these can take between minutes to hours so caching is critical. 

I use the python SDK because I and my team know Python 😄 

### How are you currently working around this?

I don't use dagger now, but am excited to use this.  Before this, a host volume could be mounted for the APT cache, but this can be tedious and error prone if multiple containers are trying to use it simultaneously.

**Comment by helderco** [comment]
This is not Python specific, any API changes will be picked up by all SDKs automatically. So this is an engine request.

**Comment by grouville** [comment]
@samalba @aluzzardi, can we bump this as a P1 ? Will take it, as it's shouldn't be too hard

**Comment by shykes** [comment]
I may be missing something, but isn't this already supported with [cache volumes](https://docs.dagger.io/api/reference/#query-cacheVolume). Under the hood they work exactly the same as `RUN --mount=type=cache`.

**Comment by robertu94** [comment]
It's the locking bit that I need so the cache doesn't become corrupted

**Comment by shykes** [comment]
Ah! Of course. Sorry for missing that. Indeed should be trivial to add.

**Comment by shykes** [comment]
For reference here's the equivalent in the CUE API: https://github.com/dagger/dagger/blob/cue-sdk/pkg/dagger.io/dagger/core/exec.cue#L81

**Comment by grouville** [comment]
###### Using this issue as source of truth

_Putting this issue as `stuck` for the moment being, even though I hope it can be closed by end of week._

#### What is blocking

A pending PR implements this behavior: https://github.com/dagger/dagger/pull/4437.
It works for GraphQL queries, but breaks at the codegen level.

**Context**
I relied on an `enum` graphQL type to benefit on autocompletion when providing the cache sharing mode.
However, none of our codegens implement this type.

#### What are the next steps

- [x] Add enums to NodeJS SDK codegen. Fixed, as part of https://github.com/dagger/dagger/pull/4437
- [ ] Add enums to Go SDK codegen. **Stuck by on-going work on codegen**: https://github.com/dagger/dagger/pull/4415 mostly
- [ ] Add enums to Python SDK codegen: https://github.com/dagger/dagger/issues/4445

**Comment by grouville** [comment]
Closed by #4437
