### ISSUE TITLE
Individual GraphQL field reference is not linkable

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#4305]
## Problem

When using the [GraphQL API reference documentation](https://docs.dagger.io/api/reference/), I often want to link to a specific field or query. This is currently not possible.

Note: types are linkable, but not fields. Example of a link to the [Container type](https://docs.dagger.io/api/reference/#definition-Container)

## Solution

Make fields linkable in the same way as types.

**Comment by shykes** [comment]
@vikram-dagger @crjm @slumbering would this be an easy fix? I run into it quite regularly, when looking for links to share with users.

**Comment by crjm** [comment]
Looking into it!
