### ISSUE TITLE
Auth parameters for pulling/pushing an image

### ISSUE THREAD

**Issue by samalba** [dagger/dagger#4310]
We need auth support for pulling and pushing a container image.

Related issue:

- #4242
- #3138

**Comment by aluzzardi** [comment]
Docker auth is supported -- asking clarifying questions in https://github.com/dagger/dagger/issues/3138

**Comment by samalba** [comment]
For the record, this is about supporting the auth directly from the dagger code. Given that docker auth is supported as a workaround, I'll decraese the prio on this one.

**Comment by samalba** [comment]
> @samalba are you sure that `docker auth` is truly a workaround ? I thought it was the "new" proper way to solve this issue ? As @jpadams linked it as a need to a field, do we need to update its priority ?

Yes I am sure. It's a workaround as it depends on the docker cli to do the registry auth. It's acceptable short-term but the issue is about supporting the auth on the dagger side, so it can be programmatically configured via the API and dagger secret types for credentials.

**Comment by TomChv** [comment]
I'm currently working on it with @sipsma supports, I made things worked now I'm cleaning up the code.
