### ISSUE TITLE
Python: show errors from establishing session

### ISSUE THREAD

**Issue by grouville** [dagger/dagger#4321]
Whenever a `dagger session` connection fails, the output error message is not forwarded by the Python SDK.

This behavior was already commented in the codebase, but not referenced as an issue yet:

https://github.com/dagger/dagger/blob/937323182e02fe6b02b601f77d134aaec3305435/sdk/python/src/dagger/session.py#L63

https://github.com/dagger/dagger/blob/937323182e02fe6b02b601f77d134aaec3305435/sdk/python/src/dagger/session.py#L74

Below is an example with a modified version of our `dagger session` where it should retrieve the stderr of buildkit.
Instead, we get the a `Dagger engine failed to start` error:
```shell
Traceback (most recent call last):
...
  File "/private/tmp/dagger/sdk/python/src/dagger/engine/cli.py", line 33, in __enter__
    raise ProvisionError("Dagger engine failed to start") from e
dagger.exceptions.ProvisionError: Dagger engine failed to start
```
cc @helderco

**Comment by helderco** [comment]
Thank you for adding this. It's one of the FIXMEs, I'll need to hunt them and create issues for them soon.
