### ISSUE TITLE
feat: Node SDK: handle errors from establishing session

### ISSUE THREAD

**Issue by grouville** [dagger/dagger#4322]
Similar to #4321

Whenever a dagger session connection fails, the output error message is not forwarded by the Node SDK.

Below is an example with a modified version of our dagger session where it should retrieve the stderr of buildkit.
Instead, we get the stack trace error with a hardcoded string `"No line was found to parse the engine connect params"`:
```
➜  typescript_sdk node --loader ts-node/esm copy.ts

(node:83510) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///private/tmp/dagger/sdk/nodejs/dist/provisioning/bin.js:166
            throw new EngineSessionEOFError("No line was found to parse the engine connect params");
                  ^
EngineSessionEOFError: No line was found to parse the engine connect params
    at Bin.<anonymous> (file:///private/tmp/dagger/sdk/nodejs/dist/provisioning/bin.js:166:19)
    at Generator.next (<anonymous>)
    at fulfilled (file:///private/tmp/dagger/sdk/nodejs/dist/provisioning/bin.js:4:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: undefined,
  code: 'D105'
}
```

cc @slumbering

**Comment by slumbering** [comment]
Hey @benjaminstrasser ! any opinion on this one ?

**Comment by grouville** [comment]
> I could look into it tonight.

Hi @benjaminstrasser, thanks for the proposal. It's already currently [work in progress](https://github.com/dagger/dagger/pull/4284). Shall be mergeable/merged soon (probably today) 😇

### Context

After the merge of above PR (#4284), in the Go SDK, whenever a connection tentative with the engine fails, it will show the output of the failure (buildkit message, with the proper context).

This issue (#4320) is more of a follow-up issue, to put the Node SDK at the same level as the Go and Python one (#4321)

> Yeah, there currently isn't any error we catch or omit here. Reading the connection params is simply the first thing we do. The error is very technical(not useful) as we fail to read any line from the reader while trying to parse the connection params.

From what I understand here, we do not want to add a new error message, but forward the error retrieved by the `dagger session` subprocess, as an error message. More context is available  [in this PR](https://github.com/dagger/dagger/issues/4320)
