### ISSUE TITLE
Node.js SDK - Typedocs improvement

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#4323]
As discussed here : https://github.com/dagger/dagger/pull/4240#discussion_r1061342567
We should use the most appropriate Typedoc tags when documenting the SDK.

```diff
export type DirectoryWithDirectoryOpts = {
 /**
  * Exclude artifacts that match the given pattern.
- * (e.g. ["node_modules/", ".git*"])

export type DirectoryWithDirectoryOpts = {
 /**
  * Exclude artifacts that match the given pattern.
+ * @example
+ * ["node_modules/", ".git*"]
```

**Comment by TomChv** [comment]
To implement this feature, we should first define a convention to write examples in the GQL doc.
For now, everything is written with `(e.g. <the example>)`.

A simple idea would be to replace `e.g.` by `@example`. However, I feel it's not a portable solution specially for bigger examples.

Another idea would be to:

```gql
type Container {
  "Initializes this container from the base image published at the given address."
  from(
    """
    Image's address from its registry.
    Formatted as {host}/{user}/{repo}:{tag} 
    Example:
    docker.io/dagger/dagger:main.
    """
    address: String!
  ): Container!
}
```

In an abstract form, this would be:

```
<doc>.
Example:
<the example>.
```

So basically, then we can just search for the string `Example` -> replace it with `@example` and we got the right output.
This requires less parsing for the same result and it will look good on other SDKs too.

WDYT @dolanor @slumbering?

**Comment by slumbering** [comment]
`Example: ....` looks good to me.

**Comment by TomChv** [comment]
> Example: .... looks good to me.

Okay, I'll update the GQL doc and add additional examples when it's possible!
