### ISSUE TITLE
Add support for go, typescript, javascript and python embeddings for interactive docs

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#4325]
- [x] go
- [x] typescript (code done, waiting on https://github.com/dagger/dagger/pull/4359 to be released)
- [x] javascript (code done, waiting on https://github.com/dagger/dagger/pull/4359 to be released)
- [x] python

**Comment by grouville** [comment]
So excited about this one ! 🔥

**Comment by marcosnils** [comment]
being worked on here: https://github.com/dagger/dagger.io/pull/1423
