### ISSUE TITLE
✨ Linter for GraphQL schema

### ISSUE THREAD

**Issue by TomChv** [dagger/dagger#4331]
### What are you trying to do?

> Comments from @dolanor applied, I'll also make sure every query follow the convention we defined above:
> 
> ```text
> <verb at the third person> description using the param names.
> (ending with a .)
> ```
> 
> And that every query params with doc associated has a line break.

> We can take care of example formatting and additional example in a follow-up PR.

> Having a linter to ensure those roles are set on our schema is a good idea.
> This [linter](https://github.com/cjoudrey/graphql-schema-linter) looks pretty good, and we can create custom rules. For instance, to make sure every description's line end with `.`.
> Or that we are using a verb in the third person to begin a type function.

> WDYT @helderco @dolanor ?

_Originally posted by @TomChv in https://github.com/dagger/dagger/issues/4240#issuecomment-1372734935_

### Why is this important to you?

This will enhance GraphQL maintainability and enforce global conventions.

### How are you currently working around this?

Manually check for inconsistency.

**Comment by d3rp3tt3** [comment]
GraphQL ESLint is another good linter to look at when spiking on this issue.

https://github.com/B2o5T/graphql-eslint/blob/master/docs/README.md

**Comment by TomChv** [comment]
> GraphQL ESLint is another good linter to look at when spiking on this issue.

Good idea! Our GraphQL schemas are in a standalone directory, so either solution work. However, ESLint seems to be more complete.
I'll have a closer look at both and choose one :D

**Comment by helderco** [comment]
Our schema is now generated from code so we can enforce our rules in core functions that implement them.

**Comment by TomChv** [comment]
@helderco What do you think about closing this one? I'm not sure it's a priority nor adding an impactfull improvement on our SDKs?

**Comment by jedevc** [comment]
Agreed, we have linting that ensures that the graphql schemas are up-to-date with code, but we should be enforcing the standards in the code that generates them as mentioned above.

Closing :tada:
