### ISSUE TITLE
Integrate analytics for common quickstart guide

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#4358]
This task is to integrate analytics into the common quickstart guide to answer the following questions:
- Is the multi-language approach engaging for readers?
- Is this approach preferable to single-language guides?
- Is there a clear preference for one language over others?
- etc

**Comment by marcosnils** [comment]
I'll be working on this one!

**Comment by marcosnils** [comment]
here's the first iteration of the funnel review: https://app.posthog.com/insights/c4gKCXvF

**Comment by marcosnils** [comment]
funnel working as expected. Closing this
