### ISSUE TITLE
CI Observability for dagger/dagger

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#4370]
dagger's CI is currently a black box. In order to make any improvements, we first need to measure:

- Tracing
  - See the overall time breakdown for CI runs
- Metrics
  - Which operations are the slowest
  - Trends (is it getting slower, faster, the same, ...)
  - Caching information (is it working, what's the hit ratio, ...)

/cc @gerhard

**Comment by mircubed** [comment]
closing since this is just an abstract issue based on an overall goal we are trying to achieve.
