### ISSUE TITLE
Node.js SDK - check for await

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#4386]
## Problem
Many users get confused with their async pipeline.
When should I use await ? Is my pipeline executing ?
The error doesn't give any clue of what's happening.
```shell
throw new UnknownDaggerError("Encountered an unknown error while requesting data via graphql", { cause: e });
```

## A better approach
Display an understandable error message if users omit to await the promise.

**Comment by TomChv** [comment]
I found a way to check if the function has been called with `await` keyword or not but it [looks like a hack](https://stackoverflow.com/questions/49297200/how-to-tell-if-an-async-funcion-has-been-invoked-with-await).

A simpler way would be to check for the error code.
After quick test I find out that if you do not `await` the call, it will throw an `ECONNREFUSED` error.
We might check for that one and throw a different message.
However, there might be other kinds of errors that may trigger that one too.
