### ISSUE TITLE
#Container / #Exec need the ability to control their networking environment  

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [dagger/dagger#440]
Specifically, it should be possible to specify:

 * additional hosts (--add-hosts in docker lingo)
 * the network the container is attached to
 * specify dns servers

**Comment by shykes** [comment]
Taking stock now that 0.2 is released:

> * additional hosts (--add-hosts in docker lingo)

I believe this is available in `core.#Exec`

> * the network the container is attached to

Not relevant in buildkit (assuming you're talking about networks in the docker engine sense)

> * specify dns servers

Is this supported by buildkit? And if so, does `core.#Exec` support it?

**Comment by shykes** [comment]
I'm closing this, since it's specific to the CUE SDK and we are not currently adding features to the CUE API.
