### ISSUE TITLE
✨ [Go SDK] Introduce interfaces for interoperability and encapsulation

### ISSUE THREAD

**Issue by sagikazarmark** [dagger/dagger#4401]
### What are you trying to do?

I'm trying to build a set of libraries on top of the Go SDK to provide higher level interfaces to Dagger making it easier for people to work with it.

Some of those libraries/features may require to encapsulate `dagger.Client` or `dagger.Container` in custom interfaces. For example: I have a custom `Client` that detects if Dagger is running on GitHub Actions and forwards all GitHub related environment variables automatically to all `Container`s.

In order to do this, I've created a `Client` interface that I use internally (exposing all methods of `dagger.Client`). The problem with this approach is that it's not interoperable between different libraries that depend on `dagger.Client`.

### Why is this important to you?

In order to be able to encapsulate certain parts of the SDK and keep interoperability between different libraries.

### How are you currently working around this?

I have a custom interface at the moment and I use it in all of my libraries instead of depending on `dagger.Client` directly, but there are no guarantees that every potential library out there will do the same.

**Comment by helderco** [comment]
Hi, have you seen how this could work for you?

- #3885

**Comment by sagikazarmark** [comment]
I think it's a nice syntactic sugar, but it still wouldn't allow encapsulating any of those resources.

The use case is also a bit different: encapsulation would support passing the client and containers across API layers (eg. using multiple, different libraries)

**Comment by sagikazarmark** [comment]
Here is the repo, but that part of the code is not pushed yet: https://github.com/sagikazarmark/goci

**Comment by sagikazarmark** [comment]
> A use case you shared, detecting if Dagger is running via GitHub Actions, should be supported as a first-class state by Dagger. Taking that info and using it throughout the pipeline is critical.

Agreed.

**Comment by sagikazarmark** [comment]
@d3rp3tt3 here: https://github.com/sagikazarmark/goci/pull/2

**Comment by d3rp3tt3** [comment]
Thank you, @sagikazarmark! The code is really clean and easy to read for me. 

I see you're adding several pieces of GitHub metadata as environment variables with the container. How do you use that info?

**Comment by v0lkc** [comment]
I would also appreciate if you could provide the mentioned interfaces for the client and the other types. Usecase is similar to what @sagikazarmark described. For compliance reasons I'm building a little framework around dagger with the intend to automatically capture build logs in a certain format, checksums of the images being used, etc. Those interfaces would enable me to mock interactions with the dagger framework and eventually speed up testing.

**Comment by mircubed** [comment]
@v0lkc Thanks for your time today! As mentioned on the call, please share a summary of your use case here. This will help us for the next steps of the PR review.

For feature requests, we want to support them in Dagger proper vs one SDK as much as possible, so we will take that into consideration when we are evaluating the PR and your use case.

**Comment by TomChv** [comment]
@mircubed Do we have any update on this issue?

**Comment by gerhard** [comment]
Considering that we now have https://docs.dagger.io/zenith/, and users are able to create & share their own modules, we are thinking that is less important and perhaps even unnecessary.

If you agree with the above @sagikazarmark, would you be OK to close this?

If we don't close this, it will not be before sometime in 2024 that we can follow-up on this considering everything else that is in flight.

Thank you! In-sync with @helderco. cc @vito

**Comment by sagikazarmark** [comment]
> Considering that we now have https://docs.dagger.io/zenith/, and users are able to create & share their own modules, we are thinking that is less important and perhaps even unnecessary.

Agreed. Depending on whether the plain Go SDK remains a first-class citizen, it's either less important or unnecessary.

**Comment by sipsma** [comment]
Just a side note that Zenith modules will support interfaces in the very near future: https://github.com/dagger/dagger/issues/6213

That change specifically will most likely just start as an optional field, totally backwards compatible, but the option of going "full-blown everything is an interface" remains open in my mind, especially if it can be done fully or at least mostly backwards compatible and provides enough benefits.

At that time we'll need to make a call on whether it's Zenith Go SDK only or applies to the "legacy" one too.

**Comment by levlaz** [comment]
Hey @sagikazarmark would you consider this resolved with modules now?

**Comment by sagikazarmark** [comment]
I guess so. Zenith introduced different challenges, but I guess this isn't the right issue to track those.
