### ISSUE TITLE
[Docs] Quickstart page layout

### ISSUE THREAD

**Issue by crjm** [dagger/dagger#4419]
This issue is being created to document the ~~research~~ progress behind the new quickstart that will live inside `docs.dagger.io`.

**Comment by crjm** [comment]
Following the benchmarking done by @marcosnils in #4291, we can see that the Next.js learn experience is a different section inside the Next.js docs. 

This takes me to the following questions: 
- Do we want to have the sidebar containing all the docs site content when in the quickstart?
- If not, should we have a sidebar that contains each step of the quickstart instead?
- If not, should we leave more space for quickstart-related content? (The embedded playground would go on the right and wouldn't be small in this case). 

I look at Stripe's model and it has 0 white-space between sidebar + text + editor (left to right). I understand the use of having all the information in the viewport, but at the same time, it looks bloated and it's indeed difficult to focus on one place. An alternative would be to add the [hideable sidebar feature](https://docusaurus.io/docs/sidebar#hideable-sidebar) so the user can decide the amount of information presented to him in the same viewport.

**Comment by crjm** [comment]
@vikram-dagger to put you into context, had a chat yesterday with @marcosnils where we agreed it would be nice to have a quickstart with the explanation on the left, and the code implementation on the right, just [like Stripe has](https://stripe.com/docs/payments/quickstart?client=next).
By having all the information in the same viewport, there's no need to scroll, making the quickstart a better learning experience. For this to happen, we need to decide how to layout the quickstart, hence this issue.
Let us know what you think!

**Comment by marcosnils** [comment]
> * Do we want to have the sidebar containing all the docs site content when in the quickstart?

What are the pros and cons of having the getting started with a different sidebar? Unless we have a clear goal of separating it, I'd just leave as part of the docs for now.



> An alternative would be to add the [hideable sidebar feature](https://docusaurus.io/docs/sidebar#hideable-sidebar) so the user can decide the amount of information presented to him in the same viewport.

I guess we can try to hide the sidebar in the quickstart page and see how that works so it doesn't feel that bloated.

**Comment by vikram-dagger** [comment]
> @vikram-dagger to put you into context, had a chat yesterday with @marcosnils where we agreed it would be nice to have a quickstart with the explanation on the left, and the code implementation on the right, just [like Stripe has](https://stripe.com/docs/payments/quickstart?client=next). By having all the information in the same viewport, there's no need to scroll to see the code and come back to the place I was to keep reading, making the quickstart a better learning experience. 

I agree. This is similar to the two-pane structure/mockup I proposed in https://docs.google.com/document/d/1UH0xHjPgOg4aqU9o5KLBmXM56hQE_xP0Q6K_MZq8ilI/edit?usp=sharing

See also https://github.com/dagger/dagger/issues/4291#issuecomment-1384165556 for discussion related to above.

**Comment by crjm** [comment]
After benchmarking several quickstart guides, it's standard for the guide to have it's own sidebar. 
I have the feeling is not used only for navigation, but it also gives a summary of what the quickstart is about, so the user has more context and can decide if the quickstart is a fit for them/they are in another step of the learning process.
[Docusaurus allows grouping related docs into their own sidebar.](https://docusaurus.io/docs/sidebar/multiple-sidebars)

**Comment by marcosnils** [comment]
:wave: I'm renaming this issue from **research** to **layout** since there's no need to do a research here. We know we want to make this change, the "research" part is basically part of the implementation.

**Comment by crjm** [comment]
Adding/testing layout changes [here](https://github.com/crjm/dagger/tree/docs-quickstart-layout) based on [this PR](https://github.com/dagger/dagger/pull/4391).

**Comment by crjm** [comment]
Done in #4537
