### ISSUE TITLE
Example pipeline in a non-SDK-supported language using a GraphQL client

### ISSUE THREAD

**Issue by kpenfound** [dagger/dagger#4428]
Create an example using a GraphQL client to write a CI pipeline in a language we don't yet have an SDK for such as Java, Rust, or Ruby

**Comment by vikram-dagger** [comment]
I'm not sure if I am misunderstanding the task...just a quick ping that we already have two (albeit simple) examples of this at https://devel.docs.dagger.io/api/254103/build-custom-client using Rust and PHP.

**Comment by kpenfound** [comment]
Yeah that's a good point @vikram-dagger , I forgot about those. This one will be a more advanced pipeline to dig into more of the api. Maybe too much depth to try to cover in a guide, I'm not sure yet

**Comment by d3rp3tt3** [comment]
@kpenfound, I agree that it would be nice to have a more in-depth example with even a starter app. I followed the steps to create a client in Rust and was successful. However, I needed to learn how to build _my_ app with this client. Part of it has more documented examples for the GraphQL API, which you can reference in the client.

**Comment by vikram-dagger** [comment]
Closing this as https://github.com/dagger/dagger.io/issues/1769, which envisages a similar result, is in progress.
