### ISSUE TITLE
🐞 Dagger license copyrights refer to 2022 instead of 2023

### ISSUE THREAD

**Issue by d3rp3tt3** [dagger/dagger#4432]
### The Dagger license dates are not current
Several of the Dagger licenses to 2022 and need to be updated for 2023.

### Licenses to be updated
- [x] Dagger - https://github.com/dagger/dagger/blob/main/LICENSE
- [x] Go SDK - https://github.com/dagger/dagger-go-sdk/blob/main/LICENSE
- [x] Node.js SDK - https://github.com/dagger/dagger/blob/main/sdk/nodejs/LICENSE
- [x] Python SDK - https://github.com/dagger/dagger/blob/main/sdk/python/LICENSE
- [x] Sphinx config file for Python SDK docs - https://github.com/dagger/dagger/blob/main/sdk/python/docs/conf.py
- [ ] Cue SDK - (see note below)

For the Cue SDK, the branch appears outdated, and no copyright date is listed in its license file.

https://github.com/dagger/dagger/blob/cue-sdk/LICENSE (note that it is: `cue-sdk` and not `main`)

### Log output

NA

### Steps to reproduce

View copyright

### SDK version

https://github.com/dagger/dagger/releases/tag/v0.3.9

### OS version

NA

**Comment by d3rp3tt3** [comment]
@helderco updated the license date for Python docs conf with this PR: https://github.com/dagger/dagger/pull/4399.

**Comment by helderco** [comment]
@d3rp3tt3 I believe the copyright year referes to the first publication date, so we shouldn't need to update the license dates.

**Comment by helderco** [comment]
> @helderco updated the license date for Python docs conf with this PR: #4399.

That was a mistake 👼 Should have been just the `noqa`.
