### ISSUE TITLE
Node.js SDK getting started CommonJS JavaScript example for multibuild is broken

### ISSUE THREAD

**Issue by d3rp3tt3** [dagger/dagger#4451]
## Docs page
URL: https://docs.dagger.io/sdk/nodejs/783645/get-started#step-4-test-against-multiple-nodejs-versions

## Issue
If you copy-pasta the Node.js multibuild example for CommonJS JavaScript, the code does not run. The two preceding examples DO work.

## Cause
The example does not include the final parentheses `( )` required by JavaScript for the function call. I originally did not have the linter enabled when I tried to run the example. As a result, running build.js for multibuild resulted in the terminal returning immediately without any errors. I then enabled a linter in VS Code, which shows the issue.

<img width="631" alt="Screen Shot 2023-01-26 at 10 39 03 AM" src="https://user-images.githubusercontent.com/1811126/214879689-3068d0cc-eef9-46dc-9ab7-630a7917b7fb.png">

## The fix
Update the docs example to include the parentheses `( )` at the end of the file. 

<img width="538" alt="Screen Shot 2023-01-26 at 10 39 09 AM" src="https://user-images.githubusercontent.com/1811126/214880335-486de75d-1b50-4450-aacb-c87c42c98fd8.png">

**Comment by jpadams** [comment]
Nice issue and fix. Very clear. Thank you!

**Comment by jpadams** [comment]
Fixed by #4452
