### ISSUE TITLE
🐞 Error with export function

### ISSUE THREAD

**Issue by Ekyazed** [dagger/dagger#4458]
### What is the issue?

I was trying dagger with the [Get Started](https://docs.dagger.io/sdk/go/959738/get-started#step-4-create-a-single-build-pipeline)
page. The failing function is the Export function.

### Log output

 input:1: container.from.withMountedDirectory.withWorkdir.withExec.directory.export destination "C:\\Users\\***\\GolandProjects\\FilesManagement\\build" escapes workdir

### Steps to reproduce

code:
`func daggerBuild() error {
	ctx := context.Background()

	client, err := dagger.Connect(ctx, dagger.WithLogOutput(os.Stdout))
	if err != nil {
		fmt.Printf("Error connecting to Dagger Engine: %s\n", err)
		os.Exit(1)
	}
	defer client.Close()

	src := client.Host().Directory(".")

	golang := client.Container().From("golang:latest")
	golang = golang.WithMountedDirectory("/src", src).WithWorkdir("/src")

	path := "build/"
	golang = golang.WithExec([]string{"go", "build", "-o", path})

	output := golang.Directory(path)
	_, err = output.Export(ctx, path)
	if err != nil {
		fmt.Printf("Error on export: %s", err)
	}

	return nil
}`

### SDK version

Go SDK 0.4.3

### OS version

Windows 11

**Comment by grouville** [comment]
Confirming the error:
<img width="980" alt="image" src="https://user-images.githubusercontent.com/31691250/215452865-8e463831-8fad-424c-8151-af28f726c443.png">

Exploring a fix today 🙏

**Comment by grouville** [comment]
@samalba, shall be moved as P1, as it [blocks a user](https://discord.com/channels/707636530424053791/1068166308383965195/1068166308383965195) + All exports are broken on Windows.
Fix is on the way (being tested)
