### ISSUE TITLE
Unreadable text in dark mode docs

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#4464]
When viewing our docs in dark mode, words formatted as `code` aren't readable:
<img width="722" alt="Screenshot 2023-01-26 at 2 43 33 PM" src="https://user-images.githubusercontent.com/30126853/214967437-f34df67f-497e-4c93-b521-449a3f120952.png">

Seems to be the same on at least Firefox and Chrome. This used to work for me so I guess something changed relatively recently.

cc @slumbering

**Comment by slumbering** [comment]
Thanks @sipsma, good catch.

PR to fix this: #4468

**Comment by mircubed** [comment]
closing since PR is merged
