### ISSUE TITLE
Reference Discord from our Github Discussions

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#4476]
## Problem

We have two places for the community to give feedback and ask questions: Discord and Github discussions. There should be more bridges between them.

## Solution

Pin a post on our github discussions, referencing and linking to our discord server.

Suggested by @d3rp3tt3 , thank you Jenn!

**Comment by mircubed** [comment]
@shykes want me to make this post? Happy to!

**Comment by shykes** [comment]
That would be great, thanks 🙏

**Comment by mircubed** [comment]
I am closing this since this is something we can do as we post them. For example, I just updated Alex's post to mention the discord thread -https://github.com/dagger/dagger/discussions/4942
