### ISSUE TITLE
Custom GraphQL client docs: Add links for installing Rust and PHP

### ISSUE THREAD

**Issue by d3rp3tt3** [dagger/dagger#4477]
## Docs Page
URL: https://devel.docs.dagger.io/api/254103/build-custom-client
In the repo: https://github.com/dagger/dagger/edit/main/docs/current/api/254103-build-custom-client.md

## The Issue
The Rust and PHP examples for creating a custom GraphQL client to use Dagger do not include the steps to install the languages. As a result, when you run the following example to create the starter projects, you get errors in the terminal. 

### Rust
**Command**
`cargo init`
`cargo add gql_client@1.0.7`
`cargo add serde_json@1.0.89`
`cargo add tokio@1.22.0 -F full`
`cargo add base64@0.13.1`

**Error in Terminal**
`command not found: cargo` 

### PHP
**Command**
`composer require gmostafa/php-graphql-client`

**Error in Terminal**
`command not found: composer` 

## Context
The docs for the other Dagger SDKs include links to the installation instructions for the respective languages. For example, the [Python SDK Getting Started doc](https://devel.docs.dagger.io/sdk/python/628797/get-started) links to the [download site for Python](https://www.python.org/downloads/).

We should not assume that people who want to learn how to create a custom client know Rust or PHP. So, the docs should include the link to install Rust and one for PHP - and links to getting started content. (However, I assume that most people would pick Rust over PHP if unfamiliar with either language. :) )

## Recommendation
Update the **Requirements** section to point to getting started guides for Rust and PHP and for installing each. The following section shows how you might do that in the docs.

> Requirements
> This tutorial assumes that:
> 
> * You have a basic understanding of the Rust or PHP programming languages. If not, [read the Rust tutorial](https://www.rust-lang.org/learn) or [read a PHP tutorial](https://www.w3schools.com/php/).
> * You have a development environment with Rust **versionHere** or later or PHP **versionHere** or later set up.  If not, install [Rust](https://www.rust-lang.org/tools/install) or [PHP](https://www.php.net/manual/en/install.php).
> * You have Docker installed and running on the host system. If not, [install Docker](https://docs.docker.com/engine/install/).
> * You have the Dagger CLI installed on the host system. If not, [install the Dagger CLI](https://devel.docs.dagger.io/cli/465058/install).

### Supporting information
**Dagger docs**
[Python Get Started](https://devel.docs.dagger.io/sdk/python/628797/get-started#requirements)
[Go Get Started](https://devel.docs.dagger.io/sdk/go/959738/get-started#requirements)
[Node.js Get Started](https://devel.docs.dagger.io/sdk/nodejs/783645/get-started#requirements)

**Note** The Node.js Get Started doc has a link for how to set up an example application but does not give you the link to install node.

**Comment by slumbering** [comment]
cc @vikram-dagger ! Thanks @d3rp3tt3 😄

**Comment by vikram-dagger** [comment]
Ping @d3rp3tt3 for review

**Comment by vikram-dagger** [comment]
Updated: https://docs.dagger.io/api/254103/build-custom-client#requirements
