### ISSUE TITLE
Transfer quickstart example code to Dagger org repo

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#4479]
### What is the issue?

This task is to transfer the repository from https://github.com/vikram-dagger/hello-dagger to https://github.com/dagger/hello-dagger so that it resides in the organization's location rather than a personal one.

**Comment by marcosnils** [comment]
we've decided to create a new repo in the Dagger org and move it there.

**Comment by vikram-dagger** [comment]
I tried to do this but lack permissions

![image](https://user-images.githubusercontent.com/112123850/215867569-af5fb16c-ca33-49d3-a8fb-46b89804fdbd.png)

**Comment by d3rp3tt3** [comment]
How does the plan fit in with the Dagger/Examples repo? Do you expect to have a the "Hello" repo for the quickstart and the Examples repo for more in-depth examples?

**Comment by marcosnils** [comment]
> How does the plan fit in with the Dagger/Examples repo? Do you expect to have a the "Hello" repo for the quickstart and the Examples repo for more in-depth examples?

yes, that's correct.
