### ISSUE TITLE
Engine provision should be resilient to registry errors

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#4484]
Right now `ghcr.io` is returning 500 errors which is resulting in any calls following the default provision path to fail on this line: https://github.com/sipsma/dagger/blob/19d61667f361fd925a2f8526823778e1b3cc3384/internal/engine/docker.go#L50-L50

Instead, if we get an error there we should have some fallback codepath that just tries to use any local engine that already exists.

**Comment by grouville** [comment]
Hi @laupse,
Assigned it to you 😇 Feel free to make a draft PR whenever you feel confident, to iterate on top of that 🙏

**Comment by laupse** [comment]
#4489 here what i did ! 
If we cant get the digest from remote we are in fallback, 
check if any dagger-engine exist
if yes use the most recent one (based on docker ps output)
if no fail

**Comment by grouville** [comment]
Closed by #4489
