### ISSUE TITLE
Support for getting resolved image SHA after `Container.From`

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#4516]
User requested the ability to get the SHA of the image that was pulled as part of `Container.From` in order to include it in an SBOM they are generating.

This is simple to implement, the harder part is deciding on the API. We can just have a `imageRef` field in `Container`, but if you modify the container (i.e. call `With*`) should we just return the same SHA as was pulled originally? Or should we error out? Or recalculate the SHA (very expensive and raises other questions)?

My immediate preference would be to only allow it to be called right after `From` and error out otherwise, at least to start. That's simple and comprehensible and if we want to change the behavior in the future it will be backwards compatible (just not an error anymore).

**Comment by helderco** [comment]
Fixed in #4600
