### ISSUE TITLE
Best practice: how to map Dagger pipelines to CI jobs?

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#4558]
## Problem

When running Dagger in a CI workflow, one must decide how to map its Dagger pipeline(s) to CI job(s). We don't help users navigate this decision.

## Solution

Document best practices, and clarify how to decide on the best approach.

## Context

There are two possible approaches to mapping Dagger pipelines to CI jobs:

1. **1-to-N**: One big CI job triggers all Dagger pipelines
2. **1-to-1**: Each Dagger pipeline is triggered by a dedicated CI job

These approaches can also be combined in a hybrid approach.

* The advantage of **1-to-N** is that it limits the role of the CI runner to an implementation detail that you can mostly forget about after initial setup. This maximizes the amount of logic moved to the Dagger API, and therefore the value of Dagger to its user. It also maximizes portability of the pipeline to other CI runners.

* The disadvantage of **1-to-N**: all dagger pipelines are run in the same job. This means that they are all run in the same VM, sharing the same resources. In other words, users will lose a valuable feature of the existing CI system, which is job parallelization.

**Comment by thinkingerrol** [comment]
Dagger's stated purpose is to eliminate CI lock-in effects and allow running (and debugging) CI locally.
My team is locked into Jenkins by using its parallelization mechanism to run a DAG of stages across many Jenkins agents.
This lock-in would be gone if Dagger provided a networked pool of engines, sort of like https://en.wikipedia.org/wiki/Incredibuild
That would unlock a **1-to-N** best practice.

**Comment by khrisrichardson** [comment]
This was also on the radar of [kpt](https://github.com/GoogleContainerTools/kpt/issues/226), which appears to have opted for a 1-to-1 mapping of pipeline to CI job for the time being.

**Comment by jglick** [comment]
> We don't help users navigate this decision. […] users will lose a valuable feature of the existing CI system, which is job parallelization

To start with, so far as I can tell, [existing docs](https://docs.dagger.io/) do not even mention the fact that a pipeline runs in a single VM and thus that the tool in isolation cannot handle the fundamental requirement in a large project of distributing work (usually automated test suites) across a cluster of machines—that you still need some higher-level orchestration system for this. Unless and until something like #2061 is implemented, it would be best to make this limitation explicit, even if there is no detailed advice about alternatives (such as code examples showing use of multiple agents in the case of the [Jenkins snippet](https://docs.dagger.io/cookbook#jenkins), and analogously for other CI systems).

**Comment by shykes** [comment]
This is now documented in https://docs.dagger.io/adopting#integrating-with-ci
