### ISSUE TITLE
Support exporting shared cache volumes to remote cache backend

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#4569]
Cache mount contents are not included in remote cache exports in buildkit.

In cases where dagger has ephemeral local cache and a fast connection to its remote cache backend it may often be highly beneficial to be able to support synchronizing the shared cache mounts with that backend. For example, if using S3 as a remote cache backend on EC2 instances, S3 would essentially serve as a faster and more reliable source to download package artifacts from.

One approach I've been thinking about for a while is to start a service container in buildkit that has the shared cache mount in it and use that to continuously synchronize with the backend. This could be implemented in our own codebase for now, shouldn't require any new upstream changes so we can iterate quickly.

There's a lot of potentially tricky problems with this approach though. The biggest one in my mind is whether we can maintain a consistent state when the shared cache mount is being synchronized from multiple independent runners?
   * I believe the answer is that it not feasible to do this *in general* but it may be possible for many use cases. Specifically those where the cache mount is a content-addressed store where state can be merged cleanly.

If we run into issues with that approach there's others we could investigate. For example, if synchronization between distributed runners is too big of an issue then we could try out support for distributed filesystems (e.g. EFS on AWS). Those have their own tradeoffs too of course in terms of cost, performance and vendor lockin.

It's also possible this whole approach may turn on to not be viable in the real world, in which case there may be other options for supporting the same use case, such as support for running package manager specific proxies w/ caching running as persistent services in dagger. That can be a separate issue if we decide to go that route.

**Comment by nipuna-perera** [comment]
This is a fantastic alternative to running to entire engine remotely!

**Comment by sipsma** [comment]
For a first iteration of this I'll probably give [rclone](https://github.com/rclone/rclone) a try. We can just run the rclone daemon in the background with the shared cache mount when the engine starts.

I have used rclone at home successfully in the past and it has a lot of potentially useful features like transparent compression, deduplication based on hashes (I think), etc. It's also written in Go so if initial tests are promising it might be a nice long-term option in case we ever want to make upstream improvements+fixes.

**Comment by sipsma** [comment]
Another thought while I wait for some other tests to run, to deal with the problem of synchronization between different hosts, I think an approach conceptually similar to how normal layer caching works might be viable:
1. Store data (as in actual file contents of the cache mount) under one global shared pool. Use content addressed names to make synchronization easy.
2. Store each "manifest" (i.e. the contents of a cache mount) for each host separately.
3. If you want to add a new dagger engine host (e.g. you are autoscaling up and spinning up more engines) the new engine can initialize itself by just copying one of the existing manifests from a different host

**Benefits:**
1. No need to synchronize state of filesystems between different hosts, manifests are managed independently
2. Remote cached data is still deduplicated between hosts though (via content addressed storage in a global pool)
3. Lots of options for expanding and optimizing further
   * E.g. certain cache mount use cases already support safe synchronization between hosts and so we could easily pool manifests (exact same idea as how we are approaching normal s3 layer caching)

**Challenges:**
1. Implementing all that ourselves would be a lot of effort
   * Between rclone and numerous other libraries/frameworks out there I think there is a good chance we will not need to implement everything ourselves though. We're certainly not the first in this problem space...
1. Getting this performant will still be a challenge, will require at minimum a fair bit of tuning of things like compression, fuse vs. fsnotify, etc.

**Comment by sipsma** [comment]
Haven't written a test yet but just finished up a first pass on very basic support, will send out once I've added a test case https://github.com/sipsma/dagger/commit/28ebf972498d798738ffb9e8c6ab97850cfd51dc

Going for a simple as possible approach to start here. When the engine starts, it will run a container that does a single sync from s3 to the local cache, using cache mode locked. Then, when the engine shuts down, it synchronizes the cache mount back to the remote.

This should get us going for use cases where engines are long(ish)-running and are pre-initialized in a warm-pool-like configuration. It will also be pretty easy to layer on more required features like having one engine initialize its cache dir from another's (as described in my last comment). There's also tons of performance knobs available out-of-the-box thanks to use rclone and we can iterate on other things like more "continuous" syncing to the remote (to speed up engine shutdown), lazy pulling via rclone support for fuse+local caching, etc.

**Comment by itaischwartz** [comment]
@sipsma Maybe we could do something like https://github.com/overmindtech/buildkit-cache-dance

**Comment by sipsma** [comment]
Support for this has actually been merged, should have closed this issue a while ago. It's part of our cache service, which is currently in alpha. Please reach out to us if you'd like to try it out: https://airtable.com/shrpRWVkxxJWRMs18

**Comment by Konubinix** [comment]
Hi. I'm discovering dagger and don't find this in the documentation. Could you provide a link please?
