### ISSUE TITLE
Guide Centralization

### ISSUE THREAD

**Issue by crjm** [dagger/dagger#4571]
After a discussion with @vikram-dagger, we agreed that the next best move of #4291 would be to centralize the guides we currently have.
To do this, we would implement an index where we can see all the different guides, with tags (indicating the SDK, difficulty maybe, etc.). This will bring more visibility to the guides, as this index will be the entrypoint to all of them.

```[tasklist]
### Tasks
- [ ] #4573 
- [ ] #4574 
- [ ] #4575 
- [ ] #4576
- [ ] https://github.com/dagger/dagger/issues/4581
- [ ] #4617 
- [ ] https://github.com/dagger/dagger/issues/4628
```

**Comment by crjm** [comment]
@vikram-dagger FYI I'm reassigning so we keep one owner per issue. I'm still working on this.

**Comment by vikram-dagger** [comment]
Fine to close this, as the two pending tasks are no longer significant IMHO. We may wish to reopen https://github.com/dagger/dagger/issues/4617 in future.

**Comment by gerhard** [comment]
+1 for migrating what is left into Linear.
