### ISSUE TITLE
Convert single-language guides to multi-language where required

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#4574]
### What is the issue?

This task involves analyzing the complete collection of guides and defining the work required for each one. There are some considerations here:

1. Leave it as single-language or add equivalent code in other languages?
- The CUE guides, as an example, may require additional work/thought as there are a large number of them eg. https://docs.dagger.io/sdk/cue/232322/guides
- The get started guides for each SDK are another example where we might prefer to leave those as single-language only as they are directly connected to the primary language of the SDK.
2. Use the embedded playground or use static code snippets?
- The playground is useful for code snippets that work in isolation and don't have any dependencies on external services. It does not add value in all cases eg. some snippets will always fail due to required user credentials for external services not being available in the playground environment eg. https://docs.dagger.io/sdk/nodejs/620941/github-google-cloud

**Comment by helderco** [comment]
Hey @vikram-dagger, the CI guides are simple and already exist for the 3 SDKs. Should be quick to merge, no?

- [Dagger Go SDK in CI](https://docs.dagger.io/768421/go-ci/)
- [Dagger Python SDK in CI](https://docs.dagger.io/454108/python-ci/)
- [Dagger Node.js SDK in CI](https://docs.dagger.io/114934/nodejs-ci/)

Can we then redirect from these to the combined one?

[Context](https://discord.com/channels/707636530424053791/708371226174685314/1095134707076829264)

**Comment by vikram-dagger** [comment]
> Hey @vikram-dagger, the CI guides are simple and already exist for the 3 SDKs. Should be quick to merge, no?

https://github.com/dagger/dagger/pull/4937

**Comment by gerhard** [comment]
Do you think that we can close this now @vikram-dagger?

**Comment by vikram-dagger** [comment]
> Do you think that we can close this now @vikram-dagger?

Yes, this is done already, although I think the status was updated in Linear and not here.
