### ISSUE TITLE
Dynamically produce a chronologically-sorted index page for guides

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#4576]
### What is the issue?

Currently, the index page for guides is manually generated and has minimal information eg. https://docs.dagger.io/sdk/go/275922/guides

We intend to centralize all the guides under a new "Tutorials" primary node in the navigation tree.

Ideally this Tutorials page should hold a dynamically generated index with the following characteristics:
- Chronologically sorted
- For each guide, display title, author, date of publication, abstract (maybe?) and tags
- Allow filtering of listed items by tag eg. view only guides with tag `go`

**Comment by vikram-dagger** [comment]
Closing as duplicate of #4581

**Comment by vikram-dagger** [comment]
@crjm does the new guides index already implement the requirement in https://github.com/dagger/dagger/issues/4628? It seems to be Docusaurus metadata.

**Comment by crjm** [comment]
Yep, the index is sorted based on the date in the docs metadata.
