### ISSUE TITLE
Convert existing code snippets in docs to interactive API Playground embeds

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#4617]
### What is the issue?

This task is to convert existing code snippets (excepting those which have external dependencies) in docs to interactive API Playground embeds.

Done:
- All code snippets are represented as API Playground embeds (excepting those which have external dependencies)

**Comment by vikram-dagger** [comment]
I tried to do this starting with the get started guides. However each get started guide assumes that you have an application in the current directory which is to be tested, built etc. This assumption is fine for local development but doesn't work for the API Playground. How should we handle this so we can produce interactive embeds for the get started guide @marcosnils ?

**Comment by vikram-dagger** [comment]
@marcosnils https://play.dagger.cloud/playground/8I0c_SMKQbj works but am embed using the same id https://play.dagger.cloud/embed/8I0c_SMKQbj fails. Any idea why this would happen? Note these are for raw GQL queries, not program code.

**Comment by crjm** [comment]
Looking into it!

**Comment by crjm** [comment]
Should be fixed now in with https://github.com/dagger/dagger.io/pull/1792

**Comment by vikram-dagger** [comment]
This PR only updates the API Concepts guide to use snippets. Other guides will be addressed in separate PRs.

Ping @marcosnils @crjm for review and approval.

**Comment by vikram-dagger** [comment]
> Should be fixed with [dagger/dagger.io#1792](https://github.com/dagger/dagger.io/pull/1792)

@crjm one UX issue: in the section https://docs.dagger.io/api/975146/concepts#object-identifiers, we ask the user to copy the id from the previous query to the next query. However it's very difficult to select the id, because the background is black and the text selection colours is brown/grey. Could we adjust the text selection colour in the Playground to make it more visible to users?

**Comment by crjm** [comment]
Looking into it!

**Comment by gerhard** [comment]
Do you think that we can close this now @vikram-dagger @crjm?

**Comment by vikram-dagger** [comment]
It's fine with me to close it, as this will likely become irrelevant with modules anyway.
