### ISSUE TITLE
Engine fails, hangs or becomes really slow when several operations are chained

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#4620]
Some users (cc @cpuguy83 ) have observed that when chaining  several `WithMountedDirectory` calls, sometimes the engine becomes extremely slow or completely unresponsive. 

Discord thread: https://discord.com/channels/707636530424053791/1075544944388882522

@cpuguy83 managed to come up with a simple repro here.

Repro snippet: https://gist.github.com/cpuguy83/b61f22d05fd05a6407008d944f5858f4

cc @sipsma

**Comment by marcosnils** [comment]
Next step is to understand if this is a Dagger or Buikit specific behavior. I'll to reproduce it with Dockerfiles to do a quick rule out test.

**Comment by sipsma** [comment]
One super quick thing to check is if we are hitting the problem described in this issue: https://github.com/moby/buildkit/issues/1459#issuecomment-1197430137

If so, `dmesg` should show stack traces from the kernel for a hung task after this problem happens.

**Comment by marcosnils** [comment]
> One super quick thing to check is if we are hitting the problem described in this issue: [moby/buildkit#1459 (comment)](https://github.com/moby/buildkit/issues/1459#issuecomment-1197430137)

might not be the case. I'm on `5.19.0-31-generic` and can still repro

**Comment by marcosnils** [comment]
wasn't able to repro using a simplified Dockerfile example: https://gist.github.com/marcosnils/ab3b020e90b41d918b85bb17a2694835

Even though the behavior is not exactly the same, seems like `mount` is not particularly the issue here

**Comment by pmengelbert** [comment]
I have been having this issue as well, and it seems to happen when I have many chained `WithExec` calls. I'll try to put together a minimal reproduction if it will help diagnose.

**Comment by cpuguy83** [comment]
I also cannot reproduce this with a Dockerfile (neither Docker nor build via the dagger SDK).
I also added a simplified reproducer to the gist (https://gist.github.com/cpuguy83/b61f22d05fd05a6407008d944f5858f4#file-simplified-go).

If you run the simplified reproduce above with default (10) it works pretty much fine.
If you bump that to 11 it gets very slow... 20s to complete a fully cached build compared to 5s with 10 (note that even running it with 1 takes 5s fully cached).
A run with 12 took a full 3mins to complete, during this time it just sits there with no output except for the image metadata load.
So beyond 10 seems like a the tipping point.

**Comment by marcosnils** [comment]
thx for the inputs @cpuguy83 . We've assigned super high priority to this, so expect an update this week :raised_hands:

**Comment by TomChv** [comment]
I did several tests on this case and I think the issue comes from the depth of the query to solve.

When you chain 12 mounted, the query is really deep and it seems that the resolver struggles to deal with all those containers and mounts to solve. Especially since everything is done at the same time!

As a workaround, I tried to use a temporary container to reduce the query depth and execute mounts gradually and it definitely improves performance and caching.

```go
	ctmp := client.Container().From("busybox:latest")

	for i := 0; i < count; i++ {
		// Recreate empty container (operations is cached, so it's instant)
		c := client.Container().From("busybox:latest")
		
		// Mount previous result stored in tmp, add new directory and execute ls
		c = c.
			WithMountedDirectory("/tmp", ctmp.Directory("/tmp")).
			WithMountedDirectory("/tmp/bin"+strconv.Itoa(i), base.Directory("/bin")).
			WithExec([]string{"/bin/sh", "-c", "ls -lh /tmp"})

		_, err = c.ExitCode(ctx) // Solve operation there
		ctmp = ctmp.WithMountedDirectory("/tmp", c.Directory("/tmp")) // Copy back result to temp container
	}
```

Here is an example below with `count = 15`.

```shell
#4 0.111 drwxr-xr-x    2 root     root        4.0K Mar  4 02:03 bin0
#4 0.111 drwxr-xr-x    2 root     root        4.0K Mar  4 02:04 bin1
#4 0.111 drwxr-xr-x    2 root     root        4.0K Mar  4 02:04 bin10
#4 0.111 drwxr-xr-x    2 root     root        4.0K Mar  4 02:04 bin11
#4 0.111 drwxr-xr-x    2 root     root        4.0K Mar  4 02:04 bin12
#4 0.111 drwxr-xr-x    2 root     root        4.0K Mar  4 02:04 bin13
#4 0.111 drwxr-xr-x    2 root     root       12.0K Jan  3 22:48 bin14
#4 0.111 drwxr-xr-x    2 root     root        4.0K Mar  4 02:04 bin2
#4 0.111 drwxr-xr-x    2 root     root        4.0K Mar  4 02:04 bin3
#4 0.111 drwxr-xr-x    2 root     root        4.0K Mar  4 02:04 bin4
#4 0.111 drwxr-xr-x    2 root     root        4.0K Mar  4 02:04 bin5
#4 0.111 drwxr-xr-x    2 root     root        4.0K Mar  4 02:04 bin6
#4 0.111 drwxr-xr-x    2 root     root        4.0K Mar  4 02:04 bin7
#4 0.111 drwxr-xr-x    2 root     root        4.0K Mar  4 02:04 bin8
#4 0.111 drwxr-xr-x    2 root     root        4.0K Mar  4 02:04 bin9
#4 DONE 0.7s
go run ./test.go 15  3.25s user 0.68s system 28% cpu 13.988 total
```

That's also maybe why you do cannot reproduce the issue with `Dockerfile`, since operations are done gradually and not at once.

I think it explains now why it takes time when you chain everything. However, the evaluation should not be that long.

@sipsma I'm maybe wrong but that may come from the LLB evaluation, do you have any insight about how it works internally? And if there is anything we can do on Dagger itself?

**Comment by marcosnils** [comment]
:wave: just thinking out loud here after reading your comments Tom

> When you chain 12 mounted, the query is really deep and it seems that the resolver struggles to deal with all those containers and mounts to solve. Especially since everything is done at the same time!

Do you mean the graphql resolver? I find it surprising that resolving a 12 elements deep query actually takes that much time :thinking: 

---

Is there a way to instrument how much time the resolver takes? Aside from this issue, I'd guess this is a nice metric to have to understand where times in a complete execution are going since several things happen during a pipeline run

**Comment by cpuguy83** [comment]
I also found that if we reduce the chaining by using intermediate containers and just grab the rootfs and put it into the original container it helps a lot.

**Comment by TomChv** [comment]
> Do you mean the graphql resolver? 

I'm thinking about the LLB resolver instead. We may had that kind of issue with previous dagger version when the CUE dag was large.
It takes time to evaluate by CUE but also to resolve sometime.

I also think that monitoring those metrics would be very helpful!

**Comment by sipsma** [comment]
Also just was debugging something with a different user this morning that looks like it could be this, so taking a look at it some more.

I ran the simple reproducer @cpuguy83 provided (thank you btw!) and saw that the engine process running in docker was taking up 100% of a cpu. Sending SIGQUIT to the engine process gave me this stack trace in the logs: https://gist.github.com/sipsma/4868337101c84d89b9917eafe6d79a22

The goroutine that sticks out to me is:
```
goroutine 1211 [runnable]:
github.com/moby/buildkit/solver/llbsolver.recomputeDigests({0x18a2e48, 0x4000f01450}, 0x40003210b0?, 0x40009b1958?, {0x4000a9ec80, 0x47})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/vertex.go:190 +0x30c fp=0x40009b1190 sp=0x40009b1190 pc=0xd6f64c
github.com/moby/buildkit/solver/llbsolver.recomputeDigests({0x18a2e48, 0x4000f01450}, 0x4000a9f090?, 0x47?, {0x4000a9ee10, 0x47})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/vertex.go:202 +0x114 fp=0x40009b1230 sp=0x40009b1190 pc=0xd6f454
github.com/moby/buildkit/solver/llbsolver.recomputeDigests({0x18a2e48, 0x4000f01450}, 0x4000a9f2c0?, 0x47?, {0x4000a9f090, 0x47})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/vertex.go:202 +0x114 fp=0x40009b12d0 sp=0x40009b1230 pc=0xd6f454
github.com/moby/buildkit/solver/llbsolver.recomputeDigests({0x18a2e48, 0x4000f01450}, 0x4000a9f5e0?, 0x47?, {0x4000a9f2c0, 0x47})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/vertex.go:202 +0x114 fp=0x40009b1370 sp=0x40009b12d0 pc=0xd6f454
github.com/moby/buildkit/solver/llbsolver.recomputeDigests({0x18a2e48, 0x4000f01450}, 0x4000a9f9f0?, 0x47?, {0x4000a9f5e0, 0x47})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/vertex.go:202 +0x114 fp=0x40009b1410 sp=0x40009b1370 pc=0xd6f454
github.com/moby/buildkit/solver/llbsolver.recomputeDigests({0x18a2e48, 0x4000f01450}, 0x4000a9fd10?, 0x47?, {0x4000a9f9f0, 0x47})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/vertex.go:202 +0x114 fp=0x40009b14b0 sp=0x40009b1410 pc=0xd6f454
github.com/moby/buildkit/solver/llbsolver.recomputeDigests({0x18a2e48, 0x4000f01450}, 0x4000a880f0?, 0x47?, {0x4000a9fd10, 0x47})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/vertex.go:202 +0x114 fp=0x40009b1550 sp=0x40009b14b0 pc=0xd6f454
github.com/moby/buildkit/solver/llbsolver.recomputeDigests({0x18a2e48, 0x4000f01450}, 0x4000a88500?, 0x47?, {0x4000a880f0, 0x47})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/vertex.go:202 +0x114 fp=0x40009b15f0 sp=0x40009b1550 pc=0xd6f454
github.com/moby/buildkit/solver/llbsolver.recomputeDigests({0x18a2e48, 0x4000f01450}, 0x4000a88a00?, 0x47?, {0x4000a88500, 0x47})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/vertex.go:202 +0x114 fp=0x40009b1690 sp=0x40009b15f0 pc=0xd6f454
github.com/moby/buildkit/solver/llbsolver.recomputeDigests({0x18a2e48, 0x4000f01450}, 0x4000a88f50?, 0x47?, {0x4000a88a00, 0x47})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/vertex.go:202 +0x114 fp=0x40009b1730 sp=0x40009b1690 pc=0xd6f454
github.com/moby/buildkit/solver/llbsolver.recomputeDigests({0x18a2e48, 0x4000f01450}, 0x4000a89130?, 0x47?, {0x4000a88f50, 0x47})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/vertex.go:202 +0x114 fp=0x40009b17d0 sp=0x40009b1730 pc=0xd6f454
github.com/moby/buildkit/solver/llbsolver.recomputeDigests({0x18a2e48, 0x4000f01450}, 0x4000785db0?, 0x47?, {0x4000a89130, 0x47})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/vertex.go:202 +0x114 fp=0x40009b1870 sp=0x40009b17d0 pc=0xd6f454
github.com/moby/buildkit/solver/llbsolver.loadLLB({0x18a2e48, 0x4000f01450}, 0x4000b38d50, {0x0, 0x0}, 0x4000321080)
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/vertex.go:265 +0x394 fp=0x40009b1b00 sp=0x40009b1870 pc=0xd6fa04
github.com/moby/buildkit/solver/llbsolver.Load({0x18a2e48, 0x4000f01450}, 0x4000b38d50, {0x0, 0x0}, {0x4000321050, 0x5, 0x5})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/vertex.go:149 +0xd0 fp=0x40009b1b40 sp=0x40009b1b00 pc=0xd6edd0
github.com/moby/buildkit/solver/llbsolver.(*llbBridge).loadResult(0x4000426960, {0x18a2e48?, 0x4000f01450}, 0x52a98?, {0x4000ff05d0, 0x1, 0x4000b5dda8?}, {0x0, 0x0, 0x0})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/bridge.go:130 +0x61c fp=0x40009b1d60 sp=0x40009b1b40 pc=0xd5a38c
github.com/moby/buildkit/solver/llbsolver.(*resultProxy).loadResult(0x4000bcce00, {0x18a2e48?, 0x4000f01450?})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/bridge.go:227 +0x54 fp=0x40009b1e00 sp=0x40009b1d60 pc=0xd5b424
github.com/moby/buildkit/solver/llbsolver.(*resultProxy).Result.func2({0x18a2e48, 0x4000f01450})
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/solver/llbsolver/bridge.go:255 +0x21c fp=0x40009b1eb0 sp=0x40009b1e00 pc=0xd5b99c
github.com/moby/buildkit/util/flightcontrol.(*call).run(0x4000f03e60)
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/util/flightcontrol/flightcontrol.go:121 +0x64 fp=0x40009b1f10 sp=0x40009b1eb0 pc=0x6de3b4
github.com/moby/buildkit/util/flightcontrol.(*call).run-fm()
        <autogenerated>:1 +0x28 fp=0x40009b1f30 sp=0x40009b1f10 pc=0x6e0398
sync.(*Once).doSlow(0x4000a2b7c0?, 0x0?)
        /usr/local/go/src/sync/once.go:74 +0x100 fp=0x40009b1f90 sp=0x40009b1f30 pc=0x834d0
sync.(*Once).Do(0x4000d92060?, 0x4000b5df90?)
        /usr/local/go/src/sync/once.go:65 +0x24 fp=0x40009b1fb0 sp=0x40009b1f90 pc=0x833a4
github.com/moby/buildkit/util/flightcontrol.(*call).wait.func1()
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/util/flightcontrol/flightcontrol.go:164 +0x2c fp=0x40009b1fd0 sp=0x40009b1fb0 pc=0x6deb7c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40009b1fd0 sp=0x40009b1fd0 pc=0x7cf54
created by github.com/moby/buildkit/util/flightcontrol.(*call).wait
        /go/pkg/mod/github.com/moby/buildkit@v0.11.0-rc3.0.20230222163458-34a576c411ea/util/flightcontrol/flightcontrol.go:164 +0x458
```

I need to go look into what's exactly happening in the buildkit code there but it seems like a strong possibility there's some n^2 or worse behavior happening in buildkit's llbsolver, which would explain why there's such a huge degradation from n=10 to n=11... Will update with what I find.

**Comment by sipsma** [comment]
Sent out a PR to buildkit with a fix: https://github.com/moby/buildkit/pull/3732
