### ISSUE TITLE
Go SDK: Better way to extract Stdout and Stderr from failed commands

### ISSUE THREAD

**Issue by blairdrummond** [dagger/dagger#4622]
### What are you trying to do?

I want a more parseable version of [this solution](https://github.com/dagger/dagger/issues/3997). When a `withExec` command has a non-zero exit code, I still expect there to be a Stdout and Stderr. At the moment I need to parse that out of [the err.Error() message](https://github.com/dagger/dagger/pull/4161/files/a4b51ddb3b69e5ea2278f7fdb98026c6da67dfda#diff-341172efc3ae450d87e524bff8a3338bc73ea8f60e881226524bd76a20634139R147).

### Why is this important to you?

I am trying out Dagger with `go test`, and running commands that may return non-zero exit codes, like on scans that find vulnerabilities. When this happens, I want to get the Stdout and Stderr messages and format them nicely as usual.

Maybe this is an unintended use of Dagger, but what I want is to run `go test` as usual to orchestrate; I want to use Dagger to run the `aquasec/trivy` and `aquasec/tfsec` and such within their own containers instead of building a single image that has all the tools.

### How are you currently working around this?

For now I'm going to parse the stdout: and stderr: out of the error message, but this is unintuitive and error prone (and I expect it to break later)

Thanks!

**Comment by dolanor** [comment]
Hi, I would believe it's a duplicate of https://github.com/dagger/dagger/issues/3192
I close this for now, but don't forget to subscribe on #3192.
And if you don't feel it's a duplicate, please reopen this one.
