### ISSUE TITLE
API Playground embed throws errors

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#4633]
### What is the issue?

To reproduce:
- Visit https://docs.dagger.io/593914/quickstart-hello
- Click the Play button in the API playground embed (any language)
- Login if prompted
- Click the Play button
- An error message appears like `forwarding ResolveImageConfig: no such job 7lnkxo8kly8o9exjzsue7qgv0`

![image](https://user-images.githubusercontent.com/112123850/220575478-e7cc0088-9917-4c2d-826e-0cec3a782482.png)

**Comment by marcosnils** [comment]
this is already being worked on
