### ISSUE TITLE
The quickstart codeblock for Go is broken

### ISSUE THREAD

**Issue by mieubrisse** [dagger/dagger#4640]
### What is the issue?

On https://docs.dagger.io/593914/quickstart-hello/ after "add the following code to it.", there's a big black box with this error:

`Application error: a client-side exception has occurred (see the browser console for more information).`

My console has:

<img width="1034" alt="Screen Shot 2023-02-24 at 10 18 02" src="https://user-images.githubusercontent.com/1142185/221188170-e9d314bb-858d-410b-a311-a002e59cfb34.png">

### Log output

See screenshot above

### Steps to reproduce

Simply visit https://docs.dagger.io/593914/quickstart-hello/ (persists through refresh for me)

### SDK version

NA (I didn't even get to installing the bug)

### OS version

MacOS 12.5

**Comment by marcosnils** [comment]
Seems like you're using Chrome? 

By any chance do you have an add-blocker extension of some sort? This could generally cause.
