### ISSUE TITLE
Python: `dagger.api.gen` should be just `dagger` in reference docs

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#4685]
https://discord.com/channels/707636530424053791/1037455051821682718/1080836880356102265

cc @vikram-dagger @helderco

**Comment by d3rp3tt3** [comment]
@vikram-dagger , I assigned this to you. Can you please pick this one up soon? It looks pretty straightforward.

**Comment by helderco** [comment]
My update on this was in the parent issue:
> Just an update: I started working on this a month ago but it was harder than it looks and had to shift focus to other priorities.

\- Originally posted in https://github.com/dagger/dagger/issues/4704#issuecomment-1495931681
