### ISSUE TITLE
Filter guides by content

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#4701]
### What is the issue?

It would be nice to add a way to filter to [the new guides page](https://docs.dagger.io/278912/guides) by its content, in addition to tags. This would be a nice complement to the global search box, which as we know is [quite broken](#4211).

**Comment by crjm** [comment]
I've thought about it, but didn't implement it because performance might not be the best when looking for a string inside each guide client-side. Will try it out with a pretty simple implementation and post an update here.

**Comment by shykes** [comment]
Our best shot might be to use the algolia integration already in place? If it can be adapted in the way we want. The index and query API is already setup.

**Comment by crjm** [comment]
Hmm, didn't thought of that. Makes a lot of sense actually. Will look into it tomorrow.

**Comment by crjm** [comment]
I've been able to create an Algolia search box that **queries the guides only** and allows searching for content present in them (content outside the guides is being filtered out). Implementing this would mean removing the current tag filter and only searching the content of the guides as this search box is only for content, not tags. **Searching for tags in this box would require a different implementation.**

I have a few questions though regarding this:
- How would the tags and the content search box coexist? First, we had clickable tags on each guide card. Then we added the tag filtering box. The filtering box should be removed if we add the content search box. But should we remove tags altogether if they are not searchable?
- Two searchbars would be available in the same view: one at the header for the general docs, one in the main body for the guides. Is this a problem?

**Comment by vikram-dagger** [comment]
>     * How would the tags and the content search box coexist? First, we had clickable tags on each guide card. Then we added the tag filtering box. The filtering box should be removed if we add the content search box. But should we remove tags altogether if they are not searchable?

Yes. I would remove the tags and tag filtering in this case. I'm not sure the tags serve any purpose if a user can anyway query the content ie. if searching for `go` will return the same result as searching for a tag named `go`, then the general-purpose query input is preferable and likely to be more useful.
 
>     * Two searchbars would be available in the same view: one at the header for the general docs, one in the main body for the guides. Is this a problem?

Yes, I think this is confusing. I understand the guide search appears only when in the guides section, but having two search boxes still seems weird to me.

**Comment by crjm** [comment]
> Yes. I would remove the tags and tag filtering in this case. I'm not sure the tags serve any purpose if a user can anyway query the content ie. if searching for `go` will return the same result as searching for a tag named `go`, then the general-purpose query input is preferable and likely to be more useful.

Agree 100%.

> Yes, I think this is confusing. I understand the guide search appears only when in the guides section, but having two search boxes still seems weird to me.

Yep, agree. Was thinking that maybe we can differentiate both searchbars with a combination of:
- The input placeholder
- Styling
- A description/label/annotation on top of the searchbar indicating that it serves a different purpose than the one in the header. 

LMK what you think so I can start working on it.

**Comment by crjm** [comment]
@vikram-dagger  with #4794 we are removing the default `/tags` & `/tags/{tag}` pages.
However, the tags list will still be shown at the bottom of each guide that has tags set in the front matter (at the top of the .mdx files).

My question here is, should we remove the tags all together, or should we keep them but remove their functionality (e.g. making them links)? I believe that having non-interactive tags does help in summarizing the guide's content (the user has a quick way to know what the guide is about).

**Comment by vikram-dagger** [comment]
> @vikram-dagger with #4794 we are removing the default `/tags` & `/tags/{tag}` pages. However, the tags list will still be shown at the bottom of each guide that has tags set in the front matter (at the top of the .mdx files).
> 
> My question here is, should we remove the tags all together, or should we keep them but remove their functionality (e.g. making them links)? I believe that having non-interactive tags does help in summarizing the guide's content (the user has a quick way to know what the guide is about).

Maybe just me, but I've got used to the behaviour of "clicking a tag in a tag cloud will filter to that tag". So I'm leaning towards removing the tags altogether because:
- they won't behave in that way (although: subjective expectation)
- the title of the guide should always communicate clearly what the guide is about (or else it's a bad title)
- we have a separate guides search input for the user as a better alternative to tag filtering

**Comment by mircubed** [comment]
moving to linear
