### ISSUE TITLE
🐞 client host directory paths cannot use `./` ?

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#4717]
surprised that these are not the same. do we have documented that the first works and the second does not?

```
const dir = client.host().directory('sdk/go')
const out = await dir.entries()
console.log(out)
```

```
const dir = client.host().directory('./sdk/go')
const out = await dir.entries()
console.log(out)
```
Node.js SDK

**Comment by helderco** [comment]
What outputs are you getting that are different? Have you tried the other SDKs? All of them should be just building that same query, there's no special handling. Can't test myself right now though, but will try it soon.

**Comment by mircubed** [comment]
@helderco may I assign this one to you?

**Comment by helderco** [comment]
Well, I can't reproduce. Need more info from @jpadams to confirm.

**Comment by jpadams** [comment]
Wow. No idea. Can't repro anymore myself. Must have been a transient thing based on my environment. Or something...
