### ISSUE TITLE
✨ `(*dagger.Client).Host().Directory(...)` equivalent for a `*dagger.File`

### ISSUE THREAD

**Issue by kminehart** [dagger/dagger#4745]
### What are you trying to do?

I am using `container.WithMountedFile` but `Host()` only lets me retrieve a `*dagger.Directory`, and there is no equivalent for a `*dagger.File`

### Why is this important to you?

It would be nice to have and would eliminate some boilerplate :)

### How are you currently working around this?

Right now I'm doing

```go
path := "/path/to/my/file.txt"
file := client.Host().Directory(filepath.Dir(path)).File(filepath.Base(path))
client.Container().From("alpine").WithFile("/file.txt", file)
```

**Comment by mircubed** [comment]
From @marcosnils : 
### What are you trying to do?

I'm trying to fetch use a file in my host machine and mount that into a container. It'd be nice to do something like

```
{
  host {
    file(path:"some/file.txt") {
      id
    }
  }
}
```

However, `file` is not currently a field of the `host` query.

### Why is this important to you?

So I don't have to make multiple calls.

### How are you currently working around this?

I have to use a `directory` call to get what I need. i.e: 

```
{
  host {
    directory(path: "some/folder") {
      file(path: "somefile.txt") {
        id
      }
    }
  }
}
