### ISSUE TITLE
[Docs] Guides search is broken in Algolia

### ISSUE THREAD

**Issue by crjm** [dagger/dagger#4759]
When a guide title appears in the algolia search bar after typing, clicking on the result takes you to the guide index instead of said guide.

![image](https://user-images.githubusercontent.com/70334844/225039411-f6066b19-ea54-42c4-8e3b-c3e377854d3f.png)

We should fix this behavior by taking the user to said guide instead of the index.

**Comment by marcosnils** [comment]
ref: https://discord.com/channels/707636530424053791/783828171153866782/1084857914050740224

**Comment by crjm** [comment]
Docusaurus has a default tags page, which [we cannot hide](https://github.com/facebook/docusaurus/discussions/5542). 
Currently it lives [here](https://docs.dagger.io/tags/).
It's also being crawled by Algolia right now.
I advise we remove the tags page with a redirection to `https://docs.dagger.io/404` in the `netlify.toml` config file.
@vikram-dagger

**Comment by crjm** [comment]
It also leads to [these pages being rendered](https://docs.dagger.io/tags/circle-ci/).

**Comment by crjm** [comment]
I modified the indexing pattern and it seems the guides are being crawled instead of the index. We can close this issue after someone can confirm that's the case.
BTW, I'm creating another issue regarding tags redirection.

**Comment by crjm** [comment]
Closing as it was confirmed that searching for guides works better now.
