### ISSUE TITLE
Update "Engine", "Runner" and "Session" terminology to be more consistent

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#4826]
As time has gone on some of our terminology has slowly morphed, but it's now reached the point where there's significant inconsistencies/vagueness in our docs and especially in our codebase, e.g.
1. It's not clear what the runner is vs. the engine
2. In our code, `engine/engine.go` is what starts a session with the remote engine, it's used by our CLI in `cmd/dagger/`. However `cmd/engine/main.go` is the implementation of the engine that executes on the runner (not the CLI). And `internal/engine/client.go` has the code the session created by `engine/engine.go` uses to connect to the process running the code in `cmd/engine/main.go` 😵‍💫

We should tweak the docs to be more consistent and clear and rename some of the packages in our codebase.

TODO: actual proposal on the exact tweaks to make

**Comment by crjm** [comment]
I would like to help on this. 
IMO anyone who hasn't been directly involved in the development of this part of the project can help with a different perspective to rubber-duck the content.

**Comment by mircubed** [comment]
related comment - https://github.com/dagger/dagger/issues/5303#issuecomment-1594044501

**Comment by TomChv** [comment]
@sipsma I have see some recent changes on core files, what is the current status of this issue?

**Comment by jedevc** [comment]
Think this is probably resolved:
- We don't really talk about the runner inside our code/docs any more
- Lots of our code has been reorganized around the `DaggerServer`
- Modules has changed a lot of the connection details

Not to say there's no work to do here, but the scope of the work is probably entirely distinct now with all the re-orgs.
