### ISSUE TITLE
Check Python variable names for case consistency

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#4852]
### What is the issue?

This task is to review all Python code samples and ensure that variable names use `snake_case` and not `camelCase`, for consistency with language conventions. Update where required and also update accompanying text to reflect this change.
Relates to https://github.com/dagger/dagger/pull/4825 and https://github.com/dagger/dagger/pull/4851

**Comment by FaithKovi** [comment]
hello, @vikram-dagger I want to work on this issue. Please assign

**Comment by mircubed** [comment]
@FaithKovi Thanks for reaching out to help support! Please ping @vikram-dagger if you run into any issues with this one.

**Comment by FaithKovi** [comment]
Okay, thanks @mircubed

**Comment by FaithKovi** [comment]
@vikram-dagger 
I wanted to confirm the location of the python code samples 

From the root folder, sdk/python right?

**Comment by vikram-dagger** [comment]
> @vikram-dagger I wanted to confirm the location of the python code samples
> 
> From the root folder, sdk/python right?

No, this refers to Python code snippets in the docs. Therefore, this will be all the snippets ending in `.py` under docs/current.

**Comment by FaithKovi** [comment]
Okay noted, thanks @vikram-dagger

**Comment by FaithKovi** [comment]
@vikram-dagger I checked the python code snippets in the docs and the variable names are all consistent

**Comment by helderco** [comment]
This was fixed by the recent doc snippet linting that was restored in:
- https://github.com/dagger/dagger/pull/5311
