### ISSUE TITLE
Docs: new guides section isn't being linted

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#4857]
We lint the code snippets in the SDK guides, but the new Guides section uses a different path for the snippets that isn't being included in that linting. This is creating some inconsistency in code formatting.

With the playground embeds though, it's no longer a direct reference between the snippet file and what you see on the page. I assume the playground embeds are created from the snippets, @vikram-dagger please correct me if I'm wrong.

**Comment by vikram-dagger** [comment]
> We lint the code snippets in the SDK guides, 

Can you please point me to this code?

> With the playground embeds though, it's no longer a direct reference between the snippet file and what you see on the page. I assume the playground embeds are created from the snippets, @vikram-dagger please correct me if I'm wrong.

Correct, documented at https://github.com/dagger/dagger/blob/main/docs/STYLE_GUIDE.md#api-playground-embeds

**Comment by helderco** [comment]
> Can you please point me to this code?

Sure! 

https://github.com/dagger/dagger/blob/b56aee2fe0875c1e3b5b47372e91afbee158c9ce/internal/mage/docs.go#L46-L61

In Python:

https://github.com/dagger/dagger/blob/b56aee2fe0875c1e3b5b47372e91afbee158c9ce/internal/mage/sdk/python.go#L50-L60

Where `poe lint-docs` is:

https://github.com/dagger/dagger/blob/b56aee2fe0875c1e3b5b47372e91afbee158c9ce/sdk/python/pyproject.toml#L82-L83

https://github.com/dagger/dagger/blob/b56aee2fe0875c1e3b5b47372e91afbee158c9ce/sdk/python/pyproject.toml#L107-L108

**Note**: I actually started to fix this locally but didn't finish, to deal with other priorities.

Go seems fine because the linting is done for all go files in the repo:

https://github.com/dagger/dagger/blob/b56aee2fe0875c1e3b5b47372e91afbee158c9ce/internal/mage/engine.go#L124-L131

Maybe we should do the same for the others. In Python, the linter has slightly different rules for docs, but that should be fine if their path is preserved.

**Comment by helderco** [comment]
> > With the playground embeds though, it's no longer a direct reference between the snippet file and what you see on the page. I assume the playground embeds are created from the snippets, @vikram-dagger please correct me if I'm wrong.
> 
> Correct, documented at https://github.com/dagger/dagger/blob/main/docs/STYLE_GUIDE.md#api-playground-embeds

From that guide:

> Currently supported file extensions are `.go`, `.ts`, `.js`, `.python`.

First of all, the extension for python is wrong (`.py`). Secondly, snippets for nodejs have been using `.mjs`. Is that supported? Or even `.mts`?

**Comment by vikram-dagger** [comment]
> > > With the playground embeds though, it's no longer a direct reference between the snippet file and what you see on the page. I assume the playground embeds are created from the snippets, @vikram-dagger please correct me if I'm wrong.
> > 
> > 
> > Correct, documented at https://github.com/dagger/dagger/blob/main/docs/STYLE_GUIDE.md#api-playground-embeds
> 
> Nice, I forgot about that. 🙂
> 
> From that guide:
> 
> > Currently supported file extensions are `.go`, `.ts`, `.js`, `.python`.
> 
> First of all, the extension for python is wrong (`.py`). Secondly, snippets for nodejs have been using `.mjs`. Is that supported? Or even `.mts`?

`.py` and `.mjs` are both supported. `.mts` is not. I've updated the guide with this info - thanks for pointing it out! https://github.com/dagger/dagger/pull/4874

**Comment by gerhard** [comment]
Is linting the snippets in docs sufficient to ensure that they run successfully?

Linting is the right way of catching programmatic and stylistic errors, but not testing that the code actually runs. Maybe linting is enough for now, but I am pretty sure that we want some type of integration tests that would show failures - maybe in GitHub Actions - when the code fails. Running these snippets and ensuring that they all exit with `0` would be sufficient.

---

I know that my comment is not on topic. I am mostly continuing a conversation that we started with @vikram-dagger on March 28th, 2023.

**Comment by helderco** [comment]
Yes, two separate things. Linting is fast and easy, brings more consistency to the examples and helps us follow good practices for users to copy.

As for tests, that was discussed but don't remember when or where. What I remember is that Andrea (I think) alluded that it was a burden on CI (time and cost continually increasing when adding more docs) and maintainability (keeping tests up to date with the code).

On maintainability, with CUE it was a bit easier since it's declarative, now it's a much harder problem with the multiple languages. As for simply running a script and checking exit code, it's not that simple. For example, many guides use external services that need to be set up with proper keys (GCR, AWS...).

So I believe consensus (at least for now) is that it's not worth to automatically test the documentation snippets.

**Comment by mircubed** [comment]
@vikram-dagger can we close this issue?

**Comment by helderco** [comment]
It's not done.

**Comment by helderco** [comment]
This was fixed in https://github.com/dagger/dagger/pull/5351

**Comment by helderco** [comment]
I realized Node.js isn't fixed yet.
