### ISSUE TITLE
Update Node get started to specify the TS configuration file if not present

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#4865]
### What is the issue?

The Typescript code fails if the user doesn't have a `tsconfig.json` file already. This is not explicitly stated anywhere, so should be added. The command to create the file if not already present is `tsc --init --module esnext --moduleResolution nodenext`

**Comment by helderco** [comment]
Ah sorry for not creating this issue before. I came up with this a couple weeks back. Even yesterday I had to use that command (had it slightly different `tsc --init --moduleResolution node --module ESNext`).

**Comment by vikram-dagger** [comment]
URL: https://docs.dagger.io/sdk/nodejs/783645/get-started#step-2-create-a-dagger-client-in-nodejs
