### ISSUE TITLE
🖐️ Execute multiple commands in the same 'WithExec' sentence

### ISSUE THREAD

**Issue by rubtobar** [dagger/dagger#4890]
### What happened? What did you expect to happen?

Hi,

I whould like to know how can i build a container with golang making a:
[...]
WithExec([]string{"apt-get", "update"}).
WithExec([]string{"rm", "-rf", "/var/lib/apt/lists/*"}).
[...]

if i try using something like this:
WithExec([]string{"apt-get", "update","&&","rm", "-rf", "/var/lib/apt/lists/*"}).

The contaner build complains saying that the command "apt-get update" only takes one argument.

I dont fully underestand how the commands are interpreted in order to fail in this case.

Using the tool "dive" https://github.com/wagoodman/dive i can see that multiple layers are generated for an apt update and i whould like to optimize as much as possible the number of layers. Run this kind of creation and eliminations at once whould prevent from creating aditional layers, making the container bigger.

I am missing something?
Sorry in advance if it's a naive question, i really like this project and i whould like to build my pipelines with it.

**Comment by mircubed** [comment]
Thanks for you kind comments @rubtobar ! If possible, can you join our [discord](https://discord.com/invite/dagger-io) and post this in our "[help forum](https://discord.com/channels/707636530424053791/1030538312508776540)"?

Our team can help here, but it will be much faster through Discord since we can talk in real-time.

**Comment by helderco** [comment]
Hey @rubtobar, you just need to run that as a shell script:

```go
WithExec([]string{"sh", "-c", "apt-get update && rm -rf && /var/lib/apt/lists/*"}).
```

**Comment by rubtobar** [comment]
Thanks, worked perfectly!
