### ISSUE TITLE
Warn users when SDK/CLI connects to incompatible engine

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#4904]
Our "default" codepaths ensure that SDK+CLI+Engine are all compatible with one another, but if you manually deploy an engine and connect a CLI/SDK to it, it's no longer guaranteed to be compatible.

Today, the only way users know about compatibility is by looking at the SDK release notes ([example](https://github.com/dagger/dagger/releases/tag/sdk%2Fpython%2Fv0.4.2)), but that's extremely non-obvious.

There are many possible ways of improving this situation and in the long run our goal should be to maintain backwards compatibility. However, one simple improvement in the much shorter term would be to just have the CLI/SDKs print a Warning when they connect to an incompatible engine. That will at least give users some more visibility.

**Comment by cpdeethree** [comment]
A driving usecase behind this: We started wondering this when working with remote dagger engines in EKS - in these kinds of installations where packaging and deployment of the engine is decoupled from the SDK it's very possible that the compatibility can drift and you may not want some magical autoupgrading behavior (or indeed, even be capable of that in many setups)

**Comment by TomChv** [comment]
To simplify the checking of the version, `dagger session` could also print a field `version` and then we implement a checker in our SDK / CLI that will verify if the given version is supported by the SDK/CLI.

The only problem is that our older engine version will not have this field so I don't know how we can be backwards compatible with them? Maybe just print a warning by default if there's no version field?

**Comment by sipsma** [comment]
Done in https://github.com/dagger/dagger/pull/5315
