### ISSUE TITLE
✨ Add Dagger SDK version to pipeline root labels

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#4918]
### What are you trying to do?

PR https://github.com/dagger/dagger/pull/4892 adds some SDK labels that are used for `user-agent` tagging to understand better our SDK usage. It'd be very valuable if we could also add these labels to the root pipeline here https://github.com/dagger/dagger/blob/4be9d6ee11cb5d3a66ec3e0f846436535009fd5e/core/pipeline/label.go#L33 so we can have visibility of the SDK version at the telemetry level.

cc @grouville @gerhard 

### Why is this important to you?

To understand which SDK was using when looking at a Dagger journal file

### How are you currently working around this?

N/A

**Comment by jedevc** [comment]
With the recent changes to telemetry, I don't think this makes sense any more - we now have different ways of tracking SDK usage today.

Closing this one, but we can re-open if we need to!
