### ISSUE TITLE
Create guide for substituting Docker with podman and others

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#5017]
### What is the issue?

This task is to create a guide to setup Dagger in order to use podman instead of Docker.

This has been requested multiple times:
https://discord.com/channels/707636530424053791/1100004042207416404
https://discord.com/channels/707636530424053791/1100004042207416404/1100081213760340029
https://discord.com/channels/707636530424053791/1073859480560865360

**Comment by jpadams** [comment]
@vikram-dagger this gist should help
https://gist.github.com/jpadams/789b259cb0cf7d2a166dc4f2fa588cc5

**Comment by shykes** [comment]
I believe that with `podman` aliased to `docker`, this should already work? I remember we had that issue and fixed it.
