### ISSUE TITLE
Add an example of glob patterns include/exclude in the filesystems guide

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#5070]
### What is the issue?

Add an example of glob patterns include/exclude in the filesystems guide: https://docs.dagger.io/421437/work-with-host-filesystem. 

From Helder: "I've seen users put things like glob("**.py") at the language level to traverse multiple subdirs. We need to show that this is also supported."

**Comment by JammUtkarsh** [comment]
Hey @vikram-dagger,

Is this issue still open? You have merged PR.

**Comment by vikram-dagger** [comment]
> Is this issue still open? You have merged PR.

Yes, it is open. The merged PR only added equivalent code for other languages for the existing examples.

**Comment by helderco** [comment]
See https://github.com/dagger/dagger/pull/4999#discussion_r1181210314. Notice that this is for adding `**` glob examples (two stars).

**Comment by JammUtkarsh** [comment]
This can now be closed!
