### ISSUE TITLE
TUI: show directory export target

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#5084]
## Problem

In the new (and awesome) TUI:

* directory imports (reading from host filesystem) are shown with the source path ✅ 
* but directory exports (writing from host filesystem) don't 😢 

Example: 
![image](https://user-images.githubusercontent.com/29565/236122949-033beb18-59aa-4d59-8724-311411c64bb2.png)

## Solution

Change how directory exports are displayed in the TUI, so that the target path is visible.

**Comment by shykes** [comment]
FYI @vito

**Comment by TomChv** [comment]
@vito Is there any new changes that could unblock this issue now?

**Comment by vito** [comment]
@TomChv Definitely; we can just create a custom Vertex using Progrock now, just like we do here:

https://github.com/dagger/dagger/blob/c7a2ec341ddc61e07fb69f4eae52d9fb41a520d5/core/service.go#L161-L173

I would especially like to see it print filenames to the vertex logs as it exports them, but I'm not sure if that's possible at the moment. But that's all bonus points, not sure if it's even possible at the moment, might be hard. :grin:

**Comment by TomChv** [comment]
Not stuck anymore! I'll take care of this issue next week
