### ISSUE TITLE
🐞 cannot diff with different relative paths

### ISSUE THREAD

**Issue by kralicky** [dagger/dagger#5117]
### What is the issue?

When performing a diff between a host sub-directory and a client `Directory` sub-directory, the following error is encountered: `TODO: cannot diff with different relative paths: "bin" != ""`

Example:
```go
hostBin := client.Host().Directory("bin") // bin/ already exists on the host

artifacts := client.Directory()
// ... write files to the bin/ directory in artifacts
artifactsBin := artifacts.Directory("bin")

diff := artifactsBin.Diff(hostBin) // will fail
diffs, err := diff.Entries(ctx) // error
```

Relevant source: https://github.com/dagger/dagger/blob/51f6dd9c5c2e64e55ff497a48ce1886bbca77103/core/directory.go#L431

### Log output

```
directory.withDirectory.withDirectory.withDirectory.withFile.withFile.withFile.withFile.withFile
.withFile.withFile.withFile.withFile.directory.diff TODO: cannot diff with different relative paths: "bin" != ""
```

### SDK version

Go sdk v0.6.1

### OS version

Linux srv1 6.1.27-2-MANJARO #1 SMP PREEMPT_DYNAMIC Thu May  4 06:46:21 UTC 2023 x86_64 GNU/Linux

**Comment by TomChv** [comment]
I cannot repro this error with `dagger v0.8.4`.

@kralicky do you still have this issue?

**Comment by kralicky** [comment]
Nope, this is no longer an issue.

**Comment by TomChv** [comment]
Good, I'm closing it then 🚀
