### ISSUE TITLE
Deprecate `exitCode`

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#5124]
## Summary

I’m proposing we deprecate `exitCode` in favor of [`sync`](https://github.com/dagger/dagger/pull/5071).

## Background

If accepted, will resolve:
- https://github.com/dagger/dagger/issues/3192

## Motivation

The `Container.exitCode` field doesn’t make sense because you always get zero on success and you can’t get the non-zero value when the command fails due to a bug:
- https://github.com/dagger/dagger/issues/3192

We do get the value in the error:

```go
_, err := ctr.ExitCode(ctx)  // if no error we already know the result is 0
if exerr, ok := err.(*dagger.ExecError); ok {
    return exerr.ExitCode
}
```

Additionally, one of the problems with the [confusion over laziness](https://github.com/dagger/dagger/issues/4668) is that users use `.ExitCode(ctx)` everywhere just to force execution, not caring about the actual value of the exit code. But you’re able to use the more general [`.Sync(ctx)`](https://github.com/dagger/dagger/issues/5065) instead:

```diff
- _, err = ctr.ExitCode(ctx)
+ _, err = ctr.Sync(ctx)
```

And you can still get the exit code value from the error if needed:

```go
_, err := ctr.Sync(ctx)
if exerr, ok := err.(*dagger.ExecError); ok {
    return exerr.ExitCode
}
```

## Specification

```diff
type Container {
  """
  Exit code of the last executed command. Zero means success.

  Will execute default command if none is set, or error if there's no default.
  """
- exitCode: Int!
+ exitCode: Int! @deprecated(reason: "Use `sync` instead.")
}
```

## Caveat

There is one big difference between `ExitCode(ctx)` and `Sync(ctx)`. While the former triggers command execution, defaulting to the entrypoint and default args if no `WithExec` is defined in the pipeline, the latter does not.

Just “renaming” to a new `.Run(ctx)` that behaves the same doesn’t seem worth it. And some users don’t actually want to run the command (e.g., just do a `Dockerfile` build), so it pays to understand what’s going on.

We’ll just have to make this clear in documentation and examples:
- https://github.com/dagger/dagger/issues/3617

**Comment by gerhard** [comment]
This sounds good, let's do it & remove part of https://github.com/dagger/dagger/discussions/5374

**Comment by gerhard** [comment]
That's a good idea!

Is there a PR / issue that we can track for the [`v0.8.0` milestone](https://github.com/dagger/dagger/milestone/18)?

**Comment by helderco** [comment]
Yes, it's in https://github.com/dagger/dagger/issues/5479.
