### ISSUE TITLE
Expand environment variables in `withEnvVariable` values

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#5140]
### Discussed in https://github.com/dagger/dagger/discussions/5001

<div type='discussions-op-text'>

<sup>Originally posted by **wingyplus** April 21, 2023</sup>
I want to install something and append it to `PATH` to make it accessible. So how to prepend the new directory into the env variable as we do with `PATH`?</div>

Solution proposed by @vito : 

> I agree; extending $PATH seems like a common use case. it would be nice to have parity with Dockerfile ENV which supports interpolation.
> 
> It might be a surprising default, since who knows what values people might try to set in env vars. An expand: true param would be simple enough to implement by using [os.Expand](https://pkg.go.dev/os#Expand) and fetching values from the current image config.
> 
> ```
> container {
>   withEnvVariable(name: "PATH", value: "/opt/venv/bin:${PATH}", expand: true) {
>     withExec(args: []string{"sh", "-c", "echo $PATH"}) {
>       stdout
>     }
>   }
> }
> ```
> (Interpolate might be a more obvious name.)

**Comment by gerhard** [comment]
Your suggestion seemed elegant to me @vito: https://github.com/dagger/dagger/discussions/5001#discussioncomment-5689641
