### ISSUE TITLE
🐞 Interactive UI drops stderr

### ISSUE THREAD

**Issue by stobias123** [dagger/dagger#5150]
### What is the issue?

Just upgraded to the latest version of dagger `0.5.2` (golang sdk) to use the new pipeline logging features. I see the error output in the regular view, and in the "non interactive view" **but I dont see stderr in the "interactive view".**

Client initialization looks like this 
```golang
c, err = dagger.Connect(ctx, dagger.WithLogOutput(os.Stdout), dagger.WithLogOutput(os.Stderr))
```

Excerpt from my cobra cli...

```golang
terraformDeployable.InitAndPlan(ctx, c)
```

Func details and actual step execution looks like this
```golang
func (t *TerraformInstantiation) InitAndPlan(ctx context.Context, client *dagger.Client) {
	c := client.Pipeline("Terraform")
	src := t.getSrc(c)

	if t.WorkspaceOverride == nil {
		t.WorkspaceOverride = []string{"dev-us-west-2", "prod-us-west-2"}
	}

	eg, gctx := errgroup.WithContext(build.ContextWithTimeout(ctx, 20*time.Minute))
	for _, workspace := range t.WorkspaceOverride {
		eg.Go(func() error {
			client := c.Pipeline(workspace)
			dir := t.init(client, src, workspace)
			_, err := t.plan(client, dir).Stderr(gctx)
			return err
		})
	}

	if err := eg.Wait(); err != nil {
		log.Fatalf("Error running terraform plan: %v", err)
	}
}

```
Here's the `t.plan` and `t.init` funcs.
```golang
func (t *TerraformInstantiation) init(client *dagger.Client, src *dagger.Directory, workspace string) *dagger.Directory {
	c := client.Pipeline(fmt.Sprintf("[%s][%s] Terraform Init", t.Name, workspace))
	mountPath := fmt.Sprintf("/src/%s", t.Name)
	return t.terraformContainer(c, src).
		WithExec([]string{
			"terraform",
			"init",
		}).
		WithExec([]string{
			"terraform",
			"workspace",
			"select",
			workspace,
		}).Directory(mountPath)
}

func (t *TerraformInstantiation) plan(client *dagger.Client, src *dagger.Directory) *dagger.Container {
	c := client.Pipeline(fmt.Sprintf("[%s][plan] Terraform Plan", t.Name))
	buildContainer := t.terraformContainer(c, src)
	planArgs := []string{
		"terraform",
		"plan",
		"-out=plan.tfplan",
		"-lock=false",
	}
	if t.Version != nil {
		planArgs = append(planArgs, "-var", fmt.Sprintf("helm_version=%s", *t.Version))
		planArgs = append(planArgs, "-var", fmt.Sprintf("image_tag=%s", *t.Version))
	}
	return buildContainer.WithExec(planArgs)
}
```

### Log output

Here's the output in each view. Note that I can't scroll down any further to see the error details in my `terraform init` step.

interactive `dagger run -i <my_cli>`
![image](https://github.com/dagger/dagger/assets/590677/0617dd1b-ffbd-438e-a50d-94cb57830d4d)

regular `dagger run <my_cli>`
![image](https://github.com/dagger/dagger/assets/590677/afb2162a-94d1-4056-9145-0b04dcb967ae)

standlone `<my_cli>`
![image](https://github.com/dagger/dagger/assets/590677/2b65a644-93f1-4a31-88ea-8959f5132824)

### Steps to reproduce

See above client initialization and step execution.

### SDK version

0.5.2

### OS version

osx 13.3.1

**Comment by vito** [comment]
Hard to tell what's going on here - would you be able to put together steps to reproduce this that I can run myself?

I just pushed some more fixes/tweaks for the interactive TUI (#5232), so this _might_ be fixed by the next release, but I can't be completely sure. I haven't seen any issues with dropping output.

**Comment by mircubed** [comment]
@stobias123 just wanted to check in to see if you could add some additional details that @vito requested?

**Comment by stobias123** [comment]
Hey guys sorry for the delay here. @vito  - just added the details of the `t.plan` func - is that sufficient?

**Comment by mircubed** [comment]
@stobias123 we will close this as resolved for now, but feel free to reopen if you need additional support.
