### ISSUE TITLE
TUI: hide container stdout by default

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#5156]
## Context

Now that we have an awesome TUI merged, and soon released (yay!) I think we can finally make progress on an old topic: container output streams (stdout and stderr); pipeline output; and the difference between them.

## Problem

The current situation: there is no difference. If your container prints something (anything!), the user will see it in the TUI. If the TUI prints anything about the status of a step, a possible error... It came from the stdout of a container.

In my opinion, that is not ideal, we should change it.

1. Most of the stdout and stderr of a container is noise, unless there's an error, in which case you want to go back and investigate some of it.
2. The value of the TUI is diminished by having to show so much noisy logging by default.
3. The important questions ("what's the status of this step? Why did it fail?") are difficult to answer, because the answer is drowned in an ocean of logs, with no way to extract it semantically.

## Solution

With this awesome new TUI and the scaffolding behind it, I think now is a good time to start changing this, incrementally.

- Step 1 (the title of this issue): **hide stdout/stderr by default**. You can still see everything with a flag; and in case of error, maybe it all gets dumped to you (or maybe it doens't, and you just re-run it with the verbose flag)
- Step 2: we add an API for steps to explicitly send status, error etc. Data from that API is displayed prominently, by default.
- Step 3: over time access to raw logs becomes less and less important - everything you need is surfaced in the step status and error API; You only look at the raw logs very occasionally, when a) you're debugging and b) step status/error wasn't enough to find the answer (should be rare).

In my opinion, the sooner we agree on step 1 and implement it, the smoother the transition will be for users.

**Comment by shykes** [comment]
FYI @vito

**Comment by vito** [comment]
Here's the current state of things (as of #5151):

* While things are running, only failed and/or actively running commands show their output.
  * Completed commands are collapsed so you can stay focused on the bird's eye view and not get distracted by noisy output of "boring" successful commands.
* Failed and actively running commands are always pushed to the end of the output, so you never have to scroll around to find interesting things among a sea of logs.
* _Only on the final render_, i.e. after everything has completed, all output is displayed. The point of this is just to have everything available in the scrollback if you want to read it.
  * Any failed commands will still be at the bottom.

One thing I want users to not have to worry about is "oh crap, I saw that briefly print something interesting, but now it's hidden away, and I didn't run with `--verbose`, and I don't know if that will ever happen again." Teaching users to always pass `--verbose` as a result of this experience would be something to avoid.

**Comment by gerhard** [comment]
I can see that you have already thought about this @vito. Do we want to do something about this in a follow-up TUI - `v0.6.0` patch release?

**Comment by vito** [comment]
Circling back to this after a bit of dogfooding `dagger do`, I agree that it would be nice to hide all the noise.

My current idea is to add a `focus: true` flag to `WithExec` that will bubble up to the TUI. We can have `dagger do` respect it by default, which makes sense to me as its goal is to be a higher-level `dagger run`.

So in `dagger do` with `focus: true` used sparingly you would see something like this instead:

[![asciicast](https://asciinema.org/a/k0YwdT2c18guGoFcMo6hgH2kj.svg)](https://asciinema.org/a/k0YwdT2c18guGoFcMo6hgH2kj)

**Comment by shykes** [comment]
What if we did it at the pipeline level?

* Add an option to `Pipeline` to configure the focus behavior. Possible values could be `FocusFirstExec` to focus the first exec operation, `FocusLastExec`, `FocusNone`, `FocusAllExec`.
* Default would be `FocusLastExec` which would match the most common patterns IMO, but I could be wrong
* Also encourages the use of `Pipeline` to control what is presented to the user

**Comment by vito** [comment]
@shykes I like that line of thinking; it'd be great if you didn't have to remember to set a flag.

Worth noting that our own tests run two commands that I think we would want to see the output of:

1. [`gotestsum ./...`](https://github.com/dagger/dagger/blob/58a68e0a25cb809fa3b88c8b581b5e6b9ef07456/internal/mage/engine.go#L243), to run our tests with pretty output and generate a report
2. [`gotestsum tool slowest`](https://github.com/dagger/dagger/blob/58a68e0a25cb809fa3b88c8b581b5e6b9ef07456/internal/mage/engine.go#L244) to report the slowest tests

I suppose we would have to use `FocusAllExec` and put them in their own pipeline to set that flag. We've talked about having `dagger do` automatically place commands in a pipeline reflecting the command hierarchy, so having to set up another pipeline nested beneath might feel a little redundant; I'm not sure what I would name it.

Could still make sense as a sane default but I'll keep thinking.

---

Here's an idea:

```graphql
type Container {
  "All subsequent commands will be focused."
  focus: Container!

  "All subsequent commands will be unfocused."
  unfocus: Container!
}
```

I like that this could be a pattern implemented by all APIs, as opposed to just container execs. It's also easy to sprinkle into a call chain to debug something.
