### ISSUE TITLE
🐞 Running TUI with `--debug` flag exposes secret values

### ISSUE THREAD

**Issue by nipuna-perera** [dagger/dagger#5171]
### What is the issue?

Running the TUI with `dagger run --debug` exposes the secrets otherwise masked in the logs. I can observe the `withSecretVariable` being exposed in the listing of stages.

### Steps to reproduce

Run any pipeline that has a `withSecretVar` with `dagger run --debug go run pipeline.go`

### SDK version

Go SDK 0.6.3

### OS version

Mac OS 12.6.2

**Comment by sipsma** [comment]
Thank you for reporting @nipuna-perera, sent out a fix for this here: #5186
