### ISSUE TITLE
Need to turn TUI off

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#5185]
I want to be able to run `dagger run sh` to run commands against an open session. In this case the command I’m running needs to be interactive so I need control over stdin, stdout and stderr.

This is also related to https://github.com/dagger/dagger/issues/5181 but I’ve wanted to turn it off for some reason multiple times when running our test suites. During tests you get a lot of failed pipelines but it’s okay because we’re making assertions on that, but it adds a lot of noise to the output. Sometimes when I’m debugging, I just want to `Printf` some things and skip the whole TUI.

I tried to use a pipe or redirection so that `useTUI` is false:

https://github.com/dagger/dagger/blob/1d902d3f2e3bcc20765683602dbdff214ed012ac/cmd/dagger/engine.go#L20-L21

But it seems to swallow it 🐞:

```shell
$ dagger run env | grep DAGGER
# TUI shows up and all env vars are returned

$ dagger run env > out.txt
# TUI shows up and out.txt is empty
```

\cc @vito

**Comment by gerhard** [comment]
I **think** that this will be partially fixed by https://github.com/dagger/dagger/pull/5197. Would that be sufficient for you @helderco?
