### ISSUE TITLE
Deprecate sync Python

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#5192]
## Summary

Raise a deprecation warning when using the synchronous version of the Python SDK in favor of only the asynchronous one.

## Motivation

It’s simple to move from sync to async, but the opposite isn’t true. 

There’s multiple disadvantages for having these two versions:
- more complicated codebase leading to a higher **maintenance** burden
- adds **fragmentation** to the ecosystem since you can’t share `async` functions in sync code
- *sync* is **rarely used** from what we can see

But there’s another even more compelling reason. 

### Concurrency

It doesn’t make much sense to use the synchronous API with Dagger.

Due to the nature of our client/server architecture, we need to make concurrent requests for things that can run in parallel by the engine. If you’re using the synchronous API you’ll have to use threads, deal with the GIL and generally jump through hoops when we already have an asynchronous API that makes this easy.

Let’s take the example of running tests against a code base for multiple Python versions. This is a good candidate for running concurrent requests since they can run in parallel. Otherwise you need to test in sequence, taking much longer:

- [helderco/dagger-examples/test_multiple.py](https://github.com/helderco/dagger-examples/blob/main/test_multiple.py) → ~3m
- [helderco/dagger-examples/test_concurrency.py](https://github.com/helderco/dagger-examples/blob/main/test_concurrency.py) → ~1m

```mermaid
gantt
title Testing the FastAPI library with and without concurrency
dateFormat x
axisFormat %M:%S

section sync
Python 3.7 : 68, 37831
Python 3.8 : 37873, 63971
Python 3.9 : 64010, 97783
Python 3.10 : 97824, 128072
Python 3.11 : 128109, 162619

section concurrent
Python 3.7: 48, 51079
Python 3.8: 58, 50979
Python 3.9: 52, 51978
Python 3.10: 55, 52633
Python 3.11: 56, 59450
```

You can learn more about this in:
- https://github.com/dagger/dagger/issues/4766

### Confusion

The two versions (sync vs async) can also lead to more confusion. 

It’s a possible misconception by users unfamiliar with asynchronous code that by using an `await` it makes an asynchronous call without waiting for it to finish.

> We use the sync code because we have to execute it in the order. Build the image and then deploy it. In the build image part we create a base image with rust and everything we need to cross-compile the application. So here we are free to do that async because we build the image for the different platforms/architecture.

\- From [Discord](https://discord.com/channels/707636530424053791/1088575225026846822/1090224327816908962)

That’s incorrect. Just by using `async`/`await` is not asynchronous on it’s own (not concurrent to be exact). The `await` name should imply that it will wait for the asynchronous task to finish before proceeding, but this may not be obvious to some.

You need to use concurrency primitives like a *task group* to run multiple asynchronous functions concurrently.

#### Not concurrent

```python
async def test(client: dagger.Client):
    await testX(client)
    await testY(client)
    await testZ(client)
```

#### Concurrent

```python
async def test(client: dagger.Client):
    async with anyio.create_task_group() as tg:
        tg.start_soon(testX, client)
        tg.start_soon(testY, client)
        tg.start_soon(testZ, client)

```

See [But aren’t I using “async” with `await`?](https://github.com/dagger/dagger/issues/4766#python-sdk) for more information.

## How to migrate to async?

Here’s the **TL;DR**:
- Add `async` to the connection context manager;
- Add an `await` before methods that make requests to the API;
- If a function has `await` or `async` statements, add `async` to the function as well;
- Wrap the call to the first `async` function in `anyio.run()`.

```diff
+import anyio
import dagger

-def main():
+async def main():
-  with dagger.Connection() as client:
+  async with dagger.Connection() as client:
    ctr = client.container().from_("alpine").with_exec(["echo", "hello"])
-    output = ctr.stdout()
+    output = await ctr.stdout()
  print(output)

-main()
+anyio.run(main)
```

If you’re importing types from the synchronous API, replace with the one defined in `dagger` instead:
```diff
import dagger
-from dagger.api.gen_sync import BuildArg

-BuildArg("version", "2")
+dagger.BuildArg("version", "2")
```

### Running from a synchronous function

If your code base is fully “sync”, you can still call asynchronous Dagger from any synchronous scope. Just pass the first asynchronous function (coroutine) to `anyio.run()`:

```python
import anyio
import dagger

async def my_dagger_func():
    async with dagger.Connection() as client:
        ...

def my_sync_func():
    anyio.run(my_dagger_func)
    # do more after that's done
```

`anyio.run` kicks off the chain of coroutines in an event loop and waits until it’s all done.

### Blocking code

In fully synchronous code bases, there’s no need to worry about calling blocking code inside asynchronous functions, at least at the start.

It only matters if you’re running multiple tasks concurrently. Even If you’re not doing that yourself the SDK does it when it can (for example when converting objects to IDs before sending a request), but if you’re already using synchronous Dagger you already have that performance bottleneck.

At least after the initial quick migration, you’ll be able to **gradually migrate** more code to be non-blocking when you can invest the time to do it, including learning about it more.

Then you’ll see performance improvements where you couldn’t otherwise.

## Resources

For more information:
- [FastAPI: Concurrency and async / await](https://fastapi.tiangolo.com/async)
- https://github.com/dagger/dagger/issues/4766
- https://github.com/dagger/dagger/issues/4705

**Comment by gerhard** [comment]
We should remove this part of:
- https://github.com/dagger/dagger/discussions/5374
