### ISSUE TITLE
✨ `dagger run` does not print the running program's stdout

### ISSUE THREAD

**Issue by kminehart** [dagger/dagger#5196]
### What are you trying to do?

Weird use-case I'm sure but I have a Dagger pipeline ran using 'go run ./cmd', which prints some data to stdout, which we are writing to a file.

```
go run ./cmd > out.txt
```

When we use `dagger run` with this, it doesn't print anything.

### Why is this important to you?

There's probably a lot of weird cases where one would want your porgram's stdout to be piped to another program or to be written to a file. We are using it to write down the file paths of objects that are created by the pipeline where other processes will be used to copy them.

### How are you currently working around this?

We're just not using 'dagger run' for this at the moment.

---

I don't necessarily think this is a bug.

**Comment by kminehart** [comment]
Testing a fix for this now by just adding `cmd.Stdout = os.Stdout` [here](https://github.com/dagger/dagger/blob/main/cmd/dagger/run.go#L105)

**Comment by helderco** [comment]
Yeah, I mention it in https://github.com/dagger/dagger/issues/5185

**Comment by kminehart** [comment]
Hmm, actually it looks like it's already being set to stdout in non-interactive mode here: https://github.com/dagger/dagger/blob/main/cmd/dagger/run.go#L126

So I wonder why it's not actually working. :thinking:
