### ISSUE TITLE
🐞 `dagger listen` stopped working in v0.6.0 release

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#5205]
### What is the issue?

`dagger listen` doesn't work anymore since starting from v0.6.0, it starts the TUI instead of executing the actual `listen` command

### Log output

![image](https://github.com/dagger/dagger/assets/1578458/d0890996-c380-48e0-93bf-3a10358eec9c)

### Steps to reproduce

run `dagger listen` 

### SDK version

Engine v0.6.0

### OS version

N/A

**Comment by marcosnils** [comment]
> I don't think this was broken in the sense that it still ran the HTTP server, but the TUI was definitely broken because the command logged directly to `stderr`. Fix here: #5219

I think the fact that the TUI started was breaking the playground script which started `dagger listen` and then did something else in the background.

**Comment by vito** [comment]
> I think the fact that the TUI started was breaking the playground script which started `dagger listen` and then did something else in the background.

Ah interesting, in that case it might be best to just run it with `-s` or `--silent` in the script now that #5218 is merged.

Could also just remove the TUI from `dagger listen`. I can change #5219 to do that if it makes more sense.

**Comment by vito** [comment]
Throwing a curveball idea: could we retire `dagger listen` in favor of wrapping Playground with `dagger run`? :thinking: Sounds like that's sort of what your script was approximating. It's a bit different, since you'd have to use `$DAGGER_SESSION_PORT` and `$DAGGER_SESSION_TOKEN` and you'd no longer have a stable listen address (unless we make that configurable). But maybe it'd let us tidy up the CLI a bit, since it doesn't seem like most people would be using `dagger listen`.

**Comment by shykes** [comment]
`dagger listen` is just meant as a convenience wrapper around `dagger run`, for the use case "I want to debug the graphql API with curl". Unless it's very painful and expensive to keep `listen`, I would prefer keeping it. Even though, yes, it's a niche command and hopefully will become increasingly so.

**Comment by shykes** [comment]
Follow-up @vito : I prefer keeping `listen` BUT I do agree Playground maybe should switch to using `dagger run`, if it makes things easier. Like I said, `listen` is intendend as a convenience for users who "just want to use curl", and that doesn't match the description of Playground.

**Comment by vito** [comment]
@shykes 

> `dagger listen` is just meant as a convenience wrapper around `dagger run`, for the use case "I want to debug the graphql API with curl". Unless it's very painful and expensive to keep `listen`, I would prefer keeping it. Even though, yes, it's a niche command and hopefully will become increasingly so.

Got it. I suppose showing a TUI makes sense for this case then, so the user can see progress for GraphQL queries they're submitting.

> Also, unless I'm remembering wrong, `dagger listen` is not supposed to have a stable listening address. It's supposed to print a URL that is derived in the same way that `$DAGGER_SESSION_PORT` and `$DAGGER_SESSION_TOKEN` are - in other words, not stable.

Looks like it has always (at least in the Cloak Era) exposed a `--listen` flag with a default value of `127.0.0.1:8080`, and it doesn't set up a session token. We could change that default to `127.0.0.1:0` and then print the port that was selected instead, if we still want to let the user pass a stable address while defaulting to unstable.

Is there a ton of value in having an unstable address? Seems like it would hinder reusing `curl` commands from your shell history, for example.

**Comment by shykes** [comment]
> Got it. I suppose showing a TUI makes sense for this case then, so the user can see progress for GraphQL queries they're submitting.

Yes I agree.

> Is there a ton of value in having an unstable address? Seems like it would hinder reusing curl commands from your shell history, for example.

Yes you’re right…
