### ISSUE TITLE
🐞 `dagger run go run` stopped working with v0.6.0

### ISSUE THREAD

**Issue by schlapzz** [dagger/dagger#5216]
### What is the issue?

Since I upgraded the Dagger client (v0.6.0) and the Go SDK (v0.7.0) the Dagger command `dagger run go run ci/main.go`  stopped working.

### Log output

progress forwarding: mkdir /run/user/1000: permission denied

### Steps to reproduce

Checkout Pipeline from https://github.com/puzzle/goff.git
Run Dagger command `dagger run go run ci/main.go`

### SDK version

Go SDK 0.7.0

### OS version

Windows 11 with WSL 2 (Ubuntu)

**Comment by helderco** [comment]
Can you see if this solves it for you?
- https://github.com/dagger/dagger/pull/5210

**Comment by Gambler13** [comment]
I think this would solve the problem.
As a workaround you can create the missing directories on your host system manually.
```bash
sudo mkdir -p  mkdir /run/user/1000/dagger
sudo chmod -R 777 /run/user/1000
```

**Comment by gerhard** [comment]
@schlapzz did this solve your problem? If not, let us know so that we can sure that we have this fix in the next patch release.

**Comment by schlapzz** [comment]
The workaround from @Gambler13 is working for me.
I think #5210 should solve the issue as well (not tested yet, but code change look good to me)

**Comment by nipuna-perera** [comment]
I am seeing the same even though i'm not using `dagger run`. I'm running `go run` because I'm within Jenkins. This was working before 0.7.0.

**Comment by schlapzz** [comment]
Can confirm cli v0.6.1 fixes the problem ❤️
