### ISSUE TITLE
How to use a locally built image as container

### ISSUE THREAD

**Issue by dmarteau** [dagger/dagger#5245]
### What happened? What did you expect to happen?

We need to use a locally built image as container for running pipeline, I did not find anything in the  documentation on how to achieve this.

Actually, passing a locally built image to `client.container().from_(<local_image>)` lead to failure with the following error:
```
dagger.exceptions.QueryError: docker.io/<my_local_image>: not found
```

Thanks,

**Comment by helderco** [comment]
`from` pulls from a registry, where the default is `docker.io`. To import an image from the local docker engine see this issue:
- #5235

**Comment by helderco** [comment]
Closing in favor of:
- #5235
