### ISSUE TITLE
🖐️ Running Dagger with Apple Silicon (linux/arm64)

### ISSUE THREAD

**Issue by sFritsch09** [dagger/dagger#5289]
How can I set the **default Platform** to **linux/arm64** with the dagger GO SDK.

Problem is when I run dagger it starts the engine inside a docker image for linux/amd64 because it is set as default on my macbook and I like to change that in my Dagger pipeline. The container crashes with amd64 on an arm64 machine.

I don't get it how to set it with to following function:

`func (r *Client) DefaultPlatform(ctx context.Context) (Platform, error)`

and where do I set this at:

`ctx := context.Background()
	// initialize Dagger client
	client, err := dagger.Connect(ctx, dagger.WithLogOutput(os.Stdout))
	if err != nil {
		panic(err)
	}
	defer client.Close()`

**Comment by grouville** [comment]
Hi,
We'll need to add it to the docs 🙏 
Here is an example: https://github.com/dagger/dagger/issues/4567#issuecomment-1549808121

**Comment by sFritsch09** [comment]
The following pipeline is now working with platform set to linux/amd64 and building a Next App based on a Dockerfile:

`// build image and push to registry
func Build() {
	ctx := context.Background()
	// initialize Dagger client
	client, err := dagger.Connect(ctx, dagger.WithLogOutput(os.Stdout))
	if err != nil {
		panic(err)
	}
	defer client.Close()
	godotenv.Load()
	// read secret from host variable
	tag := os.Getenv("REGISTRY_IMAGETAG")
	reg_user := os.Getenv("REGISTRY_USER")
	reg_pass := client.SetSecret("reg-pass", os.Getenv("REGISTRY_PASS"))
	// dockerfile code base
	contextDir := client.Host().Directory(".", dagger.HostDirectoryOpts{
		Exclude: []string{".next", ".env", "magefiles", "go.*"},
	})
	// init container registry
	ctr := client.Container(dagger.ContainerOpts{Platform: "linux/amd64"}).WithRegistryAuth(tag, reg_user, reg_pass)

	ref, err := ctr.Build(contextDir).
		Publish(ctx, fmt.Sprintf(tag))
	if err != nil {
		panic(err)
	}

	fmt.Printf("Published image to %s\n", ref)
}`

**Comment by gerhard** [comment]
FTR: https://docs.dagger.io/7442989/cookbook#publish-image-to-registry

```go
// create container
c := client.Container(dagger.ContainerOpts{Platform: "linux/amd64"})
```

**Comment by gerhard** [comment]
As a follow-up, we should add a recipe to the cookbook.
