### ISSUE TITLE
`core/integration TestClientWaitsForEngine` fails intermittently

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#5306]
While running tests ~20 times for https://github.com/dagger/dagger/pull/5149#discussion_r1224441710, I have noticed that `core/integration TestClientWaitsForEngine` fails intermittently:

```go
FAIL core/integration

=== Failed
=== FAIL: core/integration TestClientWaitsForEngine (17.78s)
    engine_test.go:117:
            Error Trace:    /app/core/integration/engine_test.go:117
            Error:          Received unexpected error:
                            input:1: container.from.withServiceBinding.withMountedFile.withEnvVariable.withEnvVariable.withNewFile.withExec.exitCode process "time dagger query --debug --doc /query.graphql" did not complete successfully: exit code: 1

                            Stdout:

                            Stderr:
                            panic: open /.dagger_meta_mount/exitCode: no such file or directory

                            goroutine 1 [running]:
                            main.shim()
                                /app/cmd/shim/main.go:252 +0x1265
                            main.main()
                                /app/cmd/shim/main.go:60 +0x5d
                            Please visit https://dagger.io/help#go for troubleshooting guidance.
            Test:           TestClientWaitsForEngine

```

I have hit a few more like this one - will open separate issues so that we can track each of these separately.

While I do not have time to investigate right now, I wanted to capture it as an issue and come back to it another time, in case someone else doesn't beats me to it! Either way, I have been paying extra attention to test flakes in recent weeks & raising these seems important.

---
This failed with:
- an empty cache
- a dev build of https://github.com/dagger/dagger/pull/5149
- run with `_EXPERIMENTAL_DAGGER_INTERACTIVE_TUI=1 dagger run ./hack/make engine:testrace`
- dagger CLI `0.6.1`
- running on `Linux 5.15.81 #1-NixOS SMP x86_64 GNU/Linux` & `Docker 20.10.21`

**Comment by jedevc** [comment]
Thankfully, this flake seems to have gone away at some point (and replaced with others :cry:)

Closing this one out now though :tada:
