### ISSUE TITLE
🐞  Failing to run Elixir SDK

### ISSUE THREAD

**Issue by gmile** [dagger/dagger#5326]
### What is the issue?

Installing `dagger` Elixir SDK fails for me, when attempting to install either `1.0.0` or version from `main` branch.

### Log output

```
Mix.install [:dagger]
Error while loading project :dagger at /Users/eugene/Library/Caches/mix/installs/elixir-1.14.5-erts-13.2.2.1/5962b72f360e314a48eab2e764b5c632/deps/dagger
** (File.Error) could not read file "VERSION": no such file or directory
    (elixir 1.14.5) lib/file.ex:358: File.read!/1
    /Users/eugene/Library/Caches/mix/installs/elixir-1.14.5-erts-13.2.2.1/5962b72f360e314a48eab2e764b5c632/deps/dagger/mix.exs:4: (module)
    (elixir 1.14.5) src/elixir_compiler.erl:66: :elixir_compiler.dispatch/4
    (elixir 1.14.5) src/elixir_compiler.erl:51: :elixir_compiler.compile/3
    (elixir 1.14.5) src/elixir_module.erl:379: :elixir_module.eval_form/7
    (elixir 1.14.5) src/elixir_module.erl:105: :elixir_module.compile/6
    (elixir 1.14.5) src/elixir_compiler.erl:38: :elixir_compiler.eval_or_compile/3
    iex:1: (file)
```

```
Mix.install [{:dagger, github: "dagger/dagger"}]
* Getting dagger (https://github.com/dagger/dagger.git)
remote: Enumerating objects: 54235, done.
remote: Counting objects: 100% (351/351), done.
remote: Compressing objects: 100% (262/262), done.
remote: Total 54235 (delta 108), reused 296 (delta 80), pack-reused 53884
origin/HEAD set to main
Could not compile :dagger, no "mix.exs", "rebar.config" or "Makefile" (pass :compile as an option to customize compilation, set it to "false" to do nothing)
Unchecked dependencies for environment dev:
* dagger (https://github.com/dagger/dagger.git)
  could not find an app file at "/Users/eugene/Library/Caches/mix/installs/elixir-1.14.5-erts-13.2.2.1/5962b72f360e314a48eab2e764b5c632/_build/dev/lib/dagger/ebin/dagger.app". This may happen if the dependency was not yet compiled or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix.Error) Can't continue due to errors on dependencies
    (mix 1.14.5) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.5) lib/mix/tasks/deps.loadpaths.ex:43: Mix.Tasks.Deps.Loadpaths.run/1
    (mix 1.14.5) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.5) lib/mix.ex:782: anonymous fn/5 in Mix.install/2
    (elixir 1.14.5) lib/file.ex:1607: File.cd!/2
    (mix 1.14.5) lib/mix.ex:749: Mix.install/2
    iex:1: (file)
```

### Steps to reproduce

1. start `iex` session,
2. enter `Mix.install([:dagger])` or `Mix.install([{:dagger, github: "dagger/dagger"}])`
3. see the error

### SDK version

Elixir SDK 1.0.0

### OS version

macOS 13.3 (22E252)

**Comment by gmile** [comment]
Btw, I noticed that the version 1.0.0 of Elixir SDK being available at https://hex.pm/packages/dagger. If I go there and click on a "Changelog" link, it redirects me https://github.com/dagger/dagger/releases/tag/sdk%2Felixir%2Fv1.0.0, but no Elixir SDKs are currently visible under https://github.com/dagger/dagger/releases/

**Comment by gmile** [comment]
@wingyplus tagging you in case you want to look at this one 🙇

**Comment by wingyplus** [comment]
@gmile Thank you for using the SDK. ❤️ 

Could you try:

```elixir
Mix.install([
  {:dagger, github: "dagger/dagger", sparse: "sdk/elixir"}
])

Dagger.connect()
|> dbg()
```

I think we mistake somehow with testing release  process. But the SDK doesn't release yet. :)
 
@gerhard Do you have any clue?

**Comment by wingyplus** [comment]
@gerhard That's my fault https://github.com/dagger/dagger/pull/5286/files#diff-735d5b7ac2b3d07befb7e17064d7ce236f499436496ef0c46c651afef40be40dR172. Dry run need to set to `1` but I forgot to tell you. T_T

**Comment by gmile** [comment]
> ```
> Mix.install([
>   {:dagger, github: "dagger/dagger", sparse: "sdk/elixir"}
> ])
> ```

@wingyplus this worked, thanks! And thanks for working on the SDK, great stuff!

**Comment by gerhard** [comment]
Hi @gmile, thank you for spotting this! We did not mean to publish the SDK just yet.

That was a quick fix @wingyplus, it will get merged as soon as all the checks pass - any minute now.

**Comment by wingyplus** [comment]
> > ```
> > Mix.install([
> >   {:dagger, github: "dagger/dagger", sparse: "sdk/elixir"}
> > ])
> > ```
> 
> @wingyplus this worked, thanks! And thanks for working on the SDK, great stuff!

Glad to hear it's works. I'll update readme to avoid confusing. 🙇
