### ISSUE TITLE
✨ sdk(elixir): strict with httpc but open for user to switch http client

### ISSUE THREAD

**Issue by wingyplus** [dagger/dagger#5334]
### What are you trying to do?

**This is just idea.** 

The current implementation use `Req` which depends on `:castore` (used by Finch). So if we switch to `:httpc`, it means that we can cut down the dependency, and ensure that it work on escript. But some people might not want to use httpc, so we should open for the user to switch the client by implement the behaviour.

**Comment by wingyplus** [comment]
Ran into `:req` warning because of req graphql use old `:req`

```
warning: setting `auth: {username, password}` is deprecated in favour of `auth: {:basic, userinfo}`
  (req 0.4.8) lib/req/steps.ex:127: Req.Steps.auth/2
  (req 0.4.8) lib/req/request.ex:976: Req.Request.run_request/1
  (req 0.4.8) lib/req/request.ex:937: Req.Request.run/1
  (dagger 0.9.4) lib/dagger/query_builder.ex:107: Dagger.QueryBuilder.execute/2
  (hello_world_dagger 0.1.0) lib/mix/tasks/dagger.test.ex:79: Mix.Tasks.Dagger.Test.run/1
  (mix 1.15.7) lib/mix/task.ex:455: anonymous fn/3 in Mix.Task.run_task/5

**Comment by jedevc** [comment]
With #6905 merged, can this be closed now?

**Comment by wingyplus** [comment]
I think we can close it for now. 👍
