### ISSUE TITLE
✨ CLI/API/Engine version compatibility checks

### ISSUE THREAD

**Issue by vito** [dagger/dagger#5339]
### What are you trying to do?

Now that users wrap their code in `dagger run`, the CLI version is the source of truth for the Dagger API version. If the user forgets to upgrade their `dagger` CLI it is easy to end up with an SDK talking to an out-of-date CLI. Or vice versa: someone could be using a new dagger CLI with an out-of-date SDK.

### Why is this important to you?

Dagger is still rapidly evolving so this leads to occasional runtime breakage - or worse, confusing behavior that's hard to trace to a difference in version.

### How are you currently working around this?

There's no workaround at the moment, and it's even pretty difficult to verify compatibility because SDK versions (as present in `go.mod` or `package.json` etc) are not the same as the CLI/API version.

Each SDK _does_ know its expected CLI version, so what we can do is run a version compatibility check against the API on start and emit a warning if the version is significantly different, where "significantly" means major or minor version.

I think we can leave wiggle room at the patch level, since this version encompasses the CLI, TUI, API, and engine version. Any one of those may be involved in a patch bump, but they're likely probably still compatible at the API level which is what mostly matters with the SDK. We might just want to warn on _any_ difference, but it's hard to say right now.

**Comment by aweris** [comment]
This situation is quite common for me. I'm currently utilizing a dagger in dagger approach with two different repositories, and every time a new engine version is released, I have to update both repositories simultaneously and ensure that the versions are in sync. This is one of the primary reasons why I am considering reverting to a mono repo in order to simplify the dependency check process.

**Comment by helderco** [comment]
There's now an api check from the SDK to the API, released in 0.8.0:
- #5315

**Comment by TomChv** [comment]
I think it's fine to close the issue! The SDK shall always be up to date, we can reopen it in case I'm wrong
