### ISSUE TITLE
🐞 sdk(elixir): with_env_variables return error rather than returning the list of env variables

### ISSUE THREAD

**Issue by wingyplus** [dagger/dagger#5342]
### What is the issue?

From example:

```elixir
Mix.install([
  {:dagger, path: "."}
])

client = Dagger.connect!()

client
|> Dagger.Query.container()
|> Dagger.Container.from("alpine")
|> Dagger.Container.env_variables()
|> IO.inspect()
```

The API will return an error:

```elixir
{:error,
 %Dagger.QueryError{
   errors: [
     %{
       "locations" => [%{"column" => 40, "line" => 1}],
       "message" => "Field \"envVariables\" of type \"[EnvVariable!]!\" must have a sub selection."
     }
   ]
 }}
```
 
This should returns list of environment variable, not error.

### SDK version

elixir

### OS version

macOS 13.1 (22C65)

**Comment by dogukanzorlu** [comment]
first of all I got no errors when I tried on main branch, but I found why we got like that error and solution. I'm just writing to give you an idea.

[from_docs](https://graphql.org/learn/schema/#scalar-types): 
_A GraphQL object type has a name and fields, but at some point those fields have to resolve to some concrete data. That's where the scalar types come in: they represent the leaves of the query._

ref: [stackoverflow](https://stackoverflow.com/questions/53910519/field-createuaction-of-type-createuaction-must-have-a-sub-selection)

the error indicates you are missing a subselection for the type, so our query should look like this
`{
  user {
    id,
    contact {
      name
    }
  }
}`

not like this:
`{
  user {
    id,
    contact
  }
}`

I think we have an arg missing in the generated function here:

https://github.com/dagger/dagger/blob/844d7ea738a3a477a092be085baf5e7801b29f01/sdk/elixir/lib/dagger/gen/container.ex#L109-L116

@wingyplus

**Comment by wingyplus** [comment]
@dogukanzorlu yes. The SDK didn’t select   child argument. If you see in Go SDK https://github.com/dagger/dagger/blob/main/sdk/go/api.gen.go#L258, they’re select name and value after select envVariables.

**Comment by wingyplus** [comment]
@dogukanzorlu the fix was submitted at #5347. :)

**Comment by dogukanzorlu** [comment]
I came for fix but you are so fast :) for now our bug issues finished. Im tracking...

@wingyplus

**Comment by wingyplus** [comment]
👋 i would like to open the issur again. I found the bug that it will return a map instead of id string when calling id function.

I already have a patch but need more testing. So i will submit tomorrow aftet tested.
