### ISSUE TITLE
✨ Activate new TUI of Dagger 0.6 for SDKs

### ISSUE THREAD

**Issue by sFritsch09** [dagger/dagger#5348]
### What are you trying to do?

I think it is more convenient to run Dagger pipelines with the GO SDK in combination with mage.

This way I can have multiple tasks which can be run with `mage funcName`
Plus I can use mage/sh to run a simple shell cmd.

Still I like the new TUI of the Dagger CLI 0.6 and I like to see that for all SDKs as well 🚀 

### Why is this important to you?

I quote from blog: "Using Dagger should spark joy. If users are going to be running CI/CD builds all day, it needs to be easy on the eyes!"

### How are you currently working around this?

I still use mage

**Comment by gerhard** [comment]
I don't understand the issue.

I can run both `mage ci` & `dagger run mage ci` in this project https://github.com/thechangelog/changelog.com/tree/master/magefiles

`_EXPERIMENTAL_DAGGER_INTERACTIVE_TUI=1 dagger run mage ci` works too.

**Comment by sFritsch09** [comment]
Ahh got it, didn't think about using it before mage! Really nice thanks 😁
