### ISSUE TITLE
🐞 AttributeError: module 'dagger' has no attribute 'Connection' #1

### ISSUE THREAD

**Issue by senthilmk** [dagger/dagger#5358]
### What is the issue?

When using Python SDK. (Python 3.11 on Windows 11)

### Log output

    async with dagger.Connection() as client:
               ^^^^^^^^^^^^^^^^^
AttributeError: module 'dagger' has no attribute 'Connection'

### Steps to reproduce

import sys

import anyio
import dagger

from rich.console import Console

console = Console()

async def sample_run(args: list[str]):
    with console.status("Hold on..."):
        async with dagger.Connection() as client:
            # build container with cowsay entrypoint
            # note: this is reusable, no request is made to the server
            ctr = (
                client.container()
                .from_("python:alpine")
                .with_exec(["pip", "install", "cowsay"])
                .with_entrypoint(["cowsay"])
            )

            # run cowsay with requested message
            # note: queries are executed only on coroutines
            result = await ctr.with_exec(args).stdout()

    print(result)

if __name__ == '__main__':
    anyio.run(sample_run, sys.argv[1:])

### SDK version

python sdk

### OS version

Windows 11

**Comment by helderco** [comment]
I looks like you may have installed dagger with `pip install dagger` instead of `pip install dagger-io`. Can you confirm you have the right PyPI package?

**Comment by senthilmk** [comment]
You are right...
