### ISSUE TITLE
CLI example in documentation fails

### ISSUE THREAD

**Issue by jcrosby** [dagger/dagger#5423]
### What is the issue?

Running the example in [Step 3](https://docs.dagger.io/cli/389936/run-pipelines-cli#step-3-build-an-application-from-a-remote-git-repository) of the CLI documentation fails. Note that the example in Step 2 executed correctly without errors on the same machine.

### Log output

• Engine: 520d3686abe7
• Engine: 520d3686abe7
Error: Unknown argument "source" on field "withDirectory" of type "Container".
Field "withDirectory" argument "directory" of type "DirectoryID!" is required but not provided.
Build unsuccessful

### Steps to reproduce

1. brew install dagger/tap/dagger
2. click the copy icon in the upper right corner of the example
3. paste into build.sh
4. save the file
5. chmod +x build.sh
6. ./build.sh

### SDK version

CLI (dagger v0.6.3 darwin/arm64)

### OS version

macOS 13.4.1

**Comment by imownbey** [comment]
It seems like in some recent Dagger the `source` argument changed to `directory`. If you change that line to be:
```
      withDirectory(path:"/src", directory:"$source") {
```
it seems to fix it, although now I am getting the error:
```
█ [3.08s] exec go build -o dagger-builds-hello ./hello/hello.go
┣─╮ exec go build -o dagger-builds-hello ./hello/hello.go
█◀╯ [0.01s] copy /src/dagger-builds-hello /dagger-builds-hello
█ ERROR exporting to client directory
┣ [0.08s] copying files
┻ 
Error: failed to solve: error from receiver: open /Users/ianownbey/.Trash: operation not permitted
Build unsuccessful
ianownbey@Ians-MacBook-Pro ~ % 
```

**Comment by jcrosby** [comment]
Thanks for spotting this @imownbey. When I change `source` to `directory` locally, it works, so this may be a stale documentation bug.

**Comment by mircubed** [comment]
@vikram-dagger to review
