### ISSUE TITLE
Node.js: Export ´Client´ as a named export, instead of default

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#5434]
Import `Client` like the rest of codegen types:

```diff
-import Client, { connect, Container } from "@dagger.io/dagger"
+import { connect, Client, Container } from "@dagger.io/dagger"
```

Discussed in:
- https://github.com/dagger/dagger/pull/5141#discussion_r1196161481

Mentioned by users as well. Example in [discord](https://discord.com/channels/707636530424053791/1125996361117093958/1126050103422103572) in relation to https://github.com/dagger/dagger/issues/4036.

> **Warning**
> Breaking change. This is meant for a breaking release:
> - https://github.com/dagger/dagger/discussions/5374

**Comment by TomChv** [comment]
That mean every users that currently use Dagger in Typescript will have their pipeline broken after the update of the package until they also update their import.
Is there anything we shall do about it?

**Comment by gerhard** [comment]
Sounds good, let's do it!

**Comment by slumbering** [comment]
On top of updating docs, let's not forget to update the website:

![image](https://github.com/dagger/dagger/assets/1186424/1c246783-ab60-449d-a88d-4a4c23ae02c5)
