### ISSUE TITLE
✨ I want to add bitbucket pipline Integration

### ISSUE THREAD

**Issue by paikend** [dagger/dagger#5444]
### What are you trying to do?

https://docs.dagger.io/7442989/cookbook#integrations

Unfortunately, there is no integration for bitbucket pipeline in the documentation.

It would be nice if this part could be added. :)

### Why is this important to you?

There are many users who use bitbucket pipeline. If the function is introduced, I think that companies will use it a lot in enterprise units.

**Comment by dzeleniak** [comment]
I can take this on :)

**Comment by dzeleniak** [comment]
Hi @paikend,

I'm sorry to inform, but after looking into the issue, we are currently unable to run dagger from bitbucket pipelines.

Bitbucket has restricted the ability to run docker commands with the --privileged flag set to true ([source](https://support.atlassian.com/bitbucket-cloud/docs/run-docker-commands-in-bitbucket-pipelines/)), and currently dagger is configured to run Buildkit with privileged set to true: [dagger/engine/server/buildkitcontroller.go](https://github.com/dagger/dagger/blob/main/engine/server/buildkitcontroller.go#L111).

The request was made in [this discussion](https://github.com/dagger/dagger/discussions/1677#discussioncomment-2362265) as well.

**Comment by paikend** [comment]
Hi @dzeleniak,

Thank you for your efforts to support.

I posted an [issue](https://community.atlassian.com/t5/Bitbucket-discussions/Please-support-me-to-run-dagger-CI-CD/m-p/2445872#M4258) on the bitbucket community.

I'm interested in the CI/CD field, so I want to help Dagger grow.
thank you

**Comment by schlumpfit** [comment]
Is it really required to run dagger in privileged mode?

Maybe this can be changed to be configurable from the outside as a tradeoff between having only a subset of features vs having no dagger at all.

I think generally it is not a very good practice from a security point of view to even allow containers running in privileged mode?

**Comment by gerhard** [comment]
Yes, Dagger requires privileged mode. [The operator manual has a section that explains why](https://github.com/dagger/dagger/blob/a06c4a01065c845e5e6091ca10eb27b819231410/core/docs/d7yxc-operator_manual.md#can-i-run-the-dagger-engine-as-a-rootless-container).

@jpadams addressed a while back:
- https://github.com/dagger/dagger/discussions/1677#discussioncomment-3195089

Closing since there are no new alternatives in the last 6 months.
