### ISSUE TITLE
🐞 Some operations stopped caching since 0.6.3

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#5450]
### What is the issue?

Since v0.6.3, some operations stopped caching. See the steps below on how to reproduce.

I did not have time to dig into which of these changes introduced this change in behaviour, but I'm fairly certain that it's one of these: https://github.com/dagger/dagger/releases/tag/v0.6.3

For now, I am sharing for visibility (discovered it earlier today). When I get a moment, if someone else doesn't pick it up by then, my intention is to continue digging into this.

cc @vito @sipsma @helderco

### Steps to reproduce

```console
git clone https://github.com/thechangelog/changelog.com some-operations-stopped-caching
cd some-operations-stopped-caching/magefiles

# upgrade to Go SDK which uses Engine v0.6.2:
go get -u dagger.io/dagger@v0.7.2

# run the pipeline:
go run main.go -w ../ ci
# this will take less than 4m on the first run
# it will take consistently 15s on all subsequent runs, when nothing changes

# upgrade to latest Go SDK which uses Engine v0.6.3:
go get -u dagger.io/dagger@v0.7.3

# run the pipeline again:
go run main.go -w ../ ci
# this will take less than 4m on the first run
# it will take consistently 50s on all subsequent runs, when nothing changes
# the expectation is that all ops should be cached, but not all are
```

### SDK version

Go SDK v0.7.2

### OS version

macOS 12.6 connecting to remote Docker 24.0.2 via TCP (runs on NixOS 22.11)

**Comment by helderco** [comment]
From [Discord](https://discord.com/channels/707636530424053791/1003718839739105300/1129417923451166842): 

> the problem is that container hostnames are derived from LLB digests, and I think the difference in v0.6.3 is that host Directories now contain the session ID in their LLB, so that causes the hostname to change in every new Dagger session, which busts the cache (edited)
> 
> This will be partly fixed when services-v2 lands, since only services will have hostnames now. But it still means that client containers downstream of a service that depends on a host dir will have their cache busted, since the service hostname changing would propagate to it.

\- @vito

**Comment by gerhard** [comment]
Nice one! Glad that we have all spotted this 💪

**Comment by gerhard** [comment]
I just confirmed that https://github.com/dagger/dagger/pull/5474 fixes this via:

```
dagger version
dagger c7a440a47f8bde4c552962114bcf608a60809972 darwin/amd64
```

The fix is expected to land in the next Engine & CLI release, `v0.6.4`
