### ISSUE TITLE
🐞 Output lines are getting duplicated

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#5571]
### What is the issue?

When running `mage ci`, I am seeing duplicate STDERR lines:

```console
> mage ci
Creating new Engine session... Creating new Engine session... Creating new Engine session... OK!
Establishing connection to Engine... OK!
Establishing connection to Engine... OK!
Establishing connection to Engine... OK!
8: resolve image config for docker.io/hexpm/elixir:1.14.4-erlang-25.3.2-ubuntu-jammy-20230126
8: > in 📦 RUNTIME IMAGE > from hexpm/elixir:1.14.4-erlang-25.3.2-ubuntu-jammy-20230126
OK!
8: resolve image config for docker.io/hexpm/elixir:1.14.4-erlang-25.3.2-ubuntu-jammy-20230126
8: > in 🧰 TEST > from hexpm/elixir:1.14.4-erlang-25.3.2-ubuntu-jammy-20230126
OK!
8: resolve image config for docker.io/hexpm/elixir:1.14.4-erlang-25.3.2-ubuntu-jammy-20230126
8: > in 🎁 PRODUCTION IMAGE > from hexpm/elixir:1.14.4-erlang-25.3.2-ubuntu-jammy-20230126
8: resolve image config for docker.io/hexpm/elixir:1.14.4-erlang-25.3.2-ubuntu-jammy-20230126 DONE
8: resolve image config for docker.io/hexpm/elixir:1.14.4-erlang-25.3.2-ubuntu-jammy-20230126 DONE
8: resolve image config for docker.io/hexpm/elixir:1.14.4-erlang-25.3.2-ubuntu-jammy-20230126 DONE
```

Same is happening when running with `dagger run` (only seeing these at the very end):

<img width="1430" alt="image" src="https://github.com/dagger/dagger/assets/3342/40d98cce-3121-4d88-88ad-aaec25ce6c58">

WDYT @TomChv @helderco?

---

Yes, there is a different issue with the version number, the Engine is not experimental - will file a separate issue for that one.

### Steps to reproduce

1. `git clone https://github.com/gerhard/changelog.com`
2. `cd changelog.com`
3. `git checkout -b upgrade-dagger-to-0.8 origin/upgrade-dagger-to-0.8`
4. `mage ci`

### SDK version

Go SDK v0.8.0

### OS version

SDK / CLI on macOS 12.6 & Engine on NixOS 22.11 (Linux 5.15)

**Comment by helderco** [comment]
Yes, this was expected: https://github.com/dagger/dagger/pull/5488#issuecomment-1655570382

From https://github.com/dagger/dagger/pull/5488#issuecomment-1656491646

> As for [#5488 (comment)](https://github.com/dagger/dagger/pull/5488#issuecomment-1655570382), that test is testing concurrent provisioning for the automatic provisioning feature in the SDK, so it explicitly ignores an existing session. I say it's not a big deal in this case and we can remove LogOutput from the test. We'll be focusing more on the CLI experience going forward so hopefully less and less users will be running off the SDK directly in the future.
> 
> In the meantime this is the problematic situation that remains. It's if someone is doing multiple `Connect`s when executing via the SDK, so that provisioning logging will be all over the place. I've seen it being done in a complex python SDK codebase, especially in a test suite that uses dagger, so I wanted to make sure I had that covered. Two things help there: 1) status update is replaced in line and disappears when run interactively; 2) No status updates are printed when running non-interactively (e.g., log_output to a file).
