### ISSUE TITLE
🐞 Node.js SDK - Enum wrongly interpreted

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#5575]
### What is the issue?

There appears to be an issue with the interpretation of the Enum in the Node.js SDK.
In the example bellow ImageMediaTypes.Dockermediatypes should return `DockerMediaTypes` but instead it returns 0.

```ts
await client
.container()
.publish(gitLabImageRepo, {
    platformVariants: seededPlatformVariants,
    mediaTypes: ImageMediaTypes.Dockermediatypes, 
});
```

### Log output

```shell
GraphQLRequestError: Argument "mediaTypes" has invalid value 0.
Expected type "ImageMediaTypes", found 0.
    at file:///Users/doe0003p/Projects/it-service/qa/teamscale/base-images/tflint/node_modules/@dagger.io/dagger/dist/api/utils.js:155:23
    at Generator.throw (<anonymous>)
    at rejected (file:///Users/doe0003p/Projects/it-service/qa/teamscale/base-images/tflint/node_modules/@dagger.io/dagger/dist/api/utils.js:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: ClientError: Argument "mediaTypes" has invalid value 0.
  ```

### SDK version

Node.js SDK v0.8.0

### OS version

macOs 13.4.1

**Comment by TomChv** [comment]
Working on it!

It's pretty tricky because the enumeration need to be inserted as a raw value (without quote) but it is type of string in the Node SDK.
I need to find a workaround to format it in the correct way
