### ISSUE TITLE
🐞 Elixir SDK always hang when running with dagger run

### ISSUE THREAD

**Issue by wingyplus** [dagger/dagger#5666]
### What is the issue?

Found on Dagger 0.8.4. When using `dagger run elixir test.exs` (the script provided in steps to reproduce section). Instead of finish execution, it still hang.

<img width="1287" alt="Screenshot 2566-08-18 at 23 44 25" src="https://github.com/dagger/dagger/assets/484530/0259f47c-0310-4c12-83d8-3bd3b604af6e">

### Steps to reproduce

Use this script:

```elixir
Mix.install([{:dagger, "0.8.4"}])

client = Dagger.connect!()

client
|> Dagger.Client.container()
|> Dagger.Container.from("alpine")
|> Dagger.Container.with_exec(~w[echo hello])
|> Dagger.Sync.sync()

Dagger.close(client)
```

And then run `dagger run elixir test.exs`. It now hangs. :/

### SDK version

Elixir 0.8.4

### OS version

macOS

**Comment by wingyplus** [comment]
Running with stable engine instead of dagger run is work fine: 

```elixir
$ elixir test.exs
1: connect
1: > in init
1: starting engine
1: starting engine [1.46s]
1: starting session
1: starting session [0.28s]
1: connect DONE
{"port":54426,"session_token":"c63bac44-a3d7-4bf4-aa84-431ab7fabc0e"}

6: resolve image config for docker.io/library/alpine:latest
6: > in from alpine
6: resolve image config for docker.io/library/alpine:latest DONE

11: pull docker.io/library/alpine:latest
11: > in from alpine
11: resolve docker.io/library/alpine@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a
11: resolve docker.io/library/alpine@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a [0.01s]
11: pull docker.io/library/alpine:latest DONE

9: exec echo hello CACHED
9: exec echo hello CACHED
```

**Comment by wingyplus** [comment]
@vito Do you have any idea why it is stuck in TUI mode?

**Comment by wingyplus** [comment]
It's hang on `--progress=plain` also.

<img width="1296" alt="Screenshot 2566-08-18 at 23 53 01" src="https://github.com/dagger/dagger/assets/484530/b8d5947e-2372-45d8-ba7f-d9b0ce276cf9">

**Comment by wingyplus** [comment]
@vito @sipsma I’m not sure if it’s related to the engine. But I need some advice. 🙇‍♂️

It looks similar to gradle https://github.com/dagger/dagger/issues/5287 but not sure is it the same problem.

**Comment by wingyplus** [comment]
<img width="1911" alt="Screenshot 2566-08-23 at 23 59 07" src="https://github.com/dagger/dagger/assets/484530/8de4170f-5712-47d0-ade0-d27ac70030f1">

Found from `dagger run --debug`.

**Comment by gerhard** [comment]
Dagger `0.8.7` works for me on macOS 12.6.9:

https://github.com/dagger/dagger/assets/3342/91843917-ae54-4f4e-94dc-b3da978fd52c

Dagger `v0.8.7` also works on NixOS 22.11:

https://github.com/dagger/dagger/assets/3342/e49f13c1-d523-4ac4-aa12-e7c0b0d99f3b

Is this now fixed for you?

**Comment by wingyplus** [comment]
@gerhard I try with dagger 0.8.7 with macOS Ventura. It still hang:


https://github.com/dagger/dagger/assets/484530/011535d0-4d4b-4bc8-b6b0-6596d75e2628

**Comment by wingyplus** [comment]
Not sure if I missing something?

**Comment by wingyplus** [comment]
Here is my machine information from neofetch:

<img width="729" alt="Screenshot 2566-09-29 at 22 57 47" src="https://github.com/dagger/dagger/assets/484530/8039d310-1faf-4dc1-a684-5c4bd6d94a7b">

Not sure if arm64 is related. 😂

**Comment by wingyplus** [comment]
<img width="1920" alt="Screenshot 2023-10-01 234644" src="https://github.com/dagger/dagger/assets/484530/4bf432a8-c1bf-40c5-abb5-41705db22ec0">

Windows 11 on x86_64 works well. Is that an Apple M1(or similar) issue?
