### ISSUE TITLE
State of CUE

### ISSUE THREAD

**Issue by codethief** [dagger/dagger#5669]
### What is the issue?

Hi there, I'm very new to Dagger, though have been following it from afar since [its announcement](https://dagger.io/blog/public-launch-announcement). Today I looked into again, and remembered that, originally, Dagger used to use CUE. Now, however, most (though not all) signs of CUE seem to be gone and these days Dagger provides SDKs for programming languages. What is the state of CUE then?

I've noticed that:

- The docs still seem to be in place, even though they seem to be missing from the navigation:
  - https://docs.dagger.io/sdk/cue/159741/how-it-works
  - https://github.com/dagger/dagger/tree/main/docs/current/sdk/cue

- The CUE SDK seems to be gone, however, with the [README](https://github.com/dagger/dagger/blob/main/sdk/cue/README.md) pointing to a dead link.

- There is no blog post documenting/announcing the shift away from CUE. The last blog post about CUE-related stuff was [this one](https://dagger.io/blog/dagger-vscode) and afterwards, blog posts announcing the Go/Python/Node SDKs followed.

- The [changelog](https://github.com/dagger/dagger/blob/main/CHANGELOG.md) doesn't go back far enough and doesn't say anything about CUE.

- I've briefly looked for Github issues with background information but couldn't find anything.

All in all, I'd be very interested in hearing what's happened! Is CUE still being used the hood? Is there going to be a comeback? If not, what were the reasons for moving away? Either way, I think the docs & repository might need an update. :)

**Comment by morlay** [comment]
I‘m used using dagger with cuelang.

Since dagger-cue not active, I start the project https://github.com/octohelm/wagon instead, 
which based on dagger-go.

Most features could be implemented,
Now just for my projects, and not have enough time to make this project fully documented.

**Comment by PierreR** [comment]
Wow, such a shame `CUE` is gone. Is there links/resources that explain the rational ? I was expecting CUE to stay as a first citizen SDK but it looks like it is not even the case anymore.

**Comment by ramnes** [comment]
<img width="933" alt="image" src="https://github.com/dagger/dagger/assets/835072/b1cdffda-fa26-4056-97b3-b6a07786e0eb">
https://discord.com/channels/707636530424053791/1145848207352533123/1155915806757093379

**Comment by helderco** [comment]
Answered in blog post: [Ending Support for the Dagger CUE SDK](https://dagger.io/blog/ending-cue-support).
