### ISSUE TITLE
[dagger.Entries] Consider support recursive list and mark type of directories or files

### ISSUE THREAD

**Issue by morlay** [dagger/dagger#5685]
### What are you trying to do?

`dagger.Entries` return filenames with single level

For example, rootfs like
```
home/
   nonroot/
      .bashrc
```

`entries(path: "/") => ["home"]`

If we want get full files in this rootfs, we have to recursive call `entries` for this.
Then without mark of the entries, we don't which one is the directory for doing recursive ([realworld example](https://github.com/octohelm/wagon/blob/main/pkg/engine/plan/task/fs_entries.go#L53-L85))

So consider support 

### return mode of entries 

`entries(path: "/", withMode: true) =>  ["home drwxr-xr-x"]`

### recursive list

`entries(path: "/", depth: 2) =>  ["home", "home/nonroot"]` 

or glob patterns: 

`entries(path: "/", include: ["*", "*/*"]) =>  ["home", "home/nonroot"]`

### Why is this important to you?

Since use [distroless](https://github.com/GoogleContainerTools/distroless)
We may not have any shell in container. 
and mount to some workspace with shell is not simple enough.

When the feature landed, we could be eazy to walk container fs. like [dive](https://github.com/wagoodman/dive) did.

A exmaple in container results testing
https://github.com/innoai-tech/runtime/blob/main/cuepkg/distroless/tests/test.cue#L16-L91

### How are you currently working around this?

Hacked implement: 
https://github.com/octohelm/wagon/blob/main/pkg/engine/plan/task/fs_entries.go#L53-L85

Use case:
https://github.com/innoai-tech/runtime/blob/main/cuepkg/distroless/tests/test.cue#L16-L91

**Comment by TomChv** [comment]
@morlay I added a PR that should fix most of your issues (except the mode) but I think a call to `ls` would be more appropriate in that case.

**Comment by TomChv** [comment]
@morlay I'm closing this issue since we merged #5824, feel free to reopen it if we need to fix something else related to this topic :D
