### ISSUE TITLE
🐞 Unexpected error when secret doesn't exist

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#5727]
### What is the issue?

Given this example: 

```go
func main() {
    ctx := context.Background()

    client, err := dagger.Connect(ctx, dagger.WithLogOutput(os.Stderr))
    if err != nil {
        panic(err)
    }
    _, err = client.Container().From("alpine").WithMountedSecret("/secret/foo", client.Secret("foosecret")).
        WithExec([]string{"cat", "/secret/foo"}).
        Sync(ctx)

    fmt.Println(err)
}
```

I'd have expected to get a `secret not found` error.

### Log output

`foosecret: illegal base64 data at input byte 8`

### Steps to reproduce

Run the pipeline in the description

### SDK version

v0.8.4

### OS version

Debian 12

**Comment by TomChv** [comment]
The issue actually come from this function: https://github.com/dagger/dagger/blob/b02479014c688ab030767e68c980def0076c0375/core/schema/secret.go#L49

But if we just return `secret not found`, we may miss other kind of error, how can we check that? Should I check in the buildkit storage manually if the secret exist? It's pretty verbose but that could work

**Comment by marcosnils** [comment]
> we may miss other kind of error,

other kind of error where particularly?

**Comment by TomChv** [comment]
> other kind of error where particularly?

I don't know, but this error is triggered by the call to `client.Secret("foosecret")`

> I think this issue is happening because we're doing the base64 encoding to support binary secrets that we include sometime ago. I think what it should happen is practice is that once the ExecOp tries to mount a secret that doesn't exit, we should be getting the secret not found error buildkit is raising.

I agrees but I'm not sure the ExecOp is actually executed, since `Secret` is executed before that, I can check if my theory is true with an example without Exec

**Comment by marcosnils** [comment]
> I think this is more likely to do with decoding the `SecretID` which is indeed encoded in base64 (all IDs are).

thx Helder :muscle:

**Comment by TomChv** [comment]
I find out that `client.Secret` is actually broken, the following example fails too

```
	ctx := context.Background()

	client, err := dagger.Connect(ctx, dagger.WithLogOutput(os.Stderr))
	if err != nil {
		panic(err)
	}
	_ = client.SetSecret("foo", "baz")

	_, err = client.Container().From("alpine").WithMountedSecret("/secret/bar", client.Secret("foo")).
		WithExec([]string{"cat", "/secret/bar"}).
		Sync(ctx)

	fmt.Println(err)
```

But it's not supposed too since `foo` should exist

**Comment by TomChv** [comment]
I'm closing this issue since the error isn't due to a lack of secret, we can reopen it there's a bug related but I didn't find one during my research, if you send the right ID, it works well 🚀
