### ISSUE TITLE
Make it easier to run functions

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#5728]
## Problem

So far Zenith focused on two modes of usage:

1) "Easy mode": run a limited set of functions from the CLI
2) "Power mode": run any functions with unlimited power, from your own functions written with an SDK

We're getting feedback that there is interest in a hybrid: unlimited function execution, without having to go all the way, choose an SDK, setup your own configuration, and write your own functions.

## Solution

Possible solutions include:

* Make it easy to run the GraphQL playground against the API
* Add a command to the CLI that runs an interactive language interpreter with environment codegen preloaded (kind of like the cloud playground with native language support, but in the command-line)
* A simple web UI :) Possibly packaged in an IDE extension? 0:-) cc @TomChv @grouville

**Comment by TomChv** [comment]
> A simple web UI :) Possibly packaged in an IDE extension? 0:-) cc @TomChv @grouville

That's a great idea! I'm trying to figure out how we could technically get to that.
What we basically need to do is:
- Introspect functions (as Zenith do) to retrieve the GQL schema and display it into a WebUI
- A call to action to run on of these function from the Web UI, with forms to fill parameters
- An integration with dagger cloud maybe? To follow the progress of your run? We could handle that by embedding dagger cloud?

I wonder how we can embed this web-ui . Should it be a new dagger command in the CLI like `dagger ui`?
What is the process to power up this UI? Should we deploy it through a docker image that we pull and bind the user workdir?  

If we can do a web UI, the IDE extension will be more or less the same on the principle, the difference will be on the user experience.

**Comment by shykes** [comment]
This issue is pretty generic. I will close it in favor of more specific proposals:

- #5774 
- A possible web UI: no issue at the moment, will wait for someone else to request it. We're busy enough as it is.
