### ISSUE TITLE
Docs: NodeJS error in Quickstart docs

### ISSUE THREAD

**Issue by 13tm3nt3r** [dagger/dagger#5771]
Looking into the Quickstart guide, using **NodeJS,** for example in the [test part](https://docs.dagger.io/quickstart/947391/test), the exclude part in the code snippet was not working, because the folders I wanted to exclude were still being uploaded.
I went to other pages such as [this `Work with the Host Filesystem` guide](https://docs.dagger.io/421437/work-with-host-filesystem/#:~:text=.directory(%22.%22%2C%20%7B%20include%3A%20%5B%22*.*%22%5D%2C%20exclude%3A%20%5B%22*.rar%22%5D%20%7D)) and I found a difference between both documentations.
While in the **Quickstart** part, the `.directory` was like this:
`.withDirectory('/src', client.host().directory('.'), { exclude: ["node_modules/", "ci/"] })`

On the other page, it was like this:
`.directory(".", { include: ["*.*"], exclude: ["*.rar"] })`

Also, when looking in VSCode the declaration of the Host directory function, I saw that the `.directory` function includes the `include` and `exclude` arguments, so the last parenthesis of `.directory('.')` should be at the end of the `exclude` in the Quickstart example and the comma should separate the arguments of the `directory` function.
So I tried it as in the second example and my exclude part finally worked. Therefore, I suggest to change the snippets in the following parts of the Quickstart guide:

- [Test the application](https://docs.dagger.io/quickstart/947391/test/)
- [Build the application](https://docs.dagger.io/quickstart/349011/build)
- [Perform a multi-stage build](https://docs.dagger.io/quickstart/472910/build-multi)
- [Use caching](https://docs.dagger.io/quickstart/635927/caching)

<br/>
<br/>
Hope this helps!

**Comment by TomChv** [comment]
@vikram-dagger Do you think you have some time to fix these inconsistencies?

**Comment by vikram-dagger** [comment]
@TomChv the current quickstart code for the test example https://docs.dagger.io/quickstart/947391/test is

```
const source = client
      .container()
      .from("node:16-slim")
      .withDirectory("/src", client.host().directory("."), {
        exclude: ["node_modules/", "ci/"],
      })
```

The proposal above suggests changing it to

```
const source = client
      .container()
      .from("node:16-slim")
      .withDirectory("/src", client.host().directory(".", { exclude: ["node_modules/", "ci/"] }) )
``` 

On checking the Node reference for withDirectory() at https://docs.dagger.io/current/sdk/nodejs/reference/classes/api_client_gen.Container#withdirectory, it looks like the first form is correct, as the third parameter is expected as an object with include/exclude values.

Can you check and let me know your thoughts? Note that we have followed the same structure for the Go and Python examples as well, so this change if required will need to be reflected in code snippets for other SDKs as well.

I'm also interested to hear from @marcosnils and @slumbering if there is a difference between the above two approaches and which one is preferred.

**Comment by vikram-dagger** [comment]
@TomChv ignore previous, it looks like there is already an open PR for this fix https://github.com/dagger/dagger/pull/5854/

**Comment by slumbering** [comment]
Closing this issue since #5854 has been merged.
@vikram-dagger feel free to reopen it, if we still have some issues. Thanks
