### ISSUE TITLE
Make registry for engine image configurable 

### ISSUE THREAD

**Issue by levlaz** [dagger/dagger#5775]
When the Dagger CLI starts it creates a default runner by pulling the latest version of the engine image from `registry.dagger.io`. Right now this registry URL is hard coded: 

https://github.com/dagger/dagger/blob/e5feaea7f1d6eb01d834e83b180fc3daed3463ea/engine/version.go#L12

In some corporate environments there are limitations to which registries are allowed. This makes it difficult to use the CLI because it's unable to download the image that is required in order to get the engine to run. 

Today you can work around this by starting your own container and using the `_EXPERIMENTAL_DAGGER_RUNNER_HOST` variable as described in the [operator manual](https://github.com/dagger/dagger/blob/main/core/docs/d7yxc-operator_manual.md#connection-interface).

This approach makes sense if you need to make changes to the base image, but in the case where you just need to pull the image from a different registry it would be much simpler if we could make this configurable.

**Comment by TomChv** [comment]
@vito @sipsma @aluzzardi Sounds like something we can handle with an environment variable, what's your thought on it?

**Comment by sipsma** [comment]
@levlaz @TomChv This isn't in the operator manual (it should be, I'll update it), but you can set `_EXPERIMENTAL_DAGGER_RUNNER_HOST=docker-image://<container image reference>` and get this behavior.

**Comment by jedevc** [comment]
I think @levlaz's ask here is for a new env variable? Something like `_EXPERIMENTAL_DAGGER_RUNNER_IMAGE` that could be used to modify the value of `EngineImageRepo` - you wouldn't need to start the container manually, you'd just point it to a different image to pull.

In that case, this wouldn't necessarily be fixed by #5890.

**Comment by TomChv** [comment]
Amazing!

**Comment by TomChv** [comment]
Closed by #5890
