### ISSUE TITLE
Improve help string for `dagger query --doc`

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#5781]
<img width="950" alt="image" src="https://github.com/dagger/dagger/assets/3187222/ddda0e0d-8d3c-4f4b-b83d-1ed5228557ab">

https://discord.com/channels/707636530424053791/1120503349599543376/1151655404883951626

**Comment by TomChv** [comment]
So as far as I understand, the idea is to update the doc in the CLI to something more relevant? Am I missing anything @jpadams ?

**Comment by blaisep** [comment]
@TomChv IMHO, it's not just a string, it's a filename:
```
--doc <filename> [query_name]   Use named queries from a file
```

**Comment by helderco** [comment]
This is the current description:
```
      --doc string        Read query from file (defaults to reading from stdin)
```

It doesn't have to have "named queries", but if it does, the command's description explains:
<pre>
Can optionally provide the GraphQL <strong>operation name</strong> if there are multiple
queries in the document.

USAGE
  dagger query [options] [<strong>operation</strong>]
</pre>

So I'm closing this as completed.
