### ISSUE TITLE
🖐️ Can I use dagger in generic cli tooling that is not just for CI/CD?

### ISSUE THREAD

**Issue by red8888** [dagger/dagger#5784]
### What happened? What did you expect to happen?

Perhaps a dumb question, but I didn't find anything regarding this specific use case in the docs and I want to confirm this is possible and doesn't have any caveats.

My goal is to write an internal cli tool. The tool will run locally on users machines for interactive use and will also be containerized to run in automation- so it can run in k8s cron jobs and other places as a container.

The internal cli will wrap other shell commands like gcloud, aws, helm, kubectl, etc. But it will run the commands inside containers. So when executing gcloud it will programmatically execute the gcloud command with the official google gcloud container image and capture the output- same with the other tools. And like I said the tool itself will be containerized.

Now what I could do is used the official docker dind image and have the cli tool use the docker API to programmatically run all these commands in containers.

But could I use dagger instead? It seems more feature rich. Could I install my tool in the official dagger container image and use the dagger SDK to run these commands in individual containers programmatically?

Maybe this is obvious, but I'm wondering if there is any reason why I can't use dagger not just for CI/CD but for generic cli tooling like I'm describing as well?

Also, I saw this thread: https://github.com/dagger/dagger/issues/4921. Its really important to be able to check the exit code for a wrapper like this to determine if the command succeeded or failed. shell tools frequently write log info to stderr even if the command didn't actually fail. Is it impossible to see the exit code of a command executed with dagger? If so that would be a deal breaker for this use case.

**Comment by d3rp3tt3** [comment]
Hi @red8888, your use case sounds similar to some of the things that are in development with Project Zenith. Come join the community Discord: https://discord.gg/dagger-io. Some members of the community have begun to build Dagger modules, which aims to create a great DX that is CLI-centric.

These are two areas in Discord that can help.
* [Project Zenith room](https://discord.com/channels/707636530424053791/1120503349599543376)
* [Help room](https://discord.com/channels/707636530424053791/1030538312508776540)

**Comment by red8888** [comment]
I found this video about zenith: https://www.youtube.com/watch?v=Pt_AsbQilAM

**Comment by shykes** [comment]
@red8888 yes your use case seems like a good fit for Dagger. We emphasize the CI use case but really, anything that might be usually done by an “artisanal script” or makefile in a software project can probably be done by Dagger. The practical limitation is that it has to fit in a container but that seems to be your intended design anyway.

Project Zenith is relevant but not a requirement:

1. Yes as you mentioned, Zenith adds cross-language reusable components. This will make it easier to reuse work already done in the Dagger community for your own project; and also to reuse your own work for the next project. It will also make it easier for the end users of your CLI to customize and integrate it, instead of wrapping it in another layer of artisanal scripts.

2. Zenith also makes it easier to call these modules as an API. So in addition to wrapping them in your custom CLI, you and your users can at anytime access the underlying API for debugging, customization, integrations etc.

I hope this helps!

**Comment by red8888** [comment]
@shykes thanks, question about this "The practical limitation is that it has to fit in a container"

What I have done in the past is have a containerized cli tool that wraps shell commands (gcloud, helm, etc) and installed all those tools in the cli tools container image. The tool could be run anywhere like in a k8s cron job for example- instead of running a loose script. But it required a big container image with all the tools installed.

I was expecting to be able to run my cli tool with the dagger official container image to keep it minimal but then run commands like gcloud with the official gcloud container with dagger. Is there a limitation with this? Would I be able to run it on k8s or would there be an issue with privileged mode? Is it enough to just configure the pods security context? Does k8s need to be configured to support buildkit or anything? Thanks!

**Comment by TomChv** [comment]
> would there be an issue with privileged mode?

We do not support running Dagger Engine without `--privileged`, so I think yeah, it can create issues.

> Does k8s need to be configured to support buildkit or anything?

We wrote a guide few weeks ago that explain how to run dagger with Kubernetes: https://docs.dagger.io/194031/kubernetes

>  I was expecting to be able to run my cli tool with the dagger official container image to keep it minimal but then run commands like gcloud with the official gcloud container with dagger. Is there a limitation with this?

As far as I know, this is the right way to do 🚀  I'm not sure there's any limitation, you can basically pull anything to run what you need.

**Comment by red8888** [comment]
@TomChv The guide you linked to is for building out a whole CI/CD platform on k8s, I merely want to run my dagger based tool in a k8s pod like any other application- the tool's container image would just be based off the official dagger image.

Should that just work? GKE for example supports privileged containers so I don't think that will be an issue there I should be able to just do this:

```
  containers:
  - name: mycli
    securityContext:
            privileged: true
```

But does it also need access to buildkit on the host nodes or anything? I'm running dagger in a pod but that pod is going to need to pull and run other containers. How does that work? 

There is also this github issue which seems related: https://github.com/dagger/dagger/issues/3140

Like I said I'm just building an all purpose cli tool with the dagger SDK that I want to run containerized wherever I need it. Not using it for CI/CD pipelines just for all purpose admin tasks, maybe in k8s cronjobs, etc.

**Comment by red8888** [comment]
@jedevc Awesome thanks for clearing that up! I'm gonna close this because I got my questions answered.
