### ISSUE TITLE
🐞 secrets scrubbing implementation causes excessive log output latency

### ISSUE THREAD

**Issue by postamar** [dagger/dagger#5791]
### What is the issue?

# Context

We have a dagger pipeline which, at some point, [mounts secrets](https://github.com/airbytehq/airbyte/blob/327d3c9ae8e14b28bf2bdf7528b22f86f510d629/airbyte-ci/connectors/pipelines/pipelines/actions/environments.py#L1053) to a container which is then runs [integration tests](https://github.com/airbytehq/airbyte/blob/327d3c9ae8e14b28bf2bdf7528b22f86f510d629/airbyte-ci/connectors/pipelines/pipelines/gradle.py#L157) by with_exec'ing a task in gradle.

We are just as bad computer programmers as anyone and sometimes we introduce regressions which cause our integration tests to hang. In our particular case, the bug we introduced was that we tried to connect a jdbc driver to a nonexistent host and we'd hit some absurdly large timeout in our code.

What's unexpected, and why I'm filing an issue right now, is that dagger would be completely silent about the output of this `with_exec` step until it eventually failed. 

# The problem

I eventually found that dagger's secrets scrubbing implementation is to blame. In our case, we mount about 20 secrets files, which while a lot, doesn't seem that crazy. I read dagger's code [1] and it appears that if there's a nonzero number of secrets mounted (env vars or files) the output gets piped through `replace.Chain` which chains a bunch of `Transformer` instances from go's transform module [2]. There's one instance per secret and each appears to wrap a reader with a hardcoded buffer of 4kB [3].

In our case, our gradle process was simply not chatty enough to overcome this buffering and so it seemed like it didn't do anything. We're on an old version of dagger but the problem seems still present in the `main` branch from what I can tell.

# My expectations as a user

The need to scrub secrets is not in question. However, `transform` appears to be written in a way that biases throughput over latency, when in our case exactly the opposite is desirable: when scrubbing secrets my expectation is that the output becomes visible to me _as soon as possible_. I don't want to wait for some arbitrary unconfigurable buffer to fill up and I certainly don't want that behaviour to be `O(n)` to the number of secrets mounted.

I say as soon as possible but that's not strictly speaking true, it's not like each rune has to pass through as soon as it's determined that it's not part of a prefix of one of the secrets. This being textual output, I'd be fine if it was each _line_ that gets passed through ASAP. I'm guessing this would also be undoubtedly less complicated to implement on your end and I'm also guessing that most secrets are not multiline (or if they are, it's only a handful of lines). 

tl;dr: no need to go crazy here, but I'll be happy with reasonable and predictable behaviour.

# Repro

I didn't look into how dagger is tested but the desired behaviour of the return value of `NewSecretScrubReader` seems adequately unit-testable from my naive standpoint:
1. mock mounting 1, 10 and 100 secrets in each test case;
2. kick off a goroutine with an `io.Reader` which mocks a `with_exec`'ed process' `stdout`;
3. have that `io.Reader` serve a fixed number of bytes and then block on a channel, then serve a bunch more bytes, then block again;
4. concurrently, expect the `io.Reader` returned by `NewSecretScrubReader` to read an expected subset of those bytes, then unblock the channel, then read another expected subset of bytes, then unblock again.

# Notes

Dear dagger maintainers: I hope you're not finding me overprescriptive here or feel that I'm babying you. Far from it! I'm being deliberately wordy because I'm reasonably hopeful that this issue is quite cheap to fix so I'm provide as much info as I can to that aim. On our end, it sure caused a lot of head-scratching. 

This is only an issue in an interactive setting: developing locally, or looking at dagger.cloud, which is probably why it went unnoticed (I didn't find any similar issue, though I only did a quick search).

# References

[1] https://github.com/dagger/dagger/blob/v0.6.4/cmd/shim/main.go#L294
[2] https://golang.org/x/text/transform
[3] https://cs.opensource.google/go/x/text/+/refs/tags/v0.13.0:transform/transform.go;l=130

### SDK version

0.6.4

### OS version

irrelevant, I believe, but macOS and some unremarkable linux distro

**Comment by TomChv** [comment]
@sipsma @vito @jedevc This issue looks pretty tricky to repro, do any of you has more context about secret performances?

I can work on a repro case as explained by @postamar to help it moving forward, I'm not sure I can fix this issue myself though.

**Comment by TomChv** [comment]
@jedevc @postamar I opened a PR with a repro case, I don't know if this will help because I'm not sure I've actually hit the issue but I followed the protocol

> I didn't look into how dagger is tested but the desired behaviour of the return value of NewSecretScrubReader seems adequately unit-testable from my naive standpoint:
>
> - mock mounting 1, 10 and 100 secrets in each test case;
> -kick off a goroutine with an io.Reader which mocks a with_exec'ed process' stdout;
> - have that io.Reader serve a fixed number of bytes and then block on a channel, then serve a bunch more bytes, then block again;
> - concurrently, expect the io.Reader returned by NewSecretScrubReader to read an expected subset of those bytes, then unblock the channel, then read another expected subset of bytes, then unblock again.

The PR: https://github.com/dagger/dagger/pull/6012

**Comment by TomChv** [comment]
@postamar Just a quick summary of what we did and what are the next steps planned to move forward this issue.

**Summary**

@jedevc wrote an approach on how we could fix that issue with a different implementation. (See https://github.com/dagger/dagger/issues/5791#issuecomment-1775203225)

I also made a repro case on #6012 to see the issue, I couldn't actually see any latency except when I mount `1500` secrets. But I may missed something.

**Next steps**

- Could you have a look at the repro (#6012) and let me know if it does what you had in mind. I also posted a comment https://github.com/dagger/dagger/pull/6012#discussion_r1375232742 that may change the actual behaviour of the repro.
- Could you check on https://github.com/dagger/dagger/issues/5791#issuecomment-1775203225 and confirm if that can fix the issue?

Once these 2 steps are done, we can start the implementation and compare the result between our old implement and the new one to see if we see any differences of latency.

**Comment by postamar** [comment]
Hmm, the latency should be apparent with less secrets than that. I have a high-level repro for you in the form of a short python script:
```
import sys

import anyio
import dagger

BASH_SCRIPT= """
while true
do
  echo hello
  sleep 1
done
"""

async def main():
    config = dagger.Config(log_output=sys.stdout)

    async with dagger.Connection(config) as client:
        container = client.container().from_("ubuntu:latest")
        for i in range(int(sys.argv[1])):
            secret = client.set_secret(f"s33kr3t_{i}", "shhh")
            container = await container.with_secret_variable(f"S33KR3T_{i}", secret)
        await container.with_exec(["sh", "-c", BASH_SCRIPT])


anyio.run(main)
```

When running this using dagger 0.6.4 with `dagger run python daggerizer.py 0` I get the expected behaviour where 'hello\n' gets printed every second. Replace the 0 argument with 1 and I see 'lo/nhel` instead, and replace it with 20 and it takes half a minute for anything to come on the screen and then in stalls again and after a Ctrl+C all the missing "hello"s all show up.
