### ISSUE TITLE
✨ Change `.withEntrypoint` to accept the `nil` case (in Typescript)

### ISSUE THREAD

**Issue by mckinnsb** [dagger/dagger#5803]
### What are you trying to do?

Started from discord conversation here:

https://discord.com/channels/707636530424053791/1149095919330009098/1149095919330009098

I'd like to be able to "unset" the entrypoint by passing `nil` to `.withEntrypoint`. Currently, to unset the entrypoint, you need to pass an empty array. While this makes sense after thinking about it for a while, this isn't intuitive for the first time user.

### Why is this important to you?

You frequently have to unset/change entrypoints when working with an image in a different context; for example, testing a built image usually requires unsettling the entrypoint and changing it such that you can run test commands against the build artifact.

### How are you currently working around this?

Currently, you can pass an empty array. However, passing `nil` would be a lot more intuitive.

**Comment by helderco** [comment]
I think it's better to use `withoutEntrypoint` for this:
- #3284

**Comment by TomChv** [comment]
@mckinnsb I'm closing this issue since `withoutEntrypoint` should fix your issue, feel free to reopen it if I missed something :D
