### ISSUE TITLE
✨ Attach stdin/stdout to Container with Node SDK

### ISSUE THREAD

**Issue by pzmarzly** [dagger/dagger#5820]
### What are you trying to do?

I want to drop into a shell inside a dagger container, so I can debug a pipeline and even have a dagger-defined development environment (so that developers would only need docker + dagger to develop an app).

For Docker, there is https://github.com/ktock/buildg.

I would imagine being able to write:

```js
await appContainer
      .withServiceBinding("redis-server", redis.srv)
      .withServiceBinding("postgres-server", postgres.srv)
      .withWorkdir("/app")
      .withEnvVariable("CACHE_BUSTER", Date.now().toString())
      .withExec(["bash"])
      .stdout({ attach: true }); // <- NEW, passes stdin and tty from dagger CLI
```

Or at least:

```js
await appContainer
      .withServiceBinding("redis-server", redis.srv)
      .withServiceBinding("postgres-server", postgres.srv)
      .withWorkdir("/app")
      .withEnvVariable("CACHE_BUSTER", Date.now().toString())
      .withExec(["bash"])
      .waitForDebugger(); // <- NEW, pauses the pipeline and prints an ID
```

```bash
dagger debugger --attach $SOME_ID
```

### How are you currently working around this?

I replace `["bash"]` with `["sleep", "86400"]` and run the pipeline.

It hangs, so then from a second terminal I run:

```console
$ lima bash -c 'sudo nsenter -a -t $(pidof -s sleep) bash'
root@buildkitsandbox:/# # We are in!
root@buildkitsandbox:/# cat /etc/hosts 
127.0.0.1       localhost buildkitsandbox
::1     localhost ip6-localhost ip6-loopback
10.87.0.144     redis-server
10.87.0.143     postgres-server
```

I'm using `lima bash -c '<CMD>'` due to running on macOS, it just forwards the command over SSH to the Linux VM.

I keep this function in my macOS `~/.zshrc`:

```bash
dagger-shell() {
  if [ -z "$1" ]; then
    # If no command was provided, just spawn bash
    dagger-shell bash
    return
  fi

  lima bash -ic -- \
    'sudo nsenter -at $(pidof sleep) -- bash -ic -- "$*" dagger-shell-inner' \
    dagger-shell-outer \
    $@
}
```

And the same function in my Linux `~/.bashrc`, just without `lima`.

Then I can run:

```console
$ dagger-shell cat /etc/hosts
127.0.0.1       localhost buildkitsandbox
::1     localhost ip6-localhost ip6-loopback
10.87.0.147     redis-server
10.87.0.148     postgres-server
```

**Comment by TomChv** [comment]
@vito I remember you mentioned that feature some days ago, do we have anything implemented that could do this job with our tty?

**Comment by TomChv** [comment]
@pzmarzly this feature will be supported with `dagger shell` once Zenith (our new version) is stable.

You can check on our Discord for some updates and try it to give us feedbacks: https://discord.com/channels/707636530424053791/1120503349599543376

**Comment by TomChv** [comment]
It's actually possible with the latest version of Dagger ([v0.9.0](https://github.com/dagger/dagger/releases/tag/v0.9.0)), I just tried it through a Zenith module and it's going great!

Here's a quick demo that I recorded to show you.

https://github.com/dagger/dagger/assets/61683879/c7cad0e4-8c32-4778-b0d6-a5162c751349


My repro code is available on [this repository](https://github.com/quartz-technology/daggerverse/tree/main/redis-shell):

```go
package main

type RedisShell struct{}

func (m *RedisShell) Cli() *Container {
	password := dag.SetSecret("redis-password", "foo123")

	redisCtr := dag.Redis().
		WithVersion("latest").
		WithPassword(password)

	server := redisCtr.Server()

	cli := redisCtr.Cli(server.AsService())

	return cli.Container()
}
```

I made a quick README to explain how to spawn a shell. It basically uses `dagger shell`, this command expect a container as input (produced by a zenith command) and will start a shell in it.

For your use case, you would need to create a Zenith module for your application and return a `Container` from a function.

For example in Go

```go
func (a *App) App() *Container {
   return appContainer
      .WithServiceBinding("redis-server", a.Redis.Srv)
      .WithServiceBinding("postgres-server", a.Rostgres.Srv)
      .WithWorkdir("/app")
      .WithEnvVariable("CACHE_BUSTER", Date.now().toString())
}
``` 

Then you could do `dagger shell app --entrypoint /bin/sh` to spawn a shell in your appContainer that can interact with redis and postgres if you installed the CLI in your app container.

⚠️ Dagger shell and Zenith are still experimental, but feel free to give it a try and open issues if you struggle on anything.

I hope this solve your problem, let me know if I can close this issue :D

**Comment by pzmarzly** [comment]
Wow, that looks awesome. I cannot try it out in my tests due to Node.js Zenith SDK not being available (at least this doc page https://docs.dagger.io/labs/project-zenith/#creating-your-first-module says so, and when I tried making `dagger.json` file by hand, it got stuck at resolving modules). But I will as soon as it's supported, thanks!

**Comment by TomChv** [comment]
> says so, and when I tried making dagger.json file by hand, it got stuck at resolving modules). But I will as soon as it's supported, thanks!

Yes you should use the CLI `dagger mod init ...` to kick of the `dagger.json`

We will supports other SDKs as soon as Go and Python are fully stable. I'll ping you on this issue when it's released.
Let me know if you want to keep it open or closed 😊

You can also check our progress on the specific [Zenith Discord channel](https://discord.com/channels/707636530424053791/1120503349599543376) or join our community call, I'm sure we'll do a demo when the Node SDK is ready 🚀
