### ISSUE TITLE
✨Add API to export the resolved commit hash of a GitRef

### ISSUE THREAD

**Issue by jpeach** [dagger/dagger#5834]
### What are you trying to do?

I have a build that pulls sources from a Git repository using the Git API. Internally Dagger resolves the branch or tag name to a commit hash:

```
223: git://github.com/my-org/sources.git#v1.1
223: [2.61s] c94c15a6ef1974b29877c8b99edf27708a3be78f	refs/heads/v1.1
223: git://github.com/my-org/sources.git#v1.1 DONE
```

It would be very helpful if there was a way to query commit has that Dagger resolved so that I can add it to the build metadata.

See also https://github.com/dagger/dagger/issues/5367

### Why is this important to you?

For QA and triage it's useful to know the exact version of the sources that were used to build an artifact. The Git commit hash is a good identifier for this, but there's no good way to get it in a Dagger build.

### How are you currently working around this?

I'm using the tag or branch name, but that's potentially ambiguous.

**Comment by TomChv** [comment]
I totally understand the use case of getting the digest of a pulled repository.

You can currently pull a specific `commit` (kind of a workaround but really hard to use).

@sipsma @vito @helderco After closing #5367 with #5410, do you think now dagger is ready to handle this capability?
