### ISSUE TITLE
Zenith: don't swallow module compilation errors in focused output

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#5861]
right now a compilation in user go code ends up being swallowed in the default output of `dagger mod sync`, you need to append `--progress=plain` to see the problem. We should make sure those errors show up by default even in focus mode.

**Comment by sipsma** [comment]
This maybe should expand in scope to any failure in general, not just compilation

**Comment by jedevc** [comment]
With changes to the TUI recently, I haven't hit this issue in ages (TUI output can still be difficult to parse, but doesn't fall under this issue anymore) :tada:
