### ISSUE TITLE
Zenith: fix dagger mod use to support multiple deps

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#5863]
`dagger mod use` only supports a single dependency even though we support multiple dependencies underneath the hood. Workaround right now is to manually edit dagger.json

**Comment by jedevc** [comment]
This should be fixed in [`8a00f68` (#5757)](https://github.com/dagger/dagger/pull/5757/commits/8a00f687011164399de10bbc215777bd92f1527a) by @vito, so closing this :tada:
