### ISSUE TITLE
Zenith: host directory access

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#5867]
Today, in zenith we have a small inconsistency in the way that host directory access works:

We can read the host's current directory:

```go
	dag.Host().Directory(".")
```

But we can't export to the host:

```go
	// this actually exports to the module container
	dir.Export(ctx, "build/")
```

I think there's two points here:

1. As we encourage users to modularise existing dagger code, I think this will be a small papercut since this changes from the previous way of doing things. Maybe it's just a docs-level change, or maybe we could consider making it clearer in code that calling `Export` in a module doesn't export to the host anymore.

2. It's also probably a security issue that any module (no matter how deep in the chain) can access the host (or perform other privileged operations, like publishing images) - maybe we should instead consider only allowing the top-level module (e.g. `dagger query` or `dagger call` to access the host, and then all modules have to take these as parameters, which would also make them more reusable).

**Comment by sipsma** [comment]
> We can read the host's current directory:

That call made in a Module will actually read from the module container, not the caller's host. The workdir of the module container is the directory of the module source code, so if you loaded the module from the host then you will see that directory from your host. However, it's just that directory synced into buildkit, you can't read anything from the host arbitrarily.

@jedevc Does that align with what you're seeing? If you saw behavior where you could read arbitrary files from the caller's host, then something is going wrong and we need to fix.

**Comment by jedevc** [comment]
Yup, this tracks. That makes a lot of sense - the security issue isn't a problem then, I was misunderstanding what's actually going on.

I still think there's a papercut to resolve here at some point though - the `Host` isn't the host, it's the module. Though I'm not entirely sure if there's a neat fix for that.

**Comment by jedevc** [comment]
Deduped against https://github.com/dagger/dagger/issues/6312, which is clearer.
