### ISSUE TITLE
Zenith: support module re-execution inside of dagger

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#5870]
One open question we've discussed previously is how modules should work when run directly on the host. Prior to Zenith, we've tried to encourage users to prefer `dagger run go run main.go` instead of directly calling `go run main.go` - better progress, etc. With the code-gen, it's kind of become essential to wrap everything.

Attempting to call without the `dagger run` wrapper today gives:

```
panic: DAGGER_SESSION_PORT is not set
```

Ideally, we'd be able to detect the case where a module is being run outside of dagger, and somehow re-execute it inside, by re-calling itself, maybe using the CLI.

Aside from allowing better integration with the native ecosystem, here's one main use case for where we might want to allow this - for tests, debugging, general IDE support, etc. For example, if we have a `_test.go` file, and we run a test inside that file using our IDE, we won't be running in dagger. So if we could somehow connect this into a running dagger instance so that the module can run with all the right dependencies and services, etc, then we would get these kind of integrations "for free", without needing tons of custom logic.

**Comment by helderco** [comment]
Not sure what you mean here. Can you clarify?

**Comment by jedevc** [comment]
I'll quote @sipsma from discord:

> We can update the code pretty easily if desired. The only thing I'd advocate for is to not support executing the module code directly on the host. I'm wondering if there could maybe be a way to detect that the code is running outside of dagger and then execute itself inside dagger, same as if directly invoked with the CLI.

As I read it, when running something of the form `go run main.go`, outside of dagger, we would somehow *magically* get this running inside of dagger, instead of just erroring out.

I'm not actually sure how feasible this is, but thought it might be interesting to continue the discussion in a more permanent place.
