### ISSUE TITLE
Zenith: `dagger mod use` causes a rollback on code compilation failure

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#5872]
This is a bit of a papercut when working with zenith modules. For example,

1. `dagger mod init` a new module
2. `dagger mod use` a module found in daggerverse
3. Add code to call a function from the module
4. `dagger mod use` to update that module to a new version
   - If the new version changes the function signature of the called function, then this step will fail, returning an error - additionally, any changes to the codegen will be reverted, so the user isn't easily able to see the error in their code editor.

Is it possible to not attempt to run the code after code-generation (since it's fairly plausible it won't compile)? Or if it's necessary, maybe we could put dagger into a conflict state - something like git merge conflict resolution.

**Comment by sipsma** [comment]
Fixed by https://github.com/dagger/dagger/pull/5964
