### ISSUE TITLE
Zenith: support pinning of moving references in dagger.json

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#5912]
After https://github.com/dagger/dagger/pull/5900, SDK module references are just assumed to be non-moving (e.g. a git digest rather than branch)

We should support those being moving references and automatically pinned on `dagger mod init/sync`, but with some additional ability to upgrade them (`dagger mod update-sdk` as a strawman example).

---

Additionally, it would be great to move as much of the functionality needed here to be in the core API, so that it's reusable across SDKs and other dagger UX frontends (e.g. web interface, alternative CLIs, etc.).

This should likely include some better integration of the newly added `moduleConfig` API into the wider API (possible that's out of scope and better for a separate issue, can be made if needed once this issue is tackled): https://github.com/dagger/dagger/pull/5900#discussion_r1362367581

Some nuances noted [here](https://github.com/dagger/dagger/pull/5900#discussion_r1362322800) by @vito:
> There's a lot of nuance hidden in the resolution of refs though so it might take some time to fully bikeshed it; definitely won't block this PR on all that.

> For example it's tempting to think it's as simple as this:

> ```graphql
> extend type Query {
>   moduleFromRef(ref: String!): Module!
> }
> ```

> ...but we'll also want to be able to resolve moving refs to stable refs and know which commit/version they resolved to, and likely want to support loading config from a ref, and support getting the source code + sub path, etc. etc.

**Comment by jedevc** [comment]
Think this is done through #8587. Closing! :tada:
