### ISSUE TITLE
🐞github and dl.dagger.io binary releases don't match for 0.9.0

### ISSUE THREAD

**Issue by kjuulh** [dagger/dagger#5944]
### What is the issue?

Github release and dl.dagger.io releases don't match.

github releases
```bash
❯ shasum -a 256 dagger_v0.9.0_linux_amd64.tar.gz
86171d7a703c3f74b17f4e5977ec26d909b2e101106e544675ccd923f5eb4e8a  dagger_v0.9.0_linux_amd64.tar.gz
```

dl.dagger.io
```bash
❯ shasum -a 256 dagger_v0.9.0_linux_amd64.tar.gz
f85a19488ed4e6a0251ca047f5ab1d99c8242b38537a42ac8b9876f6bb7172ca  dagger_v0.9.0_linux_amd64.tar.gz
```

the checksum matches the github release. But causes conflict in at least rust sdk, and the release archive from dl.dagger.io (which I think is still the approach?

### SDK version

0.9.0

### OS version

linux amd64

**Comment by kjuulh** [comment]
This looks to be a cloudfront issue, as it may either change, or store a previous version of said artifact

**Comment by gerhard** [comment]
Thank you @kjuulh for opening this, I just fixed it, everything should be working as expected now.

We rolled out a hot patch for the Engine image & ended up in an inconsistent state. FWIW: https://github.com/dagger/dagger/actions/runs/6593588282/job/17916282638

Much appreciated 🙌
