### ISSUE TITLE
🐞 `dagger call -m <git-module>` fails if remote module contains dependencies with local path

### ISSUE THREAD

**Issue by aweris** [dagger/dagger#5953]
### What is the issue?

When we call a module with local dependency using `git-ref`,  cli isn't able to find dependencies. 

`dagger.json` for following error log https://github.com/aweris/gale/blob/0fcf43c126b03fc4296f05970328aaca085c18af/daggerverse/gale/dagger.json#L1-L9

### Log output

```shell
dagger call --mod github.com/aweris/gale/daggerverse/gale@0fcf43c126b03fc4296f05970328aaca085c18af
✘ build "dagger call" ERROR [4.15s]
├ [4.15s] loading module
✘ asModule ERROR [0.00s]
• Engine: 61b34bf9d33e (version v0.9.0)
⧗ 5.44s ✔ 27 ✘ 2
Error: failed to get loaded module ID: input:1: git.commit.tree.directory.asModule failed to create module from config `.::`: failed to get config file: lstat dagger.json: no such file or directory
```

### Steps to reproduce

- create a module with has a dependency on the local path.
- push module to repository 
- make a `dagger call -m <git-ref>`

### SDK version

Dagger CLI v0.9.0

### OS version

macOS 14.0

**Comment by gerhard** [comment]
WDYT @helderco?

**Comment by sipsma** [comment]
Can repro, thanks for reporting @aweris! Will work on fix quick
