### ISSUE TITLE
✨ AllowToFail in ContainerWithExecOpts

### ISSUE THREAD

**Issue by schlapzz** [dagger/dagger#5981]
### What are you trying to do?

In CI there are many jobs where you need to decide based on there return code  of a command (ok / not ok) how to proceed.

Simple example, upload the artefact if it is not already there If it exists, skip upload. 

The current workaround is as described in your docs
https://docs.dagger.io/cookbook#continue-using-container-after-command-execution-fails

Of course, the solution is working. But I have often the case that I want decide the further based on the exit code, and the code gets polluted by writing/reading the exit code into/from files. In view of a better DX it would be great if we can move this into Dagger and hide it from the developer.

For example something like that

```go
_, err := c.WithExec([]string{"curl -f https://example.com/file/v222"}, ContainerWithExecOpts{
		AllowToFail: true,
	})

if err != nil && !errors.Is(err, dagger.ExecNonZero){
  return err
}
``` 

### Why is this important to you?

* Improve the DX
* Avoid boilerplate code

### How are you currently working around this?

The current workaround is as described in your docs
https://docs.dagger.io/cookbook#continue-using-container-after-command-execution-fails

**Comment by marcosnils** [comment]
> Of course, the solution is working. But I have often the case that I want decide the further based on the exit code, and the code gets polluted by writing/reading the exit code into/from files. 

this is already the case if you want to handle the exit code yourself. This guide (https://docs.dagger.io/cookbook#continue-using-container-after-command-execution-fails) is mostly for pipelines where some command "always" return a status code != 0 and you still need your pipeline to continue. 

Here's an example on how to handle status codes: 

```go
func main() {
	ctx := context.Background()
	client, err := dagger.Connect(ctx, dagger.WithLogOutput(os.Stderr))
	if err != nil {
		panic(err)
	}
	defer client.Close()

	_, err = client.Pipeline("test").
		Container().
		From("alpine").
		WithExec([]string{"sh", "-c", "exit 20"}).Sync(ctx)

	var execErr *dagger.ExecError
	if errors.As(err, &execErr) && execErr.ExitCode == 20 {
		fmt.Println("failed with 20")
	}
}

```

**Comment by helderco** [comment]
> ref: #5539

That's also in the cookbook: [Handle exit code and unexpected errors](https://docs.dagger.io/cookbook/#handle-exit-code-and-unexpected-errors).

**Comment by schlapzz** [comment]
This is what I need. Close the issue

**Comment by jedevc** [comment]
I'm gonna re-open this one, since I think we can do better here - the cookbook suggestion is fine as a workaround, but I think an option like suggested originally would be good.

It's also not impossible to do - buildkit preserves the failed result for us in `ExecError`: https://github.com/moby/buildkit/blob/db3aaa3cffb08ddc6707a5c7591c22186b244dfc/solver/llbsolver/errdefs/exec.go#L11-L17. We'd just need to grab the output `Mounts` for this, and use those instead of our normal outputs.

This might require a bit of upstream tinkering, but should be possible without it (I think).
