### ISSUE TITLE
Zenith: allow private fields in types

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#5991]
Creating an issue based on @shykes's comment here: https://discord.com/channels/707636530424053791/1120503349599543376/1166880734741549176

Today, an example type in Go might look something like:

```go
type X struct {
     Foo string `json:"foo"`
}
```

In this example, `Foo` is exported and persisted between multiple calls (since each function call is a separate execution of the go binary) as well as being queriable by the user / calling module.

However, a relatively normal use case would be to want only that first property - a private field `Foo`, accessible and modifiable by the module, but inaccessible to the calling code.

There are two main parts of this:
- How should we mark a field as private at the API level?
  - We could have a `WithPrivate` call for fields, similar to `WithOptional` for function parameters.
  - This would mark the field as private, so we would always serialize/deserialize it, but would not generate it as part of the graphql schema for the module.
 
- How should we indicate that the field is private in Go/Python/etc?
  - For Go, ideally we could use unexported fields as private - since `dagger.gen.go` is in the same package as `main.go`, then this wouldn't be a problem.

    However, a couple caveats: this would be the first thing (as far as I'm aware) to require access to private fields in `main.go` from `dagger.gen.go`, so it would be difficult to split this into a separate package later (if we wanted to prevent the user from accessing private parts of `dagger.gen.go`). It would still be possible though! We'd just need the code that accessed the parts of `main.go` to be auto-generated into the same package (and extract the internals into a separate package).

    Secondly, we'd then have no way to have fields with "forbidden types" - today, that's any structs (until we have module-defined IDable types), and any types declared outside the current package. This is similar in behavior to how args work today, so maybe this isn't a huge issue.

**Comment by helderco** [comment]
> How should we indicate that the field is private in Go/Python/etc?

In Python it's the opposite approach: explicit. You'll need to use the decorators to expose something to the API. Otherwise it'll stay internal but still serializable in results and arguments. 

```python
from dagger import mod

@mod.object_type
class ExposedClass:
    private_field: str
    exposed_field: str = mod.field()

    def private_function(self) -> str:
        return "bar"

    @mod.function
    def exposed_function(self) -> str:
        return "bar"
```

These "private" prefixes aren't really private to the class, that would be prefixing the name with an underscore ("_"). They're just not exposed to the API using `withObject`, `withField` and `withFunction`.

**Comment by jedevc** [comment]
Ha ok so during the community call - I had a realization... we kind of already have this today, entirely by accident: https://github.com/dagger/dagger/issues/5860.

If you don't declare the `json` fields, we can't query those properties but they are serialized/deserialized correctly. This isn't quite right though, since codegen against that module is convinced we can access the property - even if we can't.
