### ISSUE TITLE
withEntrypoint should clear default arguments (by default)

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#6044]
## Problem

When I call `Container().WithEntrypoint()`, the container's entrypoint is changed (good) but the default arguments, if any, remain unchanged (confusing).

Keeping the default arguments when changing the entrypoint is confusing, because default arguments are applied to the entrypoint. So although it's possibly that the arguments still apply to the new entrypoint, it's most likely not. This is *especially* confusing when setting the entrypoint of a third-party image: typically the consumer doesn't know what entrypoint or default args are set, if any. In that context, if the consumer sets the entrypoint it expects arguments to be cleared. The fact that it is not, creates confusing errors.

### Example of the problem

Example: `index.docker.io/ubuntu` has no entrypoint, but default arguments are `["/bin/bash"]`. Look at this snippet:

```golang
func motdContainer() *Container {
  return dag.Container().From("index.docker.io/ubuntu").WithEntrypoint([]string{"motd"})
}

func motd(ctx context.Context) (string, error) {
  // FIXME: can't remember the exact laziness behavior but don't have the courage to look it up for a hypothetical example. Is there an extra Sync() call needed? Whatever.
  return motdContainer().Stdout(ctx)
}
```

- What I expect to be executed: `["motd"]`
- What is actually executed: `["motd", "/bin/bash"]`

As a result, I get a cryptic error. Or if I'm not lucky, no error at all depending on the state of polish of the CLI command I'm using (experimental Zenith commands, etc).

This actually happened to me, I had to ask for help on Discord to understand what was going on.

## Solution

1. Change the behavior of `WithEntrypoint` so that default arguments are cleared by default.
2. Add an option to `WithEntrypoint`: `keepDefaultArgs: Bool!`. The default value is `false`. If set to `true`, the old behavior is preserved, and default arguments are not cleared.

This is a breaking change, but:

- I believe the actual breakage will be almost zero, because it's unlikely that anyone relies on the behavior being broken.
- If someone does rely on it, it's easy to fix. 
- The behavior being broken is bad and confusing, so the benefit of breaking it is greater than the cost.

**Comment by helderco** [comment]
> * What I expect to be executed: `["/bin/sh", "-c", "echo hello world"]`
> * What is actually executed: `["/bin/sh", "/bin/bash", "-c", "echo hello world"]`

Isn't the first one what's executed? Since you're using `WithExec`, it should override whatever's in default args:
https://play.dagger.cloud/playground/vlZdVPVSK0Q

**Comment by shykes** [comment]
> Isn't the first one what's executed? Since you're using `WithExec`, it should override whatever's in default args: https://play.dagger.cloud/playground/vlZdVPVSK0Q

Yes sorry, I made up an example to try and illustrate the problem, but my example is wrong. I will simplify.

**Comment by helderco** [comment]
I agree! 

I submitted https://github.com/dagger/dagger/pull/6280 and you can see that when `withDefaultArgs()` is used in our codebase (with empty args) it's either to pair it with a `withEntrypoint` or to just unset it, which you can do with `withoutDefaultArgs` after https://github.com/dagger/dagger/pull/6278.
