### ISSUE TITLE
dagger mod publish should switch to `PUT /crawl` instead of `GET /crawl`

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#6066]
There has been a recent change - 7pm GMT on Nov. 5, 2023 - in the <https://daggerverse.dev> route that publishes a module.

It used to be `GET /crawl`. It is not `PUT /crawl`. This private PR has more details: https://github.com/dagger/dagger.io/pull/3058#issuecomment-1793819422

This is a reminder that we need to change the route that `dagger mod publish` uses & also cut a new release.

As a temporary workaround publish directly from <https://daggerverse.dev> instead.

I will be travelling & will not have internet for the next 10 hours. Unless someone else doesn't beat me to it - @vito @sipsma @jedevc @helderco @marcosnils @aluzzardi - I will look into this when I get on the other side.

🛫

**Comment by gerhard** [comment]
WDYT @vito, should we close this since https://github.com/dagger/dagger.io/pull/3074 ?

**Comment by vito** [comment]
I think we can keep this, it still makes more sense to do a PUT here anyway, and we should probably also switch it to a proper API so it can handle errors.

**Comment by shykes** [comment]
FYI `dagger mod publish` appears to be broken. It will appear to succeed, even printing a published URL with checksum, but that URL will 404.

@vito just pointed me in the direction of this issue from Discord.
