### ISSUE TITLE
Zenith: Support invoking core in CLI

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#6078]
Conceptually speaking core is a module (not in the implementation yet) so it makes sense that you could invoke it with dagger call/shell/up/etc too.

**Comment by helderco** [comment]
Done in #6293, or is there something missing?

**Comment by sipsma** [comment]
> Done in #6293, or is there something missing?

Yep this is done, rest of interrelated follow ups described here https://github.com/dagger/dagger/issues/6229#issuecomment-1875963601
