### ISSUE TITLE
🖐️ Docker commands not working after v0.7.4

### ISSUE THREAD

**Issue by KarlisAG** [dagger/dagger#6092]
### What happened? What did you expect to happen?

We are facing an issue with running docker commands with dagger ever since v0.7.4. That is the last version where it worked for us. We planned to use dagger in our ci/cd and some tasks include docker commands. It also fails for simple commands such as `docker ps`. Here is a snippet of command we use in go:

```
socket := client.Container().
		From("docker").
		WithUnixSocket("/var/run/docker.sock", client.Host().UnixSocket("/var/run/docker.sock")).
		WithExec([]string{"docker", "ps"})
	out, err := socket.Stdout(ctx)
	if err != nil {
		panic(err)
	}
	fmt.Println(out)
```

When this is ran with `dagger.io/dagger v0.7.4` then we have the expected output of docker container list.

When the same is ran with v0.8 or v0.9 versions then it fails with the following:

```
13: exec dockerd-entrypoint.sh docker ps
13: [0.11s] runc run failed: unable to start container process: error during container init: error mounting "cgroup" to rootfs at "/sys/fs/cgroup": mount cgroup:/sys/fs/cgroup/openrc (via /proc/self/fd/6), flags: 0xf, data: openrc: invalid argument
13: exec dockerd-entrypoint.sh docker ps ERROR: process "dockerd-entrypoint.sh docker ps" did not complete successfully: exit code: 1
panic: input:1: container.from.withUnixSocket.withExec.stdout process "dockerd-entrypoint.sh docker ps" did not complete successfully: exit code: 1

Stdout:

Stderr:


goroutine 1 [running]:
main.main()
        /Users/karlisakotsgribulis/repos/github/dagger-ci-example/examples/docker-engine-host/main.go:31 +0x404
exit status 2
```

I am using Rancher Desktop on MacOS with M2 chip.

Is there something that we are missing? Or is this a known issue that would be fixed? Or is this interaction no longer supported? Any help would be greatly appreciated as we are hard stuck due to this and are forced to use older version.

**Comment by xsxz** [comment]
@KarlisAG Rancher support on M1/M2 is abysmal, have you tried Orbstack? I'm using it for a few months and haven't come across any showstopper bug yet, compared to other containerization solutions

**Comment by KarlisAG** [comment]
Thanks for the input @xsxz, I tried with OrbStack and the problem indeed disappeared. So it really seems to be a Rancher problem currently
