### ISSUE TITLE
Intermittent `failed to get state for index` errors

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#6111]
These sorts of errors have been happening occasionally (~1 / day) in our CI approximately since we switched over everything to our shared runners:
```
Error: input:1: pipeline.pipeline.container.export failed to solve for container publish: failed to compute cache key: failed to get state for index 0 on copy /runc /usr/local/bin/runc
```
([run](https://github.com/dagger/dagger/actions/runs/6870983081/job/18686952381?pr=6102#step:5:980))

The exact message varies but seems to always happen on FileOps and include `failed to compute cache key: failed to get state for index 0`.

There is an upstream issue for this here: https://github.com/moby/buildkit/issues/3635

If we can repro the error and get useful data will move to the upstream issue (or just send PR w/ fix). Creating this to track in case anyone hits it and searches for the error message.

---

The fact that it seems to have only started once we switched to the shared runner is notable. My immediate gut reaction is that it probably has something to do with concurrent solves that overlap in vertexes since that's proven to be a fairly tricky + error prone codepath in buildkit and is something that would have not happened previously before switching to the shared runners.

**Comment by matiasinsaurralde** [comment]
Have been observing it in the past days too: https://github.com/dagger/dagger/actions/runs/6937495840/job/18871658791?pr=6136

**Comment by gerhard** [comment]
I know that we've been seeing these for a while, want to resume tracking them so that we have a better idea of how often they happen:
- https://github.com/dagger/dagger/actions/runs/7729432480/job/21072590483#step:6:720

**Comment by gerhard** [comment]
https://github.com/dagger/dagger/actions/runs/7734943604/job/21103510867#step:6:882

![image](https://github.com/dagger/dagger/assets/3342/f95b7227-3f0a-4db3-b9a3-61bebe6ec86b)

**Comment by gerhard** [comment]
Just hit this again while releasing `0.10.2`: https://github.com/dagger/dagger/actions/runs/8253625814/job/22575935633?pr=6871#step:6:772

<img width="1440" alt="image" src="https://github.com/dagger/dagger/assets/3342/add0d775-6116-45a2-b87a-137c8c2ea21f">

**Comment by mckinnsb** [comment]
I also get this error, but I get a different "source":

```
cause: ClientError: resolve: container: withRegistryAuth: build: publish: failed to solve for container publish: failed to compute cache key: failed to unmount /tmp/containerd-mount922630576: failed to unmount target /tmp/containerd-mount922630576: device or resource busy: {"response":{"errors":[{"message":"resolve: container: withRegistryAuth: build: publish: failed to solve for container publish: failed to compute cache key: failed to unmount /tmp/containerd-mount922630576: failed to unmount target /tmp/containerd-mount922630576: device or resource busy"}]
```

**Comment by helderco** [comment]
Whelp! This error is happening a lot in Python tests:

```
failed to compute cache key: failed to get state for index 0 on copy /runtime/template/runtime.py /runtime
```

That copy comes from here:

https://github.com/dagger/dagger/blob/d3a11cf89ec9685d4c60737d3ab2af7bd4e558e0/sdk/python/runtime/main.go#L202-L206

Seems to be more frequent with the tests around the lock file. See anything wrong here? 

https://github.com/dagger/dagger/blob/d3a11cf89ec9685d4c60737d3ab2af7bd4e558e0/core/integration/module_python_test.go#L638-L711

Maybe this is a simpler case to debug and figure this out.

**Comment by sipsma** [comment]
Just FYI I'm attempting to debug this and the other (possibly related) `inconsistent graph state` errors here:  https://github.com/dagger/dagger/pull/7128

**Comment by sipsma** [comment]
More details in https://github.com/dagger/dagger/pull/7128, but ended up being able to very consistently repro this locally and figured out the bug upstream, fix there https://github.com/moby/buildkit/pull/4887

Will leave this open until we've picked up the upstream fix, done a release with it, upgraded CI runners and confirmed that the errors are gone now

**Comment by gerhard** [comment]
Yes!

FTR, the new CI runners for Engine & CLI are `16 CPUs` & `128GB RAM`, so this is less likely to occur for those CI jobs.

All other CI runners are still bunching around a single Engine, so we can expect this to continue being an issue.

💪

**Comment by jedevc** [comment]
The worst of this seems to be resolved by https://github.com/dagger/dagger/pull/7295, so going to take this out of the milestone, but worth leaving open until the upstream fix is resolved.

**Comment by jedevc** [comment]
Just seen this again in https://github.com/dagger/dagger/pull/10483.

https://v3.dagger.cloud/dagger/traces/531b0e1d0f5091068680253756c79298?span=fea0480a79cbb9e1
