### ISSUE TITLE
Zenith: Python SDK: `Error` `Type.__init__()` demands `required positional argument: 'ctx'`

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#6128]
User was writing a Python Module
https://github.com/Mjb141/daggerverse/tree/b4b387b0e22ee776e662be9987513043357fa3d9/echo

which uses another Python module
https://github.com/Mjb141/daggerverse/blob/b4b387b0e22ee776e662be9987513043357fa3d9/echo/dagger.json#L5
https://daggerverse.dev/mod/github.com/jpadams/daggerverse/infisical@7f64507480159500910b48f161ba8e256fa0f8ff
(note, there was an update to the infisical module, but both of these throw the same error: https://github.com/jpadams/daggerverse/commit/08bcbd1bd59467cabc8b0d1eebaadeea69314fa9)

and ran into this error message from this repro:
```
DAGGER_MODULE="github.com/Mjb141/daggerverse/echo@b4b387b0e22ee776e662be9987513043357fa3d9" dagger call with-secret --name "DATABASE_URL" --token `cat ~/infisical_service_token` echo --word foo
```

```
✘ withSecret(name: "DATABASE_URL", path: "/", token: "core.Secret:eyJuYW1lIjoiNjEzYWQxN2RkMTRiYzZmZDU1ZTBmNDVjMmZhZjM4MDFjOGY4NjBkNjdkMzgzYWY3ZmZhZmRiZWYwMWIwNGQ5YSJ9", env: "dev") ERROR [0.56s]
✘ dagger call with-secret echo ERROR [0.56s]
┃ Error: response from query: input:1: echoMod.withSecret failed to call function "EchoMod.withSecret": failed
┃  to get function output directory: process "/runtime" did not complete successfully: exit code: 1
✘ exec /runtime ERROR [0.54s]
┃ [DEBUG] dagger.client._session: Configuring shared connection to GraphQL server
┃ [DEBUG] dagger.client._session: Establishing client session to GraphQL server
┃ [DEBUG] dagger.mod._module: resolver => EchoMod.with_secret
┃ [DEBUG] dagger.mod._resolver: input args => {'name': 'DATABASE_URL', 'path': '/', 'token': 'core.Secret:eyJu
┃ 1lIjoiNjEzYWQxN2RkMTRiYzZmZDU1ZTBmNDVjMmZhZjM4MDFjOGY4NjBkNjdkMzgzYWY3ZmZhZmRiZWYwMWIwNGQ5YSJ9', 'env': 'dev
┃
┃ [DEBUG] dagger.mod._resolver: structured args => {'name': 'DATABASE_URL', 'token': <dagger.Secret object at
┃ ffff9dc03ed0>, 'env': 'dev', 'path': '/'}
┃ [DEBUG] dagger.client._session: Closing client session to GraphQL server
┃ ╭─ Error ──────────────────────────────────────────────────────────────────────╮
┃ │ Function execution error: Type.__init__() missing 1 required positional      │
┃ │ argument: 'ctx'                                                              │
┃ ╰──────────────────────────────────────────────────────────────────────────────╯
• Engine: 801e71be998b (version v0.9.3)
⧗ 2.42s ✔ 45 ∅ 39 ✘ 3
```
@helderco @Mjb141

**Comment by helderco** [comment]
It's not a bug. Maybe the error message can be better but not sure how.

The problem is in this line:
```python
        self.secret = dagger.Infisical().get_secret(name, token, env, path)
```
There's a difference between `dagger.Infisical` and `dagger.infisical`. The former is the object type, which you can't instantiate directly (same as `dagger.Container()`), while the latter is the constructor that's in `Query.infisical` in the API.

So it should be:
```python
        self.secret = dagger.infisical().get_secret(name, token, env, path)
```

**Comment by Mjb141** [comment]
> It's not a bug. Maybe the error message can be better but not sure how.
> 
> The problem is in this line:
> 
> ```python
>         self.secret = dagger.Infisical().get_secret(name, token, env, path)
> ```
> 
> There's a difference between `dagger.Infisical` and `dagger.infisical`. The former is the object type, which you can't instantiate directly (same as `dagger.Container()`), while the latter is the constructor that's in `Query.infisical` in the API.
> 
> So it should be:
> 
> ```python
>         self.secret = dagger.infisical().get_secret(name, token, env, path)
> ```

I think this is going to trip people up - `infisical()` intuitively feels like a class (which is typically title-cased). Thanks for letting me know however! This can be closed.

**Comment by helderco** [comment]
> `infisical()` intuitively feels like a class

I don't agree with you. Both a function and a class instantiation are called the same way in Python. It's the casing that's the convention for being a class or not.
