### ISSUE TITLE
🐞 Daggerverse.dev search is broken. 

### ISSUE THREAD

**Issue by aweris** [dagger/dagger#6131]
### What is the issue?

I noticed that when searching something on daggerverse.dev, an error appears as shown in the screenshot.

### Log output

<img width="1375" alt="image" src="https://github.com/dagger/dagger/assets/9319656/de41c691-3901-48b0-af18-b78187a31d5f">

### Steps to reproduce

Search anything on https://daggerverse.dev. Example link https://daggerverse.dev/search?q=github

### SDK version

daggerverse.dev

### OS version

macOS 14.0

**Comment by vito** [comment]
Fix has been deployed - thanks!
