### ISSUE TITLE
Convert Dagger's CI to a module

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#6137]
Now that we have Zenith we can move off `internal/mage` and instead implement all our own CI as a module.

There's a very stale attempt in the ci/ dir of the dagger repo. 

There's also some external modules that are more recent attempts here:
* https://github.com/shykes/daggerverse/tree/main/dagger
* https://github.com/quartz-technology/daggerverse/tree/891e322be8dd277ffe118372873edbb5b442bc99/dagger

The idea would be to update ci/ to have all the equivalent functionality of internal/mage and then remove mage entirely

---

It would be very nice if we could do this piece-by-piece rather than all at once.

The best route I currently see would be to maintain common code in `internal/mage`, make use of that as much as possible in the `ci/` module and then convert workflows under `.github/workflows` over to the `ci/` module one-by-one.

Then once we finally convert everything we can just delete `internal/mage` and move common code entirely into the `ci/` dir.

An alternative approach would be convert all of `internal/mage` over to run in a module and then refactor it from there. I don't have strong feelings either way on this approach vs. the above; it mostly comes down to which is more tractable in practice.

---

Misc things to keep in mind:
1. We need to maintain the use of the previous "stable" version of dagger to build the dev one. In the new module approach, the "stable" dagger would no longer be controlled via a `go.mod` in `internal/mage` and instead just be a CLI from our previous release.
2. The above implies updates will be needed to `./hack/dev`. It would be nice to get rid of `./hack/dev` entirely, but that may require changes slightly outside the scope of this effort, so I don't think we need to tackle removing it right away. That can be a follow up

This is also all a bit high-level, happy to help clarify further and discuss more as needed 🙂

**Comment by helderco** [comment]
Python tasks are already being migrated in #6117, so it should be a dependency of the `ci` module for coordinating what's needed in GHA.

**Comment by helderco** [comment]
This was done in:
- https://github.com/dagger/dagger/pull/6843

With numerous follow-ups, but on a more recent progress:
- https://github.com/dagger/dagger/pull/7349
