### ISSUE TITLE
🐞 Import doesn't work in typescript

### ISSUE THREAD

**Issue by miroljub1995** [dagger/dagger#6141]
### What is the issue?

I have basic `tsconfig.json` (bellow) and I use `ts-node` but I have to use dynamic import and can not import types. Whatever I tried (type module in package.json, .mts extension, ...) I ended up with different errors.
```json
// tsconfig.json
{
    "extends": "@tsconfig/node20"
}

```

![image](https://github.com/dagger/dagger/assets/46632388/8e3115a6-ded1-42cf-a0e8-08db62a39da9)

Is there a reason not to support CommonJS?
I think the easiest way to support both would be to have exports in package.json like:
```json
// package.json
...
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.mjs",
      "require": "./dist/index.js"
    }
  }
...
```

### Steps to reproduce

1. `npm init`
2. `npm i ts-node typescript @tsconfig/node20 @dagger.io/dagger`
3. create `tsconfig.json` with content: 
```json
{
    "extends": "@tsconfig/node20"
}
```

5. create `index.ts` with example:
```ts
import { connect, Client } from "@dagger.io/dagger"

// initialize Dagger client
connect(
  async (client: Client) => {
    // get Node image
    // get Node version
    const node = client.container().from("node:16").withExec(["node", "-v"])

    // execute
    const version = await node.stdout()

    // print output
    console.log("Hello from Dagger and Node " + version)
  },
  { LogOutput: process.stderr }
)
```
6. observe errors in `index.ts`

### SDK version

Node.js v0.9.3

### OS version

Ubuntu 22.04

**Comment by vvaswani** [comment]
@slumbering can you help with this question?

**Comment by vikram-dagger** [comment]
@slumbering can you help with this question?

**Comment by slumbering** [comment]
hey @miroljub1995 👋 !
I've tested using your reproduction steps and encountered no errors after configuring my `package.json` with `"type": "module"`. However, I did experience the same error as you when I removed this setting.

If you are using VSCode, did you try to restart your TS server? 

https://github.com/dagger/dagger/assets/1186424/4c9a3323-e616-4c3c-9f4a-096fe5b43666

**Comment by miroljub1995** [comment]
Setting `"type": "module"` doesn't give compile errors, but I was getting runtime error when running `dagger run ts-node --esm ./index.ts`
I got back to documentation and tried `dagger run node --loader ts-node/esm ./index.ts` instead, and it works. I thought those two commands have the same behaviour, but apparently not.

Thanks for the investigation, I'm closing this issue now.
