### ISSUE TITLE
Update the Node get started and other docs to use `tsx` to run `.ts/.mts` scripts

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#6143]
### What is the issue?

This task is to replace `node --loader ts-node/esm` with `tsx` in our docs where running `.ts/.mts` scripts.

In the Node.js get started https://docs.dagger.io/sdk/nodejs/783645/get-started:
- You no longer need a tsconfig.json as well. This step is not needed: `npx tsc --init --module esnext --moduleResolution nodenext`.
- Instead of `npm install ts-node typescript` use `npm install tsx`.

**Comment by miroljub1995** [comment]
Is this related to [this](https://github.com/dagger/dagger/issues/6141) issue I created?

**Comment by TomChv** [comment]
@vikram-dagger Hey Vikram, is this related to our Zenith documentation? 
I'm not sure we will have the kind of issue with the new doc so should we close this issue?

**Comment by vikram-dagger** [comment]
Closing as this is not required when running Dagger Functions.
