### ISSUE TITLE
✨ PHP SDK

### ISSUE THREAD

**Issue by zeroware** [dagger/dagger#6157]
### What are you trying to do?

Add PHP language support to Dagger.

### Why is this important to you?

Most of my projects are using PHP

### How are you currently working around this?

Hello !
I made an experimental SDK here : https://github.com/the-diamond-dogs/dagger-php-sdk
I'd like to get feedback and some help on how to integrate it into Dagger :cowboy_hat_face:

**Comment by helderco** [comment]
Thank you!

Have you read the [SDK Contribution Guide](https://github.com/dagger/dagger/blob/main/sdk/CONTRIBUTING.md)?

TLDR for next step is to make a PR to add the SDK under the [./sdk](https://github.com/dagger/dagger/tree/main/sdk) directory.

**Comment by helderco** [comment]
Done in:
- #6165 

First version published in [Packagist](https://packagist.org/packages/dagger/dagger).
