### ISSUE TITLE
How to build a container from a local registry? python SDK, 

### ISSUE THREAD

**Issue by Lyufy** [dagger/dagger#6215]
for example, when using client.container().from_("xxxxx")  to build a container, what should I do to let it happen from my local image registry?     

dagger version- 0.9.3

**Comment by helderco** [comment]
@Lyufy the essence of what you need is in:
- https://github.com/dagger/dagger/issues/5235

We're missing some plumbing still to make this much easier but in the meantime you need the local registry in the same network as the dagger engine, or at least reachable by the engine container (e.g., public URL).

I don't know any specifics about your infrastructure and what you can or can't do to setup the local registry. Let us know with more specifics if you need any help.

**Comment by helderco** [comment]
Let us know if you need help, but if it's directly related to #5235 you can ask there 🙂
