### ISSUE TITLE
Python modules: Fix type checking issue on `@function` usage

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#6223]
This was introduced by #6152 where the `self` argument isn't recognized as a bound variable on methods decorated with `@function` so it throws off on parameter usage:

<img width="951" alt="Screenshot 2023-12-06 at 11 30 46" src="https://github.com/dagger/dagger/assets/174525/dca0a373-7b19-4511-a6be-41e847e460dc">

Note that it's not a problem at runtime, only in the IDE.

**Comment by jedevc** [comment]
@helderco I think this was fixed by https://github.com/dagger/dagger/pull/6232?

**Comment by gerhard** [comment]
Partially, something else is missing based on the comment of that PR. @helderco?

**Comment by helderco** [comment]
> Partially, something else is missing based on the comment of that PR. @helderco?

There is, but it's related to the recent constructors support (#6152) that:
- haven't been released yet
- it's for a Python specific DX sugar
- only affects the IDE

So I think this issue can be closed and a later followup will fix the remaining use case.
