### ISSUE TITLE
Amazon S3: support creating bucket

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#623]
The Amazon S3 package should support (optionally) creating a bucket when it does not exist.

**Comment by gregwebs** [comment]
There is the AWS CDK (which generates clouformation) and has a go SDK. Personally, I really like having a central record of managed infrastructure in cloudformation with the associated basic GUI functionality. Terraform and Pulumi offer this as a paid service.

Terraform and Pulumi have Go code that can be reused. And now they are leveraging the [AWS Cloud Control API](https://aws.amazon.com/blogs/aws/announcing-aws-cloud-control-api/)

Deleting an AWS bucket requires it to be emptied of objects: that either has to be given to the user as an error message or automated with additional API calls.
