### ISSUE TITLE
CI: split up engine publish and CLI publish

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#6243]
Sometimes the engine publish job needs to re-run independent of the CLI publish, but right now because it all happens in the same job you can't run one without the other, which can create headaches where a re-run results in partial success (re-running engine publish) but failure during CLI publish.

If the jobs were separate but dependent this could be a lot cleaner to deal with.

cc @gerhard, creating issue for what we mentioned during the last release process

**Comment by jedevc** [comment]
Looks like this got done in some point during https://github.com/dagger/dagger/pull/7483:

https://github.com/dagger/dagger/blob/83f29933a90cc530b2a9bcd8e9431ff37af39bff/.github/workflows/engine-and-cli-publish.yml#L42-L85
