### ISSUE TITLE
tests: flaky rust test

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#6304]
cc @dagger/sdk-rust :heart: 

I frequently see this rust test failing: https://github.com/dagger/dagger/actions/runs/7263920431/job/19790293305 (which passes upon a re-run):

```
Diff < left / right > :
 failed to query dagger engine: domain error:
 Look at json field for more details
<unexpected status from HEAD request to https://mirror.gcr.io/v2/library/fake.invalid/manifests/latest?ns=docker.io: 429 Too Many Requests
>pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

Not quite sure why this shows up, but it appears reasonably frequently, so would be nice to clean up! Will take a look myself if I find some spare time :pray:

**Comment by kjuulh** [comment]
Hmm. I think it may be retrying too often. Or using an invalid user agent. Hence the Too Many Requests. I will have a look.

**Comment by jedevc** [comment]
@samalba any context on re-opening this?
