### ISSUE TITLE
CLI: improve display of core API in `--help` output

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#6358]
https://github.com/dagger/dagger/pull/6293 exposed the core API in `dagger call`, which results in `--help` and `dagger functions` output to be pretty overwhelming and messy when dealing with core types like `Container`.

There's most likely going to be a lot of little things needed to address this, possibly including but not limited to:
1. displaying multi-line doc strings better
2. sorting of functions more cleanly

I think we should start out trying to do this purely from the CLI without engine-side changes. But if that ends up not being feasible then we can consider whether typedefs could get optional support for annotating CLI specific presentation metadata. Preferable to avoid going down that road if possible though.

**Comment by helderco** [comment]
Maybe:

* sort functions alphabetically to make them easier to find
* print only the first line of a function description in sub-commands list
* print the whole thing when showing `--help` for function/sub-command specifically

**Comment by helderco** [comment]
Started working on this and there's more changes to the above list. I'll list them in the PR and we can go from there.

**Comment by helderco** [comment]
`dagger functions` was cleaned in:
- #6317
