### ISSUE TITLE
Document that changing secrets doesn't invalidate the cache

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#6368]
### What is the issue?

This is coming from a Discord question here: https://discord.com/channels/707636530424053791/1193141267903815700

Our official secrets docs (https://docs.dagger.io/723462/use-secrets/) do not mention anything about the fact that changing secrets doesn't invalidate the cache. I think it's important to highlight this property so users are aware of this.

**Comment by taylormonacelli** [comment]
Is deleting the container the recommended flow?  I'm using this and then rerunning.

```bash
docker ps -a --format "{{.Names}}" | grep "^dagger-engine-" | xargs --no-run-if-empty -I {} docker rm --force {}
dagger run go run hello-dagger/ci/main.go
```

Is it expected in the future that changing secret values will in fact invalidate the cache?

I'm really loving what dagger is offering and looking forward to using it.  Thanks a lot for providing this tool

**Comment by jedevc** [comment]
> Is it expected in the future that changing secret values will in fact invalidate the cache?

I don't expect we'll change this behavior.

One of the reasons that would make this tricky is that the secret then becomes part of the cache key - this is kinda dangerous, even though the cache key is a sha256 digest. Potentially, it means that a leak of the cache key could allow brute-forcing the secret :scream: 

> Is deleting the container the recommended flow?

At the moment, that's really the only option sadly :cry: 

I have suggested a new `cache` subcommand to control cache in the dagger engine: https://github.com/dagger/dagger/issues/6260. Is that kind of close to something that you'd be looking for?

**Comment by helderco** [comment]
The exception is when a secret is provided as input to a module with `dagger call`. Secrets from the CLI have a name that's based on the value.

**Comment by marcosnils** [comment]
> At the moment, that's really the only option sadly 😢

@jedevc I think invalidating the cache via  https://docs.dagger.io/cookbook/#invalidate-cache also works. Unless I'm missing something, I just did a test and when the cache gets invalidated before the `With*Secret*` calls, the secret gets effectively updated in the subsequent steps.

**Comment by taylormonacelli** [comment]
> > At the moment, that's really the only option sadly 😢
> 
> @jedevc I think invalidating the cache via https://docs.dagger.io/cookbook/#invalidate-cache also works. Unless I'm missing something, I just did a test and when the cache gets invalidated before the `With*Secret*` calls, the secret gets effectively updated in the subsequent steps.

Yes using CACHEBUSTER variable works great, but having to add that explicitly for changing secrets is the problem.
