### ISSUE TITLE
🐞 Optional type in module field yields error

### ISSUE THREAD

**Issue by sagikazarmark** [dagger/dagger#6369]
### What is the issue?

When using `Optional` in a module field type (combined with constructors) Dagger yields the following error:

> Error: query module objects: json: error calling MarshalJSON for type *dagger.Module: returned error 400 Bad Request: failed to get schema for module "ci": failed to create field: failed to get mod type for field "githubActor"

### Dagger version

dagger v0.9.5 (registry.dagger.io/engine) darwin/arm64

### Steps to reproduce

Create a module with optional fields:

```go
type Ci struct {
	GithubActor Optional[string]
	GithubToken Optional[*Secret]
}

func New(
	// Actor the token belongs to.
	githubActor Optional[string],

	// Token to access the GitHub API.
	githubToken Optional[*Secret],
) *Ci {
	return &Ci{
		GithubActor: githubActor,
		GithubToken: githubToken,
	}
}

```

Run `dagger call` with any parameters.

### Log output

Error: query module objects: json: error calling MarshalJSON for type *dagger.Module: returned error 400 Bad Request: failed to get schema for module "ci": failed to create field: failed to get mod type for field "githubActor"

**Comment by jedevc** [comment]
`Optional` shouldn't be used as a struct field - it's only valid for use in function arguments. That said, the error message you get is quite bizarre, so I'll have a look at trying to improve that.
