### ISSUE TITLE
✨ Allow pulling refs from a git repo

### ISSUE THREAD

**Issue by sagikazarmark** [dagger/dagger#6375]
### What are you trying to do?

While working on replacing a GHA workflow with pure Dagger (ie. no initial checkout step the GHA workflow), I noticed the directly pulling a commit from a ref not being fetched by default (ie. belonging to a PR: `refs/pull/5/merge`) fails.

This is quite understandable, but I had a hard time figuring out a workaround.

Here is what I tried:

```go
source = dag.Git("https://github.com/openmeterio/benthos-openmeter.git", GitOpts{
	KeepGitDir: true,
}).Commit("<SHA>").Tree()
```

Ideally, I should be able to reference an actual ref within that:

```go
source = dag.Git("https://github.com/openmeterio/benthos-openmeter.git", GitOpts{
	KeepGitDir: true,
}).Ref("refs/pull/5/merge").Tree()
```

### Why is this important to you?

Running builds on PRs is common practice in the software industry (it's why CI is CI).

### How are you currently working around this?

My initial workaround was using `supergit` to pull the ref directly:

```go
source = dag.Supergit().
	Repository().
	WithRemote("origin", "https://github.com/openmeterio/benthos-openmeter.git").
	WithGitCommand([]string{"pull", "origin", r}).Worktree()
```

After inspecting the relevant [code](https://github.com/dagger/dagger/blob/6749afe236cc5e16a3eea99880d2b069ed8b2f8b/core/schema/git.go#L100) I noticed that all of `Branch`, `Tag` and `Commit` just passes in the name directly as a ref (I expected something like `refs/heads/BRANCH` and `refs/tags/TAG`)

As a result this code works as well (although it's not obvious from looking at the docs):

```go
source = dag.Git("https://github.com/openmeterio/benthos-openmeter.git", GitOpts{
	KeepGitDir: true,
}).Branch("refs/pull/5/merge").Tree()
```

I find it a bit weird though, so I still believe it would make sense to add a `Ref` function to the GitRepository.

https://github.com/openmeterio/benthos-openmeter/pull/12

**Comment by jedevc** [comment]
Mm, I think this makes sense - and I've had this same thought before. I've added a `Ref` function in #6376.

> After inspecting the relevant [code](https://github.com/dagger/dagger/blob/6749afe236cc5e16a3eea99880d2b069ed8b2f8b/core/schema/git.go#L100) I noticed that all of `Branch`, `Tag` and `Commit` just passes in the name directly as a ref (I expected something like `refs/heads/BRANCH` and `refs/tags/TAG`)

This is weird, agreed. I think we should eventually take the approach I suggest in https://github.com/dagger/dagger/pull/6376#issue-2072192878, and make `branch`/`tag`/`commit` stricter about their inputs, while keeping the new `ref` as relaxed.

**Comment by sagikazarmark** [comment]
> This is weird, agreed. I think we should eventually take the approach I suggest in [#6376 (comment)](https://github.com/dagger/dagger/pull/6376#issue-2072192878), and make `branch`/`tag`/`commit` stricter about their inputs, while keeping the new `ref` as relaxed.

Makes sense.
