### ISSUE TITLE
✨ Allow cache volumes as CLI parameters

### ISSUE THREAD

**Issue by sagikazarmark** [dagger/dagger#6409]
### What are you trying to do?

I have a module with the following constructor:

```go
func New(
	// ...

	// Disable mounting cache volumes.
	disableCache Optional[bool],

	// Module cache volume to mount at /go/pkg/mod.
	modCache Optional[*CacheVolume],

	// Build cache volume to mount at ~/.cache/go-build.
	buildCache Optional[*CacheVolume],
) *Go {
	// ...
}
```

Currently, running this module in the CLI fails due to CacheVolume being an unsupported CLI argument:

```shell
❯ dagger call -m "github.com/sagikazarmark/daggerverse/go@main" --help
✘ load call ERROR [1.21s]
├ [0.56s] loading module
├ [0.65s] loading objects
┃ Error: unsupported object type "CacheVolume" for flag: mod-cache
```

Given cache volumes are created by their names (and that other types of objects, like files, are also referenced simply by their path or ID), I think it would be useful to do the same for cache volumes. In this instance:

```shell
❯ dagger call -m "github.com/sagikazarmark/daggerverse/go@main" --mod-cache go-build
```

An alternative I can imagine is adding a pragma comment for ignoring certain arguments from the CLI, but including them in the generated code. That's a temporary measure, but would still be easier for module developers, so they can utilize constructors instead of falling back to method chaining for tasks like setting cache.

### How are you currently working around this?

I will probably remove those arguments from the constructor for now.

I might add them to the module API, but honestly, I'd rather not.

**Comment by helderco** [comment]
I usually author the module to manage the cache volumes. Curious about the use cases for wanting to provide the cache volume's name in the CLI.

**Comment by sagikazarmark** [comment]
I had some trouble with pipelines running in parallel using the same cache: https://github.com/dagger/dagger/issues/3345#issuecomment-1862711990
