### ISSUE TITLE
🐞 Dagger cli messes up with mouse in windows terminal

### ISSUE THREAD

**Issue by giovannicandido** [dagger/dagger#6417]
### What is the issue?

After running the command `dagger run go run xxx/main.go ` when it finishes, the mouse becomes useless.
This is annoying especially because you can't scroll and copy the output or any information in terminal after that.

### Dagger version

dagger v0.9.6 (registry.dagger.io/engine) windows/amd64

### Steps to reproduce

Use any terminal in windows terminal. Tested with Powershell but other shells affected

### Log output

https://github.com/dagger/dagger/assets/915892/0d192092-0234-4301-995a-b653ee34a56c

**Comment by jedevc** [comment]
cc @vito this looks like a potential progrock issue?

**Comment by vito** [comment]
Huh, yeah weird, sorry about that. It takes over mouse input so you can scroll the TUI, but it's obviously supposed to reset back to normal when you exit. Will see if I can repro this soon. I usually use Linux on Windows via WSL so that could explain the gap in testing here.

**Comment by mxdev88** [comment]
I've got the same issue. Is there a workaround? this is a really annoying one.

**Comment by vito** [comment]
We'll likely retire the TUI that `dagger run` uses soon, and it's the only one that steals mouse input. This shouldn't affect `dagger call` or any other commands that are using the new TUI. If you're in a good position to start transitioning to the [newly launched Dagger Functions](https://dagger.io/blog/introducing-dagger-functions) that would be a good way to escape this behavior along the way.

**Comment by vito** [comment]
Should be fixed with the new TUI which is now across all commands with v0.11 :+1:
