### ISSUE TITLE
connection timed out

### ISSUE THREAD

**Issue by kingcwt** [dagger/dagger#6419]
### What happened? What did you expect to happen?

I timed out when executing CI after deploying to the server

<img width="697" alt="image" src="https://github.com/dagger/dagger/assets/29888469/f14b0965-08c4-4722-bd4a-75e290fddb14">

<img width="899" alt="image" src="https://github.com/dagger/dagger/assets/29888469/c8cf5730-a838-4594-a26b-a15497c525b8">
connection timed out

**Comment by jedevc** [comment]
It looks like this is getting stuck in the `pulling registry.dagger.io/engine:v0.9.5` step.

It could just be that the connection to `registry.dagger.io` is slow, can you attempt to manually pull it using `docker pull registry.dagger.io/engine:v0.9.5`?

**Comment by kingcwt** [comment]
It's caused by network issues. The company website is really poor
