### ISSUE TITLE
🐞 Excessive wait time on first command execution following version upgrade

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#6426]
### What is the issue?

After upgrading to a new Dagger version, attempting to create a module fails on first attempt. The new engine container is downloaded and started, but command execution seems to "freeze". The only workaround is to cancel and reattempt the command and in this case it executes correctly and immediately.

### Dagger version

dagger v0.9.6 ([registry.dagger.io/engine](http://registry.dagger.io/engine)) linux/amd64

### Steps to reproduce

Initial setup:
Dagger 0.9.5 installed and 0.9.5 container running.

Upgrade to Dagger 0.9.6:

```
curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
```

Check version:

```
dagger version
dagger v0.9.6 (registry.dagger.io/engine) linux/amd64
```

Create a new module:

```
dagger mod init --name=my-module --sdk=typescript
...
⧗ 6m23.3s ✔ 1
Error: new client: Canceled: context canceled
```

(execution cancelled by me after waiting 6m with no change)

```
docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
1a47107f1a46 registry.dagger.io/engine:v0.9.6 "dagger-entrypoint.s…" 6 minutes ago Up 6 minutes dagger-engine-81cc306759c2da0f
```

### Log output

```
dagger mod init --name=my-module --sdk=typescript
...
⧗ 6m23.3s ✔ 1
Error: new client: Canceled: context canceled
 
docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
1a47107f1a46 registry.dagger.io/engine:v0.9.6 "dagger-entrypoint.s…" 6 minutes ago Up 6 minutes dagger-engine-81cc306759c2da0f
```

**Comment by TomChv** [comment]
@vikram-dagger Did you encounter that issue recently?

**Comment by vikram-dagger** [comment]
> @vikram-dagger Did you encounter that issue recently?

No. We can close this.
