### ISSUE TITLE
🐞 Service stop semantics work differently between SDK and Modules

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#6430]
### What is the issue?

Initially repoted by @matipan here: https://discord.com/channels/707636530424053791/1120503349599543376/1196809237150584995

Given the current function

```go
func (m *Foo) Nginx(ctx context.Context) error {
	svc := dag.Container().
		From("nginx").
		WithExposedPort(80).
		AsService()
	tunnel, err := dag.Host().Tunnel(svc).Start(ctx)
	if err != nil {
		return err
	}
	defer tunnel.Stop(ctx) 

	endpoint, err := tunnel.Endpoint(ctx)
	if err != nil {
		return err
	}

	res, err := http.Get("http://" + endpoint + "/")
	if err != nil {
		return err
	}
	defer res.Body.Close()
	io.Copy(os.Stdout, res.Body)
	return nil
}
```

upon calling `dagger call nginx`,  dagger will hang for a long time in the `defer tunnel.Stop(ctx)` call. If instead of just stopping the tunnel, we stop both the service and the tunnel in the defer function, this works as intended. 

This doesn't happen while using the SDK directly without modules, the `defer` statement described in the example returns immediately. 

### Dagger version

v0.9.6

### Steps to reproduce

Run the snippet above withing a context of a module.

**Comment by jedevc** [comment]
This looks unrelated to #6354.

We seem to get stuck in https://github.com/dagger/dagger/blob/8483a5e7ace6174c60e37ba395ddd1ad9b849c1e/core/service.go#L585-L587

We never shut down the connection: https://github.com/dagger/dagger/blob/8483a5e7ace6174c60e37ba395ddd1ad9b849c1e/engine/buildkit/client.go#L641-L644

We need to make sure to *properly* shut down our outgoing connections, or we'll just keep reading and reading forever (see #6518). Not 100% sure why this only appears in modules, but for some reason... it doesn't.
