### ISSUE TITLE
🐞 Platform type is converted to string by the code generator

### ISSUE THREAD

**Issue by sagikazarmark** [dagger/dagger#6466]
### What is the issue?

The core Platform type is converted to string when using a module that references that type.

### Dagger version

dagger v0.9.6 (registry.dagger.io/engine) darwin/arm64

**Comment by helderco** [comment]
Can you provide more details?

**Comment by sagikazarmark** [comment]
I use `Platform` in [this](https://github.com/sagikazarmark/daggerverse/blob/main/go/main.go#L162) module.

When using that module as a dependency, the code generator turns `Platform` to `string`:

```go
type GoWithSourceBuildOpts struct {
	// Target platform in "[os]/[platform]/[version]" format (e.g., "darwin/arm64/v7", "windows/amd64", "linux/arm64").
	//
	Platform string
}
```

**Comment by helderco** [comment]
So the issue must extend to all scalars then.

@sipsma, do we need a KindScalar?
