### ISSUE TITLE
Networking errors after calling `Sync()` on Containers that have dependent Services

### ISSUE THREAD

**Issue by kpenfound** [dagger/dagger#6493]
I have a pipeline with multiple Services and Containers being passed around. If a Container that has a dependent service is `Sync()`'ed, future calls to the Service will fail with something like:

`lookup 5r4dg8qetp2iq.r4mh9kocl49fi.dagger.local on 10.87.0.1:53: no such host`

psuedocode example:

```go
foo := dag.Container().From("postgres").AsService()

bar := dag.Container().From("asdf").WithServiceBinding("db", foo).WithExec(["some", "commands])

_, err := bar.Sync()

baz := dag.Container().From("zbcd").WithServiceBinding("db", foo).WithExec(["this", "fails"])
```

If the `bar.Sync()` here is removed, the `baz` execution will be successful.

**Comment by kpenfound** [comment]
Runnable example: https://github.com/kpenfound/example-voting-app/blob/daggerize/ci/main.go#L21-L25

**Comment by jpadams** [comment]
https://discord.com/channels/707636530424053791/1120503349599543376/1199329512203235349

**Comment by sagikazarmark** [comment]
Same problem here: https://github.com/sagikazarmark/daggerverse/pull/42

**Comment by jedevc** [comment]
Based on @kpenfound's report, this works on v0.9.6, but doesn't on v0.9.7. Did a git bisect, and isolated the issue to #6425 (cc @sipsma).

```
9bf9f7f303b6768efbba540376a0bd6eae6979a3 is the first bad commit
commit 9bf9f7f303b6768efbba540376a0bd6eae6979a3
Author: Erik Sipsma <erik@dagger.io>
Date:   Mon Jan 15 16:14:37 2024 -0800

    services: key services by server id; auto start cli service flags (#6425)
```

**Comment by jedevc** [comment]
Got a test that seems to produce the desired issue on v0.9.7, but can't seem to repro on `main` for whatever reason.

```go
func TestModuleServiceSync(t *testing.T) {
	t.Parallel()

	c, ctx := connect(t)

	modGen := c.Container().From(alpineImage).
		WithMountedFile(testCLIBinPath, daggerCliFile(t, c)).
		WithWorkdir("/work").
		With(daggerExec("mod", "init", "--name=playground", "--sdk=go")).
		WithNewFile("main.go", dagger.ContainerWithNewFileOpts{
			Contents: `
package main

import (
	"context"
)

type Playground struct{}

func (p *Playground) DoThing(ctx context.Context, sync bool) (*Container, error) {
	svc := dag.Container().From("nginx").WithExposedPort(80).AsService()
	foo := dag.Container().From("alpine").
		WithExec([]string{"apk", "add", "curl"}).
		WithServiceBinding("foo", svc).
		WithExec([]string{"curl", "http://foo"})
	if sync {
		if _, err := foo.Sync(ctx); err != nil {
			return nil, err
		}
	}
	return foo, nil
}
`})
	modGen, err := modGen.Sync(ctx)
	require.NoError(t, err)
	logGen(ctx, t, modGen.Directory("."))

	out, err := modGen.
		With(daggerQuery(`{playground{doThing(sync: false){stdout}}}`)).
		Stdout(ctx)
	require.NoError(t, err)
	require.Contains(t, out, "Welcome to nginx")

	out, err = modGen.
		With(daggerQuery(`{playground{doThing(sync: true){stdout}}}`)).
		Stdout(ctx)
	require.NoError(t, err)
	require.Contains(t, out, "Welcome to nginx")
}
```

**Comment by jedevc** [comment]
It's weird, because I definitely would've expected this to continue to fail.

**Comment by jedevc** [comment]
> specifically in such a way that we don't actually update the state of the service to be "not running".

This is changed in #6354 - so maybe it's that

**Comment by vito** [comment]
> This is changed in #6354 - so maybe it's that

Yep that seems to be the case - specifically we now call `stop` on the services tracker which deletes it from the maps :tada: 

https://github.com/dagger/dagger/pull/6354/files#diff-1ebb5e1bc419d06e30aafaf4b05f75270d16d82924c0afc6b8a2f3332d4bcd92R330

**Comment by jedevc** [comment]
The timing still seems wrong, when closing a client, we shouldn't close all the services on that server IMO. So it no longer gets left in an invalid state - but I think what happens is we spin up the service, then stop it, and then start it again.

**Comment by vito** [comment]
Oh true. I should not declare victory while bleary-eyed.

This is tricky because the intent behind the shutdown is for it to happen synchronously as the client goes away so we don't see any services left in a running state from the event logs (e.g. in Cloud cc @marcosnils).

**Comment by jedevc** [comment]
Perhaps we could do a detach like behavior? Although I really wanted to avoid the last client from blocking on it, since that made the code so much neater (I guess there are legitimate reasons to do this though).

**Comment by nipuna-perera** [comment]
I get a similar error even without calling `sync()`. Basically trying to attach a docker daemon as a sidecar. Similar to this - https://github.com/kpenfound/dagger-modules/blob/main/dockerd/main.go

**Comment by sipsma** [comment]
Yeah @jedevc after running again w/ your fix I can't repro with Kyle's voting app example anymore either 🎉

To address the remaining weirdness around stopping too often, could we:
1. Detach from services on `StopClientServices` when it's coming from a non-main-caller (i.e. a module function call)
2. Force stop when the main client caller stops
?

**Comment by jedevc** [comment]
Yah, either of those options sound totally reasonable :tada: I'll happily pick this up, rework my test to detect the multiple stop case, and try and find a fix.

(re-assigning to myself, but if you still want it @sipsma, feel free to steal it back :laughing:)

**Comment by sipsma** [comment]
To clarify, I meant that we'd do *both* of those (detach when non-main-caller, force stop when main caller). But yes sounds good on you taking it from here, bandwidth is at a premium right now :-) thank you!

**Comment by kpenfound** [comment]
Confirmed things are working for my case in 0.9.8!

**Comment by vito** [comment]
Sneaking this into v0.10.x just as a way to not forget about it - seems like we still need to figure this out, since it's _kinda_ working but super janky that it restarts services, which is hard to notice
