### ISSUE TITLE
🐞 Logs are duplicated when a vertex is used multiple times

### ISSUE THREAD

**Issue by vito** [dagger/dagger#6501]
### What is the issue?

This issue is only on `main`; the current release, v0.9.7, is not affected.

If you run a pipeline with a vertex that is used multiple times in the same session, the log output will be duplicated, possibly with each extra use (i.e. cache hit).

### Dagger version

main

### Steps to reproduce

Once #6456 is merged, run a function that calls another function twice; you should see duplicate logs in its `codegen` vertex.

### Log output

`main`:

![image](https://uploads.linear.app/0b2a9228-3827-45ff-bb20-ccd34f57f694/3f8aa9f9-2a55-464f-88fa-b720b81b0243/5b2f333b-937b-4f83-9c32-498524dd1c66?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzBiMmE5MjI4LTM4MjctNDVmZi1iYjIwLWNjZDM0ZjU3ZjY5NC8zZjhhYTlmOS0yYTU1LTQ2NGYtODhmYS1iNzIwYjgxYjAyNDMvNWIyZjMzM2ItOTM3Yi00ZjgzLTljMzItNDk4NTI0ZGQxYzY2IiwiaWF0IjoxNzA2MjM3NTE0LCJleHAiOjMzMjc2Nzk3NTE0fQ.7DzuNYrqSTg645n0iILYM_7rx7FVC_CjoPN0saIQre8)

`v0.9.7`:

![image](https://uploads.linear.app/0b2a9228-3827-45ff-bb20-ccd34f57f694/1286bdec-e70a-46a3-858a-356ebfa69020/513d034f-3b15-4555-b767-23dde6f09f06?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzBiMmE5MjI4LTM4MjctNDVmZi1iYjIwLWNjZDM0ZjU3ZjY5NC8xMjg2YmRlYy1lNzBhLTQ2YTMtODU4YS0zNTZlYmZhNjkwMjAvNTEzZDAzNGYtM2IxNS00NTU1LWI3NjctMjNkZGU2ZjA5ZjA2IiwiaWF0IjoxNzA2MjM3NTE0LCJleHAiOjMzMjc2Nzk3NTE0fQ.-jrW8WycCYXyQsjxVMjHHXYdQ8HD_wD-_cKwYIPgWXc)

**Comment by jedevc** [comment]
Note: you don't actually need to call the function twice.

The issue comes from calling the module codegen twice (the request is properly de-duped) - but the edge merge occurs, because the parent client ids are different between the calls. See #6505 for more info.
