### ISSUE TITLE
✨ CLI: Don't show functions that can't be called

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#6608]
### What are you trying to do?

I'm writing a module that exposes a function with complex arguments which are not currently supported via the `dagger call` command. I would really like that function not to be callable or displayed in the `dagger functions` given that it's only intended to use via an SDK and not the CLI.

### Why is this important to you?

To provide a clearer API to my module users.

**Comment by sipsma** [comment]
I'll tentatively add to v0.10 milestone since I think it's likely pretty trivial implement and imo makes perfect sense to do
