### ISSUE TITLE
🐞 Typescript module dependency not included in dagger.gen.go

### ISSUE THREAD

**Issue by kpenfound** [dagger/dagger#6624]
This is happening on main, but not on version 0.9.8

Repro: 

```sh
git clone -b daggerize https://github.com/kpenfound/example-voting-app
cd example-voting-app
dagger functions
```

The module has 4 local module dependencies and 1 remote. Of the local dependencies, there are 2 Go modules (Seed, Worker), 1 Python module (Vote), and 1 Typescript module (Result).

The codegen is not including Result for some reason, and any call results in:
`dag.Result undefined (type *Client has no field or method Result)`

**Comment by sipsma** [comment]
@kpenfound I think there may have just been a backwards incompatible change in the TS sdk, this fixes it for me:
```diff
diff --git a/ci/result/src/index.ts b/ci/result/src/index.ts
index 1ceea51..19cf8ce 100644
--- a/ci/result/src/index.ts
+++ b/ci/result/src/index.ts
@@ -1,37 +1,56 @@
import { dag, Container, Directory, object, func } from "@dagger.io/dagger"
 
-@object
+@object()
 // eslint-disable-next-line @typescript-eslint/no-unused-vars
 class Result {
-
-  @func
+  @func()
   build(directory: Directory): Container {
     return dag
       .container()
       .from("node:18-slim")
       .withExec(["apt-get", "update"])
       .withExec(["apt-get", "install", "-y", "--no-install-recommends", "curl", "tini"])
       .withExec(["rm", "-rf", "/var/lib/apt/lists/*"])
       .withWorkdir("/usr/local/app")
       .withFile("/usr/local/app/package.json", directory.file("package.json"))
       .withFile("/usr/local/app/package-lock.json", directory.file("package-lock.json"))
       .withExec(["npm", "ci"])
       .withExec(["npm", "cache", "clean", "--force"])
       .withExec(["mv", "/usr/local/app/node_modules", "/node_modules"])
       .withDirectory("/usr/local/app", directory)
   }
 
-  @func
+  @func()
   serve(dir: Directory, db: Service): Service {
     return dag
       .container()
       .from("node:18-slim")
       .withExec(["apt-get", "update"])
       .withExec(["apt-get", "install", "-y", "--no-install-recommends", "curl", "tini"])
       .withExec(["rm", "-rf", "/var/lib/apt/lists/*"])
       .withWorkdir("/usr/local/app")
       .withFile("/usr/local/app/package.json", dir.file("package.json"))
       .withFile("/usr/local/app/package-lock.json", dir.file("package-lock.json"))
       .withExec(["npm", "ci"])
       .withExec(["npm", "cache", "clean", "--force"])
       .withExec(["mv", "/usr/local/app/node_modules", "/node_modules"])
@@ -41,6 +60,6 @@ class Result {
       .withServiceBinding("db", db)
       .withEntrypoint(["/usr/bin/tini", "--"])
       .withExec(["node", "server.js"])
       .asService()
   }
 }
```

@TomChv just want confirm this was a known breaking change

I think it would be good if in this situation the TS SDK failed, right now it seems like it may just end up not registering any types?

**Comment by kpenfound** [comment]
Nice find @sipsma !

> right now it seems like it may just end up not registering any types

That makes sense with how it's presenting

> I think it would be good if in this situation the TS SDK failed

agree

**Comment by kpenfound** [comment]
> I think it would be good if in this situation the TS SDK failed

This is probably the issue at it's core https://github.com/dagger/dagger/issues/6621

**Comment by sipsma** [comment]
> This is probably the issue at it's core https://github.com/dagger/dagger/issues/6621

Possibly, but in that issue there actually is an object being found (i.e. `dag.Result`), whereas in this case there's just nothing.

**Comment by TomChv** [comment]
> @TomChv just want confirm this was a known breaking change

Yes it is 👍

**Comment by TomChv** [comment]
I'm going to handle this issue by throwing an error if nothing has been registered after a scan.
