### ISSUE TITLE
Zenith: `exclude` and `include` paths in `dagger.json` should be relative to `source`

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#6628]
Since "root" is no longer sent, exclude/include patterns only take meaning from "source" directory. Otherwise you need to repeat the subdir in the patterns if you want to target something at the root of that dir, for example:

```json
{
  "name": "python-sdk-dev",
  "sdk": "python",
  "source": "dev",
  "exclude": [
    "dev/sdk"
  ]
}
```

**Comment by helderco** [comment]
Wasn't obvious to me that these paths are being prefixed with path from context dir to root dir: `(exclude: sdk/python/dev/sdk)`.

**Comment by sipsma** [comment]
My general rule of thumb has been to make all paths in dagger.json relative the directory containing dagger.json. It just seemed like the simplest approach (for both user and implementor) even if it does result in some extra boilerplate.

There is btw technically utility in using include/exclude for paths outside the module source dir. eg say I am using a go.mod from a parent dir that has a replace to other local paths or is using embed or something like that. The engine isn't smart enough to detect all that and include it so we need users to tell us in those special cases.
