### ISSUE TITLE
`slice bounds out of range [1:0]` panic in shim secret scrubbing

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#6630]
Hit this while testing publish things in my fork: https://github.com/sipsma/dagger/actions/runs/7837271347/job/21386972933#step:4:2866

Stack:
```
62: [0.09s] panic: runtime error: slice bounds out of range [1:0] goroutine 1 [running, locked to thread]:
62: [0.09s] runtime/debug.Stack()
62: [0.09s] 	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
62: [0.09s] main.main.func1()
62: [0.09s] 	/app/cmd/shim/main.go:63 +0x38
62: [0.09s] panic({0x1105620?, 0xc000044c78?})
62: [0.09s] 	/usr/local/go/src/runtime/panic.go:914 +0x21f
62: [0.09s] main.(*Trie).Insert(0xc00008b020?, {0xc0001a2b90, 0x4e, 0x50}, {0x1b18a8e, 0x3, 0x3})
62: [0.09s] 	/app/cmd/shim/secret_scrub.go:230 +0x351
62: [0.09s] main.NewSecretScrubReader({0x13307a0?, 0xc000126938}, {0x1329160, 0x1}, {0x1330820, 0xc0005a2780}, {0xc0003a28c0?, 0x2?, 0x2?}, {{0xc0005b7500, ...}, ...})
62: [0.09s] 	/app/cmd/shim/secret_scrub.go:39 +0x345
62: [0.09s] main.shim()
62: [0.09s] 	/app/cmd/shim/main.go:259 +0xc52
62: [0.09s] main.main()
62: [0.09s] 	/app/cmd/shim/main.go:76 +0x74
62: [0.09s] 
```

[Relevant line of code](https://github.com/sipsma/dagger/blob/d71867c127f6970113221c57fc03d2c8084b6c0a/cmd/shim/secret_scrub.go#L230-L230)

Not 100% sure but suspect I may have somehow set a secret value to `""`? That seems like a plausible explanation, but haven't looked at this in depth.

cc @jedevc

**Comment by sipsma** [comment]
I actually was blocked by this pretty hard while testing publish in my fork, so I ended up verifying that there weren't any empty secrets (and the shim actually handles that case anyways). So I'm not sure precisely what triggered this anymore...

I did manage to work around it with this:
```diff
diff --git a/cmd/shim/secret_scrub.go b/cmd/shim/secret_scrub.go
index d7f8f8ded..b88a69a73 100644
--- a/cmd/shim/secret_scrub.go
+++ b/cmd/shim/secret_scrub.go
@@ -215,7 +215,7 @@ func (t *Trie) Insert(key []byte, value []byte) {
        node := t
        for i, ch := range key {
                if node.Children == nil {
-                       if node.Direct == nil {
+                       if len(node.Direct) == 0 {
                                node.Direct = key[i:]
                                break
                        }
```

Though in order to actually use the shim with that updated code I needed to build the dev engine w/ the stable engine and then execute in *there*, so technically changed a lot of other variables in that process too...

**Comment by jedevc** [comment]
Wrote a test to repro this:

```go
func TestTrieExtend(t *testing.T) {
	trie := Trie{}

	trie.Insert([]byte("foo"), []byte("bar"))
	trie.Insert([]byte("foob"), []byte("bax"))
	require.Equal(t, []byte("bar"), trie.Step('f').Step('o').Step('o').Value())
	require.Equal(t, []byte("bax"), trie.Step('f').Step('o').Step('o').Step('b').Value())
}
```

Not a release blocker, since this has been around for a while, but will make this top-priority!
