### ISSUE TITLE
CLI: `dagger functions` should work after `init` and `install` of one or more modules.

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#6644]
I'm surprised I can't do this flow for installing a bunch of modules and then seeing what functions I could run from CLI with dagger functions:
1) `dagger init`
2) `dagger install <cool modules>`
3) `dagger functions` # to see what I've got to play with...
4) `dagger call <cool function>`

Step 3 `dagger functions` throws error:

`Error: input: resolve: moduleSource: resolveFromCaller: asModule: initialize: module name and SDK must be set`

Figure we need to make that flow work or provide another way to get list of functions available from installed modules since dagger call --help will give help for dagger call and won't give function names.

**Comment by helderco** [comment]
You need to specify which module to run, you won't get all at the same time.

When you install a dependency it'll create a name for it, so you just use that:
```console
❯ dagger init
❯ dagger install github.com/.../foo
❯ cat dagger.json
{
  "name": "mydir",
  "dependencies": [
    {
      "name": "foo",
      "source": "github.com/.../foo"
    }
  ]
}
❯ dagger -m foo functions
```

If you don't provide `-m`, it'll assume `source` for current `dagger.json`, not dependencies.
