### ISSUE TITLE
Generated gitattributes should be generated in module source, not module root 

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#6654]
If I have a module with a `source` key set to a `./ci`, when I run `dagger develop`, I expect that the generated `.gitattributes` file should be generated into `./ci`, and not at the top-level where my `dagger.json` is.

Alternatively, if we do decide that the top-level *is* the right place to put it, then the file should contain the right paths. Today, it looks something like:

```
/dagger.gen.go linguist-generated
/querybuilder/** linguist-generated
```

Even though `dagger.gen.go` and `querybuilder` are not in `/`, but in `/ci`.

**Comment by helderco** [comment]
Duplicate of #6625
