### ISSUE TITLE
Cannot have utils sub-package with Go Modules SDK

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#6661]
I want to have a module with a directory structure like this:

```
dagger
├── dagger.gen.go
├── go.mod
├── go.sum
├── main.go
├── querybuilder
│   ├── marshal.go
│   └── querybuilder.go
└── util
    ├── engine.go
    ├── generated.go
    └── util.go

3 directories, 9 files
```

Essentially, I want a custom `util` directory with some helpers. However, if these utils require accessing dagger types like `Client` or `Container`, then there's no way of expressing this.

The types are defined in `dagger.gen.go`, but I don't have access to them in `util` - I can't import the top-level module (since then that would create a circular dependency).

I think the correct fix for this is to move `dagger.gen.go` into a sub-directory (oh joy, this again), and then to alias the types at the top level. When doing this previously, I have a pretty strong memory of interfaces + `Optional` causing an issue (but maybe, since we've removed it in #6612, it might be possible to do this now).

**Comment by jedevc** [comment]
As a workaround, I can create a sub-module - but ideally, I don't really want to *have* to do this.

**Comment by helderco** [comment]
I'm running into the same issue.
