### ISSUE TITLE
Create LICENSE on `dagger develop`, not `dagger init`

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#6666]
## Problem

When I run `dagger init`, only 2 files are created: `dagger.json`, and `LICENSE`. Since there is no code, creating a LICENSE doesn't make sense.

Conversely, when I call `dagger develop`, no LICENSE file is created, even though new code is generated.

## Solution

Move the LICENSE file creation to `dagger develop` instead of `dagger init`.

**Comment by nipuna-perera** [comment]
To add to this, I would like to request a way to _not_ create the LICENSE. I find myself deleting it all the time as it doesn't make sense for our internal daggerverse modules.

**Comment by vito** [comment]
@nipuna-perera Easiest option is probably to just create a LICENSE file in the root of the repo (it can just be empty). The CLI will search upward, find it, and skip creating a LICENSE of its own.

**Comment by nipuna-perera** [comment]
> @nipuna-perera Easiest option is probably to just create a LICENSE file in the root of the repo (it can just be empty). The CLI will search upward, find it, and skip creating a LICENSE of its own.

I haven't tried that yet. Let me try that.

**Comment by helderco** [comment]
Yes. Similarly to https://github.com/dagger/dagger/issues/7065, should depend on whether `--sdk` is used or not.
