### ISSUE TITLE
🐞 installed module is unusable (codegen'd with wrong capitalization)

### ISSUE THREAD

**Issue by samalba** [dagger/dagger#6669]
### What is the issue?

Created module for running remote commands via SSH https://daggerverse.dev/mod/github.com/samalba/dagger-modules/ssh@35ed3e343d7e6faa3eab44570ee7531914dd4e65

I initialized the module with:
`dagger init --name ssh --sdk go --source .`

The module code uses a struct named `Ssh`. It works fine as standalone. However when you install the module from another module, it's available via `dag.SSH()` (different capitalization), which then fails to compile, because it cannot find the module version.

Simple way to reproduce: install the module from any other module and try to use it.

### Dagger version

dagger v0.9.10 (registry.dagger.io/engine) darwin/arm64

**Comment by samalba** [comment]
I think I found the root cause. We call a different code path when generating the module on creation and when calling the codegen after installing a module dependency:

When running the codegen, all names go through the function: `formatName` https://github.com/dagger/dagger/blob/fca9e788f6d605ef9d256beace4656c11d7f6fe5/cmd/codegen/generator/go/templates/functions.go#L131 (which keeps SSH capitalized): https://github.com/dagger/dagger/blob/fca9e788f6d605ef9d256beace4656c11d7f6fe5/cmd/codegen/generator/go/templates/lint_name.go#L105 (along some other names).

However, when initializing the module: we simply capitalize the struct name: https://github.com/dagger/dagger/blob/fca9e788f6d605ef9d256beace4656c11d7f6fe5/cmd/codegen/generator/go/generator.go#L318
We should expose `formatName` so we call it when scaffolding the module as well.

In the meantime, the best workaround seems to edit the module generated code in the first `main.go` to manually map to the output of the codegen.

**Comment by jedevc** [comment]
With the instructions above, managed to get a repro as an integration test:

```go
func TestModuleGoNameCase(t *testing.T) {
        t.Parallel()

        c, ctx := connect(t)

        ctr := c.Container().From(golangImage).
                WithMountedFile(testCLIBinPath, daggerCliFile(t, c))

        ctr = ctr.
                WithWorkdir("/toplevel/ssh").
                With(daggerExec("init", "--name=ssh", "--sdk=go", "--source=.")).
                WithNewFile("main.go", dagger.ContainerWithNewFileOpts{
                        Contents: `package main

type Ssh struct {}

func (ssh *Ssh) SayHello() string {
        return "hello!"
}
`,
                })
        out, err := ctr.With(daggerQuery(`{ssh{sayHello}}`)).Stdout(ctx)
        require.NoError(t, err)
        require.JSONEq(t, `{"ssh":{"sayHello":"hello!"}}`, out)

        ctr = ctr.
                WithWorkdir("/toplevel").
                With(daggerExec("init", "--name=toplevel", "--sdk=go", "--source=.")).
                With(daggerExec("install", "./ssh")).
                WithNewFile("main.go", dagger.ContainerWithNewFileOpts{
                        Contents: `package main

import "context"

type Toplevel struct {}

func (t *Toplevel) SayHello(ctx context.Context) (string, error) {
        return dag.SSH().SayHello(ctx)
}
`,
                })

        out, err = ctr.With(daggerQuery(`{toplevel{sayHello}}`)).Stdout(ctx)
        require.NoError(t, err)
        require.JSONEq(t, `{"toplevel":{"sayHello":"hello!"}}`, out)
}
```

When running the test, I get:

```
        	            	Stderr:
        	            	# main
        	            	./dagger.gen.go:5694:35: undefined: SshID
        	            	./dagger.gen.go:6206:12: undefined: SshID
        	            	./dagger.gen.go:6211:40: undefined: SshID
        	            	./dagger.gen.go:6217:15: undefined: SshID
        	Test:       	TestModuleGoNameCase
```

@samalba does that look like the error you saw? Definitely looks like a capitalization error to me.

**Comment by samalba** [comment]
Yes it looks like it indeed
