### ISSUE TITLE
`TestModuleCodegenOnDepChange` is flaky

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#6770]
See https://github.com/dagger/dagger/actions/runs/8075163921/job/22061629460?pr=6765 (in dagger cloud: https://dagger.cloud/dagger/runs/5a27b0b5-cf3a-4d29-b357-0ca9cfa946ff)

We get this utterly incomprehensible error message:

```
1179    multi.go:85: [35m59:[0m exec dagger --debug develop [32mDONE[0m
1180    module_test.go:3432: 
1181        	Error Trace:	/app/core/integration/module_test.go:3432
1182        	Error:      	
1183        	Test:       	TestModuleCodegenOnDepChange/python_uses_go
1184    suite_test.go:271: 
1185--- FAIL: TestModuleCodegenOnDepChange/python_uses_go (28.70s)
```

I've *also* seen an error message that looks like `... does not contain "Hellov2`, but I now cannot find an instance of this (but will link it here when I find one).

The test itself shouldn't be flaky - it looks good to me. I *really* have no idea how it's possible to get an empty `Error` string here - it requires passing an empty string to `assert.Fail`, which in this test would be something internal? That seems unlikely, but the only option I can think of is that maybe the error is somehow changed internally after returning it?

---

Another thing I've noted that might be interesting here @sipsma - I notice that our logs are full of `upload /work from buildkitsandbox`. The change in https://github.com/dagger/dagger/pull/6469#discussion_r1482772229 now means that all of these potentially collide and write to the same `LocalSource` snapshot. The timeline of this *might* make sense based on when I've started to see it more.

I think it might make sense to potentially set the hostname for `WithExec` to something instead of the default `buildkitsandbox`, and it might be nice if that was somehow potentially randomized (maybe it should be the client id? of course we can't do this, because that would break cache, yay).

**Comment by jedevc** [comment]
Another strange variant on this: https://github.com/dagger/dagger/actions/runs/8154660264/job/22288549128?pr=6822

```
    multi.go:85: [35m713:[0m exec tsx --no-deprecation --tsconfig /src/dagger/tsconfig.json /src/dagger/src/__dagger.entrypoint.ts [31mERROR: process "tsx --no-deprecation --tsconfig /src/dagger/tsconfig.json /src/dagger/src/__dagger.entrypoint.ts" did not complete successfully: exit code: 1[0m
    multi.go:85: [35m713:[0m [2.61s] TypeError: import_dagger.dag.dep(...).hello is not a function
    multi.go:85: [35m713:[0m exec tsx --no-deprecation --tsconfig /src/dagger/tsconfig.json /src/dagger/src/__dagger.entrypoint.ts [31mERROR: process "tsx --no-deprecation --tsconfig /src/dagger/tsconfig.json /src/dagger/src/__dagger.entrypoint.ts" did not complete successfully: exit code: 1[0m
    multi.go:85: 
    multi.go:85: [35m491:[0m exec dagger --debug query
    multi.go:85: [35m491:[0m [17.4s] [35m1:[0m dagger query [31mERROR: make request: input: use.useHello call function "useHello": process "tsx --no-deprecation --tsconfig /src/dagger/tsconfig.json /src/dagger/src/__dagger.entrypoint.ts" did not complete successfully: exit code: 1
    multi.go:85: [35m491:[0m [17.4s] [0m
    multi.go:85: [35m491:[0m [17.4s] 
    multi.go:85: [35m491:[0m [17.4s] 
    multi.go:85: [35m491:[0m [17.4s] Error: make request: input: use.useHello call function "useHello": process "tsx --no-deprecation --tsconfig /src/dagger/tsconfig.json /src/dagger/src/__dagger.entrypoint.ts" did not complete successfully: exit code: 1
    multi.go:85: [35m491:[0m [17.4s] 
    multi.go:85: [35m491:[0m exec dagger --debug query [31mERROR: process "dagger --debug query" did not complete successfully: exit code: 1[0m
    module_test.go:3552: 
        	Error Trace:	/app/core/integration/module_test.go:3552
        	Error:      	Received unexpected error:
        	            	input: container.from.withExec.withExec.withExec.withMountedFile.withWorkdir.withExec.withMountedFile.withWorkdir.withExec.withNewFile.withWorkdir.withExec.withNewFile.withExec.withExec.withWorkdir.withNewFile.withWorkdir.withExec.withExec.stdout process "dagger --debug query" did not complete successfully: exit code: 1
        	            	
        	            	Stderr:
        	            	[35m1:[0m dagger query
        	            	[35m1:[0m dagger query [31mERROR: make request: input: use.useHello call function "useHello": process "tsx --no-deprecation --tsconfig /src/dagger/tsconfig.json /src/dagger/src/__dagger.entrypoint.ts" did not complete successfully: exit code: 1
        	            	[0m
        	            	
        	            	
        	            	Error: make request: input: use.useHello call function "useHello": process "tsx --no-deprecation --tsconfig /src/dagger/tsconfig.json /src/dagger/src/__dagger.entrypoint.ts" did not complete successfully: exit code: 1
        	Test:       	TestModuleSyncDeps/typescript_uses_go
    suite_test.go:271: 
--- FAIL: TestModuleSyncDeps/typescript_uses_go (61.75s)
```

The key issue being `TypeError: import_dagger.dag.dep(...).hello is not a function`. Something is weird here, how can this possibly flake?

**Comment by TomChv** [comment]
Not directly related to TS, I removed the label

**Comment by helderco** [comment]
Is this still true?

**Comment by jedevc** [comment]
Good question :laughing: No idea honestly, we've had so many *other* flakes lately, I'm not sure.

I'll keep an eye on this one, and if I don't see it, I'll close it out :tada:

**Comment by jedevc** [comment]
We don't seem to see this anymore, closing. :tada:
