### ISSUE TITLE
🐞 v0.10.1 Client panic when with Pipeline

### ISSUE THREAD

**Issue by morlay** [dagger/dagger#6850]
### What is the issue?

The generated code missing the  private `graphql.Client`

https://github.com/dagger/dagger/blob/v0.10.1/sdk/go/dagger.gen.go#L5580-L5597

https://github.com/dagger/dagger/blob/v0.10.0/sdk/go/dagger.gen.go#L5745-L5763

### Dagger version

v0.10.1

**Comment by jedevc** [comment]
You can use `client.GraphQLClient` to get this. Exposing `Client` directly through all objects was not intentional, and was a regression introduced in https://github.com/dagger/dagger/pull/6680, and resolved in https://github.com/dagger/dagger/pull/6716.

**Comment by jedevc** [comment]
Unless you're seeing an internal panic somewhere, in which case, could you provide a stack trace?
