### ISSUE TITLE
🐞 `dagger develop` should fail if no `dagger.json` is found

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#6856]
### What is the issue?

Some users have reported some issues while getting started with dagger about `dagger develop` not apparently working as expected. In most of those cases we found out that they didn't run `dagger init` before calling `dagger develop` which yielded to some unexpected results. 

@shykes suggested (https://discord.com/channels/707636530424053791/1215438073694003300/1215471630630002818)  making `dagger develop` to fail if no `dagger.json` is found  which seems reasonable

ref: https://discord.com/channels/707636530424053791/1215438073694003300/1215438073694003300
ref: https://discord.com/channels/707636530424053791/1215318377329983519

### Dagger version

v0.10.1

**Comment by helderco** [comment]
It seems like this was added in https://github.com/dagger/dagger/pull/6386 a while ago (in v0.9.8), so asking for more info.

In an empty directory, if I do `dagger develop --sdk=go`:
```
Error: failed to get configured module: no dagger.json found in directory . or any parents up to git root
```

- In the first discord ref, it seems the user did have a `dagger.json`, but doesn't know how it got there.
- In the second discord ref, it seems the user used `develop` (albeit without `init` first) but didn't do what they thought so they created the `.py` file manually and go confused on `dagger call`.

There's some polish planned for `init`/`develop` so I want to take a general look in the _develop_ flags in relation to the usage of those commands, but that's a matter for another issue.

<details><summary>Polish</summary>

For example:
- https://github.com/dagger/dagger/issues/7065
- https://github.com/dagger/dagger/issues/6666

There's been discussions for not not using `--sdk` in `init`, but that would require two commands `dagger init && dagger develop --sdk=...` when you want to generate code for authoring so it's been decided to leave the `init` convenience so far.

We could also have `develop` do the `init` automatically if there's no `dagger.json`, but that can also be confusing. In that case you'd use `dagger develop --sdk` to author, or `dagger init` just for dependencies.

It would be less confusing to split, but frequent users like the `init` convenience.

</details>
