### ISSUE TITLE
Codegen: Functions that return the Void type should generate a client that only returns an error

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#6868]
## Summary

Return only error and no value if return type for a function is `Void`.

## Motivation

It makes no sense for the client to capture a `Void` value as it's specifically meant for side-effects only. It has no meaning as a value. If you have the following function:

```go
func (m *MyModule) Deploy() error {
    // do something that may return an error
}
```

This should produce the following schema:

```graphql
type MyModule {
    deploy: Void
}
```

But codegen forces you to use it like this:

```go
_, err := dag.MyModule().Deploy(ctx)
```

There's no use case for handling that value, so it should just be:

```go
err := dag.MyModule().Deploy(ctx)
```

## Compatibility

The downside is it's a breaking change in Go. A function that previously returns 2 values would now return only 1, and there's no clear compatible deprecation path. But we can at least add this to the "bucket list" and decide when it's a good time to introduce.

In Python or TypeScript, there's no breaking change since errors are exceptions. Even if a function doesn't return anything, it implicitly returns `None` (in Python):

```python
def test(): ... # no return
out = test() # out has the value `None`
```

Or `undefined` (in TypeScript):

```typescript
function test() {}  // no return
out = test()        // out has the value `undefined`
```

**Comment by jedevc** [comment]
@helderco WDYT about having this as v0.12.0?

We're starting to accumulate a few API breaking changes, so with this one, and the others here: https://github.com/dagger/dagger/issues?q=is%3Aopen+label%3A%22breaking+change%22+sort%3Aupdated-desc

It feels like with all of these pending, we're starting to accumulate things that would be good for v0.12, maybe thinking a timeline of in the next couple months?

One possibility for all these btw, we could use the `dagger.json` `engineVersion` field, and use this for codegen for that module, so that we wouldn't necessarily break all of the daggerverse with all these changes.

**Comment by helderco** [comment]
> @helderco WDYT about having this as v0.12.0?

Yep, that's my plan!

> One possibility for all these btw, we could use the `dagger.json` `engineVersion` field, and use this for codegen for that module, so that we wouldn't necessarily break all of the daggerverse with all these changes.

That's an interesting idea, I've actually been thinking about custom adjustments to codegen as part of a smoother deprecation path.

But definitely need deprecations warnings as well:
- https://github.com/dagger/dagger/issues/4855

We could even print warnings for changes you can do today to avoid a breaking change in the future.

**Comment by jedevc** [comment]
> But definitely need deprecation warnings as well

Agreed :tada:

Some of the changes can't be deprecated super easily yet, like the change for number of returned arguments (in go, this breaks every call, I'm not sure if there's a nice path to take for this).

To me, the big deprecations warning question is how we display these - putting these as spans for telemetry doesn't feel right. Maybe using something like `slog` from the client, like how we do for certain infos/warnings. Would they display on every build? Would we want them in cloud? Or in daggerverse? etc.

**Comment by helderco** [comment]
> To me, the big deprecations warning question is how we display these - putting these as spans for telemetry doesn't feel right. Maybe using something like `slog` from the client, like how we do for certain infos/warnings. Would they display on every build? Would we want them in cloud? Or in daggerverse? etc.

I imagine that the following line:

https://github.com/dagger/dagger/pull/7136/files#diff-89b0b6c38f29bb6615327b6126c2479d29b032ef974017a9358c0c0721fa17f9R582

Would print the warning to the TUI under its parent span, but disappear in the end when the span successfully completes, unless you add `-vv` (or `-vvv`).

Showing in cloud, wouldn't require any change, just need to integrate OpenTelemetry logging like @vito explains in https://github.com/dagger/dagger/issues/4855#issuecomment-2098721537.

**Comment by wingyplus** [comment]
It means that we can imply Void type to `void` for some languages like java or c#?

**Comment by helderco** [comment]
Yes, you can se TypeScript's example in:
- https://github.com/dagger/dagger/pull/7773
