### ISSUE TITLE
Create map of containers from docker compose files

### ISSUE THREAD

**Issue by rucciva** [dagger/dagger#6886]
### What are you trying to do?

Load docker compose files (just like how dagger can load Dockerfile) and automatically generate map of containers accordingly with docker compose service name as key. Any unsupported setting defined inside docker compose can be ignored.

### Why is this important to you?

I've been using dagger for a while and it's great for running ci/cd pipeline across machines. But i still feel that it hards to replace the simplicity of docker compose when used to run dependencies for development or debugging. So currently, there is a manual process of defining the same things twice inside dagger and docker-compose.

### How are you currently working around this?

A lot of copy paste and manual sync of container settings inside dagger script and docker composw files

**Comment by helderco** [comment]
This is good as a module. See these:
- [github.com/shykes/daggerverse/docker-compose](https://daggerverse.dev/mod/github.com/shykes/daggerverse/docker-compose@c448f929b53be0f09eafe884cc77612a6d6fc7f9)
- [github.com/vito/daggerverse/docker](https://daggerverse.dev/mod/github.com/vito/daggerverse/docker@9f66a3dc5a3687c0828e2499894a51315f998b5c)

They could be merged into one, and you can contribute to either one as they're open source, or just fork.

@shykes also has an interesting idea of making a custom SDK for docker compose. So you could init a module like this:

```
dagger init --sdk=github.com/acme/compose-sdk django
```

Creating the following file file structure:

```
django
├── dagger
│  └── compose.yml
└── dagger.json
```

Then you’d be able to see and call the services as functions:

```
$ dagger functions
Name         Description
app          -
db           -
$ dagger call app ...
```

And you'd be able to reuse one of those containers in another module as well:

```go
ctr := dag.Django().App()
```

**Comment by rucciva** [comment]
Ah i see. Thanks @helderco.
