### ISSUE TITLE
✨ Remove restriction on dagger modules only being allowed on GitHub

### ISSUE THREAD

**Issue by purpleclay** [dagger/dagger#6890]
### What are you trying to do?

I want to be able to publish a Dagger module to an SCM other than GitHub, especially as I work with organisations that use GitLab and self-hosted instances. I like the look of Dagger and can see its benefits. Running CI locally is a game changer, but GitHub isn't always an option.

### Why is this important to you?

It provides more freedom regarding where you publish your Dagger modules, greatly increasing Dagger's usability. It also enables other platforms like GitLab and the option of self-hosted SCMs.

### How are you currently working around this?

There is no workaround if your organisation uses an alternative SCM to GitHub. Ultimately, Dagger is off the table.

**Comment by gerhard** [comment]
cc @jpadams @marcosnils @grouville @vito

**Comment by purpleclay** [comment]
I have raised a DRAFT merge request as a first attempt and would love feedback.
