### ISSUE TITLE
Add `Directory.WithoutDirectory` method

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#6898]
Today, we can merge directories using `Directory.WithDirectory` - however, there's no corresponding `WithoutDirectory` method, like we have on `Container`.

This is slightly frustrating - imagine the following use case (cc @slumbering):

```go
func (m *MyModule) DoThing(src *Directory) {
	// I want to filter src down, and remove a directory:
	src = dag.Directory().WithDirectory("/", src, DirectoryWithDirectoryOpts{
		Exclude: []string{"node_modules"},
	})

	// But, ideally I'd just like to be able to:
 	// src = src.WithoutDirectory("node_modules")

	...
}
```

cc @sipsma @helderco any ideas/objections?

**Comment by jedevc** [comment]
Ugh I need more coffee, this method exists.

**Comment by helderco** [comment]
But `Container.withoutDirectory` doesn't though.
