### ISSUE TITLE
🐞 Directory.glob doesn’t work when parent directory isn’t "."

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#6903]
I found that the [Glob](https://github.com/dagger/dagger/blob/ece26ac9c704e498fefe1a994d42740390c62018/sdk/python/runtime/discovery.go#L235) being used in [https://github.com/dagger/dagger/pull/6884](https://github.com/dagger/dagger/pull/6884) doesn’t work as expected. Also reported by user in [Discord](https://discord.com/channels/707636530424053791/1219382409016115200/1219382409016115200).

Assuming the following directory:

```python
files = dag.directory().with_new_file("foo/bar.txt", "foobar")
src = dag.directory().with_directory("wat", files)
```

Currently, this works:

```python
print(await src.glob("**/*.txt"))

# Output: ['wat/foo/bar.txt']
```

But not this:

```python
print(await src.directory("wat").glob("**/*.txt"))
 
# Error: lstat /tmp/buildkit-mount751124773/wat/wat: no such file or directory
```

**Comment by marcosnils** [comment]
> ```python
> print(await src.directory("wat").glob("**/*.txt"))
>  
> # Error: lstat /tmp/buildkit-mount751124773/wat/wat: no such file or directory
> ```

q: did you mean `directory("foo")` here?

**Comment by helderco** [comment]
> q: did you mean `directory("foo")` here? given that `/wat/wat` doesn't effectively exist.

No, see this line:
```go
src = dag.directory().with_directory("wat", files)
```

I'd expect it to find files in `/wat`, not `/wat/wat`.
