### ISSUE TITLE
Support `password: Secret` argument to `Git`

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#6913]
Related discord thread: https://discord.com/channels/707636530424053791/1220153273370280048/1220153273370280048

Some git url formats inline credentials to the URL, in which case dagger ends up printing those creds. If we instead added an arg of type Secret and then internally did the formatting for the user, we could avoid this.

I'm *guessing* it's possible to do this, it just requires that the user can leave out the creds from the URL in a reasonable way that doesn't result in some ambiguous format, but can't currently see why that would be the case.

Worst case scenario, a fallback option would be to conditionally make the URL sensitive based on whether it includes creds or not.

**Comment by helderco** [comment]
Fixed in https://github.com/dagger/dagger/pull/6992
