### ISSUE TITLE
🐞 Go SDK Code generated with dagger init is missing a .gitignore file

### ISSUE THREAD

**Issue by Transmitt0r** [dagger/dagger#6921]
### What is the issue?

Hello,
when I initialise a new dagger module and select the go sdk with `dagger init --name test --sdk=go --source .`, a `.gitattributes` file is generated but a `.gitignore` file to exclude the generated code is missing. This seems like unintended behaviour since for e.g. the python sdk, a matching `.gitignore` file is produced.

### Dagger version

dagger v0.10.2 ([registry.dagger.io/engine](http://registry.dagger.io/engine)) darwin/arm64

### Steps to reproduce

1. Run `dagger init --name ko --sdk=go --source .`
2. Run `ls -a` and see that the `.gitignore` file is missing.
3. Compare it to `dagger init --name ko --sdk=python --source .`

### Log output

```sh
➜ go-test ls -la
total 112
drwxr-xr-x 12 lukas staff 384 Mar 23 15:20 .
drwxr-xr-x@ 19 lukas staff 608 Mar 23 15:23 ..
drwxr-xr-x 9 lukas staff 288 Mar 23 15:20 .git
-rw------- 1 lukas staff 118 Mar 23 15:15 .gitattributes
-rw------- 1 lukas staff 10280 Mar 23 15:15 LICENSE
-rw------- 1 lukas staff 22287 Mar 23 15:15 dagger.gen.go
-rw-r--r-- 1 lukas staff 64 Mar 23 15:15 dagger.json
-rw------- 1 lukas staff 287 Mar 23 15:15 go.mod
-rw------- 1 lukas staff 3164 Mar 23 15:15 go.sum
drwxr-xr-x 4 lukas staff 128 Mar 23 15:15 internal
-rw------- 1 lukas staff 1305 Mar 23 15:15 main.go
```

vs.

```sh
➜  python-test ls -la
total 56
drwxr-xr-x   9 lukas  staff    288 Mar 23 15:23 .
drwxr-xr-x@ 19 lukas  staff    608 Mar 23 15:23 ..
-rw-------   1 lukas  staff     27 Mar 23 15:23 .gitattributes
-rw-------   1 lukas  staff      5 Mar 23 15:23 .gitignore
-rw-------   1 lukas  staff  10280 Mar 23 15:23 LICENSE
-rw-r--r--   1 lukas  staff     68 Mar 23 15:23 dagger.json
-rw-r--r--   1 lukas  staff     42 Mar 23 15:23 pyproject.toml
drwxr-xr-x   7 lukas  staff    224 Mar 23 15:23 sdk
drwxr-xr-x   3 lukas  staff     96 Mar 23 15:23 src
```

**Comment by jedevc** [comment]
Heya, thanks for the issue @Transmitt0r! :tada:

We've actually already fixed this in https://github.com/dagger/dagger/pull/6888 - it'll make it into the v0.10.3 release, which should be this week, so hopefully not long to wait.
