### ISSUE TITLE
CLI: don't return an error when querying an object

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#6948]
## Problem

When `dagger call` ends on an object (as opposed to a scalar value), it returns an error with a message saying "please query a field of this object".

This is a problem because:

1. At a glance, it gives the impression that the user did something wrong, when in fact they did not. So an error is sending the wrong message.
2. It makes a valid task (produce an object and look at it) harder than it should be. Just show me the object!

## Solution

1. Never show an error when a function has successfully be called, and has returned an object
2. Print the actual contents of the object, in an actual format. Ideally, the contents of all scalar fields in the object. Either in JSON, YAML or pretty-print format (configurable by a flag). Possibly excluding the ID by default (also configurable).

### On the question of "expensive scalar fields"

This discussion has been sidetracked in the past by the question of "expensive scalar fields". For example, `Container.stdout` is "expensive" because it forces actually executing a container, in order to retrieve its standard output. Therefore, it is argued, the CLI should not blindly query all scalar fields of an object, because it may cause expensive computation which the user does not want.

*This is premature optimization*. Let's ship the feature in a naive implementation; then see how important it actually is to avoid expensive computation. My guess is that, in most cases, it won't matter. For example, if I query a container, I don't care that it's actually executed.  Or, if it turns out it's a problem, then we can implement a special case in the core type. I certainly won't care if my own custom types don't benefit from such a special case.

**Comment by helderco** [comment]
The printing objects part was reported in:
- https://github.com/dagger/dagger/issues/6515

It requires a change in the query builder. It's not hard though.

**Comment by shykes** [comment]
Thanks @helderco , marking this one as duplicate of #6515
