### ISSUE TITLE
🐞 Dagger module seems not working behind coorporate proxy

### ISSUE THREAD

**Issue by disaster37** [dagger/dagger#6953]
### What is the issue?

The command to init module not working when we are behind coorporate proxy.
```bash
dagger develop --sdk=go
```

It try to access direcly on internet instead to use coorporate proxy (env http_proxy / https_proxy / no_proxy). It seems it ignore standard environment variable to drive proxy ...

### Dagger version

dagger 0.10.2

### Steps to reproduce

Set proxy with on local computer with:
  - HTTP_PROXY
  - HTTPS_PROXY
  - NO_PROXY

Set the $HOME//.docker/config.json with
```json
{
        "proxies": {
                "default": {
                        "httpProxy": "http://squid.squid.svc.cluster.local:8080",
                        "httpsProxy": "http://squid.squid.svc.cluster.local:8080",
                        "noProxy": "127.0.0.0/8, .svc, .cluster.local, 10.0.0.0/8"
                }
        }
}
```

To finish, run
```bash
dagger develop --sdk=go
```

It try to access directly on Internet instead to use proxy. I doesn't know if is the cli that access on internet or is dagger engine on this story, but is not working as expected ...

### Log output

✘ ModuleSource.asModule: Module! 39.0s
  ✘ Module.withSource(
      source: ✔ ModuleSource.resolveFromCaller: ModuleSource! 0.0s
    ): Module! 39.0s
    ✘ Container.directory(path: "/src"): Directory! 38.7s
      ✘ exec /usr/local/bin/codegen --module-context /src --module-name dagger --propagate-logs=true --introspection-json-path /schema.json 31.6s
      ┃ Error: exit status 1                                                                                                                                                
      ✘ generating go module: dagger 30.4s
      ┃ go: dagger/dagger/internal/dagger imports                                                                                                                           
      ┃         github.com/Khan/genqlient/graphql: github.com/Khan/genqlient@v0.6.0: Get "https://proxy.golang.org/github.com/%21khan/genqlient/@v/v0.6.0.zip": dial tcp 142
      ┃ .49:443: i/o timeout                                                                                                                                                
      ┃ go: dagger/dagger/internal/dagger imports                                                                                                                           
      ┃         github.com/vektah/gqlparser/v2/gqlerror: github.com/vektah/gqlparser/v2@v2.5.6: Get "https://proxy.golang.org/github.com/vektah/gqlparser/v2/@v/v2.5.6.zip":
      ┃ p 142.250.200.49:443: i/o timeout                                                                                                                                   
      ┃ go: dagger/dagger/internal/querybuilder imports                                                                                                                     
      ┃         github.com/99designs/gqlgen/graphql: github.com/99designs/gqlgen@v0.17.31: Get "https://proxy.golang.org/github.com/99designs/gqlgen/@v/v0.17.31.zip": dial 
      ┃ 250.200.49:443: i/o timeout                                                                                                                                         
      ┃ go: dagger/dagger/internal/querybuilder imports                                                                                                                     
      ┃         golang.org/x/exp/slices: golang.org/x/exp@v0.0.0-20231110203233-9a3e6036ecaa: Get "https://proxy.golang.org/golang.org/x/exp/@v/v0.0.0-20231110203233-9a3e60
      ┃ ip": dial tcp 142.250.200.49:443: i/o timeout                                                                                                                       
      ┃ go: dagger/dagger/internal/querybuilder imports                                                                                                                     
      ┃         golang.org/x/sync/errgroup: golang.org/x/sync@v0.6.0: Get "https://proxy.golang.org/golang.org/x/sync/@v/v0.6.0.zip": dial tcp 142.250.200.49:443: i/o timeo

Error: failed to generate code: input: moduleSource.withContextDirectory.withSDK.withSourceSubpath.asModule resolve: failed to create module: select: failed to update codegen and runtime: failed to generate code: failed to get modified source directory for go module sdk codegen: select: process "/usr/local/bin/codegen --module-context /src --module-name dagger --propagate-logs=true --introspection-json-path /schema.json" did not complete successfully: exit code: 1

Stderr:
Error: exit status 1

**Comment by jedevc** [comment]
Heya @disaster37! :tada: There's already an issue tracking this in https://github.com/dagger/dagger/issues/6599, along with some proposed solutions.

I'm going to close this issue as a duplicate, just so that we can track all this in one place!
