### ISSUE TITLE
Signature misalignment of Directory.with_new_file and Container.with_new_file

### ISSUE THREAD

**Issue by skycaptain** [dagger/dagger#6961]
### What is the issue?

In the Python SDK, the signatures of `Directory.with_new_file` and `Container.with_new_file` are inconsistent. For `Directory`, `contents` is a required positional argument, while for `Container`, `contents` is a keyword-only argument. This inconsistency is confusing and often requires referencing the API documentation to determine the correct usage. I vote for setting up a PR, if you could give me a hint on the preferred behaviour.

### Dagger version

dagger v0.10.2 (registry.dagger.io/engine) darwin/arm64

**Comment by helderco** [comment]
Yeah, that's a good point. I think the `Directory` version, with contents being a required argument is preferred, but it's not a Python change, it's a core API change.

**Comment by helderco** [comment]
Just to explain the reason why, we've changed `Directory` but not `Container`, because of:

* [https://github.com/dagger/dagger/issues/3884](https://github.com/dagger/dagger/issues/3884)
