### ISSUE TITLE
🐞 Optional fields from Python Module are mandatory in Go

### ISSUE THREAD

**Issue by skycaptain** [dagger/dagger#6964]
### What is the issue?

I have two modules, `ModuleA` written in Python using string fields with default values. I depend on this module in my second module `ModuleB` written in Golang. It seems that the generated code in `dagger.gen.go` in `ModuleB` does not respect the default values of the fields from `ModuleA`, and requires to set values for these fields again.

### Dagger version

dagger v0.10.2 (registry.dagger.io/engine) linux/amd64

### Steps to reproduce

I've setup https://github.com/skycaptain/dagger-issue-6964 to illustrate the issue, where this line fails: https://github.com/skycaptain/dagger-issue-6964/blob/c53a88810c6a179392731555ad81a016ba4fe602/main.go#L6

**Comment by helderco** [comment]
Yeah, I need to rethink this:
- https://github.com/dagger/dagger/issues/6749

Right now the SDKs are consistent in translating to and from GraphQL, but I need to think a bit more on cross-language DX.

What's happening is that while an argument with a default makes it optional in Python, the internal APIs that the SDKs use equate "optional" to mean "nullable". In fact, in GraphQL, a nullable field is in indeed optional, but it's also possible to have a non-null type with a default value which also makes it optional.

So when you have this:

```python
@object_type
class ModuleA:
    greeting: str = "Hello"
    name: str = "World"
```

It creates the following constructor in the schema:

```graphql
type Query {
    moduleA(greeting: String! = "Hello", name: String! = "World"): ModuleA!
}
```

And so Go is interpreting those non-null types as being required, even though they have defaults. It's equivalent to the following Go constructor:

```go
func New(
    // +default="Hello"
    greeting string,
    // +default="World"
    name string,
) *ModuleA {
}
```

To make those arguments optional, you have to add `// +optional`:

```go
func New(
    // +default="Hello"
    // +optional
    greeting string,
    // +default="World"
    // +optional
    name string,
) *ModuleA {
}
```

Which, cycling back to Python, the equivalent being:

```python
@object_type
class ModuleA:
    greeting: str | None = "Hello"
    name: str | None = "World"
```

The Go SDK’s codegen (for the client) probably needs to consider arguments with defaults to be optional, not just nullables.

But in module functions (for extending the schema), if you do the same then it wouldn’t be able to express a non-null argument with a default value. Python when through the opposite transformation [fairly recent](https://github.com/dagger/dagger/pull/6752). A `greeting: str = "Hello"` would produce `greeting: String = "Hello"` with no way to express that, and has realigned for consistency.

What I need to think a bit more is in the value and usage of nullable vs non-null values across the API and SDKs as there’s still some inconsistencies. Maybe we don’t need to express the above case in our API and we may be worse off for surprising behavior.

**Comment by helderco** [comment]
I thought this was hitting a more general problem here, but I just hit it too. There is indeed an issue with Python not declaring some arguments with defaults as being optional. I'll jump on a fix for this.

**Comment by helderco** [comment]
Update: After reaching out to the core devs, it's not intentional that null values are being ignored in the API, so we do want to represent nullable vs non-null values correctly. This is a part of:

* [https://github.com/dagger/dagger/issues/6749](https://github.com/dagger/dagger/issues/6749)

That issue splits the problem in 3 areas. This one being one of those. But there's a simple fix here for this part of it. Every codegen needs to consider both nullable and default values before considering an argument optional.

This logic will be simplified in the future with:

* [https://github.com/dagger/dagger/issues/5226](https://github.com/dagger/dagger/issues/5226)

**Comment by helderco** [comment]
Only Go needs fixing here.
