### ISSUE TITLE
Python `building Dockerfiles` link results in 404 on https://dagger.io/blog/dockerfiles-with-dagger

### ISSUE THREAD

**Issue by d33bs** [dagger/dagger#6997]
### What is the issue?

Thanks for the great work on Dagger! I noticed that the link for `building Dockerfiles` under the Python section on https://dagger.io/blog/dockerfiles-with-dagger results in a 404. The 404 link is: https://dagger-io.readthedocs.io/en/latest/api.html#dagger.api.gen.Directory.docker_build .

**Comment by levlaz** [comment]
Thanks so much for the bug report @d33bs!

@mircubed could we fix this in Framer? 

We need to replace `https://dagger-io.readthedocs.io/en/latest/api.html#dagger.api.gen.Directory.docker_build` with this link: `https://dagger-io.readthedocs.io/en/latest/client.html#dagger.Directory.docker_build`

**Comment by mircubed** [comment]
Thanks for reporting @d33bs! I have updated the blog post link, and the changes will be reflected tomorrow when we push it to production again.
