### ISSUE TITLE
Create files from template only in new modules

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#7034]
It’s surprising that you can create a module, make some functions, run them, remove `main.go` and it’ll still run, just with the default ones from the template.

Instead of stopping `dagger call` from doing codegen automatically, I think it would be more reasonable to just not use the template unless you’re using `--sdk` for a new module. So if you remove `main.go` or some other file, it errors rather than re-creating on an ephemeral container, which is more surprising.

The client will still be regenerated, just not the initial template files for modules with an existing source.

As a pre-requisite, runtime modules need to know whether they’re creating a new module or not. `dagger init --sdk` is easy to detect because `ModSource.ConfigExists(ctx)` returns false. But when adding sources through a `dagger develop --sdk`, that happens on an existing module but we can’t look for `"sdk"` field in `dagger.json` because that’s added in by the CLI before loading the module.

In Python, for example, we would look for the existence of a `pyproject.toml` file and assume it’s a new module if it doesn’t exist, but now it can be used to configure essential things like Python’s version for the runtime, which is used for the codegen’s base image.

So rather than have the SDKs try to figure it out, have the server set an `init` boolean in the constructor or call a separate `Init` function when first adding sources to a module, so it’s easy and consistent for SDKs to apply the template then.

**Comment by jedevc** [comment]
This feels a bit like https://github.com/dagger/dagger/issues/6621#issuecomment-1934787396?

**Comment by helderco** [comment]
> This feels a bit like [#6621 (comment)](https://github.com/dagger/dagger/issues/6621#issuecomment-1934787396)?

Yes, thanks!

Close as duplicate.
