### ISSUE TITLE
🐞 Daggerverse Search Does Not Support dash symbol "-" 

### ISSUE THREAD

**Issue by levlaz** [dagger/dagger#7041]
### What is the issue?

I have a module called [cloud-utils](https://daggerverse.dev/mod/github.com/levlaz/daggerverse/cloud-utils@f6152f0a9828cefdb3ec6e9b6dc9722fb70291e7) 

When I try to search for it in Daggerverse it does not show up in the results. I suspect its due to the dash in the name. 

https://daggerverse.dev/search?q=cloud-utils 

### Dagger version

n/a

**Comment by d3rp3tt3** [comment]
@grouville is working on improving search now

**Comment by grouville** [comment]
fixed ✅
