### ISSUE TITLE
Error: failed to get configured module: no dagger.json found in directory . or any parents up to git root

### ISSUE THREAD

**Issue by JCzz** [dagger/dagger#7042]
### What is the issue?

Installed dagger using "brew install dagger" on macos M1 arm64 chip.

From this: https://daggerverse.dev/mod/github.com/kpenfound/dagger-modules/golang@57352e06a1cfbcb5307c009d37c0201b2719b935

It says "dagger install github.com/kpenfound/dagger-modules/golang@57352e06a1cfbcb5307c009d37c0201b2719b935". Then I get: 
Error: failed to get configured module: no dagger.json found in directory . or any parents up to git root

### Dagger version

dagger v0.11.0 (registry.dagger.io/engine) darwin/arm64

**Comment by jedevc** [comment]
Currently, you need to be inside a dagger module to run `dagger install` - there is discussion about adding a global install in #6883, so you don't need to be in a module at all.
