### ISSUE TITLE
🖐️ How to regenerate dagger.gen.go

### ISSUE THREAD

**Issue by jkblume** [dagger/dagger#7044]
### What happened? What did you expect to happen?

I initialized my dagger module with `dagger init --name=simple-frontend --sdk=go`. Now i modified the available functions and removed the default generated ones. Now the `dagger.gen.go` contains errors, because of referencing the default functions initially generated with `dagger init` (`ContainerEcho`and `GrepDir`). What is the intended usage of the `dagger.gen.go` file. I didn't found a documented way to regenerate the file?

**Comment by vikram-dagger** [comment]
@TomChv see https://docs.dagger.io/reference/979596/cli/#dagger-develop

**Comment by jkblume** [comment]
Nice, the link really helps @vikram-dagger. IMHO this documentation is enough, it just needs to better found by search engines to point searching developers in the right direction.

**Comment by levlaz** [comment]
>  it just needs to better found by search engines to point searching developers in the right direction. 

cc @mircubed more feedback for the SEO stuff we've been talking about lately.

**Comment by TomChv** [comment]
Should we close this issue since it's only related to SEO and not an actual TS issue?
@vikram-dagger ?

**Comment by vikram-dagger** [comment]
This information will be added to the docs once https://github.com/dagger/dagger/pull/7411 lands, so I'm OK with closing it. Please see https://github.com/dagger/dagger/pull/7411/files#diff-89c2ede14a397d6a4d1d9496aa86753a05c85020c53414dfe4485fefb55c8ffaR123 and let me know if any further information should be added.

**Comment by TomChv** [comment]
Thanks for your reply! I'm closing this issue after #7411 is merged

**Comment by TomChv** [comment]
We can close it since #7411 has been merged
