### ISSUE TITLE
TypeScript SDK performance improvement

### ISSUE THREAD

**Issue by TomChv** [dagger/dagger#7093]
This issue aims to regroup all my tests and dig into the SDK performances improvement.

## Init

- Env: compiled a binary from main: (bdce95d0abfa9014a35f5e3962a64afce03d5fca)
- Use dagger cli `v0.11.0` 
- Use latest dagger cloud

```
time dagger init --name=perf --sdk=typescript                                              
Initialized module perf in .
dagger init --name=perf --sdk=typescript  0.98s user 0.73s system 11% cpu 14.829 total
➜  perfs git:(main) ✗ time dagger functions                        
Name             Description
container-echo   Returns a container that echoes whatever string argument is provided
grep-dir         Returns lines that match a pattern in the files of the provided Directory
dagger functions  1.32s user 0.78s system 10% cpu 20.765 total
➜  perfs git:(main) ✗ time dagger call container-echo --string-arg "dig into perf" stdout
dig into perf
dagger call container-echo --string-arg "dig into perf" stdout  0.92s user 0.69s system 18% cpu 8.599 total
```

<table>
<tr>
 <td> Operation
 <td> Time
 <td> Cloud URL (by sha)
 <td> Go time (as ref)
<tr>
 <td> Init
 <td> 14.8
 <td> <a href="https://dagger.cloud/Quartz/traces/1951a90ea8679fa505b67f640c4a7ce7">1951a90ea8679fa505b67f640c4a7ce7</a>
 <td> 2.6s
<tr>
 <td> Functions
 <td> 20s
 <td> <a href="https://dagger.cloud/Quartz/traces/7cf74155070bf75952fa5164e3e9667c">7cf74155070bf75952fa5164e3e9667c</a>
 <td> 3.12s
<tr>
 <td> Call container-echo
 <td> 8.6s
 <td> <a href="https://dagger.cloud/Quartz/traces/da94c06b08ba15704f815667a440e44d">da94c06b08ba15704f815667a440e44d</a> 
 <td> 2.89s
</table>

It's obvious that the Go SDK is much faster than TypeScript. Now that we have the context, let's understand why.

## Compares traces

If we compare the [TypeScript init trace](https://dagger.cloud/Quartz/traces/1951a90ea8679fa505b67f640c4a7ce7) and the [Go init trace](https://dagger.cloud/Quartz/traces/15a3e12d0a95affef58dc038b1c60e24).

<img width="1275" alt="Screenshot 2024-04-15 at 12 20 03" src="https://github.com/dagger/dagger/assets/61683879/37fd3f11-5765-43f7-b576-bf5c0c968928">

<img width="1275" alt="Screenshot 2024-04-15 at 12 20 45" src="https://github.com/dagger/dagger/assets/61683879/5b916f04-99ed-4818-b749-d9622e50e1a3">

We can observe a huge difference in the initialization, if we expends the traces, we find something interesting.

The `Go` `withDirectory` operation takes less than a second 

<img width="1100" alt="Screenshot 2024-04-15 at 12 27 02" src="https://github.com/dagger/dagger/assets/61683879/1f6ca5f1-d94f-4cef-9ffa-5fdc0f8f4ec6">

**The `Typescript` SDK takes 5.2s**

<img width="1100" alt="Screenshot 2024-04-15 at 12 26 41" src="https://github.com/dagger/dagger/assets/61683879/36dd6acc-05bd-400a-86db-afbba498e8e5">

**This is where we need to optimize the setup.**

**Note**

<img width="1264" alt="Screenshot 2024-04-15 at 12 25 27" src="https://github.com/dagger/dagger/assets/61683879/622b47b0-0cce-4b03-b1b7-0fec7d0bbc09">

We also have an extra step where we download the node image, but the speed will be dependant of the network so we cannot really optimize it.

**Comment by TomChv** [comment]
By @jedevc in https://github.com/dagger/dagger/pull/7081#issuecomment-2056371841

> Just dumping here for potential avenues for exploration (duplicating from discord):

> npm install --package-lock-only step seems to take a lot of time - is there a faster package manager we could use here? I think this is likely only generating the package-lock.json, so I'm not sure what makes this so expensive.
Or is this approach even right? It feels like an issue that we wouldn't respect the existing package-lock.json, cc @helderco, I know you looked at the python equivalent in https://github.com/dagger/dagger/pull/7064.
We should actually split out these commands to be separate if possible! There's a lot of stuff being done in groups of commands, so traces only show for that chunk, making it hard to dive deeper.
Caching doesn't seem to always cache between running init and functions. Not quite sure why - this should be pretty instantaneous.
I suspect something in TSX is introducing some latency - is there a way to cache TSX at all? Or maybe we could consider not using TSX at all, and instead compile the typescript into javascript? That feels like it would cache much better potentially, and could move some of the costs upfront.

**Comment by TomChv** [comment]
In the setup, we have this sets of operations that additioned takes more than 3 seconds, what are theses?

<img width="1100" alt="Screenshot 2024-04-15 at 12 30 24" src="https://github.com/dagger/dagger/assets/61683879/8534b041-3084-47ba-9c24-ebd62a9b5507">

We also have 2 seconds dedicated to install `tsx`

<img width="1100" alt="Screenshot 2024-04-15 at 12 32 05" src="https://github.com/dagger/dagger/assets/61683879/ad71f2de-b4c3-422e-b7a4-faf8d565450c">

This is something we could improve by changing the package manager (to [pnpm](https://pnpm.io/) maybe?)

**Comment by TomChv** [comment]
I did some test, trying to switch to `pnpm` but I keep hitting issues with `graphql`: https://github.com/pnpm/pnpm/issues/1715

I'm trying another strategie first, seeing if I can get rid of these shell script to do it with dagger operations, maybe it can impact the cache?

**Comment by TomChv** [comment]
I can see that with cached operations, it's going pretty fast so we can do 2 things:
- Simplify the caching (the longest operation is, `npm install ./sdk` which is something that can easily cached)
- Reduce the installation time (pre-install the sdk or post install it for example)

<img width="1135" alt="Screenshot 2024-04-15 at 17 26 45" src="https://github.com/dagger/dagger/assets/61683879/43502ff4-dc4c-4ffb-8a58-70889550ac51">

**Comment by TomChv** [comment]
I made some tests in order to reduce the time of the dependency installation, it seems I can slightly reduce the time by only installing production dependencies.

I really want to use pnpm, I'll continue to dig into the dependency resolutions, starting by using yarn which may also increase the time.

**Note** The time are much slower because I changed of place and my internet connection is slower.

<img width="1135" alt="Screenshot 2024-04-15 at 20 16 20" src="https://github.com/dagger/dagger/assets/61683879/45561f51-9684-4acb-b19e-0b4b20401d16">

<img width="1135" alt="Screenshot 2024-04-15 at 20 16 57" src="https://github.com/dagger/dagger/assets/61683879/be604ddf-2e9a-4dea-9e1e-79f1d6479c2c">

**Comment by TomChv** [comment]
It seems I can really decrease the time using `yarn` and I'm not hitting an issue (almost by 2)

Based on this [benchmark](https://nodesource.com/blog/nodejs-package-manager-comparative-guide-2024/#:~:text=Even%20though%20npm%20and%20yarn,pnpm%20is%20faster%20than%20Yarn.), yarn is faster in cold start so it might be a good first solution..

<img width="1135" alt="Screenshot 2024-04-15 at 20 43 53" src="https://github.com/dagger/dagger/assets/61683879/3c35ebac-eeb9-4af7-8425-191d2ae61332">

**Comment by TomChv** [comment]
For the latest update about SDK performance improvement, see: https://github.com/dagger/dagger/pull/7096#issuecomment-2123537679

**Comment by TomChv** [comment]
Quick update on that one, https://github.com/dagger/dagger/pull/7864 could unlock a possible optimization on the setup by removing the `sdk install` part, it seems that by only using the lockfile, we can download every dependencies.
So we would remove half the download work on the setup, which can potentially lead to great improvement.

The support for multiple package manager will also help measuring performances. I'll probably go back on that one soon.

**Comment by fprotazio** [comment]
> I made some tests in order to reduce the time of the dependency installation, it seems I can slightly reduce the time by only installing production dependencies.
> 
doesn't `npm ci` help? 
[npm ci](https://docs.npmjs.com/cli/v10/commands/npm-ci)

**Comment by TomChv** [comment]
> doesn't npm ci help?

It does help but it's not enough sadly... We're going to create benchmark for every package manager/runtime to see if we can spot some major diff.
