### ISSUE TITLE
🐞 On Windows, 'dagger init'  fails if it does not find or create certain expected files

### ISSUE THREAD

**Issue by scotthain** [dagger/dagger#7114]
### What is the issue?

When running `dagger init` in an emply directory, it will fail with an error message if the directory does not have a .git directory or a dagger.json.

There is another issue that is related but not the same, I'll file another issue for that one and link it back. (edit: #7115 )

I traced it back in the dagger codebase to the buildit module's `filesync.go`. Based on something I ran into years ago, my suspicion is that the CreateFile needs either a UNC path or double slashes on Windows. I wasn't able to get a windows build working to debug further though!

### Dagger version

dagger v0.11.1 ([registry.dagger.io/engine](http://registry.dagger.io/engine)) windows/amd64

### Steps to reproduce

```
mkdir dagger-test
cd .\dagger-test\
dagger init
```

### Log output

```
[scott][~\code\dagger-test]> dagger init
✔ connect 11.3s
✘ ModuleSource.resolveContextPathFromCaller: String! 0.0s
! failed to find up root: failed to lstat .git: failed to receive file bytes message: rpc error: code = Unknown desc = stat path: CreateFile C:/Users/scott/code/dagger-test/.git: The system cannot find the file specified.

Error: failed to get configured module: failed to get local root path: input: moduleSource.resolveContextPathFromCaller resolve: failed to find up root: failed to lstat .git: failed to receive file bytes message: rpc error: code = Unknown desc = stat path: CreateFile C:/Users/scott/code/dagger-test/.git: The system cannot find the file specified.
```

**Comment by jedevc** [comment]
Argh, yeah, this will be the result of https://github.com/dagger/dagger/pull/7003 - it's apparently still an issue. I'm not quite sure what happened here? I could have *sworn* I tested this, though maybe in a slightly different environment.

Regardless, can confirm this is an issue, the trick here is that for some reason, while we're encoding paths to be `filepath.ToSlash` over-the-wire, we're not un-encoding them using `filepath.FromSlash` in any consistent way. What a pain, but at least the fix should be pretty simple - will take a look at this tomorrow :tada:

Thanks for the quick report! :tada: 🎉

**Comment by scotthain** [comment]
Awesome! I was going to try and hop on it myself but I couldn't get the build to... build with dagger on Windows 😄 and ran out of time to play with it today.

**Comment by jedevc** [comment]
Oops, #7118 should have fixed this :tada: Closing now!

@scotthain did you ever manage to getting to build dagger-on-windows? I got it working using mingw (git bash) and docker desktop and bootstrapping using the latest dagger version. Curious if you got any further - it would be pretty cool to have a `./hack/dev.ps1` or similar if you ended up getting there.
