### ISSUE TITLE
🐞 On Windows, if dagger.json exists, 'dagger init' fails with a duplicate message

### ISSUE THREAD

**Issue by scotthain** [dagger/dagger#7115]
### What is the issue?

This is a semi followup to #7114 with what looks like a different cause. If one follows the steps in that issue, you'll eventually end up with a git repo that has a dagger.json in it. Running 'dagger init' there will throw a duplicate module error.

### Dagger version

dagger v0.11.1 ([registry.dagger.io/engine](http://registry.dagger.io/engine)) windows/amd64

### Steps to reproduce

```
mkdir dagger-test
cd .\dagger-test\
dagger init
git init
dagger init
New-Item -Type File -Path dagger.json
dagger init
```

### Log output

```
[scott][~\code\dagger-test]> dagger init
15:23:24 WRN failed to get repo HEAD err="reference not found"

✔ connect 1.1s

Error: module already exists
```

**Comment by jedevc** [comment]
This is expected I think. If there's already a module in the current directory (detected by if a `dagger.json` already exists), then we should fail initialization - it wouldn't be correct to try and overwrite the previous module.

Or maybe I'm misunderstanding something, and there's something that is unexpected here, even with the above behavior.

**Comment by scotthain** [comment]
Yeah this might be the correct behavior but I thought I'd post up the issue for visibility - I ran into this while following the tutorial and hitting the init bug behavior in #7114 . I didn't have a lot of time to dig into the code but I *think* when 7114 is fixed, `init` should just create the dagger.json file. Feel free to close if that's the case, just wanted to make sure this was the expected behavior.
