### ISSUE TITLE
Document how to get logs out of a service

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#7133]
## Problem

When running a service container in Dagger, sometimes things go wrong and you want to look at log files. Unfortunately there is no documented way to do this.

## Solution

Document how to get log files created by a service, and add it to the administrator guide.

**Comment by jedevc** [comment]
A bit more context in https://github.com/dagger/dagger/issues/6553, ideally we need a way to access this using the dagger API.

But also, it would definitely be cool if we could somehow get this using dagger watch as well? Not sure if this is the scenario you're thinking of.
