### ISSUE TITLE
Docs: Building a Module Tutorial

### ISSUE THREAD

**Issue by scottames** [dagger/dagger#7157]
### What is the issue?

Per discussion with Jeremy And Solomon [on Discord](https://discord.com/channels/707636530424053791/1230728932488253531), dropping a request to have the recent (or anything similar) [workshop](https://www.linkedin.com/posts/jeremy-adams-pdx_for-all-the-folks-who-ask-me-to-explain-dagger-activity-7183146597675937794-3rpZ) documented in the docs as a tutorial.

For a bit of context, I had been reading up on the prior method of developing Dagger (`dagger call`) and was a bit confused on where the prior method fit in with the module method. After watching the workshop it was made _very_ clear how the module method works, why it's the right direction, and more importantly, how quickly get started with it in my project. Having this as a quick tutorial in the docs for folks to walk through would go a long ways.

Hashicorp does a great job with their tutorials, take [Terraform](https://developer.hashicorp.com/terraform/tutorials) as an example.

**Comment by vikram-dagger** [comment]
@scottames would love your feedback on https://github.com/dagger/dagger/pull/7326 which should address this request.

**Comment by scottames** [comment]
> @scottames would love your feedback on #7326 which should address this request.

@vikram-dagger - Nice job with these! Those are great tutorials, I think will help a lot. I see in one of them you link back to examples in the daggerverse - having folks go through the tutorials _and_ look at examples in the daggerverse will go a long ways.
