### ISSUE TITLE
🐞 Directory.glob doesn't seem to be working as expected

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#7169]
### Discussed in https://github.com/dagger/dagger/discussions/7156

<div type='discussions-op-text'>

<sup>Originally posted by **skycaptain** April 22, 2024</sup>
I may be missing something simple, but I'm currently struggling with `Directory.glob` returning an empty list instead of the files. Consider this example where I want to match all the files in the `deploy/sdk` directory. Note the different `tmp-*` directories:

```python
mydir = (
    dag.directory()
    .with_new_file("build/tmp-build-a/deploy/sdk/test.txt", "FOO")
    .with_new_file("build/tmp-build-a/deploy/sdk/test.manifest", "BAR")
    .with_new_file("build/tmp-build-b/deploy/ipk/test.ipk", "BAZ")
)

await mydir.glob('build/tmp-*/deploy/sdk/*')
```

This example returns `[]`. Running the same command with regular `ls` works fine. I tried different combinations of the pattern, but none have worked as expected. What could I be missing?</div>

**Comment by marcosnils** [comment]
cc @TomChv

**Comment by cwlbraa** [comment]
I did a little digging here, there may be 2 overlapping bugs in dir.Glob. 

first,
```
entries, err := ref.ReadDir(ctx, bkgw.ReadDirRequest{
		Path:           path.Join(dir.Dir, src),
		IncludePattern: pattern,
	})
```
doesn't appear to handle single stars in directory specifications.

second, even using an input like `build/**/deploy/sdk/*`,
```
if entry.IsDir() {
			subEntries, err := dir.Glob(ctx, entryPath, pattern)
			if err != nil {
				return nil, err
			}
			paths = append(paths, subEntries...)
		}
```
may not recurse correctly. after matching `tmp-build-*`, it then tries to match the same pattern, `build/**/deploy/sdk/*` against the subentry (which now doesn't include the `/build/` part)
