### ISSUE TITLE
Allow env variable interpolation in Container.withEnvVariable

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#7171]
## Problem

Dagger has no direct equivalent to this simple Dockerfile line: `ENV PATH=foo:${PATH}`.

## Solution

Add an optional argument `Container.withEnvVariable` to allow interpolating the current container's env variables into string arguments. And possibly, add it to other `Container` functions as well.

The default for this new argument should be `true`, I think. In other words, interpolation should happen by default.

Then this would work out of the box:

```golang
func addToPath(c *Container) *Container {
 return c.WithEnvVariable("PATH", "$HOME/bin:$PATH")
```

**Comment by wingyplus** [comment]
I remember that withEnvVariable has an option to expand variable here https://github.com/dagger/dagger-go-sdk/blob/v0.11.1/dagger.gen.go#L1063. Is it similar use case?

**Comment by wingyplus** [comment]
Or it should start expand by default?

**Comment by helderco** [comment]
Yeah, this exists just isn't the default. More annoying in go because optionals are verbose:

**Go**

```go
c.WithEnvVariable("PATH", "$HOME/bin:$PATH", ContainerWithEnvVariableOpts{
    Expand: true,
})
```

**Python**
```python
ctr.with_env_variable("PATH", "$HOME/bin:$PATH", expand=True)
```

**TypeScript**
```ts
ctr.WithEnvVariable("PATH", "$HOME/bin:$PATH", {expand: true})
```

The best argument in favor of flipping the default is perhaps users don't trip up when they assume it should work like that off the shelve.

**Comment by shykes** [comment]
Wow I had no idea this existed! Then yes, I am arguing for 1) making it the default, and 2) considering adding it to other Container functions as well.

**Comment by vito** [comment]
Making it do this by default feels like a potential footgun to me, thinking of cases where you might pass a value in from a user that happens to contain a `$` :thinking:

**Comment by TomChv** [comment]
I removed the `sdk/typescript` label because it's not related to it directly.

However, we can close this issue since we already support variable interpolation

**Comment by helderco** [comment]
@shykes still argues for making this the default though:
- https://github.com/dagger/dagger/issues/7171#issuecomment-2075873862
- https://github.com/dagger/dagger/pull/7173

So I'll let him reopen if he wants to push for that, but @vito has concerns that I somewhat share and asks for more bikeshedding.

**Comment by jedevc** [comment]
Yeah, just adding my two cents here that I also agree with @vito here - it feels like a possibly annoying breaking change (so probably a candidate for v0.12.0 instead of v0.11.X IMO).

I'm also not entirely convinced it should be the default, I think each command should try and do as little magic by default as possible, and I don't think at least I would expect expansion by default (e.g. I think things like this are one of the things that makes bash-programming such a pain - I'd like to avoid that as much as possible).

**Comment by shykes** [comment]
I'm going to pick my battles and drop this. I agree it could cause confusing breaking changes.

My main motivation for changing the default behavior, is that most comparable tools *do* make this the default. I can't think of any case where variables expansion is configurable by a flag. Example: Dockerfile, docker-compose.yaml, and of course, shell scripts.

I needed expansion, and didn't even know an option was available for this. I think this will happen to many people. Which inconvenience will be greater? Honestly I don't know.

So, I'm dropping but also leaving this argument here for the record, in case it changes anyone's mind :)

**Comment by staticaland** [comment]
This caught me off guard.

But I discovered `Terminal()`, which makes debugging stuff like this way easier.
