### ISSUE TITLE
Clarify that rosetta and DEFAULT_PLATFORM should **not** be used in Mac  + Docker

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#7209]
### What is the issue?

Some Mac users have been having issues lately as they have either rosetta or the DEFAULT_PLATFORM variable set to something other than arm64 when using Dagger with Docker Desktop installed. ref: https://discord.com/channels/707636530424053791/1232715125480493127

We should add a note in our docs that in case of issues running our `hello` example in Mac + Docker Desktop, to double check this. It's also important to clarify that **if** they effectively ran into this issue, the way to fix it is by ensuring that neither rosetta and DEFAULT_PLATFORM is set, remove the current pulled engine image, and to try again. 

ref: https://discord.com/channels/707636530424053791/1232715125480493127/1233172844427481240

**Comment by vikram-dagger** [comment]
@marcosnils a few questions:

- is this different from the troubleshooting guidance at https://docs.dagger.io/manuals/user/932727/troubleshooting#calling-a-dagger-function-fails-when-docker_default_platform-is-set

if yes:
- what is the error message the user sees in this case? is it always `moduleSource.withContextDirectory.asModule resolve: failed to create module: select: failed to update codegen and runtime: failed to generate code: failed to get modified source directory for go module sdk codegen:`? are there any others?
- `the way to fix it is by ensuring that neither rosetta and DEFAULT_PLATFORM is set, remove the current pulled engine image, and to try again.` -> can you provide a set of commands for this, that a user could copy-paste?
- does this error appear only with the `hello` example in the quickstart, or with any `dagger call` command? This would determine whether (a) we document it generically in the [troubleshooting guide](https://docs.dagger.io/manuals/user/932727/troubleshooting) and link to it in the quickstart or (b) we document it specifically for the quickstart?

**Comment by marcosnils** [comment]
> * is this different from the troubleshooting guidance at https://docs.dagger.io/manuals/user/932727/troubleshooting#calling-a-dagger-function-fails-when-docker_default_platform-is-set

it overlaps with that troubleshooting section, yes, but there are some differences. I think we could improve to make sure that users check for both the rosetta and the DEFAULT_PLATFORM issue.

> * `the way to fix it is by ensuring that neither rosetta and DEFAULT_PLATFORM is set, remove the current pulled engine image, and to try again.` -> can you provide a set of commands for this, that a user could copy-paste?

1. Check that DEFAULT_PLATFORM is not set in your current shell and/or your equivalent shell config files (.bashrc, .profile, .zshrc, etc)
2. Validate that rosetta is disabled in Docker Desktop (https://docs.docker.com/desktop/settings/mac/)
3. Remove any running engine containers and docker images:  ` docker rm -fv $(docker ps --filter name="dagger-engine-*" -q) && docker rmi $(docker images -q --filter reference=registry.dagger.io/engine)`


> * does this error appear only with the `hello` example in the quickstart, or with any `dagger call` command? This would determine whether (a) we document it generically in the [troubleshooting guide](https://docs.dagger.io/manuals/user/932727/troubleshooting) and link to it in the quickstart or (b) we document it specifically for the quickstart?

It'll appear with any `dagger call`
