### ISSUE TITLE
Can't load local module at absolute path

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#7212]
## Problem

When loading a local module, absolute paths are not supported.

Example:

```shell
dagger -m /foo/bar functions
```

Output:

```shell
  ! local module source root path is absolute: /foo/bar
```

## Solution

Allow loading local modules from a local path.

**Comment by grouville** [comment]
@sipsma, is there any security / behavior concerns around allowing absolute paths ?
It seems that the restriction allows for just related path inside a module's context to be run

**Comment by sipsma** [comment]
> @sipsma, is there any security / behavior concerns around allowing absolute paths ? It seems that the restriction allows for just related path inside a module's context to be run. I am currently checking #7476, where the tests seem to pass (after a rebase), just wanted to double check 🙏

Got back here https://github.com/dagger/dagger/pull/7476#issuecomment-2174413739

**Comment by shykes** [comment]
I know this is already in progress. Just noting for the record that I ran into this issue again. Wanted to add a custom `DAGGER_MODULE=$(pwd)/...` in an `.envrc` file but not possible

**Comment by shykes** [comment]
Thank you!
