### ISSUE TITLE
🐞 bash completion setup instructions are broken when XDG_DATA_HOME is not set

### ISSUE THREAD

**Issue by iximiuz** [dagger/dagger#7280]
### What is the issue?

Here is an excerpt from the `install.sh` run on my server(s):

```
dagger has built-in shell completion. This is how you can install it for:

  BASH:

    1. Ensure that you install bash-completion using your package manager.

    2. Add dagger completion to your personal bash completions dir

      mkdir -p /bash-completion/completions
      dagger completion bash > /bash-completion/completions/dagger
```

Notice how `mkdir -p /bash-completion/completions` and the consequent line try to install the bash-completion instructions to the root `/` folder. #7279 hopefully fixes it.

### Dagger version

dagger v0.11.2

### Steps to reproduce

curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh (and look at the bash-completion part).

**Comment by gerhard** [comment]
Resolved by https://github.com/dagger/dagger/pull/7279
