### ISSUE TITLE
🐞 On Windows 11 - Cannot start an interactive terminal

### ISSUE THREAD

**Issue by giuliohome** [dagger/dagger#7282]
### What is the issue?

The command

```
 dagger -m github.com/shykes/daggerverse/wolfi@v0.1.2 call container --packages=python3 terminal
```

fails with `Error: sending initial size: get terminal size: The handle is invalid.`

### Dagger version

dagger v0.11.2 ([registry.dagger.io/engine](http://registry.dagger.io/engine)) windows/amd64

### Steps to reproduce

I have create an azure windows 11 vm with docker desktop installed.
I follow the install docs, I install powershell 7.4.2 and I execute

```pwsh
Invoke-WebRequest -UseBasicParsing -Uri https://dl.dagger.io/dagger/install.ps1 | Invoke-Expression
```

I add the location of dagger to the path and then I try to follow t[he instructions to build a container](https://docs.dagger.io/quickstart/883939/containers)

Eventually I want to start an interactive terminal session with the container

```pwsh
dagger -m github.com/shykes/daggerverse/wolfi@v0.1.2 call container --packages=python3 terminal
```

### Log output

```pwsh
PS C:\Users\giulio365cloud> dagger -m github.com/shykes/daggerverse/wolfi@v0.1.2 call container --packages=python3 terminal
←[31m✘←[0m start sh ←[2m1.4s←[0m
←[33m! new container: client closed
←[0m
Error: sending initial size: get terminal size: The handle is invalid.
PS C:\Users\giulio365cloud>
```

**Comment by giuliohome** [comment]
Btw, without the terminal, the command is running like that

```pwsh
PS C:\Users\giulio365cloud> dagger -m github.com/shykes/daggerverse/wolfi@v0.1.2 call container --packages=python3 with-exec --args="python3,-c,print('hello from Dagger')" stdout
hello from Dagger
PS C:\Users\giulio365cloud>
```

**Comment by giuliohome** [comment]
it seems related [to this line](https://github.com/dagger/dagger/blob/1bc2cffabc80e614afea9dc0155a0e77af1aa4c4/cmd/dagger/shell.go#L158)

```go
	w, h, err := term.GetSize(int(f.Fd()))
```

Maybe this [closed/resolved issue](https://github.com/golang/go/issues/20388) is relevant.

**Comment by jedevc** [comment]
Yay, more windows issues :tada: I'll take a look at this ideally for the next release.

**Comment by wingyplus** [comment]
Just try on it against `stdout`, it works!

**Comment by giuliohome** [comment]
Awesome, thank you 💯 

![image](https://github.com/dagger/dagger/assets/3272563/fe054668-a877-41f7-9af7-32d3dffeed30)
