### ISSUE TITLE
🐞 Latest TypeScript SDK throws `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"`

### ISSUE THREAD

**Issue by harleylang** [dagger/dagger#7284]
### What is the issue?

Since the latest changes were merged in on Friday I have found that TypeScript Dagger Modules and Functions will fail to run, with the following error thrown in the logs: `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"`

The best hypothesis I could drum up is that this error was introduced after this PR merged in on Friday:

- https://github.com/dagger/dagger/pull/7194

Here is the commit where I *think* the bug was introduced:

[https://github.com/dagger/dagger/commit/56a039a3ee96b4ab826b711d3e5843da8aadd8cb#diff-a8b5f7f08501c3951b9991d2450b8b0a68ac764af369185bbf7044d9654ac58c](https://github.com/dagger/dagger/commit/56a039a3ee96b4ab826b711d3e5843da8aadd8cb#diff-a8b5f7f08501c3951b9991d2450b8b0a68ac764af369185bbf7044d9654ac58c)

In the above PR the TypeScript SDK was changed. I *think* the error occurs due to how the SDK now uses paths to target module. But I am not 100% sure. Here is the change that is leading me to think this might be the case:

[https://github.com/dagger/dagger/commit/56a039a3ee96b4ab826b711d3e5843da8aadd8cb#diff-a8b5f7f08501c3951b9991d2450b8b0a68ac764af369185bbf7044d9654ac58cL78-R79](https://github.com/dagger/dagger/commit/56a039a3ee96b4ab826b711d3e5843da8aadd8cb#diff-a8b5f7f08501c3951b9991d2450b8b0a68ac764af369185bbf7044d9654ac58cL78-R79)

CC @jedevc

### Dagger version

v0.11.1 - but somehow my setup is using the latest upstream code and I'm not sure how.

### Steps to reproduce

I have provided an example repository that includes a way to simulate the bug both locally and in a GitHub action. The repository can be found here: [https://github.com/harleylang/dagger-11.2-bug](https://github.com/harleylang/dagger-11.2-bug)

Notice that in my repository I have targeted Dagger Engine v0.11.1 and v0.11.0 for the module itself and that worked fine Friday Morning. Though I note in the logged output that it appears the engine is using \~v0.11.2\~ the latest Dagger TypeScript SDK somehow.

### Log output

GitHub Action output:

These logs are the most detailed. See: [https://github.com/harleylang/dagger-11.2-bug/actions/runs/8957758849/job/24601209335](https://github.com/harleylang/dagger-11.2-bug/actions/runs/8957758849/job/24601209335)

Notice how the logs identified that the following go module was installed: `github.com/go-logr/stdr`. This module was not present in v0.11.1 and when I reviewed my GitHub Action logs for actions that were successful on Friday morning, this module was not installed. Is the Dagger Engine downloading the latest version of the TypeScript SDK? If so is that intentional behaviour?

Local output:

```
$ yarn start
yarn run v1.22.22
warning ../package.json: No license field
$ dagger -m demo call --dir=. bug
✘ demo(
    dir: ✔ blob(digest: "sha256:fa474445ec46181df24cd11c1b2a24676c5bad5af0e5acbfcd2d4fb0ddc29565", mediaType: "application/vnd.oci.image.layer.v1.tar+zstd", size: 10707417, uncompressed: "sha256:0eccfa1e3e11c831c45a14a72aace07f9b62dadfd3541e8e0825ee099d3cf3a0"): Directory! 0.0s
  ): Demo! 2.9s
! call constructor: process "tsx --no-deprecation --tsconfig /src/tsconfig.json /src/src/__dagger.entrypoint.ts" did not complete successfully: exit code: 1
┃ node:internal/process/promises:289
┃             triggerUncaughtException(err, true /* fromPromise */);
┃             ^
┃ TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /src/src/index.ts
┃     at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
┃     at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
┃     at defaultLoad (node:internal/modules/esm/load:143:22)
┃     at async nextLoad (node:internal/modules/esm/hooks:749:22)
┃     at async x (file:///usr/local/lib/node_modules/tsx/dist/esm/index.mjs?1714870275019:2:1744)
┃     at async nextLoad (node:internal/modules/esm/hooks:749:22)
┃     at async Hooks.load (node:internal/modules/esm/hooks:382:20)
┃     at async handleMessage (node:internal/modules/esm/worker:199:18) {
┃   code: 'ERR_UNKNOWN_FILE_EXTENSION'
┃ }
┃
┃ Node.js v21.3.0
  ✘ exec tsx --no-deprecation --tsconfig /src/tsconfig.json /src/src/__dagger.entrypoint.ts 2.7s
  ! process "tsx --no-deprecation --tsconfig /src/tsconfig.json /src/src/__dagger.entrypoint.ts" did not complete successfully: exit code: 1

Error: response from query: input: demo resolve: call constructor: process "tsx --no-deprecation --tsconfig /src/tsconfig.json /src/src/__dagger.entrypoint.ts" did not complete successfully: exit code: 1

Stderr:
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /src/src/index.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async nextLoad (node:internal/modules/esm/hooks:749:22)
    at async x (file:///usr/local/lib/node_modules/tsx/dist/esm/index.mjs?1714870275019:2:1744)
    at async nextLoad (node:internal/modules/esm/hooks:749:22)
    at async Hooks.load (node:internal/modules/esm/hooks:382:20)
    at async handleMessage (node:internal/modules/esm/worker:199:18) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v21.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gerhard** [comment]
cc @jedevc @sipsma @TomChv

**Comment by TomChv** [comment]
Hey @harleylang 

Thanks for the reported issue!

I tried to reproduce the step in https://github.com/harleylang/dagger-11.2-bug with the latest version of Dagger but I was unfortunately unable to reproduce the issue.
Did I miss anything in the repro step?

I tried with and without downloading dependencies (it's actually not required to download them unless you have external TS dependencies in your pipeline)

<img width="863" alt="Screenshot 2024-05-06 at 13 28 47" src="https://github.com/dagger/dagger/assets/61683879/7d06f205-d3a4-49f7-8acf-c0d0417c14d0">

> v0.11.1 - but somehow my setup is using the latest upstream code and I'm not sure how.

Can you try with engine version `v0.11.2`? Maybe the version missmatch is leading to that issue based on the recent changes you saw in the commits.

**Comment by harleylang** [comment]
Hi @TomChv, thank you for looking into this and sharing your reproduction results. 

Everything works as expected. I have re-tested with v0.11.1 and v0.11.2 across the GitHub Action, the reproduction repository, and the function I was working on when this error occurred, all good now.

I'll close the issue and follow-up with some comments in Discord. Many thanks to the team for your time and attention to this one!
