### ISSUE TITLE
Move to Compose v2 (a.k.a "Local Docker Compose")

### ISSUE THREAD

**Issue by Alvise88** [dagger/dagger#732]
I saw that docker-compose support was recently added; i suggest to install the [newer implementation](https://github.com/docker/compose-cli) based on go.
Considering that it is based on the "cli plug-in mechanism" we can add the ability to install external cli plug-ins as packages or wait for it to become part of the base docker cli installation.

**Comment by TomChv** [comment]
I think we can consider this issue outdated since the API has changed a lot.

**Comment by samalba** [comment]
Closing this one after discussion with Tom
