### ISSUE TITLE
CLI cannot call function accepting a list of scalars in v0.11.3 

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#7320]
Found in https://github.com/dagger/dagger/actions/runs/9003172745/job/24733214096?pr=7319.

Attempting to call a function like:

```go
// Verify that the engine builds without actually publishing anything
func (e *Engine) TestPublish(
	ctx context.Context,

	// +optional
	platform []Platform,
) error {
```

Causes a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xf6108d]

goroutine 1 [running]:
main.(*modFunctionArg).AddFlag(0xc000b1a0f0, 0xc000d7bd00)
	/app/cmd/dagger/flags.go:703 +0xb2d
main.(*FuncCommand).addArgsForFunction(0x1d30520, 0xc000d7e000, {0x1d767a0, 0x0, 0x0}, 0xc000b12180)
	/app/cmd/dagger/functions.go:558 +0x1a5
```

This looks to be a regression from #7158.

**Comment by levlaz** [comment]
Is there any workaround for this, or should people using scalars avoid v0.11.3?

**Comment by jedevc** [comment]
You can avoid using list of scalars - there's no workaround, we're planning to do a v0.10.4 release tomorrow I think.

**Comment by levlaz** [comment]
v0.11.4* — but yes, thank you, you're the best! :D

Lev Lazinskiy
Head of Solutions @ dagger.io ( http://dagger.io )
e: ***@***.***
p: 415.470.2142
