### ISSUE TITLE
Add Documentation for dagger.json

### ISSUE THREAD

**Issue by levlaz** [dagger/dagger#7324]
### What is the issue?

As far as I can tell we don't have any documentation describing the contents of dagger.json. 

We should have a section in the docs that talks about the file, what it contains by default, and what additional parameters are available. 

The biggest point of friction for newcomers is there is a way to exclude files and dirs via dagger.json that is undocumented. So for projects with large directories (that are not required for the actual build) it can cause significant slowness with no obvious remedy. 

The closest thing we have is the docs in this file that implements the config object: https://github.com/dagger/dagger/blob/b8409fb11a163168860259f26fa27cb9e2e7b48b/core/modules/config.go#L9

**Comment by helderco** [comment]
`dagger.json` isn't meant to be edited manually, that's just a stop gap. The real fix is to polish `dagger config`:
- https://github.com/dagger/dagger/issues/6606

**Comment by levlaz** [comment]
Thanks @helderco this is an important clarification. I think my point would then to improve the existing docs around dagger config https://docs.dagger.io/reference/979596/cli/#dagger-config -- but seems like that's going to be capture in the other issue. Ill close this for now.
