### ISSUE TITLE
✨ Dependency updates

### ISSUE THREAD

**Issue by sagikazarmark** [dagger/dagger#7343]
### What are you trying to do?

Automate/make dependency updates easier.

Dependency update strategies:

1. Update one dependency because I need something from a newer version:

```
dagger install github.com/...
```

2. Update all dependencies to latest (due to Dagger engine compatibility or because I just want to update everything to the latest version):

Ideal solution:

```
dagger install -u
```

### How are you currently working around this?

https://twitter.com/sagikazarmark/status/1788527291800170928

```
cat dagger.json | jq -r '.dependencies[].source' | cut -d '@' -f 1 | xargs -L1 dagger install
```

**Comment by helderco** [comment]
Yep, that's covered in:
- https://github.com/dagger/dagger/issues/6605

**Comment by sagikazarmark** [comment]
Closing as duplicate
