### ISSUE TITLE
✨ `.AsTarball` Add OCI manifest RepoTags

### ISSUE THREAD

**Issue by stobias123** [dagger/dagger#7368]
### What are you trying to do?

I want to add tags when running `.AsTarball()`, perhaps in `ContainerAsTarballOpts`

Example usage:
```
client.Container().From("ubuntu:latest").WithExec([]string{"touch", "/test"}).AsTarball(dagger.ContainerAsTarballOpts{Address:"test:foo"}).Export(context.Background(), "test.tar")
```

Docker equavalent:
```shell
➜  git:(stobias/ci-improvements) ✗ docker build -t tarball_test .
➜  git:(stobias/ci-improvements) ✗ docker tag tarball_test tarball_test:foo
➜  git:(stobias/ci-improvements) ✗ docker save tarball_test:foo  -o test.tar
➜  git:(stobias/ci-improvements) ✗ docker load -i test.tar
Loaded image ID: sha256:91f46b36568a0cc2723effb809637b7c2dfe09046852c66f654fdccd470244e1
➜  git:(stobias/ci-improvements) ✗ docker images | Grep test
tarball_test                                                  foo       7caccf1a1a35   13 minutes ago   76.2MB
```

### Why is this important to you?

I have an offline use case where I must ship container images as tarballs. I'd like these to be tagged, similar to images produced via `docker save`.

### How are you currently working around this?

I'm not... I have to use different tooling, or end up with a wild and ugly bash script that would open the tarball, edit the manifest and then re-tar it.

**Comment by morlay** [comment]
Same as  https://github.com/dagger/dagger/issues/6999

**Comment by stobias123** [comment]
cosing as duplicate
