### ISSUE TITLE
App crashing with NPE for some classes when Lazy Class Key is used

### ISSUE THREAD

**Issue by nitinsethi86** [dagger/dagger#7383]
### What is the issue?

NPE sometimes when the class used in LazyClassKey is removed by R8.

R8 has removed that type from the final APK. Can we provide examples of R8 rules that should accompany with usage of LazyClassKey? 

Example module that uses LazyClassKey

```
@Module
public abstract class AppDataFactoryModule {

    @Binds
    @IntoMap
    @LazyClassKey(ILogger.class)
    abstract Object bindILogger(ILogger logger);
}
```

### Dagger version

2.51.1

**Comment by jedevc** [comment]
Heya @nitinsethi86! I *think* you might have the wrong dagger repo - you're probably looking for https://github.com/google/dagger, the dependency injection system.

We're a project focused on making CI better with programmable SDKs, and fast caching - we also have a Java SDK, that you might be interested in! Sorry, we can't really help with Java dependency injection though :cry: Good luck! :tada:
