### ISSUE TITLE
🐞 Don't require any params when asking for help 

### ISSUE THREAD

**Issue by levlaz** [dagger/dagger#7398]
### What are you trying to do?

Right now if I want to call --help on a module or function that has some required parameters I need to add those parameters before getting the help output. This is especially painful when using a constructor. 

I expect this to work closer to daggerverse.dev where I can inspect everything a module or function can do without needing to think about the inputs. 

### Why is this important to you?

I think its a much cleaner DX if we decouple --help from execution

**Comment by helderco** [comment]
That's actually a regression, reported in DEV-3785, and actively being worked on.
