### ISSUE TITLE
🐞 Go: `dagger functions` treat constructor arg as a function

### ISSUE THREAD

**Issue by wingyplus** [dagger/dagger#7410]
### What is the issue?

I have a module that has 1 constructor argument and a `run` function. When I call `dagger functions`, the command treat constructor arg as a function.

### Dagger version

0.11.4

### Steps to reproduce

Use the module from https://github.com/wingyplus/daggerverse/tree/main/earthly. Then run `dagger functions`. You will see both function and constructor arg listed like the screenshot below:

![Screenshot 2024-05-19 171753](https://github.com/dagger/dagger/assets/484530/14787ebe-5787-4a25-865f-de786a270113)

**Comment by wingyplus** [comment]
This get a little confuse because you cannot call with `dagger call source...`  but it's `dagger call --source...`.

**Comment by helderco** [comment]
That’s expected because the `source` function that you’re seeing comes from the `Source` field in the `Earthly` struct. So you have both:

```
dagger call --source=. source entries
```

If you don’t want to create a function for that field, you can use `// +private`.

**Comment by wingyplus** [comment]
Thank you 🙇‍♂️
