### ISSUE TITLE
🐞 Failed `dagger call` check fails due to missing span & does not get fixed when re-running the job

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#7423]
### What is the issue?

This `dagger call` check failed:
<img width="969" alt="image" src="https://github.com/dagger/dagger/assets/3342/1a8b9d7f-d13e-4ada-b9c4-6ec3c30033e1">

If you look carefully at all the workflows, you will notice that they all succeeded. The last time that this happened, re-triggering the workflow fixed it: https://github.com/dagger/dagger/pull/7407#issuecomment-2119253346

In this case - https://github.com/dagger/dagger/pull/7416 - that didn't work.

https://dagger.cloud/dagger/traces/d2a10b407f509e3a0cb119c9f7d97a7b
<img width="1431" alt="image" src="https://github.com/dagger/dagger/assets/3342/0b524f10-4df9-4077-96ed-5c133ef36986">

Is there a different workaround that we could use for this @vito @aluzzardi ?

### Dagger version

dagger v0.11.4 (registry.dagger.io/engine) linux/amd64

**Comment by gerhard** [comment]
FWIW, there are loads of those failed checks in, even though only one workflow failed:
- https://github.com/dagger/dagger/pull/7395

<img width="971" alt="image" src="https://github.com/dagger/dagger/assets/3342/bbb26459-f2d3-40e0-bf3f-ba81f59e3a3d">

**Comment by jedevc** [comment]
I suspect this might be the same underlying issue as https://github.com/dagger/dagger/issues/7192, which https://github.com/dagger/dagger/pull/7227 was a hotfix for - the result is still invalid, but at least now the dagger cli no longer crashes.

**Comment by gerhard** [comment]
Having spoken with @aluzzardi earlier today, some of these checks may have failed due to a ClickHouse migration which killed some in-flight traces.

https://dagger.cloud/dagger/traces/d2a10b407f509e3a0cb119c9f7d97a7b was apparently part of https://github.com/dagger/dagger/pull/7416, but I couldn't find the corresponding failing workflow - all of them passed. I just retriggered the workflow that passed to force this failing `dagger call` check to pass: https://github.com/dagger/dagger/actions/runs/9160077077/job/25242742782?pr=7416

**Comment by gerhard** [comment]
OK to close. Re-open if we hit this again. cc @vito
