### ISSUE TITLE
🐞 [Typescript] Object prototypes aren't preserved for fields

### ISSUE THREAD

**Issue by Xiot** [dagger/dagger#7446]
### What is the issue?

Custom values that are stored in a `@field` do not have their prototype chain preserved.

This leads to unexpected behaviour, especially since objects need to be created as a class with `@object` in order to be serialized at all.

### Dagger version

dagger v0.11.4 (registry.dagger.io/engine) darwin/arm64

### Steps to reproduce

I created a very simple module, that just passes a custom object between two modules.

```typescript
@object()
class RootModule {
  @func() test() {
    return new PModule(new PCheck(4))
  }
}

@object()
class PCheck {
  @field() value: number

  constructor(value: number) {
    this.value = value
  }
  get doubled() {
    return this.value * 2
  }
}

@object()
class PModule {
  @field() value: PCheck
  constructor(value: PCheck) {
    this.value = value
  }
  @func() print() {
    console.log('value', this.value, Object.getPrototypeOf(this.value))
    return this.value.doubled ?? 0
  }
}
```

Running the above with
```
dagger call test print
```

will return 0 and will print

```typescript
value { value: 4 } [Object: null prototype] {} 
```

The fact that the `value` field has a `null` prototype seems very unexpected.

If I change the implementation of `print` to attach the prototype, then things work as expected.
```typescript
  @func() print() {
    this.value = Object.setPrototypeOf(this.value, PCheck.prototype)
    console.log('value', this.value, Object.getPrototypeOf(this.value))
    return this.value.doubled ?? 0
  }
```

**Comment by Xiot** [comment]
@TomChv If you can point me at where you serialize / deserialize the `@object`s I can take a crack at this

**Comment by Xiot** [comment]
Actually it looks like no prototypes are preserved.  I just got hit with this when using classes inside of my module

**Comment by helderco** [comment]
The decorators are mostly for adding things to a "registry". It's then based on this registry that objects are recreated based on serialized input.

The `@field` decorator is defined here:

https://github.com/dagger/dagger/blob/2bbdb09482e13ff5edbd59a86ae7e532837c25b9/sdk/typescript/introspector/registry/registry.ts#L56-L60

There's a layer of "abstractions" tying TypeScript introspection data to symbols in code:

https://github.com/dagger/dagger/blob/2bbdb09482e13ff5edbd59a86ae7e532837c25b9/sdk/typescript/introspector/scanner/abtractions/object.ts#L95-L107

Deserialization from input and serialization of output happens during function "invocation":

https://github.com/dagger/dagger/blob/2bbdb09482e13ff5edbd59a86ae7e532837c25b9/sdk/typescript/entrypoint/invoke.ts#L28-L60

An object is instantiated in `getResult`:

https://github.com/dagger/dagger/blob/2bbdb09482e13ff5edbd59a86ae7e532837c25b9/sdk/typescript/introspector/registry/registry.ts#L115-L116

Values filled in:

https://github.com/dagger/dagger/blob/2bbdb09482e13ff5edbd59a86ae7e532837c25b9/sdk/typescript/introspector/registry/registry.ts#L127-L128

Object state comes from here:

https://github.com/dagger/dagger/blob/2bbdb09482e13ff5edbd59a86ae7e532837c25b9/sdk/typescript/entrypoint/load.ts#L99-L115

**Comment by helderco** [comment]
Maybe this also helps understand how things tie together.

When Dagger needs to call a function, it calls the TypeScript [entrypoint](https://github.com/dagger/dagger/blob/2bbdb09482e13ff5edbd59a86ae7e532837c25b9/sdk/typescript/entrypoint/entrypoint.ts#L20) two times, first to load the module, and a second time to actually execute:
1. **Load**, which triggers this branch:

  https://github.com/dagger/dagger/blob/2bbdb09482e13ff5edbd59a86ae7e532837c25b9/sdk/typescript/entrypoint/entrypoint.ts#L42

2. **Execution**, which triggers this branch:

  https://github.com/dagger/dagger/blob/2bbdb09482e13ff5edbd59a86ae7e532837c25b9/sdk/typescript/entrypoint/entrypoint.ts#L65-L70

In either case, the result is returned in:

https://github.com/dagger/dagger/blob/2bbdb09482e13ff5edbd59a86ae7e532837c25b9/sdk/typescript/entrypoint/entrypoint.ts#L95

**Comment by TomChv** [comment]
Thanks @helderco for the great details you provided!

@Xiot Yes it's normal since the TS compiler API doesn't provide a way to keep these metadatas unfortunately.
I did some research when I first implemented the SDK and it seems like a limitation due to the creation of the class with some generic implementation and not a specific one.

TypeScript is quite weird in that area and we load source files :(

**Comment by Xiot** [comment]
This is a lot of great information.  Thanks.

The interesting thing that I noticed is that you actually do try to use the prototype
https://github.com/dagger/dagger/blob/2bbdb09482e13ff5edbd59a86ae7e532837c25b9/sdk/typescript/introspector/registry/registry.ts#L115-L116
For some reason it is being stored as `null`.

I'll try to find some time to debug through it a bit and see why it isn't saving the prototype

**Comment by Xiot** [comment]
So it looks like prototypes on the fields are initially preserved however [this](https://github.com/dagger/dagger/blob/c3dd50a50660c18c3bbb1dcfba45ef20223ad0b6/sdk/typescript/entrypoint/invoke.ts#L49-L57) block that handles the aliasing seems to break the prototype chain.

If I comment out that block, then all of the tests, except for the alias case, still pass.  So it looks like its just the alias handling that is messing things up.

It does look like that block also 'objects' to their ids as well, and I don't know how much of that is expected/desired.

For instance in the `Should correctly invoke hello world` test, the `Alias` object has a `@field() ctr: Container` property, that after it goes through the `loadResult`, it becomes `container: string` (where the value is the containers id).  Since there aren't any tests that assert whether or not the actual value, `Container` in this case, or just its id should be returned its hard for me to see what the expected result should be.

If it should be the 'proper', prototyped object, that is returned, one way to handle the aliased properties could be to use a `Proxy`.  That would allow for the object to be kept in tact, while also allowing the fields/funcs to be accessible by their aliases.

**Comment by Xiot** [comment]
This is a little more prominent on the `objectParam` test, as none of the methods are preserved.

I created a branch to make this a little easier to showcase
https://github.com/dagger/dagger/pull/7465

I'm also going to see how it is handled in go

**Comment by TomChv** [comment]
> The interesting thing that I noticed is that you actually do try to use the prototype

Yes it was required, this is the constructor function of the class. It doesn't work otherwise if we just use `.class`

> If I comment out that block, then all of the tests, except for the alias case, still pass. So it looks like its just the alias handling that is messing things up.

I think it's fine for most of the TypeScript tests but I expect a lot more fails if we run the full integrations tests.

This part is quite shady honestly, we construct and serialize object to the Dagger API but they have different systems.

> returned its hard for me to see what the expected result should be.

That's the weird things, we return a container but then we load its ID in

https://github.com/dagger/dagger/blob/6efd184405408359352c8ca9e1a0f150592e1fe4/sdk/typescript/entrypoint/load.ts#L206-L208

So we transform an object into its ID that we can return it to the Dagger API.

> This is a little more prominent on the objectParam test, as none of the methods are preserved.

They should be if you register them as `@object`, that way we can load them from the API, otherwise they will not be loaded. You would also need to decorate your function with `@func` if you want them to be exposed to other modules, otherwise it's gonna be a private function (on the Dagger API perspective).

**Comment by Xiot** [comment]
> I think it's fine for most of the TypeScript tests but I expect a lot more fails if we run the full integrations tests.

Ya I would assume so.  I haven't looked for those yet.

> They should be if you register them as @object, that way we can load them from the API, otherwise they will not be loaded. You would also need to decorate your function with @func if you want them to be exposed to other modules, otherwise it's gonna be a private function (on the Dagger API perspective).

Even if they are registered as `@func` they still aren't preserved. The tricky part is coming up with something that works within a module, as well as between modules.  

> That's the weird things, we return a container but then we load its ID in

That is going to cause things to break if someone tries to pass one of their own objects in that has an property named `id`.  Although the fact that it is a `function` makes it much less likely for a collision though

**Comment by TomChv** [comment]
> Even if they are registered as @func they still aren't preserved. The tricky part is coming up with something that works within a module, as well as between modules.

I see, well normally it should have been preserved, since the TS loader will take the object parameter identifier and convert it to an actual class, it's supposed to work.

I need to make some research around that and figure out how to fix it, I might now load object param as class.

> That is going to cause things to break if someone tries to pass one of their own objects in that has an property named id. Although the fact that it is a function makes it much less likely for a collision though

Yes, it's a function so it should be okay.

**Comment by TomChv** [comment]
@Xiot I implemented the changes in https://github.com/dagger/dagger/pull/7477 so it should fix your issue ;)
