### ISSUE TITLE
Allow defining a default view

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#7462]
We have a concept of directory "views" for filtering the contents of a directory, to avoid uploading its entire contents. A view can passed explicitly to the CLI with `PATH[:VIEW]`. For example `dagger call build --source .:default`. But there is no way to configure a view to be used by default.

| command | view used today | view used in proposal |
| -- | -- | -- |
| `dagger call build --source .:foo` | `foo` ✅ | `foo` |
| `dagger call build --source .` | none ❌ | `default` if it exists, otherwise none |

**Comment by helderco** [comment]
With the _ignore_ patterns in https://github.com/dagger/dagger/issues/7647 and https://github.com/dagger/dagger/issues/7832, do we still have a need for views?

**Comment by shykes** [comment]
With contextual directory shipped, this is no longer needed.
