### ISSUE TITLE
Document Views

### ISSUE THREAD

**Issue by levlaz** [dagger/dagger#7489]
### What is the issue?

We shipped the ability to use views to filter directories a few weeks ago, but as far as I can tell this PR did not include any additional documentation on how this works. https://github.com/dagger/dagger/pull/6857/files 

This is a powerful part of the CLI and has a chance to significantly improve performance and overall DX so we should be sure to include this in our docs.

**Comment by shykes** [comment]
I actually think we should refrain from documenting views, and go all in on #7199 . We're really close, and I'd prefer to put more wood behind fewer arrows.

**Comment by levlaz** [comment]
@shykes thanks for the feedback, agree 100% - ill close this and keep an eye on #7199
