### ISSUE TITLE
✨ [TypeScript SDK] Consider using ECMAScript Decorators

### ISSUE THREAD

**Issue by marcomuser** [dagger/dagger#7499]
### What are you trying to do?

Currently, the TypeScript SDK uses experimental decorators which are considered deprecated. TypeScript has provided support for standard ECMAScript decorators since [version 5.0](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#decorators). I would suggest considering the use of standard decorators over the now deprecated experimental decorator implementation which will never be usable from JavaScript and might even get removed from TypeScript in the (admittedly very) long-term.

### Why is this important to you?

The main benefit comes from better integration into the larger JS ecosystem and future proofing the current work. The decorator's proposal has been at [stage 3](https://github.com/tc39/proposal-decorators) in TC39 for a while now. While It will land in all the JS engines in the foreseeable future (browser vendors are actively working on it), it's usable already today in TypeScript.

### How are you currently working around this?

*No respon*

**Comment by helderco** [comment]
I agree. This was my feedback back in https://github.com/dagger/dagger/pull/6159#discussion_r1408236630 but I remember @TomChv saying he couldn't get it to work properly (I think the problem was getting the right metadata on introspection). Maybe now it's better, or if anyone can help here that would be much appreciated. 🙏

**Comment by TomChv** [comment]
Hey, yup I remember that one, I had some issue when I removed the `experimentalDecorator` in the `tsconfig`, I'll see if it's possible to remove it now.
This would be a great improvement

**Comment by TomChv** [comment]
#7944 was an attempt to fix that issue, however it seems that it's not possible for now because:

> Alright, I'm closing this PR since it doesn't support function's argument decorator and we need it for https://github.com/dagger/dagger/pull/7744.

> This will have to wait for [tc39/proposal-class-method-parameter-decorators](https://github.com/tc39/proposal-class-method-parameter-decorators) to be completed to be done.

**Comment by TomChv** [comment]
I'm closing this issue since we're not likely to use ECMA decorators until the proposal is fully integrated to Typescript.
Please reopen this issue when that's the case and we can take care of that :)
