### ISSUE TITLE
🐞 Secrets in Dockerfile not available with buildkit directive

### ISSUE THREAD

**Issue by Alvise88** [dagger/dagger#7522]
### What is the issue?

Secrets building container in dagger with dockerfile are not available. Lastest working version is v0.9.11

### Dagger version

v0.11.6

### Steps to reproduce

You can find an example in this repository: https://github.com/Alvise88/dagger-dockerfile-secret-issue

**Comment by marcosnils** [comment]
I was able to reproduce this and it seems to be related to the #syntax directive at the very top of the Dockerfile. If you remove that, it should work.  ref: https://discord.com/channels/707636530424053791/1245745373356625990/1246142688504320134

If you are able to validate this, could you please update the issue description? 

Thanks!

**Comment by Alvise88** [comment]
Ok, removing buildkit directive it starts working properly.
