### ISSUE TITLE
🐞 Windows user home directory support with ~

### ISSUE THREAD

**Issue by pjmagee** [dagger/dagger#7547]
### What is the issue?

Dagger does not seem to recognise the `~` on Windows and assumes the current working directory in combination with the \~ rather than being the current users home directory.

### Dagger version

dagger v0.11.6 ([registry.dagger.io/engine](http://registry.dagger.io/engine)) windows/amd64

### Steps to reproduce

I tried various approaches of the following

```
dagger -m github.com/pjmagee/dagger-heroes-decode@6c672139c5a5d5138ae608cd33af707c45a833c9 call decode --file "~\simple.StormReplay" stdout
```

* \~.\\file
* \~./file
* \~/file
* \~\\file

All with the same result

### Log output

```
✘ Host.file(path: "C:/Projects/~/simple.StormReplay"): File! 0.0s
! select: host directory C:/Projects/~/: rpc error: code = Unknown desc = resolve : CreateFile C:\Projects\~: The system cannot find the file specified.

Error: response from query: input: host.file resolve: select: host directory C:/Projects/~/: rpc error: code = Unknown desc = resolve : CreateFile C:\Projects\~: The system cannot find the file specified.
```

**Comment by samalba** [comment]
This is not related to Windows, it's related to how the shell is implemented. Try the following:

```
echo "~"
echo ~
```

Only the second command should show your home dir.

**Comment by pjmagee** [comment]
> This is not related to Windows, it's related to how the shell is implemented. Try the following:
> 
> ```
> echo "~"
> echo ~
> ```
> 
> Only the second command should show your home dir.

Yes, you;'re right

```
C:\Users\patri> echo $HOME
C:\Users\patri
C:\Users\patri> echo ~
~
C:\Users\patri>
```

**Comment by samalba** [comment]
Closing, not a dagger bug (feel free to re-open if you feel otherwise)
