### ISSUE TITLE
🐞 Cannot pull engine container (engine v0.8.8)

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dagger/dagger#7548]
### What is the issue?

Since late last week we have been experiencing intermittent issues with pulling the dagger container in our github actions workflows:
```
1: connect ERROR: new client: failed to run container: Unable to find image 'registry.dagger.io/engine:v0.8.8' locally
docker: Error response from daemon: Get "https://registry.dagger.io/v2/engine/manifests/sha256:779fedd2902d251166eefe4fd1f00f71ab74e157b1e736fce4c6615b0fb1b321": net/http: TLS handshake timeout.
See 'docker run --help'.
: exit status 125
Error: new client: failed to run container: Unable to find image 'registry.dagger.io/engine:v0.8.8' locally
docker: Error response from daemon: Get "https://registry.dagger.io/v2/engine/manifests/sha256:779fedd2902d2[51](https://github.com/dbt-labs/dbt-mantle/actions/runs/9369699151/job/25796363699#step:8:52)166eefe4fd1f00f71ab74e157b1e736fce4c6615b0fb1b321": net/http: TLS handshake timeout.
```
Should we use a different registry? Did anything change with the existing one? 

### Dagger version

registry.dagger.io/engine:v0.8.8

**Comment by samalba** [comment]
Could you try the following:

```
docker pull registry.dagger.io/engine:v0.8.8
```

If you get the same error, it would mean a networking issue on the client side.

Also, could you also upgrade your version of Dagger (latest is v0.11.6)?

**Comment by colin-rogers-dbt** [comment]
@samalba updated the overview to add some context that this happens intermittently in our github actions workflows.

While we can look into upgrading I'm not sure I follow how that will help.

**Comment by colin-rogers-dbt** [comment]
closing as this seems to have gone away on it's own
