### ISSUE TITLE
🐞 Windows Installation Instructions parameters don't work  

### ISSUE THREAD

**Issue by levlaz** [dagger/dagger#7560]
### What is the issue?

I thought this was resoled in [https://github.com/dagger/dagger/issues/6901](https://github.com/dagger/dagger/issues/6901) but it seems like there are still issues with the Windows Installation instructions for the Dagger CLI. [https://docs.dagger.io/install](https://docs.dagger.io/install)

I am able to to install just fine with this basic command:

```
Invoke-WebRequest -UseBasicParsing -Uri https://dl.dagger.io/dagger/install.ps1 | Invoke-Expression
```

However, if I try to change the path or version I get an error.

Command

```
$script = Invoke-WebRequest -UseBasicParsing -Uri https://dl.dagger.io/dagger/install.ps1
$params = "-InstallPath C:\temp"
"$script $params" | Invoke-Expression
```

Error

```
-InstallPath:
Line |
  94 |   -InstallPath C:\temp
     |   ~~~~~~~~~~~~
     | The term '-InstallPath' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Same issue for version.

Command

```
$script = Invoke-WebRequest -UseBasicParsing -Uri https://dl.dagger.io/dagger/install.ps1
$params = "-DaggerVersion 0.11.4"
"$script $params" | Invoke-Expression
```

Error

```
-DaggerVersion:
Line |
  94 |   -DaggerVersion 0.11.4
     |   ~~~~~~~~~~~~~~
     | The term '-DaggerVersion' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by jedevc** [comment]
@levlaz out of curiosity what version of powershell is this?

I've had this issue when using a version that's too low. See the first line of the installation instructions:

> If you want to use the installation script, PowerShell 7.0 or newer is required. From PowerShell

Perhaps the install instructions need some clarification if this is the case? Like a sanity check for the version.

**Comment by pjmagee** [comment]
> @levlaz out of curiosity what version of powershell is this?
> 
> I've had this issue when using a version that's too low. See the first line of the installation instructions:
> 
> > If you want to use the installation script, PowerShell 7.0 or newer is required. From PowerShell
> 
> Perhaps the install instructions need some clarification if this is the case? Like a sanity check for the version.

The script could be written to actually run on Windows/Linux/Mac since powershell7 is xplat - not sure if that would also help with testing

**Comment by jedevc** [comment]
Hm. I'm *okay* with allowing `install.ps1` to work on non-windows, but it shouldn't be the default. Most Linux users don't (and IMO, *shouldn't* need to) have powershell installed.

**Comment by pjmagee** [comment]
> Hm. I'm _okay_ with allowing `install.ps1` to work on non-windows, but it shouldn't be the default. Most Linux users don't (and IMO, _shouldn't_ need to) have powershell installed.

Yeah. I agree. I would imagine the defacto would be, A heavy windows user or team, may want portability to non-windows machines and in this case, they will utilise Powershell to be more xplat friendly. 

I think its perfectly acceptable to not have the dagger one run on linux.

**Comment by wingyplus** [comment]
Do we need to check powershell version somehow to make sure it works as expected?

**Comment by levlaz** [comment]
> @levlaz out of curiosity what version of powershell is this?

I was using the latest version of Powershell 7 for Windows. Initially I
was running an older version but you can't even install the Dagger CLI
on a pre 7.0 version.

> Perhaps the install instructions need some clarification if this is
> the case? Like a sanity check for the version.

I think adding a version check as the first thing that the ps1 script
does though would be a welcome improvement.

**Comment by pjmagee** [comment]
> @levlaz out of curiosity what version of powershell is this?
> I was using the latest version of Powershell 7 for Windows. Initially I was running an older version but you can't even install the Dagger CLI on a pre 7.0 version.
> Perhaps the install instructions need some clarification if this is the case? Like a sanity check for the version.
> I think adding a version check as the first thing that the ps1 script does though would be a welcome improvement.

it does have a version check right at the top `#version 7`

![image](https://github.com/dagger/dagger/assets/292720/dfa11184-ecbf-4c51-ba6c-8ac871958281)

**Comment by pjmagee** [comment]
I have a fix for this on a PR that was to improve the Powershell install experience a bit more as it looked like the script lost functionality from previous merges somewhere down the line. https://github.com/dagger/dagger/pull/7569

**Comment by levlaz** [comment]
I upgraded to latest before running these because you can’t even install the CLI before 7.0

Lev Lazinskiy
Head of Solutions @ dagger.io ( http://dagger.io )
e: ***@***.***
p: 415.470.2142

**Comment by jedevc** [comment]
Oop, this got closed by #7569 - @levlaz does that fix your issue, or do we still need to keep this issue open?

**Comment by pjmagee** [comment]
we need to update the installation page docs because now the invoking works with `Invoke-Expression | Install-Dagger -Interactive` as an example. current documentation for install does not actually work with customising the install .

Could lev retest maybe? I am happy to improve it further if we find its still not good for Win10 / and powershell isn't somehow recognising the `#Version` requirement, I have some ideas around that using the `$PSVersion` table which is another option.

**Comment by jedevc** [comment]
@pjmagee are you able to PR the updated docs in? I can merge that update as part of our release process so the docs and script are deployed at the same time.

**Comment by pjmagee** [comment]
> @pjmagee are you able to PR the updated docs in? I can merge that update as part of our release process so the docs and script are deployed at the same time.


https://github.com/dagger/dagger/pull/7669
