### ISSUE TITLE
Dagger FAQ section 

### ISSUE THREAD

**Issue by saiyam1814** [dagger/dagger#759]
Taking from the Discord chat , there are few questions as a first time users to Dagger and I think FAQ is a great place for that 
- What are Dagger Use cases 
- What is not the goal of Dagger
- Dager vs Terraform 
- is Dagger a PAAS?
- How to integrate with other cloud providers ? 
- Dagger vs Other tools like Ketch, Epinio 
- Is Dagger limited to Kubernetes ? 
And will keep on adding more relevant questions if there are tutorials then point links to them directly. or if an answer might be too long then convert that to a guide/tutorial and add link back in FAQ. 

Thoughts @shykes

**Comment by shykes** [comment]
Hi all, I know it has been a while... We have release Dagger 0.2, and launched publicly :)

On the documentation side, we are focusing on a loose collection of standalone guides, each on their own page, which we will gradually integrate into a more rigid structure. For now at least, we think this is a good alternative to FAQ.
