### ISSUE TITLE
🐞 Builds timeout on GitHub Actions

### ISSUE THREAD

**Issue by sagikazarmark** [dagger/dagger#7593]
### What is the issue?

I've seen an increase in builds timing out on GitHub Actions recently (~since the beginning of May).

Here is an example: https://github.com/openmeterio/openmeter/actions/runs/9443871398/job/26008370834?pr=984

I don't have a strong lead, but it seems to me that runs generally hang at service executions.

### Dagger version

dagger v0.11.6 (registry.dagger.io/engine) darwin/arm64

**Comment by marcosnils** [comment]
@sagikazarmark mind sharing a Dagger Cloud URL for that run? Would it be possible to re-run it using `-vvv` to get more verbose logs?

**Comment by gerhard** [comment]
My suspicion @sagikazarmark is that this is related to:
- https://github.com/dagger/dagger/issues/7387

I am curious if this change scheduled for `v0.11.7` will make things better:
- https://github.com/dagger/dagger/pull/7452

**Comment by sagikazarmark** [comment]
This has happened for the second time since I reported the issue: https://github.com/openmeterio/openmeter/actions/runs/9455568794/job/26045641230?pr=997

It got stuck at services again. And it's missing from Dagger Cloud. (A "lot" of traces are missing from Dagger Cloud)

**Comment by sagikazarmark** [comment]
And again: https://github.com/openmeterio/openmeter/actions/runs/9460680172/job/26059928031?pr=1001

Hopefully, engine logs will be available after it times out :/

**Comment by sagikazarmark** [comment]
Okay, this is extremely annoying....

I added a timeout to the step running Dagger, but all I managed to get from the engine log is this:

```
#!/bin/sh
set -e

cat $0

# cgroup v2: enable nesting
# see https://github.com/moby/moby/blob/38805f20f9bcc5e87869d6c79d432b166e1c88b4/hack/dind#L28
if [ -f /sys/fs/cgroup/cgroup.controllers ]; then
	# move the processes from the root group to the /init group,
	# otherwise writing subtree_control fails with EBUSY.
	# An error during moving non-existent process (i.e., "cat") is ignored.
	mkdir -p /sys/fs/cgroup/init
	xargs -rn1 < /sys/fs/cgroup/cgroup.procs > /sys/fs/cgroup/init/cgroup.procs || :
	# enable controllers
	sed -e 's/ / +/g' -e 's/^/+/' < /sys/fs/cgroup/cgroup.controllers \
		> /sys/fs/cgroup/cgroup.subtree_control
fi

exec /usr/local/bin/dagger-engine --config /etc/dagger/engine.toml "$@"
Initialized empty Git repository in /var/lib/dagger/runc-overlayfs/snapshots/snapshots/10/fs/
67a5e1d28665fcd9a46f0f14a58b411c66e39a1d	refs/pull/1001/merge
Initialized empty Git repository in /var/lib/dagger/runc-overlayfs/snapshots/snapshots/193/fs/
67a5e1d28665fcd9a46f0f14a58b411c66e39a1d	refs/pull/1001/merge
Initialized empty Git repository in /var/lib/dagger/runc-overlayfs/snapshots/snapshots/211/fs/.git/
commit
```


Any way I don't have to wait for 6 hours for the step to time out?

**Comment by marcosnils** [comment]
Hey @sagikazarmark! we're releasing a new version today that we believe addresses a lot of these concerns. I'll give it another try with a fork of the repo after the release to see how it goes :pray:

**Comment by gerhard** [comment]
Pretty sure this was addressed in:
- https://github.com/dagger/dagger/pull/7452
- https://github.com/dagger/dagger/pull/7605
- https://github.com/dagger/dagger/pull/7686

Please reopen if this is still a problem @sagikazarmark 👍

FWIW:
- https://github.com/dagger/dagger/pull/7996

**Comment by sagikazarmark** [comment]
Thanks! I haven't seen timeouts recently.
