### ISSUE TITLE
Align Helm Chart version with the Dagger version + start tracking a changelog

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#7597]
We did this with all SDKs in summer 2023:
- https://github.com/dagger/dagger/discussions/5374

We should do the same for the Helm chart (it's the only odd one out) and also start a changelog for it. As discussed here:
- https://github.com/dagger/dagger/pull/7596#discussion_r1633290716

**Comment by pjmagee** [comment]
A Chart version is not the same as an Application version though, Charts can have the `appVersion` with a set default, like a dagger engine version. But if the chart is not actually changing on each release, does the chart version really have to align with the dagger cli version?

I see Chart versions as the structure of how you deploy dagger, not that it is also having to match the dagger product version. There could be many versions where nothing changes in the chart, but dagger has had many updates. This is also why I thought charts have the concept of `Version` of the Chart and `appVersion`, which can also be provided which is a sort of default for something like `values.engine.tag`.

Or do you mean to align the `appVersion` property?

**Comment by jedevc** [comment]
Having separate version streams causes a few headaches from a releasing point-of-view.

Even without those head-aches, without the same versions in place, there's an assumption that you can mix-match engine and helm chart versions freely - you can use X engine and Y helm chart. While that might be the case for *some* helm charts, there's no guarantees that that would keep working - by having the same version number, it's made clearer that this is more required.

We currently don't release the helm chart separately at all - it's part of our release process for the entire engine, released in that same weekly/fortnightly cycle. One day, we might split those out, but if they're tied together, it makes sense to keep our versions tied IMO.
