### ISSUE TITLE
🐞 TypeScript module runtime: Type Error: Cannot read properties of null (reading 'trim')

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#7614]
### What is the issue?

Have hit this when starting with a clean state, no previous Dagger Engine container running. Was reviewing:
- https://github.com/dagger/dagger/pull/7518#pullrequestreview-2110232518

This is the exact command that I was running: `dagger call image --source=.:app --token=env:GH_TOKEN`

![image](https://github.com/dagger/dagger/assets/3342/ce19ff87-be0a-49a9-84db-0d895b4e29f4)

As this is a transient issue, it might be difficult to reproduce. Creating this issue so that others can find it and/or provide more detail. 💡 It would have been useful to have a trace to link to - should have `dagger login dagger` before running this.

### Dagger version

dagger v0.11.6 (registry.dagger.io/engine) darwin/amd64

---
Mention to @TomChv via DM

**Comment by TomChv** [comment]
It seems this issue happens only sometime with no correlation between a specific setup and this issue, if anyone have this issue on every run, please provide a repro case so I can dig into that.

The failing line is in the SDK runtime:

https://github.com/dagger/dagger/blob/45c78ae659a29b79f20988735d6097c735e9c695/sdk/typescript/runtime/main.go#L266

**Comment by TomChv** [comment]
@gerhard Did you hit this issue recently with v0.12? I didn't on my side and did not see the issue recently in the CI

**Comment by TomChv** [comment]
I'm closing this issue since it seems this problem hasn't happen for couple of months. Please reopen it if it happen again.
