### ISSUE TITLE
test flake: TestContainerSystemProxies

### ISSUE THREAD

**Issue by vito** [dagger/dagger#7672]
https://dagger.cloud/dagger/traces/b8f44fb34378e1f9d5da38345ee13551?span=d826e8f9b0dc1572&logs#d826e8f9b0dc1572:L1385

```
=== FAIL: core/integration TestContainerSystemProxies/git_uses_proxy/git-proxy-logs (0.00s)

    proxy_test.go:360: 

        	Error Trace:	/app/core/integration/proxy_test.go:360

        	            				/app/core/integration/proxy_test.go:228

        	Error:      	"1718561860.060      0 10.88.0.161 NONE_NONE/000 0 - error:transaction-end-before-headers - HIER_NONE/- -\n1718561860.061      0 10.88.0.161 NONE_NONE/000 0 - error:transaction-end-before-headers - HIER_NONE/- -\n1718561865.920      1 10.88.0.162 TCP_MISS/200 302 GET http://whatup/ - HIER_DIRECT/10.88.0.159 application/octet-stream\n1718561866.133     18 10.88.0.162 TCP_TUNNEL/200 1845 CONNECT whatup:443 - HIER_DIRECT/10.88.0.159 -\n"
                                does not contain "CONNECT github.com:443"

        	Test:       	TestContainerSystemProxies/git_uses_proxy/git-proxy-logs
```

cc @sipsma - took a quick look but didn't see anything super obvious. Doesn't seem telemetry logs related since it's from `cat`ting a file in the container.

**Comment by vito** [comment]
Got another one:

https://dagger.cloud/dagger/traces/b5504a9403ac2d0f2b9105f07de71f54?span=a79872b34d6ef91c&logs#a79872b34d6ef91c:L1247

**Comment by sipsma** [comment]
Attempting a fix here but couldn't repro locally so not 100% sure yet, will leave this open for now until we haven't seen it for a while https://github.com/dagger/dagger/pull/7696

**Comment by sipsma** [comment]
I haven't seen this one since the above fix was merged, so safe to close by now I think
