### ISSUE TITLE
🐞 Regression of #7057 with v0.11.7

### ISSUE THREAD

**Issue by skycaptain** [dagger/dagger#7673]
### What is the issue?

It appears issue #7057 has recurred in v0.11.7 (also tested with the latest b213c4f88de0f4bfa164e047276d717024b78cb2). Now, it occurs with all progress modes. As before, the issue arises in CI where only `--progress=plain` is available. Long-running tasks may be canceled if nothing is printed for a certain period. It would be beneficial to have the ability to read the log while the build is running.

### Dagger version

dagger dev-071bba814c2411bb8ab5c016897210711f0f26a4 (registry.dagger.io/engine) darwin/arm64

### Steps to reproduce

https://github.com/skycaptain/dagger-issue-7057

**Comment by jedevc** [comment]
Hm, I'm not seeing anything unexpected. Do you have a gif or something similar, or a specific point that you're noticing a lack of progress?

One of the changes we made recently was a decision to hide a lot of the progress under the `initialize` step (which can often be slow). The reason for that is that it's entirely internal to the creation of a module, and isn't code that the user wrote - you can expand that though by passing more verbosity flags - `-vv` should expand more.

If you're not seeing any progress at *all*, exactly as in #7057, this could be due to mismatched client and engine versions (the automagic compatibility check to handle this is disabled in dev builds or versions built directly off of `main`).

**Comment by skycaptain** [comment]
Thanks for your hint using `-vv`. I guess it seems that the changes introduced with v0.11.7 not only hide the progress under the initialise step, but also user-written code.

I've recorded the behaviour of v0.11.6 and v0.11.7 each with and without `--progress=plain` and v0.11.7 with `-vv`. I've check that both versions are using their corresponding engine version.

#### v0.11.6

![2024-06-17 13 26 16](https://github.com/dagger/dagger/assets/1119641/b5fcb9ea-0cb9-45b7-8d08-a174d7e176d4)
![2024-06-17 13 25 03](https://github.com/dagger/dagger/assets/1119641/1bc1bfd5-bcea-49d7-aaae-aa284f6883de)

####  v0.11.7

![2024-06-17 13 08 40](https://github.com/dagger/dagger/assets/1119641/fd9167c9-c8d8-4606-87fa-9f7ae8b37a77)
![2024-06-17 13 08 10](https://github.com/dagger/dagger/assets/1119641/72352ee0-d586-4cfd-9d05-d8bbe20c94b3)

####  v0.11.7 with `-vv`

![2024-06-17 13 36 10](https://github.com/dagger/dagger/assets/1119641/9082555d-b32c-4707-91f1-260d70578839)
![2024-06-17 13 36 35](https://github.com/dagger/dagger/assets/1119641/652bbf9f-1c21-463f-aa5e-29b01aff27db)

**Comment by jedevc** [comment]
Hm, nice thanks! I can't reproduce this with the Go SDK - I wonder if there's something here about how live span logs have changed in https://github.com/dagger/dagger/pull/7452

cc @vito @helderco

**Comment by skycaptain** [comment]
You are correct. I just transcribed the code from my minimal reproducible example into Go. This function works as expected, so the issue cannot be reproduced with the Go SDK, but only with the Python SDK, as far as I know.

```go
package main

import (
	"context"

	"github.com/google/uuid"
)

type DaggerIssue struct{}

func (m *DaggerIssue) ContainerEcho(ctx context.Context) (string, error) {
	return dag.Container().From("busybox:stable-uclibc").
		WithEnvVariable("CACHE_BUSTER", uuid.New().String()).
		WithExec([]string{"sh", "-c", "for i in $(seq 1 10); do echo $i; sleep 1; done"}).
		Stdout(ctx)
}
```

**Comment by skycaptain** [comment]
With v0.11.9, the issue got worse. Now, working around this issue by using `-vv` doesn't work anymore:
 
![2024-07-02 16 10 32](https://github.com/dagger/dagger/assets/1119641/6b68f7a4-481e-4ce2-a2c4-1dda4e3a2bdb)

The Go SDK still works fine. However, at least the Python SDK is affected.

**Comment by helderco** [comment]
Checking this up now. I can see what happened in v0.11.7 with https://github.com/dagger/dagger/pull/7452. The spans were removed but they were initializing the telemetry. I'll fix it in a moment.
