### ISSUE TITLE
🐞 Unable to Publish Module due to dagger version mismatch 

### ISSUE THREAD

**Issue by levlaz** [dagger/dagger#7698]
### What is the issue?

I created a new module using dagger 0.11.7 on my laptop. When I try to publish it on Daggerverse, it complains that the highest supported go from go mod is 1.22.3

I think this is because the daggerverse is still running 0.11.6

I think we should do one or both of these things to address this:

1. Make sure that daggerverse is always running latest version of Dagger because a lot of current module authors are always running latest.
2. Handle the case when there is a version mismatch better, for example spin up a newer engine container when this happens based on engine version in dagger.json

### Dagger version

dagger v0.11.7

### Steps to reproduce

*No response*

### Log output

```
get name: input: moduleSource.asModule resolve: failed to create module: select: failed to update codegen and runtime: failed to generate code: failed to get modified source directory for go module sdk codegen: select: process "/usr/local/bin/codegen --output /src --module-context-path /src/openring/dagger --module-name openring --introspection-json-path /schema.json" did not complete successfully: exit code: 1

Stdout:
generating go module: openring
Stderr:
Error: bootstrap package: existing go.mod has unsupported version 1.22.4 (highest supported version is 1.22.3)
```

```
Creating new Engine session... OK!
Establishing connection to Engine... 20:48:05 INF Connected to engine name=185710da913438 version=v0.11.6
1   : connect
2   :   starting session
OK!
2   :   starting session DONE [0.2s]
1   : connect DONE [0.2s]

3   : moduleSource(refString: "github.com/levlaz/daggerverse/openring@v0.2.0"): ModuleSource!
4   :   cache request: git://github.com/levlaz/daggerverse#openring/v0.2.0
4   :   cache request: git://github.com/levlaz/daggerverse#openring/v0.2.0 DONE [0.4s]
5   :   git://github.com/levlaz/daggerverse#openring/v0.2.0
5   :   git://github.com/levlaz/daggerverse#openring/v0.2.0 DONE [0.8s]
3   : moduleSource: ModuleSource! DONE [1.6s]

6   : ModuleSource.asModule: Module!
```

**Comment by jedevc** [comment]
This should be resolved in 0.11.8 - we now compile using 1.22.4 in that version, so this error will go away.

This error is very annoying yes, welcome: https://github.com/dagger/dagger/issues/6706#issue-2147149550
