### ISSUE TITLE
Dagger cache can fill the disk in some situations

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#7711]
## Problem

In some situations, the Dagger cache can fill up a machine's entire disk. There is a garbage collector to prevent this, but under certain circumstances the disk can fill up anyway.

## Solution

Design a more robust system for preventing the cache from filling the disk.

**Comment by shykes** [comment]
FYI @jedevc . I left the wording very vague, because I didn't want to get the details wrong. But this is about the buildkit gc and how we use it. Including 1) the change of gc threshold from 10% to 75% of total disk space, and 2) whether the "percentage of total disk space" heuristic is adequate.

**Comment by jedevc** [comment]
Opened a proposal with a sketch of some example code as a possible way to avoid the "percentage of total disk space" heuristic that we've encountered issues with: https://github.com/moby/buildkit/pull/5079

**Comment by jedevc** [comment]
Looks like part of this was also related to https://github.com/dagger/dagger/pull/7738.

But going to keep moving the upstream PR, I think that's the road to much better defaults over all.

**Comment by vikram-dagger** [comment]
This took 11m and ate a significant percentage of the disk

```
admin@ip-172-31-46-122:~$ df
Filesystem     1K-blocks     Used Available Use% Mounted on
udev             1997996        0   1997996   0% /dev
tmpfs             401904      592    401312   1% /run
/dev/xvda1      24532104 15518220   7913608  67% /
tmpfs            2009508        0   2009508   0% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
/dev/xvda15       126678    11816    114862  10% /boot/efi
tmpfs             401900        0    401900   0% /run/user/1000
admin@ip-172-31-46-122:~$ dagger init --name=multipush --sdk=typescript
Full trace at https://dagger.cloud/dagger/traces/7d9add45978fe10b448fd46c86366778

✔ connect 1.3s
✔ cache request: mkfile /schema.json 0.0s
✔ load cache: mkfile /schema.json 0.0s
✔ cache request: blob://sha256:84f5e5fc2e7aaed03bfe831f1566ddfcd56170a8aff09fc4b820397f3f22ba79 0.0s
✔ load cache: blob://sha256:84f5e5fc2e7aaed03bfe831f1566ddfcd56170a8aff09fc4b820397f3f22ba79 0.0s
✔ moduleSource(refString: "."): ModuleSource! 0.0s
✔ ModuleSource.kind: ModuleSourceKind! 0.0s
✔ ModuleSource.resolveContextPathFromCaller: String! 0.0s
✔ ModuleSource.withName(name: "multipush"): ModuleSource! 0.0s
✔ ModuleSource.withSDK(sdk: "typescript"): ModuleSource! 0.0s
✔ ModuleSource.withInit: ModuleSource! 0.0s
✔ ModuleSource.withSourceSubpath(path: "."): ModuleSource! 0.0s
✔ ModuleSource.resolveFromCaller: ModuleSource! 2m32.8s
✔ ModuleSource.asModule(engineVersion: "latest"): Module! 5m31.9s
✔ Module.generatedContextDiff: Directory! 0.0s
✔ Directory.export(path: "/home/admin"): String! 3m13.7s

21:58:42 WRN failed to open URL url=https://dagger.cloud/dagger/traces/7d9add45978fe10b448fd46c86366778 err="exec: \"xdg-open,x-www-browser,www-browser\": executable file not found in $PATH" output=""
22:01:42 WRN failed to open URL url="https://dagger.cloud/dagger/traces/7d9add45978fe10b448fd46c86366778?span=3751f5d47785ccea" err="exec: \"xdg-open,x-www-browser,www-browser\": executable file not found in $PATH" output=""
22:05:13 WRN no LICENSE file found; generating one for you, feel free to change or remove license=Apache-2.0
Initialized module multipush in .
admin@ip-172-31-46-122:~$ df
Filesystem     1K-blocks     Used Available Use% Mounted on
udev             1997996        0   1997996   0% /dev
tmpfs             401904      592    401312   1% /run
/dev/xvda1      24532104 23193648    238180  99% /
tmpfs            2009508        0   2009508   0% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
/dev/xvda15       126678    11816    114862  10% /boot/efi
tmpfs             401900        0    401900   0% /run/user/1000
```

**Comment by jedevc** [comment]
Just wanted to write a quick explanation of what's going on here - there's probably a combination of factors, but.

- https://github.com/dagger/dagger/pull/7563 was merged which bumped the disk usage of dagger to 75% of available space.
	- The logic of this is that lots of users use dagger in virtualized environments like docker desktop - having the default set very low to what it was before meant that cache was very frequently evicted and builds rarely cached.
- However, this introduces it's own issue. The 75% is a percentage of the *total* disk, regardless of what else is using the disk. For example, if I my disk is *already* 50% full, and I start using dagger, then dagger will attempt to consume 75% of the disk (essentially attempting to use 125% of the disk).
- The solution to this is in https://github.com/moby/buildkit/pull/5079 - we need a better way to describe cache policies, in a way that allows us to account for other applications on the disk. That PR has been moving upstream, and I'm hoping to merge it soon, and start using the new policies in the next release.

This is one of the *main* things going on here - there may definitely be others.

**Comment by levlaz** [comment]
I am adding some more context based on a duplicate issue that I opened this week #8561 

I don't think any of this is net new issues, its just anotehr manifestation of the problem described in this existing issue. 

> What is the issue?
> Recently we have been noticing many examples where dagger engine aggresively uses up all available disk space and seems to never clean up after itself.

> It is not clear if this is a new regression, or if we are getting a bigger wave of larger projects, but over the last few weeks there have been many different users that report these sorts of issues.

> One example looks like this:

1. Typescript application with Typescript SDK inside roughly a 600MB git repo.
1. Running Dagger in Docker on Ubuntu
1. After a day of developing the pipeline (with likely 50-100 invocations of dagger call) the user reported ~600GB of volumes being used by the Dagger Engine.

> Another example

1. Ruby application with python SDK inside roughly a 1.2GB repo
1. Running Dagger in Docker Desktop on Mac
1. After 2 hours of pipeline development with around 25-50 invocations of dagger call the user reported 116GB of volume being used by Dagger Engine

> Dagger Should not be using up this much disk space, we need to find a way to either automatically/configure limit how much disk can be used, or figure out a way to clean things up a bit more aggressively.

> Dagger version
dagger v0.13.3 (registry.dagger.io/engine:v0.13.3) darwin/arm64

**Comment by levlaz** [comment]
> Just wanted to write a quick explanation of what's going on here - there's probably a combination of factors, but.
> 
> * [engine: bump default oci worker keep to 75% #7563](https://github.com/dagger/dagger/pull/7563) was merged which bumped the disk usage of dagger to 75% of available space.


Thanks for the explanation @jedevc! 

Is there any way to make this setting configurable? Perhaps as a short term workaround we could encourage users who are badly bitten by this issue to tweak this setting when working locally?

**Comment by rajatjindal** [comment]
Hi @shykes @jedevc , it seems like the more knobs have already been added to buildkit to support more fine grained control on cache size. 

and it seems like we can already configure that in engine.toml now.

is there anything pending on this ticket?

**Comment by jedevc** [comment]
@rajatjindal I've started work on this in https://github.com/dagger/dagger/pull/8725.

I think it should just be a plumbing exercise, so going to continue on that one myself - I'll let you know if I need a hand with it.

**Comment by aweris** [comment]
Can we use the `engine.toml` configuration while we wait for this? Our CI/CD is currently accumulating 1TB in just a few hours, which is not sustainable for us.

**Comment by jedevc** [comment]
> Can we use the `engine.toml` configuration while we wait for this? Our CI/CD is currently accumulating 1TB in just a few hours, which is not sustainable for us.

Yes.

**Comment by levlaz** [comment]
> > Can we use the `engine.toml` configuration while we wait for this? Our CI/CD is currently accumulating 1TB in just a few hours, which is not sustainable for us.
> 
> Yes.

@jedevc could you share what that would look like?

**Comment by jedevc** [comment]
> > > Can we use the `engine.toml` configuration while we wait for this? Our CI/CD is currently accumulating 1TB in just a few hours, which is not sustainable for us.
> > 
> > 
> > Yes.
> 
> @jedevc could you share what that would look like?

Sorry, I got way distracted here. The *way* of doing this is a total pain, so I've spun out some additional work in https://github.com/dagger/dagger/pull/8800 to aim to hugely simplify the process.

---

You can append to the default `engine.toml`, here:

```
debug = true
trace = false
insecure-entitlements = ["security.insecure"]
```

To use a percentage of disk space, you can append:

```toml
# engine.toml
[worker.oci]
  gc = true
  gckeepstorage = "50%"
```

Or a fixed amount of space, instead append:

```toml
# engine.toml
[worker.oci]
  gc = true
  gckeepstorage = "500GB"
```

You can start an engine with a custom `engine.toml` by using the following command from the operator manual: https://github.com/dagger/dagger/blob/055498be2ea9211f4df57b341aa0207d78e53b87/core/docs/d7yxc-operator_manual.md#L216

Just replace the path to the bind-mounted `engine.toml` with the one on your host.
