### ISSUE TITLE
🐞 v0.11.8 engine throw error: failed to get main client caller: no active session for ...

### ISSUE THREAD

**Issue by morlay** [dagger/dagger#7723]
### What is the issue?

seems some issue in dagger engine.

` c.Host().Directory()` will cause https://github.com/moby/buildkit/issues/748	too.

once I downgrade `github.com/dagger/dagger` to v0.11.7 (keep `dagger.io/dagger` v0.11.8)
everything works well.

### Dagger version

v0.11.8

**Comment by morlay** [comment]
context.Context issue

**Comment by sipsma** [comment]
Hi @morlay can you explain more what the context.Context issue was? Was it the ctx on the client side being canceled early or something? Just want to make sure I understand if something changed in v0.11.8, whether or not it's a bug on our side.

**Comment by morlay** [comment]
> Hi @morlay can you explain more what the context.Context issue was? Was it the ctx on the client side being canceled early or something? Just want to make sure I understand if something changed in v0.11.8, whether or not it's a bug on our side.

Yes. I think new engineclient.Connect (v0.11.8) handle the the cancel signal. 
Once I added `context.WithoutCancel`, everything works well.  
https://github.com/octohelm/piper/blob/main/pkg/dagger/engine.go#L62

In my usage, `dagger.Client` need keep alive until all sub tasks down.
I need to precreate the `dagger Client`s for multiple dagger engines for different archs.
