### ISSUE TITLE
🐞 Module name cannot have `@` in path name

### ISSUE THREAD

**Issue by cbochs** [dagger/dagger#7762]
### What is the issue?

When using a local directory which has an `@` in the path name (e.g `/Users/cbochs@company.com`) as the source for a dagger module, dagger seems to assume it has special meaning and fails to resolve the module. This appears to be the case with `dagger init` as well:

```
dagger init --name=test --sdk=go test@test
```

Results in

```
✔ connect 1.1s
  ✔ starting engine 1.0s
    ✔ create 1.0s
✔ moduleSource(refString: "test@test"): ModuleSource! 0.0s
✔ ModuleSource.kind: ModuleSourceKind! 0.0s
✘ ModuleSource.resolveContextPathFromCaller: String! 0.0s
! failed to stat source root: failed to stat path: failed to receive file bytes message: rpc error: code = NotFound desc = rpc error: code = NotFound desc = stat path: lstat /Users/cbochs@company.com/git/daggerverse/test: no such file or directory

Error: failed to get configured module: failed to get local root path: input: moduleSource.resolveContextPathFromCaller resolve: failed to stat source root: failed to stat path: failed to receive file bytes message: rpc error: code = NotFound desc = rpc error: code = NotFound desc = stat path: lstat /Users/cbochs@company.com/git/daggerverse/test: no such file or directory
```

### Dagger version

dagger v0.11.8 (registry.dagger.io/engine) darwin/arm64

### Steps to reproduce

Run `dagger init --name=test --sdk=go test@test`

### Log output

```
$ dagger functions -m "/Users/cbochs@company.com/git/daggerverse/passenger"
✔ connect 1.3s
  ✔ starting engine 1.2s
    ✔ create 1.2s
✘ initialize 0.1s
! failed to get configured module: failed to get module ref kind: input: moduleSource resolve: local module source root path is absolute: /Users/cbochs

  ✘ moduleSource(refString: "/Users/cbochs@company.com/git/daggerverse/passenger"): ModuleSource! 0.0s
  ! local module source root path is absolute: /Users/cbochs

Error: failed to get configured module: failed to get module ref kind: input: moduleSource resolve: local module source root path is absolute: /Users/cbochs
```

**Comment by helderco** [comment]
You can use `--name` to override. The directory name is just the default.

**Comment by jedevc** [comment]
cc @grouville since you've been in this area.

The `@` is being parsed as the module version - however, local module paths can't really have versions, so we probably shouldn't do this transformation here.

**Comment by cbochs** [comment]
If a PR is easy, it would be great to see this fixed 🙂 However, this isn't a blocker for anything running in CI. Mostly an inconvenience when running dagger locally and can be easily worked around by changing to a local working directory before calling dagger (to avoid using an absolute path for the module)
