### ISSUE TITLE
🐞 No execution of install_shell_completion in install.sh if there is no tty 

### ISSUE THREAD

**Issue by erka** [dagger/dagger#7769]
### What is the issue?

It's great to know that Dagger has shell completion. However, when running Dagger inside GitHub Actions or other CI environments, it generates additional logs without providing any benefit. It would be helpful to have an option to disable this output or automatically disable it when no TTY is available.

### Dagger version

dagger v0.11.8

**Comment by jedevc** [comment]
@erka opened a fix in #7770 - hopefully that should fix your issue when we next release and deploy the install script.

**Comment by erka** [comment]
@jedevc thank you!
