### ISSUE TITLE
🐞 TypeScript dagger engine page looks incomplete

### ISSUE THREAD

**Issue by wingyplus** [dagger/dagger#7780]
### What is the issue?

I enter the https://dagger.io/dagger-engine page and found that the TypeScript example looks incomplete (missing class, or have extra end bracket, I'm not sure).

![Screenshot 2024-06-28 163607](https://github.com/dagger/dagger/assets/484530/72b1efad-5867-4817-b9c6-12e8c115f783)

### Dagger version

dagger v0.11.9

**Comment by jedevc** [comment]
cc @TomChv @mircubed can we update this example?

**Comment by TomChv** [comment]
@mircubed We need to remove 1 of the bracket at the end of the snippet, where can I do that?

**Comment by mircubed** [comment]
Sorry for missing this. Fixed now!
