### ISSUE TITLE
🐞 Unable to init Typescript or Python modules 

### ISSUE THREAD

**Issue by levlaz** [dagger/dagger#7784]
### What is the issue?

I can generate a new go module using 

`dagger init --sdk=go` 

But when I try to use the python or typescript SDK I get similar errors. 

### Dagger version

dagger v0.11.9 (registry.dagger.io/engine) linux/amd64

### Steps to reproduce

`dagger init --sdk=python` 

or 

`dagger init --sdk=typescript` 

### Log output

# Typescript 

levlaz@framework:/tmp/ts$ dagger init --sdk=typescript
Full trace at https://dagger.cloud/levs-test-org/traces/191b1333b58c7740d776a0f5152ff284

✘ ModuleSource.asModule: Module! 20.4s
! failed to create module: select: failed to update codegen and runtime: failed to generate code: failed to call sdk module codegen: select: call function "Codegen": process "/runtime" did not complete successfully: exit code: 2

Error: failed to generate code: input: moduleSource.withContextDirectory.withName.withSDK.withSourceSubpath.asModule resolve: failed to create module: select: failed to update codegen and runtime: failed to generate code: failed to call sdk module codegen: select: call function "Codegen": process "/runtime" did not complete successfully: exit code: 2

Stdout:
invoke: failed to create codegen base: could not list rootfs entries: input: container.from resolve: failed to resolve image docker.io/library/node:21.3-alpine@sha256:3dab5cc219983a5f1904d285081cceffc9d181e64bed2a4a18855d2d62c64ccb: failed to resolve source metadata for docker.io/library/node:21.3-alpine@sha256:3dab5cc219983a5f1904d285081cceffc9d181e64bed2a4a18855d2d62c64ccb: failed to do request: Head "https://registry-1.docker.io/v2/library/node/manifests/sha256:3dab5cc219983a5f1904d285081cceffc9d181e64bed2a4a18855d2d62c64ccb": dial tcp: lookup registry-1.docker.io on 10.87.0.1:53: read udp 10.87.0.1:60444->10.87.0.1:53: i/o timeout

# Python 

levlaz@framework:/tmp/py$ dagger init --sdk=python
Full trace at https://dagger.cloud/levs-test-org/traces/d55e514006a16744271c7c0a337b9534

✘ ModuleSource.asModule: Module! 20.4s
! failed to create module: select: failed to update codegen and runtime: failed to generate code: failed to call sdk module codegen: select: call function "Codegen": process "/runtime" did not complete successfully: exit code: 2

Error: failed to generate code: input: moduleSource.withContextDirectory.withName.withSDK.withSourceSubpath.asModule resolve: failed to create module: select: failed to update codegen and runtime: failed to generate code: failed to call sdk module codegen: select: call function "Codegen": process "/runtime" did not complete successfully: exit code: 2

Stdout:
marshal: json: error calling MarshalJSON for type *dagger.GeneratedCode: input: container.from resolve: failed to resolve image docker.io/library/python:3.11-slim@sha256:ce81dc539f0aedc9114cae640f8352fad83d37461c24a3615b01f081d0c0583a: failed to resolve source metadata for docker.io/library/python:3.11-slim@sha256:ce81dc539f0aedc9114cae640f8352fad83d37461c24a3615b01f081d0c0583a: failed to do request: Head "https://registry-1.docker.io/v2/library/python/manifests/sha256:ce81dc539f0aedc9114cae640f8352fad83d37461c24a3615b01f081d0c0583a": dial tcp: lookup registry-1.docker.io on 10.87.0.1:53: read udp 10.87.0.1:46223->10.87.0.1:53: i/o timeout

**Comment by helderco** [comment]
Possibly you had the go image cached and did this during a network issue.


![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNDN5dHVkMWVtcWdxMjAybjh3cGE0dG8wdHppZW5yZzJzZWh3cG85bCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/DUtVdGeIU8lmo/giphy.gif)

**Comment by levlaz** [comment]
Yeah it's possible. But this is very strange because I have no problem connecting to either dockerhub or any other site, the network issues seems to only exist in the context of running dagger commands. 

I tried switching to other networks and it did not help.

**Comment by levlaz** [comment]
Closing since it was a local issue, still unclear what the root cause is.
