### ISSUE TITLE
🖐️ How to install python dependencies for pipeline

### ISSUE THREAD

**Issue by LuminatiHD** [dagger/dagger#7816]
### What happened? What did you expect to happen?

I use dagger with python. Dependencies are managed by poetry. There is a certain library I want to use in my dagger pipeline, but no matter what I try, nothing seems to work. Any ideas?

**Comment by LuminatiHD** [comment]
I tried it and it doesn't work :/
Just to absolutely avoid any misunderstanding, I do not mean creating a container w/ all dependencies and running it there (which works fine), I mean importing the library directly in the pipeline file.

**Comment by helderco** [comment]
> I mean importing the library directly in the pipeline file.

Yes, I understand.

> I tried it and it doesn't work :/

Can you show what steps you're taking?

**Comment by helderco** [comment]
Would be helpful to know which dependency you're trying to add, to double check on possible constraints from that package as well.

**Comment by LuminatiHD** [comment]
Oh I see, I have seemed to have mixed a few things up. You see,I have a poetry file for all dependencies related to the script, and I tried to install it by changing that, and I didn't see that dagger configures one specifically for managing the dependencies for its pipeline.
Everything works now. Thanks for your help.
