### ISSUE TITLE
✨ Support downloading modules from other git hosters

### ISSUE THREAD

**Issue by LuminatiHD** [dagger/dagger#7878]
### What are you trying to do?

Since the dagger documentation only mentions installing modules from github, I tested if you could also install a module from another git hoster, like gitlab in my example. I tried installing from a repository with a path of the form `group/subgroup_1/subgroup_2/project`. But since dagger (probably) assumes the repo path to be like github's, as in `<user_or_org>/project`, it tried to pull the project `group/subgroup_1`, which obviously doesn't exist.

### Why is this important to you?

I think it's generally a good idea to support other git hosters. Gitlab in particular would be great, since it would allow one to set access permissions to certain pipeline modules.

### How are you currently working around this?

As pointed out, I only did this as a test, so for me, there isn't really a problem to sidestep at the moment.

**Comment by grouville** [comment]
Hi 👋 
Can you please provide the corresponding ref you are using ? This should work 👀

**Comment by LuminatiHD** [comment]
Oh I see. Yes, it is a private group. Using your fix works, except that now it fails with what I assume is an authentication issue. But as you said, you're already working on that. Thanks a lot for your help.

**Comment by bradfordwagner** [comment]
@grouville I'm very excited to see enterprise use cases picked up with private git hosters. As part of this feature can we make sure that Azure Devops is supported? It requires token injection to work w/ https here's a sample gitconfig with some redaction:
```
[url "https://anything:{{ ado_pat }}@dev.azure.com"]
  insteadOf = "https://{{ org }}@dev.azure.com"
```

**Comment by grouville** [comment]
> Browser urls: https://dev.azure.com/{{ org }}/{{ project }}/_git/{{ git_repo }}

Hey @bradfordwagner, your use-case should work right now
