### ISSUE TITLE
🐞Terminal() does not work with custom CA certificates

### ISSUE THREAD

**Issue by Vermillionaire** [dagger/dagger#7910]
### What is the issue?

When calling Terminal() on a dagger engine with custom certs mounted in `/usr/local/share/ca-certificates` it either exits or times out. I have tested with a normal dagger runner and a custom runner without the mounted certificates and there are no issues. I believe it also affects the `-i` command because nothing happens when running that command with custom certs.

### Dagger version

v0.12.0

### Steps to reproduce

Follow these instructions to setup a runner with a custom CA: https://docs.dagger.io/manuals/administrator/custom-runner/#custom-ca-certs. Using the sleep to see if I can trigger the timeout.

Have been using this function to test:
```
// Returns a container that echoes whatever string argument is provided
func (m *TestDagger) ContainerEcho(java string) *dagger.Container {
	return dag.Container().From("ubuntu:latest").
		WithExec([]string{"apt-get", "update", "-y"}).
		WithExec([]string{"sleep", "120"}).
		WithExec([]string{"apt-get", "install", "-y", "maven", "git", fmt.Sprintf("openjdk-%s-jdk", java)}).
		Terminal()
}
```

### Log output

This is the log output most of the time. Terminal just exits
------------------------------------------

dagger call container-echo --java 17
● Attaching terminal: 
    container: Container!
    Container.from(address: "ubuntu:latest"): Container!
    Container.withExec(args: ["apt-get", "update", "-y"]): Container!
    Container.withExec(args: ["sleep", "120"]): Container!
    Container.withExec(args: ["apt-get", "install", "-y", "maven", "git", "openjdk-17-jdk"]): Container!

exit 1
Setup tracing at https://dagger.cloud/traces/setup. To hide: export NOTHANKS=1

✔ connect 0.2s
✔ initialize 6.2s
✔ prepare 0.0s
✔ testDagger: TestDagger! 0.0s
✔ TestDagger.containerEcho(java: "17"): Container! 2m55.3s
✔ Container.sync: ContainerID! 0.0s
✔ Container.defaultArgs: [String!]! 0.0s
✔ Container.mounts: [String!]! 0.0s
✔ Container.entrypoint: [String!]! 0.0s
✔ Container.platform: Platform! 0.0s
✔ Container.user: String! 0.0s
✔ Container.workdir: String! 0.0s

_type: Container
defaultArgs:
    - /bin/bash
entrypoint: []
mounts: []
platform: linux/amd64
user: ""
workdir: ""

This happens very rarely. Haven't been able to reproduce
--------------------------------------------------------------

dagger call container-echo --java 11
● Attaching terminal: 
    container: Container!
    Container.from(address: "ubuntu:latest"): Container!
    Container.withExec(args: ["apt-get", "update", "-y"]): Container!
    Container.withExec(args: ["sleep", "120"]): Container!
    Container.withExec(args: ["apt-get", "install", "-y", "maven", "openjdk-11-jdk"]): Container!

exit 1
Setup tracing at https://dagger.cloud/traces/setup. To hide: export SHUTUP=1

✔ connect 0.3s
✔ initialize 23.6s
✔ prepare 0.0s
✔ testDagger: TestDagger! 0.0s
✘ TestDagger.containerEcho(java: "11"): Container! 2m49.4s
! call function "ContainerEcho": process "/runtime" did not complete successfully: exit code: 2
┃ marshal: json: error calling MarshalJSON for type *dagger.Container: input: container.from.withExec.withExec.withExec.terminal resolve: terminal se
┃ ion failed: io: read/write on closed pipe                                                                                                          
  ✔ Container.from(address: "ubuntu:latest"): Container! 0.7s
  ✔ Container.withExec(args: ["apt-get", "update", "-y"]): Container! 3.5s
  ✔ Container.withExec(args: ["sleep", "120"]): Container! 2m4.3s
  ✔ Container.withExec(args: ["apt-get", "install", "-y", "maven", "openjdk-11-jdk"]): Container! 2m44.0s
  ✘ Container.terminal: Container! 2m47.0s
  ! terminal session failed: io: read/write on closed pipe
    ✔ start sh 2m47.0s

Error: invalid selection for command "container-echo": response from query: input: testDagger.containerEcho resolve: call function "ContainerEcho": process "/runtime" did not complete successfully: exit code: 2

Stdout:
marshal: json: error calling MarshalJSON for type *dagger.Container: input: container.from.withExec.withExec.withExec.terminal resolve: terminal session failed: io: read/write on closed pipe
Run 'dagger call container-echo --help' for usage.

**Comment by sipsma** [comment]
Thanks for reporting! 

Just off the top of my head I can probably imagine what's going on here. Custom CAs have to wrap container execution in extra execs to setup/teardown CAs, which is mostly likely confusing the terminal code (it probably hits the setup exec first and then exits right away, skipping the actual container the terminal should be opened in).

Will fix for v0.12.1 and add integ tests for this combo of custom CA + terminal.
