### ISSUE TITLE
🐞 `--progress=plain` output verbosity is higher in v0.12.0

### ISSUE THREAD

**Issue by nipuna-perera** [dagger/dagger#7913]
### What is the issue?

There were some work done to clean up the `--progress=plain` output to improve clarity in `v0.11.x`. However, it seems to have regressed in 0.12.0. Now the output displays codegen and introspection steps which can be considered noise in most instances. 

Discord discussion: https://discord.com/channels/707636530424053791/1261532210205294702

### Dagger version

dagger v0.12.0 (registry.dagger.io/engine) darwin/arm64

### Steps to reproduce

Run `dagger call mymodule --progress=plain`

**Comment by jedevc** [comment]
Got a fix for this in #8018.

Also noticed that recently the plain progress has started looking *quite* odd - with spans magically re-appearing after completion. This is fixed in https://github.com/dagger/dagger/pull/7956.
