### ISSUE TITLE
🐞 `dagger version` inconsistent behavior (disappears) in v0.12.0

### ISSUE THREAD

**Issue by nipuna-perera** [dagger/dagger#7914]
### What is the issue?

`dagger version` does not seem to always print the version. I see something flashing on the screen and disappear. If I keep 
running it, the version may be shown intermittently but most of the time it prints a blank.

### Dagger version

dagger v0.12.0 (registry.dagger.io/engine) darwin/arm64

### Steps to reproduce

`dagger version`. Run it a few times. Observe output.

**Comment by rajatjindal** [comment]
I observed same behavior as well. and it may be related to the interactive terminal UI. 

would it make sense to disable the interactive UI for commands such as `version` or `help`? 

Thanks
Rajat Jindal
