### ISSUE TITLE
Don't need to report no HEAD commit on `dagger init` for a new git repo with just a `.git/` dir and no other files

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#7918]
If you start with an empty directory and `git init` you'll end up with a `.git/` dir.

If you run `dagger init --sdk typescript`, for example, you'll get this:

```
dv ➤ dagger init --sdk typescript                                                          git:main
2024/07/14 09:49:41 WARN failed to get repo HEAD err="reference not found"
...
```

**Comment by TomChv** [comment]
Yes this is because the git directory has no repo to commit on, it's common to every SDK and I think it's a normal behaviour?

**Comment by jedevc** [comment]
Yup this is common to every SDK, but probably still worth explicitly handling this case of an empty git repo.

> it's a normal behaviour

I think the proposal is to remove this behaviour :tada:
