### ISSUE TITLE
'dagger login' broken in 0.12

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#7920]
## Problem

- In Dagger 0.12, `dagger login` prints an auth URL, but doesn't let me click on it. I also can't select any text anywhere in that terminal window.
- After I exit the TUI with `q` or `ctrl-C`, the link becomes clickable *BUT* at that point it's too late to click it. The auth process must take place while the TUI is running. **The only solution is to manually enter the URL in the browser while the TUI is running, and complete the auth process**
- If I exit the TUI and follow the printed link, the web auth process will succeed (my account is created), but it doesn't send me to my Cloud dashboard - it just prints "Congratulations! You're all set", which 1) is incorrect since the CLI failed to authenticate, and 2) gives me no further action to take.
- At the end of this process, the CLI is not visibly broken. Everything will appear to work. I just won't be logged in in the CLI. The `w` keystroke in TUI will send me to `https://github.com/traces/setup` which, since my browser is logged in, will redirect me to my list of traces. Then I will look for my trace, not find it, and be confused.

I tried this on 2 different terminal emulators (Zed and Ghostty on MacOS).

## Solution

1. **Make the login link clickable from the TUI**
2. default `dagger login` to open a browser directly, when the environment allows it. This creates an additional fallback
3. Make it easier to verify whether a CLI is logged in or not
4. Make the CLI auth flow more clear on the web side (don't tell me "I'm all set" if the CLI never actually authenticated). Or at least, redirect me to a useful place like my dagger.cloud dashboard

## Workarounds

- `dagger login`, keep the TUI running, manually copy the URL
- On MacOS: `dagger login`, take a screenshot of the terminal, click the link from the screenshot

**Comment by shykes** [comment]
This is pretty bad.

**Comment by shykes** [comment]
I think we should consider bypassing the TUI altogether for `dagger login`, we don't use its features at all, and it seems to be part of the problem in this particular case. Instead of going down a rabbit hole trying to fix clickable links in TUI for all commands, might be faster to just re-implement `dagger login` with good old `printf`?

**Comment by marcosnils** [comment]
until this gets addressed, another workaround should be using `--progress plain` @shykes

**Comment by shykes** [comment]
> until this gets addressed, another workaround should be using `--progress plain` @shykes 

I tried but it hung & printed nothing for me. Does it work for you?

**Comment by jpadams** [comment]
As I mentioned in Discord, I unconciously did a hover+CMD on my mac to turn the link clickable
![hover_cmd_click](https://github.com/user-attachments/assets/c684eacd-1ae4-434f-8af4-b1a4cf107656)

**Comment by marcosnils** [comment]
> I tried but it hung & printed nothing for me. Does it work for you?

you're correct. It only prints something when you press ctrl +c. You can ignore my comment :grimacing:

**Comment by vito** [comment]
fixed by:

* https://github.com/dagger/dagger/pull/7932
* https://github.com/dagger/dagger/pull/7928
