### ISSUE TITLE
Add documentation for Enum

### ISSUE THREAD

**Issue by TomChv** [dagger/dagger#7921]
### What is the issue?

https://github.com/dagger/dagger/pull/7498 has been merged and released for 0.12, now we need to add some docs :D

**Comment by mihaelTBTL** [comment]
An interesting property I ran into with the Python SDK and getting help on my functions is that the Enum description is used as the argument description if I'm not using `typing.Annotated` and `dagger.Doc`. 
Piggy-backing off of the [blogpost](https://dagger.io/blog/dagger-0-12#enum-support), now I don't need to write:

```python
@dagger.function
    async def scan(self, severity: Annotated[Severity, Doc('Vulnerability severity levels')]) -> str:
```
That description will be automatically picked up from the Enum description, so it's enough to do:
```python
@dagger.function
    async def scan(self, severity: Severity) -> str:
```

It's a cool feature that might be worth a mention!
