### ISSUE TITLE
Env variable interpolation in more functions

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#7951]
## Problem

`Container.withEnvVariable` can expand env variables with an optional `expand` argument (#7171). But this is not supported in other Container operations that may need it:

- `withExec` (expand variables in `args`)
- `withFile`, `withNewFile`, `withDirectory`, `withoutDirectory`, `withoutFile`, `withMountedXXX`... (expand variables in `path`)

I have personally needed this argument in `withExec` and `withNewFile`

## Solution

Add an optional `expand` argument to all the `Container` functions that need it, with the same behavior as in `withEnvVariable`.

**Comment by jeremywitte** [comment]
This tripped me up recently when trying to use the default **bun** install cache directory:

```Go
WithMountedCache("~/.bun/install/cache", dag.CacheVolume("bun-cache"))
```

Expanding the tilde reference here would be helpful as overriding the default cache dir with **bun** requires writing a `bunfig.toml` file 📖 https://bun.sh/docs/install/cache. 

This is less of an issue for other tools that offer an env variable configuration.

**Comment by shykes** [comment]
I bumped into this again (`WithExec`)

**Comment by rajatjindal** [comment]
The first testcase I chose for this change is `WithNewFile` and have a question about it: 

do we want to expand env variable only on the path or also the contents? I can see argument both ways. 

If we do it for contents also, then we would also need a way to differentiate between if user wants this variable expansion during creation of the file or at runtime (e.g. when writing a shell script using `WithNewFile`).

maybe have two different variables for this usecase e.g. `ExpandInPath` and `ExpandInContents`?

**Comment by helderco** [comment]
I would do it only on the path (`ExpandPath`). If there's demand for doing it in the contents for some reason, we could add another option for it later.

**Comment by marcosnils** [comment]
> I would do it only on the path (with `ExpandPath` for clarity, if there's the possibility of adding to contents later). If there's demand for doing it in the contents for some reason, we could add another option for it later.

I'm ok with moving forward to expanding only the path if the flag is called ExpandPath. So I guess we can implement that first as it seem to be what's currently hurting

**Comment by shykes** [comment]
Let's do this:

- `Expand` should exist consistently, including in `WithNewFile`
- In the special case of `WithNewFile`, let's make the default behavior "expand in path only".
- If people ask to expand in the contents, we can add an additional flag just for that

**Comment by jedevc** [comment]
This was fixed in https://github.com/dagger/dagger/pull/8427 :tada:
