### ISSUE TITLE
`dagger -m ./foo` does not return an error when module FOO doesn't exist

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#7961]
## Problem

If I call `dagger -m ./foo functions`, and `./foo` doesn't exist, Dagger fails to let me know, and loads the current module instead.

**Comment by grouville** [comment]
`dagger call` might probably be affected too 👀

**Comment by helderco** [comment]
Yeah, this needs fixing.

**Comment by grouville** [comment]
https://github.com/dagger/dagger/pull/7609 had a fix for that.

Introducing a parseRef function that maps our `parseRefString` implementation and makes it generic with a generic bk.client: https://github.com/dagger/dagger/blob/27d90e36390f550a16a775be5563d39af89e825b/engine/vcs/parse_ref.go#L20-L32

**Comment by grouville** [comment]
Closed by #8193
