### ISSUE TITLE
✨ Cannot update SDK when using newer version of Dagger

### ISSUE THREAD

**Issue by noah-troncoso** [dagger/dagger#7964]
### What are you trying to do?

I updated from 0.11.8 to 0.12.0 in a Typescript project. Of course there were some breaking changes, but my IDE and other checks didn't pick up anything. This is because the SDK that is downloaded in my module was still for 0.11.8. Well, I couldn't for the life of me figure out how to update the SDK. I can't find anything in documentation, and if the CLI has a tool for this, I can't find it. Performing `dagger init` again just says it's already been initialized.

### Why is this important to you?

I think the importance of this is pretty obvious.

### How are you currently working around this?

What I ended up having to do was create a new directory, initialize a dagger project, then copy that new sdk to my original project.

**Comment by helderco** [comment]
What you want is `dagger develop`. That'll re-generate the files for the module.

**Comment by noah-troncoso** [comment]
Thank you. I guess this is a documentation request then, because I can't find that anywhere.

**Comment by helderco** [comment]
Since you mentioned the IDE not picking up on changes, see [IDE Integration](https://docs.dagger.io/manuals/developer/ide-integration).

**Comment by TomChv** [comment]
Hey @noah-troncoso, did you find a fix for your IDE integration?

**Comment by samalba** [comment]
Closing, feel free to re-open @noah-troncoso if you need help.
