### ISSUE TITLE
🖐️ Load Dagger module from private Github repository via PAT auth.

### ISSUE THREAD

**Issue by zhaopengdirk** [dagger/dagger#7990]
### What happened? What did you expect to happen?

We tried to load Dagger module from our private Github repository but failed. We'd like to know whether this capability supported now? Or is there any plan to support this in the future? By the way, our company only allows PAT auth to do this.

**Comment by grouville** [comment]
Hey 👋 It's coming here: https://github.com/dagger/dagger/pull/7708

**Comment by Jim-ent** [comment]
I am looking for the same feature. @grouville [#7708](https://github.com/dagger/dagger/pull/7708) seems only for ssh auth, any plans for https?

**Comment by grouville** [comment]
> I am looking for the same feature. @grouville [#7708](https://github.com/dagger/dagger/pull/7708) seems only for ssh auth, any plans for https+PAT token?

Hello everyone 👋 

I am starting to implement it. Would mounting the `.netrc` from the host be a nice solution for your use-case ? cc @nipuna-perera

There is also a path to supporting git credential manager but is going to be a bit more work. Would the netrc file be a nice stopgap ?

**Comment by nipuna-perera** [comment]
> > I am looking for the same feature. @grouville [#7708](https://github.com/dagger/dagger/pull/7708) seems only for ssh auth, any plans for https+PAT token?
> 
> Hello everyone 👋
> 
> I am starting to implement it. Would mounting the `.netrc` from the host be a nice solution for your use-case ? cc @nipuna-perera
> 
> There is also a path to supporting git credential manager but is going to be a bit more work. Would the netrc file be a nice stopgap ? I am trying to estimate all the use-cases / potential DX that could be occuring

I have not used .netrc for git auth. When you say mount, do you mean an automatic mount of the global netrc? If so, is there a chance that could mess with other local settings? I am afraid it will add additional work for consumers. I would love to have support for GCM as that's one of the ways we get everyone to set up for git. 

One example of a very smooth integration I've seen so far is how devcontainers handle transferring git auth into the container if you want to take inspiration. 

I am out on vacation this week so apologies in advance if I'm not responding timely. But I am very excited this is finally being worked on!

**Comment by grouville** [comment]
> One example of a very smooth integration I've seen so far is how devcontainers handle transferring git auth into the container if you want to take inspiration.

Thank you for the feedback 🙏 I'll definitely take a look. That's exactly what I needed 👌

**Comment by Jim-ent** [comment]
I prefer credential manager as well since that's what I saw most path developers in my group applied.

**Comment by cndoit18** [comment]
Hi, any updates?

**Comment by grouville** [comment]
> Hi, any updates?

Hi @cndoit18,
I am currently on it. I had to fix a few bugs regarding the SSH support and now I am free to allocate on my time on this 🙏

**Comment by sheldonhull** [comment]
In my case, it's private azure devops repos. So for many folks they'd get an oauth SSO from microsoft and that would do it. Ideally no PAT input required, so it uses just the credential provider and can allow the oauth browser to open if a user is running it directly too. Just mentioning this for some context as you pointed me to this from discord [message link](https://discord.com/channels/707636530424053791/1286428571337883688/1286703792498278483)

**Comment by grouville** [comment]
> In my case, it's private azure devops repos. So for many folks they'd get an oauth SSO from microsoft and that would do it. Ideally no PAT input required, so it uses just the credential provider and can allow the oauth browser to open if a user is running it directly too. Just mentioning this for some context as you pointed me to this from discord [message link](https://discord.com/channels/707636530424053791/1286428571337883688/1286703792498278483)

Hey @sheldonhull, thanks for the feedback 🙏 Ok, so a oauth SSO from microsoft. This should be supported when relying on the git-credential-manager standard. Do you all authenticate using SSO when using git ? Or at least, does it trigger the auth step when cloning ?

**Comment by sheldonhull** [comment]
> > In my case, it's private azure devops repos. So for many folks they'd get an oauth SSO from microsoft and that would do it. Ideally no PAT input required, so it uses just the credential provider and can allow the oauth browser to open if a user is running it directly too. Just mentioning this for some context as you pointed me to this from discord [message link](https://discord.com/channels/707636530424053791/1286428571337883688/1286703792498278483)
> 
> 
> 
> Hey @sheldonhull, thanks for the feedback 🙏 Ok, so an oauth SSO from microsoft. This should be supported when relying on the git-credential-manager standard. Do you all authenticate using SSO when using git ? Or at least, does it trigger the auth step when cloning ? 

Trying to do this without using hardcoded name:token in the string. 

https://learn.microsoft.com/en-us/azure/devops/repos/git/set-up-credential-managers?view=azure-devops


```
dagger functions -m dev.azure.com/MYORG/MYREPO/_git/daggerverse.git/tf-yolo@main
✔ connect 0.4s
✘ initialize 0.5s
! failed to get configured module: failed to get module ref kind: input: moduleSource resolve: failed to resolve git src to commit: failed to load cache key: failed to fetch remote https://dev.azure.com/MYORG/MYREPO/_git/daggerverse.git: git error: exit status 128
  ✘ resolving module ref 0.5s
  ! failed to get configured module: failed to get module ref kind: input: moduleSource resolve: failed to resolve git src to commit: failed to load cache key: failed to fetch remote https://dev.azure.com/MYORG/MYREPO/_git/daggerverse.git: git error: exit status 128
    ✘ moduleSource(refString: "dev.azure.com/MYORG/MYREPO/_git/daggerverse.git/tf-yolo@main"): ModuleSource! 0.4s
    ! failed to resolve git src to commit: failed to load cache key: failed to fetch remote https://dev.azure.com/MYORG/MYREPO/_git/daggerverse.git: git error: exit status 128
      ✘ cache request: git://dev.azure.com/MYORG/MYREPO/_git/daggerverse.git#main 0.4s
      ! failed to fetch remote https://dev.azure.com/MYORG/MYREPO/_git/daggerverse.git: git error: exit status 128

Error: failed to get configured module: failed to get module ref kind: input: moduleSource resolve: failed to resolve git src to commit: failed to load cache key: failed to fetch remote https://dev.azure.com/MYORG/MYREPO/_git/daggerverse.git: git error: exit status 128
stderr:
fatal: could not read Username for 'https://dev.azure.com': terminal prompts disabled

```

So i've tried variations. The credential provider does support an oauth workflow so if that's possible let me know

**Comment by sheldonhull** [comment]
following up. Is this still in the works @grouville? cheers

**Comment by grouville** [comment]
> following up. Is this still in the works @grouville? cheers

Hello @sheldonhull,
Thanks for the ping 🙏 I have a working prototype now. I am slicing everything in a few PRs that will come along this week 👼
