### ISSUE TITLE
Details on status of dagger.Host in SDK docs

### ISSUE THREAD

**Issue by mihaelTBTL** [dagger/dagger#7998]
### What is the issue?

When working on Python pipelines with Dagger, I frequently reference the [SDK's documentation](https://dagger-io.readthedocs.io/en/sdk-python-v0.12.1/), and it's a very helpful resource. During my work, I discovered the [dagger.Host object](https://dagger-io.readthedocs.io/en/sdk-python-v0.12.1/client.html#dagger.Host)  and the [dagger.Client.host method](https://dagger-io.readthedocs.io/en/sdk-python-v0.12.1/client.html#dagger.Client.host), which suggested that these could be used to retrieve host information.

However, I encountered an issue in practice where the following code snippet.

```python
@function
def get_host(self) -> dagger.Host:
    return dag.host()
```
throws the error:
```
AttributeError: module 'dagger' has no attribute 'Host'
```
I couldn't type hint the function since it doesn't recognize the existence of a `dagger.Host` type.

After modifying the function to return a `dagger.Directory` to avoid type hint issues:
```python
@function
def get_host_dir(self) -> dagger.Directory:
    return dag.host().directory('.')
```
I encountered a similar error:
```
Function execution error: 'Client' object has no attribute 'host'
```
This led me to believe that the `host`-related stuff may have been removed from the SDK.

Further research led me to this PR (#6535) which seems to be the answer to my question.

Using the following code:
```python
@function
def get_host(self) -> dagger.Directory:
    return dag.current_module().source()
```
would now return that module's directory.

If my understanding is correct, `Host` is a thing of the past and these are just leftovers in the documentation that weren't removed?

I took a look at Go SDK docs and [Client.Host()](https://pkg.go.dev/dagger.io/dagger#Client.Host) is also listed there without any details on its removal on end-user side. I got an impression it's a thing I can use.

Should the `Host`-related stuff be removed from the documentation, or at least be updated with a more detailed description and a redirect to `CurrentModule`? I could use and would appreciate more details on this in the documentation.

**Comment by helderco** [comment]
That's just the **reference documentation**, it doesn't have the whole picture. It's expected that you rely more on the [Dagger docs](https://docs.dagger.io) for learning. In this case in particular, see [Execution Environment](https://docs.dagger.io/manuals/developer/execution-environment).

To answer your question, `Client.host` is not deprecated, just not available in Dagger Modules, but still usable when not using Modules.

**Comment by mihaelTBTL** [comment]
I see, what would be other ways of using Dagger outside of Modules? I can think of sending GraphQL queries to the Dagger Engine, but is there something else other than that? So far, I was rather focused on development with the SDK and modules seemed to be the thing.

**Comment by helderco** [comment]
Some people haven't migrated to Modules yet. Running Dagger pipelines directly from the host is now considered an advanced/niche use case, but still allowed. Right now, the big downside to that is that it's not easy to interact with Modules yet. You can do it with raw GraphQL queries but you won't get generated client bindings for the Modules that you want to use (e.g., `dag.trivy()`). We plan on having this fixed though.

Main advantage for this use case is that you have direct access to your host's resources (files, env vars, etc...). Also, some users want to craft a custom client rather than use `dagger call` directly, for their specific needs.

**Comment by mihaelTBTL** [comment]
Thanks for the clarification. I suppose once #7647 gets merged in, we'll be wanting even less for something like `dag.host()` in Modules since it solves the number 1 reason (more convenient access to project files) we tried to turn to something like that. 

My initial puzzle is cleared up so I'll close this issue, but I think it could be useful to denote stuff not available through Modules as such in SDK docs. Since modules will be the entrypoint to Dagger for most newcomers, I believe more mix-ups like this are bound to happen.
