### ISSUE TITLE
🐞 No completion is installed when I install though homebrew

### ISSUE THREAD

**Issue by remyleone** [dagger/dagger#8036]
### What is the issue?

When I install dagger using homebrew:

```
$ brew reinstall dagger             
==> Fetching dagger/tap/dagger
==> Downloading https://dl.dagger.io/dagger/releases/0.12.2/dagger_v0.12.2_darwin_arm64.tar.gz
Already downloaded: /Users/rleone/Library/Caches/Homebrew/downloads/99fd18c03c229447e23557d450e1036a51b6d58dc24084bffb8d4b3c57b8df6b--dagger_v0.12.2_darwin_arm64.tar.gz
==> Reinstalling dagger/tap/dagger 
🍺  /opt/homebrew/Cellar/dagger/0.12.2: 5 files, 25.9MB, built in 1 second
==> Running `brew cleanup dagger`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

I don't see any messages related to installation of the completion scripts and no completion is enabled in either shells.

### Dagger version

dagger v0.12.2 (registry.dagger.io/engine) darwin/arm64

### Steps to reproduce

brew install dagger

**Comment by samalba** [comment]
What shell are you using? I just tried this and the completion is installed properly for my shell (zsh).

Alternatively you can easily generate the completion for your shell using `dagger completion <shell>` (check the help `dagger completion --help`)

**Comment by remyleone** [comment]
I'm also using zsh on macos with homebrew. I've retried and it still does not work. 
I think the reason is related to the fact that no shell completion is mentioned here: https://github.com/dagger/homebrew-tap/blob/main/dagger.rb

**Comment by samalba** [comment]
I tried to repro with the latest version (v0.12.4) and it works just fine, both on zsh and bash.

Note that you need to load the site-functions from homebrew explicly from your zsh config: https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh

I started blank from a zsh with no config:

```sh
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
autoload -U compinit
compinit -D
```

```sh
dagger <TAB>
-------> completions
call        -- Call one or more functions, interconnected into a pipeline
completion  -- Generate the autocompletion script for the specified shell
config      -- Get or set module configuration
develop     -- Prepare a local module for development
functions   -- List available functions
help        -- Help about any command
init        -- Initialize a new module
install     -- Install a dependency
login       -- Log in to Dagger Cloud
logout      -- Log out from Dagger Cloud
query       -- Send API queries to a dagger engine
run         -- Run a command in a Dagger session
version     -- Print dagger version
```

I'll close this but feel free to re-open if you still have the issue.
