### ISSUE TITLE
How to use custom Package Managers configurations

### ISSUE THREAD

**Issue by eralumin** [dagger/dagger#8056]
### What is the issue?

I am trying to use custom Yarn and NPM corporate registries with remote Dagger Engine. Currently my `.yarnrc.yml` and `.npmrc` on local are configured to work with my company proxies and registries settings.

But since I don't have the possibility to get Docker on my laptop, I need to run jobs on a remote Server.
Those package managers configurations are not passed to the Dagger Remote Engine.

I am currently trying to see if I can use some environments variables in the dagger engine container to fix my issue.

Here is how we can apparently set environment variables for:
- **NPM**: `NPM_CONFIG_<UPPER_LONG_NAME>` (Im not sure, need validation)
  https://docs.npmjs.com/cli/v10/using-npm/config#environment-variables
- **Yarn V1**: Seems to use NPM Config (need validation).
  https://classic.yarnpkg.com/en/docs/envvars
- **Yarn V2/V3/V4**: `YARN_<UPPER_LONG_NAME>`
  https://yarnpkg.com/configuration/yarnrc
  > Finally, note that most settings can also be defined through environment variables (at least for the simpler ones; arrays and objects aren't supported yet). To do this, just prefix the names and write them in snake case: YARN_CACHE_FOLDER will set the cache folder (such values will overwrite any that might have been defined in the RC files - use them sparingly).
- **PIP**: `PIP_<UPPER_LONG_NAME>` (need validation)
  https://pip.pypa.io/en/stable/topics/configuration/#environment-variables
  > pip’s command line options can be set with environment variables using the format PIP_<UPPER_LONG_NAME> . Dashes (-) have to be replaced with underscores (_).
- **GO**: ?
- **Cargo**: `CARGO_<UPPER_LONG_NAME>` (need validation)
  https://doc.rust-lang.org/cargo/reference/config.html#environment-variables
  > Cargo can also be configured through environment variables in addition to the TOML configuration files. For each configuration key of the form foo.bar the environment variable CARGO_FOO_BAR can also be used to define the value. Keys are converted to uppercase, dots and dashes are converted to underscores. For example the target.x86_64-unknown-linux-gnu.runner key can also be defined by the CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER environment variable.
Environment variables will take precedence over TOML configuration files. Currently only integer, boolean, string and some array values are supported to be defined by environment variables. [Descriptions below](https://doc.rust-lang.org/cargo/reference/config.html#configuration-keys) indicate which keys support environment variables and otherwise they are not supported due to [technical issues](https://github.com/rust-lang/cargo/issues/5416).

**Comment by eralumin** [comment]
I think documentation should help people to take the best solution to make dagger work in corporate network with proxy and others stuff.

To be honest I don't know what could be the best solution:
- Handling this at the engine level? What if the dev have error because of that and doesn't the current Engine configuration use custom settings?
- At the project level? By importing a custom library with defaults corporate settings to use during a run?
- Anything else?

**Comment by TomChv** [comment]
Hey, there's a PR related to typescript to support package manager configuration: https://github.com/dagger/dagger/pull/7864

Doc will come right after we merge that PR :)

Do you think this can solve your issue for TypeScript?

**Comment by eralumin** [comment]
Hi @TomChv yes I think it will.
