### ISSUE TITLE
🐞 Memory crash when returning the source Directory (GO SDK)

### ISSUE THREAD

**Issue by klemens-galus** [dagger/dagger#8117]
### What is the issue?

If in a dagger function you try to return a source Directory your computer will crash

### Dagger version

0.11.7

### Steps to reproduce

```go
package main
import ()
type Test struct{}
func (m *Test) BuildDist(source *Directory) *Directory {
  return source
}
```

### Log output

No logs but ram is going more than 32GO of ram (my max ram)

**Comment by jedevc** [comment]
Can you share the command you're using to call this function?

**Comment by klemens-galus** [comment]
@jedevc 
Sure i sure : 
`dagger call build-dist --source=.`

**Comment by samalba** [comment]
We did a lot of stability work since 0.11.

I could not repro this with dagger v0.12.4. Can you upgrade and confirm if it still happens on your side?

**Comment by samalba** [comment]
Closing since we can't repro on the latest version. Please re-open if it happens again on the last v0.12.
