### ISSUE TITLE
🐞 cmd: for dagger.Secret on a Windows Host seems to want to execute 'sh'

### ISSUE THREAD

**Issue by pjmagee** [dagger/dagger#8119]
### What is the issue?

I think I found a bug with the `cmd:` feature on the `--secret=cmd:""` feature, on the Windows version of Dagger. 

`env:` seems to work fine, and this is how ive been passing secrets until recently as I explore and try new approaches.

I want to use `cmd:` and use `1Password` or some other command to retrieve a secret, though what seems to be happening is its falling back to a `sh/linux` way of executing the `cmd:`.

This reminds me of a similar issue I raised a while back with windows based paths or exporting to Windows didn't work. I'm wondering if a gap here exists with `cmd:` on a Windows host. I am using `1Password CLI` and the CLI tool itself has worked fine for me, I used it in the same terminal to validate the output was a correct password string. Note this is Windows Terminal with Powershell 7.

```sh
--password=cmd:"op read 'op://OMMITED'"
```

translated to a dagger error:

```bash
Error: failed to get value for argument "password": failed to run secret command "op read 'op://OMIITED'": exec: "sh": executable file not found in %PATH%
```

It seems like the error is saying 'op' cannot be found, but actually looking further into the error message, it is also mentioning 'sh' to possibly execute that `cmd:`, hinting to me that its kind of trying to do this on a linux env. 

### Dagger version

v0.12.4

### Log output

Error: failed to get value for argument "password": failed to run secret command "op read 'op://OMIITED'": exec: "sh": executable file not found in %PATH%

**Comment by levlaz** [comment]
Thanks @marcosnils for finding where this lives in the code: https://github.com/marcosnils/dagger/blob/cff0042946c68b9ef2c1128b4ed089097f443b33/cmd/dagger/flags.go?plain=1#L449

It seems like this this is not implemented to run outside of linux/unix/bash

**Comment by wingyplus** [comment]
I think we can detect the os and use pwsh to execute command on Windows. 🤔 

Use `runtime.GOOS` to detect it would be enough?

**Comment by pjmagee** [comment]
> I think we can detect the os and use pwsh to execute command on Windows. 🤔
> 
> Use `runtime.GOOS` to detect it would be enough? I have a Windows machine so I help try fixing on this bug.

It would be a similar approach like the export/path issue fixed not too long ago too for windows.
