### ISSUE TITLE
PHP: configure which exit codes prevent subsequent calls.

### ISSUE THREAD

**Issue by charjr** [dagger/dagger#8141]
## Real Example of Current Behaviour

When my source directory has formatting errors, if I call:

`dagger/sdk/php $ dagger call -m dev format --source=. export --path=.`:

The `format` command begins:
1. The formatter, PHPCBF, **executes successfully**. It formats the errors **but returns exit code 1**
    - This is a quirk of the formatter's exit codes, [it may be fixed in the next major version](https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/184).
2. Execution stops, because it received an exit code 1.

## Desired Behaviour

1. Because I know what exit codes the formatter will return, I configure which exit codes will not halt further calls to dagger.
2. The formatter runs successfully, formatting the error and returning exit code 1.
3. The diff is returned and used in the call to `export`.

**Comment by jedevc** [comment]
@charjr would https://github.com/dagger/dagger/issues/5981 resolve this? Or this entirely related to the internal behavior of the PHP SDK?

**Comment by charjr** [comment]
> @charjr would #5981 resolve this? Or this entirely related to the internal behavior of the PHP SDK?

@jedevc resolving #5981 would also resolve this. 

More explicitly your PR #8466 would resolve this. 

(When I made the issue, I wasn't sure whether it was specific to the SDK or not)
