### ISSUE TITLE
✨ Typescript sdk should support overriding base image (like the python sdk does)

### ISSUE THREAD

**Issue by cchanley2003** [dagger/dagger#8146]
### What are you trying to do?

Of the 3 main sdks the typescript one doesn't allow for overriding the base image. Go doesn't need it and python has the [discovery](https://github.com/dagger/dagger/blob/62e369bc8ba0a29061eeb474fee01055f2babe44/sdk/python/runtime/discovery.go#L320). Typescript should support similar functionality to the python sdk.

Similar to the python we could put the  image override in the config section of the package.json

### Why is this important to you?

1. I want to be able to provide my own base image
2. For corporate envs may need to pull from a private registry

### How are you currently working around this?

Only work around atm is to fork the typescript sdk

**Comment by TomChv** [comment]
It's possible to override the current node version, do you want to actually change the image itself?

https://docs.dagger.io/manuals/developer/typescript/356352/runtime#nodejs

If so, I can add that capabilities

**Comment by cchanley2003** [comment]
Yes, change the image not just the version or package manager.

**Comment by TomChv** [comment]
> Yes, change the image not just the version or package manager.

Okay I can make that happen, I'll do a change on the runtime :D
