### ISSUE TITLE
🐞 Container Export to Host machine is not working 

### ISSUE THREAD

**Issue by GeitRavi** [dagger/dagger#8226]
### What is the issue?

We have created a container using go sdk and trying to export to host machine using Export function but it is not working.   Same operation we are doing using cli "export path " it is working fine. 

### Dagger version

v0.12.5

### Steps to reproduce

We have created a container using go sdk and trying to export to host machine using Export function but it is not working.   Same operation we are doing using cli "export path " it is working fine.                                                                                                           
//Build Docker image
func (m *Demo1) BuildPush(ctx context.Context, source *dagger.Directory) (string, error) {
	builtBinary := dag.Container().
		From("golang:1.21.3").
		WithDirectory("/src", source).
		WithWorkdir("/src").
		WithExec([]string{"go", "build", "-o", "hello-world"})
	imageWithTag := fmt.Sprintf("%s:%s", "my-hello", "1.0.0")
	imagePath := fmt.Sprintf("//%s.tar", imageWithTag)

	// Create the Docker image
	return dag.Container().
		From("alpine:latest").
		WithFile("/hello-world", builtBinary.File("/src/hello-world")).
		WithEntrypoint([]string{"/hello-world"}).Export(ctx, imagePath)
}    

### Log output

dagger call build-push --source=. 
2024/08/26 19:19:16 WARN failed to get repo HEAD err="reference not found"
Setup tracing at https://dagger.cloud/traces/setup. To hide: export NOTHANKS=1

✔ connect 7.1s
✔ initialize 1.3s
✔ prepare 0.1s
✔ demo1: Demo1! 0.0s
✔ Demo1.buildPush(
    source: ✔ ModuleSource.resolveDirectoryFromCaller(path: "."): Directory! 0.0s
  ): String! 1.9s

/my-hello:1.0.0.tar     it is showing the tar file has been created But there is no file in HOST machine.                                              But in case of cli it is working fine  dagger call build-push --source=. export --path="my-hello2:1.0.0.tar"
2024/08/26 19:26:17 WARN failed to get repo HEAD err="reference not found"
Setup tracing at https://dagger.cloud/traces/setup. To hide: export SHUTUP=1

✔ connect 1.6s
✔ initialize 6.5s
✔ prepare 0.6s
✔ demo1: Demo1! 0.0s
✔ Demo1.buildPush(
    source: ✔ ModuleSource.resolveDirectoryFromCaller(path: "."): Directory! 0.0s
  ): Container! 14.2s
✔ Container.export(path: "my-hello2:1.0.0.tar"): String! 0.2s

func (m *Demo1) BuildPush(ctx context.Context, source *dagger.Directory) *dagger.Container {
	builtBinary := dag.Container().
		From("golang:1.21.3").
		WithDirectory("/src", source).
		WithWorkdir("/src").
		WithExec([]string{"go", "build", "-o", "hello-world"})

	// Create the Docker image
	return dag.Container().
		From("alpine:latest").
		WithFile("/hello-world", builtBinary.File("/src/hello-world")).
		WithEntrypoint([]string{"/hello-world"})
}

**Comment by jedevc** [comment]
Heya @GeitRavi - this is no longer possible since https://github.com/dagger/dagger/pull/6535.

Essentially, when a module `.Export`s a file/directory/container, it's written to the scratch directory *for that module* - not for the host. To export to the host, you'd use the `dag.Host().Export()` method - however, this is intentionally disabled.

It's not secure for a random module anywhere to be able to export to any random location on the host filesystem - so it's disabled. Potentially for https://github.com/dagger/dagger/issues/8235, there might be the opportunity to improve this experience.

But for now, the workaround is to have your dagger function directly return the container/file/directory, and then to `export` it from the CLI using the `-o` option.

**Comment by GeitRavi** [comment]
Thanks for your response. 
Is there any way to transfer the container image to host machine using code( function) only??

**Comment by jedevc** [comment]
Not as of yet - you currently have to return the `Container` from your function, then you can export it from there.

You can follow along the discussion to improve this experience in #6535, and also some amount in #8025.

**Comment by GeitRavi** [comment]
Thanks
