### ISSUE TITLE
Support writing code in other languages

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#824]
Bash is nice to quickly put together something, up to a point.

Supporting other programming language would provide a much nicer developer experience (e.g. when `bash` isn't enough) and would allow to write more powerful integrations by using upstream libraries (e.g. `boto`, `netlify`, ...).

For instance, the current Netlify package has a pretty long shell script using curl, grep, sed, jq, ... In javascript, we could use the netlify library and achieve something more robust 

- Depends on Embed files in a cue configuration #277
  - Writing code in Python for instance would require using multiple files (e.g. `requirements.txt`, `app.py`, `utils.py`, ...)
 - Possibly provide stdlib helpers (in cue/dagger) for each language (i.e. bindings).
   - For instance an equivalent of `os.#Container` but for e.g. `#Python`
   - Details TBD
 - Possibly provide a per language SDK to interact with Dagger
   - e.g. `dagger.getInputs()`

**Comment by shykes** [comment]
I think we have finally shipped :)
