### ISSUE TITLE
Store dependency version information

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#8271]
## Problem

`dagger.json` does not contain version information for its dependencies. Instead, it only stores the result of digest lookup *at the time of install*. This makes it impossible to cleanly update dependencies in accordance with developer's wishes, because we don't know the developer's wishes.

## Solution

In addition to storing the exact digest of each dependency, also store the version information as provided by the developer at install time.

**Comment by jedevc** [comment]
Possible duplicate of https://github.com/dagger/dagger/issues/7898? :eyes:

**Comment by shykes** [comment]
Indeed!
