### ISSUE TITLE
🖐️ There is no file exported to the host machine when the execution command fails.

### ISSUE THREAD

**Issue by GeitRavi** [dagger/dagger#8275]
### What happened? What did you expect to happen?

We are trying to run the UI Playwright tests and export the test results to the host machine. This works fine when all tests pass. However, when there is a test failure, the container exits with error code 2 and does not export the test report.

```
func (m *Demo1) RunTest(ctx context.Context, source *dagger.Directory) *dagger.File {

        // Connect to the Dagger eng
        container := dag.Container().
                From("mcr.microsoft.com/playwright:v1.46.1-focal").
                WithDirectory("/app", source).
                WithWorkdir("/app").
                WithEnvVariable("npm_config_yes", "true").
                WithExec([]string{"npm", "install", "-g", "npm@10.8.3"}).
                WithExec([]string{"npm", "install", "@playwright/test"}).
                WithExec([]string{"npx", "playwright", "test"})

        _,err := container.Stdout(ctx)
        if err != nil {
        return container.Directory("/app").File("results.xml")
        }
		return container.Directory("/app").File("results.xml")
		
}
```

Is there a way to export the report in case of failure as well.Thanks

**Comment by jedevc** [comment]
You can see how to handle this case in the Dagger cookbook here: https://docs.dagger.io/cookbook/#continue-using-a-container-after-command-execution-fails.

Essentially, you can start a shell, like this `WithExec([]string{"sh", "-c", "npx playwright test || true"})`. Then you can continue even on failure.

There are ongoing plans to improve this, however, this isn't completed yet.

**Comment by GeitRavi** [comment]
Thanks for response
