### ISSUE TITLE
Discrepancy between our +ignore and gitignore

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#8287]
## Problem

Our new `+ignore` pragma (for directory arguments) should be compatible with the gitignore format (for simplicity to the user, and easier interop), but currently it's not.

A few examples:

| Pragma | Expected behavior | Actual behavior |
| -- | -- | -- |
| `+ignore=["**", "!.github/workflows"]` | everything is ignored except `.github/workflows` | everything is ignored |
| `+ignore=["!.github/workflows"]` | nothing is ignored | everything is ignored except  `.github/workflows` |

## Solution

Change the behavior of our `+ignore` to be fully compatible with `.gitignore`.

## Design considerations

As explained by @TomChv , the difficulty is that buildkit APIs expose an `include`/`exclude` model that doesn't map directly to Git ignore.

I would like to hear more about how much difficulty we're talking about exactly. This is an important aspect of the spec, which is why I addressed the possible difficulty early:

[On Discord, June 27](https://discord.com/channels/707636530424053791/1003718839739105300/1255782856899301457)
>  Don't underestimate the ignore though, it doesn't map directly to llb.local include/exclude. I guess it's the exact opposite of patterns from views though, maybe that will help?
>  I mean you will need to convert gitignore format to buildkit include/exclude format

**Comment by rawkode** [comment]
This is great! I literally just tried this:

```ts
@argument({ defaultPath: ".", ignore: ["*", "!package.json"] })
```

I'm trying to mount the `package.json` files in a Bun workspace to see if I can handle the `bun install` across the entire monorepo
