### ISSUE TITLE
🐞 [CLI] Arguments typed with 'Platform' are required at runtime, even when default value is specified.

### ISSUE THREAD

**Issue by vxrios** [dagger/dagger#8320]
### What is the issue?

Hello, I am using the Dagger Python SDK to define custom dagger functions.

I found that when I create a function with an argument that uses the type annotation `Platform`, and provide it a default argument, the default argument is ignored, and an error will be raised when the argument is not provided. 

### Dagger version

dagger v0.12.7 (registry.dagger.io/engine:v0.12.7) darwin/arm64

### Steps to reproduce

Define a function that accepts `platform` argument and defines a default value:

```python
from typing import Optional
from dagger import Platform, function, object_type

@object_type
class MyModule:

    @function
    def useplatform(self,
            platform: Platform = Platform("linux/amd64")
        ) -> str:

        return(f"Platform: {platform}")
```

Now try to run the command `useplatform` without providing the `platform` argument

```sh
$ dagger call useplatform
```

### Log output

Here is the error I get when I run the command `useplatform` without providing the `platform` argument:

```sh
$ dagger call useplatform
Setup tracing at https://dagger.cloud/traces/setup. To hide: export STOPIT=1

✔ connect 0.6s
✔ initialize 2.6s
✘ prepare 0.0s
! failed to get value for argument "platform": platform cannot be empty

Error: failed to get value for argument "platform": platform cannot be empty
Run 'dagger call useplatform --help' for usage.
```

## Workaround
The only way to get dagger to respect the default argument, is to wrap the type annotation with `typing.Optional`.

```py
platform: Optional[Platform] = Platform("linux/amd64")
```

Note that this type hint does not correctly reflect the type of the platform variable. `Optional[Platform]` indicates the type of `platform` can either be `None` or an instance of `Platform`.  This is incorrect, since `platform` must always be a `Platform`.

**Comment by helderco** [comment]
This isn't a Python issue, it's a CLI bug.

As a tip, the "prepare" step happens when the CLI is parsing and validating all the flags in the command, before even sending the request. I checked the Python SDK and it's reporting and working correctly from the API. The bug is in some custom CLI flags not using the default value of an argument.

There's a fix, PR coming soon.
