### ISSUE TITLE
core(private-modules): `SSH_AUTH_SOCK` env loading seems to break with shell expansion characters

### ISSUE THREAD

**Issue by grouville** [dagger/dagger#8337]
Bug found: https://discord.com/channels/707636530424053791/1280527928861655112/1280958016144932885

I believe it is linked to the lexical relative path function: https://github.com/dagger/dagger/blob/main/engine/client/pathutil.go#L9-L12

**Comment by samalba** [comment]
Looking at the thread, it looks like we need to expand `~` in the SSH_AUTH_SOCK. However it most cases, it's expected to be an absolute path (at least ssh-agent does it).
