### ISSUE TITLE
✨ TypeScript SDK: Support Constructors / Functions as Types

### ISSUE THREAD

**Issue by rawkode** [dagger/dagger#8344]
### What are you trying to do?

Use generics to construct classes within a single function, to provide an easy to use NodeJS factory function for any package manager.

```ts
type newPackageManager<T> = new (directory: Directory, version: string) => T;

@func()
withPackageManager<T extends PackageManager>(
  type: newPackageManager<T>,
  directory: Directory,
  version: string
): T {
  return new type(directory, version);
}
```

This should allow me to offer a nice API, such as:

```ts
dag.nodejs().withPackageManager<Bun>(directory).install();
```

Currently this fails as the type `new (directory: Directory, version: string) => T` is unsupported

### Why is this important to you?

It would allow refactoring code with best practices in mind, which is a key strength of Dagger.

So hopefully this use-case could be supported by the SDK.

I believe support could be added [here](https://github.com/dagger/dagger/blob/main/sdk/typescript/introspector/scanner/abtractions/typeToTypedef.ts).

### How are you currently working around this?

Creating a function for each variant, such as:

```ts
@func()
withBun(directory: Directory, version: string = "latest"): Bun {
  return new Bun(directory, version);
}
```

**Comment by TomChv** [comment]
Hey,

This requires to support Dagger Interface on the TypeScript SDK, it's something we plan to support but first we need to do https://github.com/dagger/dagger/issues/8676 :rocket:

**Comment by TomChv** [comment]
I'm closing this issue since I don't plan to add support for that in the nexts months.

If it's a big blocker, feel free to reopen that issue and we can discuss about some implementation details :)
