### ISSUE TITLE
Don't allow a function to know its caller

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#8345]
## Problem

Based on [a discord chat](https://discord.com/channels/707636530424053791/1281272011024236624/1281276263889371188), it *might* be possible for a function to identify the module that called it.

If that's true, then we should disable this. We don't want functions behaving differently based on who is calling them. The correct way to configure a function's behavior, is with an argument.

## Solution

Disable the ability for a function to know its caller (if in fact it exists).

**Comment by jedevc** [comment]
Answered in the discord thread, but for posterity:

> hm, that's not what that function does 🤔
https://docs.dagger.io/api/reference/index.html#definition-FunctionCall
> parent is:
> > The value of the parent object of the function being called. If the function is top-level to the module, this is always an empty object.
>
> it's intended to be used by the codegen, it essentially just gets the json representation of the "self" object
