### ISSUE TITLE
✨ Disable Engine Replacement

### ISSUE THREAD

**Issue by stobias123** [dagger/dagger#8364]
### What are you trying to do?

I have dagger in a few repos, and they may be different versions of dagger, and these may also differ from my dagger version when calling `dagger run foo`.

I really hate when I'm running a build from one repository, and then start a second build and it kills the docker container from my first build due to differing versions. I wish there was a way this could just fail the mismatched build rather than breaking my previously started build.

Example:

Repo A is on dagger 12.1, starts build via `dagger run foo`. Dagger engine is on v `12.5` and we use that dagger engine.

Repo B is on dagger 12.1 - starts build via `go run .` Dagger engine gets nuked, and build from repo A is nuked.

### Why is this important to you?

Significant loss of time. Caches get broken etc on long builds.

### How are you currently working around this?

I can't

**Comment by wingyplus** [comment]
Duplicate with https://github.com/dagger/dagger/issues/8195?

**Comment by shykes** [comment]
Yes it's a duplicate because @stobias123 and I hate the same thing :-P Please please let's disable this, at least by default.

**Comment by stobias123** [comment]
oh whoops I'll close as dupe. Thanks guys!
