### ISSUE TITLE
Testing Dagger modules

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#8382]
## Problem

One benefit of your CI pipelines being code, is that you can test them. Or at least, that's the theory. In practice, while it's possible to test Dagger pipelines, it's neither easy nor well documented.

## Solution

Make it completely seamless to test Dagger modules, and document it well.

**Comment by marcosnils** [comment]
related to https://github.com/dagger/dagger/issues/6724

**Comment by shykes** [comment]
Thanks @marcosnils , this is definitely a duplicate :)

**Comment by marcosnils** [comment]
closing as duplicate then since I don't see this issue adds anything new to the existing one :pray:
