### ISSUE TITLE
Can't access .git from context directory, when loading module remotely

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#8387]
## Problem

When loading a module remotely, `.git` is stripped from the module's context directory. This breaks functions that rely on accessing `.git`.

Example:

```golang
func GitHead(
// +optional
// +defaultPath="/.git"
gitDir *dagger.Directory,
) *dagger.File {
  return gitDir.File("HEAD")
}
```

This function will work when loading the module locally:

```console
dagger call -m . git-head
```

But it will **not** work when loading remotely:

```console
dagger call -m github.com/foo/bar git-head
```

## Solution

TBD

**Comment by jedevc** [comment]
This should be fixed by https://github.com/dagger/dagger/pull/8318#, which will default to keeping the git directory around in all cases.

**Comment by shykes** [comment]
Just checking that @sipsma 's concerns with this (from a caching perspective) are addressed?
