### ISSUE TITLE
✨ It is possible to create a image from scratch base image 

### ISSUE THREAD

**Issue by GeitRavi** [dagger/dagger#8403]
### What are you trying to do?

We are trying to build a golang code once it complied we are try to use scratch as base image and just put the executable go binary. 

  ############################
# STEP 1 build executable binary
############################
FROM golang:alpine AS builder
# Install git.
# Git is required for fetching the dependencies.
RUN apk update && apk add --no-cache git
WORKDIR $GOPATH/src/mypackage/myapp/
COPY . .
# Fetch dependencies.
# Using go get.
RUN go get -d -v
# Build the binary.
RUN go build -o /go/bin/hello
############################
# STEP 2 build a small image
############################
FROM scratch
# Copy our static executable.
COPY --from=builder /go/bin/hello /go/bin/hello
# Run the hello binary.
ENTRYPOINT ["/go/bin/hello"]

**Comment by jpadams** [comment]
@GeitRavi absolutely!

Here's an example

```sh
git clone https://github.com/jpadams/GeitRavi/
cd GeitRavi
dagger call build-in-scratch
```
this will return the `Container` object which you can ask for its `stdout`

```
dagger call build-in-scratch stdout
```
you should see:
```
Hello world!
```

**Comment by jpadams** [comment]
For fun, try this too :)

```
dagger call -m https://github.com/jpadams/GeitRavi build-in-scratch publish --address ttl.sh/geitravi/scratch:latest
```
that will yield an image address in the ephemeral ttl.sh registry, for example:
```
ttl.sh/geitravi/scratch:latest@sha256:fc54730dd378acb58f611d004d6b1cc02a659667d6cb0ea90e4c312a781cf942
```
then you can 
```
docker run ttl.sh/geitravi/scratch:latest@sha256:fc54730dd378acb58f611d004d6b1cc02a659667d6cb0ea90e4c312a781cf942
```
or
```
dagger core container from --address ttl.sh/geitravi/scratch:latest@sha256:fc54730dd378acb58f611d004d6b1cc02a659667d6cb0ea90e4c312a781cf942
 stdout
 ```

**Comment by GeitRavi** [comment]
Thanks for your response.

**Comment by GeitRavi** [comment]
Very much happy to discuss/discord. I have another question how we can ignore the error in WithExec set to execute binary so that we can run publish image in case of failure as well.
