### ISSUE TITLE
✨ Is there a way to first create binary using container run and second step creates a docker image/build (not creating container) using that binary. 

### ISSUE THREAD

**Issue by GeitRavi** [dagger/dagger#8444]
### What are you trying to do?

There is scenarios where we are creating golang executable binary at first step and in second step we want to use the binary but not creating a container only we want to build image using binary. 

It's like we have a Dockerfile that requires a Golang binary as input in order to build the final Docker image

Could you please help on this use care in dagger. thanks

**Comment by sagikazarmark** [comment]
Using Go:

```go
binary := dag.Container().From("golang")./* build the binary */.File("/out/binary")

finalImage := dag.Container().From("alpine").WithFile("/usr/bin/binary", binary).Publish(/**/)
```

Check out the quickstart guide: https://docs.dagger.io/quickstart

Here is a real life example: https://github.com/openmeterio/openmeter/blob/edb72be714a01edacc312d27ef95ae808ce1259a/ci/build.go#L65-L86

**Comment by GeitRavi** [comment]
Thank you so much for your response.
