### ISSUE TITLE
🐞 TypeScript Properties Don't Work Like Functions

### ISSUE THREAD

**Issue by rawkode** [dagger/dagger#8446]
### What is the issue?

Perhaps this is by design, but I can currently do the following:

```ts
@object()
class RawkodeAcademy {
	@func()
	config(): Config {
		return new Config();
	}

        @func()
        myString(): string {
                return "hello";
        }
}
```

but I can't do the following:

```ts
@object()
class RawkodeAcademy {
	@func()
	config = new Config()

        @func()
        myString = "hello";
}
```

### Dagger version

0.13.0

**Comment by rawkode** [comment]
cc @TomChv

**Comment by helderco** [comment]
You need the types at least, see https://docs.dagger.io/manuals/developer/state-functions:

```typescript
@object()
class RawkodeAcademy {
	@func()
	config: Config;

        @func()
        myString: string;
}
```

Not sure about those defaults though. They'll probably be ignored. TypeScript doesn't have a good way of instrospecting default values. They're seen as string representations so the SDK would need to `eval()` them, requiring knowing which files to load (during introspection), etc.

However, I think there's ways to fix it. For example, constructing that object should handle setting the defaults within the TypeScript process.

**Comment by TomChv** [comment]
```typescript
@object()
class RawkodeAcademy {
	@func()
	config = new Config()

        @func()
        myString = "hello";
}
```

Hmm that's strange because `hello` should be considered like a default value, you may have spot a bug here.

**Comment by Xiot** [comment]
Using `@func` for these fields still feels very odd, since they are written, and accessed like fields in Typescript.  I do understand that they are treated like functions internally to dagger, but they are just fields in typescript

**Comment by Xiot** [comment]
>In the context of dagger it makes sense though, when you decorate a property with @func, you basically ask dagger to create a function to access the field

In the context of dagger it makes sense.  But in the context of using the ts-sdk it doesn't.  My perspective is purely on the 'using the ts-sdk' side of things.

**Comment by TomChv** [comment]
> In the context of dagger it makes sense. But in the context of using the ts-sdk it doesn't. My perspective is purely on the 'using the ts-sdk' side of things.

Do you have any opinion on how we can improve this then? :D I'm open to any suggestion :)

**Comment by Xiot** [comment]
> Do you have any opinion on how we can improve this then? :D I'm open to any suggestion :)

I liked the `@field()` since that is what the code actually represents

**Comment by TomChv** [comment]
I'm closing this issue since we don't plan to go back on the `@field()` decorator so far, we'll reopen it if we decide to at some points.
