### ISSUE TITLE
📖 Update docs about Python project management

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#8449]
### What is the issue?

Follow up to:
- https://github.com/dagger/dagger/pull/8311

With the new [uv: Unified Python packaging](https://astral.sh/blog/uv-unified-python-packaging), and Python Dagger Modules now using `uv.lock` by default, it's time to update our docs and make `uv` our main recommendation to develop Dagger Modules with Python, which simplifies workflows.

**Comment by jpadams** [comment]
Not clear from the PR and what I've seen so far if your should remove the `requirements.txt` after converting to `uv` or if there is a compat benefit to leaving it in place.

**Comment by helderco** [comment]
requirements.lock should be removed when migrating to uv.lock. 

The caveat is that I've not provided instructions on how to preserve the same pinned versions, beyond linking to a workaround (in the feature PR).

In any case, it should be available from the git history, so the info isn't lost if needed. No compat concerns for keeping both files.
