### ISSUE TITLE
🐞 Context directory upload not working as expected

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#8469]
### What is the issue?

I have the following directory structure: 

```
.
├── bar
├── dagger.json
└── LICENSE
```

And the following dagger function that uses context directory: 

```go
func (m *Lala) Test(
	// +defaultPath="/"
	// +ignore=["bar"]
	dir *dagger.Directory,
) *dagger.Directory {
	return dir
}
```
If I call `dagger call test entries`, I can't see the `bar` file in the output. As discussed with @TomChv, the only way to make the `bar` file getting actually ignored, is by changing the `ignore` pragma to `bar/` which IIUC is a buildkit specific thing. 

We agreed that this is not user friendly and we should try to address it better 

### Dagger version

v0.13.0

### Steps to reproduce

NA

### Log output

NA

**Comment by TomChv** [comment]
@shykes I wonder what's your opinion regarding that issue, because it's purely DX, I think .gitignore works if you do not happen the `/` so should we add it for specific dir?

**Comment by helderco** [comment]
The way `.gitignore` works is that if a pattern ends in a `/`, it matches only directories. If it doesn't, then it matches both directories and files. I don't think there's a way to match only files.

Forcing a `/` to match the file for buildkit doesn't make sense to me, so I think something else is going on.

Here's what I did:

```
❯ cd $(mktemp -d)
❯ mkdir lala && cd lala
❯ git init
❯ touch bar
❯ dagger init --sdk=go --source=.dagger
❯ # replaced .dagger/main.go with your function
❯ ls -1a
.dagger
.git
bar
dagger.json
LICENSE
❯ dagger call test entries
.dagger
.git
LICENSE
dagger.json
```

So it was filtered.

**Comment by marcosnils** [comment]
> Do you have a competing include or something?

Hey Helder, you're correct! not sure what happened here. I might have had an incorrect include as you mention or something since I just tried again and I can't repro anymore. I'll go ahead and close this. 

Sorry for the noise :pray:
