### ISSUE TITLE
cli: rename "initialize" and "prepare" spans to be more descriptive

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#8542]
## Problem

People are confused over what "initialize" is, but more so with "prepare" when they try to understand what’s slowing down their pipelines. We can make this slightly better by giving more descriptive names, but especially in a way that users are able to **more easily make sense of why a step may be taking longer** than expected.

Inside "initialize" there’s also "installing module" and "analyzing module" which can be more descriptive as well.

### Example

<img width="1021" alt="Screenshot 2024-09-23 at 10 34 46" src="https://github.com/user-attachments/assets/11b62e79-b6f2-440a-940d-6de83972ccaa">

## Suggestions

- ~~initialize~~ → loading module
    - resolving module ref
    - installing module ？🤔
    - ~~analyzing module~~ → introspecting module for cli
- ~~prepare~~ → loading function inputs in cli

> [!note]
> Function **inputs** are the CLI **flags**. ⏱️ Use a default with [`// +defaultPath`](https://docs.dagger.io/manuals/developer/functions#directories-and-files) and `// +ignore` in code, to filter a `Directory` argument, or a  _view_ in the CLI until https://github.com/dagger/dagger/pull/8436.

## Installing module 🤔

I’m not sure what to rename "installing module", because three main things happen here and are useful to know on their own. Maybe rename the following core functions to be more descriptive:

- **`ModuleSource.resolveFromCaller`**
    - uploads local files to the engine
    - ⏱️ *fine tune `exclude` in `dagger.json`* to make it faster
- `ModuleSource.asModule`
    - **`Module.withSource`**
        - *recursively calls `ModuleSource.asModule` for every dependency*
            - ⏱️ *check if there’s a bottleneck in a dependency*
        - builds the SDK module, calling **codegen** and building the **runtime** container
            - ⏱️ *there’s possible inefficiencies in the SDK module’s pipelines (written in Go for every SDK)*
    - **`Module.initialize`**
        - executes the runtime container’s entrypoint (`exec /runtime` span), which calls out to the SDK library to report available functions (includes introspecting the code, except in Go)
            - ⏱️ *the target SDK’s language may be slower compared to others, but it’s possible there’s things that can be improved in the “module support” feature of the language library*
        - ⚠️ Easy to confuse with the outermost "initialize" span, in which this step is only a small part of

**Comment by helderco** [comment]
Note that only the Go SDK introspects the code during codegen (`Module.withSource`) instead of at runtime (`Module.initialize`). For all other SDKs, the codegen result only changes with the schema, while in Go, it changes with the source code. I think we need to double check if this is causing issues with cache misses, since the Go SDK is used for every other SDK’s (runtime) modules.

**Comment by shykes** [comment]
Thanks for tackling this. From a UX perspective the whole thing is a mess.
