### ISSUE TITLE
🐞 Dagger Engine uses too much disk space 

### ISSUE THREAD

**Issue by levlaz** [dagger/dagger#8561]
### What is the issue?

Recently we have been noticing many examples where dagger engine aggresively uses up all available disk space and seems to never clean up after itself. 

It is not clear if this is a new regression, or if we are getting a bigger wave of larger projects, but over the last few weeks there have been many different users that report these sorts of issues. 

One example looks like this: 

1. Typescript application with Typescript SDK inside roughly  a 600MB git repo.
2. Running Dagger in Docker on Ubuntu 
3. After a day of developing the pipeline (with likely 50-100 invocations of dagger call) the user reported ~600GB of volumes being used by the Dagger Engine. 

Another example 

1. Ruby application with python SDK inside roughly a 1.2GB repo 
2. Running Dagger in Docker Desktop on Mac 
3. After 2 hours of pipeline development with around 25-50 invocations of dagger call the user reported 116GB of volume being used by Dagger Engine

Dagger Should not be using up this much disk space, we need to find a way to either automatically/configure limit how much disk can be used, or figure out a way to clean things up a bit more aggressively. 

### Dagger version

dagger v0.13.3 (registry.dagger.io/engine:v0.13.3) darwin/arm64

**Comment by jedevc** [comment]
Related to https://github.com/dagger/dagger/issues/7711.

**Comment by levlaz** [comment]
I think this is actually a duplicate of #7711 - I do not believe that anything new has happened to make this worse, looking over that issue its feels like just a coincidence that we've recently seen a lot more larger projects onboard where this issue becomes even more prevalent. 

I am going to close this one to reduce noise and focus efforts on 7711.
