### ISSUE TITLE
🐞 When using a custom dagger engine container, dagger doesn't start the container automatically

### ISSUE THREAD

**Issue by kreempuff** [dagger/dagger#8603]
### What is the issue?

I was [trying to add custom certs](https://docs.dagger.io/manuals/administrator/custom-runner#custom-ca-certs) to the default dagger engine container. When I created the image and set the `$_EXPERIMENTAL_DAGGER_RUNNER_HOST` variable, the dagger cli doesn't attempt to start that container. It seems as if you opt into a custom engine container you lose the feature that starts the engine for you

I would expect dagger to attempt to detect and start the container it needs is running just like it does for the stock image

### Dagger version

dagger v0.13.3 (registry.dagger.io/engine:v0.13.3) darwin/arm64

### Steps to reproduce

1. Build a new image on top of the current dagger engine image
2. Run these commands
```
export _EXPERIMENTAL_DAGGER_RUNNER_HOST=<protocol>://<custom-image>
dagger -m github.com/shykes/daggerverse/hello@v0.3.0 call hello
```

### Log output

```shell
❯ dagger -m github.com/shykes/daggerverse/hello@v0.3.0 call hello
✘ connect 5.9s
! start engine: new client: interrupted
  ✘ connecting to engine 5.9s
  ! new client: interrupted
```

**Comment by nipuna-perera** [comment]
Dagger is able to start my custom image fine. Do you have an ENTRYPOINT or CMD that's overriding dagger default one? I am not sure that matters, but I don't have one in mine.

Can you also run your command with `-vvv` to get some more info in the log?

**Comment by kreempuff** [comment]
@nipuna-perera ~interesting. I got this with `export _EXPERIMENTAL_DAGGER_RUNNER_HOST="docker-container://registry.dagger.io/engine:v0.13.3"`~:
```
❯ dagger -vvv -m github.com/shykes/daggerverse/hello@v0.3.0 call hello
✘ connect 1m24.5s
! start engine: new client: interrupted
  ✔ starting engine 0.0s
  ✘ connecting to engine 1m24.5s
  ! new client: interrupted

14:47:28 WRN canceling... (press again to exit immediately)
```

In trying to get this info for you I noticed my mistake haha. I used `docker-container://` as the protocol instead of `docker-image://`. It worked after I changed it 💪🏿
