### ISSUE TITLE
Support disabling automatic init in `withExec`

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#8617]
Dagger automatically includes dumb-init in execs by default to avoid the quirks of Linux pid 1 processes causing unexpected behavior in most common cases.

There are use cases that call for user control of pid 1 though, so we can pretty easily add an option to disable our automatic init, leaving it in the control of the user.

**Comment by marcosnils** [comment]
related: https://github.com/dagger/dagger/issues/8513

**Comment by sipsma** [comment]
> related: #8513

I think this is just a dupe of that one actually, closing in favor it
