### ISSUE TITLE
🐞 Otel traces and logs cannot be turned off together

### ISSUE THREAD

**Issue by abhibacheti** [dagger/dagger#8620]
### What is the issue?

[discord conversation](https://discord.com/channels/707636530424053791/1291042423085989939)

Goal - I am trying to disable traces and logs both.

What I did and actaul outcome - if we set this env var OTEL_EXPORTER_OTLP_LOGS_ENDPOINT to empty value https://github.com/dagger/dagger/blob/7527e4bf607f1206afc64565fefdf78737fcef9a/sdk/go/telemetry/init.go#L125, logs exporter won't intialize(disabled)

But to disable the traces, there should not be any env var prefixed with OTEL_ https://github.com/dagger/dagger/blob/7527e4bf607f1206afc64565fefdf78737fcef9a/sdk/go/telemetry/init.go#L29, then doing so it will disable traces but then we have to remove  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT, which will be enabled to check logs exporter(it comes with wierd errors in logs that endpoint is not set), so basically these settings cannot work together becasue one is not allowing other to work properly.

Expectation - traces and logs are disabled

### Dagger version

v0.13.0

**Comment by cwlbraa** [comment]
does having all the OTEL vars unset AND being logged out result in undesirable behavior? I'm able to reproduce the annoying "can't send traces" log, but only when logged in. if I log out and unset all the OTEL vars, it's quiet and doesn't send anything.
