### ISSUE TITLE
✨ TypeScript SDK: Use `Generics` to configure things that cannot be decorated

### ISSUE THREAD

**Issue by TomChv** [dagger/dagger#8685]
#8676 would let use support more typescript features, specially some that doesn't support decorators such as `type` & `enum`.

However, users should still have a way to actually document & set specific metadata on top of these types. To do so, we can introduce `Generic` that can replace decorators when they are not usable.

For example:

```typescript
type PropertyMetadata = {
   doc: string

   // Expose this property to the Dagger API (should we actually do the opposite and let everything public by default??)
   expose?: boolean
}

type Property<Metadata extends PropertyMetadata, T extends any> = T


type User = {
   name: Property<{ doc: "the name of the user", expose: true }, string>
   age: Property<{ doc: "the age of the user", number}>
}
``` 

💡 This however has some limitation, for example you cannot interpolate string inside the doc string, it also makes the syntax a bit complex for beginners but it allows passing actual metadata from a type.

After few tests, I don't think this should actually replace decorators, but it can be another way to declare metadata for property (and why not argument but this is not the scope of the issue).

**Comment by Xiot** [comment]
Have you thought of using [JSDoc](https://jsdoc.app/) for some of this?
This is already used in the JS/TS ecosystem to provide more information about types / properties


![CleanShot 2024-10-11 at 18 38 09](https://github.com/user-attachments/assets/e21bff6c-bbbd-4e3c-8048-6dfe745d0cbb)

**Comment by TomChv** [comment]
> Have you thought of using [JSDoc](https://jsdoc.app/) for some of this?
This is already used in the JS/TS ecosystem to provide more information about types / properties

I have never been a big fan of JSDoc to define code capabitilities, but you think it's actually a thing?

If you had the choice between JSDoc & Generic, which one would you pick?

**Comment by Xiot** [comment]
Using `JSDoc` has the added benefit of being read by IDEs, so that would provide a much nicer DX

**Comment by TomChv** [comment]
> Using JSDoc has the added benefit of being read by IDEs, so that would provide a much nicer DX

Okay! That's nice topic to discuss on the community call, because this could be applied on any kind of keyword/data like class, object, func, param, types... It's a generic way basically.

**Comment by TomChv** [comment]
I'm closing this issue since we're not planning to work on this issue in the nexts months, we'll reopen it if we decide to drop decorators in favor of JSDoc or generics
