### ISSUE TITLE
🖐️ Do we even need to mention `/versioned-docs` dir at `docs/_README`?

### ISSUE THREAD

**Issue by mcruzdev** [dagger/dagger#8694]
### What happened? What did you expect to happen?

Reading the documentation at `docs/_README` was not possible to see the directory called `docs/_versioned-docs`. Is it deprecated? If yes, I can send a pull request to remove this one, WDYT?

**Comment by vikram-dagger** [comment]
It's not deprecated. We don't currently have another version of the docs in progress, so it doesn't exist right now. However, if we create a significantly new version of the docs and work on it in parallel with the main docs, then that new version will exist in this location. I've created a PR to make this clearer.
