### ISSUE TITLE
Unable to run `dagger call` locally

### ISSUE THREAD

**Issue by Xiot** [dagger/dagger#8722]
### What is the issue?

I am unable to run `dagger call` locally.  
I removed my `node_modules`, deleted the `sdk` folder and re-ran `dagger develop`.

```
 Error: Cannot find package '/src/dagger/sdk/node_modules/typescript/package.json' imported from /src/dagger/sdk/introspector/scanner/scan.ts  
```

This looks to be due to separate package managers being installed.  
The `sdk` is using `yarn v1`, however my dagger module is using `npm`.  
When `npm install` is run from my `dagger` folder, it will attempt to install all of the dependencies, and dependencies of dependencies.  It also hoists shared dependencies, so what is happening is that the `typescript` package is actually being installed in the root `node_modules` folder.  Because `yarn` is used in the sdk, it has a different mechanism for locating dependencies, so the resolution fails.

### Dagger version

dagger v0.12.4 (registry.dagger.io/engine:v0.12.4) darwin/arm64

### Steps to reproduce

```bash
> dagger develop --sdk=typescript
> npm install
> dagger call <cmd>
```

### Log output

https://dagger.cloud/Motion/traces/a2916f8b2dd2884c271fef6f7b966df6

```
✔ connect 0.7s
✘ initialize 54.8s
! input: module.withSource.initialize resolve: failed to initialize module: failed to call module "motion-dagger" to get functions: call constructor: process "tsx --no-deprecation --tsconfig /src/dagger/tsconfig.json /src/dagger/src/__dagger.entrypoint.ts" did not complete successfully: exit code: 1
  ✔ resolving module ref 0.2s
  ✘ installing module 54.6s
  ! input: module.withSource.initialize resolve: failed to initialize module: failed to call module "motion-dagger" to get functions: call constructor: process "tsx --no-deprecation --tsconfig /src/dagger/tsconfig.json /src/dagger/src/__dagger.entrypoint.ts" did not complete successfully: exit code: 1
    ✔ ModuleSource.resolveFromCaller: ModuleSource! 18.6s
    ✔ ModuleSource.asModule: Module! 5.7s
    ✘ Module.initialize: Module! 30.3s
    ! failed to initialize module: failed to call module "motion-dagger" to get functions: call constructor: process "tsx --no-deprecation --tsconfig /src/dagger/tsconfig.json /src/dagger/src/__dagger.entrypoint.ts" did not complete successfully: exit code: 1
    ┃                                                                                                                    
    ┃ node:internal/modules/run_main:129                                                                                 
    ┃     triggerUncaughtException(                                                                                      
    ┃     ^                                                                                                              
    ┃ Error: Cannot find package '/src/dagger/sdk/node_modules/typescript/package.json' imported from /src/dagger/sdk/int
    ┃ tor/scanner/scan.ts                                                                                                
    ┃ Did you mean to import "typescript/lib/typescript.js"?                                                             
    ┃     at legacyMainResolve (node:internal/modules/esm/resolve:215:26)                                                
    ┃     at packageResolve (node:internal/modules/esm/resolve:841:14)                                                   
    ┃     at moduleResolve (node:internal/modules/esm/resolve:927:18)                                                    
    ┃     at defaultResolve (node:internal/modules/esm/resolve:1157:11)                                                  
    ┃     at nextResolve (node:internal/modules/esm/hooks:866:28)                                                        
    ┃     at resolve (file:///usr/local/lib/node_modules/tsx/dist/esm/index.mjs?1729130068036:2:3893)                    
    ┃     at nextResolve (node:internal/modules/esm/hooks:866:28)                                                        
    ┃     at Hooks.resolve (node:internal/modules/esm/hooks:304:30)                                                      
    ┃     at handleMessage (node:internal/modules/esm/worker:196:24)                                                     
    ┃     at Immediate.checkForMessages [as _onImmediate] (node:internal/modules/esm/worker:138:28) {                    
    ┃   code: 'ERR_MODULE_NOT_FOUND'                                                                                     
    ┃ }                                                                                                                  
    ┃                                                                                                                    
    ┃ Node.js v20.15.0                                                                                                   

Error: input: module.withSource.initialize resolve: failed to initialize module: failed to call module "motion-dagger" to get functions: call constructor: process "tsx --no-deprecation --tsconfig /src/dagger/tsconfig.json /src/dagger/src/__dagger.entrypoint.ts" did not complete successfully: exit code: 1

Stderr:
node:internal/modules/run_main:129
    triggerUncaughtException(
    ^
Error: Cannot find package '/src/dagger/sdk/node_modules/typescript/package.json' imported from /src/dagger/sdk/introspector/scanner/scan.ts
Did you mean to import "typescript/lib/typescript.js"?
    at legacyMainResolve (node:internal/modules/esm/resolve:215:26)
    at packageResolve (node:internal/modules/esm/resolve:841:14)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at nextResolve (node:internal/modules/esm/hooks:866:28)
    at resolve (file:///usr/local/lib/node_modules/tsx/dist/esm/index.mjs?1729130068036:2:3893)
    at nextResolve (node:internal/modules/esm/hooks:866:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:304:30)
    at handleMessage (node:internal/modules/esm/worker:196:24)
    at Immediate.checkForMessages [as _onImmediate] (node:internal/modules/esm/worker:138:28) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.15.0
failed to wait for command termination: exit status 1
```

**Comment by helderco** [comment]
Here's what I tried on v0.13.5:
```console
❯ dagger init --sdk=typescript test
Initialized module test in test
❯ cd test
❯ lt -L1
.
├── sdk
├── src
├── dagger.json
├── LICENSE
├── package.json
├── tsconfig.json
└── yarn.lock
❯ rm -f yarn.lock
❯ npm install
❯ lt -L1
.
├── node_modules
├── sdk
├── src
├── dagger.json
├── LICENSE
├── package-lock.json
├── package.json
└── tsconfig.json
❯ dagger functions
Name             Description
container-echo   Returns a container that echoes whatever string argument is provided
grep-dir         Returns lines that match a pattern in the files of the provided Directory
```

**Comment by helderco** [comment]
@TomChv, after the above, doing a `dagger develop` writes `yarn.lock` again:
```console
❯ dagger develop
❯ lt -L1
.
├── node_modules
├── sdk
├── src
├── dagger.json
├── LICENSE
├── package-lock.json
├── package.json
├── tsconfig.json
└── yarn.lock ❌
```
This shouldn't happen. The existence of the lock file should be enough to setup the desired package manager, without having to specify it in `package.json`.

**Comment by Xiot** [comment]
Where are the `install` commands being run?
If it is only on the root module, then things should be fine.  I suspect though, that there is an install being run on the sdk folder.  
The other issue could be that the `node_modules` folders are being copied into the engine when `dagger call` is being called.

I'll try upgrading.  I was originally holding off upgrading since there were some issues with 13

**Comment by Xiot** [comment]
I just upgraded to 13.5, so I'll see how that does.
I did notice that it no longer has any lock files in the `sdk` folder, and it looks like it ran a `npm install` in my module as well.

![CleanShot 2024-10-17 at 09 26 56](https://github.com/user-attachments/assets/eff3260e-42c2-4b91-9517-df4266838f14)

**Comment by Xiot** [comment]
Actually, it didn't run `npm install`, but it did modify my lock file, which is kinda weird

**Comment by Xiot** [comment]
With 13.5 I was able to run things locally.

**Comment by Xiot** [comment]
@helderco re: https://github.com/dagger/dagger/issues/8722#issuecomment-2419272409

That `yarn.lock` should be there as its at the root of the repo.

**Comment by helderco** [comment]
> @helderco re: [#8722 (comment)](https://github.com/dagger/dagger/issues/8722#issuecomment-2419272409)
> 
> That `yarn.lock` should be there as its at the root of the repo.

No it shouldn't, because I removed `yarn.lock` and added the `package-npm.lock`. The TypeScript SDK knows from this alone that I want to use npm and not yarn, that just didn't happen here because the `packageManager` config has precendence over which lock file exists, and `dagger init` added that in by default. So if you remove that config too, `dagger develop` will no longer manage the `yarn.lock` file and will use `package-npm.lock` instead.

**Comment by Xiot** [comment]
> That's appropriate. Dagger needs to re-lock in case there's a change in dependencies from the SDK after you make an upgrade, or if you update the version of the package manager. It shouldn't upgrade pinned dependencies in the lock file though, unless a mininum supported version is bumped in the SDK.

How does this work if the sdk isn't upgraded between engine version upgrades?  
For example, I write my module against the sdk of `13.0`, but it later gets run against `13.5`.  If the dependencies were changed between those releases, then the lock file won't have the latest version.... I guess this is why dagger modifies the local lock file.  This can also be a little dangerous since the versions can change from underneath the module code.


> No it shouldn't, because I removed yarn.lock and added the package-npm.lock. The TypeScript SDK knows from this alone that I want to use npm and not yarn, that just didn't happen here because the packageManager config has precedence over which lock file exists, and dagger init added that in by default. So if you remove that config too, dagger develop will no longer manage the yarn.lock file and will use package-npm.lock instead.

Ah.  In my case I didn't have a `packageManager` field, so it just based it off of the presence of the lock file.

**Comment by TomChv** [comment]
I'm closing this issue for now since there's no more activities, feel free to reopen it if you still hit that issue :)
