### ISSUE TITLE
Using `expand` with a non-existent variable should fail

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#8752]
With https://github.com/dagger/dagger/issues/7951 implemented in https://github.com/dagger/dagger/pull/8427, we have some surprising behavior.

It's possible that the variable isn't set on the container - currently this silently fails - I think we should consider making failure the default.

Even if we don't - we at least explicitly handle the `withSecretVariable` case - we can't/shouldn't expand secret variables, so we should fail with a nice error message in this case. See this discord thread: https://discord.com/channels/707636530424053791/1297911858778341428/1298211444298350634

```python
        versions = await (
            dag.container()
            .from_("alpine:latest")
            .with_secret_variable("GITEA_TOKEN", token)
            .with_env_variable("URL", url)
            .with_env_variable("OWNER", owner)
            .with_exec(["apk", "add", "curl"])
            .with_exec(
                [
                    "sh",
                    "-c",
                    (
                        'curl "$URL/api/v1/packages/$OWNER?access_token=$GITEA_TOKEN"'
                        # ' --header "Authorization: token $(cat /run/secrets/gitea-token)"'
                        # ' --header "Authorization: token $GITEA_TOKEN"'
                        # " -H 'accept: application/json'"
                    ),
                ],
                expand=True
            )
            .stdout()
        )
```

Setting `expand` to `True` here should have explicitly failed with a message about `GITEA_TOKEN` not being set.

**Comment by rajatjindal** [comment]
Hi @jedevc 

I am happy to take this and submit a fix. (ofcourse unless you have already fixed it)

**Comment by jedevc** [comment]
Sounds good @rajatjindal :tada:

If you could look at adding an explicit error message for the secret case first, that would be great! I think switching all substitutions to fail hard probably needs a discussion first.

cc @shykes @helderco

**Comment by rajatjindal** [comment]
I think this specific issue is that we are calling expandEnv in `core/schema/container.go#withExec` before the secrets are injected as env variables (during the call of `core/container.go#withExec` function). But because of expandEnv function call, the string `$GITEA_TOKEN` is replaced with a blank string.

I think this breaks secret expansion in general in `WithExec` args (irrespective of if the env variable is set or not). 

what do you think @jedevc
