### ISSUE TITLE
🐞 Can't upgrade/add apk packages in dagger engine

### ISSUE THREAD

**Issue by nipuna-perera** [dagger/dagger#8787]
### What is the issue?

Before v0.13.6, I was able to run `apk update` and `apk add bash` for example within the Dagger Engine image. This is not possible since `v0.13.6`

### Dagger version

dagger v0.13.6 darwin/arm64

### Steps to reproduce

```shell
docker run -it --entrypoint='' registry.dagger.io/engine:v0.13.6 /bin/sh
apk update
```

### Log output

```shell
ERROR: Unable to read database state: No such file or directory
ERROR: Failed to open apk database: No such file or directory
```

**Comment by jedevc** [comment]
This was introduced in https://github.com/dagger/dagger/pull/8714, cc @sipsma 

Out of curiosity - why? Introspecting and modifying the dagger engine like this while it's running isn't really a supported scenario for us.

**Comment by marcosnils** [comment]
:wave:  coming from: https://discord.com/channels/707636530424053791/1120503349599543376/1299433157359177809

maybe a  better approach here is to add arguments to our `dagger/dagger` engine module command so we can add additional packages there to build the engine distro images?

**Comment by nipuna-perera** [comment]
> Out of curiosity - why? Introspecting and modifying the dagger engine like this while it's running isn't really a supported scenario for us.

Bit of a long story but I needed the docker CLI inside the dagger engine as I was using the Dagger engine container to run my dagger workloads in CI. Which kind of resulted in unnecessary nesting because at that point it's doing "engine in engine". The reason I switched to that pattern was to make use of the dagger CLI inside the dagger image (ever since that was available fairly recently). 

I reverted back to downloading the dagger CLI at build time and now I don't need the Docker CLI in dagger engine. 

I wasn't installing it at runtime. I was installing the docker CLI at engine build time. 

Although I'm good on my end, there may be others looking to use the engine this way. Maybe they create a "builder" image that has all the necessary tooling including the dagger engine to run within a CI orchestrator in a docker-in-docker way for example.

**Comment by sipsma** [comment]
Agree that it would be better to avoid the need for this entirely, but FTW if we do want to support this there is a comment here describing the extra changes needed to get `apk add` working in the image: https://github.com/dagger/dagger/blob/00ec4e9ccc41d6e79e5b41f28d278ad74b41f9a7/modules/alpine/main.go#L148-L158

**Comment by nipuna-perera** [comment]
Understood. Based on [this](https://discord.com/channels/707636530424053791/1120503349599543376/1299433157359177809) it's simpler than that? I agree with adding a function to extend the engine if needed.

**Comment by sipsma** [comment]
> Understood. Based on [this](https://discord.com/channels/707636530424053791/1120503349599543376/1299433157359177809) it's simpler than that? I agree with adding a function to extend the engine if needed.

Ah I missed that, yeah that has a weird side effect of re-installing packages that technically already exist, but is a valid workaround

**Comment by nipuna-perera** [comment]
Posting the workaround here for future reference.

```Dockerfile
FROM registry.dagger.io/engine:v0.13.6

RUN <<-EOF echo > /etc/apk/world
alpine-baselayout
alpine-keys
apk-tools
busybox
libc-utils
EOF

RUN apk -X "http://dl-cdn.alpinelinux.org/alpine/v3.2/main" add curl
```

**Comment by nipuna-perera** [comment]
I will close this for now. We can re-open if this becomes widespread.
