### ISSUE TITLE
Shell polish

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#8807]
# Overview

There is a `dagger shell` feature in development. It already works, but needs more polish before making it stable. This issue tracks my requests for that polish.

## Calling dependencies

- https://github.com/dagger/dagger/issues/9006
- https://github.com/dagger/dagger/issues/9035

Let's say I have a dependency called `go` (local name). And that dependency has a function called `build`. There should be a simple way to call that function from the shell.

| With `dagger call` | With `dagger shell` |
| -- | -- |
| `dagger call -m go build` | `go build` |

## `.doc`

- https://github.com/dagger/dagger/issues/8831

We need a builtin called `.doc`, which can be called *from any type*, and prints that type's documentation to standard output.

This is an elegant alternative to `--help`.

| With `dagger call` | With `dagger shell` |
| -- | -- |
| `dagger call --help` | `.doc` |
| `dagger call build --help` | `build | .doc` |

Note: this requires allowing builtins anywhere in the pipeline (at the moment, there is a hardcoded check that locks builtins to the top-level type only).

## Per-module history

I love that there is a persisted history. But it is global across modules. I think it would be cooler if it were module-specific.

## No-module mode

- https://github.com/dagger/dagger/issues/8890
- https://github.com/dagger/dagger/issues/8932

`dagger shell` should work even when no module is loaded. The shell is useful even with only the builtins. It also opens interesting questions (for the future, maybe) of one day dynamically loading a module from the same session

## Reloading context

- https://github.com/dagger/dagger/issues/8987

Local directories are loaded once per session, and subsequent changes are ignored. This makes the shell useless for local development:

```console
> test
# change files...
> test
# changes are ignored
```

Not sure how to solve this, but I wanted to flag it.

Note: this is related to @aluzzardi 's work on "watch".

**Comment by shykes** [comment]
FYI @helderco

**Comment by helderco** [comment]
I was going to create a few issues and an epic to tie them for an overview. "Shell polish" works for an overview issue, but I think it's useful to split the features into separate issues and just link/list here.

You've added a couple more (sgtm), but fyi, this is my list:
- `.doc` built-in
- call core functions without having to load a module
- allow targeting module dependencies
- improve telemetry spans
- preserve variables from a previous prompt in interactive mode
- command groups for built-ins ([different purposes](https://github.com/dagger/dagger/blob/ca92eab80081c34fe4d4daa3a29bc5d10dd67c3b/cmd/dagger/shell.go#L859-L860), but also to organize `.help` better)
- function completions
- select siblings with `&`?

I also have these to bikeshed:
- how to define constructor arguments?
- how to list core functions?

**Comment by shykes** [comment]
> ### Reloading context
> Local directories are loaded once per session, and subsequent changes are ignored. This makes the shell useless for local development:
> 
> ```
> > test
> # change files...
> > test
> # changes are ignored
> ```
> 
> Not sure how to solve this, but I wanted to flag it.

This part might be interesting to you @sipsma

**Comment by helderco** [comment]
> * how to list core functions?

This is the current situation for listing top level functions:
- `.doc`: shows module functions
- `.help`: shows most useful core functions[^1]
- `.core`: lists all core functions

[^1]: E.g., `.container`, `.directory`; excludes `load-xxx-from-id` and functions for SDKs to define TypeDefs.

**Comment by helderco** [comment]
To document a constructor:
- `.doc`: shows the module's constructor
- `.help .container`: shows doc for `Query.container`[^1] _(works for all core functions even if not shown in `.help`)_

[^1]: Using `.container | .doc` shows the doc for the `Container` type

**Comment by helderco** [comment]
Here's another one:
- https://github.com/dagger/dagger/issues/8932

**Comment by shykes** [comment]
These are all addressed in other issues now. Closing.
