### ISSUE TITLE
✨ Export *dagger.EnvVariable to host

### ISSUE THREAD

**Issue by gtabrar** [dagger/dagger#8836]
### What are you trying to do?

I have a Dagger module that returns the IP of a remote Dagger engine as a string (but it could also be as a `*dagger.EnvVariable`), and I would like to be able to export it as an environment variable on the host.

Something like `dagger call engine-ip export --env=_EXPERIMENTAL_DAGGER_RUNNER_HOST`

### Why is this important to you?

I want to use Dagger modules for everything, including setting up my environment (locally and in GHA).

### How are you currently working around this?

`if _DAG_HOST=$(dagger call engine-ip); then export _EXPERIMENTAL_DAGGER_RUNNER_HOST="$_DAG_HOST"; else echo "Failed to retrieve engine IP"; fi`

**Comment by gtabrar** [comment]
Updated because I forgot `dagger.EnvVariable` is a thing, but it doesn't look like I can export that either :)

**Comment by jedevc** [comment]
I don't think this is possible - in general, not just for dagger.

The `dagger` process is running as a child process of your shell (`bash`/`zsh`/`fish`/etc) - the child can modify it's *own* environment variables, but it can't modify a parent's environment variables.

Potentially *maybe* we could do something like `dagger call engine-ip export --env=_EXPERIMENTAL_DAGGER_RUNNER_HOST | source /dev/stdin`? Using `source` in this way is the only way to be able to set environment variables in the shell.

But at that point, you could just construct the string yourself in dagger as a method.

**Comment by marcosnils** [comment]
How about `eval $(dagger core container from --address alpine with-exec --args echo,"export foo=bar" stdout)`  ?

**Comment by gtabrar** [comment]
Having the Dagger command output the "export foo=bar" and then wrapping it in eval is a great solution. Thank you both :)
