### ISSUE TITLE
Update [this test](https://github.com/dagger/dagger/blob/main/core/integration/module_test.go#L2459) with the correct `dag.Engine()` newly generated type

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#8879]

**Comment by jedevc** [comment]
@marcosnils can you clarify which type needs updating? I can't seem to find any test that needs an updated test.

In this `TestEngineError`, the values are discarded, so we don't need any conversion, but maybe there's another usage?

https://github.com/dagger/dagger/blob/64165b972e6caf7a20c56380ea4515d770ee1dea/core/integration/module_test.go#L2447-L2450

**Comment by marcosnils** [comment]
This has been addressed already as a v0.14 follow-up https://github.com/dagger/dagger/pull/8901 :pray: . I'm closing this one
