### ISSUE TITLE
🐞 Can't use --sdk=python on macOS M1 Pro (ARM)

### ISSUE THREAD

**Issue by parisnakitakejser** [dagger/dagger#8941]
### What is the issue?

I'm just new for Dagger and brew install it, trying out to run the example code and then i hit this error, about latest engine version, i can't change the version but if i only use ```dagger init``` its will add a dagger.json file success with version 0.14.0 of the engine, but with SDK of python its not working.

### Dagger version

v0.14.0

### Steps to reproduce

dagger init --sdk=python --source=./dagger

### Log output

✘ ModuleSource.asModule(engineVersion: "latest"): Module! 0.9s
! failed to create module: select: failed to update codegen and runtime: failed to generate code: failed to call sdk module codegen: select: call function "Codegen": process "/runtime" did not complete successfully: exit code: 2

Error: failed to generate code: input: moduleSource.withContextDirectory.withName.withSDK.withSourceSubpath.withInit.asModule resolve: failed to create module: select: failed to update codegen and runtime: failed to generate code: failed to call sdk module codegen: select: call function "Codegen": process "/runtime" did not complete successfully: exit code: 2

Stdout:
marshal: json: error calling MarshalJSON for type *dagger.GeneratedCode: input: container.from resolve: failed to resolve image ghcr.io/astral-sh/uv:0.4.30@sha256:341e448d2ca38f11d8e2768db5464b4c95a4d87f539b8cb7511db86b02fef97e: failed to resolve source metadata for ghcr.io/astral-sh/uv:0.4.30@sha256:341e448d2ca38f11d8e2768db5464b4c95a4d87f539b8cb7511db86b02fef97e: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aastral-sh%2Fuv%3Apull&service=ghcr.io: 403 Forbidden

**Comment by parisnakitakejser** [comment]
Resolved the problem from helping from @samalba live on KubeCon :) 

Thanks a lot :)

I had an invalid auth session on ghcr.io which triggered the 403. The fix was to `docker logout ghcr.io` and everything was working correctly after.

**Comment by qweasd1** [comment]
same issue, but even when I ```docker logout ghcr.io```, I still got this issue.... I'm on dagger v0.16.3
