### ISSUE TITLE
🐞 `dagger init` using the typescipt SDK can take a long time.

### ISSUE THREAD

**Issue by cloetzi** [dagger/dagger#8954]
### What is the issue?

I was following the quickstart guide to experiment with Dagger in a large monolith repo. The problem was that Dagger is ignoring `.gitignore` and `.dockerignore` files for init process and transfers _all_ files in the repository (including `node_modules` etc) into the Dagger context. This turned out to be extremely slow (~16min using the typescript SDK, ~6 min using the go SDK`). While everything worked at the end, the experience was not great and it was unclear what was taking so long.

### Dagger version

dagger v0.14.0 (registry.dagger.io/engine:v0.14.0) darwin/arm64

**Comment by grouville** [comment]
Was here with @shykes to debug the issue ; This would be of great help: https://github.com/dagger/dagger/pull/8501, but Typescript SDK is still 2 times slower than the Go one on init command. Still unsure on why we need to mount the entire repo just for an init ? cc @TomChv

**Comment by TomChv** [comment]
>  Still unsure on why we need to mount the entire repo just for an init ?

Because we copy the whole library and generate it directly inside the user module dir. 
Caching should make things much faster normally, I already spend a lot of time making it cleaner. Another solution would be to have the dependency remote (see: #8688)

**Comment by TomChv** [comment]
I'm closing this issue since we already have some issues related to that problem. We can continue the discussion on #8699.
