### ISSUE TITLE
shell: better support with-exec

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#8969]
## Problem

In the shell, `.container | with-exec` requires comma-separated arguments:

```console
.container |
with-exec echo,hello,world |
stdout
```

But it should be instead:

```console
.container |
with-exec echo hello world |
stdout
```

## Solution

Change the syntax of `with-exec` to support the more natural `with-exec echo hello world`.

This is possible to do cleanly, because `with-exec` has a single required argument, and it's an array. In that case, the shell parser should parse arguments in the more natural way I propose. All functions which match that signature would benefit, not just `with-exec`.

**Comment by helderco** [comment]
This is doable, yes. I can make it work when the last required argument is a list, or any optional arg. For **other required args** or for explicitness, we can use a built-in:
```
.container | with-exec $(.list echo "hello world") | stdout
```

Or some syntax sugar:
- `.container | with-exec $(@ echo "hello world") | stdout`
- `.container | with-exec (echo "hello world") | stdout`
- `.container | with-exec [echo "hello world"] | stdout`

These would produce:
```graphql
withExec(args: ["echo", "hello world"])
```

We can even easily support a list of lists this way.

**Comment by helderco** [comment]
> No syntax sugar please. 

Ok, but are you extending that statement to `with-exec echo hello world`? Meaning you'd have to write `with-exec $(.list echo hello world)`?

**Comment by shykes** [comment]
We discussed this live with Helder. We agreed on the following:

1. First a very simple solution to make `with-exec` cooler. Simply support positional args if there's only one required arg, and it's an array. Flags continue to work the same, without special convenience.

2. Meanwhile, we continue discussing possible builtins to make things easier. For example `.list`, `.json` etc. This requires more discussion and is orthogonal to the first point.

**Comment by helderco** [comment]
There's still a problem with ambiguity though. It's easy enough to parse positional args until you hit a flag (`--`), but the command you want to pass to `withExec` can also have flags. I can reduce that conflict by stopping at the first occurrence of a flag that matches an optional argument (not just any flag), which for `withExec` is currently this list:
- `--use-entrypoint`
- `--stdin`
- `--redirect-stdout`
- `--redirect-stderr`
- `--expect`
- `--experimental-privileged-nesting`
- `--insecure-root-capabilities`
- `--expand`
- `--no-init`

So if you need any of these in `args`, it won't work. Of course this extends to user functions as well. Can be confusing to people so I'm not sure about it long term, but let's just do the easy thing now and continue to discuss a builtin solution (`.list`/`.json`).

**Comment by shykes** [comment]
@helderco the standard solution to this is to stop interpreting flags after `--`. So there is no ambiguity.

**Comment by helderco** [comment]
No, I mean when your command itself has flags:
```graphql
withExec(args: ["some", "cmd", "--expand", "/src"])
```
So in the shell you'd want to do this:
```shell
... | with-exec some cmd --expand /src | stdout
```

**Comment by shykes** [comment]
> No, I mean when your command itself has flags:
> 
> ```graphql
> withExec(args: ["some", "cmd", "--expand", "/src"])
> ```
> 
> So in the shell you'd want to do this:
> 
> ```shell
> ... | with-exec some cmd --expand /src | stdout
> ```

Right, we're talking about the same thing. The standard unix convention to handle this is:

```console
No, I mean when your command itself has flags:

withExec(args: ["some", "cmd", "--expand", "/src"])
So in the shell you'd want to do this:

```console
... | with-exec -- some cmd --expand /src | stdout
```

**Comment by helderco** [comment]
Oh right, you meant a standalone `--` rather than an arg with that prefix. 👍 To be fair, that can still be a valid argument for your command since it's commonly used in a lot of tools 😄 

```graphql
withExec(args: ["git", "checkout", "--", "myfile.txt"])
```

**Comment by shykes** [comment]
> Oh right, you meant a standalone `--` rather than an arg with that prefix. 👍 To be fair, that can still be a valid argument for your command since it's commonly used in a lot of tools 😄
> 
> ```graphql
> withExec(args: ["git", "checkout", "--", "myfile.txt"])
> ```

In that situation I believe you're supposed to do:

```console
... | with-exec -- git checkout -- myfile.txt
```

In any case, whatever problem arises from this convention, will be regular unix problems :)

**Comment by shykes** [comment]
> Not quite. We aren't following the POSIX spec anyway because options should come before operands:
> 
> > **Guideline 9:**
> > All options should precede operands on the command line.
> > ```
> > utility_name [options][operands]
> > ```

Yeah guideline 9 is slightly obsolete because in practice, gnu is more flexible and allows any order. We should probably do the same, any other behavior would be confusing.

> We're putting the operands before the options there, so `--` doesn't make sense here:
> 
> ```shell
> ... | with-exec git checkout -- $SRC -- --expand
> ```
> 
> Our own `--` needs to come first, but that only works if options come first.

Yeah we can't keep that behavior. Forbidding options before operands will be confusing to users, it doesn't follow any established convention, *and* it seems it also makes it harder for us to implement `--`.
