### ISSUE TITLE
shell: local fs export is broken

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#8992]
## Problem

As of 0.14.0, exporting to the local filesystem is broken:

1. export to a path without `.` or `/` characters: silent fail. The directory is not created.

```console
⋈ .directory | export mydir
⋈
```

2. export to any path with `.` or `/` characters: error.

```
⋈ .directory | export mydir/foo
declare: invalid name "mydir/foo"
```

```
⋈ .directory | export /foo
declare: invalid name "/foo"
```

```
```
⋈ .directory | export ./foo
declare: invalid name "./foo"
```

**Comment by helderco** [comment]
Looks like "export" is clashing with https://pkg.go.dev/mvdan.cc/sh/v3@v3.10.0/syntax#DeclClause:

```go
type DeclClause struct {
	// Variant is one of "declare", "local", "export", "readonly",
	// "typeset", or "nameref".
	Variant *[Lit](https://pkg.go.dev/mvdan.cc/sh/v3@v3.10.0/syntax#Lit)
	Args    []*[Assign](https://pkg.go.dev/mvdan.cc/sh/v3@v3.10.0/syntax#Assign)
}
```

**Comment by helderco** [comment]
Since this only applies to LangBash an easy fix is to set the parser to LangPOSIX (as in `sh` instead of `bash`).

**Comment by mvdan** [comment]
Just beware that switching to POSIX also loses you Bash syntax that users probably expect to work, such as `foo |& bar`, `if [[ foo == bar ]]`, `let x = y - z`, and so on.

**Comment by helderco** [comment]
Thanks for the input @mvdan. Yeah, we need to bikeshed what we want to support or not. Not just syntax but also shell builtins (I don't mean Dagger Shell builtins, in mean mvdan/sh builtins).
