### ISSUE TITLE
🐞 Experimental support for NVIDIA is broken

### ISSUE THREAD

**Issue by samalba** [dagger/dagger#9015]
### What is the issue?

I've been experimenting with gpu-enabled Dagger engine on Fly.io: https://github.com/gerhard/daggerverse/pull/4 in order to get an easy access to a physical GPU usable with Dagger.

I ran some examples to re-evaluate the ability for Dagger to use a GPU, and it seems to be all broken...

### Dagger version

dagger v0.14.0 (registry.dagger.io/engine:v0.14.0) darwin/arm64

### Steps to reproduce

Using a remote dagger engine (`export _EXPERIMENTAL_DAGGER_RUNNER_HOST=tcp://<FLY_APP_NAME>.internal:2345`).

Code snippet (with commented unsuccessful workarounds):

```go
// TestCuda tests if it can access the GPU, requires a machine with an NVIDIA GPU
func (m *Gpu) TestCuda(ctx context.Context) (string, error) {
	return dag.Container().
		// From("nvidia/cuda:12.6.2-base-ubuntu24.04").
		From("nvidia/cuda:11.7.1-base-ubuntu20.04").
		// FIXME: this is an attempt to fix the error: "fork/exec /usr/bin/nvidia-container-runtime-hook: no such file or directory"
		// WithExec([]string{"sh", "-c", "apt update && apt install -y nvidia-container-toolkit"}).
		ExperimentalWithAllGPUs().
		WithExec([]string{"nvidia-smi", "-L"}).
		Stdout(ctx)
}
```

### Log output

```console
Error: response from query: input: gpu.testCuda resolve: call function "TestCuda": process "/runtime" did not complete successfully: exit code: 2

Stdout:
invoke: input: container.from.withExec.experimentalWithAllGPUs.withExec.stdout resolve: process "nvidia-smi -L" did not complete successfully: exit code: 1
/usr/local/bin/runc did not terminate successfully: exit status 1: container does not exist


Stderr:
runc run failed: unable to start container process: error during container init: error running hook #0: fork/exec /usr/bin/nvidia-container-runtime-hook: no such file or directory
```

cc @gerhard

**Comment by gerhard** [comment]
Does the GPU variants of our image - `v0.14.0-gpu` & `v0.14.0-wolfi-gpu` - fail the same way?

**Comment by jedevc** [comment]
Definitely worth confirming that the gpu variant is being used, but I also wouldn't be particularly surprised if it's bit-rotted a bit.

We have no CI tests for GPU support - if we're committing to providing examples for GPU support in dagger (which we definitely should do), then I think we need to add GPU tests in CI for *sure*.

**Comment by samalba** [comment]
I confirm I am now using the `-gpu` variant: here is what I get:

```console
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
```

I keep digging...

**Comment by rajatjindal** [comment]
I've been looking at it and able to reproduce the issue. I enabled debug logging for the nvidia-container-toolkit, and captured some additional logs:

[nvidia-container-toolkit.log](https://github.com/user-attachments/files/17871997/nvidia-container-toolkit.log)

I am still looking into why this is happening. 

Just FYI, I am now using the same docker image to run `TestCuda` function, that we use for engine and therefore expect it to have same packages installed, but still get same error. so my 2 cents is that the nvidia-container-toolkit is not able to inject *something* successfully when running the container.

**Comment by rajatjindal** [comment]
a little search of the error string leads to a few related issues https://github.com/search?q=%22missing+compat32+library%22&type=issues&s=updated&o=desc

I am going to go through these and see if I can use any of the suggested workarounds there.

**Comment by rajatjindal** [comment]
I finally have this working after installing `libnvidia-compute-565`. The nvidia drivers are really touchy w.r.t version numbers as such, but I found installing this package fix it for both `nvidia/cuda:12.6.2-base-ubuntu24.04` and `nvidia/cuda:11.7.1-base-ubuntu20.04`.

The diff to @samalba repo: https://github.com/samalba/dagger-modules/compare/main...rajatjindal:samalba-dagger-modules:fix-gpu?expand=1

sample output:


```
## calling this from a fly.io app (running dagger engine) console:

dagger call -m github.com/rajatjindal/samalba-dagger-modules/nvidia-gpu@fix-gpu test-cuda 
✔ connect 0.0s
✔ loading module 5.4s
✔ parsing command line arguments 0.0s
✔ gpu: Gpu! 0.0s
✔ Gpu.testCuda: String! 0.4s

Setup tracing at https://dagger.cloud/traces/setup. To hide: export SHUTUP=1

GPU 0: NVIDIA L40S (UUID: GPU-250b202c-761c-5976-c4d3-f49dadc4bcd1)

root@e2866099b69708:/# 
```

**Comment by rajatjindal** [comment]
hmm, that is strange, I do see the changes using that URL.

<img width="1512" alt="Screenshot 2024-11-25 at 9 14 54 PM" src="https://github.com/user-attachments/assets/20f42e16-e9e6-48f0-abd9-12b2efde7b77">

although the diff is just to run the following two commands:

```
apt-get update
apt-get install -y libnvidia-compute-565
```

**Comment by rajatjindal** [comment]
I just tried this on a GPU VM that @marcosnils helped me get access to, and it seems to have worked without any additional package installation. I am going to investigate this more tomorrow but it seems like the issue could be specific to how fly.io setup the firecracker vm.

**Comment by samalba** [comment]
That's neat, thanks @rajatjindal for gathering all those info. I confirm the workaround on fly. Given we can't hardcode a path on the host, it's probably better (more portable) to rely on installing `libnvidia-compute-565`.

Here is the working test for the record:

```go
func (m *Gpu) TestCuda(ctx context.Context) (string, error) {
	return dag.Container().
		From("nvidia/cuda:12.6.2-base-ubuntu24.04").
		WithExec([]string{"apt-get", "update"}).
		WithExec([]string{"apt-get", "install", "-y", "libnvidia-compute-565"}).
		ExperimentalWithAllGPUs().
		WithExec([]string{"sh", "-c", "nvidia-smi -L"}).
		Stdout(ctx)
}
```

**Comment by marcosnils** [comment]
@samalba  regarding your question about Lambda labs, seems like it'll work out of the box similarly to our tests in Oblivus. Let us know in case you give it a try and it doesn't work for some reason.

**Comment by samalba** [comment]
> @samalba regarding your question about Lambda labs, seems like it'll work out of the box similarly to our tests in Oblivus. Let us know in case you give it a try and it doesn't work for some reason.

So I had some time to try it out today:

I keep getting this error, every time I invoke the `ExperimentalWithAllGPUs()` call:

```console
stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory
```

Out of the box, a Lambda VM comes with an `Ubuntu 22.04.5 LTS` and it seems to have the right packages installed:

```console
ii  libnvidia-cfg1-550-server:amd64                  550.127.05-0lambda0.22.04.1                  amd64        NVIDIA binary OpenGL/GLX configuration library
ii  libnvidia-compute-550:amd64                      550.127.05-0lambda0.22.04.1                  amd64        NVIDIA libcompute package
rc  libnvidia-compute-550-server:amd64               550.127.05-0lambda0.22.04.1                  amd64        NVIDIA libcompute package
ii  libnvidia-container-tools                        1.17.2+dfsg-0lambda0.22.04.1                 amd64        Package for configuring containers with NVIDIA hardware (CLI tool)
ii  libnvidia-container1:amd64                       1.17.2+dfsg-0lambda0.22.04.1                 amd64        Package for configuring containers with NVIDIA hardware (shared library)
ii  libnvidia-extra-550-server:amd64                 550.127.05-0lambda0.22.04.1                  amd64        Extra libraries for the NVIDIA driver
ii  libnvidia-ml-dev:amd64                           12.4.127~12.4.1-0lambda0.22.04.2             amd64        NVIDIA Management Library (NVML) development files
rc  nvidia-compute-utils-550-server                  550.127.05-0lambda0.22.04.1                  amd64        NVIDIA compute utilities
ii  nvidia-container-toolkit                         1.17.2-0lambda0.22.04.1                      amd64        OCI hook for configuring containers for NVIDIA hardware
ii  nvidia-container-toolkit-base                    1.17.2-0lambda0.22.04.1                      amd64        Container runtime for NVIDIA hardware
ii  nvidia-cuda-dev:amd64                            12.4.127~12.4.1-0lambda0.22.04.2             amd64        NVIDIA CUDA development files
ii  nvidia-cuda-toolkit                              12.4.131~12.4.1-0lambda0.22.04.2             amd64        NVIDIA CUDA development toolkit
ii  nvidia-cuda-toolkit-gcc                          12.4.1-0lambda0.22.04.2                      amd64        NVIDIA CUDA development toolkit (GCC compatibility)
ii  nvidia-dkms-550-server                           550.127.05-0lambda0.22.04.1                  amd64        NVIDIA DKMS package
ii  nvidia-fabricmanager-550                         550.127.05-0lambda0.22.04.1                  amd64        NVIDIA Fabric Manager for NVSwitch systems
ii  nvidia-firmware-550-server-550.127.05            550.127.05-0lambda0.22.04.1                  amd64        Firmware files used by the kernel module
ii  nvidia-kernel-common-550-server                  550.127.05-0lambda0.22.04.1                  amd64        Shared files used with the kernel module
ii  nvidia-kernel-source-550-server                  550.127.05-0lambda0.22.04.1                  amd64        NVIDIA kernel source package
ii  nvidia-opencl-dev:amd64                          12.4.127~12.4.1-0lambda0.22.04.2             amd64        NVIDIA OpenCL development files
ii  nvidia-profiler                                  12.4.127~12.4.1-0lambda0.22.04.2             amd64        NVIDIA Profiler for CUDA and OpenCL
```

Here is how I started the dagger-engine after stopping the default one (v0.14.0):

```console
docker run -d --privileged -e _EXPERIMENTAL_DAGGER_GPU_SUPPORT=true --name dagger-engine-v0.14.0 registry.dagger.io/engine:v0.14.0-gpu -- --debug
```

For the record I did my test with an instance with an Nvidia A6000 attached (gpu_1x_a6000). @marcosnils and @rajatjindal I gave you both an access to my account in case you want to have a look.

**Comment by rajatjindal** [comment]
I think I found the problem, we need to start dagger with `--gpus all`. once I did that I was able to run a cuda test container on Lambda labs instance.

**Comment by samalba** [comment]
Indeed, I can make it work when starting the engine container with GPU. I guess fly.io transparently set this as well.

Thanks for the help! I am closing this issue as we have several ways to access the GPU, I am working on documenting all this (planning to open the PR in the next few days).
