### ISSUE TITLE
shell: `.use` any part of a chain?

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#9020]
You can currently set any module as the current default one, even if it’s different from the module in the current local directory:

```
dagger-dev ⋈ .load wolfi | .use
wolfi ⋈ container | ...
```

@shykes has mentioned a few times he’d like to be able to “set the context” to any type, not just a module. For example:

```
dagger-dev ⋈ sdk | python | .use
dagger-dev ▶ PythonSdk ⋈ test
```

Notice the prompt change, showing the current context with `<module> ▶ <type> ⋈`.

Could be a different builtin, and could even set a name for later reuse:
```
dagger-dev ⋈ sdk | python | .alias py
dagger-dev ⋈ sdk | typescript | .alias ts
dagger-dev ⋈ .use py | test
dagger-dev ⋈ .use ts | test
```

It’s actually an easy change, the question is is it worth it? Does it add value or can it be confusing?

**Comment by shykes** [comment]
Yes correct. We would lose that potential feature. I think it's ok.

**Comment by helderco** [comment]
Yes, and curiously, if you want to save some typing, you can define a function (will take precence if name conflicts with a top-level function from module):
```shell
py() {
  . --source=$(host | directory . | --include sdk/python) | sdk | python
}
ts() {
  . --source=$(host | directory . | --include sdk/go) | sdk | go
}
py | .doc
ts | .doc
py | test
ts | test
```
No need for a special `.alias`.
