### ISSUE TITLE
docs: Constructor page includes python examples on all languagees

### ISSUE THREAD

**Issue by kpenfound** [dagger/dagger#9041]
On the constructor page with typescript or go selected, after the first two sections the remaining sections are showing python information

https://docs.dagger.io/api/constructor#exclude-argument-in-constructor

**Comment by vikram-dagger** [comment]
AFAIK this is deliberate, as those features are not available in the other SDKs (or at least they were not at the time of writing). There is a callout box for this at the top of each of those sub-sections:

![image](https://github.com/user-attachments/assets/1fac0681-a2e1-4dde-a07d-0107d1da0f4f)

LMK if this is incorrect and those features are actually available in the other SDKs now?

**Comment by kpenfound** [comment]
@vikram-dagger how come they're not within the Python tab though? Since that information is only relevant to Python?

**Comment by vikram-dagger** [comment]
> @vikram-dagger how come they're not within the Python tab though? Since that information is only relevant to Python?

There were three options:
- all 3 tabs, with the code in the Python tab and nothing in the others
- a single Python tab
- no tabs

I thought the first one would be confusing and the second one (only a single tab) didn't really seem to make sense, so went for the third option. Do you think the second one is better/more consistent? 

I can change it if so, and then will also change https://docs.dagger.io/api/interfaces/ and a few other pages.

**Comment by kpenfound** [comment]
I propose
- move "asynchronous constructor" to be a second example in the "simple constructor" section. The python asynchronous constructor is more similar to what we show for simple go/ts than the simple python one is.
- Delete "Exclude argument in constructor" and "Constructor-only arguments". These seem to be documenting something specific to the dataclasses library and not any special functionality of dagger.
- Move "Complex or mutable defaults" as another example within the "Default values for complex types" section. It's really just showing more advanced complex types.

Would like to hear what others think about this too @levlaz @helderco @shykes

**Comment by shykes** [comment]
I trust your judgment @kpenfound since you've used the sdk a lot. Since my understanding is there are a lot of different ways to do things in the python sdk, I would err towards highlighting what a pragmatic user might do, rather than everything you could theoretically do.
