### ISSUE TITLE
🐞 GO SDK enumerations are not being documented

### ISSUE THREAD

**Issue by pjmagee** [dagger/dagger#9099]
### What is the issue?

https://docs.dagger.io/api/enumerations is not working as expected on the Go SDK?

Did not confirm for other SDKs

### Dagger version

dagger v0.14.0 (registry.dagger.io/engine:v0.14.0) windows/amd64

### Steps to reproduce

```go
type Language = string

const (
	// CSharp is the C# language
	CSharp Language = "cs"
	// Cpp is the C++ language
	Cpp Language = "cpp"
	// Go is the Go language
	Go Language = "go"
	// Python is the Python language
	Python Language = "py"
)

```

If you pass this in as an argument, and call the function with `--help`, it will not document the approved acceptable enumerations. 

`dagger call run --help` shows required language, but not the valid enumations.

```
ARGUMENTS
      --day int           [required]
      --language string   [required]
      --git Directory
```

### Log output

Only `all` and `run` are valid functions.

```
✔ connect 0.3s
✔ loading module 0.7s

Name     Description
all      -
cpp      -
csharp   -
go       -
run      -

```

**Comment by jedevc** [comment]
There's a subtle difference between:

```go
type Language = string
```

and

```go
type Language string
```

The first is a type-alias - `Language` is a synonym for `string`. However, the second is a new type, `Language` is distinct from `string`. To do enums properly, we don't do anything with the alias case.

**Comment by pjmagee** [comment]
> There's a subtle difference between:
> 
> ```go
> type Language = string
> ```
> 
> and
> 
> ```go
> type Language string
> ```
> 
> The first is a type-alias - `Language` is a synonym for `string`. However, the second is a new type, `Language` is distinct from `string`. To do enums properly, we don't do anything with the alias case.

Ahh, thank you. I think this subtle difference, reading the docs **and** not being fully comfortable with go, I let this one slip.
