### ISSUE TITLE
shell: can't pass optional arguments to module constructor

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#9129]
(this is tested on #9097, not main)

When I call a module, I can pass mandatory arguments (positional args) but not optional arguments.

### What I did

(includes bootstrap from stable dagger to load the right version of dagger)

```
dagger call -m github.com/helderco/dagger@helder/dev-4805-shell-navigation-model \
 dev with-exec --args=dagger,shell,-c,'github.com/dagger/dagger/modules/go --version=1.23.0 https://github.com/dagger/dagger | .doc'
```

Note: the order of positional arguments and flags doesn't matter:

```
dagger call -m github.com/helderco/dagger@helder/dev-4805-shell-navigation-model \
 dev with-exec --args=dagger,shell,-c,'github.com/dagger/dagger/modules/go https://github.com/dagger/dagger --version=1.23.0 | .doc'

### What I expected

The module is loaded with options `--version=1.23.0` and positional args `https://github.com/dagger/dagger`, then the doc for the resulting object is printed to the screen.

### What happened

```
Error: constructor: accepts at most 1 positional argument(s), received 2
usage: github.com/dagger/dagger/modules/go <source> [options]
```

**Comment by helderco** [comment]
Required arguments come before optionals, like with SDKs.

**Comment by shykes** [comment]
@helderco I forgot to mention that I tried in both orders, and get the error either way. Let me double-check that I didn't get that wrong.

**Comment by shykes** [comment]
@helderco confirmed, the order of positional and options doesn't matter for this bug, you get the same error either way (I updated the issue description to clarify that)

**Comment by helderco** [comment]
Ok, I'm back at my computer for a bit, I can see there's a bug where those optional arguments are interpreted as positional. I'll fix that.

**Comment by helderco** [comment]
This should be affecting stdlib commands too (just top level).

**Comment by helderco** [comment]
Pushed a fix in:
- https://github.com/dagger/dagger/pull/9097

But being able to put pos args last will be on:
- https://github.com/dagger/dagger/issues/8969
