### ISSUE TITLE
Support fetching application logs from dagger

### ISSUE THREAD

**Issue by samalba** [dagger/dagger#915]
Deploying an application produces logs that cannot be fetched from dagger.

We need a `dagger logs` command that would fetch application logs.

A new `#logs` definition could be attached anywhere in the config to fetch logs. Then `dagger logs` would aggregate all logs fetched for a given configuration.

**Comment by shykes** [comment]
I believe we can close this, since in Dagger 0.3 the GraphQL API allows capturing stdout and stderr.
