### ISSUE TITLE
Support explicit dependency

### ISSUE THREAD

**Issue by samalba** [dagger/dagger#940]
Sometimes the implicit dependency of the dag is not enough, because a component `A` does not have any useful output for component `B`. However `A` must be executed before `B`.

In such a scenario, it would be useful to have the ability to define a dependency explicitly.

**Comment by jcdickinson** [comment]
Here's another workaround:

```cue
_foo: #Run & {
	input: ...
	command: {
		name: "sh"
		flags: {
			"-c": "echo 'Hello, World!'"
		}
	}
}

_requires: {
	$dagger: task: {
		_name: "Nop"
		_requires: _foo
	}
	output: _foo.output
}

output: _requires.output
```

An alternative form:

```cue
#MyTask: {
	input: #Ref

	$dagger: task: {
		_name: "Nop"
		_requires: _foo
	}

	_foo: #Run & {
		"input": input
		command: {
			name: "sh"
			flags: {
				"-c": "echo 'Hello, World!'"
			}
		}
	}

	output: _foo.output
}
```

**Comment by samalba** [comment]
Closing in favor of #4205
