### ISSUE TITLE
Programatically control the execution flow

### ISSUE THREAD

**Issue by samalba** [dagger/dagger#989]
Currently in dagger, there is no way to influence the way each pipeline is run. They either all works the first time or the whole plan (i.e. `dagger up`) fails.

We need a way to have more control on the pipelines execution. It should be possible to:

- Declaring a task in a way that it's expected to fail (eg. useful for negative unit tests, expected to fail in some cases)
- Declaring a behavior for retry (eg. a task to retry every 1 second during 10 seconds total)
- Trigger another task only if a previous one fail

**Comment by jpadams** [comment]
Mentioned by a user today:

> Is there a way to catch a failed action and if so do another action (like the discord one)

note: example of catching a failed action and firing an action to post to discord

**Comment by batleforc** [comment]
The actual interest of my demand was to implement a more complex pipeline.
Here is what I want.
![image](https://user-images.githubusercontent.com/24699592/167306962-45ef3bf5-db5c-459d-a28b-e6f445b70c41.png)

**Comment by slumbering** [comment]
Close this one. Feel free to reopen it.
